### ISSUE TITLE
GBMV/ Medizinische Diagnostik - Befundeingang vom Labor automatisch in Ornella übernehmen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#102]
Nachdem, die Diagnostik im Labor abgeschlossen wurde, soll der Befund automatisch von der "Labordatenbank" in Ornella zum zugehörigen Spender geuploadet werden.

**Comment by Toelk-A** [comment]
Folgender Ablauf soll in Ornella programmiert werden:

1) Online **Untersuchungsauftrag** ans Labor. Dieser Untersuchungsauftrag muss noch programmiert werden:

[OG Untersuchungsantrag GBM-V.pdf](https://github.com/chrbusch/GTM-V/files/1453737/OG.Untersuchungsantrag.GBM-V.pdf)

[KVG Untersuchungsantrag GBM-V.pdf](https://github.com/chrbusch/GTM-V/files/1453739/KVG.Untersuchungsantrag.GBM-V.pdf)


2) Nach Eingang des Untersuchungsauftrages im Labor vergibt das **Labor** eine **"Patientennummer"**. Diese Patiententennummer soll mit dem zugehörigen Untersuchungsauftrag in Ornella **verknüpft** werden.

3) **Befundeingang** aus Labor in Ornella:

3A) Zuordnung Befund mittels "Patientennummer Labor" zum gestellten Untersuchungsauftrag

3B) Abgleich dieser Zuordnung durch eine menschliche Person - Mitarbeiter der GBM-V und Label mit  "korrekt zugeordnet" markiert werden können (ähnlich der Freigabe durch Ärztliches Personal im Spendebereich).

![image](https://user-images.githubusercontent.com/22314271/32546768-69d6a050-c480-11e7-9628-dedc9851d769.png)

3C) Automatische Übernahme der Befundergebnisse zum Untersuchungsauftrag

**Comment by chrbusch** [comment]
Soll hieran zur Zeit weiter gearbeitet werden?

**Comment by Toelk-A** [comment]
Nein, erstmal nicht
