### ISSUE TITLE
Prozessschritt körperliche Untersuchung - bitte Mehrfachoptionen einfügen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#103]
Im Abschnitt "anatomische Angaben" bitte Mehrfachoptionen hinzufügen. z.B kann ein Patient sowohl Tattoos als auch Wunden besitzen.

![image](https://cloud.githubusercontent.com/assets/22314271/22295271/a93457f2-e316-11e6-9c41-d29c5457c477.png)

**Comment by Toelk-A** [comment]
Wenn die PDF Ausgabe den "Punkt" in "Anatomische Angaben" verschwinden lässt, ist das Thema ebenfalls erledigt und kann geschlossen werden.

**Comment by chrbusch** [comment]
Das Script oben im Menü, "5/Ausgabe als PDF" löscht jetzt die Markierung; und nur so drucken Sie doch, oder?!

**Comment by Toelk-A** [comment]
ja

**Comment by chrbusch** [comment]
Dann ist dies erl.?
