### ISSUE TITLE
Unterschriftenpad mit Ornella verbinden

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#104]
Wir möchten die Dokumente in Ornella digital unterschreiben können. Insbesondere ist dies für die Entnahmeberichte wichtig, da diese immer dem entnommenen Gewebe beim Transport beigelegt werden müssen. 

Wie hoch wäre der Aufwand ein solches "digitales Unterschriftenfeld" in Ornella zu programmieren?

Was wären die technischen Voraussetzungen?

**Comment by chrbusch** [comment]
Ich muss genau verstehen, wozu Sie das nutzen wollen.
Man kann Unterschriften als Bild abspeichern und bei Bedarf unter ein Dokument setzen; dann sieht es unterschrieben aus, ist es aber nicht im juristischen Sinne weil unklar ist, wer das Bild eingesetzt hat.
Man könnte aber auch eine genehmigte Prozedur für eine elektronische Signatur verwenden, bei der ein Arzt/AAP ein bestimmtes Passwort eintippen muss, um ein Dokument zu signieren. All das ist einfacher und v.a. billiger als die Integration von Unterschriften-Pads.
Oder warum genau möchten Sie solche Geräte einbinden? Was ist der Zweck, der erreicht werden soll?

**Comment by Toelk-A** [comment]
Da wir in Zukunft mehrere Standorte (ca 500km entfernt von Rostock)  haben werden, müssen die Spenderakten mittels elektronischer Unterschrift durch das ärztliche Personal freigegeben werden. Das bedeutet wir benötigen ein "Containerfeld" in das mittels IPAD eine digitale Unterschrift gesetzt werden kann. Ein IPAD haben wir bereist auf dem auch Ornella funktioniert.

Alle Dokumente im Reiter Prozessschritte, die durch das ärztliche Personal unterschrieben werden müssen, benötigen ein solches Containerfeld.

Bitte geben Sie uns Rückmeldung welche technischen Voraussetzungen wir zusätzlich benötigen und wie schnell das Ganze programmiert werden könnte.

**Comment by chrbusch** [comment]
Mit elektronischer Unterschrift kenne ich mich nicht aus, hier muss ich recherchieren; dies kann ich vor meinem Urlaub leider nicht mehr angehen.

**Comment by chrbusch** [comment]
"Ein IPAD haben wir bereist auf dem auch Ornella funktioniert."

**AUF KEINEN FALL darf das Programm mit einem iPad geöffnet werden**, das Startscript verhindert dies nun auch. Auf iPad laufen die sog. "Plugins" nicht, weshalb massiver Datenverlust droht!
Wir können aber ohne sehr großen Aufwand eine Extradatei für das iPad erstellen, die keine Plugins benötigt und mit Ornella bidirektional kommuniziert.

**Comment by Toelk-A** [comment]
Die Unterschriften sind eingescannt und abgespeichert. Möchten Sie dieser per Mail erhalten?

**Comment by chrbusch** [comment]
ich habe neulich beschrieben, wie Sie die US selbst integrieren können.
Ggfs. morgen am Tel. mit besprechen, ist ganz einfach
