### ISSUE TITLE
Warenkörbe

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#105]
Um die PDFs vollständig freigeben zu können, müssen wir das "Warenkorbsystem etablieren". 

Wie ist der derzeitige Stand?

Ich hatte bereits die Warenkörbe in Ornella zusammengestellt. Können wir diese nun scannen und unseren eigenen Barcode für die Warenkörbe erstellen?

Falls ich weitere Zuarbeit leisten soll geben Sie mir bitte Bescheid.

**Comment by Toelk-A** [comment]
Die hinterlegten Adressen in der Spalte "Lieferanteninfos" -Artikelliste" scheinen falsch verknüpft zu sein.
 z.B. hat Hersteller "greiner bio one" nichts mit der "Innere 2" zu tun. "Innere 2 " entspricht einer Station (Subadresse Krankenhaus).

![image](https://cloud.githubusercontent.com/assets/22314271/24200639/fec4a0e6-0f0d-11e7-8de2-6f251106160c.png)

**Comment by chrbusch** [comment]
Richtig! Da war ein falscher Verweis, ist repariert

**Comment by Toelk-A** [comment]
Um die PDFs vollständig freigeben zu können, müssen wir das "Warenkorbsystem etablieren".

Wie ist der derzeitige Stand?

Ich hatte bereits die Warenkörbe in Ornella zusammengestellt. Können wir diese nun scannen und unseren eigenen Barcode für die Warenkörbe erstellen?

Falls ich weitere Zuarbeit leisten soll geben Sie mir bitte Bescheid.

Wir können den Warenkorb morgen telefonisch bearbeiten.

**Comment by chrbusch** [comment]
Welches sind jetzt konkret die offenen Aufgaben? Ich sehe die folgenden Dinge:
Neuer Button, um für den Warenkorb zwei Aufkleber mit Barcode zu drucken. Einer davon wird  außen auf den Korb geklebt, der andere hineingelegt. 
Bei der Entnahme wird der Aufkleber auf den Entnahmebericht geklebt

Welche Information soll auf den Aufkleber? Meines Erachtens:
Die ID des Warenkorbes als Barcode
Die ID menschen-lesbar im Klartext, dazu die Bezeichnung wie in "Entnahme OG" sowie das früheste Verfallsdatum der enthaltenen Artikel

Habe ich da noch etwas übersehen, oder wäre das der nächste Schritt?
