### ISSUE TITLE
!!! PDF Dokumente im Bereich Spende: Untersuchungsantrag GTM-V !!!

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#106]
Wenn wir >1 Gewebebart entnommen haben, benötigen wir trotzdem nur 1 Untersuchungsantrag für alle Gewebe. In diesem müssen dann alle Parameter z.B. für OG und MSG und KVG abgebildet sein.

Vielleicht könnte man beim öffnen des Untersuchungsantrages einfach fragen: 

Parameter für z.B. OG und MSG oder OG, MSG und KVG holen?

Ist dies im Rahmen der Spende PDFs umsetzbar?

**Comment by chrbusch** [comment]
Es erfolgt jetzt ein entspr. Dialog, bitte testen

**Comment by Toelk-A** [comment]
funktioniert, super

**Comment by chrbusch** [comment]
Nach Dialogantwort "Alle Params" kommt diese Auswahl, ist das richtig so?

![Uploading Bildschirmfoto 2017-01-26 um 15.59.47.JPG…]()

**Comment by Toelk-A** [comment]
Hier würde ich mich am Montag nocheinmal zu melden.

Z.B. untersuchen wir nie den Parameter CMV-IgM- dieser könnte entfernt werden


Wäre es generell möglich Ankreuzfelder für die Parameter zu erstellen und je nach Gewebe, die notwendigen "Kreuze" zu laden? 

Bei postmortalem Blut benötigen wir nämlich zusätzlich noch 2 weitere Parameter.
