### ISSUE TITLE
PDF - Checkliste Freigabe Archivierung Spenderakte 

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#109]
Siehe Excel "PDF Mängel Ornella vollständig"

1) Bitte die dort genannte Reihenfolge einhalten.

2) Es fehlt die Spalte "Donor information Form"

3) Spalte "Qualität und Raum" gehört dort nicht hin.

4) "Medizinische Indikationsprüfung" ist doppelt vorhanden

**Comment by chrbusch** [comment]
Ich brauche IMMER die Spender-ID, sonst kann ich nichts prüfen

**Comment by chrbusch** [comment]
Alles erl.
