### ISSUE TITLE
Fenstergröße

### ISSUE THREAD

**Issue by chrbusch** [chrbusch/GTM-V#11]
Wie groß soll das System die Fenster einstellen - immer maximieren auf Schirmgröße?

Was sind die (in PIXEL, nicht in Zoll) kleinsten Monitore, auf denen Sie das System betreiben möchten?

**Comment by Toelk-A** [comment]
Hallo Herr Dr. Busch,

unsere kleinste Monitorgröße: 1366 x768

**Comment by Nitschke-FP** [comment]
Layout Spendenmeldung bzw. Ausdruck:
Das Datenfeld Kennnummern-andere bitte umbenennen in Eurocode SKS (SKS=Spenderkennnummersequenz). Die Daten generieren sich aus verschiedenen Datenfeldern der Einrichtung GTM-V (Länderkennung und Institutionsnummer) und der Ziffernfolge des Meldedatums, der Meldezeit und den Buchstaben des Koordinatorenkürzels. Insgesamt sind es 23 Zeichen. Aus dieser Zeichenfolge soll ein Barcode erstellt werden, der auf dem pdf mit angezeigt wird und in den folgenden Prozessen zu Scannen genutzt werden kann.

**Comment by chrbusch** [comment]
Bitte nie Themen mischen!
DIES ist der Thread zur Fenstergröße, nichts anderes darf hier rein.
Für die KennNummern hab eich einen eigenen Thread eröffnet und Ihren Beitrag dort hinein gesetzt

**Comment by chrbusch** [comment]
Ich bin der Meinung, dass wir uns nicht auf diese Minigröße reduzieren sollten; eher die Frsge klären, welche Masken unterwegs auf den Laptops oft benötigt werden und diese doppelt anlegen, in groß+klein?
Können wir kommende Woche klären

**Comment by chrbusch** [comment]
Wir besprachen am 11.10.16, dass die Maskengröße zunächst unverändert bleibt; bei einem Test von cbu mit A.Tölk via TeamViewer soll aber demnächst das System auf den üblichen kleinen Laptops gemeinsam angesehen werden.
