### ISSUE TITLE
PDF - Standardfußzeile QC bitte bei allen PDFs einfügen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#110]
Die Standardfußzeile habe ich in Ornella eingetragen. Bitte auf allen Dokumenten nachtragen

**Comment by chrbusch** [comment]
Passier das nicht beim Drucken automatisch?
So hatte ich es zumindest eingerichtet, bitte testen

**Comment by Toelk-A** [comment]
nein funktioniert nicht, bei keinem Dokument

**Comment by chrbusch** [comment]
Wir haben das korrigiert und erfolgreich getestet; wenn es AB JETZT nicht klappt, bitte das PDF zu uns
