### ISSUE TITLE
PDF Medizinische Indikationsprüfung

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#111]
1) Hier fehlen die Fußzeilen komplett inklusive Seitenangaben.

2) Rahmenproblem sende ich per Mail

**Comment by chrbusch** [comment]
Beides erledigt!!

**Comment by Toelk-A** [comment]
Seitenangaben müssen auf jeder Seite erscheinen, die QS Nummer ebenfalls.
Bitte bearbeiten


[MedizIndikPruefung_240117-0605-GNO-TOA_170131_134456.pdf](https://github.com/chrbusch/GTM-V/files/741962/MedizIndikPruefung_240117-0605-GNO-TOA_170131_134456.pdf)

**Comment by chrbusch** [comment]
Gemeinsam erl.!

**Comment by chrbusch** [comment]
Ist jetzt OK, oder?
