### ISSUE TITLE
Entnahmebericht OG

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#112]
3. Seite Unterschrift darf nur vom ärztlichen Personal sein.

Bei ID  1293 und 1382 stand mein Name drin.

![github](https://cloud.githubusercontent.com/assets/22314271/22464915/77111538-e7b9-11e6-89b8-4be69fba94bc.png)

**Comment by chrbusch** [comment]
Ich denke, Ihr Name wurde eingetragen, BEVOR wir dies Feld kontrolliert haben; wenn man heute auf den AuswahlButton klickt, kommen nur die Ärzte
