### ISSUE TITLE
Reiter "Blutproben" - genereller Bezug auf alle Spendermeldungen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#113]
Die Plausibilität zur Einhaltung der sieben Tage für Blutproben darf sich nicht auf den Tag der Eintragung sondern auf den Todestag beziehen.

**Comment by chrbusch** [comment]
Ist jetzt so, WENN der Spender tot ist; ansonsten 14 Tage zurück ab heute.
Ist das gut so?

**Comment by Toelk-A** [comment]
Die Blutproben dürfen isngesamt nicht älter (inklusive) als 7 Tage sein

**Comment by chrbusch** [comment]
Wenn der Spender tot ist prüfe ich DatumAbnahme gg. Todesdatum, OK?
Wenn der Spender nicht tot ist -  prüfe ich DatumAbnahme gg. was?

**Comment by Toelk-A** [comment]
1) ok
2) gegen Entnahmezeitpunkt Gewebe (Entnahmeprotokoll) aktuelles Datum, Zeitspanne muss ebenfalls kleiner/gleich 7 Tage sein.
