### ISSUE TITLE
Abrechnungen for Gewebeentnahmen m.d. meld. Einrichtg.

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#114]
Hinsichtlich der Abrechnung stellen wir uns folgendes System vor:

Die Rechnung soll alle Entnahmen des Vormonats individualisiert pro Masteradresse beinhalten. Hierbei müssen folgende Gewebe unterscheiden werden:

1) OG-Entnahme:

- Regel: Nur wenn im Entnahmebericht OG die Entnahmezeit und der Entnehmer/Koordinator eingetragen sind, fand eine OG Entnahme statt und diese Entnahme darf in die Rechnung aufgenommen werden
- die meldende Einrichtung (in Spendermeldung dokumentiert) wird mit 50,-Euro pro Entnahme entlohnt 
- Als Rechnungsadresse gilt die Masteradresse mit der Abteilung "Controlling" ( bis jetzt gibt es nur eine Rechnungsadresse für Boddenkliniken Ribnitz Damgarten).

2) MSG oder KVG oder MSG und KVG

- Regel: Nur wenn im Entnahmebericht MSG/KVG die Entnahmezeit und der Entnehmer/Koordinator eingetragen sind, fand eine MSG/KVG Entnahme statt und diese Entnahme darf in die Rechnung aufgenommen werden
- der Entnahmeort (im Entnahmebericht dokumentiert) entspricht der Masteradresse (Klinik) der 200,-Euro pro Spender (egal ob MSG oder KVG oder beides) bezahlt werden
- Als Rechnungsadresse gilt die Masteradresse mit der Abteilung "Controlling" ( bis jetzt gibt es nur eine Rechnungsadresse für Boddenkliniken Ribnitz Damgarten)

Bei Fragen rufen Sie mich bitte an

**Comment by chrbusch** [comment]
Ich denke, dies ist alles os umgesetzt; andernfalls bitte konkretes Beispiel nenne, wo es nicht funktioniert
