### ISSUE TITLE
PDF Dokumente Bereich Spende - Medizinische Indikationsprüfung - Rahmenproblem

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#115]
Bitte den Rahmen auf den Seiten 5 und 6 anpassen

[Rahmenproblem_ MedizIndikPruefung_240117-0605-GNO-TOA_170203_163629.pdf](https://github.com/chrbusch/GTM-V/files/750901/Rahmenproblem_.MedizIndikPruefung_240117-0605-GNO-TOA_170203_163629.pdf)

**Comment by chrbusch** [comment]
Erledigt
