### ISSUE TITLE
PDF Dokumente Bereich Spende - Untersuchungsantrag - Überschrift + 1. Seite 

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#116]
1) 2. Seite im PDF ist leer - bitte entfernen

2) Bitte das Wort 

[Untersuchungsantrag_240117-0605-GNO-TOA_170203_164115.pdf](https://github.com/chrbusch/GTM-V/files/750907/Untersuchungsantrag_240117-0605-GNO-TOA_170203_164115.pdf)
"OG" in Überschrift entfernen

**Comment by chrbusch** [comment]
Das ist bei NEUEN Geweben schon seit 2 Tagen umgesetzt., bitte mit Testspender tsten

**Comment by Toelk-A** [comment]
ID 1361

hier steht auch immernoch "OG" in der Überschrift

![image](https://cloud.githubusercontent.com/assets/22314271/22638578/393cce52-ec49-11e6-941d-1d6706f1426f.png)

**Comment by chrbusch** [comment]
...der Prozessschritt ist auch vor 5 Tagen angelegt, vor der Änderung. Ich habe jetzt aber auch alle ALTEN Dokum.-Titel der Unters.Anträge entspr. bereinigt

**Comment by Toelk-A** [comment]
Danke funktioniert
