### ISSUE TITLE
PDF Dokumente Bereich Spende - Freigabe Archivierung Spenderakte - siehe Excel

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#117]
Bitte noch die Nachbearbeitung wie in Excel beschrieben durchführen

[FreigabeArchivgSpdAkte_240117-0605-GNO-TOA_170203_164520.pdf](https://github.com/chrbusch/GTM-V/files/750918/FreigabeArchivgSpdAkte_240117-0605-GNO-TOA_170203_164520.pdf)

**Comment by Toelk-A** [comment]
Hier wurde auch noch nichts geändert.

**Comment by chrbusch** [comment]
Ich denke, dass das alles OK ist bei NEU ANGELEGTEN Datensätzen.
Bitte diesbezgl. testen.

cbu

**Comment by Toelk-A** [comment]
Für unser QM benötigen wir alle "neuen" Änderungen auch beim Spender ID 1394. Das QM muss eine handschriftlich verfasste Akte mit einer digitalisierten Akte abgleichen um die PDFs freigeben zu können.
DANKE

**Comment by Toelk-A** [comment]
![image](https://cloud.githubusercontent.com/assets/22314271/22643344/4ee03158-ec5e-11e6-8ca3-7dba3c98f938.png)

**Comment by Toelk-A** [comment]
Dr Busch bitte unbedingt bearbeiten, sonst können die PDFs noch nicht freigegeben werden

**Comment by chrbusch** [comment]
Fehlt dort jetzt nur die "Freigabe Archiv...g"?
Bitte anrufen und genau erklären, was ich tun soll

**Comment by chrbusch** [comment]
Die beiden getrennten Teil für postmortal und Lebendspende sind jetzt eingerichtet

**Comment by chrbusch** [comment]
Es werden jetzt immer alle Gewebearten angezeigt. Der rote Hinweis wird nicht mit gedruckt

![bildschirmfoto 2017-02-10 um 14 08 05](https://cloud.githubusercontent.com/assets/1241899/22827905/824388ee-ef9a-11e6-8f8c-145800bb21a0.JPG)

**Comment by Toelk-A** [comment]
Bitte rufen Sie mich an es gibt noch kleine Änderungen. Danke

**Comment by Toelk-A** [comment]
ID 1361 // ID 1509

Es fehlen "ja und Nein" bei Freigabe  im PDF

![image](https://cloud.githubusercontent.com/assets/22314271/22927443/8e6d8920-f2b1-11e6-9d6b-3778bf785c70.png)

**Comment by chrbusch** [comment]
Mit Dr. N ist besprochen. dass die Freigabefelder nur erscheinen, wenn Entnahme=Ja!
