### ISSUE TITLE
PDF Dokumente Bereich Spende - Entnahmeberichte

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#118]
Bitte in der Fußzeile die Formularnummern einfügen

[Entnahmebericht_240117-0605-GNO-TOA_170203_165016.pdf](https://github.com/chrbusch/GTM-V/files/750935/Entnahmebericht_240117-0605-GNO-TOA_170203_165016.pdf)

**Comment by chrbusch** [comment]
Habe ich gerade getestet, hat alles geklappt!

**Comment by Toelk-A** [comment]
nach wie vor nicht vorhanden

![image](https://cloud.githubusercontent.com/assets/22314271/22638456/7a8558a8-ec48-11e6-94f9-f26122b5670f.png)

**Comment by Toelk-A** [comment]
ID1394

**Comment by chrbusch** [comment]
Wie soeben am Telefon besprochen sollte das jetzt ok sein.
