### ISSUE TITLE
PDF Dokumente Bereich Spende - Transportbegleitschein

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#119]
Bitte im Adressfeld "Gewebebank" die GBM-V Adresse löschen. Dieses Feld muss manuell von uns ausgefüllt werden können bzw. mit in der Datenbank hinterlegten Adressen.

[Transportbegleitschein_240117-0605-GNO-TOA_170203_164252.pdf](https://github.com/chrbusch/GTM-V/files/750945/Transportbegleitschein_240117-0605-GNO-TOA_170203_164252.pdf)

**Comment by chrbusch** [comment]
Ich kann hier keinen Fehler finden; Anklicken des Adressenfeldes zeigt den üblichen Adressenauswahldialog, Sie können dort eine bel. Adresse einsetzen; dies habe ich gerade erfolgreich ausprobiert

![bildschirmfoto 2017-02-03 um 20 42 24](https://cloud.githubusercontent.com/assets/1241899/22605721/6c8f73e4-ea51-11e6-9344-942501fe2521.JPG)

![bildschirmfoto 2017-02-03 um 20 42 42](https://cloud.githubusercontent.com/assets/1241899/22605725/710ec186-ea51-11e6-88a3-e27070560135.JPG)
