### ISSUE TITLE
SKS - Barcode in Transportetiketten hinterlegen

### ISSUE THREAD

**Issue by chrbusch** [chrbusch/GTM-V#12]
Layout Spendenmeldung bzw. Ausdruck:
Das Datenfeld Kennnummern-andere bitte umbenennen in Eurocode SKS (SKS=Spenderkennnummersequenz). Die Daten generieren sich aus verschiedenen Datenfeldern der Einrichtung GTM-V (Länderkennung und Institutionsnummer) und der Ziffernfolge des Meldedatums, der Meldezeit und den Buchstaben des Koordinatorenkürzels. Insgesamt sind es 23 Zeichen. Aus dieser Zeichenfolge soll ein Barcode erstellt werden, der auf dem pdf mit angezeigt wird und in den folgenden Prozessen zu Scannen genutzt werden kann.

**Comment by chrbusch** [comment]
Wie lautet die exakte Regel für diese Nr, am besten mit konkretem Beispiel?

**Comment by chrbusch** [comment]
Bitte mit Ihren IT-Beratern klären: Welche Barcode-Art ist kompatible zu allen Ihren Computer und Scannern? 
Die entsprechende Barcode-Schrift dann bitte zu mir senden, samt einem Scanner (den Sie später zurück bekommen)

**Comment by chrbusch** [comment]
Es wird nun voraussichtlich das Tool "Barcode Creator" gekauft, mit dem man praktisch alle Arten von Barcodes generieren kann, und auch QR-Codes.
NIF wird am 111016 einen Scanner mit nach HH bringen

**Comment by Toelk-A** [comment]
Bitte den SKS-Code als 2D-Format auf den Transportetiketten: MSG, Blut und OG hinterlegen. 
Weiterhin soll auf den MSG-Etiketten die "Spenderkennummer" mit der SKS Nummer ersetzt werden.

**Comment by chrbusch** [comment]
Transp.Etiketten zeigen nun den SKS_Eurocode, bitte drucken&Scannen testen

**Comment by Toelk-A** [comment]
Funktioniert super.
