### ISSUE TITLE
Reiter "Dokumentenablage"

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#120]
Bitte als Auswahl

"Obduktionsbefund"
und
"Notizen Spende"

Hinzufügen

![image](https://cloud.githubusercontent.com/assets/22314271/22686485/95920678-ed24-11e6-87d8-d0f7cc64e78c.png)

**Comment by chrbusch** [comment]
erl.

**Comment by Toelk-A** [comment]
Hier bitte noch "Freigabe MSG" einfügen

![image](https://cloud.githubusercontent.com/assets/22314271/22821293/b7dcaf32-ef7a-11e6-85f2-0612befb6207.png)

Hier bitte noch "DIZG" einfügen

![image](https://cloud.githubusercontent.com/assets/22314271/22821332/da6f75a2-ef7a-11e6-8c0c-da942b227c6e.png)

**Comment by chrbusch** [comment]
Erl.
