### ISSUE TITLE
Spendermeldung PDF - Titel von Barcode überdruckt

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#121]
ID1481

![image](https://cloud.githubusercontent.com/assets/22314271/22690525/80b16796-ed36-11e6-82ab-1a5bd6a13603.png)

**Comment by Toelk-A** [comment]
auch hier tritt wieder das Überschriftenproblem auf

**Comment by chrbusch** [comment]
besser?

![bildschirmfoto 2017-02-07 um 14 14 41](https://cloud.githubusercontent.com/assets/1241899/22692544/ce834d0a-ed3f-11e6-9578-794ea690344e.JPG)

**Comment by chrbusch** [comment]
erl.
