### ISSUE TITLE
Reiter Blutproben- Eingabe Blutprobe Fehlermeldung

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#122]
Die Blutprobe ist vom 06.02.2017
folgender Fehler taucht hier auf:

![image](https://cloud.githubusercontent.com/assets/22314271/22776493/1a47c9f2-eeb0-11e6-8f4d-d2dedfbe4af7.png)

**Comment by Toelk-A** [comment]
selber Fehler hier
Blutprobe vom 07.02.2017
![image](https://cloud.githubusercontent.com/assets/22314271/22776609/9552b102-eeb0-11e6-9e48-43f55c7911a4.png)

**Comment by chrbusch** [comment]
M.E. erledigt, bitte erneut testen
