### ISSUE TITLE
Entnahmebericht KVG Länge, Durchmesser proximal distal

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#124]
Je Präparat (also nicht beidseits, sondern rechts und links) müssen die Maße eintragbar sein. Außerdem dürfen die distal Werte nicht automatisch in proximal übernommen werden, sondern sollen individuell sein.

ID 1394

![image](https://cloud.githubusercontent.com/assets/22314271/22783855/e524dfc6-eecd-11e6-86d8-3247ad9bbf95.png)

**Comment by chrbusch** [comment]
Dass pro. und distale Werte nicht getrennt erfassen liessen, beruhte auf einem nun korrigierten Fehler.
Für die D/S-Unterscheidung hab eich gerade mit Dr. N. beschlossen, dass wir künftig die Seiten stets als getrennte Präparate erfassen.
