### ISSUE TITLE
Etikettendruck MSG

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#126]
ID 1504

Knochen Etiketten werden pro Seite 3x ausgegeben zb Tibia rechts (3x) und Tibia links (3x) wir benötigen jedoch nur 2 Etiketten pro Seite bitte ändern

**Comment by Toelk-A** [comment]
bitte auch bei den Sehnen prüfen

**Comment by chrbusch** [comment]
Ich denke, ich habe es gefunden, bitte testen
