### ISSUE TITLE
Prozessschritt körperliche Untersuchung - Unterschriftenfeld

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#128]
Im Unterschriftenfeld darf nur das ärztliche Prüfpersonal also NIF und MAA erscheinen. Bitte ändern

**Comment by chrbusch** [comment]
Erledigt

**Comment by chrbusch** [comment]
![bildschirmfoto 2017-02-20 um 10 32 26](https://cloud.githubusercontent.com/assets/1241899/23119279/e48bf76a-f757-11e6-87b0-b27a1906d61e.JPG)
