### ISSUE TITLE
PDF Transportbegleitschein

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#129]
Wenn in der Spendermeldung keine Angaben in den Feldern "Kühlung des Leichnams" eingetragen sind

![image](https://cloud.githubusercontent.com/assets/22314271/22922954/e7eed22c-f29f-11e6-98e9-f746b2ba90d3.png)

so muss auf dem Transportbegleitschein Abschnitt "Transportdaten" - "Kühlung des Leichnams" ein "Nein" erscheinen.

![image](https://cloud.githubusercontent.com/assets/22314271/22923049/3706d102-f2a0-11e6-9e1b-d8c041bae082.png)

Falls dies zu kompliziert zu programmieren ist könnte man hier auch einfach ein Dropdown erstellen.

**Comment by chrbusch** [comment]
Etwa so?

![bildschirmfoto 2017-02-15 um 16 10 35](https://cloud.githubusercontent.com/assets/1241899/22980340/67bf5d74-f399-11e6-9c1b-eb59d8689d88.JPG)
![bildschirmfoto 2017-02-15 um 16 10 42](https://cloud.githubusercontent.com/assets/1241899/22980341/682fca5a-f399-11e6-9c34-2427055abf16.JPG)
