### ISSUE TITLE
Hämodilution

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#131]
ID 1528

Datum und Entnahmezeitpunkt  (14.02.2017 20:11) werden nicht automatisch übernommen

![image](https://cloud.githubusercontent.com/assets/22314271/23061456/356bc5d2-f502-11e6-896f-ae29df681dd9.png)

**Comment by chrbusch** [comment]
Ich muss immer wissen: Welchen Button haben Sie zuletzt geklickt?
(Hinter jedem Button steckt ein "Script", und in diesem muss ich nach Fehlern suchen)
War es der Button <Hämodil.> auf dem Reiter mit den Blutproben?

**Comment by chrbusch** [comment]
..ausserdem fehlt das Datum nur bei dieser _einen_ Blutprobe; das hat vermutlich dann eher technische Ursache wie eine Netzwerkstörung.
