### ISSUE TITLE
Untersuchungsauftrag - kleine Änderungen im Aufbau

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#133]
1)  Feld "Aufnahmenummer" bitte löschen

![image](https://cloud.githubusercontent.com/assets/22314271/23205131/13d6e1fa-f8e9-11e6-98f2-6532da82d605.png)

2) Feld "Datum und Uhrzeit Probennahme" bitte löschen

![image](https://cloud.githubusercontent.com/assets/22314271/23205327/c0d8c6d4-f8e9-11e6-95aa-b1b33258e804.png)

3) Feld "Datum und Uhrzeit Probenübergabe": nur "Datumsfeld"notwendig, "Uhrzeitenfeld" löschen

![image](https://cloud.githubusercontent.com/assets/22314271/23205420/1bdc344e-f8ea-11e6-9684-fb587c22d22d.png)

4) bitte hier zweites Datumsfeld einfügen: "Vorraussichtliches Datum Laboreingang"

![image](https://cloud.githubusercontent.com/assets/22314271/23205437/2787d26c-f8ea-11e6-900a-c91bbe6d5de4.png)

**Comment by chrbusch** [comment]
Erl.

**Comment by Toelk-A** [comment]
Bitte Problem lösen

![image](https://cloud.githubusercontent.com/assets/22314271/23213220/5fffb194-f90a-11e6-87ec-7d1548684118.png)

**Comment by chrbusch** [comment]
fixed
