### ISSUE TITLE
Preise für Transplantate

### ISSUE THREAD

**Issue by chrbusch** [chrbusch/GTM-V#134]
Bitte hier beschreiben, wie bei der Abrechnung der Transplantate der Preis bestimmt werden soll.
OG: Wann sind es 1900 Eur, wann nicht?
Andere Gewebe??

**Comment by Nitschke-FP** [comment]
Eine Augenhornhaut der Kategorie humane Augenhornhaut, organkultiviert, GBM-V wird den Zentren mit 1900 € in Rechnung gestellt, Stromer Patch, temporäre Hornhautersayz, human, organkultiviert, GBM-V mit 1500 €

**Comment by Nitschke-FP** [comment]
Bitte im Layout "Rechnung Eingabe" den Button Abrang. zurück setzen" aktivieren.
Alternativ die Rechnungen mit der ID 160 und 161 zurücksetzen (falsche Augenhornhaut zugeordnet!!)
