### ISSUE TITLE
Dokumentenablage-Bereich Spende

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#135]
ID 1578

beim Hochladen der Dokumente erscheinen folgende Fehler:

![image](https://cloud.githubusercontent.com/assets/22314271/23352161/df283202-fcc5-11e6-98f0-cc334e0f44c1.png)

![image](https://cloud.githubusercontent.com/assets/22314271/23352178/f799f14a-fcc5-11e6-8928-b9f57f6221a3.png)

**Comment by chrbusch** [comment]
confirmed & fixed
