### ISSUE TITLE
OG Entnahmebericht Seite 3 Freigabe ...

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#136]
In 3 Fällen kam es nun wieder vor, dass mein Name eingetragen wurde.
ID 1495
ID 1481
ID 1523

![image](https://cloud.githubusercontent.com/assets/22314271/23352752/46f0c96e-fcc9-11e6-9adc-f0d53644af48.png)

**Comment by Toelk-A** [comment]
Hier dürfen nur die Namen des ärztlichen Personals erscheinen MAA oder NIF

**Comment by chrbusch** [comment]
Bitte hierzu anrufen!

**Comment by chrbusch** [comment]
Wie tel. besprochen: Endlich verstanden und behoben!
