### ISSUE TITLE
PDF´s Hämodilution- Bitte 1 Dokument für alle angelegten Hämodilutionen erstellen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#137]
ID 1523

Bitte ein PDF Dokument für alle angelegten Hämodilutionen erzeugen. Achtung, die Seitenzahlen müssen dementsprechend angelegt werden.

**Comment by chrbusch** [comment]
Das ist erledigt, und nebenbei auch die unnötige Anlage von Hämodilutions-Datensätze für JEDE Probe.
Nun wird pro "Spender und Zeitpunkt" eine Dilution angelegt.Dies gilt AB JETZT, jedoch nicht für alte Fälle.
