### ISSUE TITLE
Button "Spenderakte drucken" bei Prozesschritten einfügen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#139]
Wir benötigen einen Button zum Ausdrucken der vollständigen Spenderakte, nachdem das ärztliche Personal (MAA, NIF) die Spenderakte freigegeben hat. Dieser Button darf für den Koordinator erst sichtbar/freigegeben werden, nachdem das ärztliche Personal (MAA, NIF) die Spenderakte(alle separaten Prozesschritte -PDF´s) freigegeben hat z.B. Prozessschritt "Freigabe Archivg. SpdAkte neu"

Im Moment müssen wir jedes PDF einzeln erstellen und ausdrucken. Für die Zukunft wäre es effizienter nur 1x den Button zu klicken und alle vollständig ausgefüllten PDFS würden automatisch erstellt und ausgedruckt werden. Man könnte diese PDF als "freigegebene Spenderakte"in der Dokumentenablage hinterlegen.

**Comment by chrbusch** [comment]
Bitte abgekürzt auflisten, welche Dokumente in welcher Reihenfolge das werden sollen, in der Art
SpdMaske
EinwillGespr.
....

**Comment by Toelk-A** [comment]
Hier die Reihenfolge der Dokumente:

1) Freigabe Archivg. SpdAkte neu
2) Checkliste Spd.
3) Untersuchungantrag
4) Spendermeldung
5) Einwill.Gespr
6) Med. Indik.
7) Hämodil.
8) Freig. Gew. Entn.
9) Körp. Untsg.
(10) wenn zutreffend Mobil Entnahmeteam)
11) Entnahmebericht OG, MSG, KVG
12) Transportbegleitschein

Achtung: einzelne Dokumente wie z.B. Spendermeldung, Untersuchungsantrag, Transportbegleitschein, Entnahmeberichte müssen ebenfalls separat ausdruckbar sein

**Comment by chrbusch** [comment]
Mache ich so - aber ich sage gleich, dass es wegen einer partiellen Amnesie in Filemaker bzgl. Druckseiten äußerst schwierig wäre, der ganzen Spenderakte durchgehende Seitenzahlen zu verpassen!
Da das Ganze ja aber EIN PDF wird, ist das m.E. nicht so dramatisch.

**Comment by Toelk-A** [comment]
ID 1624, hier ist allerdings noch keine Freigabe durch die Ärzte erfolgt

ID 1394, sollte komplett freigegeben sein

**Comment by chrbusch** [comment]
OK; Ihc bin noch nicht ganz fertig, muss jetzt zunächst etwas anderes erledigen, aber Sie können schon den neuen Button
**Spenderakte drucken**
links auf der Spendermaske testen.

**Comment by chrbusch** [comment]
Bitte nun kritisch testen! Ich denke, dass alle erforderlichen Seiten und nur diese gedruckt werden.
Ansonsten bitte fehlerhafte PDF per Email zu mir

**Comment by Toelk-A** [comment]
ID 1568
Seite 23 "Entnahmbericht alle Gewebe" -> brauchen wir nicht, gehört nicht zum Spender
Seite 27 Transportbegleitschein (Bereich Spende) doppelt angelegt -> bitte löschen
Seite 22 Adresse von Dr Nitschke ist verdeckt - bitte ändern

[Spenderakte_1568_170310144148 neu.pdf](https://github.com/chrbusch/GTM-V/files/834078/Spenderakte_1568_170310144148.neu.pdf)

**Comment by Toelk-A** [comment]
Bitte den Button **"Spenderakte drucken"** erst freigeben, wenn ärztliches Personal "unterschrieben" hat -> dies gilt ins besondere für Prozessschritt "Freigabe Archivierung Spenderakte" ... das entnommene Gewebe soll nur durch das ärztliche Personal als freigegeben "ja" oder "nein" markierbar sein, erst danach darf es möglich sein die Spenderakte komplett auszudrucken

**Comment by Toelk-A** [comment]
"Entnahmebericht (alle Gewebe)" - Bitte PDF Überschriften entsprechen der spezifischen Entnahmeberichte (OG oder MSG oder KVG) anpassen.

**Comment by chrbusch** [comment]
Bitte für das letztgenannte Probleme eine konkrete SpenderID nennen, und am besten das große PDF per Email zu mir

**Comment by Toelk-A** [comment]
z.B: ID 1628

**Comment by chrbusch** [comment]
Entnhamebericht jetzt korrekt betitelt
