### ISSUE TITLE
Barcode und QR-Code

### ISSUE THREAD

**Issue by chrbusch** [chrbusch/GTM-V#14]
Lagerung bei -180 Grad: Meine anderen Kunden lagern nur bei -40 C, daher sind deren Etiketten nicht für uns brauchbar.

Bitte allen mit Codes zu bedruckenden Medien mit uns besprechen; wir suchen dann einen geeigneten DYMO-Drucker dafür aus und schlagen Ihnen diesen zum Kauf vor.
Wie groß sollen die gedruckten Barcode-Etiketten sein?
Je größer, desto einfacher ist das Scannen....

**Comment by Toelk-A** [comment]
anbei eine Übersicht der von uns benötigten Etiketten

[Übersicht Etiketten_09 11 2016.xlsx](https://github.com/chrbusch/GTM-V/files/580680/Ubersicht.Etiketten_09.11.2016.xlsx)

**Comment by Toelk-A** [comment]
nach erneuter Rücksprache ist Thema jetzt erledigt, wir benötigen keinen Dymodrucker mehr
