### ISSUE TITLE
Mobiles Entnahmeteam PDF- kleine Schreibkorrekturen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#140]
1) Bitte Überschrift ändern - "anlegen" löschen, Rest bleibt

![image](https://cloud.githubusercontent.com/assets/22314271/23750891/44d29ec4-04cf-11e7-8cd0-bd3824924b8b.png)

2) Muskuloskelettales Gewebe bitte zu "tt" korrigieren

![image](https://cloud.githubusercontent.com/assets/22314271/23750941/7a20a95e-04cf-11e7-98c6-cd62e894badc.png)

**Comment by chrbusch** [comment]
erledigt
