### ISSUE TITLE
Ornella - GBM-V - Spd Transplantat

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#141]
Bitte noch "Glaskörperabstrich" in Werteliste einfügen -> folgen sollen die selben Auswahlmöglichkeiten wie beim "Bindehautabstrich"

![image](https://cloud.githubusercontent.com/assets/22314271/23794507/ac2e7b44-0590-11e7-8526-5cca3e7851a5.png)

**Comment by chrbusch** [comment]
Erl.
