### ISSUE TITLE
Transportetiketten - Kleinschreibung "rechts" "links"

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#144]
Bitte die Kleinschreibung bei "rechts" und "links" auf den Transportetiketten korrigieren.
Danke

**Comment by chrbusch** [comment]
Bin nich tsicher, was hier getan werden sollte: "rechts" und "links" schreiben?

**Comment by Toelk-A** [comment]
Im Moment werden "rechts" und "links" in Großbuchstaben geschrieben, bitte um Kleinschreibung

**Comment by Toelk-A** [comment]
erledigt
