### ISSUE TITLE
Allokation

### ISSUE THREAD

**Issue by Nitschke-FP** [chrbusch/GTM-V#146]
Bitte beim Aufrufen des Layouts "Liste der Gewebeanforderungen" die Spalte "Kl. Wunsch-Dt" immer aufsteigend sortieren

**Comment by Nitschke-FP** [comment]
wird im Layout "Transplantat-Auswahl+Allokation" ein Patient der Anforderung zugeordnet und eine allokierte Augenhornhaut wird deallokiert, so wird auch der Patient aus der Anforderung entfernt.
Dieses bitte abstellen. Wenn eine Deallokation notwendig wird und auch der Patient entfernt werden soll auf der Anforderung, kann man dieses über den Anforderungsstatus "Storno" umsetzen?
Wenn dieses so umsetzbar ist, wie kann ich erkennen, dass Patienten im System erfasst sind, die keiner Anforderung zugeordnet sind? Wie kann ich nachvollziehen, welche transplantierende Einrichtung diese einmal angemeldet hat?

**Comment by Nitschke-FP** [comment]
beim aufrufen des Layouts „Passende Transplantate (Hornhaut CSK)“ werden mir Hornhäute angeboten zur Allokation, die den Status haben „fest allokiert“ (2017-0085-GMV-CD und 2017-0085-GMV-CS)
Können Sie dieses bitte einmal prüfen.
<img width="1241" alt="bildschirmfoto 2017-03-24 um 11 26 54" src="https://cloud.githubusercontent.com/assets/22288833/24290481/6ba021b8-1085-11e7-9b1a-87637b060836.png">

**Comment by chrbusch** [comment]
KÖNNTE damit zu tun haben, dass Sie "Fest allokiert" oben angekreuzt haben :-)))

**Comment by chrbusch** [comment]
Bitte ein Ticket pro Thema!!!!

"Bitte beim Aufrufen des Layouts "Liste der Gewebeanforderungen" die Spalte "Kl. Wunsch-Dt" immer aufsteigend sortieren"

Das ist jetzt auch erl.

**Comment by Nitschke-FP** [comment]
Wir schließen jeden Donnerstag die Allokation ab, damit die Vorbereitungen der Bank für die Verschickung erfolgen können. Sinnvoll wäre hier, einen Bericht zu erstellen , der die Allovationen der nächsten Woche dokumentiert mit folgenden Daten:
Anfordernde Einrichtung
Patientenname, -vorname (sind keine Patientendaten erfasst, bitte leere Felder anzeigen)
Patientenalter
Geplantes Operationsverfahren
Klassifikation Anwendung (Kornea) (hier bitte im Dropdown "alle Anwendungen" hinzufügen
letzte Zellzahl
Voroperationen Spenderauge (dieses Feld muß noch erstellt werden im Layout OG-Transplantat Details)
Freigabe 20b vorhanden (Ja/Nein/Offen - Feldinhalt bitte aus dem Feld Entnahmebericht OG: Freigabe zur Gewebeaufbereitung entnehmen
Transplantationsdatum
Lieferdatum/-zeit
Lagerung im Transportmedium

Die Tabelle bitte sortieren nach
1. Lagerung im Transportmedium (aufsteigend)
2. Anfordernde Einrichtung

**Comment by chrbusch** [comment]
Bitte testen Sie im HM den neuen Button, im Thema Allokation

![bildschirmfoto 2017-09-11 um 12 03 29](https://user-images.githubusercontent.com/1241899/30269490-4b69ce2c-96e9-11e7-93fb-cd461d7ad0ba.JPG)
