### ISSUE TITLE
Externe Personen erfassen

### ISSUE THREAD

**Issue by chrbusch** [chrbusch/GTM-V#15]
Zu der Hierarchie 
Krankenhaus < Klinik < Abteilung < Station
gehören vermutlich i.d.R. auch am Ende eine oder mehrere Personen, zB die auf den Stationen tätigen Ärzte.
Gibt es diese als XLS-Liste?
Oder sollen die alle manuell eingepflegt werden?

**Comment by Toelk-A** [comment]
werden manuell eingepflegt

**Comment by Nitschke-FP** [comment]
Wie sollen nat. Personen manuell eingepflegt werden? In den Adressdaten kann pro jur. Person eine nat. Per. dokumentiert werden. Wie wird eine zweite dokumentiert?

**Comment by chrbusch** [comment]
Eine nat. Person legt man am besten an als Subadresse einer Station!

**Comment by Nitschke-FP** [comment]
Nun gibt es auch hat. Personen, die den übergeordneten Adressen zuzuordnen sind, z.B. Klinikdirektor der Klinik oder Medizinischer Vorstand der Masteradresse!!??

**Comment by chrbusch** [comment]
Wir müssen genau besprechen, was Sie mit diesen Adressen TUN WOLLEN.
Sie könne ja auch als Unteradresse einer Topadresse eine Person anlegen.

**Comment by Nitschke-FP** [comment]
Die Adressen sind für Berichte, die an nat. Personen in einem Krankenhaus verschickt werden sollen. Z.B. Ärztlicher Direktor und Verwaltungsdirektor, beide als hat. Person unter der Musteradresse des Krankenhauses eingegliedert

**Comment by chrbusch** [comment]
Wir müssen in Rostock besprechen, wie das vorhandene Briefmodul integriert werden soll.
