### ISSUE TITLE
Inhalt Etiketten Herstellung Kornea 

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#151]
Die Etiketten "Herstellung" sollen einen Barcode in Strichform mit der bankinternen Präparatenummer verschlüsseln. Diese Nummer erstellt Ornella bereits automatisch z.B.:
![image](https://cloud.githubusercontent.com/assets/22314271/24441809/a499eb3c-145b-11e7-8a40-ca5850a2e560.png)

und müsste nur noch im Barcode hinterlegt werden. Außerdem muss diese Nummer lesbar unter dem Barcode ausgeschrieben sein.

Der Barcode soll auf die Zellkulturflaschen aufgebracht werden. Das Etikett an sich soll transparent/bzw. beschichtet sein (Ethanol - wischfest) und darf nur eine maximale Breite von 1,5cm und eine max. Länge von 6cm haben.

Pro Transplantat benötigen wir:
- 15 der o.g. Etiketten

Diese könnte man der Übersicht halber unterteilen in "Herstellung" und "Mikrobiologie".

**Herstellung**
-> Beschriftung der Zellkulturflaschen für folgende Zeitpunkte:
1) Eingang
2) Mediumwechsel I + Sterilkontrolle I
3) Mediumwechsel II
4) Mediumwechsel III
5) Mediumwechsel IV - zu KMII zum Versand

**Mikrobiologie**
-> Beschriftung der mikrobiologischen Proben zu unterschiedlichen Zeitpunkten (Bezug zur Herstellungsziffer steht in Klammern)

6) Bindehautabstrich (gehört zu 1)
7) Glaskörperabstrich falls notwendig (gehört zu 1)
8) aerobe Untersuchung (Durchführung bei 2)
9) anaerobe Untersuchung (Durchführung bei 2)
10) aerobe Untersuchung (Durchführung bei 5)
11) anaerobe Untersuchung (Durchführung bei 5)

Im Falle von Kontaminationen werden die folgenden Proben durchgeführt:
12) aerobe Untersuchung (nur Durchführung bei Kontamination)
13) anaerobe Untersuchung (nur Durchführung bei Kontamination)
14) aerobe Untersuchung der Partnerhornhaut (Achtung CD/CS entsprechend anpassen) (nur Durchführung bei Kontamination)
15) anaerobe Untersuchung der Partnerhornhaut (Achtung CD/CS entsprechend anpassen) (nur Durchführung bei Kontamination)

Alle genannten Etiketten sollen bei "Bankeingang" ausgedruckt werden und in der jeweiligen Akte hinterlegt werden.

**Comment by chrbusch** [comment]
Ich verstehe die Anleitung bis zur Zeile "15 der o.g. Etiketten"
Aber was soll ich mit den darunter stehenden Angaben anfangen? Soll ich die 15 Etiketten unterschiedlich beschriften? Oder nur den Druckbogen mit Unterschriften unterteilen?

**Comment by chrbusch** [comment]
Ich brauche auch exakte Angaben, we groß die verwendeten Etiketten sein werden, am besten zusammen mit deren "Avery-Nummer" (so wie 3481 bei den Transportetiketten)

**Comment by Toelk-A** [comment]
Wenn der Barcode in den Maßen 40 x 10mm abgebildet werden kann, werden wir Etiketten von Label Ocean LO-0056-D-70-100 mit den Abmaßen 50 x 20mm bestellen.

Der Barcode "Herstellung" soll, wenn möglich, die Maße 40 x 10mm haben. Im Barcode selbst soll die bankinterne Präparatenummer (z.B.: 2017-0134-GMV-CD) verschlüsselt sein. 

**Wareneingang**
Der Eingang der Hornhaut (zunächst von der GTM-V) soll im Eingangsbuch dokumentiert werden. Hierfür benötigen wir ebenfalls ein Etikett (entspricht Etikett Nummer 16 - fehlte in der oberen Auflistung der Etiketten).  Im Barcode selbst soll die bankinterne Präparatenummer (z.B.: 2017-0134-GMV-CD) verschlüsselt sein. Unter dem Barcode soll die bankinterne Präparatenummer menschenlesbar sein.

**Herstellung** 
Unter dem Barcode soll menschenlesbar nur die zugehörige laufende Nummer sowie die Seite abgebildet werden (z.B.: 0134 – CD)
Zusätzlich kommt zu jedem Zeitpunkt sein entsprechendes Kürzel hinzu:
1.	KMI.0
2.	KMI.1
3.	KMI.2
4.	KMI.3
5.	KMII

**Mikrobiologie**
Unter dem Barcode soll menschenlesbar die bankinterne Präparatenummer (z.B.: 2017-0134-GMV-CD) abgebildet werden. Zusätzlich die folgenden Informationen:
6.	Bindehautabstrich
7.	Glaskörperabstrich
8.	Aerobe Untersuchung I
9.	Anaerobe Untersuchung I
10.	Aerobe Untersuchung II
11.	Anaerobe Untersuchung II

**Kontamination**
Unter dem Barcode soll menschenlesbar die bankinterne Präparatenummer (z.B.: 2017-0134-GMV-CD) abgebildet werden. Zusätzlich die folgenden Informationen:
12.	Aerobe Untersuchung K
13.	Anaerobe Untersuchung K
Unter dem Barcode soll menschenlesbar die bankinterne Präparatenummer der Partnerhornhaut (z.B.: 2017-0134-GMV-CS) abgebildet werden. Zusätzlich die folgenden Informationen:

14.	Aerobe Untersuchung K P
15.	Anaerobe Untersuchung K P

**Comment by Toelk-A** [comment]
Die Etiketten werden am 18.04.2017 über Amazon Prime bestellt. Vielleicht können wir vorher schon Testdrucke durchführen um zu sehen ob die o.g. Kriterien druckbar und lesbar sind.

**Comment by chrbusch** [comment]
Moin, bitte den neuen Button testen und NUR auf den Inhalt der Etiketten achten. 
Um Aufteilung und Größe kümmere ich mich demnächst (heute)
Können Sie den Barcode scannen?

<img width="254" alt="bildschirmfoto 2017-04-19 um 08 15 58" src="https://cloud.githubusercontent.com/assets/1241899/25165821/93c34a46-24d8-11e7-9b71-aa4d2fd5717c.png">

**Comment by chrbusch** [comment]
Ich denke. jetzt ist auch der Aufbau der Etiketten schon ganz gut; ob man das aber auf die Etiketten drucken und scannen kann, kann ich hier nicht testen.
Wenn etwas nicht passt, bitte  ganz genaue Angaben in mm, was wohin verschoben oder zB kleiner gemacht werden muss

[TestHerstellEtikett.pdf](https://github.com/chrbusch/GTM-V/files/932026/TestHerstellEtikett.pdf)

**Comment by chrbusch** [comment]
<img width="390" alt="bildschirmfoto 2017-04-19 um 08 33 22" src="https://cloud.githubusercontent.com/assets/1241899/25166275/ddad7d8c-24da-11e7-99db-775d724a835f.png">

**Comment by Toelk-A** [comment]
Sieht erstmal gut aus. Ich versuche später zu Scannen.  

Bitte beschriftungstechnisch Nummer 14 und 15 ändern: Hier muss die Partnerhornhaut angegeben werden, d.h. wenn XXXX-CD die Ausgangshornhaut ist so müssen bei Etikett 14 und 15 die Partnerhornhaut  XXXX-**CS** angegeben werden.

![image](https://cloud.githubusercontent.com/assets/22314271/25166666/bcef9434-24dc-11e7-82ba-a31c8e094b14.png)

**Comment by chrbusch** [comment]
Try again now...

**Comment by Toelk-A** [comment]
Scanner kann Barcodes nicht lesen

**Comment by Toelk-A** [comment]
Barcodes sind lesbar. Allerdings ist anstatt des "-" ein "ß" im Barcode hinterlegt. Bitte ändern.

**Comment by Toelk-A** [comment]
Bitte auch hier die Ausdrucke an die Etikettengröße anpassen. Wir haben 4 Etiketten pro Zeile. Die Vorlage hat Dr. Nitschke.

**Comment by chrbusch** [comment]
Wenn die Barcodes in Ornella gescannt werden, wird "ß" automatisch gg. "-" ersetzt; die Scanner machen hier einen Fehler, nicht mein Programm.
Mit welcher Spender-ID haben Sie getestet?

**Comment by chrbusch** [comment]
>Bitte auch hier die Ausdrucke an die Etikettengröße anpassen.

Bitte präzise Angaben: Ist der Inhalt zu hoch, zu breit? Wieviele mm?
