### ISSUE TITLE
Etikettendruck Herstellung  und Versand GBM-V 

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#152]
Beim Eingang der Bulbi in die Gewebebank, werden diese schriftlich in einem "Eingangsbuch" dokumentiert. 

1) Wir stellen uns vor, dass dieses "Eingangsbuch" ebenfalls in digitaler Form in Ornella hinterlegt, sodass nur das Transportetikett (Spende, welches die SKS Nummer enthält) abgescannt werden muss. Im Moment werden Transplantate des Spenders im Reiter "Gewebe/Präparate/Transplantate" angelegt.

2) Nachdem die Bulbi "eingegangen" sind, also als Transplantat in "Transplantate dieses Spenders" in Ornella angelegt sind, soll ein Button erstellt werden, der die Etiketten für die Herstellung druckt. Diesen könnte man ähnlich dem Button "Transport-Etikett für alle Präparate" im Bereich "Präparate dieses Spenders" anlegen, entsprechend für die Transplantate. siehe #151 Inhalt Etiketten Herstellung Kornea

3) Wenn das Transplantat freigegeben ist - allokiert werden kann, soll ein weiterer Bogen an Etiketten erstellt werden "Etiketten Versand". siehe #151 Inhalt Etiketten Versand Kornea

**Comment by chrbusch** [comment]
Sind die SEC-Etiketten jetzt OK,kann ich die als Vorgabe für alle Maße nehmen?

**Comment by chrbusch** [comment]
Bitte Ausdruck erneut testen und Rückmeldung.

![bildschirmfoto 2017-04-26 um 08 19 44](https://cloud.githubusercontent.com/assets/1241899/25420597/2022a0ce-2a59-11e7-9eab-0d9adfcfcbb0.JPG)

**Comment by Toelk-A** [comment]
Ausdrucke funktionieren. Bitte für Herstellung umsetzen.

**Comment by chrbusch** [comment]
..habe ich schon,bitte testen!
