### ISSUE TITLE
Inhalt Etiketten Versand Kornea

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#153]

**Comment by Toelk-A** [comment]
Zum Versand der Kornea zur transplantierenden Einrichtung muss die Zellkulturflasche, in der sich die Kornea befindet, mit einem Barcode (SEC-Code) sowie einem Transportetikett versehen werden. Weiterhin muss der SEC Code in Form eines Etikettes auf den Begleitpapieren aufgeklebt werden. Die Transportumverpackung benötigt ebenfalls den SEC-Code. Verlässt die Kornea die GBM-V muss sie im "Ausgangsbuch" ausgetragen werden.

Wir benötigen also folgende Anzahl an Etiketten (Barcode mit verschlüsseltem SEC-CODE):

1) Zellkulturflasche mit Kornea
2) Transportumverpackung
3) Begleitpapiere 1
4) Begleitpapiere 2
5) Begleitpapiere 3
6) Ausgangsbuch
7) Reserve
8) Reserve

Zusätzlich noch 1 Transportetikett für die Zellkulturflasche, wobei hier zwischen "stromaler Hornhautersatz" sowie "Augenhornhaut" unterschieden werden soll

![image](https://cloud.githubusercontent.com/assets/22314271/24450612/cf5a288a-147b-11e7-9f47-888ec8208667.png)

![image](https://cloud.githubusercontent.com/assets/22314271/24450658/f66258c6-147b-11e7-9e83-af632276563b.png)

**Comment by Toelk-A** [comment]
Bildung des SEC Codes #154

**Comment by chrbusch** [comment]
Zwischenstand: Der Scanner kann Barcodes (vom Typ "128") lesen, wenn diese 28mm breit und nur 5mm hoch sind!
Wir haben also gute Karten...

**Comment by Toelk-A** [comment]
Wenn der SEC Code auf 50x20mm programmierbar ist, dann werden wir die Ocean LO-0056-D-70-100 mit den Abmaßen 50 x 20mm bestellen.

Wir können Probedrucke gern testen.

Aufbau des SEC Codes ist im Ticket #154 beschrieben.

Der Barcode ist zweiteilig. Im oberen Barcode ist die SKS Nummer verschlüsselt. Diese muss mit dem Zusatz "SEC" unter dem Barcode menschenlesbar sein. Der untere Barcode verschlüsselt den PKS Code, welcher ebenfalls menschenlesbar darunter abgebildet sein muss.

**Comment by Toelk-A** [comment]
Primär wären hier die Etiketten 1-8 wichtig (SEC-Code).

**Comment by chrbusch** [comment]
Bitte den neuen Button "SEC" testen: Inhalt ok? Etiketten scannbar?

<img width="320" alt="bildschirmfoto 2017-04-19 um 10 37 26" src="https://cloud.githubusercontent.com/assets/1241899/25170855/40c9f3ee-24ec-11e7-8e08-5f828f933478.png">

**Comment by Toelk-A** [comment]
Diese Barcodes sind auch nicht scannbar.

**Comment by chrbusch** [comment]
Auch diese Etiketen sind nun beide scanbar bei mir, Format 125x25 Pixel

**Comment by chrbusch** [comment]
Die Änderungen aus der Email vom 20.4. sind m.E. nun fertig umgesetzt, siehe PDF

[HerstellEtiketten_neu_230417.pdf](https://github.com/chrbusch/GTM-V/files/949485/HerstellEtiketten_neu_230417.pdf)

**Comment by Toelk-A** [comment]
Bitte die Etiketten folgendermaßen umgestalten:

1) Vor den Barcode der SKS Nummer das Kürzel "DIS" vertikal zur Leserichtung einfügen
2) Vor den Barcode der PKS Nummer das Kürzel "PIS" vertikal zur Leserichtung einfügen
3) den lesbaren Inhalt bitte unter den beiden Barcodes folgendermaßen zusammenfassen:

SEC:   SKS
          PKS

![image](https://cloud.githubusercontent.com/assets/22314271/25328637/f0da7426-28d8-11e7-81e9-2f8261fc9317.png)

**Comment by Toelk-A** [comment]
![image](https://cloud.githubusercontent.com/assets/22314271/25328747/57c5f4a8-28d9-11e7-9ee3-aadcdce11789.png)

**Comment by chrbusch** [comment]
OK, getan. Bite v.a. testen, ob die Barcodes nun noch GETRENNT scanbar sind, denn sie stehen ja jetzt eng untereinander

**Comment by Toelk-A** [comment]
Barcodes sind scannbar. Allerdings ist unser Ausdruck noch nicht passgenau mit den Etiketten. Vielleicht könnte man die Freizeichen zwischen DIS und Barcode löschen bzw, den Abstand verkleinern. 

Den SEC könnte man ebenfalls näher am Barcode abbilden.

**Comment by Toelk-A** [comment]
Bitte Druckbeginn 8mm von oben und 6mm von links

**Comment by chrbusch** [comment]
Das kann ich so nicht einstellen; ich muss immer wissen, wieviele mm es ANDERS sein soll relativ zum momentanen Druck, also Angaben wie
"Alles 2mm weiter nach links"

**Comment by Toelk-A** [comment]
alles 2mm nach unten 
1. Etikett links oben 5mm weiter nach links
Etiketten an sich sind 5cm lang, diese Einstellung bitte übernehmen, da sich sonst alle folgenden Etiketten der selben Zeile zu weit nach links verschieben

**Comment by chrbusch** [comment]
1) alles 2mm nach unten : Erledigt

2) Etikett links oben 5mm weiter nach links_ Erl.

3) Etiketten an sich sind 5cm lang, diese Einstellung bitte übernehmen: Bitte auch hier relative Angabe zum Ist-Zustand: Wieviel mm "driftet" es jetzt PRO ETIKETT nach links?
Oder ist die gerade durchgeführte Korrektur schon ausreichend?
