### ISSUE TITLE
Programmierung des SEC-Codes zur Erstellung der Etiketten Herstellung und Versand Kornea

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#154]
![image](https://cloud.githubusercontent.com/assets/22314271/24451111/ca551bc2-147d-11e7-84f8-49e4fd6f5239.png)

Der SKS -Code ist bereits in Ornella programmiert.
Die Produktkennungssequenz muss noch erstellt werden:

Für das Produkt Kornea gilt: B0721001
linke Kornea Splitnummer = CSO
rechte Kornea Splitnummer = CDO

Der SEC Code soll in 2 Barcodes auf einem Etikett aufgesplittet sein:
SKS-Code    Zeilenumbruch
PKS-Code

**Comment by chrbusch** [comment]
Bitte den neuen Code prüfen auf der Spendermaske, Reiter "Gew/Präp/Transpl.", zb SpenderID 1675

![bildschirmfoto 2017-03-30 um 11 08 32](https://cloud.githubusercontent.com/assets/1241899/24496708/481a35b8-1539-11e7-9184-1536bf9615e1.JPG)

**Comment by chrbusch** [comment]
Beide Codes werden nun l.o. auf der Detailmaske des Transplantates dargestellt

![bildschirmfoto 2017-03-30 um 11 17 12](https://cloud.githubusercontent.com/assets/1241899/24497069/7e7f6636-153a-11e7-9403-66c31a4ce76d.JPG)

**Comment by Toelk-A** [comment]
Code funktioniert
