### ISSUE TITLE
Erstellen einer "Herstellungsliste"

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#155]
Neben der "Transplantatliste" wünschen sich die Mitarbeiter der GBM-V der Übersicht halber eine "Herstellungsliste". Diese soll folgende Informationen enthalten:

- Bank Nr. des Transplantates (automatische Anordnung: höchste Nummer (=neuster Bankeingang) an erster Stelle
- Zellzahl
- Haltbarkeitsdatum
- Status

Die Herstellungsliste soll den Zeitraum "heute bis  - 5 Wochen" umfassen

**Comment by chrbusch** [comment]
>Die Herstellungsliste soll den Zeitraum "heute bis - 5 Wochen" umfassen

..bezgl. welches Datums?

**Comment by Toelk-A** [comment]
Heutiges Datum "minus" 5 Wochen

**Comment by chrbusch** [comment]
Ich meine. Welches Datum soll in diesen Bereich fallen? Herstellungsdatum?
Ich brauche immer so eine Angabe: Das Feld "????" in der Datenbank soll in den Bereich "????" fallen.
Die Liste und der Button (im Thema Hauptmenü/Herstellung) existieren nun, aber wie soll ich suchen lassen?

**Comment by Toelk-A** [comment]
Heutiges Datum: 03.04.2017

1)  Herstellungsliste gibt folgenden Zeitraum an : 25.01.2017 - 06.03.2017
Wie oben mehrmals beschrieben benötigen wir den Zeitraum "heutiges Datum" = Herstellungsdatum heute (03.04.2017) bis "minus" 5 Wochen (ca. Ende Februar).

2) Bitte "Bank-Nr des Transplantates" in absteigender Reihenfolge anordnen, d.h. "jüngste" Hornhaut an 1. Stelle abbilden

**Comment by chrbusch** [comment]
Habe gerade mal Internet...

Dass im Feld "Herstellungsdatum" gesucht werden soll, wurde m.E. eben nie vorher gesagt - wie dem auch sei, nun wird so gesucht. Die Sortierung halte ich aber für unglücklich, da die BankNr nicht zuverlässig das "Alter" des Transplantates abbildet.
