### ISSUE TITLE
Kompaktansicht mit detaillierteren Informationen füllen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#156]
Bitte die Kompaktansicht im Abschnitt "Befunde" mit den Daten aus der "Spd Transplantat Details" - Abschnitt "Befunde aller Art" füllen. So bildet die Kompaktansicht eine schnellere Übersicht ob Transplantat allokierbar ist oder nicht.

Kompaktansicht
![image](https://cloud.githubusercontent.com/assets/22314271/24504107/3384fec8-1555-11e7-8ed1-ca71defc7dc9.png)

Spd Transplantat Details
![image](https://cloud.githubusercontent.com/assets/22314271/24504222/ac0e0718-1555-11e7-9440-c834fde106a7.png)

**Comment by chrbusch** [comment]
Erledigt, mit neuer Sortierung nach "Anklickfeld" ganz vorne

![bildschirmfoto 2017-03-31 um 10 03 20](https://cloud.githubusercontent.com/assets/1241899/24541803/4ac69d36-15f9-11e7-8e3e-60753eaf21e9.JPG)
