### ISSUE TITLE
/GBMV Button Partnerhorhnhaut setzt bankinterne Nummer CD anstatt CS

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#157]
Nachdem z.B. das rechte Transplant im Reiter "Basisdaten" angelegt wurde, sowie Daten im Feld "Herstellung" und "Befunde aller Art" eingetragen sind, soll der Button "Partnerhornhaut anlegen" im Feld "Herstellung" anklickbar sein.

![image](https://cloud.githubusercontent.com/assets/22314271/24507049/b7e31b50-155f-11e7-8748-eab2d2ef0b19.png)

Somit kann die Partnerhornhaut, in diesem Fall die linke Seite, direkt angelegt werden und man erspart sich den "Weg" zurück zur Spendermeldung, Reiter "Gewebe, Präparate, Transplantate". Ebenfalls sollen die bereits eingetragenen Informationen im Bereich "Herstellung" und "Befunde aller Art" automatisch übernommen - trotzdem modifizierbar - werden.

**Comment by chrbusch** [comment]
Ich denke, dies funktioniert jetzt, siehe neuen grünen Button

![bildschirmfoto 2017-05-15 um 12 20 58](https://cloud.githubusercontent.com/assets/1241899/26053410/0a6111ac-3969-11e7-80e4-0705683ba7c0.JPG)

**Comment by Toelk-A** [comment]
Button funktioniert wunderbar. 
Wir haben noch 1 Bitte:
Im Abschnitt "Kenn-Nummer" soll in der Zeile "Seite" auch automatisch die Partnerhornhautsseite angelegt werden: z.B. Die zuerst angelegte Hornhaut war "D" so soll nach dem Klicken des Buttons "Partnerhornhaut anlegen" automatisch "S" angeklickt sein. Außerdem wäre es gut wenn hiermit auch automatisch die "Bank-int Nummer" (Zeile darunter) von "CD" in "CS" geändert werden könnte.

Ist dies umsetzbar?

 Im Moment werden die Seiten nicht automatisch getauscht und in der Herstellliste erscheinen 2 "linke" Hornhäute des selben Spenders.
![image](https://cloud.githubusercontent.com/assets/22314271/26189607/c5741172-3ba5-11e7-8abc-3ced66e19161.png)

**Comment by Toelk-A** [comment]
Transplantatdetails

Wenn durch uns ein HH-Transplantat erstellt wird, dann gibt es den Button „Partnerhornhaut erstellen“.
![image](https://user-images.githubusercontent.com/22314271/37663074-bb8043d0-2c58-11e8-9c0c-04894e0304ab.png)

Erstellt man über diesen Button die andere HH-Seite (also CS), wird im Feld der Bankinternen Nummer erneut die CD Seite erstellt (aber nur im Feld der Bankinternen Nr, KennNr. der GTMV ist korrekt mit OS).

**Comment by chrbusch** [comment]
DUMMER Fehler von mir, sollte jetzt klappen!
