### ISSUE TITLE
Wareneingang - Barcode erstellen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#158]
Nachdem die Waren bei uns eingehen müssen wir die Chargennummer (LOT) sowie das Haltbarkeitsdatum, Menge etc. in Ornella auf der von ihnen bereits programmierten Maske eingeben.

![image](https://cloud.githubusercontent.com/assets/22314271/24508643/61decede-1564-11e7-9bc4-b78194783713.png)

Auf dieser Maske sollte ein Button "Barcode drucken" eingefügt werden. Der Barcode soll die Chargennummer, das Haltbarkeitsdatum und Produkt enthalten. Leserlich (menschenlesbar) müssen Chargennummer und Haltbarkeitsdatum abgebildet sein.

Dieser Barcode könnte beim Erstellen der Warenkörbe abgescannt werden, sodass im Warenkorb selbst das "Mindesthaltbarkeitsdatum des Warenkorbs" hinterlegt ist.

**Comment by chrbusch** [comment]
Der Barcode kann nicht all das enthalten, muss er doch auch gar nicht.
Ich denke, der Barcode sollte NUR die ID der Charge enthalten; alles andere kann das Programm dann beim Scannen "nachschlagen" aus dem entspr. Datensatz.
Und lesbar wird gedruckt: Artikel-Bezng., Charge, MHD
Wird nur jeweils ein Aufkleber benötigt?

**Comment by chrbusch** [comment]
Es fragt sich auch, ob nicht do langsam mal ein Barcode-Drucker angeschafft werden sollte, der stressfrei einzelne Aufkleber drucken kann! Bislang müssen Sie ja immer einen DIN-A4-Bogen nehmen und die schon verbrauchten Etiketten zählen...

**Comment by Toelk-A** [comment]
okay, dann ID im Barcode hinterlegen und lesbar Artikel-Bezng., Charge, MHD drucken

**Comment by chrbusch** [comment]
Avery wie Blut, 3657

**Comment by chrbusch** [comment]
Artikelmaske, Reiter mit den Chargen: Dort ist neuer Button "Etikettendruck", der eine bel. Anzahl Etiketten druckt
Was noch fehlt: Scanoption für diese Etiketten bei Platzierung eines Artikels in einen Warenkorb

**Comment by chrbusch** [comment]
Nun bitte beschreiben; Was passiert genau mit den Etiketten?
Meine Vorstellung: Sie werden auf die Behälter im Lager geklebt. Beim Zusammenstellen eines WaKos werden die Barcodes gescannt; dadurch kennt der WaKo u.a. das MHD seiner Positionen.
Dieses kann menschen-lesbar auf dem Etikett stehen, das für den WaKo gedruckt wird.

**Comment by Toelk-A** [comment]
okay
