### ISSUE TITLE
Wareneingang - Bitte Feld für Haltbarkeitsdatum erstellen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#159]
Bitte in Ihrer Materialienmaske ein Feld für "Haltbarkeitsdatum" erstellen in dem wir dann manuell das Datum eingeben können.

![image](https://cloud.githubusercontent.com/assets/22314271/24510442/8821b2a0-1569-11e7-8164-f2680f422a2c.png)

**Comment by Toelk-A** [comment]
Zwischen "Anzahl" und "Bemerkungen" könnte man das Feld Haltbarkeitsdatum einfügen

**Comment by chrbusch** [comment]
Erl., Feld heißt "Datum MHD"
