### ISSUE TITLE
!!!!! Höchste Priorität !!!! Dokumente im Bereich Spende

### ISSUE THREAD

**Issue by chrbusch** [chrbusch/GTM-V#16]
Bitte ALLE Dokumente im Bereich Spende ausfüllen und drucken.
Dann die Ausdrucke genau betrachten: was fehlt hier noch?
Alle erwünschten Änderungen hier in github dokumentieren.

**Comment by chrbusch** [comment]
Ist dieser Punkt erledigt?

**Comment by Toelk-A** [comment]
noch in Arbeit, Ergebnis in der kommenden Woche

**Comment by Toelk-A** [comment]
Ergebnisse kommen in der nächsten Woche

**Comment by Toelk-A** [comment]
Dokumente sind alle Korrekturlesen. Die Änderungsvorschläge werden noch mit Dr. Nitschke besprochen und anschließend Ihnen mitgeteilt. Wie möchten Sie Änderungsvorschläge erhalten:

a) in Form einer Exceltabelle
oder
b) jeden einzelnen Änderungsvorschlag als Issue?

**Comment by chrbusch** [comment]
Ich denke, wir machen das am besten gemeinsam in Rostock ab dem 21.11. (nächste Woche bin ich ja in Urlaub).
Dann sparen Sie sich viel Schreibarbeit und es gibt keine Mißverständnisse.

**Comment by Toelk-A** [comment]
Anbei die Exceltabelle mit Änderungsvorschlägen

[PDF Mängel Ornella vollständig.xlsx](https://github.com/chrbusch/GTM-V/files/603287/PDF.Mangel.Ornella.vollstandig.xlsx)

**Comment by Toelk-A** [comment]
Anbei Exceltabelle mit alten/neuen Änderungsvorschlägen in den PDF Dokumenten. Die Fehler sind im Exceldokument in "Tabelle 2" aufgelistet.

Dies ist der Wichtigste Punkt der neben dem Emailversand schnellstmöglich bearbeitet werden soll.

[PDF Mängel Ornella vollständig.xlsx](https://github.com/chrbusch/GTM-V/files/696041/PDF.Mangel.Ornella.vollstandig.xlsx)

**Comment by chrbusch** [comment]
Das gehe ich heute an!

**Comment by chrbusch** [comment]
Ich habe das XLS gelesen; in den allermeisten Fällen weiss ich nicht, was ich tun soll.
Ich brauche hier nicht Stichworte, sondern klare Handlungsanweisungen.
Wir sollten zudem zumindest ein Ticket pro Dokument haben; sonst wird die Kommunikation sehr unübersichtlich.
Legen Sie bitte ein Ticket pro Dokument an, alle mit "Wichtig!" vorne.
Dann aber bitte die Dokumententitel wie "Entnahmebericht" im Ticket-Titel, nicht so etwas wie "Spenderakte Teil 5", sonst muss ich jedes Mal nachschauen, welches Dokument das ist.

**Comment by Toelk-A** [comment]
Bitte bearbeiten Sie die PDF´s als allerhöchste Priorität. Im Moment schreiben wir "Ornella- und Papierakten". Der zeitliche Aufwand ist einfach viel zu hoch. Rufen Sie mich bitte bei Fragen an.

**Comment by chrbusch** [comment]
Ich denke, dies ist nun erl., oder?

**Comment by Toelk-A** [comment]
Unser QM schaut die Dokumente gerade durch, bis 12Uhr gibt es hier ein Update

**Comment by Toelk-A** [comment]
Wie in der Mail angekündigt hier die Exceltabelle. Bitte Reiter "Letzte Verbesserungen" bearbeiten


[PDF Mängel Ornella vollständig.xlsx](https://github.com/chrbusch/GTM-V/files/747556/PDF.Mangel.Ornella.vollstandig.xlsx)

**Comment by chrbusch** [comment]
Das ist alles erledigt bis auf den letzten Punkt; hierzu bitte anrufen

**Comment by Toelk-A** [comment]
Bitte alle Tickets und die den letzten Reiter der Exceltabelle (siehe Email von heut morgen)  bearbeiten.
