### ISSUE TITLE
Überschrift Entnahmebericht OG PDF "OG" wird doppelt abgebildet

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#160]
ID 1763

bei Erstellung des PDFs tritt jetzt folgendes Problem auf:

![image](https://cloud.githubusercontent.com/assets/22314271/24597915/0858493e-1849-11e7-9868-1e9fabe4620c.png)

bitte umgehend korrigieren

**Comment by chrbusch** [comment]
Erledigt, bitte testen
