### ISSUE TITLE
Medizinische Indikationsprüfung "keine Datensätze vorhanden" ID 1811

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#161]
ID 1811

medizinische Indikationsprüfung zeigt folgende Fehler 

Es kann kein Hausarzt hinterlegt werden (Name Biermann Björn)
außerdem können "B" und "C" nicht angekreuzt werden. Bitte Problem umgehend beheben

![image](https://cloud.githubusercontent.com/assets/22314271/24896301/9100c594-1e94-11e7-96ce-d5b63edba126.png)

**Comment by chrbusch** [comment]
Ich weiss nicht wodurch, aber hier war ein Datensatz gelöscht worden.
Ist wieder hergestellt; wenn es erneut passieren sollte, müssen wir es genau analysieren
