### ISSUE TITLE
Regeln Erstellung RBD-Plan

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#162]
1) Wer "Urlaub", "nicht verfügbar", etc. Im Dienstplan stehen hat, darf nicht als "Diensthabener" eingetragen werden.

2) Wer das Vorwochenende (Fr-So) Dienst hatte, darf nicht am darauf folgenden Montag sowie am darauf folgenden Wochenende Dienst haben (Achtung: Vormonate mit einbeziehen).

3) Die Dienste (wochentags und Wochenende) sollen unter den Mitarbeitern gleichmäßig verteilt werden.

4) Dienste wochentags sollten möglichst 1x pro Woche und nur in Ausnahmefällen mehrmals in derselben Woche angesetzt werden.

5) "Dienstwünsche" in Dienstplanung einbeziehen.

6) Der Dienstplan soll für "Notfälle" (z.B. Krankheit) flexibel bleiben (das Tauschen muss im aktuellen Monat und Tag möglich sein)

**Comment by chrbusch** [comment]
Ich denke, wir müssen hier noch die Priorität der obigen Regeln diskutieren.
Regel 1 verhindert meines Erachtens ohne Ausnahme, dass jemand Dienst haben kann.
Danach kommt aber doch wohl Regel 5: egal, wie der Dienst in den Vortagen lag, wer ausdrücklich wünscht, Dienst zu haben, sollte meines Erachtens dafür eingeteilt werden.
Oder gibt es gesetzliche Regelungen, die das ausschließen?

**Comment by chrbusch** [comment]
..und muss ein Dienstwunsch überhaupt "abgesegnet" werden, oder kann man das ohne Prüfung akzeptieren?

**Comment by Toelk-A** [comment]
hierzu telefonieren wir am Besten auch noch einmal...

**Comment by Toelk-A** [comment]
habe Sie eben nciht erreichen können, bitte rufen Sie mich bis 08:55Uhr zum Thema RBD zurück

**Comment by Toelk-A** [comment]
Ergänzung zu Regel 2: Wer am Wochenende Dienst hat, darf nicht am Donnerstag vor dem Dienstwochenende eingeteilt werden.

Am unteren Beispiel äußerte ich den Wunsch von Freitag bis Montag Dienst zu machen. Anstelle dessen, trägt Ornella einen anderen Koordinator für den Montagsdienst ein.

![image](https://cloud.githubusercontent.com/assets/22314271/24961238/7edb59ba-1f98-11e7-9005-87975a1f9a7f.png)

**Comment by chrbusch** [comment]
Ich denke, dieses Ticket hat zZ keine Priorität, oder?
Ich habe die Erstellung des RBD-Plans deaktiviert, weil ich dies das nächste Mal selbst tun und überwachen möchte.
Wann soll der nächste Plan erstellt werden?

**Comment by Toelk-A** [comment]
Der nächste Dienstplan (Juni 2017) soll in der letzten Aprilwoche erstellt werden, sodass die Mitarbeiter  4 Wochen vorher über Ihre Dienste informiert sind.

**Comment by chrbusch** [comment]
Sehe ich richtig, dass alle für den Juni eingetragenen RBD beim Testen entstanden sind und gelöscht werden können?
Ist Ihr RBD-Wunsch f.d. 5.6.2017 echt?

**Comment by chrbusch** [comment]
Ich denke, dass nun alle Regeln beachtet werden vom Programm; für den Juni gemeinsam testen.
(Ist zZ nur für die Koordinatoren, kann aber leicht verallgemeinert werden für Ärzte und andere Teams)

**Comment by Toelk-A** [comment]
Der 1.Mai ist ein Feiertag. 

Für Feiertage sowie Sa und So (beides bereits programmiert) gibt es 2h "Zeitausgleich". 

Bitte ändern Sie die Feiertagsausgleiche zu "2h".

**Comment by Toelk-A** [comment]
Für Wochentage (Mo-Fr) exkl. Feiertage gibt es für den RBD 1h "Zeitausgleich". Bitte ändern.

![image](https://cloud.githubusercontent.com/assets/22314271/25334731/2b3493ba-28f0-11e7-86d1-001647eccfb2.png)

**Comment by chrbusch** [comment]
Jetzt richtig?
