### ISSUE TITLE
Bestellungen mit Ornella - Kundenummer hinterlegen 

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#166]
Bitte in der Masteradresse ein Feld "Kundenummer" z.B. über "Bemerkungen" anlegen:

![image](https://cloud.githubusercontent.com/assets/22314271/24956288/3f1696e8-1f87-11e7-8ce3-1c99e4023218.png)

Diese Kundennummer soll dann automatisch in die Bestellung beim Lieferanten eingefügt werden.

**Comment by chrbusch** [comment]
Beides erledigt, bitte einige KundenNummern eintragen und dies testen
