### ISSUE TITLE
Bestellungen mit Ornella - Artikelnummer einfügen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#168]
Bitte die Artikelnummer neben der "Bezeichnung des Artikels" einfügen.

![image](https://cloud.githubusercontent.com/assets/22314271/24956548/613e2d98-1f88-11e7-96d3-7084dde64d84.png)

**Comment by chrbusch** [comment]
Meinen Sie die ID?
Denn das Feld "Art-Nr bei GTM-V" ist fast immer leer.
Bitte genau angeben, was ich dort platzieren soll

**Comment by Toelk-A** [comment]
Ich meine die Artikelnummer / Bestellnummer ist unter  "Artikelnummer beim Lieferanten" hinterlegt

![image](https://cloud.githubusercontent.com/assets/22314271/24958567/09ba6822-1f90-11e7-8743-9ebb197039a1.png)

**Comment by chrbusch** [comment]
OK, so gemacht
