### ISSUE TITLE
Button "Koordinator fertig - Mail an Arzt"

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#17]
Hallo Herr Dr. Busch,

der Mailbutton in "Spenderdaten" fehlt derzeit komplett. Bitte geben Sie uns Bescheid sowie er wieder vorhanden und funktionsfähig ist.
Vielen Dank 
MFG A.Tölk

**Comment by chrbusch** [comment]
Was meinen Sie mit "Mailbutton"??

**Comment by chrbusch** [comment]
Falls Sie den Button <Koord. schließt ab..> meinen:
Dieser ist sichtbar, wenn die SpdKennNr gesetzt wurde, keine Plausibilitätsprobleme angezeigt werden und der Button noch nicht geklickt wurde siehe Bild.

![bildschirmfoto 2016-10-19 um 13 00 09](https://cloud.githubusercontent.com/assets/1241899/19516399/1acb8e8e-95fc-11e6-80f6-1f66c10aa62b.JPG)

**Comment by chrbusch** [comment]
Bei mir klappt nun auch das Senden mit den von Hr. Peters gelieferten SMTP-Daten von GTM-V.
Bite den <Koord. Schließt...> nun testen mit einem neuen Testspender

**Comment by chrbusch** [comment]
Meines Erachtens kann dieses Ticket nun geschlossen werden, da seit gestern das Mailing funktioniert.
