### ISSUE TITLE
Warenkorb erstellen

### ISSUE THREAD

**Issue by chrbusch** [chrbusch/GTM-V#170]
Bislang umgesetzt: 
Hauptmenü/Artikel, Warenkorb, Bestellung/Neuer konkreter Warenkorb 
(im Gegensatz zum "virtuellen" Warenkorb; bin nicht sicher, ob wir das noch brauchen)
Nun mit dem neuen Button "Neue Position" den Warenkorb befüllen.

**Comment by chrbusch** [comment]
![bildschirmfoto 2017-04-17 um 08 25 52](https://cloud.githubusercontent.com/assets/1241899/25080924/7d4a9c7a-2347-11e7-82fa-6d27fc2256f2.JPG)
![bildschirmfoto 2017-04-17 um 08 25 42](https://cloud.githubusercontent.com/assets/1241899/25080925/7d4b8a86-2347-11e7-9142-ce56f2c52201.JPG)
![bildschirmfoto 2017-04-17 um 08 25 30](https://cloud.githubusercontent.com/assets/1241899/25080926/7d5061b4-2347-11e7-978c-03dad505e6fe.JPG)

**Comment by chrbusch** [comment]
Ablauf in Bildern:
![bildschirmfoto 2017-04-17 um 08 25 30](https://cloud.githubusercontent.com/assets/1241899/25080939/8cdd939a-2347-11e7-8f26-912dbeb4a7b7.JPG)
![bildschirmfoto 2017-04-17 um 08 25 42](https://cloud.githubusercontent.com/assets/1241899/25080941/8f0bd0b4-2347-11e7-9c89-7e705428cdf0.JPG)
![bildschirmfoto 2017-04-17 um 08 25 52](https://cloud.githubusercontent.com/assets/1241899/25080944/919803ca-2347-11e7-87c4-5c349de8c6c1.JPG)

**Comment by chrbusch** [comment]
Ist der Barcode nicht bei einer Artikelcharge hinterlegt, erscheint eine Warnung:

![bildschirmfoto 2017-04-17 um 08 29 10](https://cloud.githubusercontent.com/assets/1241899/25081013/fe8ec4aa-2347-11e7-9065-376930cb3049.JPG)

**Comment by chrbusch** [comment]
Ich denke, wenn Sie nun über Adresse/Neue Bestellung und den dortigen Wareneingang die Chargen erfassen, können Sie Warenkörbe befüllen.
Zu besprechen: Wie bekommen wir den aktuellen Warenbestand in das System?

**Comment by Toelk-A** [comment]
Wir werden uns am Donnerstag mit allen Mitarbeitern zum Thema Warenkorb beraten. Wenn die Warenkörbe von unserer Seite aus klar strukturiert sind, werden wir in der kommenden Woche eine Inventur durchführen und den aktuellen Bestand in Ornella nachtragen.
