### ISSUE TITLE
SKS Nummer im Barcode der Spenderakte hinterlegen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#171]
Bitte den SKS Code im Barcode (rechts oben) in der kompletten Spenderakte hinterlegen. Hier ist zur Zeit nur die Spender ID hinterlegt).

![image](https://cloud.githubusercontent.com/assets/22314271/25166825/6253abd6-24dd-11e7-831a-20219a580549.png)

**Comment by chrbusch** [comment]
Bitte testen, ob das jetzt korrekt erscheint und gescannt werden kann

**Comment by Toelk-A** [comment]
funktioniert
