### ISSUE TITLE
Bitte neuen "Status" in Spendermeldung-Status des Spenders  einfügen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#172]
![image](https://cloud.githubusercontent.com/assets/22314271/25226352/00133ee4-25c5-11e7-8a19-9f17e96e1e94.png)

Status bitte übernehmen und ein "keine" davor setzen
![image](https://cloud.githubusercontent.com/assets/22314271/25226406/2908e79a-25c5-11e7-8f99-0031fd612135.png)

**Comment by chrbusch** [comment]
Ich bin nicht sicher, was mit "übernehmen" gemeint ist.
Soll ein NEUER Status "keine Freigabe.." eingerichtet werden?

**Comment by Toelk-A** [comment]
ja, bitte neuer Status "keine Freigabe.." einrichten

**Comment by chrbusch** [comment]
OK, erledigt
