### ISSUE TITLE
Bitte Perikard aus MSG Präparateliste "j" löschen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#173]
ID 1876 Reiter Gewebe/Präparate/Transplantate  Hier erscheint "Perikard" (was eigentlich zu KVG gehört und auch schon rot für KVG markiert ist) in der MSG Präparateliste. Bitte umgehend den Fehler beheben

![image](https://cloud.githubusercontent.com/assets/22314271/25285574/fe14c67a-26ba-11e7-9f59-c16113343390.png)

**Comment by chrbusch** [comment]
In der Basistabelle steht Perikard korrekt als "KVG".
Mit welchem Button sind die Präparate am 21.4. angelegt worden?
Ist das Problem reproduzierbar?

**Comment by Toelk-A** [comment]
MSG Standardset "j" anlegen

**Comment by chrbusch** [comment]
Wenn ich richtig sehe, dass dies ein ganz anderes Thema ist, bitte neues Ticket dafür; das alte kann dann m.E: geschlossen werden

**Comment by Toelk-A** [comment]
Fehler erneut aufgetreten
ID 1934

![image](https://cloud.githubusercontent.com/assets/22314271/25621767/a238abd2-2f52-11e7-938c-d353459afd50.png)

**Comment by chrbusch** [comment]
Hier ist das Standardset falsch erfasst! Perikard ist als Bestandteil des "MSG-Standardsets" definiert gewesen; dies habe ich korrigiert.
