### ISSUE TITLE
MSG Entnahmebericht Präparate nebeneinander anordnen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#174]
Eigentlich war dieses Issue schon einmal abgearbeitet.

Bitte Präparate nebeneinander anordnen, da sonst nicht alle entnommenen Präparate im MSG Entnahmebericht sichtbar sind

ID 1876

![image](https://cloud.githubusercontent.com/assets/22314271/25285633/395d94aa-26bb-11e7-9a8a-54562e12b2e9.png)

**Comment by chrbusch** [comment]
Das ist nicht so simpel, weil durch die nachtrgl. Einführung der von Durchmesser und länge die Zeilen evt. zu lang sind, um nebeneinander zu passen!
Es ist jetzt so: Sind es mehr als 12 Präparate, erscheinen sie als Fliesstext mit dem Trenner "   /   ".
Ist das in Ordnung so?

![bildschirmfoto 2017-04-22 um 10 17 45](https://cloud.githubusercontent.com/assets/1241899/25302723/f977e8d8-2744-11e7-8aa7-9bdb298c1863.JPG)

**Comment by Toelk-A** [comment]
In Ordnung
