### ISSUE TITLE
Mail vom 26.04.17   Etiketten Herstellung Button "Alle Herstellungsetiketten drucken" anlegen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#179]
Können Sie bitte für die Etiketten 'Herstellung' einen Button anlegen, der die Etiketten für beide Transplantate (also CD und CS, nur wenn beide Transplantate angelegt sind ) auf einen A4 Bogen druckt? Am Besten für die Partnerhornhaut die Etiketten in einer neue Zeile beginnen.

Auf diesem A4 Bogen bitte zusätzlich 1 Etikett mit Barcode, der die SKS Nummer verschlüsselt, und menschenlesbar die SKS Nummer abbildet, programmieren. (Dieser könnte von den Transportetiketten -Präparate - übernommen werden)

**Comment by chrbusch** [comment]
Das klappt m.E. schon ganz gut!

[aaaa.pdf](https://github.com/chrbusch/GTM-V/files/969959/aaaa.pdf)

**Comment by Toelk-A** [comment]
Wie oben beschrieben bitte:

1) zusätzlich 1 Etikett mit Barcode, der die SKS Nummer verschlüsselt, und menschenlesbar die SKS Nummer abbildet, programmieren. (Dieser könnte von den Transportetiketten -Präparate - übernommen werden) 

2) Der Übersicht halber bitte die Etiketten der Partnerhornhaut in einer neuen Zeile beginnen.

**Comment by chrbusch** [comment]
das ist doch auch beides so?!

**Comment by Toelk-A** [comment]
1. Etikett = SKS Code. Bitte heirmenschenlesbar nur "SKS" abbilden, "Etikett vorab" bitte löschen
Bitte das Wort "Spacer 1 " entfernen
