### ISSUE TITLE
Prozesschritt Einwilligungserklärung

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#18]
-   Verwandtschaftsgrad Dropdown: Angehörige gemäß TPG ins Drop-Down setzen
-   Rahmenbedingungen: Dropdown „Gesprächsort“ : („Telefonat“, „Station“, „Sonstiges“ mit Eingabefeld)
-   im Feld Gesprächsteilnehmer beratenden Koordinator und gesprächsführenden Arzt eintragen und weiteren Text editieren lassen
-   außerdem Eingabefeld zur Definition der „eingeschränkten“ Gewebe Zustimmung 
-   Wenn Todesursache „natürlich“, dann entfällt der restliche Teil „Freigabe Staatsanwaltschaft“ – ist feintuning
-   Beratender Koordinator im Angehörigengespräch muss nicht gleich verantwortlicher Koordinator sein (KEINE Änderung in Spendermeldung bitte)
-   wenn Externe das Gespräch führen kopieren wir uns die Aktennotiz. Dieses Dokument sollte hochgeladen werden

**Comment by chrbusch** [comment]
Was ist "TPG"?
Bitte die obigen Punkte nummerieren!

**Comment by Toelk-A** [comment]
ich erstelle für jeden Punkt ein eigenes Issue
