### ISSUE TITLE
Zusatz Regeln RBD - Wochenenddienst

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#180]
Bitte Wochenenddienste (Freitag - Sonntag) gleichmäßig aufteilen, d.h. der selbe Koordinator darf nicht an 2 aufeinander folgenden Wochenenden Dienst haben. Es sollte ebenfalls vermieden werden, dass ein und der selbe Koordinator an 2 von 3 aufeinanderfolgenden Wochenenden Dienst hat.

**Comment by chrbusch** [comment]
Der Juliplan ist erstellt, siehe Bild.
Es bekamen zwar nur Schweder und Maschmeier WE-Dienste, aber erstens nie zweimal nacheinander, und v.a. haben alle anderen Koord. MEHR WE-Dienste in diesem jahr gehabt.
ggfs. anhand des Bildes diskutieren
![bildschirmfoto 2017-05-17 um 10 31 53](https://cloud.githubusercontent.com/assets/1241899/26145309/4c19932e-3aec-11e7-9002-1082ce4a9f88.JPG)

**Comment by Toelk-A** [comment]
1) Herr Maschmeier ist erst seit 01.02.2017 bei der GTM-V. Weiterhin wurde festgelegt, dass er erst ab April 2017 eigenständig WE-Dienste durchführen soll. Dies sollte in die Berechnung der RBD und WE-Dienste einbezogen werden.

2) Regel: Wer WE-Dienst hat, darf den darauffolgenden Montag keinen Dienst haben (10.07.2017+24.07.17) ist dies nicht zutreffend.

3) Herr Petrowski hat nur 1x Dienst, ist dies richtig berechnet?

4) Wer WE-Dienst hat darf innerhalb von 3 Wochenenden nicht 2x Dienst haben. Dies bedeutet es müssen nach dem WE Dienst mindestens 2 weitere Wochenenden "frei" sein.

**Comment by chrbusch** [comment]
Ich denke, jetzt stimmt alles; bitte RBD-Plan JULI für die Koord. prüfen

**Comment by Toelk-A** [comment]
Auf den ersten Blick scheint der Juli Plan in Ordnung. Wenn alle Regeln programmiert sind, denke ich, dass in Zukunft das Erstellen des Dienstplanes problemlos klappen sollte.

Können die Geschäftsführer die Anzahl/Verteilung der geleisteten Dienste in Ornella einsehen?

**Comment by chrbusch** [comment]
Übersicht RBD: Im Hauptmenü Thema Mitarbeiter, dann...

![bildschirmfoto 2017-05-24 um 11 04 57](https://cloud.githubusercontent.com/assets/1241899/26395629/f1398830-4070-11e7-92ac-34af2269cb47.JPG)


[Mitarbeiterliste_Aerzte_170524110506.PDF](https://github.com/chrbusch/GTM-V/files/1024965/Mitarbeiterliste_Aerzte_170524110506.PDF)

**Comment by Toelk-A** [comment]
![image](https://cloud.githubusercontent.com/assets/22314271/26395915/deeeca22-4071-11e7-8a61-652fa768f6e9.png)

Anhand der Übersicht haben Herr Petrowski und Herr Schweder im Vergleich zu mir und Frau Kroll relativ wenig RBD-WE. Dieses sollte in die Monatsplanung mit einbezogen werden. Herr Schweder hat im Juli 3 Wochen Urlaub. 

Herr Petrowski hat für den Monat Juli nicht einen einzigen WE -Dienst. Bitte überprüfen.

**Comment by chrbusch** [comment]
Herr Schweder hat im Juli Urlaub bis 23.7., und am 24.7. erstmalig RBD, ist das falsch?

Ich rechne jetzt alles noch einmal automatisch und beobachte genau, wer warum dran kommt

**Comment by Toelk-A** [comment]
Herr Schweder ist korrekt.
Okay, dann geben Sie mir bitte Rückmeldung. Danke

**Comment by chrbusch** [comment]
Bitte Ticket schliessen und ggfs. Ende Juni NEUES Ticket erstellen

**Comment by Toelk-A** [comment]
Es scheint Rechenfehler in der Dienstübersicht zu geben (gelbe Markierung)
Herr Schweder und Frau Kroll haben bis Juli Dienste. Diese sind noch nicht in die Dienstübersicht übernommen worden. Bitte aktualisieren.

![image](https://cloud.githubusercontent.com/assets/22314271/26571384/0503b954-4516-11e7-8cf6-dd2f2931ca5d.png)

**Comment by Toelk-A** [comment]
![image](https://user-images.githubusercontent.com/22314271/27422280-d1e8f014-572d-11e7-9ad7-48656d4d1074.png)

Stand 22.06.2017 bitte alle Mitarbeiter auf den aktuellen Stand bringen - hier scheint nach wie vor der Automatismus (Berechnung nach Erstellung des Dienstplanes) nicht zu funktionieren - bitte Fehler beheben

**Comment by chrbusch** [comment]
Erledigt
