### ISSUE TITLE
Bitte Anschrift im Entnahmebericht vollständig abbilden

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#181]
Nach wie vor wird im Entnahmebericht die Adresse von Dr. Nitschke nicht vollständig abgebildet. Dieser Fehler wurde bereits mehrere Male behoben.
ID 1934

![image](https://cloud.githubusercontent.com/assets/22314271/25621927/285f5184-2f53-11e7-907e-fbfb64df6d78.png)

**Comment by chrbusch** [comment]
Passt es jetzt?
