### ISSUE TITLE
Änderung menschenlesbarer Barcode "Eingang Bank"

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#182]
Bitte nur bei "Eingang Bank" im Barcode und menschenlesbar die "Präparatenummer" abbilden ("C" wird hier durch "O" ersetzt).

Das heißt rechtes Auge wäre "2017-xxx-GMV-OD" bzw. links "2017-xxx-GMV-OS"

Danke

![image](https://cloud.githubusercontent.com/assets/22314271/25650971/b38d2046-2fe0-11e7-8858-c2048a670036.png)

**Comment by Toelk-A** [comment]
Bitte wie oben angegeben, die bankinterne Nummer mit der Ausnahme "O" anstatt "C" angeben:

2017-xxx-GMV-OD
2017-xxx-GMV-OS

**Comment by chrbusch** [comment]
Wie erscheint es denn jetzt??
Bitte Teilbild hier einstellen

**Comment by Toelk-A** [comment]
Der Bankeingang soll wir oeben beschrieben abgebildet werden:

2017-xxx-GMV-OD
2017-xxx-GMV-OS

Die rote Markierung  zeigt die Präparatenummer. Wir benötigen an dieser Stelle aber die bankinterne Nummer. Anstelle des CD soll aber OD bzw OS abgebildet werden (siehe gelbe Markierung)

![image](https://cloud.githubusercontent.com/assets/22314271/25693213/61162b6e-30a8-11e7-9417-9241c27169a7.png)

**Comment by chrbusch** [comment]
"Wir benötigen an dieser Stelle aber die bankinterne Nummer. Anstelle des CD soll aber OD bzw OS abgebildet werden "
Das heißt, hier erfinden wir NOCH eine KennNr, die es sonst im System nicht gibt??

**Comment by chrbusch** [comment]
Ich habe nun die Bank.int. Nr genommen und ersetze "-CD" gg."-OD" und "-CS" gg. "-OS", bitte testen

**Comment by Toelk-A** [comment]
ID 1968

Bankeingang "rechte Seite" ist richtig abgebildet, Bankeingang "linke Seite (roter Unterstrich) muss das "C" durch "O" ersetzt werden

![image](https://cloud.githubusercontent.com/assets/22314271/25846060/b3ab9394-34b0-11e7-9734-54e9638561d1.png)

**Comment by chrbusch** [comment]
try again...
