### ISSUE TITLE
Bestellung Ornella - Mandanten wählen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#183]
Bitte als Absender (= Lieferadresse) die Mandanten  GTM-V oder GBM-V hinterlegen.

Hierzu könnte ein Dialogfenster bei jeder neuen Bestellung programmiert werden bei dem der entsprechende Mandant angeklickt werden könnte.

**Comment by chrbusch** [comment]
r.o. können Sie nun den Mand. wählen
