### ISSUE TITLE
PDF Bestellung Ornella - Text unvollständig abgebildet

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#184]
Bitte den Standardbestellungstext vollständig abbilden (Bestellposten 4 Zeilen nach unten verschieben?).

![image](https://cloud.githubusercontent.com/assets/22314271/25664157/11170310-301a-11e7-9670-2022e0744eb6.png)

**Comment by chrbusch** [comment]
Nun ca. 5 Zeilen mehr Platz
