### ISSUE TITLE
PDF Bestellung - Standard Fußzeile anlegen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#185]
Können wir die Standardfußzeile selbst anlegen?

**Comment by chrbusch** [comment]
Es gibt doch gar keine Fußzeile bei Bestellungen? Oder was ist hier gemeint?

**Comment by Toelk-A** [comment]
Könnte ein "Nachtext" - indiesem Fall haben wir nur ein Foto- als Standard im System hinterlegt werden?

z.B.:

**Comment by Toelk-A** [comment]
![image](https://cloud.githubusercontent.com/assets/22314271/26061021/0ecbf284-3987-11e7-8655-d542abb42600.png)

**Comment by chrbusch** [comment]
Das macht verm. den Ausdruck unscharf und erlaubt such nur schwer Anpassungen!
Das Bild enthält doch nur TEXT, der kann doch in das neue Feld?
