### ISSUE TITLE
Inventur - Warenkorb OG

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#186]
Bitte das Feld "Anzahl" (siehe Anlage) freigeben, so dass wir die aktuelle Anzahl von Jod und NaCl (Warenkorb OG) im System hinterlegen können.

Morgen wollen wir 5 "Testwarenkörbe" OG anlegen -> Barcodes drucken und scannen. Der abgescannte Warenkorb OG müsste dann im Entnahmebericht OG unter "Verwendete Materialien" einscannbar sein. Ist diese Funktion -Button  "Warenkorb/Artikel scannen" bereits programmiert?

![image](https://cloud.githubusercontent.com/assets/22314271/25665252/5138d100-301d-11e7-819c-1d2872e7c8be.png)

**Comment by chrbusch** [comment]
Feld Anzahl ist frei gegeben, aber wir müssen hierüber sprechen!
Hier Zahlen manuell einzugeben umgeht den ganzen Formalismus zu LotNr etc; könnten Sie stattdessen eine Bestellung (!) anlegen und die gezählten Bestände als BESTELLTE ANZAHLEN eintragen? Dann machen wir einen Pseudo-Wareneingang und alles ist sauber!

**Comment by Toelk-A** [comment]
Wenn wir eine "Bestellung" anlegen, darf diese aber nicht in das Ornellarechnungswesen eingehen, da die gelieferten Artikel ja schon bezahlt sind. Wenn wir diese Bestellung als "Pseudowareneingang" markieren können, dann können Sie das "Anzahl" Feld wieder blockieren. Bitte geben Sie hierfür schnell Rückmeldung, sodass wir mit dem Barcode drucken beginnen können. Danke

**Comment by chrbusch** [comment]
Auf welchem Etikettenformat sollen die Warenkorb-Etik. gedruckt werden?

**Comment by Toelk-A** [comment]
wie abgesprochen bleiben wir bei dem Format der "Blutprobenetiketten"

**Comment by Toelk-A** [comment]
Update: wir lassen die Etiketten so wie Sie von Ihnen programmiert wurden -> MSG Etiketten
