### ISSUE TITLE
Artikeldetails - Artikelbasisdaten - Lieferanten des Artikels - Bitte Änderungen einarbeiten

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#187]
Bitte folgende Änderungen einarbeiten:

1) Überschrift "B.-Einh" bitte in "Stück pro Packung" umbenennen
2) Bitte daneben weitere Spalte mit der Überschrift "Bestelleinheit" einfügen.

![image](https://cloud.githubusercontent.com/assets/22314271/25701952/fb99f564-30ce-11e7-97e7-45724c3f2ee5.png)

**Comment by chrbusch** [comment]
Erl.
