### ISSUE TITLE
Weiteres Vorgehen konkreter Warenkorb -> Verwendete Artikel im Entnahmebericht abbilden

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#188]
1) Barcode des konkreten Warenkorbs ausdrucken
-> dies haben wir bereits telefonisch besprochen und funktioniert super

2) Einscannen des Barcodes (konkreter Warenkorb) nach Entnahme im Entnahmebericht

-> hier haben sie bereits einen Button "Warenkorb/Artikel scannen" angelegt
![image](https://cloud.githubusercontent.com/assets/22314271/25743427/98e4527c-3194-11e7-8c57-520ec1652bf9.png)

Dieser Button muss fertig programmiert werden, sodass wir in den Entnahmebericht die verwendeten Materialien einscannen können. Dies bedeutet:

- Einscannen des "konkreten Warenkorb" Barcodes (menschenlesbar muss im Entnahmebericht aber das hinterlegte Material des Warenkorbes abgebildet sein d.h. Bezeichnung + Chargennnummer + MHD) 

- Einscannen weiterer verwendeter Materialien, die nicht im Warenkorb hinterlegt sind. Hierfür muss der Entnahmebericht die Barcodes der Chargennummer + MHD (die auf die Umverpackungen nach Wareneingang angebracht werden) lesen können. Die menschenlesbare Abbildung enstprechend siehe oben.

Bitte programmieren Sie dies unbedingt fertig, da wir sonst eine erneute Inventur durchführen müssen.

**Comment by Toelk-A** [comment]
Die im Entnahmebericht eingescannten Materialien (also Artikel des konkreten Warenkorbs und zusätzliche Artikel) müssen im Gesamtbestand automatisch abgezogen werden.

**Comment by chrbusch** [comment]
Sorry, aber hierbei handelt es sich um komplexe Eingriffe in die Datenbank, die gar nicht durchgeführt werden können, während Sie arbeiten; und weil ich auch Druckmasken umbauen muss, ist ein kleiner Laptop äußerst unpraktisch hierfür.
Realistisch kann ich das daher erst in Hamburg am Wochenende erledigen, wenn ich bei Ihnen das System schliessen kann.
Ich schlage vor, dass Sie sich bis dahin helfen mit einer Excel-Liste, bei der Sie jede Entnahme eines Artikels in eine eigenen Zelle scannen; diese kann ich dann importieren und von den Bestände abziehen.

**Comment by chrbusch** [comment]
Moin!
Sie dürfen den Scanbutton nun testen für den WaKo.
Auch für die ZusatzPos mache ich das jetzt jetzt gleich fertig
![bildschirmfoto 2017-05-12 um 07 07 41](https://cloud.githubusercontent.com/assets/1241899/25983026/e87348c8-36e1-11e7-8b59-e3e2fb89ecfe.JPG)

**Comment by chrbusch** [comment]
Nun sind beide ScanButtons realisiert; Ergebnis etwa so?

![bildschirmfoto 2017-05-12 um 07 45 31](https://cloud.githubusercontent.com/assets/1241899/25983768/0b395b54-36e7-11e7-8f26-9393eee81ec4.JPG)

**Comment by chrbusch** [comment]
Wir müssen nun noch genau besprechen, WANN die Bestände gesenkt werden;dies ist aber ein anderes Thema, für das ich jetzt ein neues Ticket erstelle.
Bitte HIER nur dies diskutieren: Scannen, Zuordnen, Ausdrucken der WaKo-Zuordnung

**Comment by Toelk-A** [comment]
Das Einscannen des Warenkorbes sowie des Zusatzartikels funktioniert wunderbar.

Die gelb markierten Textfelder sollen in Zukunft nicht im Entnahmebericht abgebildet werden.

![image](https://cloud.githubusercontent.com/assets/22314271/26060802/6dc0bf32-3986-11e7-844b-284edba421d9.png)

**Comment by chrbusch** [comment]
Erl.

**Comment by Toelk-A** [comment]
Bitte noch : Anz... entfernen (siehe gelbe Markierung)

![image](https://cloud.githubusercontent.com/assets/22314271/26305240/c7bb0ab6-3eee-11e7-8680-1e5ce1cc0b7e.png)

**Comment by chrbusch** [comment]
erl.
