### ISSUE TITLE
Tauschfunktion RBD Plan funktioniert nicht

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#189]
am 04.05. 17 stehe ich mit Rufdienst drin, Herr Maschmeier hatte aber meinen Dienst übernommen. Warum ist die Tauschfunktion nicht anklickbar?

Bitte bearbeiten

![image](https://cloud.githubusercontent.com/assets/22314271/25845334/d4ef3e82-34ad-11e7-89d6-a98a21a4bf09.png)

**Comment by chrbusch** [comment]
Tauschwünsche kann man nur für die Zukunft anmelden! 
Das erscheint mir auch sinnvoll.
Der 4.5. ist Vergangenheit

**Comment by chrbusch** [comment]
Sollte jetzt klappen

**Comment by Toelk-A** [comment]
Als Supervisor im Menüpunkt RBD Tausch/Wünsche fehlt noch immer der Tauschbutton

![image](https://cloud.githubusercontent.com/assets/22314271/25886620/b3d6cd58-355e-11e7-9e6f-0501f93fb4db.png)

**Comment by chrbusch** [comment]
Jetzt sichtbar? Andernfalls bitte gemeinsam per Teamviewer ansehen
