### ISSUE TITLE
Artikelbestände, Warenkörbe, Bestandsverwaltung

### ISSUE THREAD

**Issue by chrbusch** [chrbusch/GTM-V#190]
Wann genau sollen Bestände gesenkt werden in dem Ablauf
WaKo zusammen stellen stellen
WaKo einem Entnahmebericht zuordnen
Zuzatzpos. zuordnen
Entnahmebericht drucken

Meine Vorstellung: Die Bestände der Artikelchargen ("AC") meinen die FREIEN, VERFÜGBAREN Anzahlen. Ist eine AC in einen WaKo gewandert, ist sie nicht mehr verfügbar, etwa für weitere WaKos.
Auch für die Frage, ob Artikel nachbestellt werden müssen, können die bereits in WaKo gelegten Stücke ignoriert werden.

**Daher sollten m.E. die Bestände beim PACKEN der WaKos gesenkt werden.**

Bitte dies intern gründlich diskutieren.

**Comment by Toelk-A** [comment]
1) Die Bestände sollen beim Packen des Warenkorbes gesenkt werden.

2) Artikel die nicht im Warenkorb hinterlegt sind, müssen ebenfalls nach Benutzung vom Bestand abgezogen werden können. Hierfür müsste ein Feld zum "Ausscannen" programmiert werden".

**Comment by chrbusch** [comment]
Ad 1.) Bitte noch einmal ganz kurz beschreiben, welche Buttons in Ornella Sie für das Packen neuer WaKos benutzen
 Ad 2.) Kann das nicht passieren, wenn auf dem EntnBericht ein ZusatzArtikel gescannt wird?

**Comment by Toelk-A** [comment]
1)

Button "neuer konkreter Warenkorb"
Bezeichnung: XXX
Bereich: 
Button "neue Position" -> Artikel in Warenkorb einscannen

Button "Barcode drucken"




Vorher legte ich sog. "virtuelle Warenkorb" an...  Was nun der Unterscheid ist weiß ich nicht recht.

**Comment by chrbusch** [comment]
Der Button r.o. beim WaKo, "Etiketten..ausbuchen" funktioniert jetzt!

**Comment by chrbusch** [comment]
Scannen einer ZusatzPos beim EntBericht senkt nun auch den Bestand

**Comment by chrbusch** [comment]
Im HM ist nun rechts oben ein neuer Button "Artikel ausscannen", der m.E. funktioniert
Ist damit alles Dringliche zu diesem Thema erledigt?

**Comment by Toelk-A** [comment]
erledigt
