### ISSUE TITLE
Hämodilution funktioniert wieder nicht - unterschiedliche Entnahmezeitpunkte separat behandeln

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#191]
Spender ID 1989
Bitte überprüfen Sie die Hämodilution.

Es sind 2 verschiedene Entnahmezeitpunkte hinterlegt:
1) 10.05.17
2) 09.05.17

Bei Zeitpunkt 1) werden die Daten vom 09.05.17 übernommen. Bitte schnellstmöglich korrigieren.

**Comment by chrbusch** [comment]
Gut gebrüllt Löwe!
Da haben Sie einen schwer zu findenden Programmierfehler entdeckt, der nur bei genau gleicher Abnahmezeit auftrat. Ich meine, es ist jetzt korrigiert, aber evt. noch einmal mit einem Testspender ausprobieren: Datum verschieden, Abnahmezeit gleich, ist es dann OK?
