### ISSUE TITLE
Abrechnung mit der Bank

### ISSUE THREAD

**Issue by chrbusch** [chrbusch/GTM-V#192]
FNi liefert Details...

**Comment by chrbusch** [comment]
In diesem Rahmen wird cbu die Tabelle für die kunden.-spezif. Preise realisieren

**Comment by Nitschke-FP** [comment]
Prozessschritt: Gewebebereitstellung der GTM-V an die Gewebebank:
1. wenn im Entnahmebericht (OG/MSG/KVG) die Gewebeprozessierende Einrichtung und der Zeitpunkt der Entnahme (Datum und Zeit) dokumentiert ist und der Zeitpunkt der Entnahme (Datum und Zeit) gleich dem Systemdatum ist, dann generiere eine Mail an die Gewebebank, dass die im Entnahmebericht entnommenen Gewebe der Bank avisiert werden. Wenn es möglich ist, sollte auch der Anlieferungszeitpunkt mit angekündigt werden. Der berechnet sich aus Entnahmezeit + 2 Stunden Logistik + Fahrzeit zwischen Entnahmeort und Gewebebank (Berechnung Prio 3).
2. Die an die Bank gelieferten Gewebe werden in Ornella zu Transplantaten verarbeitet, wobei jedes Transplantat eine eigene ID und das Feld "Von Bank akzept.?" besitzt. Wenn die Bank das Transplantatakzeptiert hat, muß eine Rechnung erstellt werden von der GTM-V an die Gewebebank (i.d.R. GBM-V). Die Preise für die Transplantate werden in die Tabelle Kundenspezifische Preise durch die GTM-V eingepflegt. Das System sollte einmal am Tag, am optimalsten 12 Uhr schauen, ob neue Transplantate akzeptiert worden sind und dann diese z.B. in der Transplantat Liste (allgemein) anzeigen. Über den Button "gezeigte Transplantate abrechnen" sollte dann ein Dialog erscheinen, wo zwischen der Abrechnung von der GTM-V an die Bank oder der GTM-V an die transplantierende Einrichtung ausgewählt werden kann.

**Comment by chrbusch** [comment]
Ad 1) An welche Emailadresse geh das? Es ist doch nicht immer GBMV, aber woher weiss ich das auf Basis des Entn.Berichtes?
Wie sollen Betreff und der Text lauten?

**Comment by Nitschke-FP** [comment]
Emailadresse bekommen Sie Morgen, wird in der Adressdatenbank entsprechend hinterlegt, ggf. muß hierfür ein extra Adressfeld generiert werden.
Im Betreff soll stehen: Ankündigung Gewebepräparate „Spenderkennnummer“
Text: Die folgenden Gewebe wurden entnommen am 01.05.2017 um 19:30:00:
Spender:010517-0857-GNO-KRJ | König, Siegfried; m; Alter 60 J., Postmortemzeit: hh:mm (Differenz zwischen Herzkreislaufstillstand/Perfusionsbeginn und Entnahmezeitpunkt
010517-0857-GNO-KRJ-OD
010517-0857-GNO-KRJ-OS
Entnahmeeinrichtung:DRK Krankenhaus Grevesmühlen
Prosektur
Klützer Straße 13-15
23936 Grevesmühlen

Entnehmer:Kroll, Judith
GTM-V, Wilhelm-Külz-Platz 3, 18055 Rostock

LG
F.-P. Nitschke


Mit freundlichen Grüßen

Dr. med. Frank-Peter Nitschke
Geschäftsführender Arzt

[id:image001.png@01D1F158.CFDCB8A0]

GTM-V Gesellschaft für Transplantationsmedizin
Mecklenburg-Vorpommern
gemeinnützige GmbH
Wilhelm-Külz-Platz 3
18055 Rostock

'           +49 381 444 30 50
7            +49 381 444 30 525
Mobil:       +49 171 222 26 06
@       frank-peter.nitschke@gtm-v.de<mailto:frank-peter.nitschke@gtm-v.de>
•          www.gtm-v.de<http://www.gtm-v.de/>

USt-IdNr.: DE 298945377 Amtsgericht Rostock, HRB 13143 Geschäftsführer:          Dr. med. Frank-Peter Nitschke
                                     Dr. med. Axel Manecke

Diese Email enthält vertrauliche und/oder rechtlich geschützte Informationen. Jeglicher unbefugter Gebrauch oder Verbreitung dieser Nachricht oder Auszüge dieser Nachricht ist strengstens verboten. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail.

This e-mail may contains confidential and/or privileged information. Any unauthorised usage or dissemination of this message in whole or in part is strictly prohibited. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail.

Von: chrbusch <notifications@github.com>
Antworten an: chrbusch/GTM-V <reply@reply.github.com>
Datum: Mittwoch, 17. Mai 2017 um 11:01
An: chrbusch/GTM-V <GTM-V@noreply.github.com>
Cc: "Dr. Frank-Peter Nitschke" <frank-peter.nitschke@gtm-v.de>, Comment <comment@noreply.github.com>
Betreff: Re: [chrbusch/GTM-V] Abrechnung mit der Bank (#192)


Ad 1) An welche Emailadresse geh das? Es ist doch nicht immer GBMV, aber woher weiss ich das auf Basis des Entn.Berichtes?
Wie sollen Betreff und der Text lauten?

**Comment by chrbusch** [comment]
Es gibt nun ein neues Extrafeld für die Email, an die der Avis geht; bitte bei den Banken ausfüllen.

![bildschirmfoto 2017-05-17 um 16 35 30](https://cloud.githubusercontent.com/assets/1241899/26159498/02ef337e-3b1f-11e7-918a-1c5904c523e5.JPG)

**Comment by chrbusch** [comment]
Sie sollten soeben eine korrigierte Email erhalten haben, bitte kritisch ansehen

**Comment by chrbusch** [comment]
Wie soll ich die FAHRZEIT berechnen??

**Comment by Nitschke-FP** [comment]
Adresse Bank und Entnahmeeinrichtung via gogglemaps und dann 80 km/h?

Mit freundlichen Grüßen

Dr. med. Frank-Peter Nitschke
Geschäftsführender Arzt


[test2]

GTM-V Gesellschaft für Transplantationsmedizin
Mecklenburg-Vorpommern
gemeinnützige GmbH
Wilhelm-Külz-Platz 3<x-apple-data-detectors://10>
18055 Rostock<x-apple-data-detectors://10>

Telefon:    +49 381 444 30 50<tel:+49%20381%20444%2030%2050>
Fax:          +49 381 444 30 525<tel:+49%20381%20444%2030%20525>
Mobil:       +49 171 222 26 06<tel:+49%20171%20222%2026%2006>
Mail:         frank-peter.nitschke@gtm-v.de<mailto:stephan.petrowski@gtm-v.de>
Web:         www.gtm-v.de<http://www.gtm-v.de/>

USt-IdNr.: DE 298945377<tel:298945377>
Amtsgericht Rostock, HRB 13143
Geschäftsführer:          Dr. med. Frank-Peter Nitschke
                                     Dr. med. Axel Manecke

Diese Email enthält vertrauliche und/oder rechtlich geschützte Informationen. Jeglicher unbefugter Gebrauch oder Verbreitung dieser Nachricht oder Auszüge dieser Nachricht ist strengstens verboten. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail.

This e-mail may contains confidential and/or privileged information. Any unauthorised usage or dissemination of this message in whole or in part is strictly prohibited. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail.

Am 17.05.2017 um 17:07 schrieb chrbusch <notifications@github.com<mailto:notifications@github.com>>:


Wie soll ich die FAHRZEIT berechnen??

**Comment by chrbusch** [comment]
Ist m.E. alles fertig, inkl. Entfernungsschätzung. Können SIe mir bitte einen Entnahmebericht nennen, bei dem ALLE Daten vorhanden sind, also PLZ. Emailadresse der Bank usw?

Emailtext ist nun
Die folgenden Gewebe wurden entnommen am 01.05.2017 um 19:30:00:
Spender:König, Siegfried, m; Alter 60 Jahre, Postmortemzeit: 12,67 Std.
010517-0857-GNO-KRJ-OD
010517-0857-GNO-KRJ-OS
Entnahmeeinrichtung:DRK Krankenhaus Grevesmühlen
Prosektur
Klützer Straße 13-15
23936 Grevesmühlen 

Entnehmer:Kroll, Judith
GTM-V, Wilhelm-Külz-Platz 3, 18055 Rostock

Geschätzte Ankunftszeit:01.05.2017 22:19

**Comment by chrbusch** [comment]
Ich schreibe jetzt ein neues Ticket, das NUR die zu erstellende Rng behandelt
