### ISSUE TITLE
Persönlicher Kalender- Stundenübersicht - zur Zeit zweimaliger Eintrag der Anfangsuhrzeit notwendig

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#193]
Trägt man die Anfangsuhrzeit ein so befindet sich immer ein "?" in dem Kästchen

![image](https://cloud.githubusercontent.com/assets/22314271/26305136/55a6c294-3eee-11e7-9194-90493bbacd39.png)

klickt man anschließend in das selbe Kästchen so befindet sich neben dem Uhrzeiteintrag zusätzlich ein ":*"

![image](https://cloud.githubusercontent.com/assets/22314271/26305157/7489ad2a-3eee-11e7-8e51-bc6a247ea8da.png)

Bitte ändern Sie dies. Ansonsten muss die Anfangsuhrzeit immer 2x eingetragen werden

**Comment by chrbusch** [comment]
Jetzt besser?

**Comment by Toelk-A** [comment]
![image](https://cloud.githubusercontent.com/assets/22314271/26396172/b4a4eab6-4072-11e7-9c02-b658e372749a.png)

![image](https://cloud.githubusercontent.com/assets/22314271/26396184/bf52152e-4072-11e7-86c1-c0225b3c97be.png)

leider nein

**Comment by chrbusch** [comment]
Habe die Schrift etwas kleiner gemacht, jetzt müsste es aber passen
