### ISSUE TITLE
Bericht für geleistete Überstunden

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#194]
Wir benötigen zum Ende jeden Monats einen Bericht, der die geleisteten Überstunden - in Anlehnung an Dr. Maneckes Zuarbeit - für unser Steuerbüro abbildet. Hierbei sollte die Tabellenform übernommen werden in der ebenfalls die jeweiligen (steuerfreien/steuerpflichtigen) Zuschläge aufgezeigt sind.

Des Weiteren soll der Mitarbeiter die Gelegenheit haben sich die geleisteten Überstunden auszahlen lassen zu können. Hierfür müsste ein Eingabefenster "Auszahlung Überstunden (steuerfrei oder steuerpflichtig)" erstellt werden. Diese Auszahlung soll ebenfalls in dem Bericht vermerkt werden und muss natürlich von den geleisteten Überstunden abgezogen werden.

**Comment by Toelk-A** [comment]
3) Auf dem o.g. Bericht müssen ebenfalls Unterschriftenfelder abgebildet sein:

-Datum Unterschrift Mitarbeiter
-Datum Unterschrift Geschäftsführer

**Comment by Toelk-A** [comment]
Das Monatsende Juni naht. Welche Informationen benötigen Sie um den Bericht für geleistete Überstunden fertigstellen zu können?

**Comment by chrbusch** [comment]
Bitte mit Dr. manecke besprechen; er bat mich zu warten, bis die Erfassung besser geregelt ist.
cbu

**Comment by Toelk-A** [comment]
1) Zur Berechnung:

![image](https://user-images.githubusercontent.com/22314271/27391335-03c3830e-56a4-11e7-8eb6-83b26a5ac572.png)

"Basis" und "Std" müssen addiert nicht multipliziert werden.   AZK= Summe aus Basis und Std.

2) Die geleisteten Überstunden werden nicht berechnet (gelbe Markierung).

![image](https://user-images.githubusercontent.com/22314271/27391696-e69a5de2-56a4-11e7-935a-1ffe0e0f01f1.png)

3) Die geleisteten Überstunden unter der Woche (02.06.2017) werden nicht abgebildet nachdem auf "Überstunden setzen" geklickt wurde. (rote Markierung)

**Comment by chrbusch** [comment]
Bitte die Screenshots so erstellen, dass ich alle relevanten Felder sehen kann. Hier fehlt links v.a. der Name des Mitarb.

**Comment by chrbusch** [comment]
Am 2.6.17 gibt es eine Aktivität nur an einem Fr innerhalb der Bereitschaftszeit; dafür gibt es keinen Zuschlag.
Und die Stunden selbst stehen ja links; es fallen daher m.E. nur die 2 Stunden für den RBD an.
Oder gilt der Zuschlag am Fr wie für Sa+So?

**Comment by Toelk-A** [comment]
Für jede Rufbereitschaft (egal ob aktive Arbeitszeiten anfallen oder nicht) bekommt man immer entweder 1h (werktags) oder 2h (WE/FT) gutgeschrieben. Diese "Bereitschaftsstunden" dürfen nur abgebummelt - nicht ausgezahlt - werden.

**Comment by Toelk-A** [comment]
Zum Screenshot: dies ist mein persönlicher Kalender: Anita Tölk

**Comment by Toelk-A** [comment]
Ich kann noch immer meine Überstunden nicht setzen Freitag und Samstag. Nach Klicken des Buttons "Überstd. setzen" passiert nichts

![image](https://user-images.githubusercontent.com/22314271/27538059-9d66ace0-5a76-11e7-930e-1a8e5cff59a0.png)

**Comment by Toelk-A** [comment]
Auch beim geleistetet RBD funktioniert der Button "Überstd. setzen " nicht vollständig. Es wird nur der RBD abgebildet, aber keine geleisteten Überstunden

![image](https://user-images.githubusercontent.com/22314271/27623720-02d0adca-5bde-11e7-8e9f-1fa57eebfba7.png)

**Comment by chrbusch** [comment]
Mir scheinen alle gezeigten Beispiele korrekt zu sein.
Bitte beschreiben, was Ihrer Ansicht nach resultieren sollte.
(Das ist fast IMMER die beste Art, einen Fehler zu beschreiben:Soll- und Ist-Ergebnis gegenüber stellen)

**Comment by Toelk-A** [comment]
An dem oben genannten Beispielen sollten folgendes geschehen:

27.06.17:
Soll Arbeitszeit 7h/ Ist Arbeitszeit: 7,75h d.h. es müssen die 0,75h (zusätzlich zum RBD 1h) in den Überstunden abgebildet werden.

**Comment by chrbusch** [comment]
Bitte anrufen damit wir prüfen können, ob bzw. in welchen Fällen jetzt die Überstunden korrekt ermittelt werden.

**Comment by Toelk-A** [comment]
Dieser Punkt hat nach wie vor die allerhöchste Priorität. Bitte melden Sie sich sobald Sie wieder in Hamburg sind.

**Comment by chrbusch** [comment]
Ist jetzt alles erledigt, oder? Dann bitte schliessen
