### ISSUE TITLE
Abbildung aktuelle Anzahl geleisteter Überstunden persönlicher Kalender

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#195]
Bitte fügen Sie in den persönlichen Kalender (Personalplanung) ein Fenster ein in dem jeder Mitarbeiter seine aktuelle Anzahl an Überstunden einsehen kann.

**Comment by chrbusch** [comment]
Ist das jetzt so ausreichend?

**Comment by Toelk-A** [comment]
Ist die Gesamtanzahl geleisteter Überstunden (nicht geleistete Überstunden pro Tag) abgebildet?

**Comment by Toelk-A** [comment]
Folgende Angaben sollen im persönlichen Kalender des jeweiligen Mitarbeiters in Form einer Tabelle abgebildet werden. Hierbei soll die Summe **aller noch nicht abgebummelten/ausgezahlten** (nicht nur die täglich geleisteten) Überstunden folgendermaßen abgebildet werden:

Überstunden (AZK) nicht auszahlbar
Überstunden (AZK) steuerpflichtig auszahlbar -> !abzüglich Warengutschein!
Überstunden (AZK) steuerfrei auszahlbar

Diese Tabelle könnte im folgenden Bereich des persönlichen Kalenders (rote Markierung) abgebildet werden:

![image](https://user-images.githubusercontent.com/22314271/29414334-a21ba9e0-835f-11e7-90c6-f8c546994e3d.png)

**Comment by chrbusch** [comment]
Bitte Ticket schliessen, falls erledigt.
