### ISSUE TITLE
Status AZK = Arbeitszeitkonto = Überstunden vom Konto abziehen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#196]
Wird im Team Kalender der Status "AZK" gewählt, so müssen für diesen Tag 8h vom Stundenkonto des "AZK"- Mitarbeiters abgezogen werden. Ausnahme ist im Moment Herr Maschmeier, der noch nicht Vollzeit arbeitet.

**Comment by chrbusch** [comment]
Ich denke, dies sollten wir bei Abarbeitung des Monatsprotokolls tun.
Bitte hierzu anrufen
