### ISSUE TITLE
Bestellungen GTM-V und GBM-V  // gleicher Lieferant unterschiedliche Kundenummern

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#197]
Da die GTM-V und GBM-V teilweise die gleichen Lieferanten und Hersteller nutzen müssten wir eine Lösung hinsichtlich der Kundennummern finden.

Mein Vorschlag:

In der Adresse des Lieferanten ein weiteres Feld "Kundennummer GBM-V" hinzufügen und das bereits vorhandene Feld "Kundennummer" in "Kundennummer GTM-V" umbenennen.

Wird später bei den Bestellungen das Mandat GTM-V gewählt, so sollte dementsprechend auf die GTM-V Kundennummer des Lieferanten/Herstellers zugegriffen werden.

Bitte schnellstmöglich umsetzen.

**Comment by chrbusch** [comment]
Erl.

**Comment by Toelk-A** [comment]
![image](https://cloud.githubusercontent.com/assets/22314271/26396253/f0bc6b46-4072-11e7-99fa-2e2cad571fcf.png)

![image](https://cloud.githubusercontent.com/assets/22314271/26396279/060f76a0-4073-11e7-811d-0e90f7496c2a.png)

Kundennummer GTM-V = "Test" - taucht in der Bestellung nicht auf

**Comment by chrbusch** [comment]
Rennt jetzt

**Comment by Toelk-A** [comment]
Kundennummer wird noch nicht übernommen... Beispiel alpha Apotheke... Kundennummer eingetragen:


![image](https://cloud.githubusercontent.com/assets/22314271/26546618/3337a408-446b-11e7-85a7-28b0d28b9a13.png)


![image](https://cloud.githubusercontent.com/assets/22314271/26546656/62005230-446b-11e7-9b9a-c7150901256a.png)

**Comment by chrbusch** [comment]
Die gezeigte Bestellung ist ja auch 3 Wochen alt!
AB LETZET WOCHE wird die KdNr übernommen in die Bestellung
