### ISSUE TITLE
Bitte Lager benennen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#198]
Bitte die Ziffern folgendermaßen beschriften

1 - Kühltruhe
2 - Kühlschrank
3 - Lagereingang
4 - Zwischenlager
5 -
6 -

**Comment by Toelk-A** [comment]
![image](https://cloud.githubusercontent.com/assets/22314271/26400771/f87beef0-4082-11e7-8b9c-3e6a145aa21d.png)

**Comment by chrbusch** [comment]
Die Namen waren versehentlich verschwunden, jetzt wieder sichtbar
