### ISSUE TITLE
Stück pro Packung - bei Wareneingang bitte automatisch aufmultiplizieren

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#199]
Beispiel Artikel Enukleationsset Raguse ID 86

![image](https://cloud.githubusercontent.com/assets/22314271/26543185/254e8f68-445d-11e7-8e8e-d53acd077fe6.png)

Wir haben 12 Artikel pro Umverpackung (Karton). Geben wir beim Wareneingang "3" Kartons erhalten ein, so muss Ornella den Bestand automatisch mit der Anzahl "Stück pro Packung" multiplizieren (3*12 = 36 Artikel vorhanden). Im Moment geben wir den Bestand noch per Hand ein. Bitte schnellstmöglich ändern, da wir heute die Inventur machen wollen.

![image](https://cloud.githubusercontent.com/assets/22314271/26543232/6240db1a-445d-11e7-8b07-6fe11917115f.png)

**Comment by chrbusch** [comment]
1. Ich habe die Chargen nach oben geschoben, unten nun die dazu gehörenden Bestände.
2. Oben ist neuer Button "Intentur:Eingabe", der erst nach Anzahl PACKUNGEN und dann nach EINZELartikeln fragt, bitte testen
