### ISSUE TITLE
Referenzwarenkorb OG MSG und KVG

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#201]
Beim Erstellen eines neuen Warenkorbes, soll Ornella den Inhalt auf Vollständigkeit mit einem Referenzwarenkorb prüfen.

Wie können wir dies Umsetzen?

**Comment by chrbusch** [comment]
Prozedur ist m.E. fertig programmiert; ich warte auf korrektes Dupl.-Vorbild für OG_WaKo, dann test eich erst einmal selbst

**Comment by Toelk-A** [comment]
1) ID 20 Ist unser Referenzwarenkorb OG -> diesen können Sie testen.
Wir möchten hiervon 13 Warenkörbe erstellen -> diese Artikel müssen aus dem Bestand abgezogen werden. 

2) Weiterhin muss im System auftauchen, dass wir "13 Warenkörbe OG" haben.
Diese könnten in einem Zusatzbutton im Ornellahauptmenü "Bestand Warenkörbe" hinterlegt sein.

**Comment by chrbusch** [comment]
Bitte hierzu anrufen; die Jodlösung gibt es NUR im Lager 2, die NaCl-Lösung NUR in Lager 7 -.
Wir hatten aber vereinbart, dass alle Artikel aus demselben Lager kommen.

**Comment by chrbusch** [comment]
Das Script fragt nun nach dem EINEN Lager, der gewünschten WaKo-Anzahl und PRÜFT dann vorher, ob es für jeden der erforderl. Artikel in diesem Lager ausreichend Bestand gibt.
Ist das clever oder ist das clever?

**Comment by Toelk-A** [comment]
Waren umlagern funktioniert derzeit nicht. Bitten überprüfen Sie Ornella (Nacl sollte aus dem Zwischenlager in den Kühlschrank gelagert werden, sodass OG Warenkorb erstellt wird).

**Comment by Toelk-A** [comment]
funktioniert super - siehe Ticket #207
