### ISSUE TITLE
Zusatzposition auscannen - Zusatzposition vor Auscannen definieren - Kostenübersicht

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#202]
Zur Aufschlüsselung der Kosten einer Gewebeentnahme sollen die auszuscannenden Zusatzpositionen unter "OG", "KVG" oder "MSG" ausgebucht werden.

Hierzu könnten Sie ein Feld programmieren, das fragt "Zusatzposition auscannen für "Button" OG, Button "KVG" Button "MSG".

![image](https://cloud.githubusercontent.com/assets/22314271/26550363/b29404b4-447d-11e7-88a1-9ba85ee0e2aa.png)

Diese Einteilung der Zusatzpositionen  zu den jewiligen Geweben muss in ornella dokumentiert werden, sodass wir eine Kostenauflistung haben.

**Comment by Toelk-A** [comment]
Zur Verständigung "Zusatzposition" bitte durch "Artikel" ersetzen, war mein Fehler

**Comment by chrbusch** [comment]
Erledigt, bitte testen

![bildschirmfoto 2017-05-30 um 12 05 57](https://cloud.githubusercontent.com/assets/1241899/26578567/a7629930-4530-11e7-861b-e414a1fe2399.JPG)

**Comment by Toelk-A** [comment]
super Danke
