### ISSUE TITLE
Etikettendruck - Artikel /Warenkorb - Bitte Hinweis welches Etikett genutzt werden soll

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#203]
1) Etikettendruck "Barcode nach Eingang" bitte folgende Notiz einfügen "Bitte kleine Etiketten zum Druck nutzen"

![image](https://cloud.githubusercontent.com/assets/22314271/26550536/80ce1392-447e-11e7-9266-db89f3435f4c.png)

2) Etikettendruck "Warenkorb" bitte folgende Notiz einfügen "Bitte MSG-Etiketten zum Druck nutzen"

![image](https://cloud.githubusercontent.com/assets/22314271/26550579/a985d4f0-447e-11e7-903a-cd8c5fad5a45.png)

**Comment by chrbusch** [comment]
Bei großen und kleinen Etiketten kommt jetzt jeweils der Hinweis; dies kann aber aus techn. erst direkt vor dem Druck erfolgen.

**Comment by Toelk-A** [comment]
OK
