### ISSUE TITLE
Transportetiketten OG sind verändert worden, bitte rückgängig machen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#204]
ID 2100

![image](https://cloud.githubusercontent.com/assets/22314271/26620056/811ccb22-45e1-11e7-8104-9b9ed1462a07.png)

Etiketten wurden pro Seite 2x gedruckt mit der Beschriftung "Oculus links" und Oculus rechts" -> ähnlich der MSG Etiketten. Normalerwreise müsste hier Augengewebe in feuchter Kammer aufgeführt sein und nur 1 Drück pro Seite. Bitte überprüfen und ändern

**Comment by chrbusch** [comment]
Bei mir funktioniert das einwandfrei, bitte erneut testen und ggfs. gemeinsam per TeamViewer
