### ISSUE TITLE
Bitte weitere Lager einfügen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#205]
Morgen soll die Inventur in der GBM-V durchgeführt werden. Bitte folgende weitere Lager (für die GBM-V) einrichten:

- Hauptlager GBM-V
- Zwischenlager GBM-V
- Kühlschrank GBM-V
- Tiefkühler GBM-V
- Flüssigstickstoff GBM-V

**Comment by chrbusch** [comment]
Bitte versuchen Sie dies selbst über
HM/Supervisor/Lager definieren, dort Btn "Neues Lager"
(Ich möchte so wenig wie möglich unentbehrlich sein!)
