### ISSUE TITLE
Button Artikel zurückscannen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#206]
Manchmal kann es vorkommen, dass nicht alle Artikel aus einem Warenkorb bei der Entnahme verbraucht werden. Wir benötigen einen Button mit dem Artikel (die bereits mit dem Warenkorb ausgebucht sind) zurück in den Bestand gescannt werden können.

**Comment by chrbusch** [comment]
erledigt, bitte testen
