### ISSUE TITLE
Reduzierung Bestand Warenkorb nach Einscannen im Entnahmebericht

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#207]
Wir sind kurz vor dem Ziel :-)

Jetzt muss nur noch der Warenkorbbestand reduziert werden, nachdem er im OG bzw. später MSG und KVG Entnahmebericht eingescannt wurde.

Bitte porgrammieren Sie dies schnellstmöglich.

**Comment by chrbusch** [comment]
Das habe ich gerade auf dem EntnBericht so programmiert, bitte testen.

**Comment by Toelk-A** [comment]
funktioniert einwandfrei :-)
