### ISSUE TITLE
Rechnung - Einfügen Button "versandt"

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#208]
Rechnung Reiter Details&Position
Bitte fügen Sie unter dem Status einen Button ein "Versand". Dieser Button soll ähnlich dem Status "Druck01.06.2017/NIF" einen weiteren Status wie folgt abbilden "Versand Post /Mail 02.06.2017/USERKürzel"

"Post" oder "Mail" müsste vorher abgefragt werden.

Bitte programmieren Sie dies schnellstmöglich

**Comment by Toelk-A** [comment]
![image](https://cloud.githubusercontent.com/assets/22314271/26723109/3d056382-4793-11e7-94e3-b0f44a75c46a.png)

**Comment by chrbusch** [comment]
Erledigt
![bildschirmfoto 2017-06-07 um 08 48 36](https://user-images.githubusercontent.com/1241899/26865690-1da882de-4b5e-11e7-8f8c-cd6bed07daaa.JPG)

**Comment by Toelk-A** [comment]
funktioniert
