### ISSUE TITLE
Zugriffserlaubnis User KRJ auf Buchhaltung

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#209]
![image](https://cloud.githubusercontent.com/assets/22314271/26723160/71844178-4793-11e7-9632-30fb29442df9.png)

Bitte erlauben Sie Frau Kroll den Zugriff auf die Buchhaltung

**Comment by chrbusch** [comment]
Frau Kroll ist jetzt in der Rolle "Buchhaltung"; evt. müssen wir aber eine neue Rolle in der Art "Nicht-ärztl. Mitarbeiter mit Buchhaltung" erstellen?!

**Comment by Toelk-A** [comment]
Ja, bitte erstellen Sie die Rolle  "Nicht-ärztl. Mitarbeiter mit Buchhaltung"
