### ISSUE TITLE
Prozessschritt Freigabe Gewebeentnahme 

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#21]
-   Wenn mobile Teams „nein“ dann entfällt „Mobile Meldung am“ ist feintuning

**Comment by chrbusch** [comment]
In HRO gemeinsam machen

**Comment by Toelk-A** [comment]
ist dies erledigt?

**Comment by chrbusch** [comment]
Habe das heute endlich angesehen, brauche aber mehr Infos.
Was genau ist gemeint mit "dann entfällt „Mobile Meldung am“ ?

**Comment by chrbusch** [comment]
Ich denke, das Datumsfeld soll einfach ausgeblendet werden?
Bild MIT Mob. Team:
![image](https://user-images.githubusercontent.com/1241899/75234019-1b31bf00-57ba-11ea-92e8-41d9903f0a2a.jpeg)

Bild OHNE Mob. Team:

d_MobilesTeam_fuer_Entnahme_JaNein
