### ISSUE TITLE
Status OG Transplantate - "nicht freigegeben" dann rot hinterlegen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#211]
Manchmal erfolgt eine Allokation (Zuordnung einer Hornhaut zum Patienten) = Status "fest allokiert"   , bevor das Transplantat eigentlich den Status "Frei zur Allokation" erreicht. 

Hatte das Transplantat noch nicht den Status "frei zur Allokation" sondern wurde von "In Herstellung" zu "Fest allokiert" oder "Reserviert" verändert, so muss diese Hornhaut farblich markiert sein oder einen Hinweis enthalten "Achtung noch nicht freigegeben zur Allokation"

**Comment by chrbusch** [comment]
Bitte testen: Rechts neben dem grüne Allokations-Button sollte jetzt grellgelb eine entspr. Warnung erscheinen, aber das geht nur AB HEUTE also nicht für vergangene Allokationen

**Comment by chrbusch** [comment]
PS: Das neue Warnungs-feld kann künftig mit beliebigen Infos gefüllt werden; bitte dies auch den Ärzten mitteilen
