### ISSUE TITLE
Transportetiketten drucken - bitte Auswahl Gewebe einfügen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#212]
Sind mehrere Präparate unterschiedlicher Gewebe eines Spenders angelegt fügen Sie bitte eine Zwischenabfrage zum Etikettendruck ein:

"Welche Transportetiketten möchten Sie drucken : 1 Alle, 2 nur OG, 3 nur MSG"

![image](https://cloud.githubusercontent.com/assets/22314271/26724874/e2d27658-479b-11e7-9173-565a7a109803.png)

Danke

**Comment by chrbusch** [comment]
Bitte testen, zB mit Spender 1988, ich weiss ja, dass ich Ihnen IMMER ein Beispiel nennen soll :-)))
