### ISSUE TITLE
Spendermeldung Status des Transplantates im Feld "Arzt Abschluss" abbilden

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#213]
Wir stellen uns eine erweiterte Aufteilung im Abschnitt Arzt Abschluss -> Gewebe vor:

Gewebeart / Status Gewebe GTM-V / Status Gewebe GBM-V (entspricht Status "Transplantate dieses Spenders" / Bermerkungen

Es geht hauptsäschlich um OG und KVG
Für OG müssten sowohl CS als auch CD abgebildet sein, da unterschiedliche Status möglich sind.

**Comment by Toelk-A** [comment]
![image](https://cloud.githubusercontent.com/assets/22314271/26725418/c5e19cc4-479e-11e7-8917-14de2a3de264.png)

**Comment by chrbusch** [comment]
Das müssen wir besprechen, bitte hierzu anrufen

**Comment by Toelk-A** [comment]
Montag 26.06.2017 10-12:00Uhr

**Comment by chrbusch** [comment]
Erl. mit neuem Button "St.-Info"
![bildschirmfoto 2017-06-26 um 10 32 44](https://user-images.githubusercontent.com/1241899/27530891-d7594668-5a5a-11e7-9c69-368f128632b9.JPG)
