### ISSUE TITLE
Kleine Umstrukturierung Spenderdaten - Montag 26.06.2017 10-12:00Uhr

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#214]
Es können folgende Abschnitte in der Spenderdaten "gelöscht" also ausgeblendet werden:

1)  "Widerspruch gg. Spende"
2)  "Weitere Kennummern" ACHTUNG nicht den Eurocode SKS -> dieser soll unter der Spenderkennnummer abgebildet werden

Das Fenster "Blut Rückstellproben" könnte dann an Stelle des Feldes "Widerspruch gg Spende" abgebildet werden.

**Comment by chrbusch** [comment]
Alles erledigt.
Und wir haben jetzt Platz für eine Dgn zus.

**Comment by Toelk-A** [comment]
Dieser soll für Ticket #213 genutzt werden
