### ISSUE TITLE
SEC-Codes zur Erstellung der Etiketten Herstellung und Versand KVG

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#215]
![image](https://cloud.githubusercontent.com/assets/22314271/26726010/8a0c1bf4-47a1-11e7-9d6e-f59cff92a3fd.png)

Den SEC Code haben Sie bereits für die Korneas programmiert. Demnächst werden wir einen SEC-Code für KVG benötigen:

Der SKS -Code ist bereits in Ornella programmiert.
Die Produktkennungssequenz muss noch erstellt werden:

Für das Produkt Aortenklappe gilt: B0717002
Für das Produkt Pulmonalklappe gilt: B0719002
Aortenklappe Splitnummer = AKL
Pulmonalklappe Splitnummer = PKL

Aussehen soll das fertige Versandetikett (Maße 12cm x 6cm) wie folgt:

![image](https://cloud.githubusercontent.com/assets/22314271/26726842/de348f7e-47a4-11e7-9519-e144ab6b7409.png)

**Comment by Toelk-A** [comment]
Wir benötigen 5 Zeilen inkl. Eingabefelder für den _Abschnitt Kennnummern_:

1) "Gewebekennnumer" = SKS-Code + Präparate-Code (hierfür bitte folgende Codes neu in Ornella einspeisen, die alten vorher löschen)

[Abkürzungen KVG_Final.xlsx](https://github.com/chrbusch/GTM-V/files/1101568/Abkurzungen.KVG_Final.xlsx)


2) "Chargennummer" + Eingabefeld
3) "Präparatekennummer" (früher "bankinterne Nummer") + Eingabefeld
4) "Seite D oder S" (bei Blutgefäßen, entfällt bei Klappen) + "D" oder "S" (bereits vorhanden)
5) "PKS-Code" = automatisch unter Verwendung der Vorlage #215 erstellen

Wir benötigen 8 Zeilen inkl. Eingabefelder für den _Abschnitt Herstellung_:
„Herstellung“ bitte umbenennen in „Be- und Verarbeitung“
1)	„Be- und Verarbeitung Mitarbeiter“ – Feld vorhanden, bitte nur umbenennen
2)	 „Präparationsbeginn Datum/ Zeit“ – Feld vorhanden, bitte nur umbenennen !ACHTUNG! Präparationsbeginn spätestens 40h nach Todeseintritt
3)	„Beginn Antibiose Datum/Zeit“ – ähnlich Nr.2 programmieren
4)	„Ende Antibiose Datum/Zeit“ – ähnlich Nr.2 programmieren
5)	„Lagerung Datum / Position“ – 2 Eingabefelder
6)	„Endlagerung Datum/Position“ – 2 Eingabefelder
7)	„Datum Haltbarkeit“ – Datum Lagerung + 5 Jahre
8)	„Von Bank akzeptiert“ – bereits vorhanden

Wir benötigen 3/5 Zeilen inkl. Eingabefelder für den _Abschnitt Klassifikation_:
!ACHTUNG! unterschiedliche Angaben bei Klappen und Gefäßen
Klappe:
1)	„Durchmesser“ + Eingabefeld in mm
2)	„Score“ + Eingabefeld 
3)	„Länge Gefäß über Klappe“ + Eingabefeld in mm
Gefäße:
1)	„Durchmesser distal“ + Eingabefeld in mm
2)	„Durchmesser proximal“ + Eingabefeld in mm
3)	„Score“ + Eingabefeld 
4)	„Länge“ + Eingabefeld in mm
5)	„Bifurkationsmessungen“ + Eingabefeld mehrzeilig ca 5 (Text und Zahl)

Keine Veränderungen _Abschnitt Allokation_
Keine Veränderungen _Abschnitt Transpl. dieses Spenders_
Für den _Abschnitt Befunde aller Art_ benötigen wir folgende Modifikationen:
-	Wenn Befunde „Positiv“ oder „keine Freigabe durch GTM-V“ dann entsprechendes Transplantat in „Transpl. dieses Spenders“ rot einfärben

**Comment by chrbusch** [comment]
Ich verstehe nicht, wie sich die Produktkennungssequenz zusammen setzt. Oben stehen 2 Beispiele für Klappen, aber ist ist die REGEL? Sind die Splitnummenr unsere Kürzel?
Wie lautet die Sequenz für Arterien und Venen?

**Comment by chrbusch** [comment]
Haben Sie für dieses Etikettenformat eine Typennummer á la Avery...?
Wie sieht der Druckbogen aus? Anz. Etiketten pro Zeile, wieviele Zeilen gibt es?

**Comment by chrbusch** [comment]
Haben wir diese 4 Dinge in der Datenbank? Wie sind die Werte f.d. anderen Transplantate wie Sehnen usw?
Für das Produkt Aortenklappe gilt: B0717002
Für das Produkt Pulmonalklappe gilt: B0719002
Aortenklappe Splitnummer = AKL
Pulmonalklappe Splitnummer = PKL

**Comment by chrbusch** [comment]
Was ist das für ein Text? Ich denke, auch dafür brauchen wir ein neues Feld in der Datenbank, á la "Benennung für SEC-Etikett"?

![bildschirmfoto 2017-06-27 um 08 29 15](https://user-images.githubusercontent.com/1241899/27573575-cffd7200-5b12-11e7-96a4-fd737461a725.JPG)

**Comment by Toelk-A** [comment]
1) Es gibt keine Averyetiketten hierfür. Der Ausdruck soll auf einem normalen A4-Blatt erfolgen. Dieses wird dann zurechtgeschnitten und in einen Plastikbeutel eingeschweißt (Maße 12cm x 6cm des Ausdruckes sollte eingehalten werden).

2)

Produkt Aortenklappe gilt: B0717002
Splitnummer Aorta: AKL

Produkt Pulmonalklappe gilt: B0719002
Splitnummer Pulmonalklappe: PKL

Produkt Arterien gilt: B0711003
Splitnummer Arterien -> Siehe Excel hier hängt die Splitnummer von entnommener Arterie ab  (exklusive AORTA)

Produkt Venen gilt: B0713001
Splitnummer Venen -> Siehe Excel hier hängt die Splitnummer von entnommener Venen ab 
Produkt Aorta gilt: B0714001 


3) Ja "Bennenung SEC" Feld bitte anlegen

**Comment by Toelk-A** [comment]
4. Finetuning Etikett

![image](https://user-images.githubusercontent.com/22314271/27586733-d59f0a0a-5b41-11e7-8511-192060786dc9.png)

**Comment by Toelk-A** [comment]
erledigt
