### ISSUE TITLE
Digitalisierung Herstellungsprotokoll Teil I OG (Materialdokumentation)

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#216]
Scanmaske GBM-V // entspricht von der Funktion dem Entnahmebericht der GTM-V

In der kommenden Woche möchte die GBM-V ihre Inventur durchführen. Bitte programmieren Sie mit Hilfe der Excel Datei _(Beachten Sie bitte unbedingt den Reiter "Bemerkungen zum Herstellungsprotokoll")_
[Herstellungsprotokoll OG Teil I.xlsx](https://github.com/chrbusch/GTM-V/files/1055107/Herstellungsprotokoll.OG.Teil.I.xlsx)

 sowie des Originaldokumentes
[3.4.3.1 F Herstellprot 1 (Mat) OG-04-10.08.16K.docx](https://github.com/chrbusch/GTM-V/files/1055105/3.4.3.1.F.Herstellprot.1.Mat.OG-04-10.08.16K.docx)

die notwendige Scannmaske.

Vom Prinzip her werden wieder Warenkörbe sowie Zusatzpositionen gescannt. Bei Fragen bitte heute noch anrufen.

**Comment by Toelk-A** [comment]
Wie ist hier der Stand? Wir möchten am 24.06.17 eine Inventur in der GBM-V durchführen.

**Comment by chrbusch** [comment]
Bitte den neuen Reiter "Herstellung" bei den TransplantatDetails ansehen und die beiden blauen Buttons testen

![bildschirmfoto 2017-06-20 um 12 04 50](https://user-images.githubusercontent.com/1241899/27328067-06345a9e-55b1-11e7-979f-c866ac54b5fe.JPG)

**Comment by Toelk-A** [comment]
Im Moment kann ich noch nichts testen. Dies versuche ich morgen. Generell sollen alle Artikel, die im Warenkorb enthalten sind (inkl. LOT und MHD), abgebildet werden. Bitte orientieren Sie sich an der Vorlage, die ich im 1. Kommentar hochgeladen habe (Herstellprot I). Final sollen alle verwendeten Artikel als PDF (Format siehe Anlage "Herstellprot I") ausdruckbar sein.

**Comment by chrbusch** [comment]
Wie besprochen realisiere ich die Druckfunktion, sobald für ein Präparat vollständige Daten zum Drucken vorliegen.

**Comment by Toelk-A** [comment]
Barcodedruck Artikel ( LOT und MHD) : funktioniert
Einscannen Artikel in Warenkorb: Funktioniert
Warenkorb duplizieren: funktioniert
Warenkorb in Herstellungsprotokoll scannen: funktioniert


Folgende Sachen müssen noch durchdacht und programmiert werden:

1) Es gibt Warenkörbe, die für _beide Partnerhornhäute gleichzeitig_ benutzt werden (1WK = Inhalt für 2 Hornhäute - !nur Partnerhornhäute!). Beim Erstellen dieser Warenkörbe müsste eine Spalte eingefügt werden "Warenkorb für Partnerhornhaut" Ja/Nein - ähnlich "Duplikat-Vorbild"

![image](https://user-images.githubusercontent.com/22314271/27475710-71f5d8c8-5806-11e7-889f-d24e781e5bfa.png)

Weiterhin soll nach dem Einscannen dieser Warenkörbe (1WK = Inhalt für 2 Hornhäute - !nur Partnerhornhäute!) die im Warenkorb hinterlegten Materialien **beiden** Parnerhornhäuten zugeordnet werden.

Warenkörbe , die nur für _1 Hornhaut benutzt_ werden (1 WK = 1 Hornhaut) sollen normal abgebildet werden (dies funktioniert bereits.

2) Es werden außerdem _Lösungen zur Herstellung_ der Hornhäute verwendet. Dies bedeutet 1 Flasche Lösung kann für ca 18 Hornhäute benutzt werden. Beim "Ausscannen einer Lösung" darf also nicht die Flasche sondern, nur der im System hinterlegte Teil der Lösung ausgescannt werden.

 Hierfür könnte man z.B. beim Erstellen des Artikels "Lösung" ein Extrafeld einfügen "Für wie viele Hornhäute kann dieser Artikel verwendet werden". Ist dies möglich?

**Comment by chrbusch** [comment]
1.) bitte jetzt testen: Einem Transp. mit PartnerTx einen WaKo zuordnen, dann sollte entspr. Dialog kommen

**Comment by chrbusch** [comment]
Bitte bei diesen Artikel das neue Feld entspr. setzen, zB auf 18

![bildschirmfoto 2017-06-29 um 09 03 12](https://user-images.githubusercontent.com/1241899/27675331-d4b31dd4-5ca9-11e7-8329-16a37100e520.JPG)

**Comment by Toelk-A** [comment]
1) ID 862  Warenkorb wird nicht in Partnerhornhaut abgebildet obwohl "ja" angeglickt nach Nachfrage durch ornella 

2) ID 864 Nach Button "Zusatz pos scannen" KMI gescannt (Zellkulturmedium) -> Partnerhornhaut zuordnen? - Ja - folgender Fehler erscheint: 

![image](https://user-images.githubusercontent.com/22314271/27686875-f6fe5ebe-5cd4-11e7-8b52-1de3b54a7f3f.png)

(Barcode "Herstellung OG" scheint Ornella nicht lesen zu können)

3) ID 864 Nach Button "Zusatz pos scannen" 20ml Pipette gescannt -> weitere Hornhäute zuordnen? - Ja - folgender Fehler erscheint: 

![image](https://user-images.githubusercontent.com/22314271/27686875-f6fe5ebe-5cd4-11e7-8b52-1de3b54a7f3f.png)

(Barcode "Herstellung OG" scheint Ornella nicht lesen zu können)

**Comment by chrbusch** [comment]
Die Prüfung für den beim Scannen erwarteten Wert war zu streng; bitte jetzt erneut versuchen.

**Comment by Toelk-A** [comment]
nächster Fehler:

![image](https://user-images.githubusercontent.com/22314271/27689714-5d6a3dd0-5cdf-11e7-9e6d-737a175636f9.png)

**Comment by Toelk-A** [comment]
gescannt wurde das Herstelletikett 2017-0256-GMV-CS  KMI.1

**Comment by Toelk-A** [comment]
Pipette 25ml soll für CD als auch CS im Herstellungsprotokoll hinterlegt werden.

Ergebnis Scan Partnerhornhaut CS:

![image](https://user-images.githubusercontent.com/22314271/27691125-69d6f0be-5ce3-11e7-8840-8d8a730363c9.png)

Fehlermeldung:

![image](https://user-images.githubusercontent.com/22314271/27691228-b5bf0a3e-5ce3-11e7-928a-5283e9e356ad.png)

Es sieht so aus als ob das "ß" der Fehler ist?

**Comment by chrbusch** [comment]
Es werden nun _alle_ Scanvorgänge im Logbuch protokolliert.
Bitte alles, was gestern schief ging, erneut scannen und mich dann anrufen

**Comment by chrbusch** [comment]
Bitte NOCH NICHT die Spezialfälle mit 1,5 testen, sondern nur Lösungen mit 18 o.ä.!

**Comment by chrbusch** [comment]
Jetzt bitte Lösungen mit 1,5 / 0,5 testen!

**Comment by Toelk-A** [comment]
Das Scannen der Warenkörbe und der Zusatzmaterialien funktioniert. Nun müssen wir eine PDF programmieren in der alle verwendeten Materialien abgebildet sind (siehe 1. Comment 06.06.2017).

**Comment by chrbusch** [comment]
Weiter geht es mir der Druckmaske, siehe Ticket #250
