### ISSUE TITLE
Rechnungsnummern dürfen nicht doppelt vergeben werden

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#217]
Wir haben im System 2 Rechnungen mit der selben Rechnungsnummer. Bitte dies in Zukunft unterbinden.
![image](https://cloud.githubusercontent.com/assets/22314271/26833866/f48851e8-4ad3-11e7-8ed3-ce4e3aeae3d9.png)

und
![image](https://cloud.githubusercontent.com/assets/22314271/26833915/14ed83cc-4ad4-11e7-8881-f50b93c681ad.png)

**Comment by chrbusch** [comment]
Fehler gefunden und behoben, siehe Email hierzu von heute!
