### ISSUE TITLE
KVG / Drei Preise A, B, C

### ISSUE THREAD

**Issue by chrbusch** [chrbusch/GTM-V#219]
Bitte hier beschreiben, was wann wie wem verkauft wird und den ABC-Preis braucht; ich habe es noch nicht verstanden.
Handelt es sich dabei um Gewebe, Präparat oder Transplantat?
Ist es ein Preis für so etwas wie "KVG Komplett-Entnahme"?

**Comment by Nitschke-FP** [comment]
Wir entnehmen derzeit muskuloskelettale Gewebe in 3 Kategorien (Abhängig vom Alter und Geschlecht).
Kat. A erlösen 3025 €
Kat. B erlösen 2025 €
Kat. C erlösen 1525 €.
Für die einzelnen Kategorien gibt es eine Mindestanzahl von Gewebepräparaten, die auch unterschritten werden könnte und dann ein Pauschalbetrag abgezogen wird.
Da dieses Modell der Abrechnung ausläuft und wir ab dem 4. Art. ein neues bekommen, schlage ich vor, dass für die Abrechnung der muskuloskelettalen Gewebe eine Kategorie abfragen, den Standardpreis setzen und die Möglichkeit des editieren des Preises zulassen.

**Comment by Nitschke-FP** [comment]
Bitte beachten, dieses gilt nur für MSG, nicht für KVG

**Comment by chrbusch** [comment]
Bitte hier beschreiben, was wann wie wem verkauft wird und den ABC-Preis braucht; ich habe es noch nicht verstanden.
Wonach soll das Programm suchen? Wer ist Empfänger der Rechnung?

**Comment by Nitschke-FP** [comment]
Der Umfang der Entnahme von muskuloskelettalen Geweben ist alters- und geschlechtsabhängig, daher die 3 Kategorien.
Da die Abrechnung hierfür gerade in Bearbeitung ist und dann pro Präparat bezahlt werden wird, schlage ich vor, dieses so einfach wie möglich zu halten.
Rechnungsempfänger ist die Adress-ID 25 (DIZG). Können Sie eine Tabelle generieren, wo alle MSG Spender aufgelistet sind und dann ein Button zur Abrechnung vorhanden ist. In den folgenden Dialogfenstern kann dann der Rechnungsempfänger gesucht und ein Preis eingegeben werden.
Die vernünftige Programmierung, nach den neuen Kriterien erfolgt dann im 4. Qrt..

**Comment by chrbusch** [comment]
Verstehe ich das richtig: 
a) Der ABC-Preis gilt dann immer für alles pauschal, was dem Spender im Bereich MSG entnommen wurde? 
b) Soll dann auf der Rng die Spd-KennNr erscheinen? 
c) Welcher Text steht oben auf der Rng?

**Comment by chrbusch** [comment]
Soll es eine Rng pro Spender geben, oder eine pro EmpfängerAdresse mit einer POSITION pro Spender?

**Comment by chrbusch** [comment]
Bitte im Hauptmenü den neuen Button
Buchhaltung / "MSG/ABC-Abrechnung"
ausprobieren: Ist das die korrekte Suche f.d. Abrechnung?
