### ISSUE TITLE
Prozessschritt Mobiles Entnahmeteam

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#22]
-   Nur notwendig wenn Entnahmeraum (siehe Entnahmebericht) außerhalb Rostocks ist feintuning

**Comment by Toelk-A** [comment]
-	Nur notwendig wenn in „Checkliste zur Freigabe der Gewebeentnahme“ angekreuzt
-	Adressat abhängig von Region Entnahmeort (Entnahmebericht)
-	HKTS automatisch einfügen
-	Standort: Rostock
-	Verantwortlicher Entnehmer den entnehmenden Eintragen, ggf. mehrere aus dem Entnahmebericht

**Comment by chrbusch** [comment]
Bitte genauere Angaben.
"Adressat abhängig von Region Entnahmeort (Entnahmebericht)"
Wie ist die Regel hierfür?

"HKTS automatisch einfügen"
Was ist HKTS?

"Standort: Rostock"
Was soll das bedeuten?

Bitte versuchen Sie, klare Anweisungen zu geben, was wir TUN SOLLEN.

**Comment by Toelk-A** [comment]
## "Adressat abhängig von Region Entnahmeort (Entnahmebericht)"
-> Wenn Adresse Entnahmeort in MV, dann folgenden Adressat einfügen:

Landesamt für Gesundheit und Soziales Mecklenburg-Vorpommern Arzneimittelüberwachungs- und –prüfstelle
Wismarsche Straße 298 19055 Schwerin
Telefon: 0385-58859-380 Telefax: 0385-58859-399 E-Mail: poststelle.amuest@lagus.mv-regierung.de

->Wenn Adresse Entnahmeort in Brandenburg (z.B Schwedt, Angermünde) dann folgenden Adressat einfügen:

 Landesamt für Umwelt, Gesundheit und Verbraucherschutz Abt. Gesundheit Referat Apotheken, Arzneimittel, Medizinprodukte
Wünsdorfer Platz 3 15806 Zossen
Telefon: 0331 8683-802 Telefax: 03318683-809


## "HKTS automatisch einfügen"
Was ist HKTS?

HKTS = Herz-/Kreislaufstillstand entspricht Todesdatum und Todeszeit in Spendermeldung

## "Standort: Rostock"
Was soll das bedeuten?

Standort momentan immer Rostock - Bitte Dropdown und Eingabefeld anlegen

**Comment by Toelk-A** [comment]
Dokument funktioniert im Moment garnicht

**Comment by Toelk-A** [comment]
Zeile "Verantwortlicher Entnehmer": Bitte Koordinatoren zum Dropdown hinzufügen (Ärzte bleiben in Liste)

**Comment by chrbusch** [comment]
"Zeile "Verantwortlicher Entnehmer": Bitte Koordinatoren zum Dropdown hinzufügen"

erl.

**Comment by Toelk-A** [comment]
Zum mobilen Entnahmeteam müssen bitte noch folgende Dinge bearbeitet werden:

1) Spenderart: Hier wäre es gut anstatt der Abkürzungen "H", "O", "L" di Wörter vollständig abzubilden
H= Herz-Kreislauf-toter-Spender
O= Organspender
L= Lebendspender

2) Standort: Standort momentan immer Rostock - Bitte Dropdown und Eingabefeld anlegen

3) Generell muss, wenn ausgefüllt, das "Mobile Entnahmeteam" auch als PDF erstellt werden können und ausgedruckt werden können. -> Vielleicht könnte man es einfach in die Prozessschritte mit einfügen?

**Comment by chrbusch** [comment]
1. erl.
2: In das Feld kann man frei tippen; die zum ersten Buchstaben passenden Orte erscheinen als Dropdown
3. Das ist doch schon so?? Hat bei uns sofort geklappt.
