### ISSUE TITLE
RBD-Tausch/Wünsche - Fehlermeldung

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#220]
Als Supervisor, wollte ich dem folgenden "Tausch" stattgeben:

![image](https://user-images.githubusercontent.com/22314271/27276755-721c54ee-54dc-11e7-84c4-9a687699db59.png)

Dies funktioniert nicht mit folgender Fehlermeldung:

![image](https://user-images.githubusercontent.com/22314271/27276785-8a6b749e-54dc-11e7-8bd3-257be0dffd0b.png)

Bitte beheben da der Juliplan heute fertiggestellt werden soll.
Danke

**Comment by chrbusch** [comment]
try again...
