### ISSUE TITLE
Dienstplan August bis 03.07.2017 erstellen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#221]
Der Dienstplan für den August muss bis 03.07.2017 erstellt werden. Können wir dies gemeinsam telefonisch durchführen?

**Comment by chrbusch** [comment]
Ja; gerne anrufen, ich habe auch jetzt sofort Zeit

**Comment by Toelk-A** [comment]
erneut taucht Frau Karnatz im RBD Plan auf:

![image](https://user-images.githubusercontent.com/22314271/27370367-8d486358-565c-11e7-983f-4d3f8e5d5c3b.png)

Fehler war gestern bereits behoben, warum taucht er heute wieder auf?

Meine Vorgehensweise:
Personalplanung - Miatrbeiter - RBD-Monatsplan

**Comment by Toelk-A** [comment]
Kann ich den Namen eines Koordinatoren in den Dienstplan eintragen, wenn Ornella keinen Koordinator für RBD findet? Wenn ja wo?

**Comment by chrbusch** [comment]
Menü/Supervisor/SV-Kalender.
Dort den Mitarb. suchen, RBD auf 1=Ja setzen

![bildschirmfoto 2017-06-22 um 06 43 00](https://user-images.githubusercontent.com/1241899/27417625-0eb9b3f6-5716-11e7-8d67-8ba565df3af5.JPG)
