### ISSUE TITLE
Spender ID 2221-MSG Standardset unvollständig

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#222]
MSG Standardset ist für das Alter 60 Jahre unvollständig. Die Sehnen fehlen. Bitte umgehend wiederherstellen.
Danke

**Comment by chrbusch** [comment]
Das "alte" MSG Standardset enthält nur 5 Knochen. Und das "junge" auch!
Sie können dies selbst wie folgt konfigurieren:
Hauptmenü/Supervisor, Button "Präparat- u. Transpl.-Arten"
Dort im Feld "StandardSet_JA" (jung/alt) ankreuzen, welche zu welchem Standardset gehören.
