### ISSUE TITLE
Spd Transplantat Details für KVG

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#223]
Ähnlich der programmierten "Spd Transplantat Details" für Kornea benötigen wir ein solches "Übersichtsfenster" für die KVG Transplantate. Dieses würde ich am Liebsten gern mit Ihnen zusammen telefonisch erstellen. Es spart viel Zeit und Schreiberei. Als Grundlage können wir das "Kornea Übersichtsfenster" nutzen. Es müssten prinzipiell ein paar Zeilen umbenannt und hinzugefügt werden. Der Aufbau bleibt der selbe. Bitte nennen Sie mir ein Datum in der Woche vom 26.06-30.06.2017 (außer 29.06.17) an dem wir dies zusammen durchführen können.

**Comment by Toelk-A** [comment]
Montag 26.06.2017 10-12:00Uhr

**Comment by Toelk-A** [comment]
Wir benötigen 5 Zeilen inkl. Eingabefelder für den _Abschnitt Kennnummern_:

1) "Gewebekennnumer" = SKS-Code + Präparate-Code (bitte die alten KVG Präparate udn Transplantate Codes löschen und die neuen hinzufügen - siehe Excel)
[Abkürzungen KVG_Final.xlsx](https://github.com/chrbusch/GTM-V/files/1101599/Abkurzungen.KVG_Final.xlsx)


2) "Chargennummer" + Eingabefeld
3) "Präparatekennummer" (früher "bankinterne Nummer") + Eingabefeld
4) "Seite D oder S" (bei Blutgefäßen, entfällt bei Klappen) + "D" oder "S" (bereits vorhanden)
5) "PKS-Code" = automatisch unter Verwendung der Vorlage #215 erstellen

Wir benötigen 8 Zeilen inkl. Eingabefelder für den _Abschnitt Herstellung_:
„Herstellung“ bitte umbenennen in „Be- und Verarbeitung“
1)	„Be- und Verarbeitung Mitarbeiter“ – Feld vorhanden, bitte nur umbenennen
2)	 „Präparationsbeginn Datum/ Zeit“ – Feld vorhanden, bitte nur umbenennen !ACHTUNG! Präparationsbeginn spätestens 40h nach Todeseintritt
3)	„Beginn Antibiose Datum/Zeit“ – ähnlich Nr.2 programmieren
4)	„Ende Antibiose Datum/Zeit“ – ähnlich Nr.2 programmieren
5)	„Lagerung Datum / Position“ – 2 Eingabefelder
6)	„Endlagerung Datum/Position“ – 2 Eingabefelder
7)	„Datum Haltbarkeit“ – Datum Lagerung + 5 Jahre
8)	„Von Bank akzeptiert“ – bereits vorhanden

Wir benötigen 3/5 Zeilen inkl. Eingabefelder für den _Abschnitt Klassifikation_:
!ACHTUNG! unterschiedliche Angaben bei Klappen und Gefäßen
Klappe:
1)	„Durchmesser“ + Eingabefeld in mm
2)	„Score“ + Eingabefeld 
3)	„Länge Gefäß über Klappe“ + Eingabefeld in mm
Gefäße:
1)	„Durchmesser distal“ + Eingabefeld in mm
2)	„Durchmesser proximal“ + Eingabefeld in mm
3)	„Score“ + Eingabefeld 
4)	„Länge“ + Eingabefeld in mm
5)	„Bifurkationsmessungen“ + Eingabefeld mehrzeilig ca 5 (Text und Zahl)

Keine Veränderungen _Abschnitt Allokation_
Keine Veränderungen _Abschnitt Transpl. dieses Spenders_
Für den _Abschnitt Befunde aller Art_ benötigen wir folgende Modifikationen:
-	Wenn Befunde „Positiv“ oder „keine Freigabe durch GTM-V“ dann entsprechendes Transplantat in „Transpl. dieses Spenders“ rot einfärben

**Comment by chrbusch** [comment]
Es wurde ein neues LAYOUT erstellt namens "[SpdTranspl_D-KVG] KVG-Transplantat Details"

**Comment by chrbusch** [comment]
Bitte das Wording anhand dieses Beispiels diskutieren:
1) Gewebe = "OG"
2) Präparat = "Bulbus"
3) Transplantat = "humane Augen-HH"

Nur was auf Stufe 1 "lebt", darf "Gewebe" heissen
Nur was auf Stufe 2 "lebt", darf "Präparat" heissen
Nur was auf Stufe 3 "lebt", darf "Transplantat" heissen

**Comment by Toelk-A** [comment]
Layout unvollständig, bitte vollständig programmieren

Wording: Stufe 2 muss umbenannt werden in "Gewebepräparat" siehe Ticket #227

**Comment by chrbusch** [comment]
Am Bereich a) arbeite ich noch
Die neuen Felder im "b"-Bereich bitte testen

**Comment by chrbusch** [comment]
Die Felder der Bereiche c) und d) sind nun auch vorhanden, aber jeweils sichtbar nur für de entspr. Transplantat
![bildschirmfoto 2017-06-26 um 15 00 03](https://user-images.githubusercontent.com/1241899/27540350-2a092e9e-5a80-11e7-9372-5437fdf2b1a5.JPG)
arten

**Comment by chrbusch** [comment]
"Wenn Befunde „Positiv“ oder „keine Freigabe durch GTM-V“ dann entsprechendes Transplantat in „Transpl. dieses Spenders“ rot einfärben"

Bitte für einen Testspender Daten so erfassen, dass Rotfärbung kommen SOLLTE und mir dann dessen ID nennen

**Comment by Toelk-A** [comment]
siehe Ticket #229  -> erst danach kann ich Ihren Test durchführen

**Comment by chrbusch** [comment]
Bereich a) ist halbfertig, den Rest müssen wir besprechen

**Comment by Toelk-A** [comment]
Bitte folgende Veränderungen einarbeiten:

1) Mindesthaltbarkeitsdatum soll 5 Jahre sein (im Moment sind 6 Jahre programmiert)
Spender ID 1361 
![image](https://user-images.githubusercontent.com/22314271/27585578-2762ad1a-5b3d-11e7-8b79-bce596e52307.png)

2) Seitenauswahl "D" oder "S" trifft bei folgenden Transplantaten nicht zu: 
- Arteria pulmonalis mit Bifurkation
- Aortenbogen
- Aorta thoracica
- Aorta abdominalis
- Aorta ascendens
- Aorta descendens
- Aorta abdominalis mit Bifurkation

3) Abschnitt Klassifikation bitte folgende 2 Zeilen einfügen:
![image](https://user-images.githubusercontent.com/22314271/27585806-f200bf12-5b3d-11e7-8461-28335ac3003b.png)

Diese sind bei den Hornhäuten (inklusive Status) bereits programmiert. Dies bitte mit Statusauswahl übernehmen.

4) Sonderfall Transplantat "Arteria pulmonalis mit Bifurkation":
Hier sollen zusätzliche Eingabefelder programmiert werden. Zur Vorstellung: Die "Arteria pulmonalis mit Bifurkation" ähnelt einem "Y". 
- Die Gefäßlänge muss also in "Gefäßlänge Arteria pulmonalis dextra" - rechter Gefäßarm - und "Gefäßlänge Arteria pulmonalis sinistra" - linker Gefäßarm - unterteilt werden.
- Durchmesser proximal - _bereits programmiert_
- Durchmesser distal: hier benötigen wir wieder 2 Eingabefelder: "Durchmesser distal Arteria pulmonalis dextra" und "Durchmesser distal Arteria pulmonalis sinistra"
- "Länge bis zur Bifurkation" + Eingabefeld

-> Das Eingabefeld "Bifurkationsmessungen" kann also gelöscht werden. Alle unter Punkt 4 genannten Felder genannten zusätzlichen Felder können bei Herzklappen und Gefäßen ausgeblendet werden Ausnahme: "Durchmesser proximal" und Angaben in Punkt 3

**Comment by chrbusch** [comment]
So in Ordnung?


![bildschirmfoto 2017-06-27 um 15 01 04](https://user-images.githubusercontent.com/1241899/27588784-99a88640-5b49-11e7-9872-88ff9a7e62b5.JPG)

**Comment by Toelk-A** [comment]
Ja in Ordnung, die Schriftfarbe ist dann auch blau?

**Comment by Toelk-A** [comment]
Bitte noch 1 - 3 bearbeiten. Danke

**Comment by chrbusch** [comment]
Erl., bitte prüfen.

**Comment by Toelk-A** [comment]
1) **erledigt**
2) hier fehlen jetzt alle "normalen Gefäßangaben. Es sollten nur die Seite "D" oder "S" entfernt werden.
Artikel ID 857
![image](https://user-images.githubusercontent.com/22314271/27626882-066054a2-5bea-11e7-8261-03f8e23c98a7.png)

3) fehlt komplett

4) **erledigt**

**Comment by chrbusch** [comment]
M.E. jetzt erl.

**Comment by Toelk-A** [comment]
Funktioniert :+1: 

Können Sie bitte noch die Möglichkeit programmieren innerhalb des Fensters "Transplantate dieses Spenders" mit einem Doppelklick das Öffnen des jeweiligen anderen Transplantates zu ermöglichen? Dies funktioniert bereits bei den Hornhäuten (Wechsel zwischen CD und CS durch klicken auf das jeweilige Transplantat)

![image](https://user-images.githubusercontent.com/22314271/27628911-c866ae4c-5bf0-11e7-88e0-dabb77da8f18.png)

**Comment by chrbusch** [comment]
Durch Anklicken der ERSTEN Spalte gelangen Sie nun zu dem jew. Transplantat; und nun wird dabei auch ggf. automatisch die Maske gewechselt (OG <> KVG), gut zu testen mit Spender 1361

**Comment by Toelk-A** [comment]
funktioniert
