### ISSUE TITLE
Button Arbeitszeit erfassen funktioniert nicht

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#224]
siehe Fehlermeldung, bitte fertig programmieren, da alle Koordinatoren bereits auf diesen Button hingewiesen wurden.

![image](https://user-images.githubusercontent.com/22314271/27392769-ccf160d6-56a7-11e7-8e32-0001559c7b6e.png)

**Comment by chrbusch** [comment]
Wird noch heute erledigt, ich bin aber in frühestens 2 Stunden wieder im Büro

**Comment by chrbusch** [comment]
Sorry, Button funktioniert jetzt!

**Comment by Toelk-A** [comment]
trägt man keine Endzeit ein, wird automatisch bis 24 Uhr dokumentiert. Danach kann man direkt die Uhrzeit  im Erfassungsfeld ändern/löschen. Dementsprechend sind nach wie vor "Fehldokumentationen möglich".

![image](https://user-images.githubusercontent.com/22314271/27419745-ced5943c-5722-11e7-9f32-f42ed538866f.png)

![image](https://user-images.githubusercontent.com/22314271/27419775-e09a9ce4-5722-11e7-9f7d-360a88ecee0b.png)

**Comment by chrbusch** [comment]
Guter Punkt!
Das System erzwingt jetzt Eingabe von UhrzeitBeginn, UhrzeitEnde und Pause
