### ISSUE TITLE
Artikel Scannen aus ein um - Button Problem "keine plausible Artikelcharge gescannt"

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#225]
1) Artikel ID 17 (Ecotainer Nacel 1000ml) soll ausgescannt/umgelagert werden unter Verwendung des Buttons "Artikel Scannen aus ein um"
obwohl Chargen in Ornella registriert

![image](https://user-images.githubusercontent.com/22314271/27469530-5741d286-57f0-11e7-9408-79570a141a21.png)

kommt folgende Fehlermeldung nach dem Abscannen unseres selbst erstellten Barcodes:

![image](https://user-images.githubusercontent.com/22314271/27469548-72910ebc-57f0-11e7-8c1f-8f589e54eee1.png)

**Comment by chrbusch** [comment]
Bei mir klappt das mit dieser Charge! Bitte erneut testen.

**Comment by Toelk-A** [comment]
Bitte rufen Sie mich an damit wir alles über den Teamviewer testen können.
