### ISSUE TITLE
Artikel Scannen aus ein um - 1) Zwischenlager wird nicht aufgeführt  2) Funktion Abbrechen nicht gegeben

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#226]
1) Klickt man den Button "Artikel Scannen aus ein um" und scannt Handschuhe ( ID ) kommt folgende Abfrage durch Ornella:

![image](https://user-images.githubusercontent.com/22314271/27469613-d6765de2-57f0-11e7-9d4b-44b2ac8aefed.png)
(Das ist in Ordnung) 

Klickt man auf "umlagern" so erscheinen folgende Lager:

![image](https://user-images.githubusercontent.com/22314271/27469671-0ebce626-57f1-11e7-81e8-6af4d44527fc.png)

-> das Zwischenlager fehlt!!! Hier bitte alle mögliche Lager abbilden (früher war dies möglich, ich weiß nicht warum es jetzt nicht mehr funktioniert)

2) Klickt man nun auf "Abbrechen" so kommt folgende Anfrage:

![image](https://user-images.githubusercontent.com/22314271/27469722-3b813be4-57f1-11e7-9bd0-870aee0397f6.png)

-> Artikel werden also ausgebucht.... wir müssen eine neue Inventur in der GTM-V machen, da die Zahlen nicht mehr stimmen.... Die Funktion Abbrechen sollte immer gegeben sein..

**Comment by chrbusch** [comment]
Hat denn die Charge BESTAND im Zwischenlager? Es sollen als Entnahmelager nur diejenigen mit Bestand erscheinen.
"Abbrechen" klappt jetzt

**Comment by Toelk-A** [comment]
Ja hat sie
