### ISSUE TITLE
Button "Barcode scannen" - Funktion programmieren

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#228]
Für die Mitarbeiterinnen der Bank ist es leichter die Hornhäute/KVG-Transplantate abzuscannen, die gerade in Arbeit sind. Hierfür sollen die Etiketten "Herstellung" abgescannt werden. Ornella soll dann den Barcode mit der jeweiligen Hornhaut/KVG-Transplantat verknüpfen und die Detailansicht öffnen.

**Comment by Toelk-A** [comment]
![image](https://user-images.githubusercontent.com/22314271/27539111-7f238938-5a7b-11e7-8fcc-1e3eca47a9ad.png)

**Comment by chrbusch** [comment]
Siehe neuer Button "Herstell-Etikett scanne" rechts im Hauptmenü

**Comment by Toelk-A** [comment]
Allgemeines General-Master-Super-Scanscript ist eine super Idee, dann ist es für alle übersichtlicher.
