### ISSUE TITLE
Neue Werteliste für KVG - "Befunde aller Art" 

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#229]
Zum Ihrer Anfrage #223 :

cBu:  "Wenn Befunde „Positiv“ oder „keine Freigabe durch GTM-V“ dann entsprechendes Transplantat in „Transpl. dieses Spenders“ rot einfärben"

Bitte für einen Testspender Daten so erfassen, dass Rotfärbung kommen SOLLTE und mir dann dessen ID nennen

-> Wir benötigen eine neue - nur für KVG sichtbare - Werteliste für den Abschnitt "Befunde aller Art":

- Transportlösung (1-TL)
- Bioptat vor Antibiose, proximal (2-BVAP)
- Bioptat vor Antibiose, distal (2-BVAD)
- Bioptat nach Antibiose, proximal (3-BNAP)
- Bioptat nach Antibiose, distal (3-BNAD)
- Kryolösung (4-KL)

**Comment by chrbusch** [comment]
Für welches Feld ist denn diese Liste - Material? Oder Bezeichnung des Befundes?

**Comment by chrbusch** [comment]
statt wl "km1, km2..."

**Comment by chrbusch** [comment]
Diese Liste erscheint jetzt - aber welche Parameter gehören dazu?

**Comment by chrbusch** [comment]
Man kann nun bei den Parametern alle Materialarten ankreuzen; aber mir ist noch gar nicht klar, welche Params es bei KVG überhaupt gibt!

![bildschirmfoto 2017-06-27 um 14 07 51](https://user-images.githubusercontent.com/1241899/27586819-2144e7f4-5b42-11e7-941e-9ed648cddedf.JPG)

**Comment by Toelk-A** [comment]
Aufbau "Befunde aller Art" ist der selbe wie bei den Hornhäuten:

![image](https://user-images.githubusercontent.com/22314271/27586945-bda03eb4-5b42-11e7-84cb-70a9b68b57f2.png)

**Comment by Toelk-A** [comment]
![image](https://user-images.githubusercontent.com/22314271/27587015-0588f022-5b43-11e7-9d63-c554a411fd6d.png)

identisch für KVG bitte

**Comment by chrbusch** [comment]
Bitte testen, ob ich das richtig verstanden habe.

**Comment by Toelk-A** [comment]
Ja, das haben Sie.

Ist es möglich das Material "vollständig" abzubilden? Falls es Platzprobleme gibt, möchte ich Sie bitten die Abkürzungen an 1. Stelle  zu setzen:

3-BNAD, Bioptat nach Antibiose distal

**Comment by Toelk-A** [comment]
![image](https://user-images.githubusercontent.com/22314271/27588038-07c5ad18-5b47-11e7-9a4c-ffc854e91a29.png)

**Comment by chrbusch** [comment]
Das Kz. steht bei ab jetzt erstellten Befunden vorne
