### ISSUE TITLE
Prozessschritt Qualität Raum Gewebeentnahme?!

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#23]
Layout: Qual.Raum Gew.Entn. neu: nur bei den Prozessschritten anzeigen, wo erstmalig eine Entnahme stattfindet.

**Comment by chrbusch** [comment]
Ich verstehe nicht, was nur angezeigt werden soll, und was "erstmalig eine Entnahme" genau meint.
Sind es die Buttons auf der Spendermaske?
Am besten mit einem Bild erläutern, was genau gemeint ist

**Comment by Toelk-A** [comment]
Layout: Qual.Raum Gew.Entn. muss nur ausgefüllt werden, wenn der Entnahmeraum noch nicht in unserem Adressbuch hinterlegt ist, d.h. wenn wir dort zum ersten Mal eine Entnahme durchführen, dann müssen wir vorher den Raum für eine Entnahme "qualifizieren". Für diese Qualifikation benötigen wir das Dokument: Qual.Raum Gew.Entn.

**Comment by chrbusch** [comment]
Dann sollten wir den EntnahmeRAUM als Subadresse der meld. Einrichtg. angelegen und bei der ADRESSE ein Ankreuzfeld "Geeignet für..." haben; einverstanden?

**Comment by chrbusch** [comment]
So habe ich es jetzt gemacht

![bildschirmfoto 2016-11-10 um 10 47 30](https://cloud.githubusercontent.com/assets/1241899/20171909/1d34d480-a733-11e6-8779-f7e85f833f6f.JPG)

**Comment by Toelk-A** [comment]
okay
