### ISSUE TITLE
Button Allokation - Transplantatliste

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#231]
Nachdem ich beide Buttons gedrückt habe öffnet sich das KVG Transplantat Detail Fenster

![image](https://user-images.githubusercontent.com/22314271/27633176-757bc5ce-5bfe-11e7-88b7-11e208c2ff0c.png)

Ich muss mich immer neu bei Ornella anmelden, dann funktioniert die Transplantatliste 2x, danach erscheint das KVG-Fenster

**Comment by chrbusch** [comment]
Bitte genauer beschreiben, welchen Button Sie wo klicken!

**Comment by Toelk-A** [comment]
![image](https://user-images.githubusercontent.com/22314271/27640942-ceb45a4a-5c1a-11e7-9473-7eeb44adbae6.png)

**Comment by Toelk-A** [comment]
![image](https://user-images.githubusercontent.com/22314271/27640951-d6ed621a-5c1a-11e7-91c0-70964c243bd4.png)

**Comment by Toelk-A** [comment]
![image](https://user-images.githubusercontent.com/22314271/27640968-dfc0f3b6-5c1a-11e7-916a-b11f70c308cc.png)

**Comment by Toelk-A** [comment]
1 Allokation
2 Transplantatliste

**Comment by chrbusch** [comment]
Wieder OK, oder?!
