### ISSUE TITLE
KVG Deatilmaske - Befunde aller Art - falsch "positive" Befundung Ersteingabe - Farbcode ändert sich nicht bei Wechsel zu "negativ"

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#232]
KVG Deatilmaske - Befunde aller Art - ID783

Es wurde fälschlicherweise ein Befund als "positiv" angeklickt, der eigentlich "negativ" ist. Nach Drücken des Buttons "negativ" ändert sich die Beschriftung in "neg", der Befund (1-TL) ist allerdings nach wie vor gelb eingefärbt. Diese Einfärbung bitte "deprogrammieren"

![image](https://user-images.githubusercontent.com/22314271/27679833-29c16bd6-5cba-11e7-850e-e940c471bd1e.png)

**Comment by chrbusch** [comment]
Gelb sind die vorne als "wichtig" angekreuzten Befunde, NICHT die positiven! Diese werden dann nach oben sortiert.
Die Färbung kann ich aber leicht  ändern - bitte "Wunschfärbung" angeben: Sollen nur positive gefärbt werden?
