### ISSUE TITLE
KVG-Detailmaske- Neuer Befund- Fehlende Parameter 

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#233]
KVG-Deatilmaske- Neuer Befund- Fehlende Parameter 

Beim anklicken der Zeilen Bioptat **vor Antibiose** , distal und proximal sind keine Parameter im System hinterlegt.

Alle anderen funktionieren.

![image](https://user-images.githubusercontent.com/22314271/27680027-c62ffc62-5cba-11e7-8f62-c9643156930c.png)

![image](https://user-images.githubusercontent.com/22314271/27680096-fb864dda-5cba-11e7-8e89-6c4977c85c06.png)

![image](https://user-images.githubusercontent.com/22314271/27679499-38347394-5cb9-11e7-990d-3c37d0b2e94b.png)

**Comment by chrbusch** [comment]
Dies lag an den fehlenden Leerzeichen bei einigen Materialien, sollte jetzt wieder klappen!
