### ISSUE TITLE
KVG SEC-Etikett- Bitte Ch.-B.: Abkürzung korrigieren

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#234]
Im SEC Etikett wird die Ch.-B.: durch eine falsche Verknüpfung erstellt.

![image](https://user-images.githubusercontent.com/22314271/27683149-51c2e712-5cc5-11e7-965d-ab88a1ce5074.png)

 Es darf nicht die Abkürzung aus der Chargennummer heiraufgeführt werden (H)
![image](https://user-images.githubusercontent.com/22314271/27683183-6e7fa3b8-5cc5-11e7-83ab-ab0844385062.png)

sondern es muss die Abkürzung der "Präparatekennnummer" aufgeführt werden:
![image](https://user-images.githubusercontent.com/22314271/27683241-90868968-5cc5-11e7-9aeb-b979519d5744.png)

Diese Abkürzung ist auch inder "product identification sequence" hinterlegt.

![image](https://user-images.githubusercontent.com/22314271/27683033-04bc86da-5cc5-11e7-9392-6828e7e28b3f.png)

**Comment by chrbusch** [comment]
Erl.
