### ISSUE TITLE
"Abbrechen" - Button -Inventureingabe - keine Funktion programmiert

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#235]
Artikel ID 9

Button "Inventureingabe" - "Abbrechen" -> funktioniert nicht, da folgendes Bild erscheint

![image](https://user-images.githubusercontent.com/22314271/27724747-a638ad8c-5d73-11e7-8377-3b0e7f0dea2c.png)

**Comment by chrbusch** [comment]
fixed, Abbrechen klappt nun

**Comment by Toelk-A** [comment]
Abbrechen klappt nicht, nach Zuordnung eines Artikels zu einer weiteren Hornhaut:

![image](https://user-images.githubusercontent.com/22314271/27726709-c53d838a-5d7b-11e7-9b12-a45be8beb489.png)

**Comment by Toelk-A** [comment]
nach Klick auf !Abbrechen kommte folgendes Fenster als endlos Schleife:

![image](https://user-images.githubusercontent.com/22314271/27726942-b67562b8-5d7c-11e7-858d-cbf705339649.png)

**Comment by Toelk-A** [comment]
klickt man auf "Nein" kommt wieder "Barcode des nächsten Transplantates Scannen"

**Comment by chrbusch** [comment]
Irgendetwas geht hier durcheinander; der InventurEingabe-Button hat doch nichts mit einem Transplantat zu tun?

**Comment by chrbusch** [comment]
Ah, hab´s trotzdem gefunden; Abbrechen sollte jetzt auch dort klappen
