### ISSUE TITLE
Scannprobleme Spender ID 1361 - kein Script beim Scannen angezeigt worden....

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#236]
1) Artikel ID3 Testpipette:
    Bestand wird ausgebucht - **Funktioniert**
    Pipette einer weiteren Hornhaut zuordnen 1A: Scannen funktioniert (ohne Fehlermeldung)
                                                                         1B: Pipette wird in eingescannter Hornhaut als Zusatzposition 
                                                                               nicht abgebildet
                                                                          1C: Es muss die Möglichkeit des Einscannens von ca 10 
                                                                                Hornhäuten für den Artikel bestehen
                                                                           1D: Bitte alle Buttons (Ja, Nein,Abbrechen) mit Funktionen 
                                                                                 programmieren

2) Artikel ID 12 Test Zellkulturmedium:
![image](https://user-images.githubusercontent.com/22314271/27727251-ef80ba48-5d7d-11e7-8459-2c9b26b91593.png)
2A) 1 Flasche ist für 1,5 Hornhäute anwendbar. Hier dürften also maximal 2 Hornhäute pro Flasche eingescannt werden. 
2B) Medium nicht in zusätzlich eingescannter Hornhaut im Herstellungsprotokoll abgebildet

![image](https://user-images.githubusercontent.com/22314271/27727497-010a0804-5d7f-11e7-9d61-cccc37adfa81.png)

Bitte das Ganze per Teamviewer durchgehen

**Comment by chrbusch** [comment]
So weit ich weiss sind alle SCAN-Probleme erledigt; aber das mit der Mehrfachverwendung muss noch programmiert werden
