### ISSUE TITLE
Herstellungsliste bitte nur Transplantate der GBM-V abbilden

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#237]
Bitte nur Transplantate der GBM-V in der Herstellungsliste abbilden.

= nur Transplantate die "GMV" in Ihrer Bank Nr. des Transplantates beinhalten

![image](https://user-images.githubusercontent.com/22314271/27734424-17a9cf74-5d9b-11e7-942e-0732c34a2aee.png)

**Comment by chrbusch** [comment]
Done
