### ISSUE TITLE
SEC CODE - stromaler Patch erstellen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#238]
Aus einem Bulbus (Gewebepräparat) wird eine Hornhaut präpariert. Diese wird anhand Ihrer Zellzahl in den OG Transplantat Details klassifiziert:

>2000 Zellen  in Augenhornhaut, organkultiviert (Splitcode CSO/CDO)

![image](https://user-images.githubusercontent.com/22314271/27735700-412bd756-5da1-11e7-8a74-3dcc34e4baa1.png)

oder <2000 Zellen stromaler Patch (Splitcode CSP/CDP)

![image](https://user-images.githubusercontent.com/22314271/27735713-527c9338-5da1-11e7-805c-ede0b4735fc8.png)

für einen stromalenPatch darf nicht der Splitcode CSO/CDO genutzt werden sondern CS**P**/CD**P**

![image](https://user-images.githubusercontent.com/22314271/27735610-cea07c32-5da0-11e7-9e28-b314cecd2b77.png)

Bitte im SEC CODE der Hornhauttransplantate ändern.

**Comment by chrbusch** [comment]
Erledigt; wg. der Wichtigkeit bitte besonders kritisch prüfen.
VOR dieser Änderung gedruckte Etiketten mit SEC-Code können nun evt. nicht mehr eingelesen (gescannt) werden! Tritt das auf gibt es aber ein simples work around
