### ISSUE TITLE
Prozessschritt Entnahmebericht (aller Gewebe)

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#24]
-   Bitte automatischer Eintrag „HKTS“ Todesdatum und Todeszeit
-   Entnahmeorte hinterlegen (Dropdown bzw. Nachtrag möglich) erledigt, aber die komplette Adresse fehlt
-   Gewebeprozessierende Einrichtung hinterlegen funktioniert noch nicht
-   Individuelle Entnahmeberichte für OG, MSG, KVG, Amnion, Haut
-   Besonderheiten: Arbeitsbereichreinigung – Mehrfachauswahl (vor und nach Entnahmetätigkeit
-   Unterschriftenfeld: Koordinator/Entnehmer nicht ankreuzbar, wenn Koordinator angekreuzt wird sollte der Koordinator der Spenderakte (siehe Kennnummer) eingetragen werden. Wenn Entnaehmer angekreuzt wird Drop-Down mit einer Entnehmerliste. Entnehmerliste rekrutiert sich aus den natürlichen personen und der Funktion Entnehmer
-   Letztes Unterschriftenfeld Dropdown des ärztlichen Personals 
-   Eignung für Gewebeaufbereitung: Text Bemerkung darf nicht in Begründung für Nichtfreigabe kopiert werden
-   Nachtrag – Anpassung Entnahmebericht: Kopie aus den daten des Angehörigengespräches!

![image](https://cloud.githubusercontent.com/assets/22314271/19688599/b5fe73a8-9aca-11e6-903a-db171161eafa.png)
-   Entnahmebericht: Beschreibung von Besonderheiten/Abweichungen/Gefährdungspotential fehlt

**Comment by Toelk-A** [comment]
HKTS = Herz-/Kreislaufstillstand entspricht Todesdatum und Todeszeit in Spendermeldung

**Comment by chrbusch** [comment]
"... Funktion Entnehmer"

Diese Funktion gibt es bislang gar nicht! Ich habe sie jetzt eingeführt und bitte Sie, die entsprechenden Personen hier zu markieren. Danach kann ich dann eine Auswahl programmieren

**Comment by chrbusch** [comment]
"Individuelle Entnahmeberichte ": dies möchten wir angehen, wenn der Entnahmebericht für OG komplett ist.

**Comment by Toelk-A** [comment]
Zu "... Funktion Entnehmer"

Diese Funktion gibt es bislang gar nicht! Ich habe sie jetzt eingeführt und bitte Sie, die entsprechenden Personen hier zu markieren. Danach kann ich dann eine Auswahl programmieren


Habe ich Zugriff auf die Personen? Wenn ja, wo kann ich diese in Ornella finden? 

Ansonsten müsste Dr. Nitschke assigned werden, da er Administratorrechte hat.

**Comment by chrbusch** [comment]
Administratorrechte haben nur wir; Dr. N. ist "Supervisor"
Aber diese Rechte benötigen Sie nicht!
Einfach die Personen suchen und bei den Funktionen die neuen Option "Entnehmer" ankreuzen.

**Comment by Toelk-A** [comment]
Zu "... Funktion Entnehmer"

Wo genau kann ich nach Personen in Ornella suchen?

**Comment by chrbusch** [comment]
Button "Adresse suchen" klicken, Namen eingeben

**Comment by Toelk-A** [comment]
funktioniert nicht

![image](https://cloud.githubusercontent.com/assets/22314271/19968256/1f060a18-a1d4-11e6-936e-937608cac426.png)

**Comment by chrbusch** [comment]
Wie sollte es auch, Sie sind ja nicht als Adresse erfasst.
Oder möchten Sie USER (ANWENDER) suchen?
Ich denke, eher Adressen, denn es geht ja hier um die "Entnehmer"
Bitte möglichst immer dazu schreiben was Sie erreichen möchten.

**Comment by chrbusch** [comment]
Ich denke, dies ist erledigt?

**Comment by Toelk-A** [comment]
ich habe alle offenen Punkte als separate "Issues" angelegt und schließe nun dieses Thema
