### ISSUE TITLE
Abbildung RBD Feiertage einfügen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#240]
Bitte die geleisteten Rufbereitschaftsdienste an Feiertagen mit abbilden:

![image](https://user-images.githubusercontent.com/22314271/27789008-111095f6-5feb-11e7-950f-e4f586688170.png)

**Comment by Toelk-A** [comment]
Feiertage 2017 in Mecklenburg- Vorpommern:

01. Jan 2017 Neujahr
14. Apr 2017 Karfreitag
17. Apr 2017 Ostermontag
01. Mai 2017 Tag der Arbeit
25. Mai 2017 Christi Himmelfahrt
05. Jun 2017 Pfingstmontag
03. Okt 2017 Tag der Deutschen Einheit
31. Okt 2017 Reformationstag
25. Dez 2017 1. Weihnachtsfeiertag
26. Dez 2017 2. Weihnachtsfeiertag

**Comment by chrbusch** [comment]
PersoMenü / Supervisor / Button "Tage/Feiertage"
Dann können Sie dort selbst jederzeit die Feiertage pro Bundesland pflegen.

**Comment by Toelk-A** [comment]
Diesen Button sehe ich nicht im Supervisor Menü

**Comment by Toelk-A** [comment]
Mein Fehler, ich war im Hauptmenü

**Comment by Toelk-A** [comment]
Feiertage sind alle in Ornella eingespeist. Nun bitte die RBD an Feiertagen in der o.g. Liste mit abbilden.
Danke

**Comment by Toelk-A** [comment]
Wann wird dieses Ticket erledigt?

**Comment by chrbusch** [comment]
Warum wurde dieses Ticket reopened,die Feiertage sind doch in der Liste?
