### ISSUE TITLE
Monatsweise Abrechnung der Entnahmen Partnerschaft der FÄ für Pathologie Güstrow-Rostock (ID 251 Adressen) funktioniert nicht

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#241]
Masteradresse ID 251

-> Button "Entnahmen prüfen und abrechnen"
-> Button "Prüflauf"
-> Datumseingabe 01.04.2017 - 30.04.2017

folgende Meldung:

![image](https://user-images.githubusercontent.com/22314271/27832759-25403122-60d0-11e7-96fc-e8aae24bdefc.png)

-> klick Button "aha"

![image](https://user-images.githubusercontent.com/22314271/27832780-3af71c74-60d0-11e7-96b0-60ab313641d0.png)

 Wir bekommen kein Ergebnis im **gewünschten Abrechnungszeitraum**.

-> Klick auf Button "Abrechnung"

Auflistung aller Spenden, nicht die des angegebenen Wunschabrechnungszeitraumes.

![image](https://user-images.githubusercontent.com/22314271/27832858-9c823686-60d0-11e7-9637-36fb25590dcb.png)

**Comment by chrbusch** [comment]
Try again now...

**Comment by Toelk-A** [comment]
Es funktioniert leider immer noch nicht. Nach Aussage von Dr. Manecke werden weder für Mai noch für April 2017 Abrechnungen angezeigt, obwohl Entnahmen durchgeführt wurden ((April 4x und Mai 9x).

Bitte schauen Sie noch einmal nach wo sich der "Fehler" verstecken könnte.

- Vielleicht sind die Abrechnungen geblockt, da sie bereits berechnet wurden?
- Liegen Fehler in der Dokumentation vor?

**Comment by chrbusch** [comment]
Bitte möglichst konkrete Fälle nennen (IDs), die fehlen, sonst suche ich zu lange danach.

**Comment by Toelk-A** [comment]
Es geht noch immer um den oben beschriebenen Fall. Es sollen die Abrechnungen für die Pathologie Südstadt für den Monat April und Juni berechnet werden. Die Fehler/Probleme sidn ebenfalls oben beschrieben. Masteradresse ID 251

**Comment by chrbusch** [comment]
Ja, aber welche Entnahmen sollten KONKRET erscheinen, tun dies aber nicht?
Hier brauch eich mind. ein Beispiel bitte
