### ISSUE TITLE
Neuer Status in Werteliste "GewebeAnforderung Details"

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#242]
Bitte den Status "Berechnet" einfügen

![image](https://user-images.githubusercontent.com/22314271/27857168-f3275f7a-6170-11e7-81c8-9d8405242418.png)

**Comment by chrbusch** [comment]
Erledigt

**Comment by Toelk-A** [comment]
Folgendes Problem tritt jetzt auf:
Allokation - Transplantatliste - Status Transplantat

"Originalwerteliste" 

![image](https://user-images.githubusercontent.com/22314271/27902568-7fbaecac-6236-11e7-83ff-7acb9e0f5b0c.png)

Klickt man nun auf "neu" passiert nichts, da in den Anforderungen eine "neue Werteliste" hinterlegt wurde, die den Status "neu" nicht mehr beinhaltet.

![image](https://user-images.githubusercontent.com/22314271/27902598-9b28be6a-6236-11e7-90c6-ee01676b3398.png)

"neue Werteliste"
![image](https://user-images.githubusercontent.com/22314271/27902644-c184d2b0-6236-11e7-82d0-8069772bc672.png)


Bitte fügen Sie diese "neue Werteliste" auch beim Öffnen der "Transplantatliste" ein, sodass man nach bestimmten Statuus suchen kann. Danke

**Comment by chrbusch** [comment]
Es gibt mehrere Transplantatlisten!
Bitte Screenshot schicken, der den Titel der Maske zeigt und genau benennen, was vor dem Feld steht, auf das Sie klicken.
Meine Erachtens gehört Ihre obige "Originalwerteliste" gar nicht zu Transplantaten, sondern zu Gewebeanforderungen

**Comment by Toelk-A** [comment]
Allokation - Gewebeanforderung nach Status

![image](https://user-images.githubusercontent.com/22314271/27904797-33700aaa-623e-11e7-89a3-e6fd8c3e77c1.png)


Klickt man nun "neu" 

![image](https://user-images.githubusercontent.com/22314271/27904810-3dafb5ba-623e-11e7-8047-0352b472ec29.png)

passiert nichts..... Wertelisten oben bereits kopiert

**Comment by chrbusch** [comment]
OK, ich dachte, Sie meinten das LAYOUT Allokation, statt dessen meinten Sie den BUTTON in Hauptmenü.
Klappt jetzt
