### ISSUE TITLE
Bitte "Archivierung" Rückgängig machen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#243]
Spender ID 7222 - Bitte Archivierung ruckgängig machen. Es wurde eine Spende durchgeführt. Aufgrund des Status "archiviert" fehlt die Spende in unserer Statistik.

![image](https://user-images.githubusercontent.com/22314271/27900946-79636c36-6230-11e7-80fc-cbfacd65019c.png)

**Comment by chrbusch** [comment]
7222 gips nich, bitte korrigieren

**Comment by Toelk-A** [comment]
2272

**Comment by chrbusch** [comment]
OK, ist erledigt
