### ISSUE TITLE
Entscheidung Mitarbeiter Monatsprotokoll 

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#244]
Die möglichen Überstunden sind in dem folgenden Diagramm aufgeschlüsselt. 

![image](https://user-images.githubusercontent.com/22314271/27904454-fee1bd34-623c-11e7-96bf-5b5964b15f52.png)

Orange = Arbeitszeitkonto, keine Auszahlung dieser Überstunden möglich
Grün = hier soll der Koordinator zwischen „Auszahlung“ oder „Arbeitszeitkonto“ entscheiden.
Violett = Sonderfall Gutschein – keine Wahl! (Wert 44,-€; Abzug des individuellen Anteils steuerpflichtiger ÜS), folgende Zusatzinformationen werden bis Freitag 07.07.17 nachgereicht:

A) ?Sind nicht genug steuerpflichtige ÜS auf dem ÜS Konto, kann trotzdem ein Gutschein ausgestellt werden?
B) Bruttostundenlohn A.Tölk 

1)	**Mitarbeiter benötigt eine Aufstellung der angefallenen ÜS:**
-	Steuerpflichtige ÜS gesamt
         -	Sonderfall Gutschein 
-	Steuerfreie ÜS gesamt
-	ÜS Arbeitszeitkonto

=> Nach der Entscheidung des Koordinators ob Auszahlung oder Arbeitszeitkonto (grüne Markierungen siehe oben), müssen die ÜS entsprechend abgezogen oder gutgeschrieben werden.
2)	**Steuerfreier Anteil ergibt sich aus der von Dr. Manecke zur Verfügung gestellten Excel Tabelle**
3)	**!ACHTUNG!** wurden im zu berechnenden Monat bereits ÜS vom AZK abgebummelt? Wenn ja, müssen diese natürlich bereits vom ÜS Arbeitszeitkonto abgezogen sein.

**Comment by chrbusch** [comment]
Brauchen wir die Option, dass die Überstunden _eines_ Tages teilweise AZK, teilweise ausbezahlt werden?
Das würde alles noch komplexer machen :-(((

**Comment by Toelk-A** [comment]
Ja die brauchen wir... ich weiß, dass es alles nur noch komplexer macht, aber dies sind die Wünsche der Mitarbeiter. Ich glaube auch hier können Sie eine Lösung programmieren...., meistens wären es ja nur die "steuerfreien Zuschläge", die sich die Mitarbeiter auszahlen lassen möchten. Die geleisteten ÜS an sich wollen meist abgebummelt werden.

Als Beispiel:

2h ÜS geleistet, davon 50% steuerfrei -> 2hÜS auf AZK und 1h (=50%) steuerfrei auszahlen lassen.

**Comment by Toelk-A** [comment]
![image](https://user-images.githubusercontent.com/22314271/28270364-82ad08d2-6b05-11e7-9a44-394c48a3df17.png)

zu A) 
Es soll **immer** ein Gutschein pro Monat ausgestellt werden. Ornella muss prüfen wie viele ÜS auf dem AZK sind und entsprechend des Bruttostundenlohnes ausrechnen wie viele Stunden pro Gutschein (Wert 44,-€) abgezogen werden müssen.

Sind nicht genügend ÜS auf dem AZK vorhanden um 44,-€ abzudecken, so soll den ÜS entsprechend ein Gutschein ausgestellt werden; z.B. habe ich nur die Hälfte der notwendigen Stunden darf auch nur ein Gutschein für 22,-€ ausgestellt werden.

zu B) Der Bruttostundenlohn entspricht dem der Koordinatoren Judith Kroll und Stephan Petrowski.
