### ISSUE TITLE
Rechtschreibung korrigieren

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#245]
Spenderdaten- Arzt-Abschluss - Das Wort "Abbruch" korrigieren

![image](https://user-images.githubusercontent.com/22314271/27907549-5f95adce-6248-11e7-8f0f-b4e3e4222fd7.png)

**Comment by chrbusch** [comment]
ENDLICH mal ein simples Ticket :-)))
Ist erl.
