### ISSUE TITLE
Spenderliste 2 weitere Spalten einfügen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#246]
Für unsere Statistik benötigen wir in der Spenderliste noch folgende Abbildungen:

1) Spalte "Entnommene Gewebe"
hier sollen die entnommenen Gewebe also "OG und/oder MSG und/oder KVG" abgebildet werden. Manchmal findet man vor Ort in der Klinik doch eine gewebespezifische Kontraindikationen in den Akten, sodass die jetzige Spalte "Gewebe" (gelbe Markierung) nicht die wirklich entnommenen Gewebe abbildet. Zur Programmierung könnte man auf den Reiter "Gewebe Präparate Transplantate" zugreifen. Alle unter "Gewebepräparate aufgeführten "Gewebepräparate" sind die wirklich entnommenen Gewebe.

2) Spalte "Anzahl entnommener Gewebepräparate"
Hier bitte die genaue Anzahl der entnommenen Präparate abbilden. Achtung es muss zwischen den verschiedenen Geweben (OG, MSG, KVG) unterschieden werden. Zur Programmierung könnte man auf den Reiter "Gewebe Präparate Transplantate" zugreifen. Alle unter "Gewebepräparate dieses Spenders" aufgeführten "Gewebepräparate" mit dem selben Farbcode bilden die "Anzahl entnommener Gewebepräparate" pro Gewebe.

roter Pfeil = Einfügen der beiden o.g. Spalten

![image](https://user-images.githubusercontent.com/22314271/27945705-7eb9759a-62ee-11e7-91c7-130cb20c7a3b.png)

**Comment by chrbusch** [comment]
1.) Was wäre hier die richtige Anzeige? Wenn ich die Daten richtig interpretiere, wurden bei Spender 2296 gar keine Entnahmen durchgeführt? Es gibt aber die bei der Spenderanlage erzeugten Datensätze für alle drei Gewebearten.
Soll ich diejenigen hier anzeigen, bei denen ein Entnahmedatum eingetragen wurde?

**Comment by chrbusch** [comment]
1. ist erl.
