### ISSUE TITLE
Änderung Status Transplantat "reserviert" zu "fest allokiert" programmieren

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#247]
Maske: Transplantat-Auswahl + Allokation

Im Moment sind Transplantate mit dem Status "Reserviert [33]" nicht direkt auf den Status "Fest allokiert" zu setzen. 

1) Man muss immer über den Button:

![image](https://user-images.githubusercontent.com/22314271/27950585-23730bce-6302-11e7-9795-c635e36baa73.png)

gehen. (Nachdem dann alle Patientendaten wieder eingegeben sind - siehe Problem 2) ) sucht man das selbe Transplantat (Reiter passende Transplantate) um es "Fest zu allokieren". Dies ist sehr umständlich. Bitte beim Transplantat selbst die Möglichkeit der "Fest allokiert" Option programmieren

![image](https://user-images.githubusercontent.com/22314271/27950691-8e0cdbfe-6302-11e7-981f-3a580467d285.png)

2) Nutzt man den o.g. Button, sind alle Patientendaten verschwunden. Dies bitte ebenfalls umprogrammieren.

**Comment by Toelk-A** [comment]
ist dies erledigt?

**Comment by chrbusch** [comment]
m.E. erledigt
