### ISSUE TITLE
Prozesschritt  Gewebe/Präparateeingabe

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#25]
-   Löschfunktion funktioniert nicht
-   Femur nicht in MSG Auswahlliste vorhanden

**Comment by chrbusch** [comment]
Löschen geht bei mir. 
Bitte immer (!) konkretes Beispiel nennen: Welcher Spender? Welcher Button genau?

Femur ist eine eigenen Gewebart, die nur bei Lebendspendern angeboten wird! 

![bildschirmfoto 2016-11-08 um 11 16 02](https://cloud.githubusercontent.com/assets/1241899/20095384/92d6a5f4-a5a5-11e6-8bce-f88302c20152.JPG)

**Comment by Toelk-A** [comment]
Es muss zwischen "Femur" und "Femurkopf" unterschieden werden. 

"Femurkopf" gehört zum Lebendspender. Der "Kopf" des Femurs (Oberschenkelknochen) kann während einer Patienten-OP entfernt und anstelle dessen ein künstliches Gelenk eingesetzt werden.   

"Femur" gehört zur MSG Entnahme - HKTS- Herz-Kreislauf-toter Spender. Hier würde man den den vollständigen Knochen entnehmen.

Beispiel: 031116-1231-GNO-SCD
MSG Entnahme

![image](https://cloud.githubusercontent.com/assets/22314271/20095807/486fad88-a5a7-11e6-8172-9ecbb303f904.png)



.

**Comment by chrbusch** [comment]
In der mir geschickten Gewebeliste gibt es "Femurkopf" nicht; es gibt "Femur" und  "Caput femoris".
Soll diese dt./latein. Mischung bestehen bleiben?

**Comment by chrbusch** [comment]
![bildschirmfoto 2016-11-10 um 15 10 34](https://cloud.githubusercontent.com/assets/1241899/20179744/db5977c6-a757-11e6-95cf-a886e9ddd94a.JPG)

**Comment by Toelk-A** [comment]
Femur (lateinisch)= Oberschenkelknochen=HKTS=MSG Entnahme

Caput femoris = Femurkopf = Lebendspender
