### ISSUE TITLE
Druckmaske Herstellungsprotokoll Teil I OG (Mat.-Dokum.)

### ISSUE THREAD

**Issue by chrbusch** [chrbusch/GTM-V#250]
Hier geht es um die Ausgabe des eingesetzten Materials als PDF.
Es ist die Fortsetzung von Ticket #216

**Comment by chrbusch** [comment]
Ist es nötig, die Material-Gruppen wie "sterile Einweg-Verbrauchsmaterialien" getrennt aufzuführen, oder kann ich das alles zusammen fassen?

**Comment by chrbusch** [comment]
Es gibt eine Spaltenüberschrift "PZN/REF/Artikelnr."
Was genau soll hierhin - m.E. brauchen wir eine hierarchische Bedingung:
Wenn wir eine PZN haben, nehmen wir diese;
andernfalls: Wenn wir ... haben, kommt das dorthin;
andernfalls: Wenn wir ... haben, kommt das dorthin....

**Comment by Toelk-A** [comment]
In der Exceltabelle (imTicket 216 hochgeladen) im Reiter Bemerkungen finden Sie die folgenden Hinweise:

"

Ähnlich dem Entnahmebericht im Spendebereich müssen nun alle verwendeten "Warenkörbe" und "Zusatzpositionen" zur Herstellung der Hornhäute den beiden Transplantaten zugeordnet (eingescannt) werden. Wie im PDF abgebildet benötigen wir: Tabelle 1 "sterile Einweginstrumente" -> hierzu wird ein Aufkleber, der sich auf den Instrumenten befindet auf das Protokoll aufgebracht, Tabelle 2 "sterile Einweg-Verbrauchsmaterialien" = im Warenkorb bzw. Zusatzposition hinterlegt, Tabelle 3 "Kulturmedien, Lösungen, Kontrollreagenzien" = in Warenkorb bzw. Zusatzposition hinterlegt und Tabelle 4 "Sonstige Verbrauchsmaterialien" = Zusatzpositionen.
  
  Jenachdem wie kompliziert die Programmierung ist, könnte man über eine "Zusammenfassung" der Tabellen 2-4 mit der Überschrift "Verwendete sterile Einwegmaterialien, Verbrauchsmaterialien, Kulturmedien, Lösungen und Kontrollreagenzien" nachdenken. Es müssen bei der Transplantatherstellung mehr Informationen auf dem Dokument hinterlegt sein als in der Spende: 1)Artikel 2) Hersteller/Lieferant 3) PZN/REF/Artikelnummer 4) Chargennummer 5) Verwendet Ja/Nein (würde sich über das Einscannen ergeben-könnte prinzipiell weggelassen werden)."

B) Wahrscheinlich bei keinem. -> ist das Abbildungsproblem bei der "Partnerhornhaut" fertig programmiert? #216 

Artikelnummer sollte meines Wissens immer in Ornella angelegt sein (zumindest beim Lieferanten hinterlegt).
