### ISSUE TITLE
Warenkorb wird nur für 1 der beiden Partnerhornhäute abgebildet

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#251]
Transplantat ID 897

Reiter Herstellung Warenkorb und Zusatzpositionen abgebildet. 

Partnerhornhaut ID896 

Reiter Herstellung nur Warenkorb - keine Zusatzpositionen abgebildet, obwohl die selben Zusatzpositionen genutzt wurden.

**Comment by chrbusch** [comment]
Frage vorab: Brauchen wir bei den Zusatzpos. den Dialog "Diese Artikelcharge welcher Gewebeart zuordnen:"???
Wir sind doch bei einem Transplantat, da steht doch die Gewebeart ohnehin fest?!

**Comment by chrbusch** [comment]
Haben Sie beide HH gescannt? Am besten anrufen und per Teamviewer gemeinsam machen

**Comment by Toelk-A** [comment]
UPDATE: unsere Mitarbeiter der GBM-V haben folgendes festgestellt:

bei den Pipetten ist es so, dass die HH in der der Artikel zuerst gescannt wird nicht mit dem Artikel versorgt werden, sondern nur die darauffolgenden. Ich habe dir deshalb immer die Bilder als Vergleich zwischen 274 CD  (ID 917) (hier wurde der Artikel zuerst gescannt) und 274 CS (ID 918) (hier wurde sie als weiteres Transplantat hinzugefügt) fotografiert. Es ist zu sehen das in 274 CD (ID 917) keine Artikel auftauchen aber in CS....

Falls Sie die Screenshots benötigen geben Sie bitte Bescheid.

**Comment by chrbusch** [comment]
Wenn das noch aktuell ist, bitte Beispiel parat haben und anrufen; ich möchte das per TeamViewer ansehen
