### ISSUE TITLE
Bezugfehler zur Angabe im Feld  "x-fach anwendbar für" (Artikel Details)

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#252]
Für den folgenden Artikel ID 110 wird die Gesamtanzahl immer als 1,5 anstatt wie in dem Feld "x-fach anwendbar für" eingegeben  2 .
Bitte prüfen

**Comment by chrbusch** [comment]
Bei mir klappt es für Charge 394 vom 5.7.2017
Aber bei Charge 229 desselben Artikels steht 1,5 in der Charge; war evt. beim Artikel früher mal 1,5 angegeben? Bitte hierzu mal anrufen, evt. muss man hier Daten manuell korrigieren.
