### ISSUE TITLE
Prozessschritt mobiles Entnahmeteam- Abbildung Adresse unvollständig abgebildet

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#253]
Bitte die Adresse der "Einrichtung der Gewebeentnahme" vollständig abbilden. Adresse ist fast immer Unvollständig/abgeschnitten.

![image](https://user-images.githubusercontent.com/22314271/28154639-29dded82-67ab-11e7-975d-14bd29754547.png)

**Comment by chrbusch** [comment]
Sind nun drei Zeilen mehr, sollte reichen
