### ISSUE TITLE
Erstellen mehrerer unabhängiger Entnahmeberichte eines Gewebetyps

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#254]
Spender ID 2342

Bei diesem Spender wurden 2 verschiedene Transplantattypen aus OG hergestellt (gelbe Markierung):

![image](https://user-images.githubusercontent.com/22314271/28272607-486c7b38-6b0c-11e7-8196-1296867e9204.png)

Es muss möglich sein mehrere unabhängige Entnahmeberichte eines Gewebetypes zu erstellen.
Z.B.: Es wurden die Hornhäute in Ribnitz entnommen udn an die GBM-V gesendet. Außerdem wurden die Skleren entnommen ABER nach München versandt. Im Moment ist diese "unabhängige Dokumentation" in Ornella noch nicht möglich. Bitte programmieren.

**Comment by chrbusch** [comment]
Ich habe nun das Datenmodell leicht umgebaut: Eine Gew.-proz. Einrichtung kann nun, wie bisher, einem ganzen Spd-Gewebe zugeordnet werden, oder auch den einzelnen, daraus erstellten Präparaten.
Wir müssen Montag hierzu tel., am besten zus,. mit Dr. Nitschke

**Comment by chrbusch** [comment]
Wenn Sie auf der Spd-Maske die Präparate auswählen, ist dann schon klar, welche Bank die einzelnen Präparate bekommt?
Dann könnte ich dort eine Dialog platzieren: "Alle Präparate an eine Bank (dann wird diese einmal erfragt) oder pro Präparat Bank erfragen?"

**Comment by chrbusch** [comment]
Dieser Dialog erscheint nun, wenn Sie bei einem TESTspender ein Präparat auswählen, bitte testen

**Comment by chrbusch** [comment]
Bitte einen herkömmlichen Entn.-Bericht ganz genau ansehen:
Wenn es mehrere für ein Gewebe gibt, welche Felder können abweichen?
Klar ist mir das für:
a) Adr. der gew.-proz. Einrtg
b) Liste der Präparate
c) KofferNr
Bitte alle weiteren Felder hier auflisten

**Comment by chrbusch** [comment]
Reminder für cbu Jan.2018: Neue Tabelle _EntnahmeBericht_ ist erstellt, im ERM zwischen Gewebe+Präparat zu legen.
Script schreiben, das für ein SpdGewebe die SpdPräp mit derselben fk_Adr_GewProzEinrtg sucht und druckt

**Comment by Toelk-A** [comment]
Bei folgendem Spender wurden die Sclera oculi im Entnahmebericht angelegt, der Entnahmebericht ist allerdings verschwunden. Jedoch taucht in den Geweben folgendes auf :

![image](https://user-images.githubusercontent.com/22314271/52262623-3c183f80-292d-11e9-897e-f96c2b4ded40.png)


Wir haben 3 Spenden bei denen die Sclera oculi nachträglich angelegt werden müssen können wir dies zusammen telefonisch tun?
Danke

**Comment by Toelk-A** [comment]
Folgende Spender benötigen noch die Sclera oculi (Gewebeprozessierende Einrichtung ist NICHT die GBM-V!)

Spender ID:

7182
7118
7194

**Comment by Toelk-A** [comment]
Testspender: ID 1361

Sclera oculi  angelegt -> Präparat gehört NICHT zur selben Bank ("Klick auf Nein"), neue Adresse ausgewählt - trotzdem werden Skleren in dem selben Entnahmebericht abgebildet

![image](https://user-images.githubusercontent.com/22314271/52270788-3d079c00-2942-11e9-9d9c-b7c027f88e49.png)

Programmierung bitte prüfen

**Comment by Toelk-A** [comment]
Ist meine Mail vom 07.02.2019 11:45Uhr abgearbeitet? Dieses Ticket hat die allerhöchste Priorität. Vorher nichts anderes bearbeiten, sondern dieses Ticket erst abschließen..

**Comment by chrbusch** [comment]
Muss das System nicht aufpassen, das ein bestimmtes SpdPräparat nicht auf zwei EBs auftaucht?
Dies würde bedeuten, dass man Präparate auswählen nur aus denen, die noch auf keinem EB waren.

**Comment by Toelk-A** [comment]
**Muss das System nicht aufpassen, das ein bestimmtes SpdPräparat nicht auf zwei EBs auftaucht?
Dies würde bedeuten, dass man Präparate auswählen nur aus denen, die noch auf keinem EB waren.**
Ja

-> Ich habe bei Spender ID 7118 Ihre Programmierungen getestet. Leider funktioniert es nciht so wie abgesprochen bzw. in meiner Mail beschrieben. Z.B. 

Gestern hatten wir telefonisch die "B"s  besprochen. Hier fehlt der Entnahmeort.

-> Verwendete Materialien sind unvollständig abgebildet:

![image](https://user-images.githubusercontent.com/22314271/52625238-d7bb2a00-2eb0-11e9-93ee-886041599b36.png)


Seite 2 scheint noch nicht durch Sie programmiert zu sein.

![image](https://user-images.githubusercontent.com/22314271/52625347-1355f400-2eb1-11e9-81eb-6c85018aeb99.png)

Bitte fertigstellen, damit ich testen kann.
Danke

**Comment by Toelk-A** [comment]
Bitte Programmierung prüfen:

Arzt und Koordinator werden nicht übernommen
![image](https://user-images.githubusercontent.com/22314271/52775419-f865ba00-303f-11e9-90d6-c01bab0fcf6b.png)


Text wird in beiden Bemerkungsfeldern gespiegelt. Dies bitte ausblenden bzw. unabhängig von einander gestalten.

![image](https://user-images.githubusercontent.com/22314271/52776978-1680e980-3043-11e9-8ce6-7d40e7ac14a9.png)

**Comment by chrbusch** [comment]
Die doppelte Bem. ist repariert, und es werden die Namen von Arzt und Entnehmer übernommen - aber nicht die Unterschriften, richtig?

**Comment by chrbusch** [comment]
Es sollte nun bei jedem neuen Spender bzw. Gewebe ein Prozessschritt
EntnahmeBericht-v2 anlegen
angelegt werden.
Auch ist der neue Entnahmebericht nun auf dem normalen Wege druckbar in ein PDF

**Comment by Toelk-A** [comment]
Test Anlegen neuer Entnahmebericht hat funktioniert!

Bitte noch die kursive Schriftform in normale Schriftform ändern.

![image](https://user-images.githubusercontent.com/22314271/52941617-89eb6980-3369-11e9-8f65-64c2f06e9f74.png)

Wo genau kann jetzt ein 2. unabhängiger Entnahmebericht zu OG angelegt werden?

**Comment by Toelk-A** [comment]
Wie lege ich denn nun einen 2. unabhängigen Entnahmebericht an? Die Erstversion scheint jetzt nach den ganzen Bugfixen zu funktionieren.

**Comment by chrbusch** [comment]
Moin, das teste ich jetzt mit einem Testspender durch

**Comment by Toelk-A** [comment]
okay, also ist das Thema jetzt erledigt :-)
