### ISSUE TITLE
KVG-Transplantat-Details ID 943 - NIF   als "Mitarbeiter Be- und Verarbeitung" hinterlegen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#255]
KVG-Transplantat-Details ID 943 Abschnitt "Be- und Verarbeitung" - Mitarbeiter

![image](https://user-images.githubusercontent.com/22314271/28413416-b3affb44-6d47-11e7-8ca1-9cb07f98b7ec.png)

Hier bitte auch Dr. Nitschke (NIF) hinterlegen, da er ebenfalls als Mitarbeiter "Be- und Verarbeitung" in Frage kommt.

**Comment by chrbusch** [comment]
Sollte erledigt sein
