### ISSUE TITLE
Abrechnung bereits berechneter HH-Transplantate  Rechnungsnummer: 2017-0362

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#257]
Rechnungs ID: 505

Bei dieser Rechnung wurden Transplantate abgerechnet, die an anderen Einrichtungen als München versandt wurden, bereits berechnet und bezahlt waren.

Bitte prüfen Sie diese Rechnung und ermitteln das Problem.

**Comment by chrbusch** [comment]
Ich denke, dies ist verstanden und behoben? Dann bitte Ticket schliessen
