### ISSUE TITLE
Ornella Nutzer die für beide Mandanten angestellt sind

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#258]
Wir haben Mitarbeiterinnen, die sowohl für den Mandant GBM-V als auch GTM-V arbeiten. 

Dr. Nitschke soll z.B. in KVG-Details als "Mitarbeiter Be- und Verarbeitung" in der Werteliste erscheinen (Ticket #255). Da er als Mandant die GTM-V gelistet hat, kann er nicht gleichzeitig Mandant der GBM-V sein. Ein weiteres Problem stellt die Stundenabrechnung dar. Stunden müssen pro Mandant dokumentierbar sein (gilt für Personen die für beide Mandanten tätig sind)

Idee 1)  einer Person lassen sich mehrere Mandanten zuordnen
Idee 2) Person duplizieren und dem jeweils fehlenden Mandanten zuordnen

**Comment by chrbusch** [comment]
jetzt mehrere Mandanten pro User möglich
