### ISSUE TITLE
Prozessschritt Dokumentenablagen nicht aktiv

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#26]
-   Totenschein
-   Diagnostische Befunde
-   Epikrisen
-   Abschlussepikrisen
-   Dokumente Hausarzt

**Comment by chrbusch** [comment]
Bitte senden Sie mir jeweils ein typisches Dokument zu

**Comment by Toelk-A** [comment]
Das Dokumentformat ist generell A4.

Totenschein ist 1 Seite - wird normalerweise aus Patientenakte von uns kopiert (Vorlage nur als Hardcopy)

Diagnostische Befunde und Epikrisen können 0- ca. 30 Seiten (oder mehr) Seiten beinhalten. Meist nur Hardcopy vorhanden, manchmal werden Befunde/Epikrisen per Fax nachgereicht (digital).

Abschlussepikrisen ca 1-5 Seiten, meistens als FAX (digital) zugesandt.

Dokumente vom Hausarzt können 1-20 Seiten (oder mehr) beinhalten (bekommen wir meist gefaxt - liegen digital in unserem Maileingang vor).

Ist es notwendig, dass Ihnen die o.g. Dokumente vorliegen oder reichen Ihnen die hier gemachten Angaben?

**Comment by chrbusch** [comment]
Bitte testen Sie den neuen Reiter "Ext. Dokumente" auf der Spendermaske, v.a. den Button "Neues Dokument auswählen"
Nur Dokumente, die als DATEIEN vorliegen, können zu geordnet werden - ansonsten könnten Sie höchstens eine Textinformation zu einem vorhandenen Dokument eintippen

![bildschirmfoto 2016-11-07 um 12 36 50](https://cloud.githubusercontent.com/assets/1241899/20056539/13ddf9aa-a4e7-11e6-8483-93ae327e2527.JPG)

**Comment by Toelk-A** [comment]
Funktioniert :+1: 

1) das PDF müsste in Ornella geöffnet werden können, da die ärztlichen Mitarbeiter sämtliche Dokumente lesen und gegenzeichnen müssen

2) technische Frage: gibt es eine Möglichkeit das Fax (als Mail im PDF Format) direkt in Ornella einzuspeisen, oder gibt es immer den Zwischenschritt über "Speichern" und "Hochladen"?

**Comment by chrbusch** [comment]
1) Gibt nun neuen Button "Dokument öffnen"
2) Dies wäre zumindest sehr aufwändig, kommt m.E. für diese Programmversion nicht in Frage

**Comment by Toelk-A** [comment]
1) funktioniert super. Das ärztliche Personal muss die hochgeladenen PDFs lesen und gegenzeichnen, bzw. in irgendeiner Art und Weise als "gelesen" markieren können. Diese Funktion darf nur dem ärztlichen Personal zur Verfügung stehen.  Ist dies möglich?

2) ok

**Comment by chrbusch** [comment]
Wenn sich Arzt oder Supervisor angemeldet haben, erscheint der folgende
![bildschirmfoto 2016-11-08 um 11 14 26](https://cloud.githubusercontent.com/assets/1241899/20095134/89026546-a5a4-11e6-9ef0-c50268d41b2b.JPG)
 Dialog:

**Comment by chrbusch** [comment]
...mit dem Ergebnis

![bildschirmfoto 2016-11-08 um 11 16 02](https://cloud.githubusercontent.com/assets/1241899/20095185/c4a3ae16-a5a4-11e6-97cd-f03d6139da1b.JPG)

**Comment by Toelk-A** [comment]
Okay, super

**Comment by Toelk-A** [comment]
Nachtrag: Falls das Einwilligungsgespräch in der Klinik durch einen Stationsarzt stattgefunden hat, müssen wir diese Aktennotiz ebenfalls in der Datenbank hinterlegen.

Zusätzlich zu den 5 o.g. Dokumenten benötigen wir bitte noch einen 6. Punkt  "Aktennotiz Einwilligungsgespräch Stationsarzt".
