### ISSUE TITLE
Layout Überstundenbericht

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#260]
[Entwurf Layout Überstundenbericht.xlsx](https://github.com/chrbusch/GTM-V/files/1231633/Entwurf.Layout.Uberstundenbericht.xlsx)

**Comment by Nitschke-FP** [comment]
Der Bericht ist in Abstimmung mit dem Steuerbüro angepasst worden.
Das Steuerbüro benötigt ihn bis Anfang Oktober
[Entwurf.Layout.Uberstundenbericht.xlsx](https://github.com/chrbusch/GTM-V/files/1283894/Entwurf.Layout.Uberstundenbericht.xlsx)

**Comment by Nitschke-FP** [comment]
kann der Bericht bei den MA als pdf abgelegt werden?

**Comment by chrbusch** [comment]
Was meinen Sie damit technisch?
Wir könnten zB das jeweilige PDF, mit der Mitarbeiter-ID versehen, ins Ornella-Archiv packen, sowie externe Dokumente (Totenschein etc)

**Comment by Nitschke-FP** [comment]
Ja, in der Art. In dem Layout (siehe Bild) einen Reiter Dokumente, wo diese Berichte abgelegt werden.
![bildschirmfoto 2017-09-07 um 11 37 58](https://user-images.githubusercontent.com/22288833/30156878-245d9604-93c1-11e7-8b4d-048cb1a2c18a.png)
