### ISSUE TITLE
Löschen von Datensätzen

### ISSUE THREAD

**Issue by Nitschke-FP** [chrbusch/GTM-V#261]
Bitte die Datensätze nicht physikalisch löschen, sondern alle relevanten IDs ins Negative kehren.
Kosten gehen auf GTM-V

**Comment by chrbusch** [comment]
OK, baue ich heute ein. Wir haben dann übrigens wie bei versehentlich gelöschten Prozessschritten auch die Möglichkeit der Reanimation

**Comment by chrbusch** [comment]
Die drei Buttons sind nun umgebaut. Bitte an Testspendern vorsichtig ausprobieren!
