### ISSUE TITLE
Dienstplan Koordinatoren, Mitarbeiter Herstellung, Ärzte

### ISSUE THREAD

**Issue by Nitschke-FP** [chrbusch/GTM-V#262]
Bei der Prüfung, ob es einen Dienstplan für Oktober 2017 gibt, wurde mir keine Einteilung der Mitarbeiter angezeigt. Daraufhin habe ich im Menü einen Dienstplan erstellen für nächsten Monat geklickt und folgendes Protokoll zur Ansicht bekommen (siehe Anlage). Was bedeutet das?
![bildschirmfoto 2017-09-04 um 09 38 21](https://user-images.githubusercontent.com/22288833/30016455-7acd62e4-9155-11e7-8efd-426727f141b5.png)

**Comment by chrbusch** [comment]
Dienste des 1. und 2, des Monats dürfen nicht gelöscht werden: Ist der Monatsletzte ein Freitag, so gehören 1.+2. im neuen Monats zum RBD des Wochenendes, das im Vormonat begonnen hat.
Aber alle RBD ab dem 3. werden zurück gesetzt.
Und das Dialogfenster zeigt: Keine Fehler aufgetreten, alles wie geplant erledigt

**Comment by Nitschke-FP** [comment]
Wenn ich es richtig verstanden habe, haben Sie das Script zu der Üst.-Berechnung bisher nur bei den Koordinatoren laufen lassen. Dieses bitte auch für die übrigen MA durchführen.
