### ISSUE TITLE
Allokation, Wochenbericht

### ISSUE THREAD

**Issue by chrbusch** [chrbusch/GTM-V#264]
Wir schließen jeden Donnerstag die Allokation ab, damit die Vorbereitungen der Bank für die Verschickung erfolgen können. Sinnvoll wäre hier, einen Bericht zu erstellen , der die Allokationen der nächsten Woche dokumentiert mit folgenden Daten:
Anfordernde Einrichtung
Patientenname, -vorname (sind keine Patientendaten erfasst, bitte leere Felder anzeigen)
Patientenalter
Geplantes Operationsverfahren
Klassifikation Anwendung (Kornea) (hier bitte im Dropdown "alle Anwendungen" hinzufügen
letzte Zellzahl
Voroperationen Spenderauge (dieses Feld muß noch erstellt werden im Layout OG-Transplantat Details)
Freigabe 20b vorhanden (Ja/Nein/Offen - Feldinhalt bitte aus dem Feld Entnahmebericht OG: Freigabe zur Gewebeaufbereitung entnehmen
Transplantationsdatum
Lieferdatum/-zeit
Lagerung im Transportmedium

Die Tabelle bitte sortieren nach

Lagerung im Transportmedium (aufsteigend)
Anfordernde Einrichtung

**Comment by chrbusch** [comment]
Frage: Meint "Lieferdatum/-zeit" den WUNSCH-Zeitpunkt des Bestellers?

**Comment by Nitschke-FP** [comment]
Ja

**Comment by Nitschke-FP** [comment]
Ja

**Comment by Nitschke-FP** [comment]
Ja

**Comment by chrbusch** [comment]
Was ist das Suchkriterium für die in dem Bericht gezeigten Daten?
Bitte "die Allokationen der nächsten Woche " präzisieren unter Nennung der zu durchsuchenden Datenfelder

**Comment by Nitschke-FP** [comment]
Suchkriterium ist das Wunschlieferdatum. Hier wäre der Dialog, wie es bei der Suche Zeitbereich für Datum "Lieferdatum" sinnvoll. Dann kann man auch schon die übernächste Woche anschauen.

**Comment by chrbusch** [comment]
Bitte testen Sie im HM den neuen Button, im Thema Allokation
![bildschirmfoto 2017-09-11 um 12 03 29](https://user-images.githubusercontent.com/1241899/30269590-9c8bbac2-96e9-11e7-8f23-40f617efe978.JPG)
