### ISSUE TITLE
Erstellung FT/Wochenend-Dienstplan Mitarbeiter Herstellung

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#266]
Für die Mitarbeiter der GBM-V (Standort „Rostock GBM-V“) soll ebenfalls ein Dienstplan erstellt, und in den RBD Monatsplan integriert, werden:

1)	Es gibt nur Dienste an Wochenenden (Sa+So) und an Feiertagen
2)	Wer am Wochenende Dienst hat, kann nicht an einem direkt darauffolgen Feiertag (Montag) Dienst haben
3)	Die Dienste sollen gleichmäßig verteilt werden
4)	Abbildung der Dienste im RBD Monatsplan der Koordinatoren - Dienstplanspalte „RBD Herstg“ (gelb markiert)

![image](https://user-images.githubusercontent.com/22314271/31073355-e389f94c-a76b-11e7-9e0a-4394e56d45d3.png)

5)	RBD-Arzt ist derselbe wie im RBD Monatsplan der Koordinatoren

**Comment by chrbusch** [comment]
Ich vermute, es geht nur um die Kollegen des Teams5 = "MA Herstellung"?

**Comment by chrbusch** [comment]
Bitte kreuzen Sie zB im August einige der Hertellg.-Mitarb. für RBD an und drucken den Plan - ist das dann wie gewollt?

**Comment by chrbusch** [comment]
"Es gibt nur Dienste an Wochenenden (Sa+So) und an Feiertagen"

Ist das so wie bei den Koord.: Der Dienst beginnt Fr Abend und geht bis So Abend?

**Comment by chrbusch** [comment]
Script läuft im Prinzip; Mittwoch gemeinsam testen

**Comment by Toelk-A** [comment]
1) Ja es handelt sich um Team 5 (MA Herstellung)
2) Der RBD findet nur an den Wochenenden (Sa und So) sowie an Feiertagen statt. Der Freitag ist nicht inkludiert.
3) Nach Klick auf den Button "RBD Plan Herstlg." wird der Dienstplan für die Koordinatoren erstellt.
![image](https://user-images.githubusercontent.com/22314271/31169451-ebb24898-a8f8-11e7-9db1-cc53960a57c0.png)

**Comment by Toelk-A** [comment]
Wann können wir dies testen?

**Comment by chrbusch** [comment]
Scheint mir zu klappen!
Bitte RBD-Plan November testen

**Comment by Toelk-A** [comment]
Plan wurde für November erstellt. Anstatt Frau Hohmann sollte eigentlich Frau Deuschle am 25.11.17 Dienst haben...Bitte prüfen
