### ISSUE TITLE
Einmaliges Erstellen des RBD-Planes Mitarbeiter Koordinatoren

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#268]
Der Monatsplan darf nur 1x pro Monat durch das System erstellt werden. Danach darf der Button "RBD Plan für Koord. erstellen" nicht mehr für den selben Monat genutzt werden können.

![image](https://user-images.githubusercontent.com/22314271/31179987-b48cf578-a91d-11e7-9a7f-7426abbf2a91.png)

Der 1x erstellte Monatsplan kann also nur über Tauschwünsche verändert werden. Über diese Funktion verfügen nur die Supervisor.

**Comment by chrbusch** [comment]
Erl. für Koordinatoren; soll wohl auch für Ärzte und Herstellung geschehen?

**Comment by Toelk-A** [comment]
ja
