### ISSUE TITLE
Prozessschritt Untersuchungsauftrag GTM-V

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#27]
-   Adresse GTM-V mit Einblenden (inkl. Tel.+Fax)
-   Aufnahmenummer entspricht Nummer in Spendermeldung wenn Proben aus meldender Einrichtung = Labor (HRO-Süd)

**Comment by chrbusch** [comment]
Welche "Nummer in Spendermeldung" meinen Sie?
Bittexaktere Angaben ich kann sonst nicht tätig werden.

**Comment by Toelk-A** [comment]
Aufnahmenummer = Aufnahmenummer in Spendermeldung WENN Blutproben aus meldender Einrichtung "Südstadtklinikum"

**Comment by chrbusch** [comment]
Beides erledigt, bitte testen

**Comment by Toelk-A** [comment]
Adresse funktioniert,

Aufnahmenummer wird hier nicht automatisch eingetragen

![image](https://cloud.githubusercontent.com/assets/22314271/20171983/7b7bbb58-a733-11e6-89be-6087d7643967.png)
