### ISSUE TITLE
MSG Preise u. Abrechnung

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#270]
1)	Die Spenderalter für mögliche MSG-Entnahmen ändern sich folgendermaßen:

Frauen: 
-	Präparateset „J“ bis inkl. 65 Jahre
-	Präparateset „A“ von >=66 bis inkl. 70 Jahre

Männer:
-	Präparateset „J“ bis inkl. 65 Jahre
-	Präparateset „A“ >=66 bis inkl. 85 Jahre

2)	Bitte ein neues Transplantat in Ornella „Präparatarten“ einspeisen:
MSG // Knochen// CT// Calcaneus + Talus (beide Seiten vorhanden) // J+A//Beide Seiten

	Dieses Präparat muss dann ebenfalls auf den MSG Etiketten erscheinen

3)	Preise pro Präparate müssen für die Rechnungsstellung aktualisiert werden. Können wir dies selbst tun?

**Comment by chrbusch** [comment]
1. und 2. sind erledigt

**Comment by chrbusch** [comment]
Was meinen Sie mit 3.?
Soll für jede Rng das angepasst werden können? Oder möchten Sie jetzt einmalig für kommenden Rng die Preise ändern?

**Comment by chrbusch** [comment]
siehe Buchhaltung, letzter Button
![bildschirmfoto 2017-10-09 um 15 27 09](https://user-images.githubusercontent.com/1241899/31340430-5f85dfe4-ad06-11e7-8db0-33334be97977.JPG)

**Comment by Toelk-A** [comment]
zu 3: Preise sollen ab dem 01.10.2017 gelten. Die MSG Präparate sind unter dem Button "Preise Transplantate" nicht zu finden.

**Comment by Toelk-A** [comment]
zu3:

Die Abrechnung soll über den Button /MSG/ABC Abrechnung erstellt werden.

Rechnungsdarstellung (selber Aufbau wie Rechnungsstellung GTM-V an GBM-V):

### Datum / Bezeichnung / Anzahl / Betrag  

**Datum**
Datum Entnahme

**Bezeichnung, Anzahl, Preis**
_Position 1:_ Entschädigung 300,-€ pro Spender
_Position 2:_ Knochenspender -> hier sollen die MSG - Präparate „Knochen“ aus dem Reiter „Gew. Pr. Tr.“ „Gewebepräparate dieses Spenders“ mit **Anzahl** abgebildet werden. Anhand der Anzahl der entnommenen Knochenpräparate errechnet sich der **Preis** (siehe Tabelle Anzahl Gewebe)

![image](https://user-images.githubusercontent.com/22314271/31344210-55c83bc6-ad12-11e7-94e3-373ac6fbbc76.png)

Position 3: _Sehnenspender_ -> hier sollen die MSG – Präparate „Sehnen“ aus dem Reiter „Gew. Pr. Tr.“ „Gewebepräparate dieses Spenders“ mit **Anzahl** abgebildet werden. Anhand der Anzahl der entnommenen Sehnenpräparate errechnet sich der **Preis** (siehe Tabelle Anzahl Gewebe):

![image](https://user-images.githubusercontent.com/22314271/31344279-859f549c-ad12-11e7-80e4-0280242bd46b.png)

**Comment by chrbusch** [comment]
Verstehe ich richtig, dass dies eine Rng von GTM-V an eine Bank ist?
Die zahlen also 300 Eur pro Spender zzgl. einem Preis, der von Anzahl Präparate pro Gewebeart und Spenderalter abhängt?
Soll die Anzahl Präparate manuell eingegeben werden, oder bekommt die Bank immer alle Präparate, die einem Spender entnommen wurden?
Sind es immer mind. 8 Präparate pro Gewebeart?

**Comment by chrbusch** [comment]
Sie können jetzt über den Button Preise auch die MSG-ABC-Preise selbst definieren, hierzu bitte anrufen
![bildschirmfoto 2017-10-12 um 10 12 42](https://user-images.githubusercontent.com/1241899/31485936-f0d631ac-af35-11e7-9ce8-72affe61203d.JPG)

**Comment by chrbusch** [comment]
Wenn die MSG-Präparate abgerechnet werden: Es dann bei den SpenderPräparaten schon die gewebeproz. Einrichtung eingetragen?
Diese bekommt doch wohl die Rechnung?

**Comment by chrbusch** [comment]
Wie lautet der Vortext f.d. Rng? Ist es auch

"LEISTUNGSABRECHNUNG
iermit erlauben wir uns, für folgende in Ihrem Auftrag erbrachte Leistungen vertragsgemäß zu berechnen:"

**Comment by Toelk-A** [comment]
1) Alle Preise sind nun in Ornella hinterlegt.

2) Die gewebeprozesssierende Einrichtung ist im MSG-Entnahmebericht des Spenders hinterlegt und somit zur Rechnungsstellung bereits eingetragen. Die Rechnung bekommt die gewebeprozesssierende Einrichtung.

3) Vortext + Nachtext für die Rechnung: 

"Hiermit erlauben wir uns, für folgende in Ihrem Auftrag erstellte Leistungen vertragsgemäß zu berechnen:"


XXXX


"Bitte begleichen Sie innerhalb von 14 Tagern de Rechnungsbetrag durch Überweisung an die u.g. Bankverbindung.
Die Leistung ist umsatzsteuerfrei gemäß §4 Nr. 17a UStG.

Mit freundlichen Grüßen


Carmen Schmalfuß-Gross
Finanzbuchhaltung

**Comment by chrbusch** [comment]
Texte sind eingebaut, bitte die Abrechnungstaste beim Spender testen.

![bildschirmfoto 2017-10-16 um 14 08 07](https://user-images.githubusercontent.com/1241899/31611199-7385dc90-b27b-11e7-9a21-ea6b70eac82a.JPG)

**Comment by Toelk-A** [comment]
1) Button getestet und funktioniert.

2) Bitte hinter Position 1 (Entschädigung für Entnahme pro Spender) die Spenderkennnummer aufführen

**Comment by chrbusch** [comment]
2. ist erl. für ab jetzt erstellte Rng

**Comment by chrbusch** [comment]
Ich habe gerade zwei Tippfehler im Vortext von 62 Rechnungen entdeckt; der Fehler war aber in der mir gelieferten Vorlage, siehe Bild.
Ist ab jetzt korrigiert (für neue Rng)

![bildschirmfoto 2018-04-16 um 09 49 45](https://user-images.githubusercontent.com/1241899/38796396-9fd36b18-415b-11e8-9dbe-c3eeffa0fcdb.JPG)
