### ISSUE TITLE
Persönlicher Kalender bitte 2018 ebenfalls komplett freischalten

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#271]
Bitte im persönlichen Kalender komplett das Jahr 2018 freischalten, sodass auch Wunschdienste dokumentiert werden können.

![image](https://user-images.githubusercontent.com/22314271/31424629-8d52c71a-ae5b-11e7-848b-4a84a02c0e12.png)

**Comment by chrbusch** [comment]
Nach FM-Neustart zeigt das System nun 13 Monate voraus

**Comment by Toelk-A** [comment]
erledigt
