### ISSUE TITLE
Gleichverteilung der Dienste WT, WE und FT Programmierung prüfen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#272]
Werden wirklich alle Dienste gleichmäßig auf die Mitarbeiter (Koordinatoren) verteilt?
Bitte unbedingt erneut die Programmierung prüfen, sodass 2018 dann korrekt aufgeteilt wird.

MA Tölk: hat 31 WE-Dienste 2017//MA Schweder 37 WE-Dienste 2017
MA Petrowski hat 0 FT-Dienste 2017
MA Tölk hat 48 WT-Dienste 2017 // MA Kroll 41-WT-Dienste 2017

**Comment by chrbusch** [comment]
Ich finde im System andere Werte; sie sind ähnlicher als die oben angegebenen.
In den komplexen Scripts kan ich keine Fehler finden; kann es sein, dass Urlaub und ähnliches das System daran gehindert hat, genau gleichmäßig zu verteilen?

![bildschirmfoto 2017-10-11 um 14 06 10](https://user-images.githubusercontent.com/1241899/31439714-7b98fe0e-ae8d-11e7-87c8-35976db9ea94.JPG)

**Comment by Toelk-A** [comment]
1) Prinzipiell haben alle MA den selben Urlaubsanteil im Jahr.

2) Wenn Sie andere Werte im System finden, dann scheint unsere "Liste Mitarbeiter" nicht aktuell zu sein. Außerdem werden hier ebenfalls keine Feiertage aufgelistet -> Bitte prüfen.

![image](https://user-images.githubusercontent.com/22314271/31439851-09de2a40-ae8e-11e7-973c-c16edae97b92.png)


3) Aufgrund von Krankheit oder AZK oder nicht verfügbar, kann das System nicht immer gleich verteilen. Hier soll es aber einen Mechanismus geben der alle RBD-Dienste gegeneinander vergleicht und gleich verteilt.

**Comment by chrbusch** [comment]
Ich habe die Liste nun um die Feiertags-Felder ergänzt, bitte erneut prüfen

**Comment by Toelk-A** [comment]
Bitte Berechnung der Feiertage beim MA Petrowski überprüfen. Nach seinen Aussagen hat er nur den 01.01.17 als Feiertags RBD geleistet. In Ihrer Liste stehen allerdings 6 geleistete FT RBD, der letzte am 17.12.17 (dies ist meines Erachtens nach kein Feiertag in MV).

**Comment by Toelk-A** [comment]
In welchem Rhythmus aktualisiert sich die "Liste Mitarbeiter"?

**Comment by chrbusch** [comment]
Bislang immer dann, wenn ein Plan erstellt wird.
Ich habe jetzt aber einen neuen Dialog eingebaut:
![bildschirmfoto 2017-10-17 um 10 45 09](https://user-images.githubusercontent.com/1241899/31655205-76d2a3a8-b328-11e7-8428-d67a0c1f1c2a.JPG)
