### ISSUE TITLE
Mitarbeiter Maschmeier Änderung auf Vollzeit

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#274]
MA Maschmeier hat seit 01.10.2017 eine Vollzeitstelle. Nach Aktualisierung der Arbeitsstunden por Tag udn Monat 

![image](https://user-images.githubusercontent.com/22314271/31433376-66972c38-ae79-11e7-9ef6-e9331494f04c.png)

ändert sich trotzdem nicht das Stundensoll (von 6 auf 8h) im persönlichen Kalender.

![image](https://user-images.githubusercontent.com/22314271/31433445-a87f4cde-ae79-11e7-86e4-a26f28592286.png)

**Comment by chrbusch** [comment]
Auf der Mitarb.-Maske wurden anscheinend die Werte für die Stunden pro Monat manuell verändert, aber nicht die für Tage, siehe markiertes Feld.
Man könnte hier eine Automatik programmieren; aber derzeit müssen Si dies händisch anpassen, wenn sich ein Arbeitsvertrag ändert.
Bitte dies erledigen und dann das AZK-Soll prüfen

![bildschirmfoto 2017-10-11 um 13 39 58](https://user-images.githubusercontent.com/1241899/31438773-e07022d4-ae89-11e7-9082-cf23395af9ef.JPG)

**Comment by Toelk-A** [comment]
funktioniert
