### ISSUE TITLE
Vollständige Abbildung verwendeter Materialien im Entnahmebericht

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#275]
Spender ID: 2808

Bitte generell im KVG Entnahmebericht "verwendete Materialien" vollständig abbilden.

![image](https://user-images.githubusercontent.com/22314271/31497647-0110aabe-af60-11e7-8988-8c1d11163c5f.png)

**Comment by chrbusch** [comment]
Ich lasse nun die Materialien in etwas kleinerer Schrift drucken, wenn es mehr als 13 Zeilen sind


![bildschirmfoto 2017-10-16 um 13 31 21](https://user-images.githubusercontent.com/1241899/31609913-502b3c18-b276-11e7-8985-d2ec527c36e3.JPG)

**Comment by Toelk-A** [comment]
erledigt
