### ISSUE TITLE
Kennnummer "Kenn Nr- GTM-V" Layout Transplantat Details falsch verknüpft

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#276]
### Spenderdetails, Reiter Gewebe Präparate Transplantate
Spender ID:2808

"Gewebepräparate dieses Spenders"
Präparate OG
-> werden Bulbi entnommen so erstellt Ornella das Kürzel Spenderkennummer - OD / -OS (gelb hinterlegt) 
![image](https://user-images.githubusercontent.com/22314271/31498711-06fdc332-af63-11e7-86cb-ec951dbb2eb9.png)

Diese Nummer muss nun im folgenden Layout ebenfalls abgebildet werden:

### Layout: OG-Transplantat Details
Spender ID:2808

**Kenn-Nr GTM-V**

![image](https://user-images.githubusercontent.com/22314271/31498728-17861088-af63-11e7-8ce3-fc2f5a620e60.png)

Hier wird derzeit fälschlicherweise "CSK" anstatt -OD // -OS abgebildet.

**Comment by chrbusch** [comment]
Das obere ist die KennNr eines Präparates, das untere die eines Transplantates.
Das sind doch nicht dieselben Informationen?

**Comment by Toelk-A** [comment]
KennNr = bitte so abbilden wie oben beschrieben. Dieses Präparat muss als Bankeingang (GTM-V in die GBM-V) wie oben beschrieben dokumentiert werden. Zur Erklärung: Die GTM-V entnimmt das Präparat "Oculus" und bringt dieses Präparat auch in die GBM-V. Danach wird ind er GBM-V ein Transplantat hergestellt. Bitte umsetzen. Danke

**Comment by chrbusch** [comment]
Erl., bitte prüfen
