### ISSUE TITLE
Personalplanung - neuer Job "AZK MA Wunsch"

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#278]
1) Bitte den Sonderjob "Freischicht" (Nr. 10) in "AZK MA Wunsch" umbennen.

2) Sonderjob "AZK" (Nr 8) darf nicht mehr als Auswahl für die Koordinatoren in der Jobliste erscheinen, sondern nur für die Geschäftsführung/Supervisor sichtbar sein.

Hintergrund ist, dass die Geschäftsführung den AZK über die Änderung des Jobs von "AZK MA Wunsch" in "AZK" umwandeln kann und somit eine Prüfung und Freigabe des AZK´s durch die Geschäftsführung stattfand.

![image](https://user-images.githubusercontent.com/22314271/31757049-7aa16246-b4a7-11e7-94bb-d4bebc1f03e5.png)

**Comment by chrbusch** [comment]
erledigt

**Comment by Toelk-A** [comment]
Ist Nr. 2 auch erledigt? Ich sehe Nr. 8 noch, kann auch aufgrund meines Supervisor Status sein.

**Comment by chrbusch** [comment]
2. ist m.E. auch erledigt; bitte am Platz eines Normalsterblichen testen OHNE dass Sie sich dort einloggen.
