### ISSUE TITLE
GBMV/Dokument 1 Transplantationsbegleitschein 

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#279]
Wie besprochen anbei der Transplantationsbegleitschein. Bei Fragen bitte anrufen

[Dokument Nr 1 - Transplantationsbegleitschein OG-Transplantate modified for CBu.docx](https://github.com/chrbusch/GTM-V/files/1397918/Dokument.Nr.1.-.Transplantationsbegleitschein.OG-Transplantate.modified.for.CBu.docx)

**Comment by chrbusch** [comment]
Die Aufbereitung dieses Dokumentes haben Sie IDEAL gelöst.
Wir werden so sehr schnell die zu druckenden Daten zusammenstellen können.
Bitte genau so weiter machen!
Sehe ich richtig, dass alles, was NICHT nummeriert wurde, auch nicht aus Ornella kommt, etwa "Art der Naht" - weil dies der Operateur einträgt?

**Comment by chrbusch** [comment]
Bitte für jedes Dokument beschreiben, wie Erzeugung und Druck in den Arbeitsablauf integriert werden sollen

**Comment by Toelk-A** [comment]
Genau alles was nicht dokumentiert wurde wird von der transplantierenden Einrichtung ausgefüllt. Der Text muss allerdings im Dokument abgebildet sein.

**Comment by chrbusch** [comment]
Woher kommt "Diagnose / Indikation" beim Empfänger?

**Comment by chrbusch** [comment]
" (transplantierende Einrichtung abbilden, nicht Namen des Bestellers)"
Soll hier die ganze mehrzeilige Adresse hin?
Im Firmular ist ja nur eine Zeile Platz...

**Comment by Toelk-A** [comment]
1) Diagnosen und Indikation werden vom Operateur eingetragen (Dieses Feld wurde nicht mit Nr. 6 markiert)

2) Nur den Namen der transplantierenden Einrichtung (ohne Abteilungs-, Straßen- und Ortsangabe) -> gelbe Markierung

![image](https://user-images.githubusercontent.com/22314271/31992271-19b33108-b97a-11e7-9da3-eb1b6c2a9f5d.png)

**Comment by chrbusch** [comment]
Bitte den neuen Button bei den Transplantaten klicken und resultierendes PDF begutachten

![bildschirmfoto 2017-10-25 um 12 52 03](https://user-images.githubusercontent.com/1241899/31995123-77555b02-b983-11e7-8b42-b9abc29adc50.JPG)

**Comment by Toelk-A** [comment]
Dokument wurde auf Richtigkeit überprüft. Folgende Mängel bitte beheben:

1) Nr. 3 im Dokument -> Der Barcode des SEC fehlt. Diesen unbedingt mit abbilden (dieser ist ja bereits in den Etiketten "SEC" programmiert.

![image](https://user-images.githubusercontent.com/22314271/32050400-f673dcb0-ba50-11e7-92af-e131f42f1e81.png)


2) Abschnitt "Implantationsdaten" - transplantierende Einrichtung - hier bitte nur die Klinik ohne Abkürzungen einfügen:

![image](https://user-images.githubusercontent.com/22314271/32050443-22c4dcc4-ba51-11e7-94c7-b9c6338cd94d.png)

**Comment by chrbusch** [comment]
1) Barcode ist integriert, bitte Lesbarkeit testen
2.) haben wir denn in  diesem Fall ein Feld, in dem die Klinik ohne Abkürzungen steht? Die Abkzg. gehört m.E. nicht in das Firmenfeld, wurde dort aber mit eingetragen!
3) Mit Dr. N. ist besprochen, dass wir das nicht grafisch nachbauen, sondern inhaltlich. All die Rahmen abzubilden würde den Aufwand erheblich erhöhen - und entsprich tja auch keinem modernen Design, oder?
4: möchte ich machen, wenn alles andere so bleiben kann

**Comment by Toelk-A** [comment]
zu 1)
Wie bereits oben beschrieben soll der SEC so abgebildet werden wie Sie ihn bereits in den Etiketten programmiert haben:

![image](https://user-images.githubusercontent.com/22314271/32054787-e57a7310-ba5f-11e7-884b-e59a1b47f81d.png)

zu 2) in Ordnung diese Info hatte ich nicht

zu 4) okay

**Comment by chrbusch** [comment]
Wenn wir Barcode und text untereinander stellen, kostet das viel Platz in der Vertikalen; kann nicht jeweils der Text rechts neben dem Barcode stehen?

**Comment by chrbusch** [comment]
Bitte jetzt noch einmal prüfen.

**Comment by Toelk-A** [comment]
Der Barcode muss wie oben beschrieben abgebildet werden, da EU Richtlinie.

**Comment by chrbusch** [comment]
OK, bitte erneut testen

![bildschirmfoto 2017-10-28 um 10 02 13](https://user-images.githubusercontent.com/1241899/32132618-19fc3f16-bbc7-11e7-8caa-bb2c8bfd217d.JPG)

**Comment by Toelk-A** [comment]
Ich habe den Begleitschein unserem QM vorgelegt. Es müsste noch unten die Formularnummer nachgetragen werden. Könnten Sie mir noch einmal kurz beschrieben wie ich zu dieser Eingabemaske komme?

**Comment by chrbusch** [comment]
HM/Supervisor/Basisdaten bearbeiten
dort "BasisDokumente" auswählen

**Comment by Toelk-A** [comment]
Bitte noch die roten "Änderungen" nacharbeiten Danke
[Transplantationsbegleitschein _ rote Änderungen einarbeiten.pdf](https://github.com/chrbusch/GTM-V/files/1441262/Transplantationsbegleitschein._.rote.Anderungen.einarbeiten.pdf)

**Comment by chrbusch** [comment]
Erledigt, bitte erneut testen

**Comment by Toelk-A** [comment]
![image](https://user-images.githubusercontent.com/22314271/32429661-e57c1692-c2cb-11e7-9415-711611478cbe.png)


Rechtschreibung - lamelläre

**Comment by chrbusch** [comment]
Erl.

**Comment by Toelk-A** [comment]
Bitte Änderungswünsche einarbeiten, Formularnummer mache ich selbst

[Transplantationsbegleitschein  rote Markierungen bearbeiten.pdf](https://github.com/chrbusch/GTM-V/files/1445603/Transplantationsbegleitschein.rote.Markierungen.bearbeiten.pdf)

**Comment by Toelk-A** [comment]
zu:

"HM/Supervisor/Basisdaten bearbeiten
Dort "BasisDokumente" auswählen; Button "Freie Suche", im fetten ID-Feld die 25 suchen"

Ich kann die Dokumentennummer nicht hinterlegen, da ich keinen "Freie Suche" Button haben. Und in welche Spalte muss die Dokumentennummer hinterlegt werden? Irgendwie hatte ich die Tabelle anders in Erinnerung.

![image](https://user-images.githubusercontent.com/22314271/32433699-2c5b80ce-c2dc-11e7-8005-c4b4888fef3a.png)

**Comment by chrbusch** [comment]
Oben im Scriptmenü steht "Freie Suche " auf ALLEN Layouts zur Verfügung - klappt auch mit Strg-7

![bildschirmfoto 2017-11-06 um 10 31 57](https://user-images.githubusercontent.com/1241899/32434223-bcaec77a-c2dd-11e7-8028-ecdc28e4521b.JPG)

**Comment by chrbusch** [comment]
>"Bitte Änderungswünsche einarbeiten, Formularnummer mache ich selbst"

Die Abstände zwischen den Ankreuzoptionen kann ich nicht verändern.
Linie hinter "Andere" ist da.
Formularnummer steht nun zunächst fest unten; die Einbindung in unsere Dokument-Automatismen schaffe ich nämlich nicht vor dem Urlaub; mehr dazu morgen am Telefon

**Comment by chrbusch** [comment]
Tel mit NIF am 180118:
Relevant sind z.Z.
3.4.3.13.3.F.Freigabeprotokoll.OG-Tx.Kornea-04-03.08.17K.pdf
3.4.3.13.4.F.Freigabeprotokoll.OG-Tx.Patch-04-03.08.17K.pdf
3.4.3.15.1.F.Prufprot.Spezifikation.Endprodukt.Kornea-00-16.07.17K.pdf
3.4.3.16.1.F.Prufprot.Spezifikation.Endprodukt.Patch-00-16.07.17K.pdf
Dokument.Nr.1.-.Transplantationsbegleitschein.OG-Transplantate.modified.for.CBu.docx
Dokument.Nr.2.-.Uebergabeprotokoll.fur.OG-Transplantate.modified.for.CBu.docx

**Comment by Toelk-A** [comment]
zu jedem Transplantatationsbegleitscheindokument gehört neben der automatisch ausgefüllten Seite noch immer eine "Blankoseite".

![image](https://user-images.githubusercontent.com/22314271/36101714-6b9a875a-100a-11e8-864f-5e5f6532a12a.png)

Auf dieser Blankoseite soll nur der Abschnitt "Transplantat" mit Daten gefüllt sein, die übrigen Abschnitte (Empfängerdaten, Implantationsdaten, Nachsorge) sollen ohne "Daten" gedruckt werden.

**Comment by Toelk-A** [comment]
Bitte Maße des Transplantationsbegleitscheines prüfen. Der Anfang der 2. Seite rutscht auf den unteren Teil der 1. Seite (roter Kringel)

![image](https://user-images.githubusercontent.com/22314271/36426457-5259bcb6-164a-11e8-9685-b11da45bf556.png)

**Comment by chrbusch** [comment]
Ist jetzt zum. auf Apple OK, bitte erneut testen
