### ISSUE TITLE
Prozessschritt Transportbegleitschein

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#28]
-   Art der Spende – nicht anklickbar
-   Kühlung des Leichnams -> „ja“ „Nein“ nicht „1“ „0“
-   „Ischämiezeit“ – Formel Spendermeldung
-   Kühlungsart – bitte Mehrfachauswahl
-   ID Temperaturlogger -> „ja“ „Nein“ nicht „1“ „0“
-   Feld Gewebebank- Adressen hinterlegen

**Comment by chrbusch** [comment]
„Ischämiezeit“ – Formel Spendermeldung
 Was meinen Sie damit?

"Gewebebank- Adressen hinterlegen"
Bitte legen Sie die gewebeproz. Adressen an und klicken Sie als Funktion (u.a.) "Gewebeproz. Einrichtg," an, dann erscheinen diese Adressen in der Auswahl

**Comment by Toelk-A** [comment]
Der Transportbegleitschein wurde von unserem QM folgendermaßen angepasst:

![image](https://cloud.githubusercontent.com/assets/22314271/19768618/9228f374-9c58-11e6-94fd-b3ed62dedc98.png)

Art der Spende: Herzkreislauftoter ODER Organspender ODER Lebendspender (automatischer Eintrag aus Spendermeldung)

Beginn der Ischämiezeit (Datum / Uhrzeit) -> entspricht beim Herzkreislauftoten Todesdatum und Todeszeit (aus Spendermeldung)

Beginn der Ischämiezeit (Datum / Uhrzeit) entspricht bei Organspender und Lebendspender die "cross clamp time" (wird später noch in Spendermeldung nachgetragen - finetuning)

**Comment by chrbusch** [comment]
"Art der Spende: Herzkreislauftoter ODER Organspender ODER Lebendspender (automatischer Eintrag aus Spendermeldung)"

Hier brauche ich eine genaue Regel.
Ich vermute:
Ist in SpdMldg "Lebendspende="Ja", so ist A"Art der Spende" = "Lebendspender"
Ist in SpdMldg "Lebendspende="Nein", so ist A"Art der Spende" = "HK-toter Spender"
Aber ist ein Organspender kein Lebendspender? Wie erfolgt diese Unterscheidung?

**Comment by Toelk-A** [comment]
Hier brauche ich eine genaue Regel.
Ich vermute:
1) Ist in SpdMldg "Lebendspende="Ja", so ist A"Art der Spende" = "Lebendspender"
2) Ist in SpdMldg "Lebendspende="Nein", so ist A"Art der Spende" = "HK-toter Spender"
3) Aber ist ein Organspender kein Lebendspender? Wie erfolgt diese Unterscheidung?


Der Korrektheit halber müsste in der Spendermeldung ebenfalls zwischen HK-toter Spender, Organspender und Lebendspender unterschiedenen werden.

HK-toter Spender: Keine Herzkreislaufaktivität UND keine Hirnaktivität (Hirntod)
Organspender: keine Hirnaktivität (Hirntod) ABER Herz-Kreislaufaktivität
Lebendspender: Hirnaktivität UND Herz-Kreislaufaktivität (z.B. Amnion- oder Femurkopfspende)

zu 1) ja
zu 2) ja
zu 3) hier benötigen wir die zusätzliche Angabe Organspender

**Comment by chrbusch** [comment]
"Der Korrektheit halber müsste in der Spendermeldung ebenfalls zwischen HK-toter Spender, Organspender und Lebendspender unterschiedenen werden."

So haben wir es jetzt gemacht, ist viel sauberer; danke für den Tipp!

![bildschirmfoto 2016-11-01 um 20 22 17](https://cloud.githubusercontent.com/assets/1241899/19903967/e81c8112-a070-11e6-8364-913f4f888d83.JPG)

**Comment by Toelk-A** [comment]
Hierzu wird sich Dr. Nitschke in den kommenden Tagen melden
