### ISSUE TITLE
GBMV/Dokument 10 Übergabeprotokoll

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#280]
1) Für das Übergabeprotokoll müssen zunächst noch folgende Felder in Transplantatdetails" programmiert werden:

1A) Abschnitt Herstellung bitte Eingabefeld Uhrzeit für "Lagerung in Transportmedium" hinzufügen.
![image](https://user-images.githubusercontent.com/22314271/31769617-a9ba877e-b4d4-11e7-9122-748aad773800.png)

1B) Abschnitt "Befunde aller Art" Endothel -> Endothelzelldichte -> bitten ebenfalls Uhrzeit hinzufügen.

![image](https://user-images.githubusercontent.com/22314271/31769699-0192d604-b4d5-11e7-9de1-1eb088b045d3.png)

2) Bitte Dokument erstellen

[Dokument Nr 2 - Uebergabeprotokoll für OG-Transplantate modified for CBu.docx](https://github.com/chrbusch/GTM-V/files/1398195/Dokument.Nr.2.-.Uebergabeprotokoll.fur.OG-Transplantate.modified.for.CBu.docx)

**Comment by chrbusch** [comment]
1A) und 1B) sind erl.

**Comment by Toelk-A** [comment]
Was ist mit 1C?

**Comment by chrbusch** [comment]
1C ist nun in Arbeit...


![bildschirmfoto 2017-11-04 um 10 38 19](https://user-images.githubusercontent.com/1241899/32404234-4b36ef1a-c14c-11e7-9fd4-c2897b5c7925.JPG)

**Comment by chrbusch** [comment]
"4 = GewebeAnforderung Details – Reiter Basisdaten – Bestelldaten – Besteller (transplantierende Einrichtung abbilden, Lieferadresse und Besteller als anfordernder Arzt)"

Das ist mir nicht ganz klar; bitte an einem konkreten Bsp. erläutern, etwa bei der Gew.Anfordg. mit ID=449, wo alle Adressen unterschiedlich sind.

**Comment by chrbusch** [comment]
Nun sind praktisch alle Felder programmiert und platziert; Details können wir am Montag tel. klären.

![bildschirmfoto 2017-11-05 um 10 51 05](https://user-images.githubusercontent.com/1241899/32413684-3e461ef4-c217-11e7-9aa9-995459521269.JPG)

**Comment by chrbusch** [comment]
Welcher dieser Informationen gehören wohin auf dem Begleitprotokoll?

![bildschirmfoto 2017-11-06 um 08 56 58](https://user-images.githubusercontent.com/1241899/32430648-776a223e-c2d0-11e7-81e8-c8c377066e32.JPG)

**Comment by Toelk-A** [comment]
Siehe Markierungen:
1) Adresse 
2) Lieferadresse
3) anfordernder Arzt

![image](https://user-images.githubusercontent.com/22314271/32436074-2ad2cdb4-c2e3-11e7-9765-fff7c9f08c1c.png)

**Comment by chrbusch** [comment]
Sind also Adresse und Lieferadresse TEILE einer Adresse ?

**Comment by chrbusch** [comment]
Wäre das also so korrekt?

![bildschirmfoto 2017-11-07 um 11 05 16](https://user-images.githubusercontent.com/1241899/32488029-94fb4db0-c3ab-11e7-85cb-c4ded9a3cb01.JPG)

**Comment by Toelk-A** [comment]
Bitte die Korrekturen einarbeiten
[Übergabeprotokoll_Korrekturen.pdf](https://github.com/chrbusch/GTM-V/files/1739651/Ubergabeprotokoll_Korrekturen.pdf)

**Comment by chrbusch** [comment]
Ist jetzt m.E. alles umgesetzt

**Comment by Toelk-A** [comment]
Es wurde nicht vollständig korrigiert. Die Dokumentennummer fehlt jetzt. Diese bitte wieder einfügen OHNE Berechnung von Arbeitszeit. 

Danke

[Erneut korrigieren OHNE Berechnung von Arbeitszeit.pdf](https://github.com/chrbusch/GTM-V/files/1743173/Erneut.korrigieren.OHNE.Berechnung.von.Arbeitszeit.pdf)

**Comment by chrbusch** [comment]
Mir scheint, dass dies an unvollständigen Daten bei dem verwendeten Testspender liegt.
Bitte testen zB mit Spender 3622
