### ISSUE TITLE
Monatsplan Rufbereitschaft weitere Spalte für Studentische Hilfskräfte einfügen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#282]
Wie telefonisch besprochen benötigen wir im Monatsplan Rufbereitschaft eine weitere Spalte "RBD-Z" (Rufbereitschaft Zusatzdienst -> gelbe Markierung siehe unten). Hier würden wir manuell die RBD´s der Studenten via Ornella einspeisen.

Von Ihrer Seite aus muss also nur die o.g. Spalte eingefügt werden. In dieser Spalte dürfen (im Moment) nur Mitarbeiter mit dem Status "Team Koordinator und geringfügig beschäftigt" eingefügt werden.

![image](https://user-images.githubusercontent.com/22314271/31812315-d8407c1c-b582-11e7-9c5d-475b7c0eb2fe.png)

**Comment by chrbusch** [comment]
Sie können nun einen Mitarbeiter manuell auswählen für den student. RBD
![bildschirmfoto 2017-10-20 um 12 52 26](https://user-images.githubusercontent.com/1241899/31817796-be9db848-b595-11e7-9cff-1fefcb04bbaa.JPG)

**Comment by Toelk-A** [comment]
funktioniert

**Comment by Toelk-A** [comment]
Könnte man auch 2 oder 3 studentische Hilfskräfte am selben Tag für RBD eintragen?

**Comment by chrbusch** [comment]
Dann muss ich das anders programmieren; in der Anforderung war ja nur vom Singular die Rede...
Ist das jetzt nötig oder irgendwann später?

**Comment by Toelk-A** [comment]
vielleicht können wir dies aufs neue Jahr verschieben, da die Studenten ebenfalls nur zu bestimmten Zeiten unter der Woche verfügbar sind...
