### ISSUE TITLE
Wunschdienst nur einmalig pro Tag möglich - sonst Warnung

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#283]
Ist bereits ein Wunschdienst durch einen Koordinator im System registriert, so soll bei Initiierung eines Wunschdienstes am selben Tag durch einen anderen Koordinator nicht möglich sein. Hier soll eine Fehlermeldung erscheinen die sagt: "An diesem Tag ist kein Wunschdienst möglich".

**Comment by chrbusch** [comment]
Erledigt.
Aber wie lange darf man das eigentlich tun?
Sicher nicht rückwirkend; soll ich prüfen, ob der RBD-Plan bereits erstellt wurde?

![bildschirmfoto 2017-10-21 um 07 24 42](https://user-images.githubusercontent.com/1241899/31848359-4da741ee-b631-11e7-86f4-e1496c348cd3.JPG)

**Comment by Toelk-A** [comment]
Wünsche dürfen nicht rückwirkend erstellt werden können. Nachdem ein Dienstplan erstellt wurde, können "Wünsche" nur noch durch die Tauschfunktion in Ornella durchgeführt werden.

**Comment by chrbusch** [comment]
Erledigt

![bildschirmfoto 2017-10-23 um 08 47 04](https://user-images.githubusercontent.com/1241899/31875510-c550d82e-b7ce-11e7-8f73-9c5e2495c4f1.JPG)
