### ISSUE TITLE
GBMV/ Autom. Befundeintragung nach Anlegen eines OG-Transplantates

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#284]
Nach Eingabe des Herstellungsdatum und der Herstellungszeit in die Maske Transplantatdetails - Abschnitt "Herstellung" sollen die folgenden Befunde automatisch angelegt werden, die eingegeben Datenfelder (Datum) aber veränderbar bleiben:

Abschnitt Befunde aller Art

1) Kornea - optisch freie Zone - Datum Befund = Herstelldatum - Datum Eingang = Herstelldatum - E endgültig
2) Endothel - Morphologie - Datum Befund = Herstelldatum - Datum Eingang = Herstelldatum - E endgültig
3) Endothel - Endothelzelldichte - Datum Befund = Herstelldatum - Datum Eingang = Herstelldatum - E endgültig
4) Kornea - Spaltlampenbefund - Datum Befund = Herstelldatum - Datum Eingang = Herstelldatum - V vorläufig
5) KMI - Hefen - Datum Befund = Feld bleibt leer - Datum Eingang = Herstellungsdatum + 4d - V vorläufig
6) KMI - anaerobe Erreger - Datum Befund = Feld bleibt leer - Datum Eingang = Herstellungsdatum + 4d - V vorläufig
7) KMI - Bakterien - Datum Befund = Feld bleibt leer - Datum Eingang = Herstellungsdatum + 4d - V vorläufig
8) Bindehautabstrich - Hefen - Datum Befund = Feld bleibt leer - Datum Eingang = Herstellungsdatum - V vorläufig
9) Bindehautabstrich - anaerobe Erreger - Datum Befund = Feld bleibt leer - Datum Eingang = Herstellungsdatum - V vorläufig
10) Bindehautabstrich - Bakterien - Datum Befund = Feld bleibt leer - Datum Eingang = Herstellungsdatum - V vorläufig

![image](https://user-images.githubusercontent.com/22314271/32050957-1f620302-ba53-11e7-90a7-89289fba2eea.png)

Nachdem im Abschnitt Herstellung Feld "Lagr. Transp. Medium" eine datum einegetragen wurde sollen die zweiten KMI Befunde automatisch angelegt werden.

![image](https://user-images.githubusercontent.com/22314271/32051057-7402542a-ba53-11e7-9867-4e766c959182.png)

11)  KMI - Hefen - Datum Befund = Feld bleibt leer - Datum Eingang = Datum Lagerung in Transportmedium (Abschnitt Herstellung) - V vorläufig
12)  KMI - anaerobe Erreger - Datum Befund = Feld bleibt leer - Datum Eingang = Datum Lagerung in Transportmedium (Abschnitt Herstellung) - V vorläufig
13)  KMI - Bakterien - Datum Befund = Feld bleibt leer - Datum Eingang = Datum Lagerung in Transportmedium (Abschnitt Herstellung) - V vorläufig

**Comment by chrbusch** [comment]
Bei dem gezeigten TestTransplantat wurden die Befunde autom. angelegt, bitte prüfen

![bildschirmfoto 2017-10-27 um 09 18 50](https://user-images.githubusercontent.com/1241899/32092261-f1b838c2-baf7-11e7-89fb-d1bda6e5ea96.JPG)

**Comment by chrbusch** [comment]
Bitte den neuen Button "Standardbefunde anlegen" testen.
Er wird erst sichtbar, wenn ein Wert in d_Datum_Herstellung vorhanden ist

![bildschirmfoto 2017-10-27 um 09 24 40](https://user-images.githubusercontent.com/1241899/32092414-adbd0016-baf8-11e7-9475-577af1951b67.JPG)

**Comment by Toelk-A** [comment]
funktioniert
