### ISSUE TITLE
GBMV/ Buttons aus Spenderdetails in Transplantatdetails verschieben

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#285]
Bitte die Buttons "Etiketten" und Tr.Begl.Schein OG aus den Spenderdetails - Reiter Gew. Pr. Tr. 

![image](https://user-images.githubusercontent.com/22314271/32052313-2aefe518-ba58-11e7-964a-7cbb667cc956.png)

in den grünen Bereich der Transplantatdetails verschieben:

![image](https://user-images.githubusercontent.com/22314271/32052353-474bf13e-ba58-11e7-8110-4b1ff0bb7b36.png)

**Comment by chrbusch** [comment]
Beide Buttons sind nun links in der Buttonleiste (wo sie hingehören)
