### ISSUE TITLE
GBMV/ Artikel ID 38 Bitte x fach anwendbar "100" hinzufügen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#286]
Artikel ID 38 

Bitte in dem Anklickfeld "X-fach anwendbar" eine "100" hinzufügen.

![image](https://user-images.githubusercontent.com/22314271/32053161-c208891c-ba5a-11e7-9a38-085ec3ddb213.png)

**Comment by chrbusch** [comment]
Erl.

**Comment by Toelk-A** [comment]
funktioniert einwandfrei
