### ISSUE TITLE
GBMV/ Anlegen Ja/Nein - Button für 2 Artikel in Reiter Herstellung

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#287]
Transplantatdetails - Reiter Herstellung - Abschnitt Zugeordnete Zusatzpositionen

Zur Herstellung mancher Hornhäute müssen die folgenden Lösungen // Artikel verwendet werden: 
-> Artikel ID 238 Trypanblau
-> Artikel ID 35 Aqua AD

Da ihre Verwendung eher sporadisch vorkommt, können sie nicht in die Warenkörbe gepackt werden. Außerdem ist die verwendete Menge dieser Lösungen nicht in Ornella abbildbar, da es sich um unterschiedliche µl Angaben handelt. Somit können die o.g. Lösungen auch nicht als Zusatzposition eingescannt werden.

1) Unsere Vorstellung ist nun, dass je ein "ja/nein" Button ähnlich dem "Vor-OP SpdAuge" programmiert wird.

![image](https://user-images.githubusercontent.com/22314271/32054451-b9773bbe-ba5e-11e7-8c41-f1dc541738dc.png)

Button 1 Trypanblau "ja/nein"
Button 2 Aqua injectabilia "ja/nein"

2) Diese Buttons sollen im Reiter Reiter Herstellung - Abschnitt Zugeordnete Zusatzpositionen angebracht werden.

![image](https://user-images.githubusercontent.com/22314271/32054079-8b39ab5c-ba5d-11e7-8f95-fec3dd306304.png)

3) Sind die Buttons auf "ja" so soll der Artikel ebenfalls in den Zusatzpositionen wie alle anderen Zusatzpositionen abgebildet werden. Dementsprechend werden diese also auch mit LOT, MHD etc. im Herstellprotokoll aufgeführt.

**Comment by chrbusch** [comment]
Frage: Soll von diesen Artikeln auch eine bestimmte Charge erfasst werden?
Wie soll die Menge erfasst werden - manuell? gar nicht?
Und wieso kann man das nicht denn nicht per Scanner auf dem normalen Weg erreichen? Hard-codierte Ausnahme machen ein Programm immer fehleranfällig und sollten eine Ausnahme bleiben.

**Comment by chrbusch** [comment]
Bitte auf der Artikelmaske alle Artikel in dem neuen Feld ankreuzen, deren Verbrauchsmengen nicht gebucht werden sollen

![bildschirmfoto 2017-10-27 um 08 00 00](https://user-images.githubusercontent.com/1241899/32089894-ea95a198-baec-11e7-8a1a-acc96bfeea49.JPG)

**Comment by chrbusch** [comment]
Ich denke, das "funzt" jetzt, bitte testen

![bildschirmfoto 2017-10-27 um 08 30 47](https://user-images.githubusercontent.com/1241899/32090747-4e394d68-baf1-11e7-82e0-7e27cf1b5265.JPG)

**Comment by Toelk-A** [comment]
funktioniert ebenfalls einwandfrei :-)
