### ISSUE TITLE
GBMV/ Bitte Präparat "arteria pulmonales mit Bifurkation(patch)" löschen ABER als Transplantat erhalten!!!

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#288]
Bitte in den Präparaten die "arteria pulmonales mit Bifurkation(patch)" löschen. Dies ist kein Präparat sondern ein Transplantat. 

![image](https://user-images.githubusercontent.com/22314271/32097989-895d54ce-bb0b-11e7-8f6a-2342308a144c.png)

**Comment by chrbusch** [comment]
Ist gelöscht
