### ISSUE TITLE
Personalplanung - neuer Job "Urlaub MA Wunsch"

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#289]
1) Bitte neuen Sonderjob "Urlaub MA Wunsch" erstellen.

2) Sonderjob "Urlaub bez." (Nr 1) darf nicht mehr als Auswahl für die Koordinatoren in der Jobliste erscheinen, sondern nur für die Geschäftsführung/Supervisor sichtbar sein.

Hintergrund ist, dass die Geschäftsführung den Urlaub über die Änderung des Jobs von "Urlaub MA Wunsch" in "Urlaub bez." umwandeln kann und somit eine Prüfung und Freigabe des Urlaubs durch die Geschäftsführung stattfand.

**Comment by chrbusch** [comment]
Neuer Job ist erstellt, und Job 1 = "Url. bez." nur noch für Supervisor sichtbar.
Bitte als SV und "Normaler" testen

**Comment by Toelk-A** [comment]
1) Job funktioniert. 

Bitte auch hier rechts unten am "Wunschurlaubstag" eine rotes Viereck als Label einfügen, da der Text an sich zwischen den ganzen anderen Texten (verfügbar etc.) unter geht.

**Comment by chrbusch** [comment]
Erledigt.
