### ISSUE TITLE
Prozessschritt Körperliche Untersuchung

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#29]
-	Grafik: „Entfernen“ oder „Rückgängig“ Button einfügen
Mehrfachnennung bei anatomischen Angaben

**Comment by Nitschke-FP** [comment]
Es können Narben und Tattoos vorhanden sein oder ich muss eine "Narbe" wieder entfernen

**Comment by chrbusch** [comment]
Wenn man einen gefärbten Punkt recht exakt erneut anklickt, wird er wieder entfernt!

**Comment by chrbusch** [comment]
Was meinen Sie mit "Mehrfachnennung bei anatomischen Angaben"?

**Comment by Nitschke-FP** [comment]
Es können Narben und Tattops  oder weitere Besonderheiten aus der Liste vorhanden sein

**Comment by Nitschke-FP** [comment]
Wenn man einen gefärbten Punkt recht exakt erneut anklickt, wird er wieder entfernt! - funktioniert nur teilweise. Wenn ich an einer Stelle des Körpers eine "Wunde" markieren will wird das "f" ca. 2 cm höher gesetzt

**Comment by chrbusch** [comment]
Bitte anrufen, damit wir das per TeamViewer ansehen können.
Auf dem Mac bei mir passt es auf den Millimeter genau!

**Comment by chrbusch** [comment]
"Es können Narben und Tattops oder weitere Besonderheiten aus der Liste vorhanden sein"

Aber diese können Sie doch nacheinander anklicken und zwischendurch den Buchstaben wechseln!

**Comment by Nitschke-FP** [comment]
Test

**Comment by chrbusch** [comment]
Now try the rubber!

![bildschirmfoto 2016-10-26 um 10 36 07](https://cloud.githubusercontent.com/assets/1241899/19718965/0ee805f4-9b68-11e6-92c5-b04418c04562.JPG)

**Comment by Nitschke-FP** [comment]
Perfekt
