### ISSUE TITLE
Personalplanung - Erstellen Teamkalender, der alle Mitarbeiter eines Mandanten abbildet

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#290]
Bitte einen Teamkalender erstellen, der alle Mitarbeiter eines Mandanten abbildet:

GTMV = Koordinatoren, studentische Hilfskräfte, Ärzte und Finanzbuchhaltung

**Comment by chrbusch** [comment]
Erledigt, bitte testen

![bildschirmfoto 2017-11-05 um 12 52 20](https://user-images.githubusercontent.com/1241899/32414509-04384ec8-c229-11e7-9c93-6096e1e14b38.JPG)
![bildschirmfoto 2017-11-05 um 12 52 34](https://user-images.githubusercontent.com/1241899/32414511-06712912-c229-11e7-861a-417f77c31acf.JPG)

**Comment by Toelk-A** [comment]
die von Ihnen abgebildeten Fenster öffnen sich bei mir nicht wenn ich: Personalplanung -> Koordinatoren -> Teamkalender ansteuere

**Comment by chrbusch** [comment]
Sie klicken vermutlich auf den TK-Button im Bereich "TEAMS des Standortes" - dann öffnet sich der TK für dieses Team.
Links ist ein neuer Button "TK allgemein"; bitte dies testen (hatte ich vergessen zu erläutern)

![bildschirmfoto 2017-11-06 um 08 21 09](https://user-images.githubusercontent.com/1241899/32429600-a367a1fe-c2cb-11e7-8362-1a61aa6fea21.JPG)

**Comment by chrbusch** [comment]
PS: Erfordert u.U. Neustart von Filemaker

**Comment by Toelk-A** [comment]
Können wir diesen bitte bei "Teams des Standortes" einfügen, sodass jeder drauf zugreifen kann?

![image](https://user-images.githubusercontent.com/22314271/32429965-49efa0a2-c2cd-11e7-88fb-0e45259fad9f.png)

**Comment by chrbusch** [comment]
Das passt von der Programm-Logik her gar nicht.
Ich habe jetzt einen entspr. Button unter dier Liste der Standorte platziert.
