### ISSUE TITLE
Erweiterung Rechte Personalplanung - MA Schmalfuß-Gross

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#291]
Unsere Mitarbeiterin "Finanzbuchhaltung" Frau Schmalfuß-Gross soll Zugriff auf die Teamkalender (um Urlaub oder AZK zu prüfen/ genehmigen) sowie Mitarbeiterdetails bekommen. Sie soll allerdings keine SUPERVISOR Recht erhalten. 

Unsere Idee ist in den Mitarbeiter/Ressource Details - rechts unten "Arbeitsbereiche" ein weiteres Ankreuzfeld "Personaleinsatzplanung" einzufügen. Wenn dieses Feld angekreuzt ist, sollen die oben beschriebenen Eigenschaften erfüllt sein.

![image](https://user-images.githubusercontent.com/22314271/32379185-1ae2a6f0-c0ad-11e7-83d9-ebf570365efb.png)

**Comment by chrbusch** [comment]
Programm ist im Prinzip erledigt.
Das neue Recht wird in ORNELLA angekreuzt, nicht im Perso-Modul.
Bitte prüfen, ob Frau G. jetzt alle erwünschten Funktionen ausführen kann.

![bildschirmfoto 2017-11-05 um 12 39 52](https://user-images.githubusercontent.com/1241899/32414422-71425584-c226-11e7-88fd-bd39a7ee861c.JPG)

**Comment by Toelk-A** [comment]
erledigt
