### ISSUE TITLE
GBMV/ Datenexport Transplantatliste einfügen der Spenderkennummer

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#292]
Allokation -> Transplantatliste

Für unsere statistische Auswertung möchten wir beim Datenexport zusätzlich die zugehörige Spenderkennnummer des jeweiligenTransplantates abgebildet haben. Die Spenderkennnummer soll nur beim Datenexport abgebildet werden nicht in der Transplantatliste selbst.

**Comment by chrbusch** [comment]
Welcher Export ist hier gemeint? Bite genau den Button benennen, dessen Funktion geändert werden soll.

**Comment by Toelk-A** [comment]
Hier gibt es keinen Button.

Allokation -> Transplantatliste -> Datei -> Daten exportieren als Excel

**Comment by chrbusch** [comment]
Ja, aber das habe ich ja nicht programmiert; dies ist eine native FileMaker-Funktion.
Alle gewünschten Felder können **und müssen** Sie selbst einfügen.
Ich kann aber stattdessen einen Button programmieren, der dies genau so tut, wie Sie wünschen.
Das ist schnell gemacht; aber ich müsste aber wissen, welche Felder exportiert werden sollen. Dafür am besten eine XLS-Datei im gewünschten Format zu mir senden.

**Comment by Toelk-A** [comment]
Allokation -> Transplantatliste -> Datei -> Daten exportieren als Excel

hier erhält man die folgende Exceltabelle:

[Datenexport Allokationsliste.xlsx](https://github.com/chrbusch/GTM-V/files/1453572/Datenexport.Allokationsliste.xlsx)

Ganz links, die gelb markierte Spalte, soll durch Sie wie oben beschrieben eingefügt werden.

**Comment by chrbusch** [comment]
Auf der Liste der Transplantate gibt es oben bereits einen grünen Button "Excel-Export"; wird dieser Export auch benötigt, oder soll er **ersetzt** werden durch die obige Export-Definition?

**Comment by chrbusch** [comment]
Bei der Umsetzung hab eich gesehen, dass die obige Exceldatei einige vollkommen unsinnige Felder enthält, zB den Namen des Layouts.
Wir müssen besprechen, welche Felder Sie tatsächlich brauchen!
