### ISSUE TITLE
ÜS_Bericht AZK wieder falsch im PDF abgebildet

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#293]
MA Petrowski Monat Oktober 2017

Nach Klicken des Buttons "Monatssummen aktualisieren" bekommen wir folgendes Ergebnis:

![image](https://user-images.githubusercontent.com/22314271/32432251-1a53d16a-c2d7-11e7-8eb8-c32f7d445149.png)

-> Button Überstundenbericht:

IM PDF wird allerdings ein AZK von 20,62 Stunden abgebildet

![image](https://user-images.githubusercontent.com/22314271/32432287-41511e8a-c2d7-11e7-8fa2-5052dcd1a9b5.png)

**Comment by chrbusch** [comment]
Ich lasse die Berechnung des AZK jetzt anders verlaufen, bitte erneut testen.
Und zwar auch für einen MA, der am 31.10. gearbeitet hat!
