### ISSUE TITLE
Digitale Unterschriften in Ornella

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#296]
1) Die digitalen Unterschriften sind in Ornella hochgeladen.

2) Mit Hinblick auf weitere Standorte sollen generell alle Dokumente im Reiter Prozessschritte durch das ärztliche Personal unterschrieben werden und somit als Spenderakte freigegeben werden können

3) Insbesondere Entnahmeberichte (OG, MSG und KVG) sollen schnellstmöglich - direkt nach der Entnahme digital unterschrieben werden können. Hierfür ist sowohl eine Unterschrift des ärztlichen Personals als auch der Koordinatoren / Entnehmers notwendig

4) Es darf nur die Unterschrift in Ornella abgebildet werden, die dem eingegeben Kürzel/Namen zugehörig ist. Zum Setzen der Unterschrift soll das persönliche Passwort abgefragt werden.

![image](https://user-images.githubusercontent.com/22314271/32499212-40b87ee0-c3d2-11e7-82c6-01fa6f8de34f.png)

**Comment by Toelk-A** [comment]
Bitte wie abgesprochen die o.g. Punkten programmieren. Eine digitale Unterschrift darf nur mittels Passworteingabe des zugehörigen Users gesetzt werden können.

**Comment by chrbusch** [comment]
Schlage vor, dass wir das anhand des Entn.Berichtes fertig stellen und dann, wenn alle zufrieden sind, durch Duplikation übertragen auf weitere Dokumente.
**Bitte hierzu möglichst bald anrufen!**

**Comment by chrbusch** [comment]
Soll zB bei Auswahl der AAP die US immer geholt werden - soll also Auswahl AAP nur noch erlaubt sein, wenn dieser das richtige Passwort eingibt?
Dies würde bedeuten, dass kein anderer User einen AAP eintragen kann - also Tölk kann nicht Nitschke auswählen.
Vllt. ist das auch genau so gewollt?

**Comment by chrbusch** [comment]
Bitte bei einem EntnBericht (am besten Testpatient) mit den neuen Button a"US" (=Unterschrift) die 2 Felder füllen und dann den EB ausdrucken - Größe der US ausreichend?

**Comment by chrbusch** [comment]
So weit ich die Anforderungen verstanden habe, ist das nun auf dem Entnahmebericht für alle drei Unterschriftenfelder realisiert, bitte testen.

**Comment by chrbusch** [comment]
Bitte hier die Dokumente auflisten, bei denen auch eine dig. US gesetzt werden soll

**Comment by Toelk-A** [comment]
Die digitalen Unterschriften im OG-Entnahmebericht werden zu klein abgebildet. Können diese bitte größer abgebildet werden?

Spenderdetails 3890 -> OG Entnahmebericht -> Abschnitt Besonderheiten


![image](https://user-images.githubusercontent.com/22314271/36300932-7336c9fa-1303-11e8-857f-c08d6ecf585e.png)

**Comment by chrbusch** [comment]
Das kann ich nicht alleine; die Unterschriften sind anscheinend als extrem kleine Bilder angeliefert worden.
Sie müssen mindestens so groß geliefert werden, wie sie gedruckt werden sollen.
(Kleinrechnen ist kein Problem; beim "Größerrechnen" wird aber alles sehr pixelig)

**Comment by Toelk-A** [comment]
Die Unterschriften sind in der folgenden Größe abgespeichert worden:

![image](https://user-images.githubusercontent.com/22314271/36429724-bff082d8-1653-11e8-88b1-579a36131766.png)

**Comment by chrbusch** [comment]
Die Bilder, die in dem US-Feld beim User sind, sind nur ca. 20 Pixel breit, siehe Bild!
Und größer kann ich sie eben nicht anzeigen. Wir brauchen m.E. Bilder von mindestens 200px Breite

![bildschirmfoto 2018-02-20 um 16 55 46](https://user-images.githubusercontent.com/1241899/36434288-f9f69c46-165e-11e8-914c-7598449c5f8c.JPG)

**Comment by chrbusch** [comment]
Ich habe jetzt zwei rote Peilmarken in das Layout gesetzt: So groß sollten die US schon erscheinen nach dem Einsetzen

![bildschirmfoto 2018-02-20 um 16 57 26](https://user-images.githubusercontent.com/1241899/36434385-322fb0fc-165f-11e8-94a6-4d15ae00899d.JPG)

**Comment by Toelk-A** [comment]
Wie bereits oben beschrieben haben ALLE Unterschriften eine Pixelbreite von 532 Pixel. Es scheint eine Problem beim hochladen der Unterschrift in Ornella zu sein, da sie ja anscheinend kleiner abgebildet wird, als die JPEG Datei eigentlich ist.

1) Das erstellen der roten Linie soll uns nicht berechnet werden, da sie nicht zur Problemlösung beiträgt. Ich habe Ihnen im Comment darüber mitgeteilt welche Pixelgröße die Unterschriften haben.

2) Bitte prüfen Sie, ob die Unterschriften beim Upload in Ornella verkleinert werden. Die Größe in Ornella entspricht anscheinen nicht der Originalpixelgröße.

**Comment by chrbusch** [comment]
Bitte senden Sie mir die US-Dateien per Email.

**Comment by chrbusch** [comment]
Habe gerade einen Test gemacht: Wenn ich ein JPG auswähle, erscheint es genau in der tatsächlichen Dateigröße in der User-Maske

**Comment by Toelk-A** [comment]
Unterschriften sind gemailt.

**Comment by chrbusch** [comment]
Es sind nun auch die 3 neuen Unterschriften integriert. Sie sind übrigens stark pixelig! Und daher vermute ich, dass die tatsächliche AUFLÖSUNG eben wie von FileMaker "vermutet" bei ca. 50 Pixel liegt. Die roten Peilmarken zeigen dies auch an, wenn künftig Bilddateien importiert werden: Bei tats. hinreichend großen JPG wird das Bildfeld entsprechend gefüllt, siehe mein Bild.
Probieren Sie dies bitte einmal mit der Ihnen gerade gemailten Unterschrift von P. Picasso, die Sie zB meinem Datensatz zuordnen können.


![bildschirmfoto 2018-02-21 um 15 57 35](https://user-images.githubusercontent.com/1241899/36486895-f31aed0c-171f-11e8-90ab-d6c7dc0e8d75.JPG)

**Comment by Toelk-A** [comment]
Mitarbeiter / User Details Sophie Wulf
1) Bitte die Unterschrift von Frau Sophie Wulf auf den roten Begrenzungsbereich erweitern.
![image](https://user-images.githubusercontent.com/22314271/37701432-5052b45c-2cef-11e8-823d-c34ae6b479a9.png)

2) Mitarbeiter / User Details Dietrich Schweder
Herrn Schweder haben Sie aus Versehen die Unterschrift von Frau Kroll zugeordnet.
![image](https://user-images.githubusercontent.com/22314271/37701503-88091580-2cef-11e8-9bed-0b6102656818.png)
 2A) Muss ich Herrn Schweders Unterschrift noch einmal hochladen, damit Sie sie vergrößern können?
2B) Können Sie einfach Herrn Schweders Unterschrift in vergrößerter Form abbilden?

**Comment by chrbusch** [comment]
Sie können doch selbst Unterschriften auswählen auf der Usermaske!
Ich kann diese nicht vergrößern, da sie dann zu pixelig werden.Sie müssen Bilddateien erstellen, die tatsächlich so groß sind, dass sie den Bereich der roten Striche ausfüllen.
Das mir vorliegende Bild für SCD ist viel zu klein; ich habe es jetzt aber eingesetzt, denn zu klein ist besser als eine falsche Unterschrift
