### ISSUE TITLE
GBMV/ Transplantationsbegleitschein udn Übergabeprotokoll werden in den Dokumenten der Spende vom falschen Spender hinterlegt

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#297]
Spender ID 3062

![image](https://user-images.githubusercontent.com/22314271/32544620-43c2cdaa-c479-11e7-9c4f-e0ebed1f9438.png)

Transplantationsbegleitschein gehört zu einem komplett anderen Spender nämlich Spender ID 2873

Bitte umgehend dieses Problem beheben, da dies zu völlig falschen Verknüpfungen führt

**Comment by chrbusch** [comment]
Bitte jetzt gleich erneut testen, zB mit testspender

**Comment by chrbusch** [comment]
Nur zur Korrektur dieser Fehler können Sie HEUTE die SpenderID bei den Dokumenten manuell ändern, dadurch sollten diese autom. beim richtigen Spender angezeigt werden.

![bildschirmfoto 2017-11-08 um 11 49 44](https://user-images.githubusercontent.com/1241899/32545135-046aefb4-c47b-11e7-8f4f-8cd90998864d.JPG)

**Comment by Toelk-A** [comment]
Wir wissen gar nicht warum die PDFs dort auftauchen. Dies wurde nie programmiert und sollte auch nie programmiert werden.... Keiner von uns hat die PDFs dort hinterlegt bzw. geöffnet

**Comment by chrbusch** [comment]
Tritt das problem noch auf? Es entstand quasi durch die "Umgehung" der Spenderprozessschritte; wie besprochen möchte ich dieses Modul nicht kurz vor einer langen Abwesenheit umbauen.
Bitte mit Testspender ausprobieren.

**Comment by chrbusch** [comment]
Bitte Ticket schliessen, falls erledigt
