### ISSUE TITLE
GBMV/ Personalplanung Team Kalender / persönlicher Kalender // Sonderjobs Koordinatoren

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#299]
Teamkalender -> Funktion -> kUf:
bzw. persönlicher Kalender -> Spalte "Jobs"

Die Koordinatoren dürfen nur die folgenden Sonderjobs angezeigt bekommen bzw. auswählen dürfen:

AZK MA Wunsch (bereits programmiert) [10]
Urlaub MA Wunsch (bereits programmiert) [12]
n. verfügb. [5]

![image](https://user-images.githubusercontent.com/22314271/34517644-242a80f8-f07c-11e7-89cf-204792ae0eda.png)

![image](https://user-images.githubusercontent.com/22314271/34517721-80caad74-f07c-11e7-8455-f4a8142d9211.png)

Alles weiteren Sonderjobs dürfen nur durch Supervisorrechte (Personalplanungrechte eintragbar sein.

**Comment by chrbusch** [comment]
M.E. erledigt, bitte testen

**Comment by Toelk-A** [comment]
erledigt
