### ISSUE TITLE
Prozessschritt Spendermeldung

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#30]
-   ITS suche – DRK Häuser werden nicht angezeigt (Teil des Feldinhaltes muss gesucht werden)
-   neue ICD-Liste laden (wird nachgeliefert ab kommender Woche (1.11.2016))

**Comment by chrbusch** [comment]
Bitte viel genauere Informationen liefern!
Welchen Button meinen Sie - <Adresse suchen>?
Welche Adresse genau wird hier nicht gefunden, die "ITS" enthält?

**Comment by Toelk-A** [comment]
Der Button lautete "meldende Einrichtung"

DRK Krankenhäuser: Mecklenburg - Strelitz, Teterow, Grevesmühlen 

gibt man "ITS" in das Suchfeld ein werden die DRK Krankenhäuser nicht gefunden, da die ITS immer mit  der Abkürzung des Krankenhauses hinterlegt ist z.B.: MSTITS (Mecklenburg-Strelitz), TETITS (Teterow), GVMITS. Das Gleiche gilt für alle anderen Abkürzungen der DRK Krankenhäuser wie z.B. IN1, IN2, CHR1, etc,...

**Comment by Toelk-A** [comment]
Abschnitt "Personenbezogene Daten" - "Diagnosen" 
bei Eingabe >5 Diagnosen passt sich "Diagnosenfeld" auf PDF-Ausdruck nicht an 

![image](https://cloud.githubusercontent.com/assets/22314271/19728818/186e2a9a-9b95-11e6-9875-38c2d8ea3e55.png)

**Comment by Toelk-A** [comment]
Abschnitt "Wiederspruch gg. Spende" 
Im Moment ist es nur möglich ein Datum aber keine Uhrzeit des Gespräches einzutragen. Bitte zusätzliches Feld für Dokumentation der Uhrzeit einfügen.

![image](https://cloud.githubusercontent.com/assets/22314271/19767256/336ef118-9c52-11e6-9889-069c94000abc.png)

**Comment by chrbusch** [comment]
Bitte für jeden einzelnen Punkt (!) ein eigenes Issue eröffnen, die Kommunikation wird sonst zu unübersichtlich.
Nezgl. der Diagnosen: Damit es keinen unerwünschten Seitenumbruch gibt, muss ich den "Anzeigeplatz" begrenzen. Wie viele Dgn werden es denn im Echtbetrieb maximal sein? Ich maches jetzt so, das ab 5 Dgn die Zeilenumbrüche dazwischen entfallen, so passt mehr in das Feld. Bitte prüfen.

**Comment by chrbusch** [comment]
Bei "Datum/Zeit des Gespräches" kann man nun bel. Text eingeben
