### ISSUE TITLE
/GBMV Transplantate mit Status "30 Freigabe Gewebe..." sind nicht allokierbar

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#301]
Transplantat-Auswahl + Allokation -> Reiter "Passende Transplantate"

Bitte die Allokation der Transplantate mit dem Status [30] ermöglichen. Der grüne Button "allokieren" fehlt unter dem Transplantat.

![image](https://user-images.githubusercontent.com/22314271/34612100-9bf0e19c-f228-11e7-83fb-3f36b16deb09.png)

![image](https://user-images.githubusercontent.com/22314271/34612030-4636ddd8-f228-11e7-9040-f0ef4772b6ae.png)

**Comment by chrbusch** [comment]
Erledigt
