### ISSUE TITLE
OG Entnahmebericht - Präparate beidseits - linkes Präparat fehlt

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#302]
OG Entnahmebericht -> OG Präparat wählen - > Oculus ->  Welche Seiten **"beidseits"**-> es wird nur das rechte Präparat angelegt (OD) links (OS) fehlt

![image](https://user-images.githubusercontent.com/22314271/36094778-d539658e-0fef-11e8-85cb-098b34571a96.png)

**Comment by chrbusch** [comment]
Bei mir klappt das! Tritt der Fehler bei Ihnen regelmässig auf?

**Comment by Toelk-A** [comment]
immer, bei allen Kollegen

**Comment by chrbusch** [comment]
Bitte jetzt erneut testen

**Comment by Toelk-A** [comment]
funktioniert
