### ISSUE TITLE
GBMV/ Transplantatdetails _ Positiver Befund -> automatisierte Nachricht an 

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#303]
Transplantatdetails -> Befunde aller Art

Gibt es einen positiven Befund bei Bindehautabstrichen:
![image](https://user-images.githubusercontent.com/22314271/36103598-11326c50-1010-11e8-895e-09122f348fd5.png)
  
so soll Ornella automatisch eine Nachricht an die verantwortliche Personen (NIF, KNA, SCP) generieren.

**Comment by chrbusch** [comment]
Aus welchem Feld kommt hier die Info über die VP?

**Comment by chrbusch** [comment]
Zur Zeit schreibe ich immer NIF in den "Ziel-User", dies kann getestet werden.
Sobald ich weiss, aus welchem Feld ich das auslesen soll, geht es weiter

**Comment by Toelk-A** [comment]
Ziel-User (= Mailadressat?) sollen NIF, KNA, SCP sein

**Comment by chrbusch** [comment]
Also immer diese drei? OK, stelle ich ein.

**Comment by chrbusch** [comment]
..und man kann nun bei jedem parameter werte eintragen, die zu so einer WV führen.

<img width="551" alt="bildschirmfoto 2018-02-13 um 12 29 32" src="https://user-images.githubusercontent.com/1241899/36147716-928cd07a-10b9-11e8-9c62-0a0dd38f93bf.png">

**Comment by Toelk-A** [comment]
okay super, kann ich dies jetzt testen?

**Comment by chrbusch** [comment]
Jawoll!

**Comment by Toelk-A** [comment]
Transplantatdetails 1809

Dr. Andreas Knipper bekommt keine Mail. Die Übertragung scheint nicht zu funktionieren. Vielleicht können Sie zum Testen mich ebenfalls in den Mailverteiler aufnehmen.

**Comment by chrbusch** [comment]
Ich habe bisher nur INTERNE Wiedervorlagen erstellt; aber jetzt sollten auch die Emails rausgehen; bis auf weiteres auch an Sie

**Comment by Toelk-A** [comment]
Wir bekommen noch immer keine Mails bei positiven Befunden. Die Wiedervorlage funktioniert:

![image](https://user-images.githubusercontent.com/22314271/36380399-6ef967ea-1582-11e8-8e29-f7e82f8ceb63.png)

**Comment by chrbusch** [comment]
Habe noch Schreibfäler im Script gefunden, bitte erneut testen

**Comment by Toelk-A** [comment]
Automatische Mail wird jetzt generiert.

1) Bitte nehmen Sie mich aus dem Email UND Wiedervorlagen - Verteiler.

**Comment by chrbusch** [comment]
Erl.
