### ISSUE TITLE
Monatsstatistik "Spendenumsetzung pro Stationen" erstellen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#304]
Es sollen die Chefärzte der Stationen pro Krankenhaus über die Anzahl der realisierten Spenden des Vormonats informiert werden. 

1) Hierfür haben wir bereits einen Vordruck (siehe Anlage).
Als Mandanten nutzen wir GTM-V und deren Brief Vorlage (bereits in Ornella gespeichert) -> Supervisor -> Mandantendaten -> GTM-V

2) Die Statistik soll abrufbar sein im Hauptmenü - "Auswertung" - "Monatsstatistik Stationen"

[Musterschreiben Informationsbrief an Kliniken.pdf](https://github.com/chrbusch/GTM-V/files/1740382/Musterschreiben.Informationsbrief.an.Kliniken.pdf)

**Comment by chrbusch** [comment]
Ich brauche teilweise präzisere Informationen:
A) Pro Spender haben wir eine "Meldende Einrichtung"; können Sie eine klare Regel nennen, anhand derer in den Chefarzt bestimmen kann, dessen Name ausgegeben werden soll?

B) Gibt es so einen Brief pro Monat und pro Entnahmeeinrichtung?

C) Was definiert "Vormonat" - das Entnahmedatum?

D) Ist die Behauptung Absicht, GTM-V hätte eine "Gewebespende ..realisiert"?
Sie spenden doch nicht - Sie entnehmen. Vielleicht ist das aber auch nur ein mir unbekannter Sprachgebrauch.

**Comment by chrbusch** [comment]
Wir werden das mit einem durch Sie jederzeit modifizierbaren Textbaustein lösen können, den ich in Rohform schon angelegt habe.

![bildschirmfoto 2018-02-20 um 17 35 31](https://user-images.githubusercontent.com/1241899/36436445-8c5d483c-1664-11e8-8c21-f71b820eae78.JPG)

**Comment by chrbusch** [comment]
Wenn ich nicht irre, müssen wir hierüber noch mehr nachdenken. 
Sollen Präparate auch abgebildet werden, wenn es dazu keine Transplantate gibt?
Aus einem Präparat können mehrere Transplantate werden, die dann auch mehrere Empfänger haben. Wie soll dies dargestellt werden?
Ich realisiere jetzt erst einmal den simplen Fall für Gewebe vom Typ OG; anhand dieses Beispiels können wir dann weiter diskutieren

**Comment by chrbusch** [comment]
Feld8: Beim SpdTransplantat gibt es r.o. ein Feld "Grund für Verwurf", können wir dies nehmen?
Andernfalls bitte angeben, wo das neuen Feld hin soll

![bildschirmfoto 2018-02-21 um 09 03 04](https://user-images.githubusercontent.com/1241899/36469014-0d1fdc60-16e6-11e8-99f0-7a156261cfbf.JPG)

**Comment by Toelk-A** [comment]
zu A) Pro Spender gibt es eine meldende Einrichtung inklusive der meldenden Station. Meines Erachtens muss von unserer Seite jeweils der Chefarzt der meldenden Station noch in Ornella hinterlegt werden. Die Hierarchie lautet:

Monat Januar 2018
Alle Spenden im Monat Januar
Meldende Einrichtung UND meldende Station (Z.b. Boddenkliniken - ITS)
-> Alle durchgeführten Spenden in der ITS der Boddenklinik abbilden 
-> Chefarzt aus Ornella als Adressat hinzufügen (Chefarzt ist unter "Position" in der Adressdatenbank abgebildet)

zu B) Ja, dieser Brief ist eine Monatsstatistik pro **meldende Station** einer Entnahmeeinrichtung. Das Heißt pro Entnahmeeinrichtung gibt es mehrere Monatsstatistiken, da jede Station über die durchgeführten Spenden informiert werden soll.

zu C) Vormonat bedeutet: Anfang Februar 2018 erstellen wir die Monatsstatistik für den Monat Januar 2018 (= Vormonat). Das Entnahmedatum ist ausschlaggebend für die Statistik. Das heißt, bekommen wir eine Spendermeldung am 31.01.2018 und die Entnahme findet am 01.02.2018 statt, so zählt diese bereits in den Februar.

zu D) bitte beibehalten

zu E) Hinsichtlich der Präparate OHNE Transplantate habe ich eine Beschreibung im hochgeladenen PDF Dokument hinterlegt.

**Comment by chrbusch** [comment]
Ad A) Bitte für HRO Süd bald eintragen, das ist mein Beispiel.

Ad E) Dann verstehe ich das nicht. Die dort genannten Status-IDs wie 33 gelten nur für Transplantate. Wir müssen wohl die genannten Werte ergänzen um Präparat-Status-IDs für den Fall, dass es keine Transplantate gibt, oder?

**Comment by chrbusch** [comment]
Wird der unterzeichnende Koordinator aus der Meld.Enrichtung gezogen?

![bildschirmfoto 2018-02-21 um 09 57 58](https://user-images.githubusercontent.com/1241899/36471144-b5e0b66a-16ed-11e8-8285-e0f6397db06c.JPG)

**Comment by chrbusch** [comment]
Um den Aufwand überschaubar zu halten, würde ich dies alles gerne als Text-Datensatz im Korrespondenzmodul gestalten. Dann sähe es etwa folgendermaßen aus (fine tuning natürlich noch möglich):

![bildschirmfoto 2018-02-21 um 10 23 00](https://user-images.githubusercontent.com/1241899/36472190-53218960-16f1-11e8-9eb8-7d50bf08c8e3.JPG)

**Comment by Toelk-A** [comment]
Zu A) -> nach Rücksprache mit Dr. Manecke sollen keine Chefärzte übernommen werden, sondern die Anrede in "Sehr geehrte Kollegen und Kolleginnen," geändert werden. Des Weiteren wird der "Koordinator" durch  
                    
"Dr.med. Axel Manecke
Dr.med. Frank-Peter Nitschke

Geschäftsführende Ärzte"   ersetzt.

zu E) Transplantate gibt es für OG UND KVG. Für MSG werden keine Transplantate angelegt. Beschreibung hierzu im PDF.

**Korrespondenzmodul**
Ist erstmal in Ordnung, aber nur wenn wir als Finetuning noch Tabellen etc. einfügen können.

**Comment by chrbusch** [comment]
A) ist erledigt
E) KVG möcht ich angehen, wenn OG perfekt ist.

Tabellen können NICHT im Korresp.Modul integriert werden. Der Aufwand wird wesentlich höher, wenn dies verlangt wird!
Ist die zu übergebende Information nicht ausreichend ansprechend durch einen Text mit Tabulatoren vermittelbar?

**Comment by chrbusch** [comment]
Aktueller Stand:

![bildschirmfoto 2018-02-21 um 11 00 12](https://user-images.githubusercontent.com/1241899/36473971-6f2d50f8-16f6-11e8-941a-473feb4ba746.JPG)

**Comment by Toelk-A** [comment]
Zur besseren Lesbarkeit dachte ich an eine Tabelle. Vielleicht kann man den Hintergrund pro Zeile abwechselnd grau/weiß/grau hinterlegen, um beim lesen nicht in der Zeile zu verrutschen?

**Comment by Toelk-A** [comment]
Vielleicht ist es besser mit einer kleinen meldenden Einrichtung mit wenigen Stationen wie z.B. Boddenklinik Ribnitz Damgarten (Adressendetails 104) als Testlauf anzufangen.

**Comment by chrbusch** [comment]
Wir können in dem Korresp.-Modul NUR Textverarbeitung machen, also auch z.B. kein eFärbungen.
Halte ich bei dieser ein informativen Liste aber auch für unerheblich.
Verrutschen in der Zeile hat ja keinerlei Konsequenzen, oder?
Morgen (Donn.) teste ich weiter mit Damgarten

**Comment by chrbusch** [comment]
Das Script fragt nun testweise nach dem Zeilenabstand; mir erscheint ca. 16 sinnvoll, bitte testen

**Comment by Toelk-A** [comment]
Nach Eingabe der Pixel "16" erscheint folgendes Bild:

![image](https://user-images.githubusercontent.com/22314271/36539302-a396bf88-17d6-11e8-9e9b-337cebf9cb27.png)


Wie soll es weitergehen?

**Comment by chrbusch** [comment]
Und klappt das jetzt?

**Comment by Toelk-A** [comment]
Das PDF wird erstellt und sieht erstmal gut aus - Fußzeile fehlt noch
Es werden nur 3 von den 6 gemeldeten Spendern (Station 3 Ribnitz Damgarten) abgebildet.

**Comment by chrbusch** [comment]
Das Script kümmert sich erst einmal NUR um OG.
Ist das denn jetzt so fertig?
Dann gehe ich an KVG

**Comment by Toelk-A** [comment]
Es wurden 4 Transplantate verworfen, abgebildet wurden allerdings nur 3. -> Bitte prüfen

![image](https://user-images.githubusercontent.com/22314271/36550153-de98b690-17f4-11e8-9681-07aa68b4feeb.png)

**Comment by chrbusch** [comment]
Da war versehentlich noch eine Testbedigung drin, die die Anzahl auf drei beschränkt hat, nun zeigt er alle 4

**Comment by chrbusch** [comment]
Bitte noch beantworten:
Feld8: Beim SpdTransplantat gibt es r.o. ein Feld "Grund für Verwurf", können wir dies nehmen?
Andernfalls bitte angeben, wo das neuen Feld hin soll

**Comment by Toelk-A** [comment]
Adressen Details 212
Klick auf Button "Monatsstatistik Stationen", dann läuft ein endloses Skript ohne Ergebnisse.

**Comment by chrbusch** [comment]
1. Beim Klick auf den Btn bei einer Stationsadresse wird nun nur diese ausgewertet; beim Klick im Hauptmenü alle Stationen
2. Das ist jetzt explizit so programmiert; bitte testen
3. In Ihrer Vorgabe war Feld 8 = "Grund für Nichttransplantation"; meine Frage lautet: Kann dafür unser Feld "Verwurfsgrund" genommen werden?
4: schaffe ich nicht vor dem Urlaub

**Comment by Toelk-A** [comment]
zu 2)

Test Boddenklinik Station 4 Adressendetails 213
Hier fand im Januar eine MSG Spende statt

Fehlermeldung:
![image](https://user-images.githubusercontent.com/22314271/36838144-a4673f4c-1d3e-11e8-9d40-b109e5fcff26.png)

**Comment by chrbusch** [comment]
...aber der Januar ist nicht der Vormonat!

**Comment by chrbusch** [comment]
Bin noch 50km südlich vom Polarkreis…

Wenn Sie das neue Auswertescript **bei einer Adresse** anklicken (also nicht im Hauptmenü für alle Adressen), so fragt das Script nun in bekannter Weise nach dem Zeitbereich.
Aus Performancegründen konnte ich das nicht selber testen, bitte tun Sie dies

**Comment by Toelk-A** [comment]
Bitte das Layout wie im Anhang bearbeiten

[Monatsstatistik bitte Layout bearbeiten.pdf](https://github.com/chrbusch/GTM-V/files/1797170/Monatsstatistik.bitte.Layout.bearbeiten.pdf)

**Comment by chrbusch** [comment]
Spaltenbreite: Wir haben doch i.d.R. OG und MSG/KVG parallel, oder?
Wie viele Zeichen der Transplantatbezng. sollen maximal abgebildet werden?

**Comment by Toelk-A** [comment]
# Spaltenbreite: Wir haben doch i.d.R. OG und MSG/KVG parallel, oder?
Es sollen OG, MSG und KVG in separaten Zeilen abgebildet werden

# Wie viele Zeichen der Transplantatbezng. sollen maximal abgebildet werden?

Generell sollen nur die folgenden "Begriffe" abgebildet werden:

"Cornea li." - **bereits programmiert**
"Cornea re." - **bereits programmiert**
"MSG" - _noch nicht programmiert_
"KVG" - _noch nicht programmiert_

# Evt. könnte man auch für die MSG/KVG-Transplantate eine Kurzbezeichnung in diesen Briefe platzieren, die nicht viel länger ist als der Ausdruck "Cornea..."?

Nein, bitte wie oben beschrieben abbilden.

# Wie wäre es mit "Musk.-skel. Gew."? Und dann die Spalten Immer gleich breit?

Generell sollen alle Spalten gleich groß sein, damit es nicht zu den gezeigten Verschiebungen kommt.

**Comment by chrbusch** [comment]
Ist geändert, bitte testen

**Comment by Toelk-A** [comment]
Adressen ID 212 Monat Februar

Bitte **alle** roten Markierungen (auch TEXT) bearbeiten:

[Änderungen Nr 2.pdf](https://github.com/chrbusch/GTM-V/files/1828559/Anderungen.Nr.2.pdf)

Original PDF:

[MonatsStatistikStationen_180320100511.pdf](https://github.com/chrbusch/GTM-V/files/1828569/MonatsStatistikStationen_180320100511.pdf)

**Comment by chrbusch** [comment]
Ist echt "fummeliges" Gebastel!
Bitte jetzt unter Windows noch einmal testen

**Comment by chrbusch** [comment]
Warum ist die Adresse rot umrandet?
Sollen AdressNr und Monat mit gedruckt werden?

**Comment by Toelk-A** [comment]
## 1) Warum ist die Adresse rot umrandet?
Sollen AdressNr und Monat mit gedruckt werden?
-> beides entfällt

## 2) Bitte bearbeiten:
[Monatsstatistik_bitte bearbeiten_3.pdf](https://github.com/chrbusch/GTM-V/files/1837239/Monatsstatistik_bitte.bearbeiten_3.pdf)

## 3) Grund für Verwurf
![image](https://user-images.githubusercontent.com/22314271/37767741-6f58178e-2dcb-11e8-9b8e-4918c710a0ab.png)

Transplantatdetails- Abschnitt Klassifikation
Wenn der Status [40] "Verworfen" angeklickt wird, öffnet sich automatisch das Eingabefeld "Grund Verwurf" (siehe Abbildung - gelbe Markierung). Dieses Eingabefeld enthält eine "selbstlernende Werteliste":
A) Können Sie uns diese selbstlernende Werteliste bitte zukommen lassen?
B) Wir möchten hieraus manuell eine "feste" Werteliste Y erstellen.
C) Zusätzlich soll zu dieser Werteliste Y pro zugehöriger Zeilenspalte eine verknüpfte Werteliste "Grund für Verwurf für Monatsstatistik" durch uns erstellt werden. Das heißt, klickt der MA in der festen Werteliste Y auf einen Verwurfsgrund, so soll automatisch der zugehörige Wortlaut aus der Werteliste "Grund für Verwurf für Monatsstatistik" im Bericht Monatstatistik abgebildet werden. (Das war kompliziert, bei Fragen rufen Sie mich bitte an)

**Comment by chrbusch** [comment]
Ad A) Die Liste habe ich Ihnen gemailt, als Bild. Hier noch einmal als Text:

Überlagerung KI

Entnahmefehler
Endothelzellnekrose
Hornhautnarbe
Endothel pathologisch
Kontamination KI iatrogen
Überlagerung KII
Kontamination KI
Cornea guttata
keine Freigabe Gewebe gemäß §8 Abs. 1 Satz 2 Nr. 4
perforiertes Ulcus mit Iristamponade (Diagnose nach Fotobeweis) SCP
V.a. Cornea guttata
zentrale Nekrosen, unregelmässiges, lückenhaftes Zellbild
großflächige Nekrosen überall
beg. Cornea guttata
Grossflächige Nekrosen überall
Endothelzellnekrose, massiver Zellverlust
zu geringe Endothelzelldichte

**Comment by chrbusch** [comment]
Hauptmenu > Supervisor > Voreinstellungen, dort Reiter "Wertelisten"
Die bisherigen Werte sind dort bereits eingetragen.

![bildschirmfoto 2018-03-26 um 10 15 05](https://user-images.githubusercontent.com/1241899/37894441-933138e6-30de-11e8-98e9-70bc7c68bf76.JPG)

**Comment by chrbusch** [comment]
Nun ist auch das Feld "Grund für Verwurf" mit dieser neuen Liste verknüpft.
Die Begriffe erscheinen aus techn. Gründen alphabetisch, anders geht das nur mit deutlich mehr Aufwand.

**Comment by chrbusch** [comment]
Das mit dem 2. Feld ist nicht ganz trivial, ich habe eine Idee gehabt, wie man das für diesen und andere Fälle lösen kann.
Könnten Sie eine XLS-Liste mit 2 Spalten liefern, "interner Grund" und "Grund für Monatsstaistik"?
Wir können das so einrichten, dass Sie diese Werte später selbst bearbeiten können

**Comment by Toelk-A** [comment]
## Anbei die gewünschte XLS:

[Grund Verwurf MOnatsstatistik_neu.xlsx](https://github.com/chrbusch/GTM-V/files/1847377/Grund.Verwurf.MOnatsstatistik_neu.xlsx)

1) Wir haben die Originalspalte "Interner Grund" zusammengekürzt. Diese soll in Zukunft, wie oben beschrieben, nur als manuell "feste" Werteliste genutzt werden können.

2) Für die Monatsstatistik, soll dann das Ergebnis der zugehörigen Partnerspalte abgebildet werden.

**Comment by chrbusch** [comment]
Rote Änderungen sind umgesetzt, und der neue Verwurfsgrund integriert.
Bitte teste

**Comment by Toelk-A** [comment]
A) Wir haben alle Hornhäute mit dem Status "Verwurf"[40] mit der neuen Werteliste aktualisiert. Es wird der entsprechende "Wert" in MStat UND dem PDF der Monatsstatistik abgebildet -> **funktioniert super**

B) für die folgenden Stati benötigen wir ebenfalls ein Eingabefeld ähnlich dem "Grund Verwurf":

![image](https://user-images.githubusercontent.com/22314271/37970498-e9d444b8-31d3-11e8-9e93-8612121300d4.png)

C) Auch für die unter "B" genannten Stati soll der entsprechende "Grund für Monatsstatistik" abgebildet werden.

**Comment by chrbusch** [comment]
Ich habe das Feld umbenannt in "d_Status_Grund_..." anstelle von "Grund_Verwurf";
und dieses Eingabefeld wird jetzt immer angezeigt
Sie können mit
Hauptmenu > Supervisor > Voreinstellungen, dort Reiter "Wertelisten"
die Werteliste bearbeiten, die ich umbenannt habe in "Transpl. Status Gründe"
Zudem gibt es nun2 Textfelder, in denen wir die Bedeutung der Wertelisten-Einträge erläutern können, siehe Bild

![bildschirmfoto 2018-03-30 um 07 30 57](https://user-images.githubusercontent.com/1241899/38125886-10f50896-33ed-11e8-8d99-1b53ca8c0bd9.JPG)


![bildschirmfoto 2018-03-30 um 07 35 57](https://user-images.githubusercontent.com/1241899/38125894-157b445c-33ed-11e8-9b3d-1ce1e64dee4b.JPG)

**Comment by Toelk-A** [comment]
Transplantatdetails - Abschnitt Klassifikation 

![image](https://user-images.githubusercontent.com/22314271/38243431-c1cb5bf0-3737-11e8-9f38-fce6881cdf7c.png)

### "Ich habe das Feld umbenannt in "d_Status_Grund_..." anstelle von "Grund_Verwurf";
und dieses Eingabefeld wird jetzt immer angezeigt"

-> Dieses Feld bitte nur bei den genannten Stati anzeigen.

**Comment by chrbusch** [comment]
Ist erledigt

PS: Plural von "Status" heißt auch "Status"

**Comment by Toelk-A** [comment]
Danke für die Info :-)

beim Status "verworfen, fehlt jetzt das Eingabefeld:

![image](https://user-images.githubusercontent.com/22314271/38305539-7ab33284-380d-11e8-8e5a-64fd49704a52.png)

**Comment by chrbusch** [comment]
Ja, ich hatte nur die Status aus Ihrem obigen Bild abgefragt. Sollte jetzt wieder stimmen

**Comment by Toelk-A** [comment]
Adresse 212
Monat März

Fallnummer: 48005497    -> die linke Seite Kornea ist prozessiert und fest allokiert. Es sind im System keine Empfängerdaten hinterlegt, sodass die Geschlecht und Alter "w 65" eigentlich nicht abgebildet werden dürfen. 

Bitte prüfen!!!

[MonatsStatistikStationen_180405153635.pdf](https://github.com/chrbusch/GTM-V/files/1880268/MonatsStatistikStationen_180405153635.pdf)

**Comment by chrbusch** [comment]
Grüner Satz: Sie können den Textbaustein, der hier verwendet wird, selbst bearbeiten!
Bitte hierzu anrufen

**Comment by chrbusch** [comment]
Ad 1)
Im System ist der Pat. WS zugeordnet, für den Alter + Geschlecht erfasst sind

**Comment by chrbusch** [comment]
Ad 2): Dies bitte jetzt testen, Suchbedingung ist erweitert.
(Bin aber nicht sicher, ob das ausreicht)

**Comment by Toelk-A** [comment]
1) erledigt

2) hier rufe ich Sie gleich noch einmal an. 

Adressen ID 212 

Ein Testen ist nicht möglich, da die Monatsstatistik März am 12.04.18 ausgedruckt wurde. Beispiel Fallnummer 48005497 (Spender ID 4345)-> Transplantatdetails ID 2009: Transplantat wurde am 22.03.2018 hergestellt und am 04.04.18 transplantiert. Im Monatsbericht März hätte also für die Fallnummer 48005497 (Spender ID 4345) hätte also in der Monatsstatistik März der Status "P" abgebildet werden müssen und für April erst der Status "T".

3) Erledigt

4) Bitte noch die folgenden Anpassungen durchführen:

[Letzte Abstandsanpassungen.pdf](https://github.com/chrbusch/GTM-V/files/1902007/Letzte.Abstandsanpassungen.pdf)

**Comment by chrbusch** [comment]
Die Zeilenabstände gezielt einzustellen ist recht aufwändig; ist das wichtig?
Ich habe zunächst das Textfeld nach oben geschoben und alles enger zusammen gebracht, so dass i.d.R. eine Seite reicht

**Comment by Toelk-A** [comment]
1. erledigt
2. in Arbeit durch CBU
3. erledigt
4. erledigt - super Darstellung :-)

**Comment by chrbusch** [comment]
Der genannte Fall erscheint nun, wenn man AKTUELLER MONAT wählt, mit dem Status "T"; ist das nun so korrekt?

<img width="433" alt="bildschirmfoto 2018-04-23 um 12 40 51" src="https://user-images.githubusercontent.com/1241899/39121980-a62bf172-46f3-11e8-8da5-d72c6596d171.png">

**Comment by Toelk-A** [comment]
1) Ja das ist korrekt.

2) für den Monat März muss aber der Status "P" für den o.g. Fall abgebildet werden, da die Transplantate im März noch nicht transplantiert waren... bitte programmieren Sie dies fertig

![image](https://user-images.githubusercontent.com/22314271/39170721-dd40e7ae-479c-11e8-996b-6f05f69cc0a0.png)

**Comment by chrbusch** [comment]
OK, Sie haben Recht; aber dann brauchen wir tatsächlich für dieses Script die neue Tabelle "Statuswechsel", in der es natürlich für den März noch keine Einträge gibt.
(Für den April aber bereits 480 Stück)
Wir können daher die gewünschte Funktion erst für die im Mai erstellte April-Auswertung programmieren, da das System für Status vor dem 13.4.2018 nicht weiss, ab wann und bis wann diese bestanden. Konkret kann man nicht am 24.4. ermitteln, wie der Status am 31.3. war.

**Comment by Toelk-A** [comment]
Zum Testen habe ich nun den Button "Auswertung" -> "Monatsstatistik Stationen" benutzt.

Es wurde die folgende PDF erstellt.
[MonatsStatistikStationen_180424114747.pdf](https://github.com/chrbusch/GTM-V/files/1942179/MonatsStatistikStationen_180424114747.pdf)

Bereits auf den ersten Seite erkenne ich die folgenden Fehler:

1) "Abstandsstrich" ist falsch gesetzt -> er trennt die Transplantate, die eigentlich zu ein und demselben Spender gehören:

![image](https://user-images.githubusercontent.com/22314271/39179962-f88e5d48-47b5-11e8-9a3f-72c149017b10.png)

2) Zum Spender 5547752 gibt es 2 Transplantate Cornea, es wird aber nur 1 abgebildet.

Bitte Fehler beheben. Die Monatsstatistik ist noch immer nicht vollständig fehlerfrei programmiert :-/

**Comment by chrbusch** [comment]
Die Forderung, dass ein Transplantat mehrfach, je nach Zeitpunkt der Statuswechsels, in dieser Statistik auftaucht, ist NACH der ersten Programmierung erhoben worden, weshalb ich all diese Arbeiten berechnen werde.
Lohnt es wirklich, jetzt noch einmal einen dreistelligen Betrag zu investieren, damit EINE EINZIGE Aufstellung perfekt ist?
Ab Mai kann ja alle auf der neuen Tabelle StatusWechsel aufgebaut werden!
Bitte mit Dr Nitschke besprechen.

**Comment by Toelk-A** [comment]
Das heißt also wir können die Monatsstatistik für April nicht versenden?

**Comment by Toelk-A** [comment]
Wir arbeiten seid Februar an diesem Ticket. Dieses Ticket sollte Ende letzter Woche fertiggestellt werden... vorhin am Telefon fragte ich Sie, ob die Statistik für April fertig zum Versand ist...

ich verstehe nicht, warum es noch immer zu Fehlprogrammierungen kommen kann, nachdem alles an einer Adresse geprüft wurde? Ich verstehe nicht warum auf einmal nur 1 anstatt 2 Transplantate abgebildet wird? Wenn Sie nach oben scrollen wurde dieser "Programmierfehler" durch sie bereits gelöst.... und taucht nun wieder auf.

Auch meine Arbeitszeit ist von der ständigen Überprüfung Ihrer Programmierungen abhängig...

**Comment by chrbusch** [comment]
"ich verstehe nicht, warum es noch immer zu Fehlprogrammierungen kommen kann"
...kommt es gar nicht, und ich habe es oben auch schon erklärt:
Lesen Sie sich die ersten Beiträge dieses Tickets durch: Nichts sprach dafür, dass ein Präparat in mehreren Monaten auftauchen sollte; dann wäre die richtige Tabelle die der Präparate gewesen.
Die _nachträglich_ erhobenen Forderung, dass ein Wechsel in den Status "T" im Folgemonat zu einer erneuten Aufnahme des Präparates in die Liste führt, erforderte eine neue Tabelle, eben "StatusWechsel", damit das System weiß, bis wann ein Status galt. Die hierfür erforderlichen Daten haben wir aber erst ab 13.4.2018

**Comment by Toelk-A** [comment]
Hier MSG und OG vom selben Spender, aber mit Trennstrich unterbrochen abgebildet

[MSG und OG derselbe Spender _ trotzdem getrennt abgebildet ID1313.pdf](https://github.com/chrbusch/GTM-V/files/1945600/MSG.und.OG.derselbe.Spender._.trotzdem.getrennt.abgebildet.ID1313.pdf)

**Comment by chrbusch** [comment]
Falsche Trennstriche nun in allen erwähnten Situationen m.E. korrekt

"Zum Spender 5547752 gibt es 2 Transplantate Cornea, es wird aber nur 1 abgebildet.": Eines davon (D) ist im Februar transplantiert worden und fehlt daher zu Recht im März-Bericht

**Comment by Toelk-A** [comment]
Adressen ID 21

Es gibt nur eine linke Kornea, die rechte Seite wurde nicht entnommen und darf dementsprechend auch kein "Empfänger" abgebildet werden sein

![image](https://user-images.githubusercontent.com/22314271/39229968-15223600-4865-11e8-9a25-fc3d6d8fe3b1.png)

**Comment by chrbusch** [comment]
Die rechte Seite hat den Status "22=entnommen" und ist daher m.E. zu Recht auf dem Bericht.

**Comment by Toelk-A** [comment]
Sie haben Recht! Dies war ein Dokumentationsfehler unsererseits. Ansonsten sieht auf den ersten Blick alles gut aus. Dann machen wir an dieser Stelle wie besprochen Anfang Mai weiter.

**Comment by Toelk-A** [comment]
Adressen ID 120
Monatsstatistik März

Wenn das Transplantat **verworfen** ist, darf **kein Transplantatempfänger** eingegeben sein!!! Es scheint, dass das System auf den letzten Empfänger zurückgreift und diesen dann bei dem verworfenen Transplantat abbildet:

![image](https://user-images.githubusercontent.com/22314271/39235118-537f6db8-4875-11e8-9ea2-59834889daee.png)

**Comment by chrbusch** [comment]
Dies ist auch eine neue Anforderung.
Um uns nicht unendlich im Kreis zu drehen müsste wohl einmal klar festgelegt werden, mit welchen Status die Präparate in die Liste gehören.

**Comment by Toelk-A** [comment]
Hallo Herr Busch, ich möchte das Ganze telefonisch klären, da wir beide anscheinend aneinander vorbeireden. Es handelt sich nicht um eine neue Anforderung. Es geht um die Behebung von Programmierfehlern.

Wenn ein Transplantat verworfen wurde, kann es keinem Empfänger transplantiert worden sein! Da sich auch im System keine Empfängerdaten zu den gezeigten verworfenen Transplantaten befinden.... ist dies also ein Programmier/Skriptfehler. Ich bitte Sie nur diesen **Fehler zu beheben** nichts anderes.

Bitte rufen Sie mich zurück.

**Comment by chrbusch** [comment]
Ich habe noch einmal geprüft: Beide Corneae haben einen Verweis auf eine GewAnforderPos. Diese wiederum haben beide denselben Status 35=erl. und eine Patienten_ID, siehe Bild


![bildschirmfoto 2018-04-25 um 12 27 35](https://user-images.githubusercontent.com/1241899/39240442-0e66645c-4884-11e8-8623-edbb21962273.JPG)

**Comment by Toelk-A** [comment]
Ich bitte erneut darum, dass Sie mich zurückrufen.

**Comment by chrbusch** [comment]
DOCH, das war ein Fehler, sorry!
Das System hat NUR wenn eine Patienten-ID vorliegt, sex&age bestimmt; das ist richtig.
Aber ich habe vergessen, die letzten Werte andernfalls auch zu LÖSCHEN, was jetzt passiert:

![bildschirmfoto 2018-04-25 um 13 10 02](https://user-images.githubusercontent.com/1241899/39242332-fc390c20-4889-11e8-8025-deecd890ef5f.JPG)

**Comment by Toelk-A** [comment]
Hallo Herr Busch, können wir hier die Programmierung hinsichtlich der Status der Transplantate zu Ende bringen? z.B. Ist ein Transplantat im Monat April in Prozesssierung so soll es dort mit Status "P" abgebildet werden. Wird es im Mai transplantiert so soll, das selbe Transplantat im Mai mit "T" abgebildet werden. Bitte nutzen Sie die bereits programmierte Tabelle "Statuswechsel des Transplantates". (Transplantatdetails - Reiter Dokumente und Status- ganz unten)

**Comment by Toelk-A** [comment]
![image](https://user-images.githubusercontent.com/22314271/39697990-3e9a5b92-51f3-11e8-946f-160fa8cee674.png)

**Comment by chrbusch** [comment]
Ich denke, das System extrahiert nun korrekt den Status zum Ende des ausgewerteten Monats, dies ist "P" in unserem Beispiel.
Allerdings müssen dann m.E. auch noch die Patientendaten weg?
![bildschirmfoto 2018-05-07 um 17 41 23](https://user-images.githubusercontent.com/1241899/39710756-01490614-521e-11e8-91f0-20221277a0c6.JPG)

**Comment by chrbusch** [comment]
Das habe ich nun auch erl.

**Comment by Toelk-A** [comment]
Adressen ID 120
Monatsstatistik April 2018

## 1) Die Gewebe sind nicht mehr abgebildet

-> bitte korrigieren
![image](https://user-images.githubusercontent.com/22314271/40488507-38c11248-5f67-11e8-8726-e220e716356e.png)

## 2) Aufn. -Nr. durch Position ersetzen
Bezugnehmend auf die neuen Datenschutzrichtlinien, dürfen wir nach Rücksprache mit unserem DS-Beauftragten keine Aufn. -Nr. mehr in den Monatsstatistiken abbilden. Diese müsste also entfernt werden und durch die Positionsnummer ersetzt werden.

**Comment by chrbusch** [comment]
m.E. erledigt, bitte testen

![bildschirmfoto 2018-05-25 um 09 05 41](https://user-images.githubusercontent.com/1241899/40530928-d76bc10c-5ffa-11e8-95f6-ab82c2975ba8.JPG)

**Comment by Toelk-A** [comment]
und nun doch wieder anders...
anbei die letzten Änderungswünsche:

[Letzte Modifikationen Monatsstatistik.pdf](https://github.com/chrbusch/GTM-V/files/2038716/Letzte.Modifikationen.Monatsstatistik.pdf)

**Comment by chrbusch** [comment]
So etwa?

![bildschirmfoto 2018-05-25 um 13 52 12](https://user-images.githubusercontent.com/1241899/40543017-db589f2e-6022-11e8-8bc3-d82206ec4f10.JPG)

**Comment by Toelk-A** [comment]
ja, perfekt

**Comment by Toelk-A** [comment]
Wenn Status P, dann darf kein "Verwurfsgrund"angegeben sein.


![image](https://user-images.githubusercontent.com/22314271/40844822-3ab2ffd6-65b5-11e8-90dc-90334e7ce1bf.png)

**Comment by chrbusch** [comment]
Es gab ein problem im Programm: Hat das Transplantat seinen Status noch nicht gewechselt, gab es keinen Datensatz in der StatusWechsel-tabelle, dann resultierte "-". In all diesen Fällen schreib eich jetzt "P"
-
Alle anderen Punkte liegen vermutlich an der Dokumentation, was Sie aber bitte selbst prüfen müssen.
Ich selbst kann es nicht mit vertretbarem Aufwand, weil das Dokument keine benutzbare ID oder KennNr mehr enthält.
Ich plädiere dringend dafür, klein gedruckt zB die Präparate-ID  in das Dokument aufzunehmen.

**Comment by Toelk-A** [comment]
Status "P" mit Verwurfsgrund. Transplantat ID 2212

-> Transplantat hat den Status "Verworfen", warum wird hier ein "P" für Prozessierung abgebildet?

![image](https://user-images.githubusercontent.com/22314271/40901236-a2d2116c-67cf-11e8-99a4-47032db2e9f2.png)

**Comment by chrbusch** [comment]
Der Verwurf wurde erst im Juni dokumentiert, darf also für die Mai-SStatistik nicht erscheinen

**Comment by chrbusch** [comment]
Ende Mai hatte das Tr. den Status 39="Sperre" - soll dann "V" abgebildet werden oder welcher Wert?

**Comment by Toelk-A** [comment]
ja

**Comment by chrbusch** [comment]
Verwurfsgrund wird nun gelöscht, wenn Status NICHT "V" ist
