### ISSUE TITLE
Funktionsprobleme in Ornella

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#305]
1) Die linke Auswalliste reagiert zum überwiegenden Teil während der Nutzung von Ornella nicht, um die benötigte Funktion auszuwählen, muss auf das Bild von O. Muti und dann auf Themen und Funktionen geklickt werden …

2) „Persönlicher Kalender“ zur Eintragung der AZ kann nicht geöffnet werden …

**Comment by chrbusch** [comment]
Bitte per TeamViewer Live-Blick auf dieses Problem ermöglichen
