### ISSUE TITLE
GBMV/ Spender ID 4045 - Transplantatnummer alte 126 löschen und 127 zu 126 neu umschreiben

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#307]
Spender ID 4045 

OG Transplantat Status in "Planung" mit Transplantatnummer  126 CD und CS - (Transplantatadetails ID 1879 und 1880). Die Transplantate wurden gelöscht, da Wiederspruch. 
Gleichzeitig wurde bereits Transplantatnummer "127 CD und CS" angelegt. 

Die 126 (Transplantatadetails ID 1879 und 1880) muss im System gelöscht (da noch immer in Transplantatliste erscheint) und die 127 als neue "126" angelegt werden.

**Comment by chrbusch** [comment]
Das ist erledigt, bitte prüfen.

**Comment by Toelk-A** [comment]
Das ist erledigt. 

Jetzt fehlt die 127 in der Allokationsliste. Bitte überschreiben Sie die 128 zur 127 und programmieren Sie, das Skript so, dass das nächste angelegte Transplantat die 128, 129, 130 sind... also fortlaufen, ohne dass eine Zahl ausgelassen wird.

**Comment by chrbusch** [comment]
Das habe ich zwar jetzt gemacht, halte dies aber für keine gute Strategie für die Zukunft.
Bitte mit Dr. N. besprechen: Es wird immer wieder vorkommen, dass Sie schon Transplantate angelegt haben, und dies dann revidiert werden muss. Angehörige können sich ja auch nach Entnahme umentscheiden!
Daher meine ich, dass wir eine sauber beschriebene "Storno-Option" brauchen, die man im Falle einer Prüfung vorlegen kann und die nachvollziehbar begründet, warum die Transpl.-Nr Lücken hat.

**Comment by chrbusch** [comment]
PS: Über Hauptmenü/Supervisor/KennNr-Liste
können Sie übrigens selbst den Stand der div. Nummern bearbeiten!

![bildschirmfoto 2018-02-28 um 11 01 19](https://user-images.githubusercontent.com/1241899/36781638-baa01c2a-1c76-11e8-98fd-767f73ed4144.JPG)

**Comment by chrbusch** [comment]
Ich habe gerade bemerkt, dass man auf "Transplantat Details" die Bank-interne Nr noch ändern kann.
Dies sollte m.E. dem normalen User nicht möglich sein, ABER für Ausnahmefälle einem Supervisor.
Soll ich das umsetzen?

**Comment by Toelk-A** [comment]
Bitte für Supervisor programmieren

**Comment by chrbusch** [comment]
Ist erledigt; bitte als Supervisor und Normal-User testen
