### ISSUE TITLE
Alter neuer Fehler Hieroglyphen im Hauptmenü Personalplanung

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#308]
Die Hieroglyphen tauchen im Hauptmenü Personalplanung bei unserer Mitarbeiterin in Leipzig auf.
Bitte beheben Sie den Fehler. es scheint kein anderer Koordinator betroffen.

![image](https://user-images.githubusercontent.com/22314271/36734756-be7c7606-1bd4-11e8-8206-e43b420ba44b.png)

**Comment by chrbusch** [comment]
Das hat m.E. nichts mit meinem Programm zu tun, eher mit fehlerhaften Schriften auf dem Computer dort. Der Titl des Hauptmenü ist fest "hingeschrieben", hier tritt keinerlei Berechnung auf. Ich wüsste nicht, was ich daran tun kann.

**Comment by Toelk-A** [comment]
Ich selbst hatte das Problem ebenfalls vor einigen Monaten auf meinem PC. Von einem Tag auf den anderen war es dann aber auch wieder verschwunden. Könnte es an der Nutzung von Ornella im Remote Desktop Modus liegen?

**Comment by chrbusch** [comment]
Ich habe keine Ahnung! Ich lebe seit 25 Jahren von Filemaker-programmierung und habe nie von diesem Phänomen gehört. Tritt das NUR bei dem Titel des Menüs auf?
Ich habe gerade mal den Schrifttyp geändert, vllt. hilft das?
