### ISSUE TITLE
Versehentlich 2x rechter Bulbus angelegt - Umschreiben in 1x OS + Herstellungsschritte anlegen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#309]
Spender ID 3846

bei diesem Spender sind versehentlich zwei OD (2x rechter Bulbus) als entnommen dokumentiert worden. Dieses führt bei den Prozessschritten zu fehlender linker Seite (OS). 

Können Sie die Bezeichnung OD bei den Gewebepräparaten auf OS umschreiben und die fehlenden Prozessschritte bei der Herstellung hinzufügen?

![image](https://user-images.githubusercontent.com/22314271/36791820-13ca4aba-1c99-11e8-87ce-d2ed5164acad.png)

![image](https://user-images.githubusercontent.com/22314271/36791848-26a5af9e-1c99-11e8-8430-c98a1bfff33d.png)

**Comment by chrbusch** [comment]
Bitte die Prozessschritte für "links" prüfen, ich habe sie manuell addiert.
