### ISSUE TITLE
RBD April 2018 - alte Fehler beheben

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#310]
Hallo Herr Busch,

anbei der RBD-Plan für April:

1)	Frau Kroll hat 2x WE Dienst, Herr Petrowski garnicht
2)	NIF hat am 27.04.Urlaub und steht mit „Dienst“ ärztlicher Mitarbeiter drin
3)	Die Mitarbeiterliste wird anscheinend nicht mehr automatisch aktualisiert, sodass im Moment keine gerechte Verteilung der Dienste kontrollierbar ist.

Bitte beheben Sie die leider noch immer alten Fehler bis 01.03.2018…
Danke

[RBD-Monatsplan_2018_4.PDF](https://github.com/chrbusch/GTM-V/files/1767372/RBD-Monatsplan_2018_4.PDF)

**Comment by chrbusch** [comment]
Ad 1: Das erscheint mir auch richtig, denn bis Ende März hatte Hr. Pet. 9 mal WE-Dienst, und Frau Kroll nur 5 mal.

Ad 3:Es ist etwas ungewöhnlich, dass Sie heute den RBD-Plan für den ÜBERnächsten Monat erstellt haben, oder? Das System fragt aber jetzt, bis zu welchem Monatsende Sie die RBD-Anzahlen ausgewertet haben möchten beim Ausdruck der Mitabeiterliste. Auf dem PDF, bei dem Sie die Aktualisierung vermisst hatten, stand höchstwahrscheinlich im Header "...bis 31.3.2018" und die Anzahlen waren richtig.

**Comment by chrbusch** [comment]
Ad 2. Da wir nur zwei Ärzte haben, können diese beiden geforderten Bedingungen nicht immer eingehalten werden:
1) Niemand soll zwei Wochen nacheinander Dienst haben
2) Niemand soll an einem Urlaubstag Dienst haben.
Hier muss m.E. manuell eingegriffen werden.

**Comment by Toelk-A** [comment]
1) Die Dienste von Frau Kroll konnte ich nicht einsehen. Da haben Sie Recht.
2) Bei den Ärzten gelten die Regeln natürlich nicht so hart wie beiden Koordinatoren. ist ein Arzt im Urlaub, so kann er logischer Weise keinen Dienst machen. Die Ärzte ändern wir für die Zukunft einfach manuell.
3) Die MA Liste zeigt noch immer nicht die richtigen zahlen an. Beispiel Herr Schweder: hat 3 Wochenenddienste geleistet, das heißt er müsste 9d in der MA Liste stehen haben (RBD Fr-So). Es stehen aber nur 8.

-> Prüfen Sie dies bitte erneut, sodass ich den Dienstplan + Mitarbeiterliste HEUTE den Koordinatoren vorlegen kann.

**Comment by chrbusch** [comment]
Herr Schweder hat "Osterdienst" um den 1.4. herum; hiervon zählen die meisten tage nicht als WE, sondern Feiertagsdienste!

**Comment by Toelk-A** [comment]
Meines Erachtens hatten wir bereits besprochen, dass Wochenenddienste "normal" (Fr- So egal ob Feiertag) gezählt werden und die Feiertagsdienste nur der Übersicht halber "zusätzlich" abgebildet werden.

**Comment by chrbusch** [comment]
Wenn ein Tag WE **und** FT sein kann, hat das m.E. bedeutsame Konsequenzen, die ich für besonders fehlerträchtig halte:
Was soll das System z.B. am Karfreitag tun, wenn ein Mitarbeiter zu viele Wochenende-RBD hat, aber zu wenige Feiertag-RBD?? Beides auszugleichen halte ich schon rein mathematisch für schwierig, wenn ein Tag in beide Kategorien fallen kann.
Oder können Sie hier eine klare Regel vorgeben?
