### ISSUE TITLE
GBMV/ Personalplanung - Wiedervorlage bei AZK/Urlaub Wunsch MA

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#312]
Bitte Wiedervorlagen (für NIF, MAA, GRC) programmieren, wenn ein Mitarbeiter den Status "AZK MA WUNSCH" [10] oder "URLAUB MA WUNSCH" [12] in den Teamkalender/persönlichen Kalender eingibt.

**Comment by chrbusch** [comment]
Ich denke, das klappt jetzt.
Wg. der div. User-Eigenschaften und Rechte kann ich es nur schlecht selbst testen, bitte tun Sie dies

**Comment by Toelk-A** [comment]
Es scheint nicht zu funktionieren - NIF erhält keine Wiedervorlage. Nachdem über den Button Fkt. (Teamkalender) "Urlaub MA Wunsch" bzw "AZK MA Wunsch" geklickt wird erscheint folgende Fehlermeldung:

![image](https://user-images.githubusercontent.com/22314271/37718295-a986238c-2d22-11e8-9789-ce4f7e431d11.png)

**Comment by chrbusch** [comment]
OK, ich teste jetzt selbst, indem ich FÜR SIE in der kommenden Woche entspr. Daten eintrage.
Bitte mit daran denken, dass wir dies später zurück fahren

**Comment by chrbusch** [comment]
Scheint mir zu klappen; bitte bearbeiten Sie IHREN Tag 28.3., prüfen die Wiedervorlagen und setzen dann den 8.3. zurück

**Comment by Toelk-A** [comment]
1) Die Wiedervorlage funktioniert.

2) Bitte folgendes programmieren: Klickt man auf den Button "Go" in der Wiedervorlage, soll sich direkt der Teamkalender zum entsprechenden Datum des Wunsches öffnen.

**Comment by chrbusch** [comment]
Ist erledigt; Details hierzu schreibe ich demnächst in einer Email

**Comment by Toelk-A** [comment]
erledigt
