### ISSUE TITLE
GBMV\ Modifizierung Button "Befunde aller Art"

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#313]
Transplantadetails
Abschnitt "Befunde aller Art" -> Button „Standardbefunde anlegen“ 

1) Bitte die "Bindehautabstriche" aus den Standardbefunden rausnehmen (siehe rote Markierung).

![image](https://user-images.githubusercontent.com/22314271/37664003-c1976be8-2c5a-11e8-9de3-0c78f3cfb066.png)

2) Die Bindehautabstriche müssen aber nachträglich trotzdem hinzufügbar sein- ähnlich dem Glaskörperabstrich (Button "Neuer Befund")

**Comment by chrbusch** [comment]
Erledigt, bitte testen

**Comment by Toelk-A** [comment]
erledigt
