### ISSUE TITLE
GBMV/ Erweiterte Optionen für Wiedervorlagen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#314]
Mit Bezug auf Ihre Mail 22.03.18 10:14Uhr haben wir folgende Ideen:

1.	Bei der Eingabe von mikrobiologischen positiven Befunden wird eine Wiedervorlage generiert. (**bereits programmiert**) Auch hier sollte per Button das Layout OG-Transplantat-Details (ID:360) angesteuert werden

2.	Änderung des Status eines Transplantates (ID: 33, 34, 35, 48, 52, 50, 36, 44 - Status-SGPTAR Liste), in den Status welcher eine Transplantation ausschließt (ID: 68, 39, 40, 38, 65, 66) – Wiedervorlage generieren und per Button das Layout OG-Transplantat-Details (ID:360) angesteuert werden

3.	Die Änderung des Status eines Spenders (Status-SGPTAR Liste) in ID: 67 – Wiedervorlage generieren und Layout ID: 9 ansteuern

4.	Die Allokation für eine nächste Woche muss am Donnerstag bis 17:00 Uhr abgeschlossen, d.h. allen Anforderungen muss ein Transplantat zugeordnet sein. Dieses muss als Bericht im pdf-Format auslesbar sein und im Layout 364 in einem Reiter abgelegt werden. Änderungen in diesem Bericht müssen eine Wiedervorlage generieren, unter Angabe des Feldes, welches geändert wurde, einen neuen Bericht erzeugen und  zusätzlich eine Mail generieren an die Mitarbeiter der GBM-V

**Comment by chrbusch** [comment]
Ad 2.: Wir haben in der Status-tabele ein Feld "Herstg. erlaubt?"; es ist angekreuzt NUR bei 37=Planung. Bitte setzen Sie Kreuze für alle Status, für die Herstellung erlaubt ist.
Und heißt Ihre obige Forderung dann Wechsel von einem Status mit Kreuz zu einem ohne?
Oder brauchen wir noch ein Ankreuzfeld á la "Transplantation erlaubt"?

**Comment by chrbusch** [comment]
Ad 3: Erledigt

**Comment by chrbusch** [comment]
Ad 4: Das ist komplexer.
Was meint "allen Anforderungen muss ein Transplantat zugeordnet sein."?
Was sind "alle Anforderungen" - die "unbedienten" aus der Vergangenheit? Wieviele Tage zurück?
Und auch die, die heute erst herein kamen?
Und es gibt doch nicht immer genug Transplantete? Ich brauche hier genauere Angaben, was das Programm tun soll.

**Comment by chrbusch** [comment]
Ad 2: m.E. erledigt fest für die genannten Status-ID, aber besser fände ich eine flexible Lösung über die Status-Tabellle

**Comment by Toelk-A** [comment]
Zu 4: 
Ornella Hauptmenü -> Allokation -> Allokationswochenbericht -> kommende Woche (= Fenster "offene Gewebeanforderungen" öffnet sich)

![image](https://user-images.githubusercontent.com/22314271/37971880-545c138a-31d7-11e8-8e82-86fffde27081.png)

Gelb markiert ist der Status bestellt, d.h. es wurde noch keine Hornhaut zugeordnet = "offene Anforderung". Wie oben beschrieben soll generell bis donnerstags 17:00Uhr allen Anforderungen ein Transplantat zugeordnet sein. Das heißt, es soll keinen Status "bestellt" mehr geben, sondern nur noch der Status "In Arbeit" in den Hornhaut Anforderungen sichtbar sein.

## Was meint "allen Anforderungen muss ein Transplantat zugeordnet sein."?

"Alle Anforderungen" = Gewebanforderung für die kommende Kalenderwoche

Für jede dieser Anforderung darf also nicht der Status der Position "Bestellt" sondern muss der Status der Position "in Arbeit" sein, dann ist jeder Anforderung ein Transplantat zugeordnet.

Ornella Hauptmenü -> Allokation ->Gewebe-Anfordg. nach Status

![image](https://user-images.githubusercontent.com/22314271/37972576-ee50dbc8-31d8-11e8-9e3a-e6ac6224f830.png)

## Was sind "alle Anforderungen" - die "unbedienten" aus der Vergangenheit? Wieviele Tage zurück?

Alle Anforderungen = die Anforderungen der kommenden KW

## Und auch die, die heute erst herein kamen?
Ja, wenn die Anforderungen für die kommende KW sind, bzw. für die laufende Kalenderwoche noch Anforderungen hinzukommen, wo Transplantate zugeordnet werden müssen. 

## Und es gibt doch nicht immer genug Transplantete? Ich brauche hier genauere Angaben, was das Programm tun soll.
Bis zum heutigen Tag gab es zum Glück immer genügend Transplantate.

**Comment by chrbusch** [comment]
Erste Version der "Allokationsberichts-WV" läuft stündlich im Serverscript, weiter nach Ostern

**Comment by chrbusch** [comment]
Der "Allokations-Wochenbericht" kann nun in ein PDF exportiert werden, siehe neuer Button rechts oben.

![bildschirmfoto 2018-03-29 um 10 48 38](https://user-images.githubusercontent.com/1241899/38079377-032e68a0-333f-11e8-9bc4-a4a055ab3104.JPG)

**Comment by Toelk-A** [comment]
1) Bitte, wie oben unter Punkt 4 beschrieben **NUR ab Donnerstags 17:00Uhr** die "bestellten" Anforderungen für kommende Woche als Wiedervorlage programmieren. Im Moment bekommen wir bereits Mittwochs Wiedervorlagen für den Status "Bestellt" für die kommende Woche.

2) Wiedervorlagen für die laufende Woche funktionieren und sollen beibehalten werden.

**Comment by Toelk-A** [comment]
Alle Wiedervorlagen, die Transplantate betreffen (positive Befunde, offene Anforderungen, etc.) sollen nur für Dr. Nitschke NIF und KNA sichtbar sein.

MAA und SGC sollen diese Infos nicht bekommen.

**Comment by chrbusch** [comment]
Ich habe bei den mir plausibel erscheinenden WV die Empfängerliste angepasst.
Wenn WVs noch unerwünscht laden, bitte deren ID zu mir (links oben auf der WV-Maske)
Die Änderung betrifft WVs, die AB JETZT erstellt werden
