### ISSUE TITLE
Wiedervorlage Verknüpfung zur Spendermaske funktioniert nicht

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#315]
Hat vor der Umprogrammierung der Wiedervorlagen funktioniert!

-> Wiedervorlage zum Einwilligungsgespräch (Atzt klick Button Freigabe Einwilligungsgespräch"-> Koordinator erhält Wiedervorlage-> bei Klick auf "Go" erscheint folgende Abbildung:

![image](https://user-images.githubusercontent.com/22314271/37890786-276caa8e-30d2-11e8-84ed-8c0da1743a98.png)

"Button "Zum Spender" ist kein Skript hinterlegt. Hier sollte der Koordinator automatisch zur entsprechenden Spenderdetailmaske weitergeleitet werden.

**Comment by chrbusch** [comment]
>(Atzt klick Button Freigabe Einwilligungsgespräch"
Wo genau ist dieser Button? Bitte immer Layout angeben und Screenshot.

**Comment by Toelk-A** [comment]
es geht darum, dass die Verknüpfung zwischen Button "Zum Spender" mit den Spenderdetails nicht funktioniert. Dieser Button ist oben abgebildet.

**Comment by chrbusch** [comment]
In Ihrem obigen Beispiel klappt das aber bei mir, ich lande mit Klick auf den breiten Btn beim Spender 4354

**Comment by chrbusch** [comment]
..und die erbetenen Detailinfos betreffen den
"Button Freigabe Einwilligungsgespräch"

**Comment by Toelk-A** [comment]
auch hier funktioniert die Weiterleitung nicht:
![image](https://user-images.githubusercontent.com/22314271/37895923-ec860670-30e2-11e8-93a1-8b287b76c286.png)

**Comment by chrbusch** [comment]
um zu prüfen, brauche ich nach wie vor die Info, wo genau der
"Button Freigabe Einwilligungsgespräch"
geklikt wird, bitte screenshot dazu senden

Bei mir hat auch der obige Fall sofort geklappt, also mit IHREM WV-Datensatz

**Comment by Toelk-A** [comment]
Bei den Kollegen funktioniert es auch. Es scheint an meinem Account zu liegen...

**Comment by chrbusch** [comment]
Int. Bem: Btn ist "Arzt: Freigabe Einwilligungsgespräch" r.u. auf SpdDetails, der ist sichtbar IFF noch nicht geklickt
