### ISSUE TITLE
Export XLS-File 2 weitere Spalten einfügen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#316]
Statistik wird folgendermaßen aus Ornella ausgeladen:

Spenderdaten -> Button Letzte Spender -> Vormonat ->Alle -> Datei -> Datensätze exportieren -> XLS File

zusätzlich zu den bereits vorhandenen Spalten benötigen wir zwei weitere Spalten:

-	Entnahmedatum (Prozesschritte -> Entnahmebericht OG)
-	Entnahmezeit (Prozesschritte -> Entnahmebericht OG)

![image](https://user-images.githubusercontent.com/22314271/38255001-f7e8464e-375a-11e8-86be-a2442476eba5.png)

**Comment by chrbusch** [comment]
Oben rechts auf der Spenderliste ist ein neuer Button <XLS-Export>
Da Sie Klartextnamen mit exportieren möchten: Soll das jeder dürfen?

**Comment by chrbusch** [comment]
Da nun ein Exportscript für Spenderdaten zur Verfügung steht, kann dieses leicht dupliziert und modifiziert werden, falls Sie weitere Exportwünsche haben.

**Comment by Toelk-A** [comment]
Die gewünschten oben beschriebenen Felder sind NICHT im Export vorhanden!!!

[Spender_ExportC_180416120415.xlsX](https://github.com/chrbusch/GTM-V/files/1914789/Spender_ExportC_180416120415.xlsX)

**Comment by chrbusch** [comment]
Ich habe Dr. Nitschke davon überzeugt, dass diese Forderung nicht sinnvoll ist, da es mehrere Entnahmezeitpunkte pro Spender geben kann.
Wir überarbeiten gerade zusammen die Exporte.
