### ISSUE TITLE
Rechnung erstellen - stornieren - Gutschrift erstellen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#318]
Abrechnung von Transplantaten mittels Button "Allokation" -> "Transplantatliste" -> Suche nach Transplantaten mit Status "zu berechnen" -> Button "Passende Transplantate abrechnen"

-	1. Schritt, ich schreibe eine Rechnung -> **bereits programmiert**
-	2. Schritt, ich storniere diese Rechnung (Hier kann ich aber keine Gutschrift) drucken -> **bitte programmieren**

Hinweis: Rechnungen und Gutschriften müssen fortlaufend nummeriert sein, unveränderlich!!!! Eine bereits gedruckte Rechnung darf nicht verändert werden können.
Bsp.
2018-0844 Ausgangsrechnung soll storniert werden
Storno sollte dann GU 2018-001 haben
Neue Rechnung bekommt dann eine neue fortl. Nr. 2018-0845

Gutschriften müssen, wie Rechnungen gedruckt werden können (müssen 10 Jahre abgelegt werden)

Beachtung:
**Transplantate, die in einer Rechnung storniert werden, müssen wieder auf Status „zu berechnen“ gesetzt werden.**

**Comment by chrbusch** [comment]
Ich nehme an, für die GU sollen die Positionen der Ursprungs-Rng dupliziert werden.
Haben diese dann negative Preise?

**Comment by chrbusch** [comment]
Wie sollen Vor- und Nachtext lauten?
Am besten wäre: Zu einer echten Rng die gewünschte Gutschrift EXAKT vom Wortlaut und den Zahlen her (aber ohne Design) in WORD verfassen und mir senden.

**Comment by Toelk-A** [comment]
Anbei ein Beispiel Worddokument

[Beschriftung Felder Beispiel Gutschrift Ticket 318.pdf](https://github.com/chrbusch/GTM-V/files/1960098/Beschriftung.Felder.Beispiel.Gutschrift.Ticket.318.pdf)

**Comment by chrbusch** [comment]
Ich benötige, wie mit Frau Schmalfuß-Grioß besprochen, für _jedes_ Feld auf der Eingabemaske die Angabe, ob und wie es sich ändert.
