### ISSUE TITLE
Liste offene Rechnungen - Mehrfachauswahl

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#319]
Button "Buchhaltung" -> Button "Liste Rechnungen"
-	Liste Rechnungen (Fällige und offene) 

Eine Markierung (Mehrfachauswahl) generieren, so dass mehrere Rechnungen markiert werden können und gleichzeitig den Status z.B. bezahlt oder mahnen erhalten.

**Comment by chrbusch** [comment]
Als erste Erleichterung habe ich den Button "Bez." mit auf die LISTE der Rechnungen gelegt, man kann also dort direkt eine Zeile anklicken und muss nicht zur Detailmaske wechseln

![bildschirmfoto 2018-04-05 um 09 37 44](https://user-images.githubusercontent.com/1241899/38352904-02263b56-38b5-11e8-924e-8270f186b580.JPG)

**Comment by chrbusch** [comment]
Ferner kann man mit dem zweiten Button "<Nur" die Fundmenge einschränken auf einen Empfänger - zB wenn dieser gerade etliche Rng beglichen hat

![bildschirmfoto 2018-04-05 um 09 38 39](https://user-images.githubusercontent.com/1241899/38352938-27ac764c-38b5-11e8-95ef-3d748104c903.JPG)

**Comment by Toelk-A** [comment]
bitte hierzu anrufen, es geht lediglich um das Programmieren von "Ankreuzfeldern"

**Comment by chrbusch** [comment]
Es gibt nun neue Buttons und Funktionen, ABER bitte zunächst nur mit mir am Telefon testen!!!

![bildschirmfoto 2018-04-06 um 15 10 31](https://user-images.githubusercontent.com/1241899/38422986-e0b769c4-39ac-11e8-9924-8a5af1393139.JPG)

**Comment by chrbusch** [comment]
Wer kann mit mir die neuen (nun grünen) Buttons testen?

**Comment by Toelk-A** [comment]
erledigt
