### ISSUE TITLE
Spendermeldung Abschnitt "Wiederspruch gg. Spende" 

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#32]
Im Moment ist es nur möglich ein Datum aber keine Uhrzeit des Gespräches einzutragen. Bitte zusätzliches Feld für Dokumentation der Uhrzeit einfügen.

 
![image](https://cloud.githubusercontent.com/assets/22314271/19800798/baee3dd8-9cfc-11e6-8fb8-fe13c0d6d727.png)

**Comment by chrbusch** [comment]
Dieser Punkt ist ,.E. erledigt, ggfs. bitte issue schliessen
