### ISSUE TITLE
Stundenreport geringfügig beschäftigter Mitarbeiter erstellen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#320]
![image](https://user-images.githubusercontent.com/22314271/38303061-30b95d64-3805-11e8-91bb-713f81f1569d.png)

1) Geringfügig beschäftigte Mitarbeiter erhalten keine Passivstunden, keine Zuschläge, etc.
2) es sollen nur die tatsächlich geleisteten Stunden im Stundenreport abgebildet werden. Da der Beschäftigte nicht mindestens 45 h/Monat arbeiten muss, darf es keine "Minusstunden" im Report geben.
3) Folgende Daten/Zahlen sollen abgebildet werden:
3.1) Monat und Mitarbeitername (oben stehend)
3.2) Datum  Beginn  Ende     Summe / Tag   
3.3) Summe / Monat in Stunden

Wenn eine Aushilfe mehr als 45 Stunden geleistet hat, sollte gefragt werden, ob die Mehrstunden bezahlt werden oder in den nächsten Monat übertragen werden sollen.

**Comment by chrbusch** [comment]
Bitte prüfen, ob die gezeigten Daten (Karnatz / März 2018) korrekt sind und die Darstellung so wie erwünscht

![bildschirmfoto 2018-04-04 um 14 25 59](https://user-images.githubusercontent.com/1241899/38307479-2b512122-3814-11e8-968a-34db07aa0a02.JPG)

**Comment by chrbusch** [comment]
Rohversion für einen einzelnen MA läuft, bitte den neuen Button testen

![bildschirmfoto 2018-04-04 um 14 36 47](https://user-images.githubusercontent.com/1241899/38307916-aa8ff67e-3815-11e8-9c5a-c955b8fe004d.JPG)

**Comment by Toelk-A** [comment]
1) die gezeigten Daten sind korrekt **- erledigt**

2) Darstellung ist wie gewünscht **- erledigt**

3) Bitte "Summe" in "Summe ausgezahlt" ändern , bei Übertrag (siehe Punkt 5), Anzahl der übertragenden Stunden abbilden als "Summe Übertrag"

![image](https://user-images.githubusercontent.com/22314271/38356124-2b3c50f2-38bf-11e8-9381-dd200133a011.png)

4) WENN der geringfügig beschäftigte Mitarbeiter >45h gearbeitet hat, so soll, wie oben bereits beschrieben, gefragt werden, ob die "Mehrstunden" bezahlt werden (Eingabe der Anzahl der auszuzahlenden Stunden) oder die Differenz in den nächsten Monat übertragen werden sollen. **-> bitte programmieren**

![image](https://user-images.githubusercontent.com/22314271/38356050-f22c52bc-38be-11e8-9327-0d2943c1b0c5.png)

5) Kommt es zu einem Übertrag der Stunden aus dem Vormonat, so soll dieser Übertrag in der ersten Zeile des Reportes abgebildet werden als "Übertrag" und in der Spalte Stunden -> **bitte programmieren**

**Comment by chrbusch** [comment]
m.E.
 alles fertig, bitte das Script/den Button testen

**Comment by Toelk-A** [comment]
erledigt
