### ISSUE TITLE
User Schmalfuß-Gross aus Wiedervorlagen Allokation/Bank entfernen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#321]
Bitte Frau Schmalfuß -Gross aus dem Verteiler der Wiedervorlagen der GBM-V entfernen (Allokation und Status Verworfen). Sie sollte **nie** in diesen Verteiler aufgenommen werden. Dies bitte nicht berechnen.

![schmalfuss gross](https://user-images.githubusercontent.com/22314271/38355082-1dbae63a-38bc-11e8-802c-e83fc7f78ec8.png)

**Comment by chrbusch** [comment]
Kostenfrei als Bugfix behoben.
Bitte künftig bei jedem Wiedervorlage-Wunsch explizit die Empfänger nennen.
