### ISSUE TITLE
GBMV/ Bank Avis Handynummer des Entnehmers hinzufügen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#322]
OG Entnahmebericht -> Button "Bank-Avis per Mail"

Bitte die Handynummer des Entnehmers in die Avis-Mail einfügen. Die Handynummer des Entnahmers ist auf der Maske "Mitarbeiter Details" hinterlegt. 

![image](https://user-images.githubusercontent.com/22314271/38371380-931f86d0-38ec-11e8-908d-c5cb6de2e345.png)

**Comment by chrbusch** [comment]
Ich denke nicht, dass die Handynummern bereits erfasst sind!
Das bisherige Feld "Telefon-Durchwahl" habe ich umbenannt in "Festnetz" und dazu ein Feld "MobilNr" erstellt. Bei den wenigen Mitarbeitern, die eine MobilNr im Durchwahlfeld haben, habe ich diese in das neue Feld übertragen.
Das Mobil-Feld hole ich nun in den Bank-Avis; hierfür relevante Mitarb. müssten dann in der Usermaske ihre Handynummern eintragen

**Comment by Toelk-A** [comment]
erledigt
