### ISSUE TITLE
PDF Monatsstatistik in Spenderakte abgelegt

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#323]
Spenderdetails- Reiter Dokumente:

Hier sind die PDF´s zur Monatsstatistik abgelegt.  Wo genau kommen diese auf einmal her? Diese PDFs sollen hier nicht hinterlegt werden.

![image](https://user-images.githubusercontent.com/22314271/38619835-5596afea-3d9d-11e8-90d8-3d27817fa0ce.png)

**Comment by chrbusch** [comment]
Erl., bitte testen. (Blöder Fehler, kostenfreier bugfix)

**Comment by Toelk-A** [comment]
Danke
