### ISSUE TITLE
GBMV/ Transplantatdetails  - Reiter umbenennen/erstellen Bereich Herstellung

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#324]
Ähnlich der Reiter im Bereich "Spende" sollen nun die Reiter im Bereich "Herstellung" angepasst werden:
Hierbei soll die folgende Reihenfolge erstellt werden:

## 1 Transplantatdetails
Reiter nur umbennen

## 2 Prozessschritte 
A) hier bitte nur die Prozessschritte aus dem Bereich Herstellung (H) und Allokation (A) abbilden. Im Moment sind diese Prozesschritte nur im Bereich Spende hinterlegt. Die Mitarbeiter der GBM-V sollen ihre Prozesschritte im Bereich Transplantatdetails sehen.

![image](https://user-images.githubusercontent.com/22314271/38678008-2d8da2d8-3e60-11e8-8d5a-ca5ccb0de540.png)

## 3 Akte
Hier bitte ähnlich wie im Bereich der Spende verfahren... genaue Infos zum Reiter "Akte" folgen... 

## 4 Dokumente + PDF
Reiter bleibt bestehen. Hier sollen dann ähnlich wie im Bereich Spende die "PDF´s" der Prozesschritte hinterlegt werden bzw. Befunde etc. in Ornella hochgeladen werden können.
  
## 5 Herstellung
bleibt wie er ist

## 6 ähnliche Transplantate 
bleibt wie er ist

**Comment by chrbusch** [comment]
Ad 1) Reiter umbenannt
Ad 2) neuen Reiter für Prozessschritte erstellt; Auswahl der Anzeige muss noch diskutiert werden, momentan alle zu dieser Transpl.-ID

**Comment by Toelk-A** [comment]
## 2 Prozessschritte
noch nicht vollständig programmiert -> Buttons fehlen
![image](https://user-images.githubusercontent.com/22314271/39626324-af9c8878-4fa1-11e8-9d14-944c213d5ddc.png)

## 3 Akte
noch nicht programmiert

**Comment by chrbusch** [comment]
Die Buttons erscheinen nun.
-
Eine Akte für ein Transplantat gibt es noch gar nicht! Hier müssen wir genau diskutieren, welche Dokumente dort hinein gehören, denn div. Dokumente beziehen sich ja potentiell auf mehrere Transplantate - weil sie als Basis ein SpdGewebe oder SpdPräparat haben.

**Comment by Toelk-A** [comment]
Ähnlich dem Reiter "Akte" in den Spenderdaten, können im Reiter AKte bei den Transplantatdetails die Statuswechsel und der AudioLOG abgebildet werden:

![image](https://user-images.githubusercontent.com/22314271/40160945-8a193714-59af-11e8-948c-bd73fbfbc4bf.png)


![image](https://user-images.githubusercontent.com/22314271/40160987-a8a975e0-59af-11e8-9b99-4cbcfc18ed14.png)


![image](https://user-images.githubusercontent.com/22314271/40161045-ceeb5f48-59af-11e8-84e7-9c4812d55534.png)

Audio LOG Button ist nicht mehr vorhanden?!

**Comment by chrbusch** [comment]
Das Modul heißt "Audit Log"
Welche Rollen sollen diesen Button sehen?

**Comment by chrbusch** [comment]
Ich denke, dieses Ticket können Sie schliessen.

**Comment by Toelk-A** [comment]
Reiter "Akte" ist noch nicht programmiert.
