### ISSUE TITLE
GBMV/ Dokument Herstellungsprotokoll Teil 1

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#325]
Im Moment ist das Herstellungsprotokoll über mehrere Buttons zu öffnen:

1) Transplantatdetails- Reiter Herstellung - Button 
![image](https://user-images.githubusercontent.com/22314271/38678441-4ec952b6-3e61-11e8-81f9-b3cb91134132.png)
-> hier wird das Herstellungsprotokoll vollständig erstellt, allerdings müssen noch einige kleine Programmierungen vorgenommen werden.

2) Spenderdetails - Prozesschritte - 
![image](https://user-images.githubusercontent.com/22314271/38678623-e1dff870-3e61-11e8-8763-975f2b587002.png)

-> Herstellungsprotokoll ist hier unvollständig

Bitte folgende Programmierungen vornehmen:

3) Das Herstellungsprotokoll soll in Zukunft nur in den Prozessschritten geöffnet werden können. d.h. dort muss das VOLLSTÄNDIGE Herstellungsprotokoll, das im Moment unter dem 1. der beiden oben beschriebenen Buttons hinterlegt ist geöffnet werden.

4) PDF Ausgabe Herstellungsprotokoll:  Bankinterne Nummer im Feld "Transplantatkennummer" des Dokumentes hinterlegen. Achtung für die rechte und linke Seite gibt es je 1 Herstellungsprotokoll.

![image](https://user-images.githubusercontent.com/22314271/38678942-c0d65e7a-3e62-11e8-8b00-64b90bca515d.png)

5) PDF Ausgabe Herstellungsprotokoll: Bitte den Namen "Carmen Hohmann" im Feld "Erstellt" hinterlegen.

![image](https://user-images.githubusercontent.com/22314271/38679080-185bab78-3e63-11e8-98e4-d0af89463d92.png)

**Comment by chrbusch** [comment]
Bitte nennen Sie einen Spender, der die hier zu druckenden Daten für beide Hornhäute enthält

**Comment by Toelk-A** [comment]
Spender ID 4475

**Comment by chrbusch** [comment]
3) Das Herstellungsprotokoll soll in Zukunft nur in den Prozessschritten geöffnet werden können. d.h. dort muss das VOLLSTÄNDIGE Herstellungsprotokoll...

Dies bitte jetzt testen.

**Comment by Toelk-A** [comment]
Bitte zu Punkt 1) den Button löschen. Dieser ist nicht mehr notwendig da das Protokoll über die Prozesschritte geöffnet werden soll.

Punkt 5) ist noch nicht programmiert

**Comment by chrbusch** [comment]
Erledigt: Bitte zu Punkte 1) den Button löschen.

**Comment by chrbusch** [comment]
Transplantat ID 2260 - fehlende Einzelpositionen.pdf
Meines Erachtens nun auch komplett, das HerstProt zeigt bei mir 32 Pos.

Erledigt: Artikel mit derselben Chargennummer nicht doppelt abbilden

**Comment by Toelk-A** [comment]
Die aufgelisteten Artikel fehlen

![herstellungsprotokoll teil i nachtrag](https://user-images.githubusercontent.com/22314271/41029116-2bc68c80-697b-11e8-9c73-aaaaf622b2df.jpeg)

**Comment by Toelk-A** [comment]
![nachtrag herstellungsprotokoll teil i](https://user-images.githubusercontent.com/22314271/41029207-64d9b15a-697b-11e8-9735-cb6bd6df8db1.jpeg)

**Comment by Toelk-A** [comment]
Fehlende Lot-Nummer

![herstellungsprotokoll teil 1 nachtrag 2](https://user-images.githubusercontent.com/22314271/41034520-210958fe-698a-11e8-807b-9d0b77638e89.jpeg)

**Comment by chrbusch** [comment]
Hier handelt es sich um einen Datenfehler. Die ArtikelCharge 587 der "Kulturflaschen 25 cm2, 50 ml" wurde gelöscht!
Das Bild zeigt die Lücke in der ID.
**Ich habe manuell eine Charge dieser ID angelegt, kenne aber nicht alle Wette, die dort hinein müssen- v.a. nicht Charge + MHD**
Bitte hierzu anrufen.

![bildschirmfoto 2018-06-11 um 07 38 49](https://user-images.githubusercontent.com/1241899/41214231-80394956-6d4a-11e8-9e2c-8b7b1dd98649.JPG)

**Comment by Toelk-A** [comment]
Daten sind nachgetragen:

![image](https://user-images.githubusercontent.com/22314271/41349762-3b47b1e8-6f11-11e8-9c05-20ec7f24449e.png)

**Comment by Toelk-A** [comment]
Frau Schröder kontrollierte das Herstellungsprotokoll Teil I. Es scheint vollständig zu sein und zu funktionieren. Unser QM wird das Dokument nun prüfen und uns mitteilen ob es freigegeben werden kann.

**Comment by Toelk-A** [comment]
**1) Bitte die Versionsnummer ändern.**

![image](https://user-images.githubusercontent.com/22314271/42154064-23298176-7de5-11e8-9cdf-ea7aec842a8c.png)


**2) Bitte noch die folgenden Felder einfügen:**

![image](https://user-images.githubusercontent.com/22314271/42154153-50dbbcd8-7de5-11e8-8156-498ed77d3cc8.png)

**Comment by chrbusch** [comment]
1) ist erledigt.

2) verstehe ich nicht: Dieses Formular listet alle dem Transplantat zugeordneten Artikel. 
"Felder" für spezielle Artikel gibt es gar nicht.
Ggfs. hierzu bitte anrufen

**Comment by Toelk-A** [comment]
## verstehe ich nicht: Dieses Formular listet alle dem Transplantat zugeordneten Artikel.
Zur Präparation der Kornea wird ein sog. "Sterilsieb" = Präparationsinstrument sowie ein Spülset verwendet. Da beides mehrfach verwendbare Artikel sind, müssen diese in der Klinik sterilisiert werden und bekommen einen "Aufkleber steril inkl. Mindeshaltbarkeitsdatum und LOT). Dieser Aufkleber muss ebenfalls im Herstellprotokoll 1 verwendet werden, da das Material in direktem Kontakt mit der Kornea stand. In Folge dessen benötigen wir die o.g. Spalten. Hierzu muss nichts programmiert sein. Sie sollen "nur" physisch auf dem Dokument vorhanden sein.

**Comment by chrbusch** [comment]
Ganz konkret: Soll ich oben auf Seite 1 nur Beschriftungen addieren und freien Raum, auf den ein Aufkleber physisch von Hand geklebt wird?

**Comment by chrbusch** [comment]
Das habe ich jetzt umgesetzt, bitte testen
![bildschirmfoto 2018-08-08 um 12 37 40](https://user-images.githubusercontent.com/1241899/43832492-e15759ea-9b07-11e8-9da0-ff110bee8ec4.JPG)

**Comment by Toelk-A** [comment]
Dokument wird durch unser QM geprüft...

**Comment by Toelk-A** [comment]
Bitte die folgenden Nacharbeiten durchführen

[Nacharbeiten Herstellungsprotokoll OG Teil 1_QM 1.pdf](https://github.com/chrbusch/GTM-V/files/2327104/Nacharbeiten.Herstellungsprotokoll.OG.Teil.1_QM.1.pdf)

**Comment by chrbusch** [comment]
Meines Erachtens sinddie Grafik optimiert und die fehlenden Objekte Programmiert, bitte testen

**Comment by Toelk-A** [comment]
Bitte bearbeiten

[Herstellungsprotokoll Teil 1 nachtrag _ QM 2.pdf](https://github.com/chrbusch/GTM-V/files/2327747/Herstellungsprotokoll.Teil.1.nachtrag._.QM.2.pdf)

**Comment by chrbusch** [comment]
Erledigt

**Comment by Toelk-A** [comment]
Noch nicht erledigt...

[Herstellungsprotokoll 1 Nacharbeiten_ QM Teil 3.pdf](https://github.com/chrbusch/GTM-V/files/2332083/Herstellungsprotokoll.1.Nacharbeiten_.QM.Teil.3.pdf)

**Comment by chrbusch** [comment]
Ich habe noch einmal ein paar Pixel gelöscht oder verschoben, schlage jetzt aber vor, dass wir uns um die von Dr. Nitschke dringend benötigten anderen Dokumente kümmern.

**Comment by chrbusch** [comment]
Ich habe ja auch Ihre letzten Wünsche gestern gleich bearbeitet! Ist das jetzt OK so?

**Comment by Toelk-A** [comment]
QM ist bei der Kontrolle.. denke nächste Woche geht es hier weiter...

**Comment by Toelk-A** [comment]
Bitte Korrekturen einarbeiten
[Githubticket 325_ Nachtrag QM _ 4.pdf](https://github.com/chrbusch/GTM-V/files/2356077/Githubticket.325_.Nachtrag.QM._.4.pdf)

**Comment by chrbusch** [comment]
Erledigt

**Comment by Toelk-A** [comment]
Datumsfeld nicht auswählbar

Fehlermeldung bei digitaler Unterschrift.

Bitte beides fertigprogrammieren

![image](https://user-images.githubusercontent.com/22314271/45215049-70af9e80-b29c-11e8-9ae3-0965f9d45f1f.png)

**Comment by chrbusch** [comment]
Für meine Tests wäre es gut, immer das Transplantat anzugeben.
m.E. klappt es jetzt

**Comment by chrbusch** [comment]
Beides funktioniert bei mir ohne Programmänderung.
Per TeamViewer auf Ihrem Platz ansehen?

![bildschirmfoto 2018-09-18 um 08 45 40](https://user-images.githubusercontent.com/1241899/45669108-3c02d900-bb1f-11e8-8f05-3d1f6d5f4e1a.JPG)

**Comment by Toelk-A** [comment]
Es funktioniert nach wie vor nicht wenn man über Prozesschritte geht. Transplantat ID 2750

![image](https://user-images.githubusercontent.com/22314271/45669342-12967d00-bb20-11e8-9d93-729f17c44296.png)

**Comment by chrbusch** [comment]
Problem verstanden; bitte erneut testen

**Comment by Toelk-A** [comment]
Freigabe durch Qm erfolgt
