### ISSUE TITLE
Koordinator Napieralski darf nicht als AAP unterschreiben können

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#326]
Mitarbeiter Bogdan Napieralski darf nicht, wie auch alle anderen Koordinatoren nicht, in den Feldern der AAP unterschreiben können:

Spender ID 4558
OG Entnahmebericht
![image](https://user-images.githubusercontent.com/22314271/38737130-9093a016-3f2e-11e8-9156-1b83a222a7ce.png)

**Comment by chrbusch** [comment]
m.E. erledigt, bitte erneut testen

**Comment by chrbusch** [comment]
Ist dieser Eintrag heute erfolgt?  Erscheint Herr N. in der Auswahl?? Bitte Screenshot davon senden, bei mir erscheinen nur die Ärzte zur Auswahl:

![bildschirmfoto 2018-04-18 um 14 54 50](https://user-images.githubusercontent.com/1241899/38933133-77ba21e4-4318-11e8-84ed-8246ab52953e.JPG)

Klikt Herr N auf das Feld ganz unten, oder wird evt. der Wert aus einem "anderen Klick" fälschlich hierhin übertragen?

**Comment by chrbusch** [comment]
Habe gerade noch einmal geprüft und denke jetzt, dass ich bislang das Feld in der Mitte prüfe,; dabei geht es wohl um das Feld ganz rechts?
Bitte _immer_ genau sagen , welches Objekt zuletzt geklickt wurde.
Kann Herr N. sich jetzt noch eintragen?

**Comment by Toelk-A** [comment]
erledigt
