### ISSUE TITLE
Spenderdetails - Dokumente + PDF

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#327]
Hier wurde die Transplantatliste abgelegt. Dieser hat hier nichts zu suchen. Dieser Speicherort wurde auch nicht vereinbart.
Bitte ändern

![image](https://user-images.githubusercontent.com/22314271/38794348-185659c6-4155-11e8-8add-6bbb058bbfd7.png)

**Comment by chrbusch** [comment]
Ich denke, das war ein einmaliges Artefakt während der Entwicklung? Habe diesen Eintrag gelöscht un dzZ gibt es keinen solchen mehr
