### ISSUE TITLE
Personalplanung- persönlicher Kalender- Arbeitszeit erfassen -> Fehlprogrammierung Pause

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#328]
Personalplanung- persönlicher Kalender- Arbeitszeit erfassen

Nach Eingabe der folgenden Zeiten:

![image](https://user-images.githubusercontent.com/22314271/38913369-aa53bb1c-42da-11e8-9913-3720935638b0.png)

Button "Anordnung" erscheint folgende Fehlermeldung, obwohl **31 Minuten Pause** angegeben wurden:

![image](https://user-images.githubusercontent.com/22314271/38913347-894e41bc-42da-11e8-8fab-45c33fba7af2.png)

**Comment by chrbusch** [comment]
Ich meine, die Prüfung lief korrekt, nur der Warntext war falsch. Dies ist korrigiert

**Comment by chrbusch** [comment]
![bildschirmfoto 2018-04-24 um 08 42 11](https://user-images.githubusercontent.com/1241899/39170336-69a34004-479b-11e8-8315-cc6050637cd1.JPG)
![bildschirmfoto 2018-04-24 um 08 41 59](https://user-images.githubusercontent.com/1241899/39170337-69bd904e-479b-11e8-8aea-4036ad6a309b.JPG)

**Comment by Toelk-A** [comment]
Es gibt nach wie vor Probleme mit der Arbeitszeitendokumentation:

08:00 -16:30 + 30min entspricht einer Arbeitszeit von 8h NICHT 08h30min

### Im folgenden Beispiel:

 7:20 bis 16:50 + 30 min. Pause

hat der Mitarbeiter genau 9h gearbeitet und 30min Pause gemacht, die Arbeitszeit beträgt also nur **9h** d.h. es sind nur 30 Minuten Pause zu dokumentieren und nicht 45 min.

Bitte noch einmal Programmierung prüfen



<img width="1501" alt="Doku Arbeiszeiten jpg" src="https://user-images.githubusercontent.com/22314271/66208374-3558ec80-e6b5-11e9-9681-3375b1572e09.png">

**Comment by chrbusch** [comment]
Mir war nicht bewusst, dass die Arbeitszeit OHNE Pause Grundlage für die Pausendauer ist; dies habe ich geändert (bug fix)

**Comment by Toelk-A** [comment]
Es darf bei einer reinen Arbeitszeit von bis zu 8h + 59 min eine 30min Pause dokumentiert werden. Arbeite ich allerdings reine Arbeitszeit 9h MUSS nach 45min Pause gefragt werden:

![image](https://user-images.githubusercontent.com/22314271/66651767-2d102c80-ec34-11e9-8b01-02dbd3efa74f.png)


![image](https://user-images.githubusercontent.com/22314271/66651794-4022fc80-ec34-11e9-82f9-6c57d40cf938.png)



Richtig programmiert ist bereits eine reine Arbeitszeit von 9h 1min -> 45 min

**Comment by chrbusch** [comment]
OK, da stand "...GRÖSSER 9", richtig ist "grösser gleich 9", dies ist nun geändert
