### ISSUE TITLE
GBMV/ Exporte

### ISSUE THREAD

**Issue by Nitschke-FP** [chrbusch/GTM-V#329]
A) beim "ExportE_Allokationsstatistik_........" bitte folgende Felder hinzufügen:
d_Datum_Versand
GewAnfPos.GewAnf::q_AdrGanz_2Zeilen_Top_Besteller

B) folgende Felder löschen:
k_Rec_nNT
k_Pat_NuVName_Alter
k_LayoutTitle
d_TS_WV_Allokation

**Comment by chrbusch** [comment]
Ich bin recht sicher, dass keines dieser Felder IN DEM VON MIR PROGRAMMIERTEN Exportscript vorkommt. Das sind m.E. noch Artefakte des bis vorgestern frei gegebenen Exportes über Datei-Menü/Datensätze exportieren.
Andernfalls bitte genau beschreiben, wo Sie den Exportbutton geklickt haben und die Exportdatei per Email senden.

**Comment by chrbusch** [comment]
Mein ExportE liefert diese Felder:

![bildschirmfoto 2018-04-18 um 14 16 25](https://user-images.githubusercontent.com/1241899/38931338-24661534-4313-11e8-9c0f-2ac4301f669e.JPG)
