### ISSUE TITLE
PDF Ausgabe auf Desktop 

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#33]
bitte PDFs nicht automatisch auf dem Desktop ablegen.

Ist es möglich alle zu einem Spender zugehörigen PDFS in einem "Spenderordner" pro Patient auf dem Server abzulegen?

**Comment by chrbusch** [comment]
Das können wir server-basiert machen, sobald Ihr Server steht; in Rostock besprechen
