### ISSUE TITLE
GBMV/Aufgabenliste Medienwechsel&Sterilkontrolle

### ISSUE THREAD

**Issue by chrbusch** [chrbusch/GTM-V#331]
Bitte einen neuen Testspender anlegen und beide Hornhäute als Transplantate.
Ich bin dabei, den Prozesschritten ein Solldatum zu verpassen, das dann u.a. für Medienwechsel usw benutzt werden kann.

**Comment by chrbusch** [comment]
Bild zeigt das neue Feld Solldatum, das nur dann erscheint, wenn der entspr. BASIS-Prozesschritt entspr. markiert wurde.
a) Ist die letzte Zeile "EIngangskontrolle" identisch zu der diskutierten "Sterilkontrolle EIngang"?

b) Sollten wir die "Lagerung im Transportmedium" auch zu einem Prozessschritt mit Solldatum machen?

![bildschirmfoto 2018-04-23 um 08 14 44](https://user-images.githubusercontent.com/1241899/39109775-a04cc148-46ce-11e8-8ce0-1d0701190360.JPG)

**Comment by chrbusch** [comment]
Hauptmenü, Thema Herstellung, neuer Button "Aufgaben Bank komm. Woche"
Bevor das funktionieren kann, müssen aber für die oben rosa gezeigten Felder Werte eingetragen werden!

**Comment by Toelk-A** [comment]
Hier bitte nicht weiterarbeiten... bis ich mich melde

**Comment by Toelk-A** [comment]
Ich finde die Programmierung des "Solldatums" und die zusätzlichen Prozesschritte nicht sinnvoll, da wir bereits die Felder "Solldatum" besitzen und diese auch später automatisch in die verschiedenen Protokolle übernommen werden sollen.

## 1) Solldatum 
Bitte definieren Sie die von uns gemeinsam in Hamburg angelegten Felder als "Solldatum":

![image](https://user-images.githubusercontent.com/22314271/39346653-8362e91c-49ef-11e8-807e-d21d0d4f4367.png)


## 2) Erstellung von Listen, die im Routinekalender abgebildet werden sollen
Jede Liste bekommt ein separates Githubticket. Ticketnummern werden hier noch nachgetragen.

Anhand dieser manuell eingetragenen Daten sollen die Listen für den Routinekalender erstellt werden:

A) Liste "Sterilkontrollen Eingang"
-> siehe Ticket #334 

B) Liste "Sterilkontrollen Ausgang"

C) Liste "Mediumwechsel 1"

D) Liste "Mediumwechsel 2"

E) Liste "Sterilitätsprüfung"
-> entspricht 3.4.3.5.1 F Herstellungsprotokoll OG Teil 2 (Präparation und mikrobiologisches Monitoring) Seite 2

F) Liste "Sterilitätsprüfung Rückstellproben"
-> entspricht 3.4.3.5.1 F Herstellungsprotokoll OG Teil 2 (Präparation und mikrobiologisches Monitoring) Seite 3

**Comment by chrbusch** [comment]
Für die "Sterilitätsprüfung Rückstellproben" gibt es nun auch eine Eintragsoption "Datum Soll"

![bildschirmfoto 2018-05-02 um 09 13 47](https://user-images.githubusercontent.com/1241899/39510204-315eab4e-4de9-11e8-9956-c3b45bcf8970.JPG)

**Comment by chrbusch** [comment]
Bitte jetzt den Button >Liste testen: Er soll eine Aufgabe für ein Datum als Liste zeigen

![bildschirmfoto 2018-05-02 um 09 47 11](https://user-images.githubusercontent.com/1241899/39511468-db8789b6-4ded-11e8-9abd-65469896bf55.JPG)

**Comment by Toelk-A** [comment]
Der Aufbau der Liste wird in der kommenden Woche durch die Bankmitarbeiterinnen geprüft.

**Comment by Toelk-A** [comment]
Die Liste ist von den Mitarbeiterinnen der Bank abgesegnet. Es kann weiter programmiert werden.
