### ISSUE TITLE
Strg+C UND Strg + V   Funktion bitte in Ornella wieder aktivieren

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#332]
Aus irgendeinem Grund kann in Ornella nichts mehr "kopiert und eingefügt" werden.

Bitte aktivieren Sie diese Funktion wieder, da es unnötige Fehleingaben verhindert.

Generell soll die Kopierfunktion im Gesamten Spendebereich, Herstellungs- und Allokationsbereich sowie Adressen verwendbar sein.

**Comment by chrbusch** [comment]
Das ist aus Sicht des neuen Datenschutzes sehr kritisch zu sehen - man kann dann unkontrolliert Daten entnehmen und v.a. Texte aus MS Word etc mit Sonderzeichen einfügen, die Filemaker nicht versteht.
Ich denke, wir müssen alle Stellen, wo das benötigt wird, mit einem kleinen Script lösen, welches genau diese eine Aktion ausführt.
Bitte nennen Sie mir ein ganz konkretes Bsp. dafür, wo Sie copy&paste benutzen.

Wer ist Ansprechpartner für mich in Sachen Datenschutz, Herr Peter?
