### ISSUE TITLE
Mitteilung Beauftragung virologische Diagnostik von GBM-V an GTM-V -> Ergebnismitteilung GTM-V an GBM-V

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#334]
Button Herstellung -> Herstellungs-Liste 

Diese Liste ist sowohl von der GTM-V als auch GBM-V einsehbar. In dieser Liste sollen 2 zusätzliche Spalten erstellt werden:

![image](https://user-images.githubusercontent.com/22314271/39178148-54b31528-47b1-11e8-9e46-e9638082fad7.png)

## Spalte 1:
1A) Benennung der Spalte  "GBM-V  - Virologie beauftragen" 

1B) Programmierung eines Ja/Nein Knopfes Transplantationsdetails im Bereich Herstellung - gelb markiert (ähnlich der Pseudophakie - rot markiert) mit Benennung "Virologie beauftragen"
![image](https://user-images.githubusercontent.com/22314271/39178305-a5421106-47b1-11e8-9de2-6a1c50ceb00f.png)

1C)  Der Status des unter 1B programmierten Knopfes, soll dann in der Spalte 1 mit folgendem Farbcode abgebildet werden: "Ja" = grün hinterlegt und "Nein" = rot hinterlegt

1D) Dieser programmierte Knopf darf nur durch NIF/KNA änderbar sein

## Spalte 2:

2A) Benennung der Spalte  "GTM-V  - Status Virologie" 

1B) Programmierung eines "Ampelknopfes": rot = "Keine virologische Freigabe", gelb = "virologische Untersuchung veranlasst", grün = "Virologische Freigabe"

1C)  Dieser programmierte Ampelknopf darf nur durch NIF/MAA (VP) änderbar sein

**Comment by Toelk-A** [comment]
Dieses Ticket hat erste Priorität nichts anderes

**Comment by chrbusch** [comment]
Bitte testen Sie jetzt die Buttons/Felder und bitte durchdenken:
Wann ist welcher Button sichtbar bzw. bedienbar?
Darf man etwa die Beauftragung (ja/nein) noch ändern, wenn es schon eine Freigabe gibt?
Damit Sie testen können, erscheint heute nur ein Dialog der Art "Nur für NIF/MAA", aber jeder kann es ändern. Sobald Sie es "abnicken", sperre ich dann die Funktionen für die Unerwünschten

![bildschirmfoto 2018-04-26 um 11 06 35](https://user-images.githubusercontent.com/1241899/39296750-03bb6872-4942-11e8-8846-8b57c16fb384.JPG)

**Comment by chrbusch** [comment]
Sollten wir einen Button haben, der die Transplantate mit beauftragter vir Unt. zeigt, zu denen der Status leer ist?

**Comment by Toelk-A** [comment]
1A) Erledigt

## 1B)Programmierung eines Ja/Nein Knopfes Transplantationsdetails im Bereich Herstellung - gelb markiert (ähnlich der Pseudophakie - rot markiert) mit Benennung "Virologie beauftragen"
-> bitte noch programmieren

## 1C) Der Status des unter 1B programmierten Knopfes, soll dann in der Spalte 1 mit folgendem Farbcode abgebildet werden: "Ja" = grün hinterlegt und "Nein" = rot hinterlegt
-> bitte fertigstellen in Kombi mit 1B

## 1D) Dieser programmierte Knopf darf nur durch NIF/KNA änderbar sein
-> bitte noch programmieren in Kombination mit 1B und 1C

## 2A) Benennung der Spalte "GTM-V - Status Virologie"
erledigt

## 1B) Programmierung eines "Ampelknopfes": rot = "Keine virologische Freigabe", gelb = "virologische Untersuchung veranlasst", grün = "Virologische Freigabe"
-> Ampelbutton vorhanden, bitte noch den zugehörigen gewünschten Text abbilden - keine Abkürzungen

1C) Dieser programmierte Ampelknopf darf nur durch NIF/MAA (VP) änderbar sein
-> bitte programmieren


Anmerkungen zu CBU:

Bitte testen Sie jetzt die Buttons/Felder und bitte durchdenken:

## Wann ist welcher Button sichtbar bzw. bedienbar?
Button GBM-V (noch nicht programmiert!!! siehe 1B) darf nur für NIF/KNA sichtbar und bedienbar sein. -> die Spalte GBM-V (Herstellungsliste) ist nur ein "Spiegelbild" des Ergebnisses zu 1B. Das heißt, in der Herstellungsliste Spalte GBM-V darf das Ergebnis durch Niemanden veränderbar/bedienbar sein ABER für alle sichtbar sein.

Ampelbutton GTM-V (Herstellungsliste Spalte GTM-V) darf nur durch MAA und NIF  bedienbar sein, aber das Ergebnis muss für alle sichtbar sein.

## Darf man etwa die Beauftragung (ja/nein) noch ändern, wenn es schon eine Freigabe gibt?
nein

## Damit Sie testen können, erscheint heute nur ein Dialog der Art "Nur für NIF/MAA", aber jeder kann es ändern. Sobald Sie es "abnicken", sperre ich dann die Funktionen für die Unerwünschten
in Ordnung

**Comment by chrbusch** [comment]
Die Felder selber sind die Buttons!
Und sie färben sich auch automatisch, je nach Eintrag.
Aus Platzgründen halte ich dies so für sinnvoll: auf diese Liste kommen sicherlich noch mehr Objekte!
Die Beauftragung kann nun nicht mehr geändert werden, wenn es bereits einen Status gibt

**Comment by chrbusch** [comment]
Es erscheinen nun die Volltexte, keine Abkzg.

**Comment by chrbusch** [comment]
Es gibt den Button nun auch bei der Transp.-Details; soll er also auf der HerstellListe nicht mehr bedienbar sein?
![bildschirmfoto 2018-04-26 um 12 16 13](https://user-images.githubusercontent.com/1241899/39300379-c390792c-494b-11e8-8ee4-e52e97441c11.JPG)

**Comment by Toelk-A** [comment]
Wir haben getestet, soweit scheint erstmal alles zu funktionieren:

1) Können Sie bitte die Buttons nun nur noch von genannten Parteien (GBM-V  NIF und KNA sowie GTMV NIF und MAA) bedienbar machen?

2) Der GBM-V Button darf auf der Herstellliste nicht mehr bedienbar sein.

## 3) Sollten wir einen Button haben, der die Transplantate mit beauftragter vir Unt. zeigt, zu denen der Status leer ist?

Ja

**Comment by chrbusch** [comment]
Neuer Button ist da, Thema Herstellung, Button "Offene virolog. Beauftrag."
Alles, was den Datenschutz und die Trennung der Mandanten betrift, bitte in eigene Tickets. Wir brauche hie rm.E. erst einmal ein solides Konzept, bevor wir an einzelne Buttons gehen.

![bildschirmfoto 2018-04-26 um 14 36 55](https://user-images.githubusercontent.com/1241899/39306036-4f4ef3b8-495f-11e8-94d2-9e83c09bd70c.JPG)

**Comment by chrbusch** [comment]
A) Können Sie bitte die Buttons nun nur noch von genannten Parteien (GBM-V NIF und KNA sowie GTMV NIF und MAA) bedienbar machen?

Erl.

B) Der GBM-V Button darf auf der Herstellliste nicht mehr bedienbar sein.
Erl.

**Comment by Toelk-A** [comment]
Es funktioniert alles soweit :+1: 

Folgende Dinge sollen noch programmiert werden:

## 4) Ampelbutton GTM-V benötigt weiteren Status 
Bitte einen 4. Status für den Ampelbutton GTM-V einfügen "Virologie beauftragen"- Farbe orange, auch dieser darf nur durch VP

## 5) Bitte Buttonbetätigungen loggen

Es soll in Ornella geloggt werden, wer von den VP (MAA/NIF) bzw. von der GBM-V(NIF oder KNA) die Buttons (Ampelbutton GTM-V bzw. Ja/Nein Button GBM-V) betätigt. Dies soll ähnlich abgebildet werden wie in den Prozessschritten Spende -> "Arzt-Freigabe" (siehe rote Markierung)

![image](https://user-images.githubusercontent.com/22314271/39519489-3b5f3f3c-4e07-11e8-9ec2-0cc87a6d0a2d.png) 

## 6) Button "Offene virolog. Beauftrag." unter Menüpunkt "Spender-Daten"

Bitte den genannten Button vom Menüpunkt "Herstellung" in Menüpunkt "Spender-Daten" verschieben

## 7) Button "Offene virolog. Beauftrag." 
Dieser Button soll alle Transplantate auflisten die den Status "ja" (GBM-V) UND den Status "ja" (GBM-V) und "Virologie beauftragen" (GTM-V) haben.

## 8) Automatische Statusänderung Ampelknopf GTM-V Teil 1
WENN der Untersuchungsantrag der GTM-V (Spender Details - Prozesschritte) vollständig ausgefüllt ist (Adressat, Parameter und Datum Versand) UND das Datum Versand >= dem aktuellen Datum ist DANN soll der Ampelknopf automatisch von "Virologie beauftragen" auf "virolog. Untersuchung veranlasst" geändert werden.

## 9) Bitte GTM-V Spalte vergrößern
sodass der gelbe Ampelknopftext vollständig abgebildet wird.

![image](https://user-images.githubusercontent.com/22314271/39520873-6fd42142-4e0c-11e8-9d8a-8783c61414db.png)

**Comment by chrbusch** [comment]
Ad4): Erledigt
![bildschirmfoto 2018-05-03 um 07 38 36](https://user-images.githubusercontent.com/1241899/39561287-0b62b496-4ea5-11e8-8268-40584d87a684.JPG)

**Comment by chrbusch** [comment]
Ad 5) Schlage vor, das Logging der virol. Beauftrag. in die neuen Tabelle "StatusWechsel" aufzunehmen - OK?

Ad6) Erledigt

**Comment by chrbusch** [comment]
"Dieser Button soll alle Transplantate auflisten die 
A) den Status "ja" (GBM-V) 
B) UND den Status "ja" (GBM-V) 
C) und "Virologie beauftragen" (GTM-V) haben.

A) und C) sind programmiert, B verstehe ich nicht

**Comment by chrbusch** [comment]
Ad 9): Erl.

**Comment by chrbusch** [comment]
Ad 8): Bitte anrufen damit wir besprechen können, wie hier der Ablauf sein soll: Wer klickt wo welchen Button, der die Statusänderung triggern soll?

**Comment by chrbusch** [comment]
Ad 7)
Das System sucht nun Transplantate, die haben
Status_GBM-V = "Ja"
UND
Status_GBM-V = (leer ODER "Virologie beauftragen")

**Comment by chrbusch** [comment]
Ad 5) Bitte Buttonbetätigungen loggen

In die früher bereits eingerichtete Tabelle "AuditLog" werden nun Änderungen der Statusfelder geschrieben
Der neue Button "AuditLog" wird gezeigt bei Spender + Transplantatdetails und ruft die Liste der Änderungen auf.

![bildschirmfoto 2018-05-03 um 09 13 13](https://user-images.githubusercontent.com/1241899/39563886-39a512ce-4eb2-11e8-9b22-92f3f0cb8bd8.JPG)

**Comment by Toelk-A** [comment]
Ist 8) auch programmiert?

**Comment by chrbusch** [comment]
Jetzt ist B) programmiert. Mir wäre am liebsten, wenn ich den ersten Fall selbst mit ScriptDebugger anklicken könnte - bitte Bescheid geben, wenn Sie einen Fall haben, sei es echt oder Testspender.

**Comment by Toelk-A** [comment]
testspender

![image](https://user-images.githubusercontent.com/22314271/39579557-5e748352-4ee7-11e8-93cb-8aa9a727ec64.png)

**Comment by chrbusch** [comment]
Hat m.E. alles geklappt: Beim PDF-Druck des Unters.-Auftrags kam der Dialog für 2xOG
Bitte prüfen Sie, ob für die Occuli dieses Spenders auf der Herstellungsseite nun alle Werte korrekt gesetzt wurden.

**Comment by Toelk-A** [comment]
## 10) Automatisierte Änderung Ampelknopf bei Statuswechsel 
-> Wenn Ticket #345 fertig programmiert ist, dann bitte automatisierte Änderung des Ampelknopfes programmieren:

### A) Status [7] = Freigabe
-> WENN Status [7] gewählt, DANN Änderung des Ampelknopfes auf "grün" -> "Virol- Freigabe"

### B) Status [67] = keine Freigabe und/oder [23] = keine Diagnostik
-> WENN Status [67] gewählt, DANN Änderung des Ampelknopfes auf "rot" -> keine virol. Freigabe
-> WENN Status [23] gewählt, DANN Änderung des Ampelknopfes auf "rot" -> keine virol. Freigabe

**Comment by Toelk-A** [comment]
zu Ad###  5) Bitte Buttonbetätigungen loggen
### 
In die früher bereits eingerichtete Tabelle "AuditLog" werden nun Änderungen der Statusfelder geschrieben. Der neue Button "AuditLog" wird gezeigt bei Spender + Transplantatdetails und ruft die Liste der Änderungen auf.

Wird heir auch geloggt wer den Button GBM-V "ja/nein" klickt?

**Comment by chrbusch** [comment]
Für die Statuswechsel haben wir jetzt (aus gutem Grund) eine eigenen Tabelle.
Änderungen mit dem oben erwähnte Button werden in der AuditLog-Tabelle gespeichert.

![bildschirmfoto 2018-05-08 um 14 08 24](https://user-images.githubusercontent.com/1241899/39756303-4c5b4efe-52c9-11e8-8e09-362b5e272251.JPG)

**Comment by Toelk-A** [comment]
Bitte Nr. 10 noch bearbeiten

**Comment by chrbusch** [comment]
Das ist nun programmiert, mangels Testdaten kann ich abe rnich tselbst testen.
Zur Zeit fragt das System,. ob der Status umgesetzt werden soll. Klappt das zuverlässig, kann m.E. der Dialog wieder weg

**Comment by Toelk-A** [comment]
erledigt

**Comment by Toelk-A** [comment]
Bitte auch hier die Mitarbeiter loggen, die die Sterilkontrolle durchführen ähnlich wie in Ticket #357
