### ISSUE TITLE
Routinekalender f.d. Bank

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#335]
Hauptmenü - Button Herstellung - > 
![image](https://user-images.githubusercontent.com/22314271/39186806-e254c308-47cb-11e8-9f99-5ba7562c2911.png)

1) Bitte umbenennen in "Routinekalender"

2) Zeitbereich ist nicht die kommende Woche, sondern die Laufende Woche... prinzipiell sollte es ähnlich des Buttons "Letze Spender" möglich sein eine Datumsauswahl zu treffen bzw. "Laufende Woche", "Nächte Woche"... etc.

![image](https://user-images.githubusercontent.com/22314271/39186990-5061fa78-47cc-11e8-9cf3-d4f39acc88ed.png)

**Comment by chrbusch** [comment]
Beides erledigt.
Das funktioniert aber nur, wenn wir noch die Eingabe der Datumswerte überarbeiten, so dass diese in den Prozessschritten laden.
Der grafische Aufbau der Herstelluns-Maske kann dabei ähnlich bleiben, ich denke heute mal darüber nach.

**Comment by Toelk-A** [comment]
## "Das funktioniert aber nur, wenn wir noch die Eingabe der Datumswerte überarbeiten, so dass diese in den Prozessschritten laden."

-> Hierzu öffne ich Ihnen ein Extraticket.

**Comment by chrbusch** [comment]
Um alles zu testen, habe ich die in die alten Felder eingegebenen Werte für Sterilkontrolle und Medienwechsel in die entspr. Prozesschritte übertragen.
Bitte testen Sie den umbenannten Button

**Comment by chrbusch** [comment]
Wir müssen noch besprechen, wie die Mitarbeiter der Bank dokumentieren, was sie erledigt haben.
Ich denke, auf genau der Liste, die gedruckt wird:
a) Einen Button in der Art "Habe diesen einen Punkt erledigt"
b) Einen Button in der Art "Habe diesen Aufgabenblock /zB alle Medienwechsel) erledigt"

Ist das sinnvoll?
Bitte den ganzen Ablauf durchdenken

**Comment by Toelk-A** [comment]
Herr Busch hier nicht weiterarbeiten bis ich mich melde...
