### ISSUE TITLE
NIF kann AZK Wunsch nicht umwandeln in AZK

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#336]
NIF erhielt Wiedervorlage:

<img width="1178" alt="wiedervorlage nif" src="https://user-images.githubusercontent.com/22314271/39233425-9ee90ee4-4870-11e8-8adc-401acf66382f.png">

Nachdem die Wiedervorlage geöffnet wird und der AZK Wunsch umgewandelt werden soll erscheint folgender Fehler:

<img width="1190" alt="fehlermeldung nif" src="https://user-images.githubusercontent.com/22314271/39233468-b5a7acb2-4870-11e8-9eb4-008b02ecdd11.png">

Vorher funktionierte dies ohne Probleme, bitte Skript überprüfen

**Comment by chrbusch** [comment]
Diese Meldung kommt nur, wenn man nicht Supervisor ist, Herr Nitschke hat aber dieses Recht.
Passierte das einmalig?
Bitte erneut testen, habe nichts geändert.
