### ISSUE TITLE
GBMV/ Erstellung Liste A) "Sterilkontrollen Eingang"

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#337]
Mit Bezug auf Ticket #331 wird hier die Liste A) **"Sterilkontrollen Eingang"** beschrieben:

## A 1) Aufbau Liste "Sterilkontrollen Eingang" 

Abgebildet werden sollen  **alle** Hornhauttransplantate, die wie hier im Beispiel gezeigt, am 25.04.18 eine "Sterilkontrolle Eingang" benötigen. Das rot markierte Eingabefeld = Solldatum. 

![image](https://user-images.githubusercontent.com/22314271/39346756-059b3222-49f0-11e8-9fc5-c61f6fba38be.png)

## A2) Zuordnung Warenkörbe und Zusatzpositionen

Wird die Liste durch den Anwender im Routinekalender geöffnet, so müssen auch hier wieder Warenkörbe und Zusatzpositionen einer und/oder mehrerer Hornhäute zugeordnet werden. (Dies wurde im Vorfeld bereits programmiert :-) -> die Zuordnung muss nur noch angepasst werden).

### A2.1) Hinzufügen der Buttons "Warenkorb hinzufügen" und "ZusatzPos zuordnen" in die o.g. Liste

Die Buttons sind bereits auf den Transplantatdetails - Reiter Herstellung programmiert:

![image](https://user-images.githubusercontent.com/22314271/39347349-b481860e-49f2-11e8-9a77-b434a89c4bf7.png)

### A2.2) Button "Warenkorb hinzufügen" - Funktion erweitern
Befinden sich z.B. 10 Transplantate auf der Liste "Sterilkontrolle Eingang" und es wird der Button "Warenkorb hinzufügen" benutzt, so soll das System automatisch, wenn noch 10 Warenkörbe mit der selben ID XY vorhanden sind, diesen Warenkorb allen Hornhäuten in der Liste zuordnen. Gleichzeitig muss dann natürlich der Bestand des Warenkorbes XY um 10 vermindert werden.

Sind z.B. nur noch 5 Warenkörbe der ID XY vorhanden, dann Meldung "Achtung es sind nur noch 5 Warenkörbe der ID XY vorhanden". Dann sollen die 5 Warenkörbe den 5 Hornhäuten in aufsteigender Reighenfolge ( z.B. 001-GMV-CD bis 003-GMV-CD) zugeordnet werden. Dann MUSS der Dialog weitergehen "Bitte scannen Sie den Warenkorb für die übrigen Hornhäute ein". Dieser wird dann den Hornhäuten (z.B. 003-GMV-CS bis 0005-GMV-CS) zugeordnet und natürlich im System abgezogen.

Das heißt, es müssen alle Hornhäute der Liste abgearbeitet sein - "ein Warenkorb und/oder Zusatzpositionen" zugeordnet sein.

### A2.3) Button "ZusatzPos zuordnen" - Funktion erweitern

Wird der Button benutzt, so muss sich auch hier nur auf die Hornhäute bezogen werden, die sich in der Liste "Sterilkontrolle Eingang" befinden

**A2.3.1 Zusatzpositonen** 1 Artikel pro Hornhaut z.B. Kulturflaschen (Artikel ID 121)

Ähnlich der Warenkörbe soll jeder Hornhaut in der Liste je eine Kulturflasche zugeordnet werden. Ändert sich die Chargennummer so soll wie beim Warenkorb eine erneute Scanaufforderung erfolgen. Bestand soll ebenfalls im System ausgetragen werden.

**A2.3.2 Zusatzposition "Artikel x-fach anwendbar" z.B. Pipetten**
Wird einer dieser Zusatzpositionen eingescannt, so wird der Artikel 1x aus dem Bestand abgezogen, aber _allen_ Hornhäuten der Liste zugeordnet. Es soll keine Hornhaut einzeln abgescannt werden.
![image](https://user-images.githubusercontent.com/22314271/39348103-f852c3f4-49f5-11e8-913a-ace3e542a5a5.png)

**A2.3.3 Zusatzposition Lösungen "Artikel x-fach anwendbar" z.B. Medium, Pnase**

Wird einer dieser Zusatzpositionen eingescannt, so weiß Ornella ich habe 10 Transplantate. 1x KMI-Flasche ist ausreichend für 2 Hornhäute (in Ornella bereits hinterlegt und programmiert). Das heißt, die eingescannte ArtikelID (Medium KMI) wird, wenn ausreichend vorhanden, jeder Hornhaut der Liste zugeordnet. Gleichzeitig soll der Bestand im System abgezogen werden. Das bedeutet, für die z.B. 10 Hornhäute benötigt man 5 Flaschen KMI Medium, da 2 Hornhäute mit einer Flasche bedient werden können.

Ist nicht genügend Medium der selben Artikelcharge vorhanden, so soll ähnlich des Warenkorbes mittels Dialogfenstern gearbeitet und zugeordnet werden -> "chargenübergreifendes Arbeiten"

![image](https://user-images.githubusercontent.com/22314271/39348358-0aca5bf4-49f7-11e8-9619-988bc76162fb.png)

## A3) Button "Job erledigt" 

Das heißt, es müssen alle Hornhäute der Liste abgearbeitet sein - "ein Warenkorb und/oder Zusatzpositionen" zugeordnet sein.

Dann soll ein Button eingebelendet werden "Job erledigt", der die Liste "Sterilkontrolle Eingang" im Routinekalender grün einfärbt.

Mit dem Klick dieses Buttons entsteht das "IST-Datum".

**Comment by chrbusch** [comment]
Bitte prüfen Sie, ob Sie im neuen Bereich "Aufgabe/Solldatum" wie gewohnt die Daten erfassen können.
Ich habe m.E. alle existierenden Daten in die neue Struktr übertragen und kann nun die Aufgabenlisten fertig stellen

![bildschirmfoto 2018-04-30 um 10 10 45](https://user-images.githubusercontent.com/1241899/39419166-dd456c36-4c5e-11e8-8b7a-34648f44ee26.JPG)

**Comment by chrbusch** [comment]
So, wie die Aufgabenstellung bislang war, kommen auch Transplantate im Status "verworfen" auf die Aufgabenliste, was wohl nicht gewollt ist?!
Vorschlag: gewisse Status müssen ausgeschlossen werden; ist das nur "verworfen", oder noch andere Status?

**Comment by Toelk-A** [comment]
## Vorschlag: gewisse Status müssen ausgeschlossen werden; ist das nur "verworfen", oder noch andere Status? Wie ist es mit 39="Sperre"?
-> Die Mitarbeiterinnen der Bank tragen nur ein Datum ein, wenn eine "Sterilkontrolle Eingang" sinnvoll ist. Das heißt die Mitarbeiterinnen der Bank treffen die Vorauswahl ob ein Transplantat in der Liste auftaucht oder nicht. Für "Verworfen würde es keinen Datumseintrag geben. Für "Sperre" ist ein Datumseintrag wahrscheinlich. 

-> Bitte hier keine Extraprogrammierungen hinsichtlichd er verschiedenen Status vornehmen. Nur alles wie oben beschrieben programmieren.

**Comment by chrbusch** [comment]
Bitte heute Anruf (Handy) eines Bank-Mitarbeiters, damit wir das testen können

**Comment by chrbusch** [comment]
Wichtige Frage: Wenn zB bei 5 Transplantaten ein Medienwechsel ansteht und ich diesen 5 denselben Warenkorb zuordne - dann sinkt doch dessen Bestand um 1, nicht um 5?
Oder wie wird das physisch gehandhabt?

**Comment by Toelk-A** [comment]
## Bitte heute Anruf (Handy) eines Bank-Mitarbeiters, damit wir das testen können

Die Sterilkontrollen finden immer nur morgens statt. Die Bankmitarbeiterinnen baten um einen Termin morgen 16.05.2018 08:30Uhr. Ist dies umsetzbar für Sie?

## Wichtige Frage: Wenn zB bei 5 Transplantaten ein Medienwechsel ansteht und ich diesen 5 denselben Warenkorb zuordne - dann sinkt doch dessen Bestand um 1, nicht um 5?
Oder wie wird das physisch gehandhabt?

1 Hornhaut bekommt 1 Warenkorb, d.h. bei 5 Hornhäuten müssen auch 5 Warenkörbe abgezogen werden. Dasselbe gilt beim Medium (alles oben unter _Punkt A_ beschrieben... x-fache Anwendung). Zusatzpositionen wie Pipetten bilden die Ausnahme -> hier kann z.B. 1 Pipette für 5 Hornhäute genutzt werden...

**Comment by chrbusch** [comment]
Ich bin am 16.5. morgens nicht in Hamburg und am 17.5. morgens beim Zahnarzt; 18.5. würde passen.

".. bei 5 Hornhäuten müssen auch 5 Warenkörbe abgezogen "
So ist es auch jetzt programmiert, ich wollte nur sicher gehen, es richtig verstanden zu haben

**Comment by Toelk-A** [comment]
Der Test heute Morgen scheint funktioniert zu haben. Was sind die nächsten Schritte?

**Comment by chrbusch** [comment]
Der neue Button "ZusatzPos zuordnen" ist nun m.E. funktionsfähig, das muss aber gemeinsam getestet werden.
Ein Bankmitarbeiter soll mich bitte morgens hierzu anrufen

**Comment by chrbusch** [comment]
Zusatzpositionen: Test mit Bankmitarbeiterin war erfolgreich, einige nicht nötige Dialoge wurden soeben entfernt und eine Abbruch-Option addiert

**Comment by chrbusch** [comment]
Bitte der Bankmitarbeiterin mitteilen, dass nun m.E. Pipetten wie gewünscht nur noch 1x ausgebucht werden; dies bitte aufmerksam testen

**Comment by chrbusch** [comment]
Rechts oben ist nun auch ein grüner Button "Alle erledigt", der das heutige Datum in die unerledigten setzt

**Comment by Toelk-A** [comment]
Die Mitarbeiterin aus der Bank teilte mir mit, dass nun gar keine Pipette aus dem Bestand abgezogen wird.

**Comment by chrbusch** [comment]
Ich denke, ich habe den Fehler korrigiert; bitte beim nächsten Aufruf RoutineKalender wieder Bestandsbuchung prüfen

**Comment by Toelk-A** [comment]
Ausbuchen der Pipetten funktioniert. Ist diese Ticket nun vollständig abgearbeitet?

**Comment by Toelk-A** [comment]
Bitte auch hier die Mitarbeiter loggen, die die Sterilkontrolle durchführen ähnlich wie in Ticket #357

**Comment by chrbusch** [comment]
Das Ausbuchen von Artikeln erzeugt ja neue Datensätze, in der Tabelle der Materialpositionen. Diese Datensätze werden ohnehin mit dem Benutzerkürzel des Erstellers markiert.
Un dim Sinne der Nachvollziehbarkeit sollte wirklich niemals jemand mit dem Account eines anderen Mitarbeiters im System arbeiten; **m.E. sollte dies von der GF verboten werden!**
