### ISSUE TITLE
GBMV/ Erstellung Liste B) "Sterilkontrollen Ausgang"

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#338]
Mit Bezug auf Ticket #331 wird hier die Liste B) "Sterilkontrollen Ausgang" beschrieben:

## A 1) Aufbau Liste "Sterilkontrollen Ausgang"
Abgebildet werden sollen **alle** Hornhauttransplantate, die wie hier im Beispiel gezeigt, am 23.04.18 eine "Sterilkontrolle Ausgang" benötigen. Das rot markierte Eingabefeld = Solldatum.

![image](https://user-images.githubusercontent.com/22314271/39357681-dba7ff9e-4a13-11e8-8dc5-cbf3d0e80e5f.png)

-> der weitere Ablauf ist bereits im Ticket #337 erklärt und programmiert

**Comment by chrbusch** [comment]
bitte testen

**Comment by Toelk-A** [comment]
Bitte auch hier die Mitarbeiter loggen, die die Sterilkontrolle Ausgang durchführen ähnlich wie in Ticket #357
