### ISSUE TITLE
Erstellen manueller Rechnungen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#340]
Wir benötigen eine Programmierung zum Erstellen manueller Rechnungen, die mit **laufender Rechnungsnummer** in Ornella hinterlegt werden sollen:

-> manuelles Feld für Rechnungssteller (= MANDANT GTM-V oder GBM-V + LOGO)
-> manuelles Feld für Rechnungsempfänger (z.B. GBM-V; GTM-V; transplantierende Einrichtung etc.)
-> manuelle Texteingabe
-> Textfeld für "Menge"
-> Textfeld Einzelbetrag
-> Feld Gesamtpreis (=Menge multipliziert mal Einzelbetrag)
-> Textfeld Nachtext
-> Fußzeile entsprechent MANDANT GTM-V oder GBM-V

**Comment by chrbusch** [comment]
Bitte den neuen Button bei der Adresse testen.
Vor- und Nachtext ändern Sie in den neuen Textbausteinen mit ID=22 und 23

![bildschirmfoto 2018-05-02 um 15 30 44](https://user-images.githubusercontent.com/1241899/39526004-dcdc7062-4e1d-11e8-8714-8f8bbe2cde76.JPG)

**Comment by Toelk-A** [comment]
Rechnung erstellen getestet. Um das Layout zu prüfen wollte ich den Button "Rechnung/Mahnung drucken" nutzen. Hier kommt folgende Meldung:

![image](https://user-images.githubusercontent.com/22314271/39561512-70b15068-4ea6-11e8-9d59-04b5e4d8c02d.png)

**Comment by Toelk-A** [comment]
Scheint alles in Ordnung
