### ISSUE TITLE
Prozessschritte fehlen ID4671

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#341]
Spender ID 4671 Prozesschritte fehlen, es sind keine Prozesschritte gelöscht wurden (Wiederherstellen gelöschter Prozesschritte - Button genutzt)

Muss die Spenderakte neu angelegt werden?

Folegende Prozessschritte fehlen:

- körperliche Untersuchung
- Freigabe Gewebentnahme
- Freigabe Archivierung Spenderakte
- Checkliste Spenderakte

Die Spenderakte kann nicht freigegeben werden.

![image](https://user-images.githubusercontent.com/22314271/39525403-2af44aec-4e1c-11e8-92f2-c75076c075c2.png)

**Comment by chrbusch** [comment]
Keine Ahnung, wie das einmalig passiert ist; ich habe das aber manuell korrigiert.

**Comment by Toelk-A** [comment]
erledigt

**Comment by chrbusch** [comment]
"Die Spende wurde ursprünglich als "Leiche am 06.05.18 angelegt und am 15.05.18 von NIF "überschrieben". "
Bitte diesen Satz erläutern, ich verstehe ihn nicht. Vermutlich liegt bei dieser "Überschreibung" das Problem, aber was hat Dr. N. tatsächlich im Programm getan?

**Comment by Toelk-A** [comment]
## Das ist MORD in und an der Datenbank! Niemals darf so etwas geschehen.
### Wozu wird das gemacht????
-> Die Spendermeldung wurde Original an einem Wochenende durch den USER KRJ angelegt, sodass eventuell die Internetverbindung im "Home Office" zu schlecht gewesen sein könnte und somit keine vollständige Erstellung der Meldung möglich war.

Anhand der "Akte" können Sie erkennen, das am Datum der Generierung der Spender ID 4803 keine weiteren Prozessschritte angelegt wurden. Es wurden damals keine weiteren Daten zu der genannten ID hinterlegt, da wahrscheinlich die Internetverbindung abgebrochen ist. Erst ab 15.05.18 mit den "neuen Daten".

![image](https://user-images.githubusercontent.com/22314271/40468151-d4c18bea-5f2c-11e8-8380-4dcfef8b8021.png)

**Comment by Toelk-A** [comment]
Die Akte muss in Papierform archiviert werden. Können Sie die fehlenden Prozessschritte wiederherstellen?

**Comment by chrbusch** [comment]
Gibt es bei diesem recht alten Ticket noch Handlungsbedarf?

**Comment by Toelk-A** [comment]
Es fehlen noch immer die Prozesschrittte.... das eigentliche Problem wurde nie bearbeitet...

**Comment by Toelk-A** [comment]
erledigt
