### ISSUE TITLE
Allokationswochenbericht laufende Woche - Spalte Tr Medium

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#342]
Button Allokation - Allokationswochenbericht - Laufende Woche

Datumssortierung nach Klick auf Spalte "Tr.Medium" funktioniert nicht mehr. Bitte wiederherstellen. Vielen Dank

![image](https://user-images.githubusercontent.com/22314271/39569346-3cf82bba-4ec5-11e8-995f-8b2fa53fed22.png)

**Comment by chrbusch** [comment]
erl.
