### ISSUE TITLE
MSG Etikettenset jung/alt scheint noch immer nicht mit den gesetzten Altersgrenzen zu funktionieren

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#343]
Wir hatten in Hamburg die Altersgrenzen neu festgelegt für die Entnahme der Sehnen (bis 65 Jahre) MSG (Etikettenset jung und alt)

Spender ID 4778 ist 82 Jahre und es wurden wieder Sehnen abgebildet (Dr. Manecke hat diese bereits gelöscht). Können Sie bitte noch einmal das Skript prüfen.

**Comment by Toelk-A** [comment]
### Frauen:

Präparateset „J“ bis inkl. 65 Jahre
Präparateset „A“ von >=66 bis inkl. 70 Jahre

### Männer:

Präparateset „J“ bis inkl. 65 Jahre
Präparateset „A“ >=66 bis inkl. 85 Jahre

**Comment by chrbusch** [comment]
War Programmierfehler, m.E. behoben
