### ISSUE TITLE
Buchhaltung - Button Rechnung stornieren - keine Funktion 

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#344]
Buchhaltung, "Button Deb.Rng. stornieren" hat keine Funktion, bitte fertig programmieren

![image](https://user-images.githubusercontent.com/22314271/39693794-8ca2a898-51e5-11e8-8ba3-f6d083feddac.png)

-> Fehlermeldung
![image](https://user-images.githubusercontent.com/22314271/39693852-b6b114d0-51e5-11e8-9bb6-16b83d6ad45e.png)

**Comment by chrbusch** [comment]
Frau Schmalfuß-Gross weiss seit langem, dass ich hier auf eine präzise Vorgabe warte, ob und wie sich die div. Felder auf der Eingabemaske ändern sollen.

**Comment by Toelk-A** [comment]
achso. Meines Erachtens hat der Stornierungsbutton immer funktioniert bis jetzt. 

Bitte stellen Sie die Ausgangsfunktion wieder her. Das Thema Stornieren und Gutschriften erstellen, wird in einem Extraticket diskutiert. Aber Sie können nicht einfach den Stornierungsbutton blocken.
Danke

**Comment by chrbusch** [comment]
Reines Storno ist wieder aktiviert, GS wartet auf Detailvorgabe
