### ISSUE TITLE
Kleine Umstrukturierung Spenderdetails - Spenderdaten

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#345]
## 1) Neue Spalte im Abschnitt Gewebe einfügen

Spenderdetails - Spenderdaten - ARZT Abschluss - Reiter Gewebe

Bitte eine 3. Spalte (wie rot markiert) einfügen "Status Freigabe Gewebe"

![image](https://user-images.githubusercontent.com/22314271/39693771-77e77640-51e5-11e8-953b-4e9dbbaf65e8.png)

## 2) Werteliste hinterlegen

-> in dieser neu angelegten Spalte soll je Gewebeart die Werteliste "Status wählen für Gewebe" ID 6401  hinterlegt werden

## 3) Werteliste modifiziert anzeigen
aus der Werteliste sollen nur die Status [7] - Freigabe, [67] - keine Freigabe und [23] Abbruch Diagnostik 
  abgebildet werden 

## 4) Zugriff nur VP
Diese Werteliste darf nur durch die VP änderbar/benutzbar sein

## 5) Abbildung Status Freigabe Gewebe auf Transplantatdetails
Im Moment wird in den Transplantatdetails der "Status des Spenders" abgebildet. Dies soll geändert werden. Es soll der "Status Freigabe Gewebe" für OG abgebildet werden, der in diesem Ticket programmiert ist.
 
![image](https://user-images.githubusercontent.com/22314271/39694869-02bf3098-51e9-11e8-8e02-a2d36bce7520.png)

## 6) Statuseingabe hat Einfluss auf Ampelknopf Virologie
-> wird in Ticket #334 beschrieben

**Comment by chrbusch** [comment]
"Werteliste "Status wählen für Gewebe" ID 6401"
cbu: Was ist das für eine ID??

Soll ein Gewebe künftig 2 Status haben, den schon existierenden und einen für die Freigabe?
Falls ja, wozu???

**Comment by Toelk-A** [comment]
## "Werteliste "Status wählen für Gewebe" ID 6401"
cbu: Was ist das für eine ID??

![image](https://user-images.githubusercontent.com/22314271/39744390-5ac508ba-52a4-11e8-8e40-fce21cca5887.png)
Scheint die ID des Transplantates zu sein? Hatte die ID nur abgetippt, da ich dachte es sei die ID der Werteliste ;-)

## Soll ein Gewebe künftig 2 Status haben, den schon existierenden und einen für die Freigabe?
Falls ja, wozu???
Ja. Der Status für die Freigabe pro Gewebe ist notwendig, da manchmal aufgrund der positiven Virologie keine MSG aber OG freigegeben werden kann.

## Abbildung Status Freigabe Gewebe auf Transplantatdetails
Erl., wenn das das schon existierende Feld ist.

Ja. Erledigt

**Comment by chrbusch** [comment]
Aber es gibt doch schon lange einen Status pro Gewebe!
Die Frage war, ob es ZWEI Status pro Gewebe geben muss; das sehe ich nicht so.
Bitte hierzu anrufen.

**Comment by Toelk-A** [comment]
Bitte um Rückruf

**Comment by Nitschke-FP** [comment]
Kurzbezeichnungen Status=
keine Freig.=keine Freigabe Gewebe gemäß §8 Abs. 1 Satz 2 Nr. 4 TPG
Freig.=keine Freigabe Gewebe gemäß §8 Abs. 1 Satz 2 Nr. 4 TPG
Abbruch Diagn.=Abbruch Diagnostik wegen Tx-Qualität

**Comment by chrbusch** [comment]
Es gibt nun 3 neue Werte in der Statustabelle mit Kennung "F" = "Freigabe"
Ist das Layout so modifiziert wie erwartet?

![bildschirmfoto 2018-05-09 um 11 01 50](https://user-images.githubusercontent.com/1241899/39805909-83abcb0e-5378-11e8-8fd4-ca0697af3da2.JPG)

**Comment by chrbusch** [comment]
Nur 30 Gewebe hatten einen der Status
Status [7] - Freigabe, [67] - keine Freigabe und [23] Abbruch Diagnostik

Bei diesen habe ich die Status-ID in das neue Feld kopiert.

Und diese Werte wurde ENTFERNT aus der Werteliste für das alte Statusfeld, hatte ich das richtig verstanden?

**Comment by Nitschke-FP** [comment]
die 30 Gewebe sind Ergebnis der neuen Werteliste.
Das kopieren ist o.k.
Ich habe die Wartelisten geändert.

**Comment by chrbusch** [comment]
Bitte nicht die Tickets vorzeitig schliessen!
Welche Werteliste haben Sie geändert??

**Comment by Nitschke-FP** [comment]
Perfekt. Danke

Mit freundlichen Grüßen

Dr. med. Frank-Peter Nitschke
Geschäftsführender Arzt

[id:image001.png@01D3797E.17922410]

GTM-V Gesellschaft für Transplantationsmedizin
Mecklenburg-Vorpommern
gemeinnützige GmbH
Wilhelm-Külz-Platz 3
18055 Rostock

'           +49 381 444 30 50
7            +49 381 444 30 525
Mobil:       +49 171 222 26 06
@       frank-peter.nitschke@gtm-v.de<mailto:frank-peter.nitschke@gtm-v.de>
:          www.gtm-v.de<http://www.gtm-v.de/>

USt-IdNr.: DE 298945377 Amtsgericht Rostock, HRB 13143 Geschäftsführer:          Dr. med. Frank-Peter Nitschke
                                     Dr. med. Axel Manecke

Diese Email enthält vertrauliche und/oder rechtlich geschützte Informationen. Jeglicher unbefugter Gebrauch oder Verbreitung dieser Nachricht oder Auszüge dieser Nachricht ist strengstens verboten. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail.

This e-mail may contains confidential and/or privileged information. Any unauthorised usage or dissemination of this message in whole or in part is strictly prohibited. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail.

Von: Christopher Busch <notifications@github.com>
Antworten an: chrbusch/GTM-V <reply@reply.github.com>
Datum: Mittwoch, 9. Mai 2018 um 11:10
An: chrbusch/GTM-V <GTM-V@noreply.github.com>
Cc: "Dr. Frank-Peter Nitschke" <frank-peter.nitschke@gtm-v.de>, State change <state_change@noreply.github.com>
Betreff: Re: [chrbusch/GTM-V] Kleine Umstrukturierung Spenderdetails - Spenderdaten (#345)


Es gibt nun 3 neue Werte in der Statustabelle mit Kennung "F" = "Freigabe"
Ist das Layout so modifiziert wie erwartet?

[ild vom Absender entfernt. bildschirmfoto 2018-05-09 um 11 01 50]<https://user-images.githubusercontent.com/1241899/39805909-83abcb0e-5378-11e8-8fd4-ca0697af3da2.JPG>
