### ISSUE TITLE
Gutschrift an Meldende Einrichtungen - Gewebeentnahmen - Südstadt keine Rechnungserstellung

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#346]
Rechnung wird nicht erstellt:

Adress ID 1
Button: Entnahmen prüfen/abrechnen - Vormonat
-> prüfen -> alles ok
Button:  Entnahmen prüfen/abrechnen - Vomronat
-> abrechnen -> keine Rechnungserstellung.

Vermutlich ist die Amnionentnahme das "Problem" (Spender ID 4697)

![image](https://user-images.githubusercontent.com/22314271/39697773-6d23e146-51f2-11e8-89fc-81560de5efa3.png)

**Comment by chrbusch** [comment]
wie tel. besprochen: Für Amnion (u.a.!) fehlt der Entschädigungsbetrag

![bildschirmfoto 2018-05-07 um 15 34 30](https://user-images.githubusercontent.com/1241899/39704622-35b82fb8-520c-11e8-8e1e-1fd711092573.JPG)
