### ISSUE TITLE
Buttons ausblenden - Transplantatdetails

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#347]
Transplantatdetails
"Befunde aller Art"
Bitte bei Endothel und Kornea die Buttpons "p", "n", "i" und "wl" ausblenden, da sie keine Funktion haben... klickt man aus Versehen drauf, so ist die eigentliche Befundangabe gelöscht

![image](https://user-images.githubusercontent.com/22314271/39702347-c935cbd6-5204-11e8-948b-928b5d8c33bb.png)

**Comment by chrbusch** [comment]
Erl.

**Comment by Toelk-A** [comment]
erledigt
