### ISSUE TITLE
KPT- Lagerung ins Transportmedium Fenster freigeben

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#348]
KPT -> Kompaktansicht "Lagerung in Transportmedium" 

![image](https://user-images.githubusercontent.com/22314271/39706324-585ee912-5211-11e8-9533-929bac019902.png)

Im Moment erscheint die Fehlermeldung, dass dieses Feld nicht mehr ausfüllbar ist. Bitte programmieren Sie eine automatische Datumsübernahme von dem rot markierten Feld in ihre neu programmierte Tabelle "Lagerung ins Transportmedium"

![image](https://user-images.githubusercontent.com/22314271/39706447-c1d2e326-5211-11e8-9501-96868cf12ea1.png)

**Comment by chrbusch** [comment]
m.E. erledigt, bitte testen

**Comment by Toelk-A** [comment]
erledigt
