### ISSUE TITLE
NIF - Teamkalender

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#349]
USER NIF möchte im Teamkalender einen AZK Wunsch in AZK umwandeln. Er selbst hat aber nur die Werteliste "AZK Wunsch", "Urlaub Wunsch" und "nicht verfügbar" zur Auswahl.

Woran liegt das?

**Comment by chrbusch** [comment]
Bitte Screenshot liefern, auf dem genau der geklickte Button zu erkennen ist

**Comment by Toelk-A** [comment]
"Button Fkt."

![image](https://user-images.githubusercontent.com/22314271/39742569-47f91f1a-529e-11e8-8545-132d6b50d9e9.png)

**Comment by chrbusch** [comment]
Script scheint mir korrekt.
Tritt das regelmässig auf? 
Und auch dann, wenn zuerst das normale Login in Ornella durchgeführt wird?
