### ISSUE TITLE
!!!! Allerhöchste Priorität PDF Dokumente!!!!   Spendermeldung drucken - PDF Ausgabe

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#35]
Es scheint ein Fehler in der Spenderkennummer 281016-1431-GNO-TOA vorzuliegen

nach Klick auf "Spendermeldung drucken" und "Ausgabe als PDF" erscheint PDF mit Überschrift des zuletzt ausgewählten/bearbeiteten Dokument des Spenders:

Hier als Beispiel "Untersuchungsauftrag" anstatt "Spendermeldung"

![image](https://cloud.githubusercontent.com/assets/22314271/19961447/fa7af134-a1b2-11e6-8cee-5e1d650e4323.png)

Vorher "Entnahmebericht" anstatt "Spendermeldung"

**Comment by Toelk-A** [comment]
Fehler ist wieder aufgetreten ID1394

![image](https://cloud.githubusercontent.com/assets/22314271/22462021/edbc52b4-e7ab-11e6-9f2b-9034d9534469.png)

**Comment by chrbusch** [comment]
Ich vermute, dies ist ein Artefakt welches nur auftritt, wenn wir gerade die Datenbankdefinitionen bearbeiten.
Wenn es erneut passiert, bitte sofort anrufen!

**Comment by Toelk-A** [comment]
Ja jetzt ist alles wieder in Ordnung
