### ISSUE TITLE
Etiketten Herstellung - Lesbarer Barcode teilweise FETT drucken

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#350]
Transplantatdetails - Button Etiketten - "Herstellung"

-> Bitte auf jedem Etikett Herstellung die laufende Nummer (gelb markiert - 0294) UND die Seite (gelb markiert CS oder CD) FETT abbilden (drucken) um Verwechselungen zu vermeiden

![image](https://user-images.githubusercontent.com/22314271/39746936-255a147e-52ac-11e8-9c23-f1d28cd4cd47.png)

**Comment by chrbusch** [comment]
M.E. erledigt, bitte testen!

**Comment by Toelk-A** [comment]
Transplantat ID 4809

-> es wird nichts FETT gedruckt
-> es fehlt das 1. Etikett "Eingang Bank"

![image](https://user-images.githubusercontent.com/22314271/39757960-c1d6906c-52ce-11e8-9e60-bae60faa6a14.png)

**Comment by chrbusch** [comment]
Nun aber!

![bildschirmfoto 2018-05-09 um 07 43 36](https://user-images.githubusercontent.com/1241899/39797524-b6106f8a-535c-11e8-8b90-a0a09db71f01.JPG)

**Comment by Toelk-A** [comment]
Transplantat ID 2232

Spenderkennnummer wird nicht vollständig abgebildet ("P" und 4 Stellen davor fehlen)



![image](https://user-images.githubusercontent.com/22314271/39798153-9038feb4-535f-11e8-871a-23a13de3f2d1.png)

Es soll nur, wie oben beschrieben und markiert, die laufende Nummer und Seite fett gedruckt werden...

**Comment by Toelk-A** [comment]
-> dies ist nicht notwendig und wurde nicht gefordert:
![image](https://user-images.githubusercontent.com/22314271/39798216-e18d1b10-535f-11e8-95ed-b0763f575863.png)

**Comment by chrbusch** [comment]
Das war ein Versehen, korrigiert

**Comment by Toelk-A** [comment]
noch immer nicht korrigiert

**Comment by chrbusch** [comment]
Bei mir war nun alles OK, auch im 1. Etikett
