### ISSUE TITLE
Datenschutz - Herstellungsliste bitte unter Spender-Daten abbilden

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#352]
Ich habe beim Ausblenden des Buttons "Herstellung" im Hauptmenü nicht zu Ende gedacht. Dr. Manecke muss Zugriff auf die Herstellungsliste habe.

Ist es möglich, die Herstellungsliste unter dem Button "Spender-Daten" abzubilden?
Hier sollen aber nur, genauso wie in der Liste "offene virolog. Beauftrag.", der Button "Det." OHNE "Kpt" abgebildet sein. Es darf keine Verknüpfung zu den Transplantatdetails geben, sondern nur zu den Spenderdetails.
 
![image](https://user-images.githubusercontent.com/22314271/39754652-334589d0-52c3-11e8-9a8c-ec50de3ead12.png)

**Comment by Toelk-A** [comment]
Hier die richtigen Buttons:

![image](https://user-images.githubusercontent.com/22314271/39755160-10072814-52c5-11e8-9b5c-d659db4b136f.png)

**Comment by chrbusch** [comment]
Es gib tnun zwei Buttons, bei den Themen "Herstellung" und "Spenderdaten"
So weit ich sehe, klappt das auch alles; bitte mit verschiedenen Accounts testen!

**Comment by chrbusch** [comment]
Hier ist nun ein "Go"-Button, der für die bösen Buben ausgeblendet wird

![bildschirmfoto 2018-05-09 um 06 40 47](https://user-images.githubusercontent.com/1241899/39795951-f31b7acc-5353-11e8-9582-983463d73184.JPG)

**Comment by Toelk-A** [comment]
erledigt
