### ISSUE TITLE
Automatische Fettung der Transplantat-KennNummer Bank

### ISSUE THREAD

**Issue by chrbusch** [chrbusch/GTM-V#354]
Ich habe eine Methode gefunden, die die KennNr automatisch teilweise fett schreibt, nicht nur auf den Etiketten, und schlage vor, dass ich das aktiviere, um Verwechselungen zu vermeiden.
Die KennNr würden dann überall so erscheinen wie die unten gezeigte "Bemerkung"

![bildschirmfoto 2018-05-15 um 08 20 27](https://user-images.githubusercontent.com/1241899/40040009-d842bf3e-5818-11e8-9796-c4ffc02e1a41.JPG)

**Comment by Toelk-A** [comment]
wir brauchen dies nur auf den Etiketten.
