### ISSUE TITLE
Statuswechsel Transplantate

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#355]
Hier MÜSSEN alle Status geloggt werden (fest allokiert, qualitätssicherung etc...) im Moment scheint nur "In Herstellung" geloggt zu sein.

Transplantat ID 2141
![image](https://user-images.githubusercontent.com/22314271/40099401-1c884192-58e0-11e8-9b8e-26f5ddb91957.png)

**Comment by chrbusch** [comment]
Das Bild zeigt die seit gestern geloggten Werte; darunter sind ganz verschiedene. Meine tests waren auch alle erfolgreich.
Bitte noch einmal kritisch testen

![bildschirmfoto 2018-05-16 um 08 56 21](https://user-images.githubusercontent.com/1241899/40101251-2b73758a-58e7-11e8-9531-93c33dbbc71e.JPG)

**Comment by chrbusch** [comment]
ich habe Tr. 2141 erneut auf "34=fest allokiert" gesetzt, und nun wird dies auch  geloggt.

**Comment by Toelk-A** [comment]
Da, die Hornhaut ja bereist versandt wurde, muss das genannate Transplantat den Status "Fest allokiert" gehabt haben. Ich frage mich warum dies nicht geloggt wurde? Ihren Status "fest allokiert" konnte ich jetzt einsehen.

**Comment by Toelk-A** [comment]
Transplantat ID 2229
Auch hier hatte ich gestern den Status auf "fest allokiert" gesetzt, dieser Status erscheint ebenfalls nicht

![image](https://user-images.githubusercontent.com/22314271/40114926-f94b4b14-590e-11e8-994d-b5e0d223d544.png)

**Comment by chrbusch** [comment]
ALLES war gestern fehlerhaft, weil die Serverfestplatte voll war!
Es können auch beliebige Teilmengen an Daten verloren gegangen sein, ohne dass man dies prüfen kann.
Bitte dies auch Dr. Nitschke mitteilen.
