### ISSUE TITLE
Patienten-ID in Aufwandsentschädigungen abbilden

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#356]
Bezüglich der neuen EU-Datenschutzrichtlinien sollen in Zukunft keine Patientennamen mehr in den Aufwandsentschädigungen abgebildet werden. Hierzu ist bereits für jeden Patienten ein Feld "Externe Patienten ID" programmiert:

![image](https://user-images.githubusercontent.com/22314271/40159020-bb373a88-59a7-11e8-8c32-a5cc0fc04f0f.png)

Über folgende Dinge muss noch nachgedacht werden:

## 1) Patienten-ID gilt pro Patient pro Klinik
Wird ein Patient nur 1 oder mehrmals pro Klinik operiert und seine Patienten ID angegeben, so kann durch die Rechnungsabteilung immer nachvollzogen werden von welchem Patienten die Rede ist.

## 2) Fallnummer vs. Patienten ID
Wird ein und derselbe Patient mehrmals in der selben Klinik operiert UND die Klinik vergibt nur Fallnummern, d.h. keine Patienten ID, so ändert sich pro Operationsdatum auch die Fallnummer.
-> Dies müsste auch in Ornella abbildbar sein. Das Heißt pro Rechnungsstellung muss auf die richtige Fallnummer zugegriffen werden.

## 3) Der selbe Patient wird in unterschiedlichen Kliniken operiert.
Wird ein Patient in Klinik X operiert so erhält er eine Patienten ID. Wechselt dieser Patient für die nächste Operation zu Klinik Y so erhält der selbe Patient eine "neue" der Klinik Y zugeordneten Patienten ID. 
-> Wie können wir dies in Ornella programmieren? Wäre es möglich der Patienten ID ein Klinikkürzel zu geben, das aber NICHT in den Aufwandsentschädigungen abgebildet wird?

## 4) Beispiel für eine Aufwandserstattung GTM-V an transplantierendes Zentrum
![image](https://user-images.githubusercontent.com/22314271/40159307-fe4bd3be-59a8-11e8-8ca9-5c929d4f95ad.png)
Zukünftig sollen hier nur die Transplantatkennummer und die PatientenID abgebildet werden    KEIN Name und KEIN Geburtsdatum

## 5) Beispiel für Aufwandserstattung GBM-V and GTM-V
![image](https://user-images.githubusercontent.com/22314271/40159351-341d6520-59a9-11e8-9479-ba3c193b1413.png)

Hier soll zukünftig nur die Transplantatkennummer abgebildet werden.

**Comment by Toelk-A** [comment]
4) funktioniert!

Bitte 5) _noch programmieren_

**Comment by chrbusch** [comment]
5) nun auch erl.

**Comment by Toelk-A** [comment]
erledigt
