### ISSUE TITLE
GBMV/ Liste Sterilitätsprüfung Rückstellproben // Vorarbeiten Dokument 3.4.3.5.1 F Herstellungsprotokoll OG Teil 2 Seite 4

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#359]
Grundlage ist Ticket #331 

Die Liste Sterilitätsprüfung benötigen wir später in erweiterter Version für das Dokument Herstellung "3.4.3.5.1 F Herstellungsprotokoll OG Teil 2 (Präparation und mikrobiologisches Monitoring Seite 4)"

![image](https://user-images.githubusercontent.com/22314271/40964273-f8d8cc3c-68aa-11e8-8469-3ace4c50a01e.png)

## 1) Welche Hornhäute sollen in der Liste Sterilitätsprüfung Rückstellproben abgebildet werden?
Zunächst sind für die Liste Sterilitätsprüfung Rückstellproben die rot markierten Spalten wichtig, d.h. es muss jeden Tag das Medium einer Hornhaut nach Versand mit den Status (Werteliste Transplantatstatus) "[34] Fest allok.; [35] verschickt; [48] zu berechnen; [36] berechnet; [44] bezahlt; [38] Rückruf" auf Trübung/Farbveränderung überprüft werden. (Versanddatum+1, Versanddatum + 2.... bis maximal 28d nach Versanddatum. 

![image](https://user-images.githubusercontent.com/22314271/40406799-576c8e3a-5e62-11e8-9b28-e49a27a979c7.png)

## 2) Ablauf der Sterilitätsprüfung Rückstellproben
Öffnen der Liste Sterilitätsprüfung Rückstellproben. Es soll gefragt werden, welcher Mitarbeiter die Sterilitätsprüfung Rückstellproben durchführt. Außerdem soll es eine Mehrfachauswahlmöglichkeit (für die zu prüfenden Transplantate) sowie 2 Buttons geben.

### 2.1) Programmierung "Wer führt Sterilprüfung durch?"

(Dies ist bereits im Ticket #357 programmiert und muss nur an die neue Liste angepasst werden)

Bei Klick auf die Liste Sterilitätsprüfung muss gefragt werden "Welcher Mitarbeiter führt die Sterilitätsprüfung durch?" Hier soll die Werteliste der Mitarbeiter Herstellung (GBM-V) abgebildet werden:

![image](https://user-images.githubusercontent.com/22314271/40406872-9dff7b14-5e62-11e8-934f-b5159284425c.png)

-> Dies soll dann für den Tag X der Sterilitätsprüfung Rückstellproben gleichzeitig geloggt werden und im Dokument 3.4.5.1 F Herstellungsprotokoll OG Teil 2 Seite 4 Spalte "Signum MA GBM-V" der jeweiligen Hornhaut (Achtung, dies können 20 oder mehr Transplantate sein) abgebildet werden.

![image](https://user-images.githubusercontent.com/22314271/40406912-c92beb42-5e62-11e8-9072-5ff684b6611d.png)

### 2.2) Programmierung Button "Steril"

(Dies ist bereits im Ticket #357 programmiert und muss nur an die neue Liste angepasst werden)

-> Mit der Mehrfachauswahl werden alle Hornhäute angeklickt, die "steril"sind und danach auf den Button "steril" geklickt. Das heißt die Hornhaut bekommt den Status am Tag X, war ich steril, was wiederum automatisch ein "nein" im Dokument 3.4.5.1 F Herstellungsprotokoll OG Teil 2 Seite 4 Spalte "Mediumkontrolle: Trübung/Farbveränderung?" bedeutet.

![image](https://user-images.githubusercontent.com/22314271/40407150-bf4b9e50-5e63-11e8-8f93-1d48d390c512.png)

### 2.3) Programmierung Button "Trübung"

(Dies ist bereits im Ticket #357 programmiert und muss nur an die neue Liste angepasst werden)

-> Mit der Mehrfachauswahl werden alle Hornhäute angeklickt, die "trüb"sind und danach auf den Button "Trübung" geklickt. Das heißt die Hornhaut bekommt den Status am Tag X, war ich trüb, was wiederum automatisch ein "ja" im Dokument 3.4.5.1 F Herstellungsprotokoll OG Teil 2 Seite 4 Spalte "Mediumkontrolle: Trübung/Farbveränderung?" bedeutet.

![image](https://user-images.githubusercontent.com/22314271/40407267-2867d69c-5e64-11e8-97ac-a3a8aae179e5.png)

**2.3.1.) Wiedervorlage bei Trübung**
Wird der Button Trübung geklickt, so soll eine Wiedervorlage an NIF und KNA rausgehen. Pro trüber Hornhaut soll eine Wiedervorlage erstellt werden.

**2.3.2.) Trübung = zusätzliche Sterilkontrolle**
Wird der Button "Trübung" geklickt, so muss eine _zusätzliche_ Sterilkontrolle durchgeführt werden. Das heißt:

A) Wir benötigen ein weiteres "Solldatumseingabefeld" = "Sterilitätsprüfung Rückstellproben"

![image](https://user-images.githubusercontent.com/22314271/40407557-1a31ce06-5e65-11e8-9ff0-0e311a84bcfc.png)

B) Es soll gefragt werden "Wird die Sterilkontrolle Rückstellproben heute oder morgen durchgeführt?" dementsprechend soll auch ein "heute" und "morgen" Button programmiert werden und das Datum als "ISTdatum übernommen werden - Routinekalender.

C) Jenachdem wann die unter B) genannte Sterilkontrolle Rückstellproben durchgeführt wird, so muss auch dieses Datum geloggt werden und ein Kreuz im Dokument 3.4.5.1 F Herstellungsprotokoll OG Teil 2 Seite 4 Spalte "Probennahme für Mikrobiologie" gesetzt werden.

**Comment by chrbusch** [comment]
Damit Sie dies ggfs. selbst anpassen können, hat in der Tabelle der Status nun das Ankreuzfeld "Sterilprfg.?" eine neue Option "RS=Rückstellproben. Bitte kreuzen Sie die Status an, bei denen dies geschehen soll. Ich programmiere dies dynamisch so, dass stets mit Kreuz bei "RS" in der Liste beachtet werden.

**Comment by Toelk-A** [comment]
Status für RS sind angekreuzt

**Comment by chrbusch** [comment]
Es sollten jetzt diese Prüfungen im Routinekalender erscheinen, bitte testen.
Ich nehme an, das auch hier nur der jeweils erste Eintrag gezeigt werden soll und erst bei Klick auf "Liste" sämtliche anstehenden Aufgaben?!

**Comment by Toelk-A** [comment]
## Ich nehme an, das auch hier nur der jeweils erste Eintrag gezeigt werden soll und erst bei Klick auf ## "Liste" sämtliche anstehenden Aufgaben?!

ja

**Comment by chrbusch** [comment]
Ich denke, das läuft jetzt alles, bitte testen.
Ich gehe heute an das Drucklayout dieses Dokuments.

**Comment by Toelk-A** [comment]
Bitte erst die Mail von Frau Schröder bearbeiten, da sonst ggf. "falsche" Kreuze gesetzt werden.

**Comment by chrbusch** [comment]
Das ganze Dokument (Seite 1 bis4) ist m.E. bis auf Kleinkram fertig, Freitag gemeinsam testen!
