### ISSUE TITLE
Entnahmebericht OG - Feld  "Verwendete Materialien"

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#36]
Wenn CSK zur Hornhautbank München gehen, muss es möglich sein im Feld "Verwendete Materialien" die Koffernummer manuell einzutragen. Der Koffer wird uns durch die Hornhautbank München zur Verfügung gestellt und beinhaltet das Präparierbesteck. Jeder Koffer ist mit einer Nummer versehen, die nach der Benutzung auf dem Entnahmeprotokoll eingetragen werden muss.

![image](https://cloud.githubusercontent.com/assets/22314271/19963617/878a351c-a1bd-11e6-8bb5-26882db947b9.png)

**Comment by chrbusch** [comment]
Dieses Feld ist jetzt neu rechts über dem gr. Materialfeld; so OK?

![bildschirmfoto 2016-11-08 um 09 55 03](https://cloud.githubusercontent.com/assets/1241899/20092618/735dc268-a599-11e6-9d6f-d74859717e63.JPG)

**Comment by Toelk-A** [comment]
Ja das Feld ist in Ordnung. 
Regel: WENN gewebeprozessierende Einrichtung Hornhautbank München gemeinnützige GmbH, dann benötigen wir das Feld Koffernummer, SONST nicht.

**Comment by chrbusch** [comment]
So etwas möchte ich nicht als Regel ins Programm integrieren, da es sich ja jederzeit ändern kann!
Der Anwender kann dieses Feld ausfüllen, muss aber nicht.

**Comment by Toelk-A** [comment]
Das Feld "Koffernummer" bitte nur in den Entnahmebericht OG. In allen anderen Entnahmeberichten ist  dieses Feld nicht notwendig.

![image](https://cloud.githubusercontent.com/assets/22314271/20100838/84f3d064-a5bf-11e6-960f-805919c4d083.png)

**Comment by chrbusch** [comment]
Ist zwar erledigt - aber m.E. sollten wir zur Zeit kein Geld verbrennen mit unwichtigen Details.
Man kann das Feld ja leer lassen.
Das alles ist m.E. etwas für ein späteres fine tuning.
