### ISSUE TITLE
Mandant GBM-V, Zugriffsrechte

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#360]
### 1) OG Entnahmebericht aus Prozessschritten GTM-V auch in den Prozesschritten GBM-V abbilden

Die Mitarbeiterinnen der Bank (GBMV) benötigen den EntnahmeBericht-OG (Spenderdetails - Prozessschritte), d.h. dieser soll in den Prozessschritten der GBM-V (Transplantatdetails - Reiter Prozessschritte) abgebildet werden. 

Spenderdetails-Prozessschritte
![image](https://user-images.githubusercontent.com/22314271/40466736-42acc1fc-5f27-11e8-8b5a-97aa0e4e7a06.png)

Transplantatdetails Prozessschritte
![image](https://user-images.githubusercontent.com/22314271/40466918-0a1509b6-5f28-11e8-9393-c7ad8c4f9509.png)

Die Mitarbeiter der GBMV dürfen aber nur eine "Leseberechtigung" und die _PDF-Funktion_ haben.

-> Nach Klick auf den Button EntnahmeBericht OG öffnet sich folgendes Fenster:

![image](https://user-images.githubusercontent.com/22314271/40467047-8bb78836-5f28-11e8-976c-58411e80683f.png)

-> Hier könnte man einen Button Lesefunktion für den **Mandanten GBM-V** einfügen und die anderen Button (Neu, bearbeiten) unsichtbar machen.

### 2) PDF - Funktion Strg+5 darf nicht auf Spendermaske zurückführen

Strg+5 zeigt folgendes Fenster:

![image](https://user-images.githubusercontent.com/22314271/40467130-ebb2f9b4-5f28-11e8-9096-156ee667e149.png)

Klick auf "Ja" erzeugt PDF und erstellt das folgende Fenster:

![image](https://user-images.githubusercontent.com/22314271/40467176-1cf6f9e4-5f29-11e8-9c85-ecdef16efd70.png)

-> Die GBM-V darf nicht zur Spendermaske weitergeleitet werden können. Das heißt, hier müsste der Button "Ja" ausgeblendet werden ODER, was besser wäre, direkt zu den Transplantatdetails - Prozesschritte zurückgekehrt werden.  Dies bitte für alle Prozesschritte -> Strg+5 -> PDF Erstellung der GBM-V prüfen und ggf. umprogrammieren.
 
### 3) Tastenkombination Strg+4 Zugang Prozessschritte Spenderdetails blocken

Die Mitarbeiter der GBM-V können über die Tastenkombination Strg+4 auf die Prozessschritte der Spenderdetails zugreifen. Dies darf nicht möglich sein.

### 4) Zugriff auf Reiter Spenderdetails - Reiter "Gew./Pr./Tr" sichern
Die Mitarbeiter der GBM-V legen die Transplantate über den in der Überschrift genannten Reiter und die Buttons "Transpl. wählen" an. 

![image](https://user-images.githubusercontent.com/22314271/40467708-2c0d4abc-5f2b-11e8-84f8-3651e194ede3.png)

Das heißt, sie benötigen Zugriff auf den Reiter und den Button "Transpl. wählen", dürfen aber nicht die anderen Reiter öffnen können.

### 5) Button Herstellung initiieren (Transplantatdetails) darf nicht auf Spendermaske zurückführen

Wird der Button geklickt, so werden die Prozessschritte "Herstellung" in den Prozessschritten Spenderdetails erstellt. Dies soll zukünftig nur bei den Transplantatdetails erfolgen (Reiter Prozessschritte bereits programmiert). Das heißt, nach dem Klick auf den Button "Herstellung initiieren" soll auf die Prozessschritte in den Transplantatdetails NICHT Spenderdetails weitergeleitet werden.

![image](https://user-images.githubusercontent.com/22314271/40472015-96452e6a-5f38-11e8-9a7c-24bf0497027d.png)

**Comment by chrbusch** [comment]
2) und 3) sind m.E. erledigt.
Wegen der anderen Punkte müssen wir sprechen.

**Comment by chrbusch** [comment]
5) Button Herstellung initiieren…
ist erledigt

**Comment by chrbusch** [comment]
Mit dem neuen Button unter den Prozessschritten beim Transplantat ist nun auch 1) erledigt.
Zu a4) muss ich aber noch nachdenken, wie man das ohne Datenschutzproblem programmieren kann

**Comment by chrbusch** [comment]
Ad 4) Hier müssen wir überlege, wie die GBMV-Mitarb. den Spender ansteuern sollen.
Button "Spenden suchen" haben sie ja nicht!

**Comment by chrbusch** [comment]
Habe, von obigem Problem abgesehen, alles programmiert; gemeinsam ansehen bitte!

**Comment by chrbusch** [comment]
Ich habe nun die Präparate-Liste "aufgepeppt" und dort, wie besprochen, den Button "Transplantate wählen" platziert.
Mir scheint, dass dies alles funktioniert - ich habe es gerade mit einer Dame aus der Bank durch gespielt

**Comment by Toelk-A** [comment]
Ist die Tastenkombination Strg+3 auch für die GBM-V Mitarbeiter gesperrt worden?

**Comment by Toelk-A** [comment]
Mandant GTMV
Bitte Tastenkombination Strg+7 sperren

**Comment by Toelk-A** [comment]
6) Nach Druck "Strg+5" muss eine Möglichkeit bestehen in die Transplantatdetails zurückzukehren. Im Moment ist das Öffnen der Prozessschritte bei den Transplantatdetails ein "Dead End".

**Comment by chrbusch** [comment]
Strg-7 nun gesperrt für GTMV

**Comment by chrbusch** [comment]
Ad 6) Strg-4 führt zur Spendermaske, wenn das System auf der aktuellen Maske irgendeinen Bezug zu einem Spender erkennt; das darf GBMV aber sowieso nicht.
Soll ich bei diesen Kollegen das System bei Strg-4 stets zum aktuellen TRANSPLANTAT zurück kehren lassen?

**Comment by Toelk-A** [comment]
## 7. Soll ich bei diesen Kollegen das System bei Strg-4 stets zum aktuellen TRANSPLANTAT zurück kehren lassen?
-> Ja unbedingt

## 8. USER NIB darf keinen Zugang zur Spendermaske haben
Dr Nitschke loggt sich als NIB ein und gibt dann die "Arztfreigabe" Die muss unterbunden werden

![image](https://user-images.githubusercontent.com/22314271/40823388-55eb3434-6570-11e8-9da2-80cb92f3d504.png)

## 9. Transplantatliste Button "Spendermaske"
Hierüber darf ebenfalls keien Verknüpfung zum Öffnen der Spendermaske mehr möglich sein

![image](https://user-images.githubusercontent.com/22314271/40823431-80bebee2-6570-11e8-8435-70f4b582e6d7.png)

**Comment by chrbusch** [comment]
7) ist erl.

**Comment by chrbusch** [comment]
Zu 8) habe ich Fragen, bitte anrufen
9) ist erl.

**Comment by chrbusch** [comment]
Ad 8) Wie gelangt denn NIB zur Spendermaske?
