### ISSUE TITLE
Mandant GTM-V Zugriffsrechte

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#361]
Dieses Ticket gilt nur für den Mandanten GTM-V

## 1) Button "Transplantat wählen" ausblenden

![image](https://user-images.githubusercontent.com/22314271/40724649-cf32ba60-6421-11e8-83e5-9256690d580a.png)

## 2) Strg+7 "Allokationsliste" blocken
Bitte die Buttonkombination Strg+7 blocken

**Comment by chrbusch** [comment]
Beides erl.
