### ISSUE TITLE
Dokumente aus Prozesschritten GBMV nur bei Transplantatdetails ablegen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#362]
Im Moment werden die PDF´s aus den Prozesschritten (Transplantatdetials) in dem Reiter Dokumente (Spenderdetails) abgelegt. Das darf nicht sein. 

![image](https://user-images.githubusercontent.com/22314271/40833605-af7a2672-658e-11e8-9970-5d2d9d05afca.png)

Bitte programmieren, dass die PDFs der Transplantatdetails im Reiter Dokuemente Transplantatdetails abgelegt werden. Wir müssen Spende und Herstellung trennen.

**Comment by chrbusch** [comment]
Ist erledigt; wegen der großen Bedeutung der Dokumentation bitte aufmerksam testen mit Testspendern

**Comment by chrbusch** [comment]
Wir können nun für bel. Dokumente entscheiden, ob sie beim Spender oder Transplantat abgelegt werden sollen.
Und ich frage mich, ob Prozessschritte vom Typ H=Herstellung überhaupt auf die Spendermaske sollen? Oder wäre es sinnvoll, diese alle nur beim Transplantat zu zeigen?

**Comment by Toelk-A** [comment]
erledigt
