### ISSUE TITLE
Prozessschritte Herstellung NICHT in Spenderprozessschritten abbilden

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#363]
Bitte deaktivieren Sie die Filter zu Herstellung udn Allokation in den Prozesschritten Spende.

![image](https://user-images.githubusercontent.com/22314271/40833684-e56efd34-658e-11e8-86f8-30000ce8b8be.png)

**Comment by chrbusch** [comment]
Erl.

**Comment by Toelk-A** [comment]
erledigt
