### ISSUE TITLE
Routinekalender - Liste Sterilitätsprüfung - kleine Änderungen Abbildung

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#364]
## 1) Sterilitätsprüfung als letzten Punkt pro Tag im Kalender abbilden

Der Übersicht halber bitte die Sterilitätsprüfung als letzten Punkt pro Tag im Routinekalender abbilden.

## 2) Punkt Sterilitätsprüfung - Transplantate ausblenden
Bitte unter dem Punkt Sterilitätsprüfung die Transplantate ausblenden. Die Transplantate werden in der Liste abgebildet. Dies ist für die Mitarbeiterinnen ausreichend. Es wird außerdem übersichtlicher wenn nicht mehr 50 Transplantate im Routinekalender abgebildet sind. Alle anderen Transplantate sollen weiterhin abgebildet bleiben. Es sollen nur die Transplantate für die Sterilitätsprüfung ausgeblendet werden.

**Comment by chrbusch** [comment]
Wenn die SterilPrüfung am Ende erscheint - müssen dann die Transplantate verborgen werden?
Jedenfalls kann, wenn ich die Transplantate dort ausblende, dort auch kein Button "Zur Liste" nicht gezeigt werden.

**Comment by chrbusch** [comment]
Weil so ein Bereich, in dem irgendetwa erscheint, zu einem Datensatz gehört.
Daher zeige ich nun, wie besproche, das erste Transplantat f.d. Sterilprüfung (testbar ca. ab 8h)

**Comment by chrbusch** [comment]
Das scheint mir schon zu klappen; auch werden nun für Tr. 2200 die beiden gestern automatisch erzeugten "Sterilktr nach Trübung" angezeigt.
![bildschirmfoto 2018-06-06 um 07 35 00](https://user-images.githubusercontent.com/1241899/41018865-5342dbde-695c-11e8-9a27-7f6837ebb9f1.JPG)

**Comment by Toelk-A** [comment]
super. Dann ist das Thema "Outlookansicht" für den Routinekalender abgearbeitet.

**Comment by chrbusch** [comment]
...mir fällt aber noch ein Problem ein: zZ erstellen wir ja stets erst beim Aufruf die RK die SterilPrüfungen für MORGEN.
Aber reicht das am Donnerstag & Freitag?
Natrülcih kann ich die SterKtr 4 Tage voraus erstellen, aber dann sind die Daten u.U. nicht aktuell, weil Transplantate hinzu kommen und andere verworfen werden.
Idee??

**Comment by chrbusch** [comment]
Andererseits scheint es ja JEDEN Tag SterilPrüfungen zu geben, so dass dies ohnehin klar ist.

**Comment by Toelk-A** [comment]
Derzeit wird die Liste Sterilprüfungen NICHT im Routinekalender abgebildet. Bitte Programmierung prüfen

**Comment by chrbusch** [comment]
Ich bin heute nicht im Büro, oder erst spät.
Wissen Sie, seit wann dieses Problem auftritt?

**Comment by Toelk-A** [comment]
Das Problem besteht wohl schon länger. Allerdings wurde es mir nicht berichtet.

**Comment by chrbusch** [comment]
Bitte jetzt erneut kritisch testen!
