### ISSUE TITLE
GBMV/ Liste G) Sterilitätsprüfung KMII // Vorarbeiten Dokument 3.4.3.5.1 F Herstellungsprotokoll OG Teil 2 Seite 3

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#365]
Grundlage ist Ticket #331 

Die Liste Sterilitätsprüfung KMII benötigen wir später in erweiterter Version für das Dokument Herstellung "3.4.3.5.1 F Herstellungsprotokoll OG Teil 2 (Präparation und mikrobiologisches Monitoring Seite 3)

![image](https://user-images.githubusercontent.com/22314271/40963576-4194a538-68a9-11e8-97d3-d0adcd5212a6.png)

-> Die Programmierung entspricht "Sterilkontrollen", nur dass sich in diesem Ticket auf ein anderes Datumsfeld bezogen werden muss: "Lagerung in Transportmedium" bis +maximal 6d

![image](https://user-images.githubusercontent.com/22314271/40963985-3cf8a712-68aa-11e8-90ad-fffd8dc0c9b3.png)

## 1) Welche Hornhäute sollen in der Liste Sterilitätsprüfung abgebildet werden?

![image](https://user-images.githubusercontent.com/22314271/40963906-faa44ede-68a9-11e8-8af6-f3e80a88708b.png)

Zunächst sind für die Liste Sterilitätsprüfung KMII die rot markierten Spalten wichtig, d.h. es muss jeden Tag das Medium einer Hornhaut mit den Status (Werteliste Transplantatstatus) "[31] in Herstellung; [32] Frei z. Allok.; [33] Reserviert; [34] Fest allok.; [39] Sperre; [30] Freigabe gemäß.... " auf Trübung/Farbveränderung überprüft werden. (Lagerung in Transportmedium +1d, Lagerung in Transportmedium +2d bis maximal 6d nach Lagerung in Transportmedium, dann muss die Hornhaut verworfen werden -> im Prinzip entsprechen die maximal 6d nach Umlagerung in Transportmedium "Datum Haltbarkeit". Wird die Hornhaut vorher versandt (Bezug zum Feld "Versanddatum"), dann muss dementsprechend weniger Tage das Medium überprüft werden.

Der Weitere Ablauf soll programmiert werden wie im Ticket Sterilitätsprüfung #357

**Comment by chrbusch** [comment]
Auch diese Prüfungen erscheinen nun im Routinekalender, bitte prüfen

![bildschirmfoto 2018-06-12 um 10 09 15](https://user-images.githubusercontent.com/1241899/41277865-af7735e6-6e28-11e8-8447-6d3a9021e393.JPG)

**Comment by Toelk-A** [comment]
Bitte die Mail von Frau Schröder abarbeiten

**Comment by chrbusch** [comment]
Mir ist nicht klar, was an diesem Ticket noch offen ist.
Bitte Update hier schreiben
