### ISSUE TITLE
Mandant GTMV Patientendaten in Transplantatherstellungsliste abgebildet 

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#366]
Mandant GTMV

Button "Offene virolog. Beauftragung"

Sind die Transplantate bereits fest allokiert, so kann man die Patientendaten sowie transplantierende Einrichtung sehen. Dies muss unbedingt ausgeblendet werden. An Stelle dessen bitte das Versanddatum des Transplantates abbilden.

![image](https://user-images.githubusercontent.com/22314271/41042372-c8d97cc8-69a1-11e8-8159-24187ba5b35a.png)

**Comment by chrbusch** [comment]
Erledigt.
Wird der blaue Abrechnungsbutton hier benutzt?

![bildschirmfoto 2018-06-07 um 08 36 07](https://user-images.githubusercontent.com/1241899/41082258-fa9d1954-6a2d-11e8-8b39-83c0b688cf14.JPG)

**Comment by Toelk-A** [comment]
## Wird der blaue Abrechnungsbutton hier benutzt?
Nein, Niemals dort abbilden bitte.

**Comment by chrbusch** [comment]
Entfernt
