### ISSUE TITLE
Artikel Mandant GBM-V werden im OG-Entnahmebericht GTMV abgebildet

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#367]
Spender ID 4958

Aus irgendeinem Grund wurden 2 Artikel der GBM-V in dem Entnahmebericht OG der GTMV abgebildet. Bitte prüfen und unbedingt korrigieren.

![image](https://user-images.githubusercontent.com/22314271/41043032-4f79d0f6-69a3-11e8-8892-9f3ee698f763.png)

**Comment by chrbusch** [comment]
Das System kennt gar keine Zuordnung von Artikeln zu Mandanten; aber vllt. sollten wir dies einrichten?
Dem SpenderGewebe ist der TEST-Warenkorb 22 zugeordnet ! Und darin sind diese beiden Positionen. Im System ist daher mE. alles korrekt - nur sind die Daten anscheinend falsch erfasst, bitte prüfen

![bildschirmfoto 2018-06-07 um 08 46 19](https://user-images.githubusercontent.com/1241899/41082635-4686ec40-6a2f-11e8-84c7-a382b41b168c.JPG)

**Comment by Toelk-A** [comment]
Wir haben das Ganze intern überprüft. Der Barcode ist bereits verworfen, sodass wir den Scann nicht mehr nachvollziehen können.
