### ISSUE TITLE
Unterschriftenfeld: Koordinator/Entnehmer nicht ankreuzbar (Entnahmebericht) 

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#37]
wenn Koordinator angekreuzt wird sollte der Koordinator der Spenderakte (siehe Kennnummer) eingetragen werden. Wenn Entnehmer angekreuzt wird Drop-Down mit einer Entnehmerliste. Entnehmerliste rekrutiert sich aus den natürlichen Personen und der Funktion Entnehmer. 

Antwort Dr Busch:

Diese Funktion gibt es bislang gar nicht! Ich habe sie jetzt eingeführt und bitte Sie, die entsprechenden Personen hier zu markieren. Danach kann ich dann eine Auswahl programmieren

Antwort A.Tölk

Habe ich Zugriff auf die Personen? Wenn ja, wo kann ich diese in Ornella finden?

Ansonsten müsste Dr. Nitschke assigned werden, da er Administratorrechte hat.

Antwort Dr. Busch:
Administratorrechte haben nur wir; Dr. N. ist "Supervisor"
Aber diese Rechte benötigen Sie nicht!
Einfach die Personen suchen und bei den Funktionen die neuen Option "Entnehmer" ankreuzen

Antwort A.Tölk

Wo genau kann ich nach Personen in Ornella suchen?

Antwort Dr Busch:
Button "Adresse suchen" klicken, Namen eingeben

Antwort A.Tölk
funktioniert nicht
![image](https://cloud.githubusercontent.com/assets/22314271/20051074/4f1e920a-a4cd-11e6-812c-a3505c3317e3.png)

Antwort Dr. Busch

Wie sollte es auch, Sie sind ja nicht als Adresse erfasst.
Oder möchten Sie USER (ANWENDER) suchen?
Ich denke, eher Adressen, denn es geht ja hier um die "Entnehmer"
Bitte möglichst immer dazu schreiben was Sie erreichen möchten.

PS: Bisher ist keine einzige Adresse als "Entnehmer" markiert.

**Comment by Toelk-A** [comment]
wir benötigen im Entnahmebericht die Option Entnehmer oder Koordinator ankreuzen zu können (Funktioniert bereits). Koordinator entspricht Koordinator in der Spendermeldung. Entnehmer kann unterschiedlich vom Koordinator sein (Entnehmer = Drop-Down mit einer Entnehmerliste. Entnehmerliste rekrutiert sich aus den natürlichen Personen und der Funktion Entnehmer). 

Können Sie bitte den Dropdown erstellen oder mir erklären wie ich die natürlichen Personen als "Entnehmer" markieren kann?

**Comment by Toelk-A** [comment]
Entnehmer = Mitarbeiter der GTM-V, die nicht als Koordinator des Spenders eingetragen sind

**Comment by chrbusch** [comment]
Es gibt nun unter dem Ankreuzfeld ein Feld zur Auswahl des GTMV-Mitarbeiters, ist das so OK?

![bildschirmfoto 2016-11-07 um 11 47 34](https://cloud.githubusercontent.com/assets/1241899/20055140/0e5293bc-a4e0-11e6-8b30-e8071548d474.JPG)

**Comment by chrbusch** [comment]
Brauchen Sie unter dem Ankreuzfeld links auch so eine Mitarbeiterauswahl?

**Comment by Toelk-A** [comment]
ja bitte, aber nur für das ärztliche Personal

**Comment by chrbusch** [comment]
OK, das ist jetzt so.
Bitte künftig die im Programm verwendeten Bezeichnungen nehmen, um Mißverständisse zu vermeiden.
"Personen" gibt es ja dort nicht, sondern "User" und "Adressen"; die ersten gehören zu GTMV/GBMV, während Adressen beliebige Firmen, Institutionen oder Personen sind

**Comment by Toelk-A** [comment]
funktioniert :+1:
