### ISSUE TITLE
Monatsstatistik - Einfügen Anzahl Meldungen pro Monat pro Station

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#370]
Für die Monatsstatistik benötigen wir noch die "Anzahl Meldungen pro Monat pro Station" in unserem Anschreiben. Ich habe bereits die Textbausteine verändert, Sie müssten nur noch das Feld "Anzahl Meldungen" programmieren.

**Comment by chrbusch** [comment]
Rennt…

![bildschirmfoto 2018-06-08 um 08 44 58](https://user-images.githubusercontent.com/1241899/41143063-41298982-6af8-11e8-8af9-4700c0b89496.JPG)

**Comment by Toelk-A** [comment]
erledigt
