### ISSUE TITLE
Liste Sterilitätsprüfung - fehlende Transplantate

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#371]
Die folgenden Transplantate wurden am 07.06.2018 hergestellt, d.h. sie müssen ab 08.06.18 in der Liste Sterilitätsprüfung erscheinen
Transplantat ID:
- 2376
- 2375
- 2374

Bitte die Programmierung prüfen

**Comment by chrbusch** [comment]
Ja, es musste das Script zur Erstellung der Erinnerungen auch für den HEUTIGEN Tag aufgerufen werden, sonst erscheinen neue Transplantate einen Tag zu spät auf der Liste.
Ich habe das Servervscript nun so erweitert, dass es mit einem beliebigen Datum aufgerufen werden kann, so dass wir ohne Aufwand (auch für andere Prozesssschritte) nun eine Vorschau der erwarteten Arbeiten erhalten können.

**Comment by Toelk-A** [comment]
Es wurde das Skript für den 08.06.18 aufgerufen und die o.g. Transplantate erschienen NICHT in der Liste

**Comment by chrbusch** [comment]
Ja, eben; dieses Script wurde doch wohl **am** 8.6.2018 aufgerufen, und dabei wurden die Einträge für den 9. (!) 6. erstellt.
Nun werden aber beim Aufruf Einträge **für heute und morgen** geprüft/angelegt, und es sollte passen
