### ISSUE TITLE
Liste Sterilitätsprüfung - Statusänderung des Transplantates  

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#372]
Nachdem die Sterilitätsprüfung morgens durchgeführt, kann sich im Laufe des Tages immer noch einmal der Status eines Transplantates ändern. Läuft nach wie vor nachts ein Skript, das die Liste Sterilitätsprüfung für den kommenden Tag erstellt?`

Es kann passieren, dass aufgrund einer medizinischen Kontraindikation ein Transplantat vom Status "In Herstellung" in den Status "Qualitätssicherung" wechselt. Diese darf dann nicht mehr in der Liste Sterilitätsprüfung abgebildet werden.

**Comment by chrbusch** [comment]
Ich konnte das Script zur Prüfung und Anlage der Routinekalender-Punkte so beschleunigen, dass es nicht mehr auf dem Server laufen muss; es wird jetzt jedes Mal frisch gestartet, wenn man den RK aufbauen lässt. Daher sollte es m.E. hier keine Probleme geben.
Ggfs. mit einem Testransplantat ausprobieren…
