### ISSUE TITLE
GBMV/ Herstellungsprotokoll OG Teil 2, Abbruchbedingungen

### ISSUE THREAD

**Issue by chrbusch** [chrbusch/GTM-V#373]
Hier soll beschrieben werden, welche Prüfungen/Kontrollen bei gewissen Ergebnissen zum ABBRUCH der Aufgabenketten des RK (RoutineKalender) führen sollen.

Mein bisheriger Wissensstand (bitte ggfs. korrigieren):
A) Führt eine SterilPrüf. des Transplantates zum Ergebnis "Trübung", so gibt es keine weiteren derartigen Prüfungen.

B) Führt eine SterilPrüf. der RS-Probe zum Ergebnis "Trübung", so gibt es keine weiteren derartigen Prüfungen.

**Comment by Toelk-A** [comment]
## Hier soll beschrieben werden, welche Prüfungen/Kontrollen bei gewissen Ergebnissen zum ABBRUCH ## der Aufgabenketten des RK (Routinekalender) führen sollen.

-> Es wird nicht der RK abgebrochen, sondern die Listen zur Sterilitätsprüfung. Alle weiteren Listen werden über die manuelle "Solldatumseingabe" der Mitarbeiterinnen Herstellung reguliert.


## A) Führt eine SterilPrüf. des Transplantates zum Ergebnis "Trübung", so gibt es keine weiteren ## derartigen Prüfungen.
-> Es wird ebenfalls eine Sterilkontrolle von der Partnerhonrhaut gezogen. Die Partnerhornhaut belibt weiterhin in der Sterilitätsprüfung. Die "trübe" Hornhaut erhält einen Abbruch.

## B) Führt eine SterilPrüf. der RS-Probe zum Ergebnis "Trübung", so gibt es keine weiteren derartigen Prüfungen.
-> Ergebnis Trübung in der RS Probe = Abbruch. Es wird trtozdem eine Sterilkontrolle RS gezogen um den Keim zu identifizieren.
