### ISSUE TITLE
Mobiles Entnahmeteam - Adressat nicht richtig zugeordnet

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#374]
OG in Schwedt = Brandenburg -> Adresse richtig

![image](https://user-images.githubusercontent.com/22314271/41467350-7a317eca-70a6-11e8-9ba7-0821ff3b3739.png)

MSG in Pasewalk = Mecklenburg Vorpommern -> Adresse aus Brandenburg NICHT Mecklenburg-Vorpommern abgebildet

![image](https://user-images.githubusercontent.com/22314271/41467418-c0da0b94-70a6-11e8-87c7-e0e9c5a5868d.png)

**Comment by chrbusch** [comment]
Die Topadresse (ID 50) zur Meldestation (ID 121) hat als Bundeslandkürzel "BB", daher erscheint mir alles richtig!
![bildschirmfoto 2018-06-16 um 09 09 12](https://user-images.githubusercontent.com/1241899/41496648-07152cda-7145-11e8-8480-6e54dc37fbfa.JPG)

**Comment by chrbusch** [comment]
![bildschirmfoto 2018-06-16 um 09 12 00](https://user-images.githubusercontent.com/1241899/41496659-5a3369fe-7145-11e8-9a4d-69e436bb622a.JPG)

**Comment by chrbusch** [comment]
Anbei ein XLS-Export aller 41 Adresse mit Bundesland="BB", bitte prüfen/korrigieren

[Adressen_aus_BB.xlsx](https://github.com/chrbusch/GTM-V/files/2107929/Adressen_aus_BB.xlsx)

**Comment by Toelk-A** [comment]
Schwedt liegt in Brandenburg, das ist richtig. Es geht aber um Pasewalk. Bitte noch einmal oben lesen.

**Comment by chrbusch** [comment]
Für die Entbnahmeadresse (ID 121) selbst ist gar kein Bundeslandkürzel erfasst, daher holt sich das System die Info von der Topadresse; dort steht "BB"

**Comment by chrbusch** [comment]
Ich habe diesen Fall nun in die Plausib.-Prüfung aufgenommen:

![bildschirmfoto 2018-06-18 um 10 34 53](https://user-images.githubusercontent.com/1241899/41526059-494b8636-72e3-11e8-9ecb-63625053b723.JPG)
