### ISSUE TITLE
KVG Datum Haltbarkeit + PKS code nicht vollständig/fehlen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#375]
Sehr dringend!!!

KVG Maske 

1) Das Datum Haltbarkeit wird nicht erstellt.

2) Der PKS Code ist unvollständig generiert. 

Wir bekommen heute Nacht KVG Material . Bis dahin muss die Dokumentation funktionieren.

Vielen DANK

![image](https://user-images.githubusercontent.com/22314271/41468989-0594dc28-70ac-11e8-9013-71d09eb4a479.png)

**Comment by chrbusch** [comment]
Ad 1.) Das DatumHaltbarkeit wird mit einer Formel berechnet aus dem Datum der Lagerung im TransportMedium, ProzessSchrittID 126. Aber zu den KVG-Transplantaten gibt es keine Prozessschritte.
Wie SOLL das Datum hier berechnet werden?

**Comment by chrbusch** [comment]
![bildschirmfoto 2018-06-16 um 08 47 12](https://user-images.githubusercontent.com/1241899/41496515-e4de03ba-7141-11e8-9601-3e237be404bc.JPG)

**Comment by chrbusch** [comment]
Dadurch erscheint nun auch ein vollständiger PKS-Code.
Aber VORSICHT, wenn wir die Berechnungsmethode der Haltbarkeit wieder ändern, ÄNDERT SICH der PKS-Code, da er dynamisch von den Daten abhängt.

**Comment by chrbusch** [comment]
![bildschirmfoto 2018-06-16 um 08 50 08](https://user-images.githubusercontent.com/1241899/41496537-4f8dc9b6-7142-11e8-918c-a6fecf173d2a.JPG)

**Comment by Toelk-A** [comment]
Ich glaube Sie haben KVG und OG verwechselt Herr Busch. KVG wird nie in ein Transportmedium gelagert. Ich bitte dringend um Rückruf da nun wahrscheinlich ein falscher PKS auf dem KVG Produkt erstellt wurde.

**Comment by Toelk-A** [comment]
Was ist hier passiert? In der Maske OG Transplantatdetails wurde ein KVG Transplantat angelegt.

![image](https://user-images.githubusercontent.com/22314271/41520356-89fd0850-72cd-11e8-8fcf-e338587a3ad8.png)

**Comment by chrbusch** [comment]
Habe gerade gesehen, dass es sich teilweise um GELÖSCHTE Transplantate handelt!
Bei diesen weiss das System nicht, wie sie zu behandeln sind.
Ich denke, wir müssen bei Klick auf den Löschbutton die Transplantate wieder so wie früher tatsächlich löschen, nicht nur deaktivieren; letzteres schafft zu viele unerwartete Probleme

**Comment by chrbusch** [comment]
". KVG wird nie in ein Transportmedium gelagert."
Ich brauche dann nur eine Regel die besagt, wie die Haltbarkeit für KVG errechnet werden soll; was ist das Startdatum dieser Berechnung?

**Comment by Toelk-A** [comment]
Es scheint wieder zu funktionieren

![image](https://user-images.githubusercontent.com/22314271/41537548-19e2e10c-7309-11e8-804b-611c51db43f6.png)

**Comment by chrbusch** [comment]
Ja, weil ich jetzt bei KVG das Datum_Herstellung nehme; aber ist das richtig so?

**Comment by Toelk-A** [comment]
Datum_Herstellung ist richtig
