### ISSUE TITLE
Lagerung in Transportmedium - Allokationsliste und KPT nicht mehr angezeigt

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#376]
Aus irgendeinem Grund wird seit heute nicht mehr das Datum "Lagerung in Transportmedium angezeigt:

![image](https://user-images.githubusercontent.com/22314271/41524360-7cdc0df0-72dd-11e8-87a4-3f8f2ea99576.png)

![image](https://user-images.githubusercontent.com/22314271/41524378-8fc740f6-72dd-11e8-9f0c-4daaee2a8b78.png)

Klickt man in das Datumfeld, so ist das eingegeben datum sichtbar

![image](https://user-images.githubusercontent.com/22314271/41524403-a76405aa-72dd-11e8-97b0-5717d75835f0.png)

**Comment by chrbusch** [comment]
Bei diesen Transplantaten hat der ProzessSchritt 126="Lag. Transp.-Med." einen Soll-Wert; dieser wird im Dialog angezeigt. Aber das Feld "Datum Erledigt" ist leer.
Wo genau wird i.d.R. dieses Datum erfasst?

![bildschirmfoto 2018-06-18 um 10 45 19](https://user-images.githubusercontent.com/1241899/41526535-d476e6fa-72e4-11e8-8093-7b5ac46cb75b.JPG)

**Comment by Toelk-A** [comment]
Datum wird noch immer nicht angezeigt (dies funktionierte vorher unabhängig vom Solldatum)

![image](https://user-images.githubusercontent.com/22314271/41528861-9fcf4684-72eb-11e8-80a8-dc9b8de81aab.png)

**Comment by chrbusch** [comment]
Try now…

**Comment by Toelk-A** [comment]
In der Allokationsliste MUSS das Solldatum zur Lagerung in Transportmedium abgebildet werden, ansonsten hat die Allokationsliste für die Bankmitarbeiterinnen keine Funktion mehr, da man außerdem nicht nach nach Lagerung in Transportmedium sortieren kann.

![image](https://user-images.githubusercontent.com/22314271/41536113-f4da46ba-7304-11e8-9e18-f0575aa6b0d6.png)

**Comment by chrbusch** [comment]
Das Solldatum wird nun wieder angezeigt, und die Spalt eist auch sortierbar; all diese Probleme sind quasi Spätfolgen der für die Herstellprotokole erfolgten Umstellung auf Prozessschritte

![bildschirmfoto 2018-06-18 um 15 16 28](https://user-images.githubusercontent.com/1241899/41538131-beb61d74-730a-11e8-9e2a-0292ab75b6b2.JPG)
