### ISSUE TITLE
GBMV/ Transplantatdetails - Tabelle für Routinekalender- Bemerkungsfeld mit Werteliste einfügen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#379]
Das QM wünscht sich, dass in dem rot markierten Bereich ein "Bemerkungsfeld angelegt wird in dem eine Werteliste ausgewählt werden kann.

![image](https://user-images.githubusercontent.com/22314271/41760357-3dcf4d5c-75f3-11e8-9b0b-992bbc81b1cd.png)

1) 

Generell sollen also die Medienwechsel 1 und Medienwechsel 2 abgebildet werden (Solldatum), obwohl eventuell vorher schon der Versand (Lagerung in Transportmedium) stattfand. Wird der Mediumwechsel 1 und oder 2 nicht durchgeführt so gibt es hierfür kein IST Datum. Gleichzeitig soll dann im Bemerkungsfeld die Werteliste anklickbar sein um den Grund anzugeben (Nachverfolgbarkeit).

Das bedeutet für den Routinekalender: Solldatum Mediumwechsel 1 UND "Eingabe" im Bemerkungsfeld = Datum NICHT im Routinekalender abbilden

**2) Werteliste für Bemerkungsfeld erstellen**

"kein MW, da zeitnahe Lagerung in Transportmedium" ;
"kein MW, da vorzeitige Lagerung in Transportmedium"; 
"keine Sterilkontrolle Eingang und MW da Verwurf/QS"

**Comment by chrbusch** [comment]
Habe ich gebaut, schlage aber vor, die Auswahl viel kürzer zu formulieren, etwa
"kein MW: zeitnahe Lag. Transp.-Med." ;

Sonst passt das ja in keine Liste!

**Comment by chrbusch** [comment]
![bildschirmfoto 2018-06-22 um 08 42 37](https://user-images.githubusercontent.com/1241899/41761646-5ffbb820-75f8-11e8-9552-a14000232c0d.JPG)

**Comment by Toelk-A** [comment]
Ja, dann verkürzen Sie bitte den Text :+1:

**Comment by chrbusch** [comment]
Erl.
