### ISSUE TITLE
Untersuchungsauftrag OG Parameter

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#38]
Untersuchungsauftrag OG

1) bitte Parameter "HCV-AK" zu "HCV" ändern

![image](https://cloud.githubusercontent.com/assets/22314271/20054020/583af294-a4db-11e6-9c3e-4f9da987c321.png)

2)
Bitte Unterteilung in Serologie und Erregernachweis (PCR)

Serologie beinhaltet Parameter TPHA, HBsAg, anti-HBc, HCV, HIV-Ag/Ak1-2-Test
Erregernachweis beinhaltet Parameter HCV-NAT

![image](https://cloud.githubusercontent.com/assets/22314271/20054192/1d806eb2-a4dc-11e6-8070-cde200661369.png)

**Comment by chrbusch** [comment]
Erledigt

**Comment by Toelk-A** [comment]
bitte Punkt 2) noch bearbeiten
