### ISSUE TITLE
Button AuditLOG Transpl. GBM-V

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#380]
## Was soll geloggt werden?

1)  Endothelzelldichte Zahl abbilden + Datum und Kürzel
2)   Endothelzelldichte Ausgang (Feld muss noch programmiert werden) (mit Datum und Kürzel)
3)   optisch freie Zone (mit Datum und Kürzel)
4)   Morphologie (mit Datum und Kürzel)
5)   Spaltlampenbefund (mit Datum und Kürzel)
6)   Klassifikation 1 (mit Datum und Kürzel)
7)   Klassifikation Anwendung (mit Datum und Kürzel)
8)  Virologie beauftragen? (mit Datum und Kürzel)

**Comment by Toelk-A** [comment]
## "Endothelzelldichte Ausgang" ist doch einfach der letzte gemessene Wert des Parameters ## "Endothelzelldichte"?!

Ja

**Comment by Toelk-A** [comment]
Transplantatdetails 2492

![image](https://user-images.githubusercontent.com/22314271/41832456-7026a0c4-784c-11e8-96ff-3d9c819da6d3.png)

Button Audit Log

Keine Ergebnisse

![image](https://user-images.githubusercontent.com/22314271/41832467-791623e4-784c-11e8-89c8-e9a2f46b6791.png)


Bitte dringend Programmierung prüfen

**Comment by chrbusch** [comment]
Der AuditLog speichert ÄNDERUNGEN von Daten. nicht deren erstmalige Erfassung. Werden die Daten nicht nachträglich geändert, stehen sie ja in der Datenbank.
Ich habe alle gezeigten Felder geändert und wieder zurück gesetzt - alles steh tim AuditLog


![bildschirmfoto 2018-06-25 um 08 08 13](https://user-images.githubusercontent.com/1241899/41833022-f2a93460-784e-11e8-889f-c3eb9c99b296.JPG)

**Comment by Toelk-A** [comment]
okay das wusste ich nicht. Danke.

**Comment by Toelk-A** [comment]
Button "AuditLog" hat wieder nicht geloggt!!!!
-> Virologie beauftragen "Ja"

![image](https://user-images.githubusercontent.com/22314271/42259463-ce8db3bc-7f60-11e8-8e1e-f853bb3b4744.png)

-> AuditLog GBM-V

![image](https://user-images.githubusercontent.com/22314271/42259533-28939a34-7f61-11e8-8848-9887034be9d9.png)

**Comment by chrbusch** [comment]
Ich denke, dies Ticket kann jetzt zu ?!

**Comment by Toelk-A** [comment]
Transplantat ID 2690
Zellzahl wurde geändert
![image](https://user-images.githubusercontent.com/22314271/44705058-cbc3e300-aa9d-11e8-868c-931cf9aae392.png)

Diese Änderung wird nicht im Auditlog abgebildet.... früher funktionierte dies bereits,.... bitte Programmierung prüfen

![image](https://user-images.githubusercontent.com/22314271/44705094-ea29de80-aa9d-11e8-968a-6c0ddea109a7.png)

**Comment by Toelk-A** [comment]
Es fehlt nach wie vor der Log von der Änderung der Zellzahl:

HOC 0 auf 1800
WIS 1800 auf 2500

Bitte prüfen warum dies nicht abgebildet wird.
Danke

**Comment by chrbusch** [comment]
Hier liegt ein Mißverständnis vor: Es wurde hier kein Wert GEÄNDERT; sondern ein zusätzlicher neuer Wert eingetragen. Wir brauchen für so etwas keinen AuditLog, weil ja beide Werte vorhanden bleiben.
Der AuditLog schützt nur nachträglich veränderte Werte so, dass man den "Vor-Wert" nicht verliert

**Comment by chrbusch** [comment]
Ich habe gerade den Wert 2500 **geändert**, das erscheint im Log!
