### ISSUE TITLE
GBMV/ Fertigstellung Herstellungsprotokoll Teil 2

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#381]
Grün markiert sind die Änderungswünsche

[Änderungsvorschläge Herstellungsprotokoll Teil 2.pdf](https://github.com/chrbusch/GTM-V/files/2126965/Anderungsvorschlage.Herstellungsprotokoll.Teil.2.pdf)

**Comment by chrbusch** [comment]
Die Änderungswünsche betreffen fast ausschl. die Dateninhalte; diese wurden bislang einfach nicht erhoben. So kann das System z.B. nicht für den 13.5.2018 ein "Nein" bei Trübung hinschreiben, weil an diese Tag noch keine Dokumentation dieser Tatsache statt fand.
-
Die dig. Unterschriften werden aber noch zeitnah ergänzt.

**Comment by Toelk-A** [comment]
z.B. Die Seitennummern können aber bereits angepasst werden

**Comment by chrbusch** [comment]
Die richtigen SeitenNr r.o. sind noch da, die falschen unten gelöscht.
Die Fusszeile ist korrigiert.
Die 2 noch fehlenden dig. Unterschriften mache ich heute; dann müssen wir halbwegs vollständige Daten abwarten.
Ein "Nein" bei einer Trübung etwa dürfen wir m.E. nicht dokumentieren, wenn es für den Tag keine echten Daten gibt.

**Comment by Toelk-A** [comment]
## -> Ist ein Kreuz bei der mikrobiologischen Untersuchung so kann auch parallel das "ja" abgebildet ## werden


Hier ist die mikrobiologische Untersuchung = "Sterilkontrolle Eingang" und "Sterilkontrolle Ausgang"- Lagerung in Transportmedium, das bedeutet es muss dementsprechend das "Ja" abgebildet werden. Die Daten erhalten Sie aus dem Routinekalender

![image](https://user-images.githubusercontent.com/22314271/41832621-0b972e16-784d-11e8-9d51-b6eefc713b68.png)

**Comment by chrbusch** [comment]
Das alles zu prüfen macht keinen Sinn, bevor wir vollständige Daten haben.
Das System erkennt zu Recht, dass es keinen EIntrag für Setrilkontrollen im Mai gab, daher bleiben fast alle Spalten leer

**Comment by Toelk-A** [comment]
Es geht um die Sterilkontrollen NICHT die Sterilitätsprüfungen.

![image](https://user-images.githubusercontent.com/22314271/41833880-6ccb9c8a-7852-11e8-8e78-77634013fa97.png)

**Comment by chrbusch** [comment]
Bitte die Unterschriftfelder unten auf Seite 1 prüfen: User-Auswahl korrekt?

**Comment by Toelk-A** [comment]
Die notwendigen Änderungen pro Seite sind im zugehörigen Githubticket beschrieben

**Comment by chrbusch** [comment]
...dann kann dieses Ticket jetzt geschlossen werden, oder?

**Comment by Toelk-A** [comment]
Meines Erachtens sind wir noch nicht fertig. Sind alle Änderungen pro Seite eingearbeitet worden?

**Comment by chrbusch** [comment]
Ich schlage nicht vor, alle "Subtickets" zu schliessen, sondern nur dieses - hier wird ja nicht mehr gearbeitet.
Ich prüfe heute anhand der "Einzelseitentickets" noch einmal den Stand und melde mich dann.
Laut Zusage des Vermieters habe ich auch ab Montag früh wieder Internet.

**Comment by Toelk-A** [comment]
[Githubticket 381_ Herstellungsprotokoll OG Teil 2 _ Nacharbeiten QM_1.pdf](https://github.com/chrbusch/GTM-V/files/2338948/Githubticket.381_.Herstellungsprotokoll.OG.Teil.2._.Nacharbeiten.QM_1.pdf)

**Comment by chrbusch** [comment]
Alles umgesetzt, siehe Bild

![bildschirmfoto 2018-09-03 um 10 52 02](https://user-images.githubusercontent.com/1241899/44977120-71c49100-af67-11e8-8ff2-be2b129b0a8b.JPG)

**Comment by Toelk-A** [comment]
Nein:
Protokoll Transplantat ID 2730
[Githubtikcet 381_  HerstellprotTeil2_2018-0516-GMV-CD_180917-103842.pdf](https://github.com/chrbusch/GTM-V/files/2387809/Githubtikcet.381_.HerstellprotTeil2_2018-0516-GMV-CD_180917-103842.pdf)

1) Seite 2 Kontrolle Organkulturmedium in Kultur fehlt

**Comment by chrbusch** [comment]
Für 2730 gibt es keinen einzigen Datensatz zur Prozesschritt-ID 131 = "Sterilitätsprüfung KMII"
Ist das gewollt?

**Comment by chrbusch** [comment]
Stattdessen scheint die HH vom 14.-22.8. in KM1 gewesen zu sein, und es fanden an 7 dieser 9 Tage Sterilprüfungen statt.

**Comment by chrbusch** [comment]
![bildschirmfoto 2018-09-17 um 10 58 31](https://user-images.githubusercontent.com/1241899/45614096-a442b380-ba68-11e8-814b-b6afa02fad0e.JPG)

**Comment by Toelk-A** [comment]
Sie haben Recht, im Dokument fehlt KMII.
Lagerung in Transportmedium war am 22.08.2018 (=KMII) und am selben Tag wurde auch versandt...

Generell muss das Dokument immer mit den 4 Seiten abgebildet werden, auch wenn es keine Daten, aufgrund von mangelnder Dokumentation, gibt.

**Comment by chrbusch** [comment]
Das ist wieder etwas komplizierter für eine Datenbank - es gibt keine Datensätze, aber es soll etwas gedruckt werden.
Wie soll denn die Druckseite aussehen, wenn es keine einzige Sterilprf. in KM2 gab?

**Comment by Toelk-A** [comment]
Bitte Seite 2 und 4 bearbeiten

[Herstellungsprotokoll OG Teil 2_NAcharbeiten.pdf](https://github.com/chrbusch/GTM-V/files/2471864/Herstellungsprotokoll.OG.Teil.2_NAcharbeiten.pdf)

**Comment by chrbusch** [comment]
Das Systen legt nun fehlende Tage vor dem Drucken an, bitte testen

**Comment by Toelk-A** [comment]
Transplantat ID 2902
Herstellprotokoll Teil 2 zeigt nur Seite 2 und ist unvollständig...

![image](https://user-images.githubusercontent.com/22314271/49516901-04dcd200-f89b-11e8-8ff5-7c289e027470.png)

Die PDF enthält ebenfalls nur Seite 2

**Comment by chrbusch** [comment]
Habe Sie tel. nicht erreicht. Bei mir fehlt nur Seite 3, Steril KM2.
Und in der Tat gibt es solche SpdProzesSchritte (SPS) nicht für 2902.
Sollen dafür auch "leere Tage" angelegt werden, wenn es keine SPS gibt?

**Comment by Toelk-A** [comment]
Es fehlt noch immer Seite 3 Sterilkontrolle KMII
Transplantat ID 3772

[Githubticket 381_HerstellprotTeil2_2019-0146-GMV-CD_190319-080336.pdf](https://github.com/chrbusch/GTM-V/files/2982049/Githubticket.381_HerstellprotTeil2_2019-0146-GMV-CD_190319-080336.pdf)

**Comment by Toelk-A** [comment]
erledigt
