### ISSUE TITLE
Abbildung "Tage ab Sterilkontrolle" Transplantat-Auswahl + Allokation

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#382]
Transplantat-Auswahl + Allokation 
![image](https://user-images.githubusercontent.com/22314271/41838157-ea1d0888-785f-11e8-81e7-fd4dec143a93.png)

Bitte an markierter Stelle die Spalte "Tage ab Sterilkontrolle (Eingang) einfügen. Das Datum auf das zurückgegriffen werden muss befindet sich im Routinekalender:

Sterilkontrolle Eingang "Erl. am"

![image](https://user-images.githubusercontent.com/22314271/41838224-1e1352be-7860-11e8-8350-3b4c372b3818.png)

Fand, wie im Beispiel, am 19.06.18 die Sterilkontrolle statt, so sind es heute am 25.06.18   6d nach Sterilkontrolle.

**Comment by chrbusch** [comment]
"Sterilkontrolle Eingang" ist der Prozessschritt mit ID=124
Ansicht so OK?

![bildschirmfoto 2018-06-25 um 13 01 00](https://user-images.githubusercontent.com/1241899/41846700-d9a66e3c-7877-11e8-97ab-cb834b452434.JPG)

**Comment by Toelk-A** [comment]
super :+1:
