### ISSUE TITLE
Neuer Reiter "mikrobiologische Untersuchungen"

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#383]
Zum Thema "Aufräumen der Transplantatdetails" haben wir uns folgendes überlegt:

## 1) Anlegen neuer Reiter "Mikrobiologische Untersuchungen"
an Stelle der roten Markierung soll der o.g. Reiter eingefügt werden.

![image](https://user-images.githubusercontent.com/22314271/41848612-44079110-787e-11e8-9b52-fcdbe33f9589.png)

## 2) Abbilden der Befunde KMI und KMII im Reiter "Mikrobiologische Untersuchung"

KMI und KMII sollen im Reiter "Mikrobiologische Untersuchungen" abgebildet werden

-> Die Befunde sollen automatisch angelegt werden, Erläuterungen unter Punkt 3)

## 3) Automatisches Anlegen der Befunde KMI / KMII nachdem Button "Job erledigt" im Routinekalender geklickt

Transplantat ID 2388
**A) "Sterilkontrollen Ausgang/ Lagerung in Transportmedium"**

Nachdem der Routinekalender "Lagerung in Transportmedium" abgearbeitet ist wird der Button "Alle erledigt" geklickt. Dann sollen automatisch die folgenden Befunde angelegt werden:

KMI - Hefen, Bakterien, Anaerobe Erreger
-> das Mitarbeiterkürzel kann aus dem Routinekalender übernommen werden
-> das "Datum Eingang" kann aus dem Routinekalender übernommen werden (IST Datum)

![image](https://user-images.githubusercontent.com/22314271/41849112-167b7124-7880-11e8-9484-0fe8d1250ab6.png)

**B) "Sterilkontrollen Eingang"**
Transplantat ID 2388

Nachdem im Routinekalender "Sterilkontrollen Eingang" abgearbeitet ist wird der Button "Alle erledigt" geklickt. Dann sollen automatisch die folgenden Befunde angelegt werden:

KMI - Hefen, Bakterien, Anaerobe Erreger
-> das Mitarbeiterkürzel kann aus dem Routinekalender übernommen werden
-> das "Datum Eingang" kann aus dem Routinekalender "Sterilkontrollen Einagng" übernommen werden (IST Datum)

![image](https://user-images.githubusercontent.com/22314271/41893363-ccfdd5ae-791b-11e8-95d4-4661ee728aab.png)

## 4) Abbildung positiver Befunde in den Transplantatdetails
Wird ein Befund positiv so soll dieser in den Transplantatdetails abgebildet werden. Das heißt die Eingabefelder befinden sich grundsätzlich nur im Reiter "Mikrobiologische Probennahme". Es darf keine Eingabefelder in den Transplantatdetails geben. Der positive Befund darf nur ein Spiegelbild der Eintragungen im Reiter "Mikrobiologische Untersuchungen" sein.

**Comment by chrbusch** [comment]
Wo ist der Button "Job erledigt" ? Bitte Screenshot schicken

**Comment by chrbusch** [comment]
Kann es sein, dass bei A) nicht stehen soll
"KMI - Hefen, Bakterien, Anaerobe Erreger"
sondern
"KMII...." ?

**Comment by chrbusch** [comment]
neuer Reiter "Mikrobiologische **Untersuchungen**"
versus
Eingabefelder befinden sich grundsätzlich nur im Reiter "Mikrobiologische **Probennahme**"

Das ist aber derselbe Reiter? Wie soll er heissen?

**Comment by Toelk-A** [comment]
Der Button heißt "Alle erledigt"

![image](https://user-images.githubusercontent.com/22314271/41910409-d6bd0c08-7949-11e8-8562-5c6f42e0d93f.png)

**Comment by chrbusch** [comment]
1), 2) und 3) nun m.E. erledigt.
Bitte heute beobachten, ob die Befunde angelegt werden.

**Comment by chrbusch** [comment]
4) ist nun auch erledigt; ich lasse auf Reiter 1 Befunde weg, deren Ergebnis noch leer ist oder "neg" enthält, ist das so OK? Die Bilder zeigen vom selben Transplantat 2240 den ersten Reiter sowie den neuen.

![bildschirmfoto 2018-06-27 um 08 19 29](https://user-images.githubusercontent.com/1241899/41956121-dba12986-79e2-11e8-87ba-2f7af118a634.JPG)

![bildschirmfoto 2018-06-27 um 08 19 37](https://user-images.githubusercontent.com/1241899/41956146-ed48d38c-79e2-11e8-83d8-ee7fb3f5c9a9.JPG)

**Comment by Toelk-A** [comment]
## 5) Kornea und Endothel sollen nicht in mikrobiologischen Untersuchungen abgebildet werden
wie unter Punkt 29 beschrieben sollen nur KMI und ggf. KMII Befunde in dem neuen Reiter "Mikrobiologische Untersuchungen abgebildet werden.

![image](https://user-images.githubusercontent.com/22314271/41956821-43fe76bc-79e5-11e8-9623-df1dbde99ea5.png)


## 6) Kein Rückspringen von Reiter "mikrobiolog. Untersuchung" auf Transplantatdetails wenn Buttons ## "neg.", "pos" oder "I" geklickt

Klickt man auf den Button "neg" so springt Ornella automatisch in die Transplantatdetails zurück. Dies bitte unterbinden.

![image](https://user-images.githubusercontent.com/22314271/41956882-7fddaef0-79e5-11e8-8798-4c99261ec42f.png)

**Comment by chrbusch** [comment]
Beides erl.

**Comment by Toelk-A** [comment]
## 7) Bemerkungsfeld Befund Endothel ist blockiert
Bitte wieder den Normalzustand herstellen (Eingabefeld), sodass Bemerkungen dokumentiert werden können.

![image](https://user-images.githubusercontent.com/22314271/41961208-238b2490-79f2-11e8-96bf-42cabb6c2e81.png)

**Comment by chrbusch** [comment]
Ad 3): Die Befunden wurden automatisch angelegt, aber durch einen Tippfehler im Script nicht mit der Transplantat-ID versehen; dadurch erschienen sie nicht in der Befundliste.
Wird vermutlich morgen klappen!

**Comment by Toelk-A** [comment]
Es wurde getestet, da es noch 2 Nachzügler gab:

-> Die Befunde und der Mitarbeiter wurden angelegt :+1: 

![image](https://user-images.githubusercontent.com/22314271/41971790-ee074da8-7a0f-11e8-8def-61d222bcc85d.png)

Folgendes soll noch programmiert werden:
A) Bitte bei ALLEN Befunden das "Datum Eingang" eintragen
B) Bitte standardmäßig das "V" als vorläufigen Befund angeklickt haben

**Comment by chrbusch** [comment]
Beides wird nun eingetragen.

**Comment by Toelk-A** [comment]
erledigt
