### ISSUE TITLE
GBMV/ Vorarbeiten Dokument 3.4.3.4.1 F Eingangskontrolle OG

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#384]
Final soll das Dokument wie folgt aussehen:

[3.4.3.4.1 F Eingangskontrolle OG-05-11.08.17K.pdf](https://github.com/chrbusch/GTM-V/files/2144004/3.4.3.4.1.F.Eingangskontrolle.OG-05-11.08.17K.pdf)

Das Dokument soll nicht direkt über den Prozesschritt ausgefüllt werden, sondern über zu programmierende Abfragen durch Ornella nach Anlegen der/die Transplantate. Das Dokument darf nur durch die VP 20c veränderbar und unterschreibbar sein.

![image](https://user-images.githubusercontent.com/22314271/42016597-67a1c98a-7aac-11e8-9523-047755b4fb23.png)

## 1) Programmierung Button "Eingangskontrolle" in Transplantatdetails"
Bitte den Button "Eingangskontrolle" in der Buttonleiste bei den Transplantatdetails programmieren (rot markiert).

![image](https://user-images.githubusercontent.com/22314271/42016669-b0eb9206-7aac-11e8-9cc1-1f94934f29fd.png)

## 2) Eingangskontrolle für CD UND/ODER CS
Sind beide Präparate entnommen, so gilt die Eingangskontrolle gleichzeitig für bei Präparate. Ist nur der linke oder recht Bulbus entnommen, so muss dies entsprechend im Dokument abgebildet sein. Diese Info kann sich Ornella aus der Präparateliste bzw. "Alle Transplantate des Spenders" ziehen.

![image](https://user-images.githubusercontent.com/22314271/42016855-522be116-7aad-11e8-93d9-c386f8cae5fb.png)

## 3) Abfrage von Daten mit Button "Eingangskontrolle"
Die MA Herstellung wünschen sich ein Abfragen der notwendigen Angaben durch Ornella. Dies bedeutet es soll eine Abfolge von Dialogen mit Eingabefeldern/Auswahlfeldern programmiert werden. Die durch die MA Herstellung gemachten Angaben sollen dementsprechend in das das Dokument "Eingangskontrolle OG" übernommen werden, ohne das Dokument über die Prozessschritte öffnen zu müssen.

Folgende Abfragen sollen in Anlehnung an das "Eingangskontrolle OG" Protokoll programmiert werden:

**3.1) Wareneingang**
![image](https://user-images.githubusercontent.com/22314271/42017100-2fa239a0-7aae-11e8-8130-d1189b65f921.png)

- _Datum/Uhrzeit Wareneingang_ (Datumsfeld + Eingabefeld für Uhrzeit)
- _angenommen von_ (Hier soll die Auswahlliste der Mitarbeiter Herstellung abgebildet werden und entsprechend ein MA ausgewählt werden)
- _Transporteur_ (generelle kann hier der "Entnehmer" aus dem OG Entnahmebericht abgebildet werden (Das Feld sollte aber einmalig in der Abfrage durch den MA Herstellung veränderbar sein)

![image](https://user-images.githubusercontent.com/22314271/42017259-ada53550-7aae-11e8-86dd-c81d2b377bbd.png)

- _Transportdauer_ (Differenz zwischen Entnahmezeitpunkt und Wareneingang <=2h, dann Kreuz ansonsten >2h dann Kreuz)

- _Entnahmeeinrichtung_ -> Ankreuzfelder "GTM-V" oder "Andere" (da derzeit nur Präparate über die GTM-V in die GBM-V eingehen kann heir standardmäßig das Kreuz bei GTM-V gesetzt werden, es muss aber veränderbar bleiben// wird "Andere" angekreuzt so benötigen wir ein Eingabefeld um die Entnahmeeinrichtung zu hinterlegen) 

**3.2) Wareneingangskontrolle**

![image](https://user-images.githubusercontent.com/22314271/42017777-813815a8-7ab0-11e8-954b-70f6d3ceba85.png)

- _Unversehrtheit der Verpackung_ (Auswahlmöglichkeit "ja" oder "nein, Mängel:" -> DANN Eingabefeld
- _Eingangstemperatur Bulbus_ - Eingabefeld für rechts und Eingabefeld für links
- _Ischämiezeit_ <= 72 Stunden -> Abfrage "Ja" oder "nein", WENN "ja" dann automatische Berechnung der Ischämiezeit aus Entn ahmebericht OG (HKTS + 72h und Datum sowie Uhrzeit abbilden) , WENN "nein" DANN Eingabefeld der Ischämiezeit
![image](https://user-images.githubusercontent.com/22314271/42023623-9bfdc800-7ac0-11e8-9a7d-50af724957c3.png)
- _Entnahmebericht vollständig_ - Ankreuzfeld "ja" ODER "nein", bei "nein Eingabefeld
- _Übereinstimmung gelistete Gewebe im Entnahmebericht_ ... Ankreuzfeld "ja" oder "nein", WENN "nein" Dann Eingabefeld
- _Spendenproben vorhanden_  - Ankreuzfeld "keine" ODER "prämortal - Serum", "prämortal - EDTA", "postmortal - Serum", "postmortal - EDTA"  
- _Kennzeichnung konform und eindeutig_ - Ankreuzfeld Gewebe "ja" ODER "nein, Mängel"  // Ankreuzfeld Spendenproben Gewebe "ja" ODER "nein, Mängel"
- _Spenderalter >= 3 Jahre_ Ankreuzfeld "ja" ODER "nein"
- _Innere Verpackung ohne Schäden_ - Ankreuzfeld "ja" ODER "nein, welche", WENN "nein" DANN Eingabefeld 
- _Bulbi bzw. CSK makroskopisch ohne Mängel_ Ankreuzfeld "ja" ODER "Nein - Artefakt, welches" WENN "nein" Eingabefeld
- _Die Wareneingangskontrolle wurde konform durchgeführt und vollständig dokumentiert_ - Ankreuzfeld "ja" ODER "nein"
- _Eingangskontrolle durchgeführt_ - Datumsfeld, Auswahl Liste MA Herstellung + digitale Unterschrift

**Comment by chrbusch** [comment]
Eine Abfolge von Dialogen zu programmieren steht erstens im Widerspruch zu allen anderen Erfassungsmasken, ist zweitens extrem aufwändig zu programmieren und macht es drittens sehr schwer, Fehleingaben zu korrigieren.
Daher plädiere ich für eine normale Erfassungsmaske mit üblichen Feldern, die wir auf schnelle Erfassung optimieren.
Insgesamt ist die Eingangskontrolle ein recht komplexes Dokument, das wird etwa dauern.
Ich kann es aber voraussichtlich ab morgen Vormittag für Sie und mich zum Testen frei geben, wobei dann sicher noch nicht alle Felder vorhanden sind.

**Comment by Toelk-A** [comment]
Bitte heute mit Frau Schröder besprechen und programmieren

**Comment by chrbusch** [comment]
Was bedeuten diese Felder:
Spendenkennungssequenz:
andere ID-Nr.:
?

**Comment by chrbusch** [comment]
WICHTIG: Beim SpdGewebe mit ID=7396 habe ich zum Testen div. der neuen Felder befüllt, dies muss später wieder gelöscht werden!

**Comment by chrbusch** [comment]
Ich denke, die Erfassungsmaske ist soweit fertig.
Bitte anrufen und mit mir zusammen testen.
Bitte beachten: Die DRUCKmaske wird ganz anders aussehen, Ihrer Vorgabe entsprechend; zur Zeit geht es NUR um die EINGABEmaske

![bildschirmfoto 2018-08-23 um 15 13 20](https://user-images.githubusercontent.com/1241899/44527477-31535080-a6e7-11e8-9ab9-fff8516e35cc.JPG)

**Comment by Toelk-A** [comment]
Kann das Dokument jetzt getestet werden?

**Comment by chrbusch** [comment]
Die Vorarbeiten sind erl., bitte Ticket schliessen
