### ISSUE TITLE
GBMV/ Button "Versandpapiere drucken"

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#386]
## 1)Bitte den Button "Versandpapiere drucken" im Hauptmenü der Transplantatdetails erstellen.

![image](https://user-images.githubusercontent.com/22314271/42037182-0bc440c0-7ae8-11e8-8fb2-7b9a661646d5.png)

## 2) Welche Dokumente = Versandpapiere?
Transplantationsbegleitschein
Übergabeprotokoll
Freigabeprotokoll

Hieraus bitte 1 PDF (ähnlich der Spenderakte) erstellen und ablegen.

## 3) HH organkultiviert versus stromaler Patch
Entsprechend der Klassifikation handelt es sich um eine "Hornhaut organkultiviert" oder um einen "stromalen Patch". Dementsprechend müssen die Versandpapiere an die Klassifikation der Hornhaut angepasst sein.

![image](https://user-images.githubusercontent.com/22314271/42037627-2ccb8fca-7ae9-11e8-80c0-8e54ef798dc0.png)

## 4) Button Versandpapiere nur möglich nach "Freigabe" VP GBM-V
Sind die Versandpapiere noch nicht mit der digitalen Unterschrift versehen, so können die Dokumente nicht ausgedruckt werden.

**Comment by Toelk-A** [comment]
Wie ist hier der Stand?

**Comment by chrbusch** [comment]
nach fertigstellung der laut Fr. N. dringenderen Sachen habe ich dies wieder auf prio1 gesetzt und fange nun damit an

**Comment by chrbusch** [comment]
Auf dem Transplantationsbegleitschein gibt es m.E. keine dig. Unterschrift!

**Comment by chrbusch** [comment]
Script ist halb fertig. Außer den Unterschriften, was soll geprüft werden?
Ich denke, es muss eine positive Freigabe geben - und nicht zB eine unterschriebene Ablehnung der Freigabe?!

**Comment by Toelk-A** [comment]
## Auf dem Transplantationsbegleitschein gibt es m.E. keine dig. Unterschrift!
## Soll dies eingerichtet werden?
Nein

## Ich denke, es muss eine positive Freigabe geben - und nicht zB eine unterschriebene Ablehnung der ## Freigabe?!
Beim Versand von Forschungshornhäuten/Übungshornhäuten gibt es keine Freigabe.
-> Digitale US + Datum (auf den Dokumenten mit digitaler Unterschrift) müssen gesetzt sein, Freigabe/nicht Freigabe muss angegeben sein (Freigabeprotokol), Übergabeprotokoll muss das Haltbarkeitsdatum enthalten -> "Hornhaut muss bis zum    transplantiert sein.

**Comment by chrbusch** [comment]
Dieses Modul kann nun getestet werden. Bitte tun Sie dies mit dem unvollständigen Transplantat mit ID=1572, und mit einem recht neuen, gut dokumentierten.

**Comment by chrbusch** [comment]
Bitte auch darauf achten, ob je nach Klassifikation das richtige Freigabeprotokoll gedruckt wird

**Comment by Toelk-A** [comment]
funktioniert

**Comment by Toelk-A** [comment]
Nach dem Testen hatte damals alles funktioniert. Warum tauchen jetzt die folgenden Fehler auf?

Transplantat ID 2831

## 1) Aus irgendeinem Grund wird ein 20 Seiten PDF erstellt

[VersandPapiere_2018-0565-GMV-CS_180910133707.pdf](https://github.com/chrbusch/GTM-V/files/2366412/VersandPapiere_2018-0565-GMV-CS_180910133707.pdf)

## 2) Die Unterschriften zur Freigabe sind teilweise nicht abgebildet..

**Comment by chrbusch** [comment]
Dies Problem hat m.E. dieselbe Ursach emit den Dubletten in Tabelle "Herstellung" und sollte somit auch erledigt sein

**Comment by Toelk-A** [comment]
erledigt
