### ISSUE TITLE
GBMV/ Erweiterung nach Klick "ja" Pseudophakie

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#388]
1) Wenn "ja", dann "Z.n. Cat.-OP" in Bemerkungen zur Klassifikation abbilden

![image](https://user-images.githubusercontent.com/22314271/42162303-74851a30-7dfe-11e8-8814-d8c574843a75.png)

ACHTUNG: Es kann vorkommen, dass sowohl ein  Arcus seniles als auch ein Z.n. Cat-OP an einem Transplantat vorliegen, d.h. beide Besonderheiten müssen in dem Feld abgebildet werden. Dies muss bei der Programmierung beachtet werden.

2) Wenn "ja" DANN "Z.n. Cat.-OP" im Feld "Besonderheiten" auf Übergabeprotokoll abbilden.

![image](https://user-images.githubusercontent.com/22314271/42162368-b5f8f306-7dfe-11e8-8d2b-ec4ae9555f63.png)

ACHTUNG: Es kann vorkommen, dass sowohl ein  Arcus seniles als auch ein Z.n. Cat-OP an einem Transplantat vorliegen, d.h. beide Besonderheiten müssen in dem Feld auf dem Übergabeprotokoll abgebildet werden. Dies muss bei der Programmierung beachtet werden.

**Comment by chrbusch** [comment]
m.E: fertig, bitte testen

**Comment by Toelk-A** [comment]
erledigt
