### ISSUE TITLE
Sterilitätsprüfung KMII - Liste nicht vorhanden

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#389]
Frau Schröder prüfte soeben den Routinekalender.

KMI-Liste ist in Ordnung
KMII Liste fehlt obwohl ca. 9 Hornhäute hätten abgebildet sein müssen

**Comment by chrbusch** [comment]
Bitte dafür sorgen dass dies heute erst gestartet wird, wenn ich grünes Licht dafür gebe

**Comment by chrbusch** [comment]
Geht wieder!

**Comment by Toelk-A** [comment]
Liste geht heute in Benutzung. Nach Rückmeldung der MA-Bank bekommen Sie ein Feedback

**Comment by Toelk-A** [comment]
funktioniert
