### ISSUE TITLE
Anlegen eines neuen Spenders-Aufnahmenummer

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#39]
Ist es möglich, dass die Aufnahmenummer des Patienten (nach Aufforderung der Eingabe und Anlegen einer neuen Spendermeldung) im Feld "Aufnahmenummer" übernommen werden, sodass wir sie nicht 2x eingeben müssen?

Danke

**Comment by chrbusch** [comment]
Gute Idee und erledigt
