### ISSUE TITLE
GBMV/ Diabetes Mellitus in "Transplantat-Auswahl + Allokation" abbilden

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#390]
Wir haben seit heute eine neue transplantierende Einrichtung, die durch die GBM-V mit Hornhauttransplantaten versorgt wird. Das Zentrum akzeptiert nur Hornhäute von Spendern die keinen Diabetes Mellitus in der Krankenvorgeschichte haben.

Zur Allokation benötigen wir also eine Markierung (z.B. Einfärben der Hornhaut ODER ein Ja/nein Feld ähnlich der Voroperationen), das uns anzeigt ob ein Diabetes Mellitus vorliegt oder nicht.

In den Spenderdetails werden alle Diagnosen mittels ICD Code verschlüsselt. Hier befindet sich auch die Info ob ein Diabetes Mellitus vorliegt:

![image](https://user-images.githubusercontent.com/22314271/42369783-4d531952-810b-11e8-9829-d57ae379a125.png)

->>>>>> WENN Diagnosen mit den ICD codes *E10, *E11, *E12, *E13, *E14 sowie M14.2, H28.0, G59.0, G63.2, N08.3 auftreten, DANN bitte _Hornhaut gelb einfärben_ ODER _Ankreuzfeld ja/nein_ auf "ja"   in "Transplantat-Auswahl + Allokation"

![image](https://user-images.githubusercontent.com/22314271/42370738-d29ed13a-810d-11e8-9cb3-768caecfb46a.png)

**Comment by chrbusch** [comment]
Bitte jetzt testen!

![bildschirmfoto 2018-07-06 um 12 11 01](https://user-images.githubusercontent.com/1241899/42373593-ae9c1024-8115-11e8-85b6-5ecd9501e880.JPG)

**Comment by Toelk-A** [comment]
erledigt
