### ISSUE TITLE
GBMV/ Button "Avis Koordinator" erstellen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#391]
Nachdem ein Bulbus in die GBM-V eingeht und präpariert wurde, soll der Button "Avis Koordinator" geklickt werden können um Rückmeldung über die Qualität der Entnahme und des Transplantates an den Koordinator UND Entnehmer zu übermitteln. Der Button "Avis Koordinator" soll ähnlich dem Button "Bank- Avis" im OG-Entnahmebericht funktionieren.

## 1) Programmierung des Button "Avis Koordinator"

Bitte Button wie im Screenshot gezeigt anlegen:

![image](https://user-images.githubusercontent.com/22314271/42371468-df228c10-810f-11e8-8ead-dc55ce99ff27.png)

## 2) Adressat "Avis Koordinator"
_Info aus OG - Entnahmebericht:_

2.1 Verantwortlicher Arzt
2.2 Entnehmer/Koordinator

![image](https://user-images.githubusercontent.com/22314271/42371768-b99e2b56-8110-11e8-9007-1f1cb990b2af.png)

![image](https://user-images.githubusercontent.com/22314271/42364531-c1ab3c68-80fb-11e8-8a56-79afe4d44206.png)

_Info aus Spenderkennnummer_
2.3 Koordinator (Kürzel)

## 3) Abbildung folgender Infos im AVIS -> Infos aus Transplantatdetails

![image](https://user-images.githubusercontent.com/22314271/42364227-c0ec056a-80fa-11e8-929b-e45fc60809f9.png)

Avis gilt für links und rechts (CD und CS)
MA Herstellung
Herstelldatum + Uhrzeit
Letzte Endothelzelldichte
Optisch freie Zone
Klassifikation 1
Bem. zur Klassif.
Releveante Befunde -> Endothel -> Morphologie ->Abbilden des Ergebnis, Abbilden Bemerkung

**Comment by chrbusch** [comment]
Das Modul ist zum Testen frei gegeben; bitte Text der Email kritisch betrachten.

Zur Zeit werden die Daten EINES Transplantatates gesendet; sollen die Daten der anderen Seite, sofern existent, auf dieselbe Weise extrahiert und darunter geschrieben werden?

![bildschirmfoto 2018-09-04 um 15 38 40](https://user-images.githubusercontent.com/1241899/45034816-c8f65e80-b058-11e8-9158-40a9103d205d.JPG)

**Comment by chrbusch** [comment]
Nun werden die Daten beider Transplantate gesendet; bei mir kam diese Email (in einem Test) auch schon an.

**Comment by chrbusch** [comment]
Bis auf weiteres erhalten auch Sie nun diese Email.

**Comment by chrbusch** [comment]
Bei den Befunden ist noch ein Fehler, es kommt 2x das Datum

**Comment by Toelk-A** [comment]
Avis sieht gut aus. Bitte noch folgende Punkte bearbeiten:

## 1) Entnehmer in Mailverteiler
Koordinator ist nicht gleich Entnehmer, darum bitte, wie oben beschrieben, auch Entnehmer in den Mailverteiler mit aufnehmen.

## 2) Endothelmorphologie

Bitte gelbe Markierung umschreiben oder "Endothelmorphologie" nennen
![image](https://user-images.githubusercontent.com/22314271/45096108-1093ed80-b120-11e8-8d52-18dbc82bdf20.png)

**Comment by chrbusch** [comment]
Fixed

**Comment by Toelk-A** [comment]
Bitte noch die Spenderkennnummer abbilden, da sonst die Zuordnung für die GTM-V schwierig wird.

**Comment by chrbusch** [comment]
Erl.

**Comment by Toelk-A** [comment]
![image](https://user-images.githubusercontent.com/22314271/45358676-78d44a80-b5ca-11e8-9306-8188f48827c9.png)

Können Sie bitte hinter dem "queroval" - gelbe Markierung noch das folgende Feld abbilden:

![image](https://user-images.githubusercontent.com/22314271/45358737-b2a55100-b5ca-11e8-8ca9-0e0c1f1f65c1.png)

**Comment by chrbusch** [comment]
Erl.
