### ISSUE TITLE
GBMV/ Routinekalender - Liste Lagerung in Transportmedium - Zusatz Notfallhornhaut

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#393]
Liste Lagerung in Transportmedium "erledigt" - danach Notfallhornhaut

Situation: 

- Lagerung Transportmedium wurde abgearbeitet und auf „Alle erledigt“ gesetzt (MiBi wurde angelegt mit Eingangsdatum und Bearbeiter)
-	Mittags Eingang eines Notfalls, dokumentiert ist heutiges Datum für Lagerung Transportmedium, dieser Notfall steht an richtiger Stelle in Routinekalender
-	Öffnen der Liste für Lagerung Transportmedium, Notfall steht klar in Liste, die morgens abgearbeiteten sind ausgegraut aber noch erkennbar

**Problematik:** 

-> man kann die Positionen die nun erneut für nur diese eine Notfall HH gescannt werden müssen nicht einscannen da sie sonst in alle anderen des Tages nochmals mit übernommen werden

-	Das ist leider nicht praktikabel, so müssen wir wieder alles zu Fuss (per Hand) eintickern.

**Comment by chrbusch** [comment]
1) Habe von hier aus getestet und fand den Zugriff nicht ungewöhnlich langsam; besteht das Problem noch?
2) Können wir sicher optimieren, wenn ich wieder im Büro bin

**Comment by chrbusch** [comment]
Bitte testen Sie einmal, ob der neue Button
"Nur dieses Transplantat zeigen"
funktioniert: Er isoliert quasi ein bestimmtes Transplantat und führt dann alle Operationen NUR für dieses eine aus.

![bildschirmfoto 2018-08-07 um 08 53 44](https://user-images.githubusercontent.com/1241899/43759403-69f51f06-9a1f-11e8-9fc6-de6702b20494.JPG)
