### ISSUE TITLE
GBMV/ USER KRJ benötigt eine GBM-V Konto

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#394]
User KRJ benötigt ein GBM-V Konto, aber NUR zur Dokumentation ihrer geleisteten Arbeitsstunden - (geringfügig Beschäftigte). Sie darf keinen Einblick in Patientendaten , Herstellung Allokation erhalten.

**Comment by chrbusch** [comment]
Ich möchte das erst einrichten, wenn ich wieder im Büro bin; andernfalls besteht die Gefahr von Störungen beim Zugriff. Wir sollten das dann sofort live testen.

**Comment by chrbusch** [comment]
![bildschirmfoto 2018-08-06 um 10 38 27](https://user-images.githubusercontent.com/1241899/43706147-df80a486-9964-11e8-9134-de16b6735ac3.JPG)
