### ISSUE TITLE
Anlegen mehrerer Entnahmeberichte des selben Spendergewebes (OG)

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#395]
![image](https://user-images.githubusercontent.com/22314271/43709381-f3ea992e-996c-11e8-8083-5db766e76926.png)

Bei diesem Spender sollen 2 OG Entnahmebericht angelegt werden:

Präparat 1 Corneoskleralscheibe -> Gewebebank GBMV
Praparat 2 sclera oculi -> Gewebebank Hornhautbank München

Dies funktionierte früher bereits, und aus irgendeinem Grund jetzt nicht mehr. Können Sie bitte die 3 bereits angelegten Entnahmeberichte prüfen? Gerne auch per Teamviewer mit mir zusammen.

**Comment by chrbusch** [comment]
Bei dem erwähnten Spender wurden (verm. durch einen Programmierfehler) sinnlose Gewebe angelegt; dies müssen wir ebenfalls besprechen.

![bildschirmfoto 2018-08-08 um 17 32 14](https://user-images.githubusercontent.com/1241899/43847531-177e3754-9b31-11e8-8fe0-8d496f8f8413.JPG)

**Comment by chrbusch** [comment]
Do + Fr habe ich wie schon berichtet ganztägig Kunden hier; aber kurze Telefonate sind möglich.
Montag, 13.8. habe ich erst einmal komplett für Sie frei gehalten und habe auch sonst kommende Woche viel Zeit

**Comment by Toelk-A** [comment]
Dies möchte ich heute mit Ihnen besprechen.

**Comment by chrbusch** [comment]
Ich habe an diesem neuen Layout nun intensiv weiter gearbeitet.
Wir müssen besprechen, wie es eingebunden werden soll

**Comment by Toelk-A** [comment]
Im Ticket #254 ist bereits alles programmiert worden....

**Comment by chrbusch** [comment]
Techn. Bem.: Der alte, anscheinend schon funktionale Dialoge mit "Gehen alle..." ist in diesem Script:
SpdPraep01.Btn.Präparat wählen für (SP=pk_SpdGewebe)/
(s. Ticket #254)

**Comment by chrbusch** [comment]
Wg. Übersichtlichkeit schliesse ich dieses Ticket, es geht ja weiter mit #395
