### ISSUE TITLE
Performanceprobleme

### ISSUE THREAD

**Issue by chrbusch** [chrbusch/GTM-V#396]
Ladezeit Routinekalender unglaublich langsam  Seit ca 1 Woche haben wir Probleme beim Arbeiten in Ornella, Dokumente hochladen sowie dem Routinekalender. Die Ladezeit dauert für einige Prozesse sehr lange. Ist der Server wieder voll? Oder liegt dies an unserer Internetverbindung?

**Comment by chrbusch** [comment]
Ich habe Hr. Peter gebeten, die fast volle Platte auf dem Server zu prüfen und die Leitungsgeschwindigkeit zu messen.
Aber diese Email kam als unzustellbar zurück.
Bitte informieren Sie Herrn Peter.

**Comment by Toelk-A** [comment]
Stephan Peter hat den Server überprüft. Nach Rückmeldung aus der GBM-V läuft der Routinekalender noch immer sehr langsam.

**Comment by chrbusch** [comment]
Und die Leitungsgeschwindigkeit bzw. Übertragungsraten?
Es sind ja mind. drei Prozesse gleichzeitig langsam geworden, während ich im Urlaub war und nichts angefasst habe. Und hier bei mir ist es m.E. nicht langsamer als vorher!

**Comment by chrbusch** [comment]
Für den Routinekalender konnte ich weitere Teile vom Server rechnen lassen; das ändert aber nichts daran, dass es vermutlich ein technisches Problem als Ursache der Performancestörungen gibt
