### ISSUE TITLE
GBMV/ Kompaktansicht Transplantate - Pseudophakie einfügen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#397]
Bitte in der Kompaktansicht der Transplantate auch abbilden, wenn eine Pseudophakie in den Transplantatdetails angegeben wurde.

![image](https://user-images.githubusercontent.com/22314271/43940980-7eee3ec4-9c72-11e8-9e98-53e4149aff75.png)

Im Moment wird nur das "Eingabefeld Bemerkungen" abgebildet. Das ist für die Kompaktansicht zu wenig.

![image](https://user-images.githubusercontent.com/22314271/43940939-53231012-9c72-11e8-957b-239b71306536.png)

**Comment by chrbusch** [comment]
Erl.

**Comment by Toelk-A** [comment]
Werden beide Bemerkungsfelder abgebildet? Also, das programmierte Feld (Arcus seniles / Pseudophakie) sowie das Eingabefeld zu Bemerkungen? (Bem. zur Klassif. )

**Comment by chrbusch** [comment]
Ja, aber bitte testen
