### ISSUE TITLE
GBMV/ Transplantatliste Transplantatstatus [39] Sperre

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#398]
Sucht man in der Transplantatliste nach Transplantaten mit dem Status Sperre:

![image](https://user-images.githubusercontent.com/22314271/44016249-93fb5478-9ed4-11e8-841f-3ed8a6d7c82d.png)

so öffnet sich das folgende Fenster:

![image](https://user-images.githubusercontent.com/22314271/44016270-adc1894a-9ed4-11e8-89e6-cd28a2df156f.png)

Dieses ist hier nicht notwendig, da in der Transplantatliste kein Statuswechsel durchgeführt wird, sondern nach dem Status gesucht wird.

Wird jedoch in einem Transplantat selbst der Status auf [39] Sperre gesetzt, so muss natürlich das Eingabefenster erscheinen.

**Comment by chrbusch** [comment]
Der kleine Button darf gar nicht für die Suche verwendet werden, ich musste das sperren.
Es besteht Gefahr, dass hier Status verändert statt gesucht werden!

**Comment by Toelk-A** [comment]
Die Aufgabe ist nicht erledigt. Es war nicht die Rede von der Sperre eines Buttons.

Nach Klick auf das Feld "Status" in den Transplantatdetails und Auswahl des Status "Sperre"

![image](https://user-images.githubusercontent.com/22314271/44192391-8ca5a180-a12f-11e8-96a5-1288db07b4df.png)


soll das o.g. Fenster ausgeblendet werden. Bitte lösen Sie nur diese Aufgabe.

**Comment by chrbusch** [comment]
Der Button in der Listre un doben im Suchbereich MUSS im Suchmodus gesperrt werden; der Auswahldialog kann so nicht benutzt werden z.B. nach Klick auf "Freie Suche".
Aber wenn man nun im normalen Modus links oben einen Status wählt, wird kein Grund mehr erfragt.
