### ISSUE TITLE
GBMV/ Personalmodul Mitarbeiterdetails Reiter Miatarbeiter Monate AZK Stand

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#399]
Mitarbeiter ID 38 (Kristin Schmidt)

Der AZK Stand beträgt derzeit 333Überstunden, obwohl der Stundenreport aus dem Monat Juli ein AZK für August bei 35,93 Stunden zeigt. Nack Klick Button "Monatssummen aktualisieren" entstand diese verwirrende Zahl an AZK.

Bitte Problem beheben

![image](https://user-images.githubusercontent.com/22314271/44192059-46037780-a12e-11e8-99bd-e5cd79ee87f0.png)

**Comment by chrbusch** [comment]
Ich weiss noch nicht, ob dies die Ursache ist, aber hier gibt es fragwürdige Eingabe in der Tagesarbeitszeit, wie etwa 2,068965517
Wurden diese manuell eingegeben oder vom System errechnet?
Auch fällt mir auf, dass in diesem Feld unterschiedliche Schriftarten stehen, was für ein immer gefährliches copy&paste spricht: Dabei gelangen oft unsichtbare Steuerzeichen mit in ein Feld!

![bildschirmfoto 2018-08-16 um 08 40 57](https://user-images.githubusercontent.com/1241899/44192554-28cfa880-a130-11e8-838e-5e6b12b2fa15.JPG)

**Comment by chrbusch** [comment]
Dort stehen wirklich merkwürdige Daten!
Die Dame startete im Aug. 2017, aber für Aug+Sep 2017 steht eine Soll_Std_pro_Monat=0
Daher errechnet das System, m.E. korrekterweise, schon für Ende Sep 2017 ein AZK=320 Std.
Können Sie alleine die Daten korrigieren, oder wollen wir das gemeinsam tun?


![bildschirmfoto 2018-08-16 um 08 47 46](https://user-images.githubusercontent.com/1241899/44192801-130eb300-a131-11e8-8f9f-981ed63c8384.JPG)

**Comment by Toelk-A** [comment]
Ich kann den August leider nichht einsehen... ist mal wieder in der Auswahl nicht möglich... wir haben jetzt Dienstbesprechung ich rufe Sie danach zurück. 

![image](https://user-images.githubusercontent.com/22314271/44193267-9250b680-a132-11e8-967b-07e455db74c3.png)

**Comment by chrbusch** [comment]
<Monat wählen> geht nun 2 Jahre zurück

**Comment by chrbusch** [comment]
Ich denke, dies ist jetzt OK, bitte prüfen

**Comment by Toelk-A** [comment]
![image](https://user-images.githubusercontent.com/22314271/44205346-562f4d00-a156-11e8-8569-425312ccb641.png)

Wurde super gelöst!!!! Vielen Dank für die Aufschlüsselung der Auszahlung und des Übertrages. 

Können Sie sich bitte noch einmal den Juli anschauen? Ich habe einen Stundenreport vorliegen in dem 45h ausgezahlt wurden und 35,93h in den August übertragen wurden.

**Comment by chrbusch** [comment]
Ich halte die für diesen ersten Monat von Frau Schmidt angezeigte Zahl 71,9 für ein Artefakt des nachträglichen Umbaus der Berechnungen und schlage vor, dies manuell zu korrigieren auf den Wert laut StdReport

**Comment by chrbusch** [comment]
manuell korigiert
