### ISSUE TITLE
User, Rollen, Rechte

### ISSUE THREAD

**Issue by chrbusch** [chrbusch/GTM-V#4]
Die mir bekannten Personen habe ich als User eingetragen.
Zur Zeit haben alle das Passwort   20Sep16
Demnächst sende ich die Datei "MuTi_Opener.fmp12"
Diese doppelklicken, dann sollte sich das System öffnen.
Es müssen diese Plugins installiert sein im Ordner FileMaker/Extension:
TroiDialog
TroiFile
BaseElements
xmChart

**Comment by Nitschke-FP** [comment]
Die Plugins sind scheinbar nicht installiert, ich habe sie in dem Ordner nicht gefunden. Wollen Sie sich einmal draufschlagen bzw. mir mitteilen - wie ich die Plugins bekomme?
