### ISSUE TITLE
GBMV/ Personalmodul Button "persönlicher Kalender"

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#400]
Nach unserem gestrigen Telefonat zu Frau Schottmann, wurde festgestellt, dass Frau Schottmann nicht den Button "persönlicher Kalender" in ihrem Personalmodul sieht.

![image](https://user-images.githubusercontent.com/22314271/44192130-8ebb3080-a12e-11e8-860e-9d28905599c0.png)

Dr. Nitschke ging dem Problem auf die Spur und fand heraus, dass der Button nur "sichtbar" ist, wenn die Rolle in der Personalplanung (USER DEtailliste) "Koordinator" lautet.

![image](https://user-images.githubusercontent.com/22314271/44192208-de016100-a12e-11e8-8a6d-621c185aa7c1.png)

1) "Koordinator" sind nur die "Koordinatoren" der GTMV.

2) Bitte schalten Sie für alle "Rolle in Personalplg." den Button "persönlicher Kalender" frei.

![image](https://user-images.githubusercontent.com/22314271/44192290-39cbea00-a12f-11e8-9820-e5796c3dfca6.png)

**Comment by chrbusch** [comment]
Der Button gehört zum Thema "Mitarbeiter", das bereits für ALLE Rollen freigeschaltet war. Dies ist also nicht der Kern des Problems.
Sehen alle anderen den Button? Ist er auch nach Neustart des Programmes nicht sichtbar bei Frau Schottmann?
