### ISSUE TITLE
GBMV/ Export Statistik "Export B" erweitern

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#401]
Folgende Felder sollen in den "Export B" mit eingefügt werden :+1: 

## 1) Transplantatdetails - Abschnitt Herstellung

->  "Von Bank akzeptiert"
-> Virologie beauftragen 

-> Beides ist im "Audio LOG" abgebildet... vielleicht ist es einfach dies dort zu exportieren

![image](https://user-images.githubusercontent.com/22314271/44522830-19c09b80-a6d8-11e8-87b8-2656e01eb398.png)

## 2) Transplantadetails Reiter "Dokumente + Status"

Bitte alle Statuswechsel mit Datum und Mitarbeiterkürzel exportieren:
![image](https://user-images.githubusercontent.com/22314271/44522909-5c827380-a6d8-11e8-851b-cc00e5d21694.png)

**Comment by chrbusch** [comment]
AuditLog f.d. Felder folgt umgehend

**Comment by chrbusch** [comment]
Kann dies Ticket geschlossen werden?

**Comment by Toelk-A** [comment]
Transplantatliste - Button "Export B"

Export B Export 3 und Export 4. Bitte sicherstellen, dass die ausgeladenen Daten im selben Format aus gegeben werden, da Verknüpfungen teilweise nicht funktionieren.

![image](https://user-images.githubusercontent.com/22314271/45612676-0c42cb00-ba64-11e8-81d9-723466e69ead.png)

![image](https://user-images.githubusercontent.com/22314271/45612702-22508b80-ba64-11e8-9918-a98f43b51fee.png)


![image](https://user-images.githubusercontent.com/22314271/45612734-3bf1d300-ba64-11e8-89dd-632c91a6864a.png)

![image](https://user-images.githubusercontent.com/22314271/45612755-4ad88580-ba64-11e8-816c-f2591872b1cc.png)

**Comment by chrbusch** [comment]
Die Exporte 3 und 4 kommen aus ganz unterschiedlichen Datenbank-Tabellen!
Hier müssen die Verknüpfungen an das Exportformat angepasst werden.
