### ISSUE TITLE
GBMV/ Statuswechsel Transplantat nicht möglich

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#402]
Transplantat ID 2730

-> Das Transplantat soll den Status "zu berechnen" erhalten. ( gelbe Markierung. Dies ist nicht möglich. 

Unten rechts (rot eingekreist - "Tabelle ohne Bezug". Hängt dies mit dem nicht durchführbaren Statuswechsel zusammen?

![image](https://user-images.githubusercontent.com/22314271/44567271-ff3b0080-a771-11e8-8e93-11d2cf6e8229.png)

**Comment by chrbusch** [comment]
Der Datensatz ist gesperrt, vermutlich hat jemand den Cursor in einem Feld gelassen und dann den Arbeitsplatz verlassen.
Hier kann ich nichts tun! Wer Ornella nicht mehr benutzt, sollte stets ins Hauptmenü wechseln.
Das (wieder entfernte) blaue Feld hat damit nichts zu tun
