### ISSUE TITLE
Bankexport importieren und autom. zuordnen

### ISSUE THREAD

**Issue by chrbusch** [chrbusch/GTM-V#405]
Die CSV-Datei, die man aus dem Bankkonto exportieren kann, kann bereits eingelesen werden.
Was noch geschehen soll, ist die weitgehend automatisierte Zuordnung der Eingänge zu den offenen Posten (Debitorrechnungen).
Unerledigte/zweifelhafte Eingänge müssen dann einem menschlichen User zur Entscheidung vorgelegt werden.

**Comment by chrbusch** [comment]
mpr hat übernommen. Import und Abgleich funktionieren bereits, Details werden zwischen mpr + NiF besprochen

**Comment by chrbusch** [comment]
Bitte beachten: Die in den Serverordner ".../NeueDateien/" kopierte Datei mit den Kontobewegungen muss, um erkannt zu werden, beginnen mit "Umsa..." und enden mit ".CSV"

**Comment by Toelk-A** [comment]
Nach Rücksprache mit unserer IT Abteilung werden die CSV-files manuell durch uns ausgeladen. Ich werde mich morgen um einen aktuellen Export bemühen und Sie telefonisch kontaktieren. VG Anita Tölk

**Comment by Toelk-A** [comment]
Soeben wurde eine Export der Kontobewegungen auf dem Server abgelegt.

**Comment by Toelk-A** [comment]
Wir haben gestern noch einmal einen Bankexport durchgeführt und auf dem Server abgelegt. Die Daten wurden automatisch in Ornella eingeladen und zugeordnet. Dies funktioniert SUPER!!! Vielen Dank Unsere Finanzbuchhaltung ist in den kommenden 2 Wochen im Urlaub, sodass ich dies weiter testen werde. Da bis jetzt alles funktioniert schließe ich erst einmal das Ticket.
