### ISSUE TITLE
GBMV/ 3.4.3.7.1 F Spaltlampenbefund-04-03.07.18K

### ISSUE THREAD

**Issue by chrbusch** [chrbusch/GTM-V#407]
Layout wird realisiert als Liste zweier DSe der Tabelle SpaltLampenBefund, die jeweils ein Spdtranspl zeigen

**Comment by chrbusch** [comment]
bitte die aktuelle Vorgabe hier einstellen

**Comment by Toelk-A** [comment]
[3.4.3.7.1 F Spaltlampenbefund-04-03.07.18K.pdf](https://github.com/chrbusch/GTM-V/files/2326678/3.4.3.7.1.F.Spaltlampenbefund-04-03.07.18K.pdf)

## In dem Dokument gib tes eine Skizze des Auges; was soll hier hinein, reichen Kennbuchstaben wie bei der körperl. Untersuchung?

Es muss hier die Möglichkeit des "Einzeichnens" bestehen, das heißt wir können keine Buchstaben wie in der körperlichen Untersuchung verwenden.

**Comment by chrbusch** [comment]
Das Drucklayout ist weitgehend fertig, und l.u. beim Spendertransplantat-.Details ist ein Button.
Nun funktioniert auch die Ansteuerung ds neuen Datensatzes, sowie die grafische Erfassung der Narben.
BITTE TESTEN!
Einige fehlende Felder (und wohl auch falsche Feldbezeichnungen) korrigieren wir umgehend

**Comment by chrbusch** [comment]
m.E. sind nun alle Felder korrekt auf dem Layout und die Grafik funktioniert.
Bitte über den Prozessschritt "Spaltlampenbefund" ansteuern und testen.

![bildschirmfoto 2018-09-04 um 08 51 14](https://user-images.githubusercontent.com/1241899/45014685-b7dd2b80-b01f-11e8-9de1-11f19ca83fb7.JPG)

**Comment by chrbusch** [comment]
Modul ist von Schröder & Schröder abgenommen worden und nun im Alltagsbetrieb

**Comment by Toelk-A** [comment]
## 1) Programmierung Liste Spaltlampenbefunde mit Frage nach "Zeitbereich"

Ornella Hauptmenü, Button Herstellung -> Button Spaltlampenbefunde erstellen

![image](https://user-images.githubusercontent.com/22314271/45138380-78901580-b1ac-11e8-8bdf-7939e09ffa63.png)

Nach Klick soll dann die Abfrage für den zeitbereich kommen:

![image](https://user-images.githubusercontent.com/22314271/45138200-e851d080-b1ab-11e8-94b4-bdedd9d3561b.png)

## 2) Programmierung Unterschriftenmodul Spaltlampenbefunde
Prinzipiell soll Ornella alle an einem Datum erstellten Spaltlampenbefunde als Liste darstellen. Diese Liste soll einen Button "Unterschreiben" haben, der ähnlich dem Button "Job erledigt" funktioniert. d.h. für alle Spaltlampenbefunde an diesem Datum setzt Frau Dr. Schröder 1x ihre digitale Unterschrift. Diese wird dann in allen Spaltlampenbefunden des selben Datums abgebildet.

**Comment by chrbusch** [comment]
Welche Felder müssen auf dieser Liste sein?
Wie stellen wir sicher, dass Auffälligkeiten auch bemerkt werden, wenn die Unterzeichnende nich die Details der Befunde sieht?

**Comment by chrbusch** [comment]
Das Modul ist hiermit zum Testen freigegeben; die Felder auf der neuen Liste sollten aber m.E. noch ergänzt werden, es ist ja noch viel Platz

![bildschirmfoto 2018-09-06 um 09 52 47](https://user-images.githubusercontent.com/1241899/45143158-b4ca7280-b1ba-11e8-8b74-46621e3c6fc1.JPG)

**Comment by Toelk-A** [comment]
## Welche Felder müssen auf dieser Liste sein?
## Wie stellen wir sicher, dass Auffälligkeiten auch bemerkt werden, wenn die Unterzeichnende nich die 
## Details der Befunde sieht?

Dies bitte mit Frau Schröder klären, ich habe nur die offenen Programmierungen in Github eingetragen...

**Comment by Toelk-A** [comment]
Die Liste wurde bereits getestet, die digitale Unterschrift allerdings noch nicht. Dies kann erst am Freitag und nach dem Hochladen der US geschehen.

Auffälligkeiten trägt die Befundende zusammen mit den Mitarbeitern der GBM-V in Ornella ein.

**Comment by chrbusch** [comment]
Modul ist im Einsatz, Ticket kann m.E. zu
