### ISSUE TITLE
Mitarbeiter Maschmeier kann "Wunschdienst" nicht rückgängig machen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#412]
![image](https://user-images.githubusercontent.com/22314271/44709169-3af30480-aaa9-11e8-825a-2b63655f2e37.png)

Personalplanung
persönlicher Kalender

Der Wunschdienst am 01.10.2018 soll rückgängig gemacht werden. Das "Kreuz" bei Wunsch kann nicht entfernt werden.
Woran liegt das?

**Comment by chrbusch** [comment]
Fixed. War Programmierfehler.
