### ISSUE TITLE
GBMV/ Routinekalender - einfügen Liste Nachkontrolle

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#414]
Nach manchen Präparationen kann die Zellzahl der Kornea nicht sofort ermittelt werden. Nach ca 4. tagen werden sich die Korneae unter dem Mikroskop erneut angesehen um dann die Zellzahl zu bestimmen.

## 1) "Zeile Nachkontrolle" in Tabelle Aufgaben anlegen
Transplantatdetails
![image](https://user-images.githubusercontent.com/22314271/45013229-a5acbe80-b01a-11e8-9135-6bbd8f4c1493.png)

## 2) "Nachkontrolle" im Routinekalender abbilden
Im Routinekalender soll dann die Liste "Nachkontrolle" abgebildet werden, natürlich nur wenn eine Nachkontrolle zum aktuellen Datum stattfinden soll.

## 3) Liste "Nachkontrolle" mit allen Funktionen wie andere Listen
Wir benötigen auch hier die Möglichkeit des Einscannens von Warenkörben und Positionen, den Button "Alle erledigt"... etc.

## 4) Dokumentation Zellzahl
die Zellzahl wird nach wie vor in den Transplantatdetails dokumentiert.

**Comment by chrbusch** [comment]
Eine SPALTE bei den Aufgaben (=SpdProzessschritten) bedeutet, dass man Nachkontrollen für jede Art von Augabe haben kann? 
Oder soll es optionale eine neue ZEILE geben mit einem manuell zu füllenden Solldatum?
Am besten hierzu einmal anrufen…

**Comment by chrbusch** [comment]
Ich schlage vor, einen neuen Prozessschritt namens "Nachkontrolle" zu erstellen, wobei allerdings der Name klarer sein sollte und spezifizieren, WAS hier nachkontrolliert wird, etea
"Nachkontrolle Zellzahl".
Dann einen Button "Nachkontrolle anlegen" mit Abfrage Datum; Vorgabewert Heute+4.
Dann liesse sich das leicht in den Routinekalender integrieren; machen wir hingegen eine neue SPALTE bei den Aufgabe, wäre es eher hoher Programmieraufwand.
Ist das so sinnvoll?

**Comment by chrbusch** [comment]
SpdProzessschritt ist definiert, wurde für Transplanate mit ID >=2777 nachtrgl. addiert und wird bei neuen Transplantate angelegt.

**Comment by chrbusch** [comment]
Ich denke, das wird nun funktionieren, sobald "Datum Soll" für diese Nachkontrollen eingetragen wird.

**Comment by Toelk-A** [comment]
funktioniert
