### ISSUE TITLE
Spenderdetails - Reiter Transplantate - zusätzlich Zellzahl abbilden

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#418]
Spenderdetails -> Abschnitt Arzt Abschluss -> Reiter Transplantate

![image](https://user-images.githubusercontent.com/22314271/45144438-6d45e580-b1be-11e8-8475-20fa2fb43230.png)

![image](https://user-images.githubusercontent.com/22314271/45144681-1b518f80-b1bf-11e8-9bfe-45e07467aa4e.png)

## 1) Änderung KennNr in bankinterne Nummer
Bitte die bankinterne Nummer abbilden

## 2) Bemerkung in Endothelzellzahl umbennen
Spalte Bemerkung in Endothelzellzahl umbennen

## 3) Endothelzellzahl abbilden
Endothelzellzahl aus der Herstellungsliste GTMV übernehmen

**Comment by chrbusch** [comment]
Erledigt. Da die KennNr-Bank viel kürzer ist und auch das Statusfeld unnötig lang war, hat die Bemerkung nach wie vor Platz

![bildschirmfoto 2018-09-06 um 15 58 36](https://user-images.githubusercontent.com/1241899/45162209-bbbea880-b1ed-11e8-8ef0-90cd84e8c07d.JPG)

**Comment by Toelk-A** [comment]
Sieht gut aus. Letzte kleine Verbessrung, bitte noch die Seiten (CD/CS) abbilden. Danke

![image](https://user-images.githubusercontent.com/22314271/45200210-05e86e00-b270-11e8-9fc5-c6f587829d9a.png)

**Comment by chrbusch** [comment]
Erl.
