### ISSUE TITLE
Position Artikel aus GBMV im Entnahmebericht GTM-V abgebildet/ 

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#419]
Spender ID
5785

Entnahmebericht OG
Position "Penicillase" gehört zur GBM-V wie kann diese im Entnahmebericht abgebildet werden??

![image](https://user-images.githubusercontent.com/22314271/45207678-e1e55680-b288-11e8-9c32-e1bc649e0fe9.png)

**Comment by chrbusch** [comment]
Ich vermute, dieser Artikel ist gescannt worden!

**Comment by Toelk-A** [comment]
Er wurde ind er GBM-V gescannt wird aber in der GTM-V im Entnahmebericht abgebildet

**Comment by chrbusch** [comment]
"Er wurde in der GBM-V gescannt .." - aber woher weiß das Programm dies?
Eine getrennte Artikelverwaltung nach Standort haben wir ja noch nicht!
Allerdings könnte man bei jeder Position und jedem Warenkorb den Mandanten des eingeloggten Users mitspeichern, das würde dann die Trennung vorbereiten. Soll ich dies tun? Der Aufwand ist eine Viertelstunde.

**Comment by Toelk-A** [comment]
Wir haben 2 Unternehmen:

## 1)
**GTM-V:** hat ihr Lager im GTM-V Gebäude am Hauptbahnhof in Rostock -> in diesem Lager befinden sich alle Artikel 7 Verbrauchmaterialien der GTM-V / Bereich Spende

## 2)
**GBM-V:** hat ihren Sitz und ihr Lager im Gebäude der Schillingallee in Rostock -> in diesem Lager befinden sich nur GBM-V Artikel/Verbrauchsmaterilien / Bereich Herstellung

## 3)
Ornella ist so programmiert, dass die Mitarbeiter der GTM-V (Spende) KEINEN Zugriff auf die Transplantatdetails / Dokumente Herstellung haben.

## 4)

Umgedreht gilt dasselbe für die GBM-V, die KEINEN Zugriff auf die Spenderdetails sowie Dokumente Spende (INKL. OG-Entnahmebericht) hat. 

### 5) Zusammenfassung
Da die Lager räumlich (5km Luftlinie) getrennt sind, kann also weder ein GBM-V Mitarbeiter die Penicillinase (Bereich Herstellung) in den Entnahmebericht OG (Bereich Spende - nur für GTM-V zugängig) eingescannt haben, noch kann ein Miatrbeiter der GTM-V "Aus Versehen" die Penicillinase in den OG- Entnahmebericht eingescannt haben, da der Artikel sich nicht im Lager am Hauptbahnhof befindet.



-> Bitte überprüfen Sie die Programmierung des Einscannens. es ist unwichtig welcher Mitarbeiter den Artikel eingescannt hat, da dies definitiv ein MA Herstellung war.

##Allerdings könnte man bei jeder Position und jedem Warenkorb den Mandanten des eingeloggten 
## Users mitspeichern, das würde dann die Trennung vorbereiten. Soll ich dies tun? Der Aufwand ist 
## eine Viertelstunde.
Nein,da dies völlig irrelevant ist.

**Comment by Toelk-A** [comment]
Wie ist hier der Stand?

**Comment by chrbusch** [comment]
Am 28.8.18 wurden 3 Zusatzposition von KRJ gescannt, darunter auch der oben gelb hervorgehobene Artikel. Ich sehe nicht, dass hier das Programm etwas falsch macht

**Comment by chrbusch** [comment]
![bildschirmfoto 2018-09-11 um 10 00 31](https://user-images.githubusercontent.com/1241899/45346545-bc6a8c80-b5a9-11e8-8aa0-0b2d09aa8313.JPG)

**Comment by chrbusch** [comment]
Penicillinase ist gelöscht
