### ISSUE TITLE
Entnahmebericht allgemein

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#42]
Letztes Unterschriftenfeld bitte einen Dropdown des ärztlichen Personals anlegen

funktioniert nicht bei Spender: 191016-0954-GNO-TOA

![image](https://cloud.githubusercontent.com/assets/22314271/20098767/b78a1e84-a5b5-11e6-8b37-0b9cc17b9598.png)

**Comment by chrbusch** [comment]
Ist das ein zusätzliches Feld oder identisch zum "Verantwortlicher Arzt" oder "Entnehmer"  weiter oben im Bereich "Besonderheiten"?

**Comment by Toelk-A** [comment]
Feld ist identisch zu "Verantwortlicher Arzt" weiter oben. Wir benötigen beide Unterschriftenfelder des "verantwortlichen Arztes"
