### ISSUE TITLE
GBMV/ Digitale Unterschriften in Versandpapieren werden gesetzt und verschwinden danach

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#420]
Das Phänomen tritt seit ungefähr 1 Woche auf. Die digitale Unterschrift wird nach Passworteingabe im Freigabeprotokoll und Übergabeprotokoll gesetzt. Nach erneutem Öffnen des Dokumentes erscheint keine Unterschrift mehr und das Freigabeprotokoll/Übergabeprotokoll ist komplett unausgefüllt. Als PDF ist aber bereits die unterzeichnete Version im Reiter "Dokumente + Status" abgelegt Bitte dringend beheben, dies kostet sehr viel Zeit!!! Und es funktionierte bereits alles einwandfrei ...

Transplantat ID

2805
2807
2809
2815
2818
2832
2774
2837

**Comment by Toelk-A** [comment]
Wie ist hier der Stand?

**Comment by chrbusch** [comment]
Ich habe nun aus allen Dubletten die Werte zusammen gesucht, in EINEM Datensatz pro Transplantat konzentriert und dann die Dubletten gelöscht.
Bitte jer´tzt erneut testen

**Comment by chrbusch** [comment]
Problem am 100918 verstanden und (kostenfrei) behoben: 
Es gab Dubletten in Tabelle "Herstellung" (durch einen Programmierfehler).
Bis zum 130918 kein neuer Fall aufgetreten, daher erst einmal Ticket zu
