### ISSUE TITLE
DIAGNOSE Bösartige Neubildung _ Warum Fenster "Diagnosen" nicht rot eingefärbt

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#421]
Spender ID 5905
ICD Code Z85.5 Bösartige Neubildung...

Normalerweise wird bei "bösartigen" Diagnose der Hintergrund des Abschnittes "Diagnosen" rot eingefärbt. Warum bei dieser Diagnose nicht? Ich habe bereits in den ICD Codes nachgeschaut, aber kein anklickbares Feld für die Roteinfärbung des Hintergrundes gefunden. Es sind MSG und MVG mit "1" also absolute Kontraindikation angeklickt, aus diesem Grund ist die Diagnose an sich rot eingefärbt.

![image](https://user-images.githubusercontent.com/22314271/45406679-7ecc3900-b667-11e8-8669-d86c20124159.png)

**Comment by chrbusch** [comment]
Die Vorgabe lautete damals, alle mit "C" beginnenden ICD-Codes zur Entscheidung der Färbung des Hintergrundes  heran zu ziehen. Dieser Spender hat keine C-Dgn
