### ISSUE TITLE
Blutproben 3. Probe "Li-Hep" hinzufügen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#422]
Spenderdetails Reiter Blutproben- Button "Neue Blutprobe"

![image](https://user-images.githubusercontent.com/22314271/45416928-43d6ff00-b681-11e8-9b20-a681b65e87a7.png)

## 1) Bitte "Lithium-Heparin prämortal" hinzufügen
![image](https://user-images.githubusercontent.com/22314271/45417043-8ef11200-b681-11e8-8d5c-4b0f438428b7.png)

## 2) Lithium-Heparin muss ebenfalls in der "Hämodilution" abgebildet werden
![image](https://user-images.githubusercontent.com/22314271/45417150-c95aaf00-b681-11e8-8bad-a195ba080131.png)

![image](https://user-images.githubusercontent.com/22314271/45417205-ec855e80-b681-11e8-8f29-3543e523ff3a.png)

## 3) Button "Etiketten drucken" Blutproben
-> Auch hier muss Lithium Heparin abgebildet werden, (wenn natürlich vorhanden)

**Comment by chrbusch** [comment]
Die Eingabedialoge wurden erweitert.
Bitte eine Spd-ID nennen, wenn die ersten Li.-Hep.-Proben erfasst wurden, dann baue ich die Etiketten usw.

**Comment by chrbusch** [comment]
![bildschirmfoto 2018-09-13 um 08 06 45](https://user-images.githubusercontent.com/1241899/45469947-024f5e00-b72c-11e8-8eae-d34800eb883e.JPG)

**Comment by Toelk-A** [comment]
1,2,3 erledigt
bitte noch folgendes programmieren:

4) Untersuchungsantrag GTM-V - Lithium Heparin einfügen
![image](https://user-images.githubusercontent.com/22314271/45491372-dc48ae80-b769-11e8-9d01-674e39fa8878.png)

**Comment by chrbusch** [comment]
So?

![bildschirmfoto 2018-09-13 um 15 41 37](https://user-images.githubusercontent.com/1241899/45492039-8d9c1400-b76b-11e8-9a6c-556dafdcc7ae.JPG)

**Comment by Toelk-A** [comment]
ja, die Ziffernauswahl funktioniert auch?

**Comment by chrbusch** [comment]
Inzwischen gibt es 8 Li.Hep-Blutproben; funktioniert alles wie gewünscht?
