### ISSUE TITLE
Transplantat berechnet - Rechnung storniert - Status Transplantat darf nicht "berechnet" bleiben

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#423]
Transplantat ID 2810
Rechnung wurde am 17.09.18 gestellt und heute am 18.09.18 storniert. Der Status des Transplantates ist noch immer "berechnet". Nach Stornierung der Rechnung muss das Transplantat automatisch in den vorherigen Status (meist "zu berechnen") zurückspringen.

![image](https://user-images.githubusercontent.com/22314271/45686307-5dc68500-bb4c-11e8-853a-e821f5d7ceea.png)

**Comment by chrbusch** [comment]
Das Storno-Script tut dies m.E. schon lange automatisch, siehe Bild.
Ist das einmalig aufgetreten? Ggfs. müssen wir es mit einem Testfall nachspielen. Zur Zeit sehe ich keinen Änderungsbedarf.

![bildschirmfoto 2018-09-19 um 06 55 01](https://user-images.githubusercontent.com/1241899/45731702-1b975500-bbd9-11e8-8c9c-2c2531995afb.JPG)

**Comment by chrbusch** [comment]
PS: Die StatusWechsel-tabelle zeigt sogar an, dass das alles perfekt funktioniert hat!

![bildschirmfoto 2018-09-19 um 06 57 12](https://user-images.githubusercontent.com/1241899/45731747-51d4d480-bbd9-11e8-98f9-f3a1dbe12e4a.JPG)

**Comment by Toelk-A** [comment]
Im besagten Beispiel hatte es nicht funktioniert. Dies können Sie auch in der Statusliste des Transplantates überprüfen am 17.09.18 wurde berechnet, am 18.09.18 storniert. es erfolgte kein Statuswechsel, sodass ich manuell um 14:23Uhr den Status auf "zu berechnen" änderte und danach das Transplantat berechnete.

![image](https://user-images.githubusercontent.com/22314271/45736014-0a0a7900-bbea-11e8-9d7c-8243a2aa68a4.png)

**Comment by Toelk-A** [comment]
dies funktioniert nach wie vor nicht. Bitte umgehend bearbeiten

**Comment by Toelk-A** [comment]
Wie ist hier der Stand?

**Comment by chrbusch** [comment]
Es wird nun im Script der Statuswechsel in der "Wechseltabelle" dokumentiert.
Am liebsten würde ich die nächste Rng selbst stornieren und das Script beobachten!

**Comment by Toelk-A** [comment]
okay, ich informiere Sie über den nächsten Storno

**Comment by Toelk-A** [comment]
scheint zu funktionieren.
