### ISSUE TITLE
GBM-V, eigener Mailserver

### ISSUE THREAD

**Issue by chrbusch** [chrbusch/GTM-V#425]
ATö am 210918:  "die GBM-V hat jetzt einen separaten Server. Aus diesem Grudn funktioniert der Avis...nicht mehr."

**Comment by chrbusch** [comment]
CBu bat S. Peter am 210918 per Email um die Zugangsdaten der GBMV

**Comment by Toelk-A** [comment]
Avis an Koordinator (GBM-V an GTM-V)  funktioniert wieder

**Comment by chrbusch** [comment]
OK, habe auch gerade die Zugangsdaten mit Hr. Peter ausgetauscht
