### ISSUE TITLE
Personalplanung - Verteilung Dienste bei Krankheit

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#427]
Ist ein Mitarbeiter >2 Wochen krank geschrieben, so muss er nicht die gleiche Anzahl an Diensten leisten wie die übrigen Mitarbeiter (Koordinatoren). Die Verteilung der Dienste muss also dementsprechend angepasst werden.

Ist dies bereits programmiert?

**Comment by chrbusch** [comment]
Nein, ich habe davon auch m.E. noch nie gehört.
Wie ist denn die genaue Regel - ich vermute mal so:
a) Eine Krankschreibung für weniger als 10 Arbeitstage ändert nichts an der RBD-Pflicht

b) Wird j-d für N>10 Tage krank geschrieben, so sinkt seine Pflicht um einen Faktor (365-N)/365
Das hiesse zB: Wer einen Monat krank ist, muss in dem betreffenden Jahr nur 11/12 der Dienste leisten.

**Comment by Toelk-A** [comment]
Am Mittwoch wird über den genauen Wert an Krankheitstagen diskutiert.

## Zu a)
Genau, wird der Wert unterschritten, so ändert sich nichts an der RBD-Pflicht

## zu b)

Wir sind 5 Koordinatoren, auf die die Dienste gleichmäßig pro Jahr aufgeteilt werden sollen. d.h. es gibt grob 52 Wochen pro Jahr -> Jeder Koordinator hat in etwa 10,5 Wochenenddienste und ca. 52 Werktagsdienste zu leisten. Der Urlaub kann meines Erachtens vernachlässigt werden, da alle Mitarbeiter ca. den gleichen Urlaubsanspruch haben.

Ist ein Mitarbeiter längere Zeit krank so muss die Differenz gebildet werden Ich weiß nicht, ob es richtig ist 365 Tage anzusetzen... hier müsste der Urlaub vielleicht doch erst subtrahiert werden...und dann die Differenz gebildet werden...

**Comment by chrbusch** [comment]
ok, ich warte auf eine präzise Vorgabe.

**Comment by Toelk-A** [comment]
Ich bekomme heute Die zahl der Krankheitsstage. Ist der Rest schon programmiert, sodass ich heute den Dienstplan für November erstellen kann?

**Comment by Toelk-A** [comment]
Nach Rücksprache mit der Geschäftsführung sollen alle Krankheitsstage in Berechnung mit einbezogen werden. Kann dies ab jetzt als Prio 1 programmiert werden? Die Krankheitstage sind im Teamkalender dokumentiert. 

Manchmal gibt es auch Krankschreibungen am Wochenende, diese müssen ebenfalls mit einbezogen werden.

**Comment by chrbusch** [comment]
Ich habe noch gar nichts programmiert, weil eine klare Vorgabe fehlte.
Ich rechne damit, dass dies eine recht komplexe Änderung am RBD-Modul ist…

**Comment by Toelk-A** [comment]
Können Sie mich bitte zurückrufen ich erreiche Sie nicht

**Comment by chrbusch** [comment]
November_RBD-Plan ist ohne Eingriff in die Programmierung m.E. korrekt.
Ich denke, Herr S. hatte einfach durch Krankheit mehrere manuell entfernte Dienste; das Programm hat dies nun aber ausgeglichen.

![bildschirmfoto 2018-09-27 um 14 58 18](https://user-images.githubusercontent.com/1241899/46147428-c9ec6b80-c265-11e8-9641-339845e2c4a7.JPG)

**Comment by Toelk-A** [comment]
Ist die Einbeziehung von Krankheitstagen jetzt schon programmiert?

**Comment by chrbusch** [comment]
Bitte Freitag gem. ansehen, was ich fabriziert habe.

![bildschirmfoto 2018-09-27 um 17 06 22](https://user-images.githubusercontent.com/1241899/46155492-b813c400-c277-11e8-9e04-65c7d8767360.JPG)

**Comment by Toelk-A** [comment]
Bin im Büro können gerne telefonieren und testen.

**Comment by Toelk-A** [comment]
Bitte noch zusätzlich die RBD Wochenende unter Berücksichtigung der Krankheitsstage in der Tabelle abbilden.

**Comment by chrbusch** [comment]
Erledigt

**Comment by Toelk-A** [comment]
Wir haben wieder einen Mitarbeiter der in diesem Jahr bereits 54d krankheitsbedingt ausgefallen ist. Können Sie bitte die Berechnung der gewichteten Dienste überprüfen? 
Danke

![image](https://user-images.githubusercontent.com/22314271/53018553-f4c49f80-3452-11e9-8def-48f1561420dd.png)

**Comment by chrbusch** [comment]
Wie tel. besprochen: Mir erscheint alles richtig, die gelbe 1,2 entsteht durch 
1  (geleistete RBD MoDo)* 365 / 311 (Verfügbarkeit 2019)
