### ISSUE TITLE
Erstellen Liste "Zu bezahlende B-Rechnungen"

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#428]
Nachdem die "A-Rechnungen" automatisch oder händisch zugeordnet wurden (= bezahlt sind), soll die zugehörige B-Rechnung in einer Liste "Zu bezahlende B-Rechnungen" abgebildet werden.

## 1) Erstellen der Liste "zu bezahlende B-Rechnungen" + Button

![image](https://user-images.githubusercontent.com/22314271/45946584-943f4c80-bff1-11e8-9c36-239ccc88e54f.png)

## 2) Kontakaufnahme mit APO-Bank
Bitte mit der APO-Bank besprechen ob "Überweisungsvorlagen" aus Ornella importiert werden können.

## 3) Überweisung aus Ornella programmieren wenn Punkt 2 möglich

**Comment by mprueter** [comment]
zu 1.
Den Button gibt es jetzt:

[BRNG.pdf](https://github.com/chrbusch/GTM-V/files/2410590/BRNG.pdf)

Er ruft alle GBMV-Rng auf, deren GTMV-Ursprungsrechnung bezahlt ist, die selber aber noch offen sind. Oder anders formuliert: es werden alle GBMV-Rng gezeigt, die bezahlt werden können.

**Comment by Toelk-A** [comment]
## Zu 1)
Funktioniert super!

## zu2) Kontakt Apo-Bank
Leider war ich auch nicht wirklich erfolgreich. Es gibt keine Unterlagen die angefordert werden können, laut Aussage der Mitarbeiter.

Von unsere IT Firma Stephan Peter erhielt ich die folgenden Infos:

a) "Der Aufbau einer ZV-Datei richtet sich nach dem Aufbau des Bankenstandards für XML. Ich suche Dir mal was raus."

b) "Im Grunde muss Dr. Busch eine XML-Datei aufbauen. Und dann müsst Ihr testen."

Hier ein paar Webseiten zur Programmierung:

https://www.hettwer-beratung.de/sepa-spezialwissen/sepa-technische-anforderungen/xml-sepa-zeilen-inhaltlicher-aufbau/

https://www.hettwer-beratung.de/sepa-spezialwissen/sepa-technische-anforderungen/pain-format-xml-nachrichtentyp/

**Comment by mprueter** [comment]
Ich habe auch noch einaml recherchiert und bin auf eine ganz brauchbare Seite gestoßen:

http://www.meta-evolutions.de/pages/artikel-20091127-sepa-ueberweisung-datei-betrachter.html

Hier gibt es eine Beispiel-Datei und eine Testmöglichkeit für eigene XML-Dateien.
Ich werde einmal eine kurzen Versuch starten...

**Comment by Toelk-A** [comment]
Frau Schmalfuß Groß ist wieder im Büro udn könnte eine DATEV Ausladung im xml Format durchführen. Diese lädt sie immer in der APObank hoch um die z.B. die Löhne zu überweisen. Benötigen Sie diese Vorlage?
