### ISSUE TITLE
Spender ID 5737 - Nachbeauftragung Parameter Virologie

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#429]
-> ist ein Parameter positiv/reaktiv so muss in manchen Fällen die Befundung eines weiteren Parameters beauftragt werden, wie im Falle des Spenders 5737

Anti-Hbc positiv -> bedeutet HBV-NAT (HBV-DNA) muss zusätzlich untersucht werden

![image](https://user-images.githubusercontent.com/22314271/46014632-43eaec00-c0d0-11e8-88a9-87a62ddf161e.png)

-> Untersuchung wurde telefonisch nachgemeldet, aus diesem Grund gibt es keinen Untersuchungantrag zu diesem Parameter. Über die LDT Datei müsste der Parameter aber auch übertragen worden sein. 

# 1) Sieht man in der LDT Datei auch Parameter, die nicht im Untersuchungsantrag abgebildet sind?

**Comment by Toelk-A** [comment]
Hatten Sie die LDT Datei gestern an mich und NIF versandt? Ich habe nichts erhalten.

**Comment by chrbusch** [comment]
Hier die Parameterzeilen aus der ersten LDT-Testdatei:

0138410HBCK
0138410HBSG
0148410HCVKU
0138410HCVK
0138410HCVM
0138410TPHA
0148410TPHAN
0148410HIVAU
0138410HIVA
0158410HBVDNA
0158410HIV1PC
0148410NACH1
0138410HAVM
0138410HBCM
0128410HTL
0148410NACHU
0138410NACH
0138410HBSQ
0128410CMV
0148410CMV-G

**Comment by Toelk-A** [comment]
Ich benötige die vollständige LDT Datei. 10 kann eine Überschrift aber auch eine Abkürzung eines Parameters sein.
Danke

**Comment by chrbusch** [comment]
Muss ich hier zur Zeit etwas tun?

**Comment by Toelk-A** [comment]
Herr Prüter sollte an diesem Ticket arbeiten. den aktuellen Stand kenne ich nicht...
