### ISSUE TITLE
Entnahmeberichte allgemein II

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#43]
Abschnitt: Eignung für Gewebeaufbereitung: Text Bemerkung darf nicht in Begründung für Nichtfreigabe kopiert werden

siehe 191016-0954-GNO-TOA (OG Entnahmebericht)

![image](https://cloud.githubusercontent.com/assets/22314271/20098849/0d92751a-a5b6-11e6-9a6d-5ea7f0b4fbb4.png)

**Comment by chrbusch** [comment]
Bitte zu diesem Stichwort anrufen; ich schlage vor, dass anders aufzubauen (EIN "Schalterfeld" geeignet ja/nein; dazu EIN Bemerkungsfeld

**Comment by Toelk-A** [comment]
Bitte mit Dr. Nitschke klären

**Comment by chrbusch** [comment]
OK, machen wir in Rostock.
