### ISSUE TITLE
GBMV/ Dokument Transplantationsbegleitschein - Rahmen anpassen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#430]
Transplantat ID 2513 - stromaler/temporärer Patch

Text wird nicht vollständig abgebildet, bitte Rahmen nach oben (roter Pfeil) vergrößern.

![image](https://user-images.githubusercontent.com/22314271/46150409-c7414480-c26c-11e8-9fdb-ffaa12e23999.png)

**Comment by chrbusch** [comment]
Erl.

**Comment by Toelk-A** [comment]
Auf Seite 2 ist der Rahemn nicht angepasst und die abbildung noch immer unvollständig

[TransplantationsBegleitschein_OG_20180412GMVCD_181026_083048.pdf](https://github.com/chrbusch/GTM-V/files/2517982/TransplantationsBegleitschein_OG_20180412GMVCD_181026_083048.pdf)

**Comment by chrbusch** [comment]
Ooops, Seite 2 hatte ich übersehen; korrigiert
