### ISSUE TITLE
GBMV/ Dokument Übergabeprotokoll - Rahmen anpassen 

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#431]
Transplantat ID 2513 - stromaler/temporärer Patch

Text wird nicht vollständig abgebildet, bitte Rahmen nach oben (roter Pfeil) vergrößern.

![image](https://user-images.githubusercontent.com/22314271/46150549-18e9cf00-c26d-11e8-89ba-5711e3259eb6.png)

**Comment by chrbusch** [comment]
Den Rahmen höher zu machen erfordert Anpassungen weiter unten im Layout, um nicht das schöne grafische Bild zu zerstören. Ich habe stattdessen alle Felder r.o. in der BREITE an den Text darüber angepasst; nun passt der Text und es sieht m.E. besser aus als vorher.

![bildschirmfoto 2018-10-25 um 09 00 27](https://user-images.githubusercontent.com/1241899/47481637-82410b80-d834-11e8-918c-3d8fdea8d511.JPG)
