### ISSUE TITLE
Perosnalplanung- Nur Sonderjobs der Mitarbeiter RBD "1" abbilden

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#432]
Bitte nur "Sonderjobs" der Mitarbeiter mit RBD im Rufbereitschaftsplan abbilden...

![image](https://user-images.githubusercontent.com/22314271/46206323-ecdd5500-c323-11e8-9230-1bfe0c7ff892.png)

TOA hat keine Rufbereitschaft mehr

![image](https://user-images.githubusercontent.com/22314271/46206273-bef81080-c323-11e8-886e-fc8c3f572f4e.png)

**Comment by chrbusch** [comment]
Erl.

**Comment by Toelk-A** [comment]
erledigt
