### ISSUE TITLE
GBMV/ Allokationswochenbericht

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#433]

**Comment by EmmaSchroederGBMV** [comment]
Wir brauchen Änderungen bei der Aufstellung der Allokationswochenberichte.
Die jetzige Gestaltung birgt zu viele Gefahren sodass wir das gern komplett umgestellt haben möchten.

1. ![allokationswochenbericht_alt](https://user-images.githubusercontent.com/43231378/46279639-f48e3b00-c569-11e8-99c6-d6d1d72d491e.png) es geht um die gelb markierten Stellen.
Die neue Aufteilung soll in der Reihenfolge links nach rechts so aussehen:

Laufende Nr. - KennNr. der Bank - Besteller - OP-Verfahren - Besonderheiten - Lagerung Transportmedium - Versand - Lieferwunsch - Lieferzeit - Lieferadresse (wirklich die genaue Adresse) - Klassifikation


Das muss dann auch alles auf der Druckversion auftauchen. Die zur Zeit noch so aussieht. 
![allokationswochenbericht_ausdruck](https://user-images.githubusercontent.com/43231378/46279917-bf361d00-c56a-11e8-93a7-85e8ba8a069f.png)

**Comment by chrbusch** [comment]
Es geht um Script/Button <118>.
Die Lieferadresse hat Werte wie

Universitätsklinikum des Saarlandes; Klinik für Augenheilkunde; LIONS Hornhautbank Saar-Lor-Lux Trier/Westpfalz; Gebäude 22; Kirrberger Straße 100; 66421 Homburg/Saar 

und passt auf keine Liste! Was tun?

**Comment by chrbusch** [comment]
Bitte die Bildschrimmaske nun einmal ansehen

**Comment by chrbusch** [comment]
Nun ist auch die Druckmaske angepasst, bitte testen

![bildschirmfoto 2018-10-23 um 10 00 37](https://user-images.githubusercontent.com/1241899/47345227-83463180-d6aa-11e8-8c0f-8c636bb7a7ba.JPG)

**Comment by EmmaSchroederGBMV** [comment]
Die Druckversion ist super, das die Adressen auf der Liste virtuell nicht ganz sichtbar sind ist aber kein Problem. Die werden komplett angezeigt sobald man mit dem Cursor auf die betreffende Adresse fährt.
