### ISSUE TITLE
Personalplanung - geringfügig Beschäftigte - Stundenreport wird falsch oder garnicht erstellt

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#434]
Hallo Dr. Busch,

die Lohnabrechnungen stehen wieder an und erneut treten Probleme bei den geringfügig Beschäftigten Mitarbeitern auf. Im Genauen handelt es sich um das Erstellen des „Stundenreportes“

## 1) Übertrag sind 36,6h aus Vormonat August – Keine Auszahlung im September möglich
![image](https://user-images.githubusercontent.com/22314271/46280120-58653380-c56b-11e8-809c-62ef38b9f329.png)

->	Bei der besagten Mitarbeiterin wurden im August „36,6“ Überstunden geleistet, die im September als „Start AZK“ abgebildet werden. Dies funktioniert. Im September hat die Mitarbeiterin keine weiteren Stunden geleistet, sodass zum 30.09.18 also 36,6h ausgezahlt werden müssen und sich der Übertrag für den Oktober auf „0“ beläuft.

->	Es ist keine Auszahlung möglich! Bitte umgehend prüfen und Fehler beheben.

## 2) Stundenreport enthält nicht AZK + geleistet Stunden

Stundenreport für September enthält nur die 31 geleistete "IST Arbeitszeit" aber nciht den Übertrag aus August. Demzufolge müssten ca 80h ausgezahlt werden. Der Abfragemechanismus "Wieviel Stunden sollen ausgezahlt werden, wie lautet der Übertrag etc." funktionieren nicht. Bitte prüfen

![image](https://user-images.githubusercontent.com/22314271/46283194-01179100-c574-11e8-938b-7f018e16c259.png)

**Comment by Toelk-A** [comment]
MAIL CBU

guten morgen,



Am 02.10.2018 um 12:49 schrieb Anita Tölk <anita.toelk@gtm-v.de>:

Bei der besagten Mitarbeiterin wurden im August „36,6“ Überstunden geleistet, die im September als „Start AZK“ abgebildet werden. Dies funktioniert. Im September hat die Mitarbeiterin keine weiteren Stunden geleistet, sodass zum 30.09.18 also 36,6h ausgezahlt werden müssen und sich der Übertrag für den Oktober auf „0“ beläuft.

Die angezeigten Spalten für freie Mitarbeiter haben wir ja letzten monat erst angepasst; welche bislang nicht aufgetretenen Fälle dies schon abdeckt, ist schwer absehbar.
Ich denke der Fall, dass jemand nicht arbeitet und dennoch Geld bekommt ist nie besprochen und schlichtweg nie programmiert worden.
Das Programm ermittelt Auszahlungen und Überträge für die, die im betrachteten Monat Arbeitsstunden erfasst haben.

ich kann auf dem kleinen Laptop, den ich mithabe, kleine Fehlerkorrekturen leisten, aber keine Entwicklungsarbeit.
Daher muss m.E. eine Lösung dieses Sache bis nach meinem Urlaub warten.
Auszahlen kann man die Mitarbeiter ja auch unabhängig von der Datenbank, wenn man die Arbeitsstunden kennt.

lg
cbu

**Comment by Toelk-A** [comment]
### Das Programm ermittelt Auszahlungen und Überträge für die, die im betrachteten Monat ### Arbeitsstunden erfasst haben.

auch dies funktioniert leider nur teilweise. Beispiel Mitarbeiterin Johanna Thiery. 

-> Dies können wir dann gern alles nach Ihrem Urlaub besprechen

**Comment by Toelk-A** [comment]
zu1)
AZK von Frau Schmidt beträgt Ende August 81,6h
![image](https://user-images.githubusercontent.com/22314271/47077467-4a691100-d201-11e8-9a53-83593f614f83.png)

-> Stundenreport enthält falschen AZK Wert
![image](https://user-images.githubusercontent.com/22314271/47077531-6ec4ed80-d201-11e8-9511-e86400fc503e.png)

Dies bitte überprüfen erst dann kann ich testen

**Comment by Toelk-A** [comment]
persönlicher Kalender Monat August Kristin Schmidt

**Comment by chrbusch** [comment]
Bitte Punkt 2) jetzt noch einmal testen, könnte mit erledigt sein!

**Comment by Toelk-A** [comment]
zu 2)
funktioniert noch immer nicht

![image](https://user-images.githubusercontent.com/22314271/47083587-5fe63700-d211-11e8-8a80-f4f9ea29e769.png)

**Comment by chrbusch** [comment]
Die grünen Felder waren von mir verwirrend benannt und platziert!
Der Übertrag in jeder Zeile ist der FÜR diesen Monat aus dem Vormonat und steht jetzt ganz links.
![bildschirmfoto 2018-10-17 um 13 52 23](https://user-images.githubusercontent.com/1241899/47084516-f7e52000-d213-11e8-890e-6203e0315df5.JPG)

**Comment by chrbusch** [comment]
Ist das so richtig?

![bildschirmfoto 2018-10-17 um 13 53 35](https://user-images.githubusercontent.com/1241899/47084548-11866780-d214-11e8-9dc2-75f4a04c812a.JPG)

**Comment by Toelk-A** [comment]
funktionert nach 2 maliger Testung erfolgreich
