### ISSUE TITLE
Modul Personalplanung - geringfügig Beschäftigte - Aufsplittung Stunden wenn bis nach 24Uhr gearbeitet funktionert nicht

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#436]
Geringfügig Beschäftigte - persönlicher Kalender- Dokumentation Arbeitszeit

Wir von 14:30Uhr bis 01:30Uhr des Folgetages gearbeitet so wird in Ornella "nur" 14:30-24:00Uhr dokumentiert. Die Abbildung am Folgetag 00:00-01:30Uhr fehlt. Dies ist bei den Koordinatoren bereits programmiert. Ich weiß nicht warum es hier nicht funktioniert.

**Comment by Toelk-A** [comment]
Oder hatten wir damals hierüber gesprochen und festgelegt, dass die geringfügig Beschäftigten ihre Stunden selbst aufsplitten sollen?

**Comment by chrbusch** [comment]
Ja, m.E. war das die Verabredung - die ganze komplexe Zuschlagsgeschichte trifft doch nur bei Festangestellten zu?!

**Comment by Toelk-A** [comment]
okay
