### ISSUE TITLE
TOA - Mandant GTMV Button "Supervisor" verschwunden

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#438]
Bitte Button wieder einblenden. Er sollte nie ausgeblendet werden.

Mandant TOA GBM-V Button "Supervisor" vorhanden 

![image](https://user-images.githubusercontent.com/22314271/46715078-bb875200-cc5e-11e8-8a80-0ff2f90fa5df.png)

**Comment by mprueter** [comment]
Sie sind mit Rolle "Arzt GTM-V" eingeloggt. Deswegen wird der Button hier nicht angezeigt. Wenn wir den Button für diese Rolle freischalten, ist er für alle User mit dieser Rolle sichtbar.

**Comment by Toelk-A** [comment]
ok, bitte nicht freischalten.
