### ISSUE TITLE
Personalplanung Status "nicht verfügbar" - bedeutet kein RBD für diesen Mitarbeiter eintragen -> funktioniert nicht mehr

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#439]
Wird der Status "nicht verfügbar" im persönliche Kalender gesetzt, so darf dieser Mitarbeiter nicht für den RBD eingesetzt werden. Dies ist für November trotzdem passiert:

![image](https://user-images.githubusercontent.com/22314271/46785730-fe1a5e80-cd32-11e8-9215-a3f581f0a26e.png)

Oder muss nun doch im Teamkalender der Status "nicht verfügbar [5]" ausgewählt werden?
![image](https://user-images.githubusercontent.com/22314271/46785924-8e58a380-cd33-11e8-928f-25f8ef12d528.png)

**Comment by chrbusch** [comment]
Sind Sie sicher, dass ZUERST der Status gewählt und DANACH der RBD-Plan erstellt wurde?
Das Script prüft explizit, ob für einen Status an einem Tag "RBD möglich?" JA ist, das habe ich gerade noch einmal überprüft. Und "Nicht verfügbar" hat definitiv "RBD möglich=nein"

**Comment by Toelk-A** [comment]
welches "nicht verfügbar" gilt denn?

Das nicht verfügbar aus dem Teamkalender oder das nicht verfügbar aus dem persönlichen Kalender?

**Comment by chrbusch** [comment]
Sie haben Recht, hier ist ein veraltetes Ankreuzfeld auf der Tabelle, dessen Wert ggfs. im Konflikt steht mit der Auswahl eines Jobs!
Unter welchen Umständen kreuzt hier jemand etwas an - brauchen wir das?
Bei einem Job wie "Urlaub bez." kann man ja generell entscheiden, ob ein MA mit diesem Job RBD haben kann.

**Comment by Toelk-A** [comment]
Okay. Bei Erstellung des RBD werden nun also das Feld "Für RBD nicht verfüg.?" im persönlichen Kalender sowie der Job "nicht verfügbar" im Teamkalender berücksichtigt?

**Comment by chrbusch** [comment]
siehe anderes Ticket 453; dieses bitte schliessen
