### ISSUE TITLE
!Wichtig! Nachtrag für alle Entnahmeberichte

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#44]
Nachtrag – Anpassung für alle Entnahmeberichte: Bitte folgendes Layout in die Entnahmeberichte vor der "Eignung für Gewebeaufbereitung" - 3. Seite einfügen:

![image](https://cloud.githubusercontent.com/assets/22314271/20098937/75e1d804-a5b6-11e6-91e0-68c70fe98619.png)

Dieses befindet sich bereits in der Einwilligungserklärung Teil IV Gesprächsergebnis. Die Kreuze können automatisch für alle Entnahmeberichte übernommen werden.

![image](https://cloud.githubusercontent.com/assets/22314271/20099081/fb9fba88-a5b6-11e6-8bd5-8de9bef2abf2.png)

Kopie aus den Daten des Angehörigengespräches!

**Comment by chrbusch** [comment]
Bitte zur Vermeidung von Missverständnissen unbedingt die Begriffe verwenden, die es im Programm gibt. Eine "Einwilligungserklärung" nicht; ich vermute sie meinen das "Einwilligungsgespräch".
Davon kann es aber auf ausdrückliche Anforderung von Dr. N. mehrere geben, mit eventuell widersprüchlichem Gesprächsergebnis. Wie soll damit verfahren werden?

**Comment by Toelk-A** [comment]
Das Dokument in dem die folgende Abbildung bereits vorhanden ist lautet bei mir "Einwilligungserklärung"

![image](https://cloud.githubusercontent.com/assets/22314271/20171595/bbace6ea-a731-11e6-9c55-bf48c51d058b.png)

von diesem Dokument, Teil IV Gesprächsergebnis können sie die Kreuze automatisch für alle Entnahmeberichte übernehmen.

![image](https://cloud.githubusercontent.com/assets/22314271/20171612/cd76d124-a731-11e6-8880-d04596d1677c.png)


Es ist richtig, dass es mehrere Einwilligungsgespräche geben kann, die dann ebenfalls in mehreren "Einwilligungserklärungen" dokumentiert werden. Final gibt es allerdings nur ein Dokument für die Entscheidungen: "Generelle Ablehnung, eingeschränkte Zustimmung oder generelle Zustimmung" und mit diesen Angaben werden auch die o.g. Kreuzchen gesetzt.

**Comment by Toelk-A** [comment]
Falls mehrere Einwilligungsgespräche stattfanden, muss ein Button der "finalen Zustimmung" eingefügt werden -> durch ärztliches Personal ausgeführt

**Comment by Toelk-A** [comment]
bitte noch bearbeiten, Schrift ist noch lila 

![image](https://cloud.githubusercontent.com/assets/22314271/21186270/3e8dd810-c214-11e6-9dd1-f2379dc0dc43.png)

**Comment by chrbusch** [comment]
Erledigt.

**Comment by Toelk-A** [comment]
funktioniert

**Comment by Toelk-A** [comment]
Bitte nur folgenden Teil in die Entnahmeberichte einfügen:

![image](https://cloud.githubusercontent.com/assets/22314271/21638538/07f0eb9a-d26c-11e6-9466-167ea316c4c5.png)


Entfernen von "IV Gesprächsergebnis und Ankreuzfeld "Der/ die Spender...."

**Comment by chrbusch** [comment]
Erledigt

**Comment by Toelk-A** [comment]
Bitte Gesprächsergebnis noch entfernen

![image](https://cloud.githubusercontent.com/assets/22314271/21638934/d63b0200-d26d-11e6-96b7-cf755bb5689d.png)

**Comment by chrbusch** [comment]
Erledigt; bitte testen und schliessen

**Comment by Toelk-A** [comment]
Es fehlt anscheinend die komplette Box
221216-1111-GNO-PET

Es ging nur darum den Text "IV Gesprächsergebnis" zu entfernen, nicht die komplette Box

![image](https://cloud.githubusercontent.com/assets/22314271/22016887/2775c9ea-dca8-11e6-985d-e3f63faf8151.png)

**Comment by chrbusch** [comment]
Ihr Bild zeigte die ganze Box und auch enthielt keinen Hinweis darauf, dass nur ein TEXT entfernt werden sollte :-(((
Nun muss ich das alles neu aufbauen, dauert aber nicht allzu lange
