### ISSUE TITLE
Personalmodul - persönlicher Kalender - Zuschläge Samstags 06:50-08:00Uhr nicht abgebildet

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#441]
Arbeitszeit 06:50-08:00Uhr -> keine 12,5% Zuschlag
![image](https://user-images.githubusercontent.com/22314271/47009496-f7c62100-d13c-11e8-842b-2cd473aa0a8e.png)

arbeitet man von 06:50 bis 09:00Uhr werden die 12,5% Zuschlag gewährt

**Comment by chrbusch** [comment]
Ursache waren unvollständig erfasste Stundenarten : Für Samstag / RBD / 6:00 bis 8:30 gab es keinen Eintrag.
Daten komplettiert, erfolgreicher Test

![bildschirmfoto 2018-10-19 um 08 38 23](https://user-images.githubusercontent.com/1241899/47201492-5c21f400-d37a-11e8-8aec-e24cb9dc2257.JPG)
