### ISSUE TITLE
Buchhaltung - Zahlungserinnerung

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#444]
Bitte die Felder/Text leserlich und vollständig abbilden.
[Beispie Rechnung Zahlungserinnerung GTMV_Rechnung_20181270.pdf](https://github.com/chrbusch/GTM-V/files/2510388/Beispie.Rechnung.Zahlungserinnerung.GTMV_Rechnung_20181270.pdf)

![image](https://user-images.githubusercontent.com/22314271/47429216-f11b5780-d795-11e8-8e13-e86f524a267d.png)

**Comment by chrbusch** [comment]
Die verwendeten Vortexte sind sehr lang! Ich habe nun auf den beiden Druckmasken für Rechnungen dafür Platz geschaffen, bitte Testausdruck erstellen
