### ISSUE TITLE
Personalmodul - MA ID 52

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#445]
Mitarbeiterin kann keine geleisteten Stunden in ihrem persönlichen Kalender hinterlegen.

![image](https://user-images.githubusercontent.com/22314271/47500510-4a04f180-d863-11e8-9346-7a5915275e50.png)

![image](https://user-images.githubusercontent.com/22314271/47500530-55581d00-d863-11e8-8c67-8da6ddccfa77.png)

**Comment by chrbusch** [comment]
Kann das Ticket zu?
