### ISSUE TITLE
Personalmodul - Urlaubsplanung 2019 - PDF Druck pro Monat

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#446]
Ende dieser Woche soll der Urlaubsplan 2019 genehmigt werden. Um die genehmigten Urlaub in Papierform in unseren Dokumenten zu hinterlegen benötigen wir eine Möglichkeit eine PDF pro TEAM Pro Monat ausdrucken zu können (Teamkalender als Übersicht?).

Bitte hierzu um Rückmeldung

**Comment by chrbusch** [comment]
Soll dieses Dokument nur die Urlaube enthalten?
Dann würde ich einfach eine Liste der mir diesem SonderJob markierten MitarbTage drucken können

**Comment by chrbusch** [comment]
Erstversion läuft, bitte testen

**Comment by Toelk-A** [comment]
Personalmodul   Button  Urlaubsplan drucken

![image](https://user-images.githubusercontent.com/22314271/49581860-99a30680-f953-11e8-8b16-a2a855fcf3e7.png)

Es soll der Zeitraum 01.01.2019-31.12.2019 gedruckt werden.
[Urlaubsplan__unvollständig.pdf](https://github.com/chrbusch/GTM-V/files/2652915/Urlaubsplan__unvollstandig.pdf)

Es wird ein unvollständiges PDF erzeugt z.B. nur ein Koordinator abgebildet...

**Comment by chrbusch** [comment]
Koordinatoren sind das Team 2; und im System gibt es NUR für Frau Kroll in diesem Team Urlaubstage in 2019, 2.-4.1.2019!

**Comment by chrbusch** [comment]
Wir haben gerade besprochen, dass der bisherige Urlaubsplan nur GENEHMIGTE Urlaube enthält, und davon gibt es wenige; alles funktioniert korekt

**Comment by chrbusch** [comment]
Der neue Dialog erlaubt, auch die Wünsche mit auszugeben; dieser sind dann in der Liste klar benannt.

![image](https://user-images.githubusercontent.com/1241899/49587765-24403180-f965-11e8-8641-4ebd41afaf4a.jpeg)

**Comment by Toelk-A** [comment]
funktioniert super
