### ISSUE TITLE
Personalmodul - Spezialrechte Personalverwaltung

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#450]
Wir benötigen folgende Rechte im Personalmodul in Ornella:

1 Person darf:
- Stunden-Report drucken (NICHTS verändern)
-Überstd.-Bericht drucken (NICHTS verändern)
![image](https://user-images.githubusercontent.com/22314271/48129321-74a27180-e289-11e8-8c41-2225abb3282f.png)

- Teamkalender -> AZK Wunsch in AZK sowie Urlaub Wunsch in Urlaub umwandeln NICHTS anderes verändern können
![image](https://user-images.githubusercontent.com/22314271/48129344-8552e780-e289-11e8-8518-0207cfeffd67.png)

- persönlicher Kalender - Kein Zugriff, nur auf den eigenen

**Comment by chrbusch** [comment]
Ich habe zunächst im Persomodul eine neue Rolle mit ID6 ="Rolle_neu_221118" definiert.

**Comment by chrbusch** [comment]
Es gbt zahlreiche MitarbTage mit AZK- oder UrlaubsWUNSCH in der Vergangenheit; das sollte m.E. nicht passieren.
Wünsche sollten abgelehnt werden oder bestätigt. Das müssen wir besprechen.

**Comment by chrbusch** [comment]
Die erwünschten Funktionen sind m.E. prinzipiell nun alle realisiert bis auf den Zugriff auf den eigenen TK.
Details müssen wir besprechen; u.a. halte ich es für unpraktisch, alle Tage eines Urlaubswunsches einzeln bestätigen zu müssen

![image](https://user-images.githubusercontent.com/1241899/48893805-78b1c000-ee41-11e8-82a8-64a32107d5c4.jpeg)

**Comment by Toelk-A** [comment]
Zum Testen habe ich meinen GTM-V Account mit der neuen Nutzerrolle versehen. 

Im Personalmodul kann ich nach dem Team "Vermittlung" suchen und in meinem Teamkalender GBMV habe ich in den Sonderjobs noch immer die komplette Auswahl zwischen Urlaubswunsch + Urlaub. Diese Liste muss für die neue Userrolle ebenfalls limitiert sein.. (siehe oben in der Beschreibung). 

![image](https://user-images.githubusercontent.com/22314271/49504998-1910d700-f87b-11e8-8229-dfc6e852b8f1.png)

![image](https://user-images.githubusercontent.com/22314271/49505025-275ef300-f87b-11e8-8c5f-ce336f5af4ce.png)


Ansonsten ist der Aufbau super!

Es müsste noch eine Programmierung hinzugefügt werden, die erst erlaubt den Stundenreport/Überstundenbericht zu öffnen wenn die Ärzte den Monat vollständig abgeschlossen haben, also für jeden Tag den Button "Tag abschließen" geklickt haben.

![image](https://user-images.githubusercontent.com/22314271/49505246-a0f6e100-f87b-11e8-9580-4221de3da2c0.png)

**Comment by chrbusch** [comment]
Dr- Nitschke wird bald nach Hamburg kommen, um an dem gesamten Komplex "Rechte im Programm" mit mir zu arbeiten.
m.E. sollte dieses Ticket bis dahin ruhen.
