### ISSUE TITLE
Funktion "Fehlklick löschen" für "Arzt" programmieren

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#451]
Spender ID 6492

A) Bei der Spendermeldung 221118-1358-KRJ wurde versehentlich der Button „Ablehnung“ beim ANG-Gespräch gedrückt. Dieser muss bitte wieder gelöscht werden. Insgesamt muss es für NIF + MAA möglich sein, hier einen „Fehlklick“ löschen zu können.

![image](https://user-images.githubusercontent.com/22314271/49431778-886cc500-f7ae-11e8-95cf-5cbc731fad94.png)

B) Das selbe gilt bei der Auswahl des beratenden Koordinators und Arztes... 
![image](https://user-images.githubusercontent.com/22314271/49431889-ba7e2700-f7ae-11e8-97c9-14f45249d350.png)

Die Taste "Entf" funktioniert beim öffnen von separaten Anzeigefenstern, wie oben gezeigt, leider nicht.

**Comment by chrbusch** [comment]
Ich verstehe das Problem nicht ganz.
Man kann doch einfach noch einmal auf das Feld klicken und eine andere Auswahl treffen?!

**Comment by chrbusch** [comment]
![image](https://user-images.githubusercontent.com/1241899/49716076-df611700-fc52-11e8-9e12-98c188b2641d.jpeg)
Der Auswahldialog hat nun optional einen neuen Button "Löschen", der den ausgew. Arzt oder Koord. wieder löscht.

**Comment by Toelk-A** [comment]
hierzu müssen wir telefonieren. Die gezeigte Abbildung darf auf keinen Fall so programmiert bleiben. Wir müssen IMMER zwischen GBMV und GTMV trennnen.

**Comment by Toelk-A** [comment]
Was ist hier der Stand?

**Comment by Toelk-A** [comment]
Wir haben wieder einmal das Problem, dass im Einwilligungsgespräch auf "Generelle Ablehnung" geklickt wurde, obwohl es noch keine Entscheidung seitens der Angehörigen gab. Man kann noch immer nicht die Auswahl im Nachhinein löschen. Kann dies bitte programmiert werden?

![image](https://user-images.githubusercontent.com/22314271/58455811-e1e0fb80-8122-11e9-8785-aabc3ab18427.png)

![image](https://user-images.githubusercontent.com/22314271/58455828-ee655400-8122-11e9-810e-894f143495e1.png)

**Comment by Toelk-A** [comment]
Aufgrund des Originalabbruches zum o.g. Spender fehlt der Prozesschritt "Freigabe Entnahme"

![image](https://user-images.githubusercontent.com/22314271/58461938-1956a480-8131-11e9-8a22-a4a0dc9f0e3a.png)

**Comment by chrbusch** [comment]
Ich habe mir nun das Script, welches bei der Auswahl des Gesprächsergebnisses läuft, genau angesehen.
Aus meiner Sicht spricht nichts dagegen, erneut auf das Feld zu klicken und das richtige Ergebnis auszuwählen.
Wollen wir das heute mal bei einem Testspender gemeinsam ausprobieren?

**Comment by chrbusch** [comment]
Es gibt nun eine Löschoption in dem Dialog.
Nachträgliches Ändern des Feldwertes scheint mir auch tadellos zu klappen, einschl. der Anlage gewisser Prozessschritte bei Zustimmung

![image](https://user-images.githubusercontent.com/1241899/60322640-3ffe3a00-9980-11e9-821b-c58f5d17a008.jpeg)
