### ISSUE TITLE
Rechnung AGE 2483 neue Abbildungen---- erledigt?

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#452]
Hallo Herr Busch,
da ich mit dem Github nicht permanent arbeite hier eine Mail, die Anita Tölk nach ihrem Urlaub in Github anlegen wird.
Anhängend eine Rechnung mit den neu hinzuzufügenden Daten. Die Rechnung wird generiert über das Adresslayout (siehe Bild). Eingefügt werden soll die Nummer aus  dem Layout „Spender Details“ (siehe Bild).
 
Grundlage für die Anzeige der Nummer in dem Bericht AGE 2483 ist ein Vertrag mit dem Krankenhaus. Bitte die Feldbezeichnung im Bericht so wie abgebildet übernehmen. Wir brauchen daher bei der Rechnungsadresse ein Ja/Nein Feld, ob ein Vertrag vorhanden ist und nur bei diesen Berichten darf die Nummer angezeigt werden.
 
HG
FPN

**Comment by chrbusch** [comment]
Das Ankreuzfeld gibt e ja bereits, siehe Bild.
Ist die Funktion mit den erweiterten Rngs-Texten getestet worden?

![image](https://user-images.githubusercontent.com/1241899/49652021-21ab0e00-fa31-11e8-9890-5fe6acb1df92.jpeg)

**Comment by Toelk-A** [comment]
Bitte mit NIF klären ich weiß nicht worum es geht. Ich sollte nur das Ticket anlegen

**Comment by Toelk-A** [comment]
Hallo Herr Busch, bitte nach Ihrem Urlaub das Gleiche noch einmal für die Rechnung AGE 2801 erstellen.
Danke
