### ISSUE TITLE
Personalplanung_ Status "nicht verfügbar" im Teamkalender " Werteliste Jobs 

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#453]
Job "nicht verfügbar" im Teamkalender führt im persönlichen Kalender werktags dazu, dass keine Mindestarbeitsstunden geleistet werden... wie kann das sein? Dies hat bis jetzt immer funktioniert!

![image](https://user-images.githubusercontent.com/22314271/49446556-bf55d180-f7d4-11e8-9bc6-e8134e2b697e.png)

![image](https://user-images.githubusercontent.com/22314271/49446642-f0ce9d00-f7d4-11e8-97c9-f860a37c71b6.png)

**Comment by chrbusch** [comment]
Ich verstehe das Problem nicht, bitte anrufen.

**Comment by chrbusch** [comment]
Da der JOB und das Ankreuzfeld dasselbe bedeuten sollen, und ein MA an einem Tag mit "RBD nicht verfügbar" normal arbeitet, habe ich den Job GELÖSCHT, nachdem ich bei allen, die diesen Job hatten, das Ankreuzfeld aktiviert habe.
(Int. Bem: Im Feld Bem_Admin steht bei diesen DSen "War pkJob=5")

**Comment by chrbusch** [comment]
Bitte Ihren Kollegen klar machen, dass die "Nicht-Verfügbarkeit für RBD" nun nur noch als Ankreuzoption in persönl. Kalender besteht; dies war auch viel häufiger benutzt worden.

**Comment by Toelk-A** [comment]
-> wird im Dienstpaln nach wie vor das Nicht verfügbar mit aufgelistet? Meines Erachtens nach kam diese Info nämlich aus dem Teamkalender?

**Comment by chrbusch** [comment]
"nicht verfügbar" ist kein Job, sondern eine Analyse der Verfügbarkeit; anbei die Liste aller Jobs.
Können wir das gemeinsam ansehen ab 16.3., wenn ich wieder einen größeren Bildschirm zur Verfügung habe?
![Bildschirmfoto 2019-03-12 um 07 57 24](https://user-images.githubusercontent.com/1241899/54183690-a7a97b80-449c-11e9-876a-9040aa7269c1.JPG)

**Comment by Toelk-A** [comment]
Das Ticket wurde am 04.12.18 eröffnet, damals war "nicht verfügbar" noch ein Sonderjob... bis Sie es geändert haben...

**Comment by Toelk-A** [comment]
Wir benötigen hier noch immer die info:


Bitte im Dienstplan, wie früher einmal vorhanden, "RBD nicht verfügbar" abbilden.

Danke
