### ISSUE TITLE
Button "Rechnung GTM-V an die Bank" - Preis wird falsch abgebildet und musste manuell geändert werden

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#454]
Nach Klick des Buttons werden die hinterlegten 630,-€ nicht pro Position sonder der Betrag von -1 in der "Rechnung" abgebildet.

![image](https://user-images.githubusercontent.com/22314271/49506548-9ee25180-f87e-11e8-9254-a9561dc00884.png)

## 2) Wie können wir den Rechnungstext ändern? 

Frau Kerstin Schacht arbeit seit 2 Jahren nicht bei uns. Wir haben schon oft versucht den Text zu ändern, leider wird Frau Schacht immer wieder automatisch eingefügt.

![image](https://user-images.githubusercontent.com/22314271/49506719-0b5d5080-f87f-11e8-9a01-0acc639088f2.png)

**Comment by chrbusch** [comment]
Ad 2) Bislang war dieser Text "fest verdrahtet"; nun wird er entmommen aus Textbaustein 24 = "Nachtext Rechnung "an die Bank""
Sie können ihn also selbst jederzeit anpassen.

![image](https://user-images.githubusercontent.com/1241899/49652223-ba418e00-fa31-11e8-9f66-d167c6fd27e7.jpeg)

**Comment by chrbusch** [comment]
Der Wert   -1  resultiert, wenn für die Komination aus Präparateart, KundenID usw kein preis gefunden wurde.
Ich habe jetzt statt dessen dafür gesorgt, dass der Preis leer bleibt.
Aber v.a. sollte die Preistabelle so erweitert werden, dass immer ein Preis gefunden wird.

**Comment by chrbusch** [comment]
Zunächst mal habe ich, weil die Suche nach "kurzen IDs" wie 24 zahllose Adressen findet, die diese Ziffern zB als PLZ haben, den Suchdialog verbessert: Gibt man nur eine Zahl ein und klickt den Button ID, so wird NUR in der ID gesucht, was immer einen einzigen Treffer ergibt.

![image](https://user-images.githubusercontent.com/1241899/49717026-eb9aa380-fc55-11e8-9765-8df451919ed2.jpeg)

**Comment by chrbusch** [comment]
Ein Problem scheint zu sein, dass für Transplantate nur dann ein eindeutiger Preis gefunden wird, wenn Klassifikation und OP-Verfahren ausgfüllt sind; dies ist aber bei ABBRUCH oft nicht der Fall!
Wie handhaben wir dies? Dafür einen spez. Preis-Datensatz anlegen?

**Comment by Toelk-A** [comment]
### Ein Problem scheint zu sein, dass für Transplantate nur dann ein eindeutiger Preis gefunden wird, wenn Klassifikation und OP-Verfahren ausgfüllt sind; dies ist aber bei ABBRUCH oft nicht der Fall!
Wie handhaben wir dies? Dafür einen spez. Preis-Datensatz anlegen?

-> Diese Rechnung hat nichts mit der Rechnungsstellung GTM-V an Transplantierende Einrichtung und zugehörige B-Rechnung zu tun. Aus diesem Grund braucht hier nicht nach Voroperationen gesucht werden. Der Preis ist zurzeit immer Fix 630€ dementsprechend müsste also wahrscheinlich ein neues Feld angelegt werden, indem die 630€ "Rechnungsstellung GTM-V an GBM-V" abgebildet werden.

**Comment by Toelk-A** [comment]
tipp kundenspezifische preise - kunde = gbmv

**Comment by chrbusch** [comment]
Habe Email an Dr. Manecke gesendet mit der Bitte, den Button "Rng an die Bank" beim nächsten Mal mit mir zusammen zu benutzen

**Comment by chrbusch** [comment]
Die Preisfindung wurde nun so dynamisiert, dass für die AdressenID 24 = GBMV (und für bel. weitere gewebeproz. Einrichtungen) kunden-spezif. Preise hinterlegt werden können.
Zur Zeit steh thier für CSK 630 Eur, die Erstellung einer neuen "Rng an die Bnak" hat autom. funktioniert
