### ISSUE TITLE
Spendermeldung durch Dateiimport erfassen

### ISSUE THREAD

**Issue by chrbusch** [chrbusch/GTM-V#459]
Meld. Einrichtungen können teilweise Textdateien (CSV) auf dem Server der GTMV ablegen bzw. per ftp abholen lassen.
Diese sollen importiert werden, wodurch eine Spd-Meldung in Ornella angelegt werden soll.
Danach soll eine entspr. Meldung an die iPhones-Anwender gesendet werden über GTMV_Go

**Comment by chrbusch** [comment]
Techn. Bem.: Importscript (in Arbeit) ist "SpdMeldung01PB.Importieren aus CSV <??> / " in Prog.

**Comment by chrbusch** [comment]
Maik, bitte weiter machen.
Die CSV-Dateien sollen in unserem Standardordner landen; das obige Script ist teilweise auf Übergabe der Werte als Scrpar vorbereitet. Es müssen noch ICD ausgelesen werden und in PatDgn als neue DSe angelegt werden; ferner eine WV an die Ärzte, wenn ein Spender per CSV kam

**Comment by chrbusch** [comment]
Heute morgen kam Spender 7952 mit Station "ICM", die nicht erkannt wurde.
Diese Information erscheint künftig mit in der WV, die über den Eingang der Meldung informiert

**Comment by Toelk-A** [comment]
Dies kann daran liegen, dass die IMC früher zur "X1" gehörte.. ich werde dies prüfen wenn der zuständige Mitarbeiter im Büro ist und Ihnen Rückmeldung geben

**Comment by chrbusch** [comment]
Ich denke, dieses Ticket kann geschlossen werden
