### ISSUE TITLE
Einwilligungserklärung 

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#46]
Verwandtschaftsgrad Dropdown: Angehörige gemäß Transplantationsgesetz ins Drop-Down setzen (hatte ich in der Exceltabelle damals angegeben):

![image](https://cloud.githubusercontent.com/assets/22314271/20099640/cedd0c96-a5b9-11e6-9734-3bb400d4e5a0.png)

**Comment by chrbusch** [comment]
Ich habe die Auswahlliste angepasst

**Comment by Toelk-A** [comment]
funktioniert
