### ISSUE TITLE
Buchhaltung weiter ausbauen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#461]
Hallo Herr Prüter,

mit Bezug auf unser heutiges Telefonat sende ich Ihnen anbei noch die Buttons die zukünftig (mit zusätzlichen Programmierungen) unter dem Menüpunkt „Buchhaltung“ abgebildet werden sollen:

![image](https://user-images.githubusercontent.com/22314271/51039817-5bce7900-15b6-11e9-8274-e78f0400a2b3.png)

### 1) Abrechnung MSG-Entnahmen
Spenderdetails -> ganz unten links Button "Rng MSG an die Bank für diesen Spender"
![image](https://user-images.githubusercontent.com/22314271/51040056-c8497800-15b6-11e9-98ed-31ebe2568b0e.png)

-> Hinter diesem Button ist die Abrechnung der MSG Präparate an das DIZG programmiert. Jede Abrechnung muss also über die Spenderdetailsmaske durchgeführt werden. **_Dies soll zukünftig nicht mehr so sein._**

Als Menüunterpunkt zur "Buchhaltung" soll, wie oben gezeigt, ein Button "Abrechnung MSG-Entnahmen" erstellt werden. Hierzu muss das Skript ein wenig angepasst werden:

Ähnlich der AGE Rechnungen (Skript ist im Button "Entnahmen prüfen/abrechnen hinterlegt) benötigen wir folgende Programmierungen:
![image](https://user-images.githubusercontent.com/22314271/51099712-a1678d80-17d2-11e9-97ee-464a868c495b.png)

# 1A) Auswahl Zeitraum Abrechnung (Prüflauf wird nicht benötigt)
-> im genannten Skript hinterlegt

![image](https://user-images.githubusercontent.com/22314271/51099767-decc1b00-17d2-11e9-9c7c-fb58e04b7b64.png)

#  1B) manuelle Auswahl der abzurechnenden MSG Entnahmen

Hier benötigen wir die Liste der im gewählten Zeitraum noch nicht in Rechnung gestellten MSG-Entnahmen. In der Liste muss manuell auswählbar seine welche Entnahmen abgerechnet werden sollen. Weiterhin muss für jede Entnahme eine separate Rechnung erstellt werden. Programmierungen zur MSG Abrechnung sollten unter dem Button "Rng MSG an die Bank für diesen Spender" zu finden sein.

### 2) Erstellung AGE "Rechnungen" 

Wie oben gezeigt benötigen wir ebenfalls im Menü Buchhaltung den Untermenüpunkt / Button "Auflistung Gewebeentnahmen - AGE"

![image](https://user-images.githubusercontent.com/22314271/51100681-6f0c5f00-17d7-11e9-915c-bd0bc8037e9c.png)

-> Derzeit werden die "AGE - Rechnungen" über den Menüpunkt Adressen Entnahmeeinrichtungen erstellt:

![image](https://user-images.githubusercontent.com/22314271/51099712-a1678d80-17d2-11e9-97ee-464a868c495b.png)

# 2A) Skript kann komplett übernommen werden (inkl. Prüflauf!)

#2B) Skript bitte erweitern, sodass eine Gesamt PDF von allen abzurechnenden Geweben (also aus verschiedenen medizinischen Einrichtungen) erstellt wird.

**Comment by mprueter** [comment]
**Abrechnung MSG**

Die Abrechnung MSG kann ab jetzt im Hauptmenü wie folgt gestartet werden:

![bildschirmfoto 2019-01-21 um 12 18 24](https://user-images.githubusercontent.com/3273572/51471449-ff6a1700-1d76-11e9-9089-52840806a2d3.png)


...es erscheint ein Modalfenster, in dem alle Spender angezeigt werden, für die es noch nicht abgerechenete MSG-Präparate gibt (ACHTUNG: es werden nur Daten mit Entnahmedatum > 30.09.2018 anegezeigt)

![bildschirmfoto 2019-01-21 um 12 28 36](https://user-images.githubusercontent.com/3273572/51472187-19a4f480-1d79-11e9-98a1-8a2cd5e3e00d.png)



Hier haben Sie jetzt die Möglichkeit mit dem Popover-Button "P" zu prüfen, ob die Anzahl Knochen/Sehnen korrekt ist:

![bildschirmfoto 2019-01-21 um 12 23 47 kopie](https://user-images.githubusercontent.com/3273572/51472265-46f1a280-1d79-11e9-99bf-999f440e1da8.png)



![bildschirmfoto 2019-01-21 um 12 24 00](https://user-images.githubusercontent.com/3273572/51471939-5fad8880-1d78-11e9-9f19-c5dce0d2b54a.png)

Sollte dies nicht der Fall sein oder ein anderer Ausschlussgrund vorliegen, entfernen Sie bitte den Spender mit dem "Red"-Button aus der Auswahl:


![bildschirmfoto 2019-01-21 um 12 23 47](https://user-images.githubusercontent.com/3273572/51472208-20336c00-1d79-11e9-90d5-fb4e95d6a397.png)
 
Sobald Sie die richtige Fundmenge zusammengestellt haben, erstellen Sie automatisch via "MSG abrechnen" für jeden Spender eine Rechnung. (Die Rechnungen sind aber durcheine Vorgangsnummer verbunden!)

![bildschirmfoto 2019-01-21 um 12 40 41](https://user-images.githubusercontent.com/3273572/51472486-dd25c880-1d79-11e9-8a91-4436a1a15352.png)

...nach der Erstellung der Rechnungen, werden diese in der Rechnungsliste aufgrufen (Hier sehen Sie auch einen Storno, weil es Testdaten sind!):

![bildschirmfoto 2019-01-21 um 12 42 51](https://user-images.githubusercontent.com/3273572/51472590-38f05180-1d7a-11e9-83f3-c12777e64a91.png)

Das Erstellen einer PDF-Datei mit allen Rechnungen eines Vorganges, erfolgt wie der normale Rechnungsdruck auch, auf der Detailsmaske einer Rechnung. Sollte es sich bei der zu druckenden Rechnung um eine Rechnung mit einer Vorgangsnummer handeln, erscheint folgender Dialog:

![bildschirmfoto 2019-01-21 um 12 48 24](https://user-images.githubusercontent.com/3273572/51472822-e499a180-1d7a-11e9-9e5c-a04f45672914.png)

..so haben Sie die Möglichkeit, gezielt eine Rechnung zu drucken oder (!)  alle zugehörigen Rechnungen.

Das Stornieren der MSG-Rechnungen erfolgt ggf. wie gewohnt. Dei zugehörigen SpdPräparate verlieren dabei ihren Bezug zur Rechnung und können/müssen ggf. neu abgerechnet werden

**Comment by Toelk-A** [comment]
A) Nach welchem Kriterium werden die abzurechnenden MSG Spenden im "Modalfenster" (nach Klick auf Button "MSG-abrechen") angezeigt?

B) Es scheint einen BUG zu geben.

Buchhaltung ->Button "Liste Deb. Rechnungen" -> Button "Abgleich Kontobewegungen" -> ok -> Button Kto-Bew. -> öffnet sich MSG Abrechnungsfenster:

![image](https://user-images.githubusercontent.com/22314271/51523599-567df380-1e2c-11e9-823b-f8d4546f3e94.png)

**Comment by Toelk-A** [comment]
Abrechnung MSG -> Punkt 1) ist erledigt und funktioniert super!
Ich hätte gern noch folgendes Fine Tuning:
-> Versandinfo Button "Set" -> "per Mail oder per Post versandt"

![image](https://user-images.githubusercontent.com/22314271/51660847-4e01f600-1faf-11e9-90b5-38d48d3a6f90.png)

-> Hier wäre es super wenn der Klick auf Mail / Post auch für alle Rechnungen der selben Vorgangsnummer hinterlegt werden könnt (ähnlich der Abfrage alle Rechnungen der selben Vorgangsnummer drucken?)
![image](https://user-images.githubusercontent.com/22314271/51660893-7a1d7700-1faf-11e9-8ec5-e0a3114cd1ed.png)

**Comment by mprueter** [comment]
..das funktioniert jetzt genauso, wie beim Drucken. Es erscheint, sofern es eine Vorgangsnummer bei der Rechnung gibt, folgender Dialog:

![bildschirmfoto 2019-01-26 um 18 19 50](https://user-images.githubusercontent.com/3273572/51790546-1655a280-2197-11e9-832c-e60a6097641e.png)

...alles andere ist wie bisher.

**Comment by Toelk-A** [comment]
Super Herr Prüter!

Bitte noch Punkt 2 "AGE Rechnungen" programmieren

**Comment by mprueter** [comment]
Ich habe die AGE-Sammelabrechnung fertig programmiert. Allerdings habe ich es noch nicht geschafft einen Testlauf durchlaufen zu lassen.

@chrbusch: Könntest Du dies bitte zusammen mit Frau Tölk machen? Der Ablauf ist wie bei den MSG-Abrechnungen (s.o.)

Es gibt im Hauptmenü unter BUCHHALTUNG jetz den Button "AGE-Abrechnungen erstellen":

![bildschirmfoto 2019-02-01 um 17 28 03](https://user-images.githubusercontent.com/3273572/52135917-35e14500-2647-11e9-96e4-c4e41d2099f5.png)

Es werden dabei folgende Script benutzt:

![bildschirmfoto 2019-02-01 um 17 28 12](https://user-images.githubusercontent.com/3273572/52135978-51e4e680-2647-11e9-8841-b07a86c3e53f.png)

Der Btn. im HM ruft folgendes Modalfenster auf, in dem alle Adressen angezeigt werden, für die im gewählten Zeitraum Entanhemn abgerechnet werden können:

![bildschirmfoto 2019-02-01 um 17 33 17](https://user-images.githubusercontent.com/3273572/52136086-8b1d5680-2647-11e9-927a-b1ec685d9652.png)

Wenn man hier auf "AGE Abrechnen" klickt, werden die Abrechnungen in einer Scheife erstellt. Die Abrechnungen sind durch eine Vorgangsnummer verbunden (Frau Tölk, das funktioniert genauso, wie bei den MSG-Rechnungen). Am Ende des Vorgangs wird eine Liste mit den erstellten AGE-Abrng. aufgerufen.

**Comment by Toelk-A** [comment]
Funktioniert alles!
