### ISSUE TITLE
Buchhaltung - Zahlungserinnerung muss aktuelles Datum anzeigen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#463]
Buchhaltung

Die Rechnung mit der ID 2462 wurde gestern als 2. Zahlungserinnerung versandt. 

![image](https://user-images.githubusercontent.com/22314271/51230841-b7578880-1961-11e9-9e1e-5fd44761aebf.png)

Hierbei ist uns aufgefallen, dass leider nicht das aktuelle - sonder das Erstellungsdatum der Rechnung auf der Zahlungserinnerung abgebildet wird.

Können Sie dies bitte ändern?

![image](https://user-images.githubusercontent.com/22314271/51230773-7fe8dc00-1961-11e9-977d-f451d9e2d5e3.png)

Die Rechnung werde ich jetzt stornieren. Zukünftig muss das Datum am Tag der Zahlungserinnerung abgebildet sein.

**Comment by mprueter** [comment]
Das solltejetzt ncht mehr passieren. Sofern ein Mahndatum vorhanden ist, wird dieses als Belegdatum gesetzt, ansonsten das RngDatum. Bitte bei Gelegenheit prüfen...
