### ISSUE TITLE
Personalmodul Urlaubsberechnung 2019

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#464]
Derzeit sind noch die Urlaubsdaten von 2018 im System hinterlegt. Für 2019 muss der Urlaub angepasst werden. Hierfür benötigen wir entweder ein neues Feld "Urlaubsanspruch 2019" oder wir "Nullen" 2018.

![image](https://user-images.githubusercontent.com/22314271/51235913-00630900-1971-11e9-8987-11ce7903cd9a.png)

**Comment by chrbusch** [comment]
Hallo Maik, ich habe zu spät gesehen, dass dies an dich geschickt wurde.
Ich habe im Persomodul eine neue Tabelle MitarbJahre angelegt, dann riss aber die Verbindung ab.
m.E. sollte man in der Jahrestabelle Urlaubsanspruch und Resturlaub speichern oder?
Du hast das m.E. schon mehrfach selbst gemacht.

**Comment by mprueter** [comment]
…wenn man das ordentlich machen möchte, kommt man nicht um eine Jahrestabelle herum. Die Frage ist, wie die Daten dort gepflegt werden bzw. wie die jetzigen Daten gesetzt werden. Sehe ich mir mal an…

**Comment by chrbusch** [comment]
Ich habe auf dem Layout noch ein )seit langem existierendes) Feld platziert, das den im lfd. Jahr schon genommenen Urlaub anzeigt.
Das System zeigt m.E. aktuell schon die richtigen Daten, aber Maik Prüter übernimmt dieses Urlaubsticket und setzt eine verbesserte Lösung mit einer Tabelle um, die die Jahreswerte dauerhaft speichert.

**Comment by Toelk-A** [comment]
Funktioniert dieser Button?

![image](https://user-images.githubusercontent.com/22314271/53942924-4b211780-40bc-11e9-99cb-61fa3da2ed1d.png)

**Comment by mprueter** [comment]
…ja, eigentlich schon. Gibt es Probleme?


Mit freundlichen Grüßen

Maik Prüter

__________________________________________
IT-Büro Dr. Christopher Busch
Sottorfallee 18
22529 Hamburg

(+49) 0170 - 165 8887


Kontakt in Potsdam:
Maik Prüter
Pomonaring 9
14469 Potsdam
(+49) 0331 - 96 76 35 93
m.prueter@christopherbusch.de

**Comment by Toelk-A** [comment]
nach klick auf den Button bei der gezeigten Mitarbeiterin, änderten sich nicht die genommenen Urlaubstage 2018

**Comment by Toelk-A** [comment]
Wenn der Button funktioniert, kann das Ticket geschlossen werden

**Comment by Toelk-A** [comment]
Bitte Die Berechnung der Urlaubstage prüfen:

im persönlichen Kalender werden andere Werte abgebildet als auf dem Reiter Mitarbeiter Urlaub

![image](https://user-images.githubusercontent.com/22314271/66371360-3767c780-e9a3-11e9-9249-631062d693f4.png)

![image](https://user-images.githubusercontent.com/22314271/66371411-56fef000-e9a3-11e9-8e3f-fcf25c6eb350.png)
