### ISSUE TITLE
Virologische Freigabeliste - Bitte Auditlog abbilden

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#466]
Wie telefonisch besprochen bitte unter der Spender ID den Auditlog zur Werteliste "virologische Freigabe, veranlasst, beauftragen...." abbilden 

![image](https://user-images.githubusercontent.com/22314271/51673471-62a1b680-1fce-11e9-93ad-616de927bcac.png)

**Comment by mprueter** [comment]
SIe finden jetzt auf der Virolog. Freigabeliste einen Button, mit dem Sie den Auditlog zum jeweiligen Gewebe aufrufen können:

![bildschirmfoto 2019-01-27 um 15 52 54](https://user-images.githubusercontent.com/3273572/51802619-29767a00-224c-11e9-9247-a20e4dd01dd9.png)

...es öffnet sich dann ein neues (Modal-)Fenster mit allen vorhandenen Auditlog-Datensätzen zum jeweiligen Gewebe:

![bildschirmfoto 2019-01-27 um 15 52 26](https://user-images.githubusercontent.com/3273572/51802630-490da280-224c-11e9-9161-802e8c3051d9.png)

...in der Regel sehen Sie alle Datensätze zu einem Gewebe. Das obige Beispiel zeigt die (bisher) einzige Ausnahme: Bei der Gewebeart "OG" wird der virolog. Status zwar auf der Liste beim Gewebe angeziegt, aus technischen Gründne aber tatsächlich bei den zugehörigen Transplantaten gesetzt. Deswegen werden hier sicherheitshalber die Auditlog-Datensätze der zugehörigen Transplantate gezeigt.

Dieses Modalfenster können wir jetzt im Prinzip überall einsetzen, wo Auditlogdatensätze erzeugt werden, um diese zu zeigen!

Mit ist aufgefallen, dass bei vielen Datensätzen, die auf "virologische Freigabe" gesetzt wurden, kein Auditlog-Datensatz vorhanden ist. Es muss noch irgendwo eine Möglichkeit geben, diesen Status zu setzen, ohne dass das Auditlogscript angeworfen wird. Das müssen wir noch einmal klären...

**Comment by mprueter** [comment]
...bei der Änderung des Freigabe Status auf der Spender-Detailmaske wird jetzt auch das Auditlog bedient, sofern die zugehörigen Transpl./Gewebe beim Status der virolog. Freigabe auf "virolog. Freigabe" gestezt werden sollen. Das wurde hier bisher nicht geloggt.

**Comment by Toelk-A** [comment]
erledigt
