### ISSUE TITLE
Bitte noch folgende Buttons ausblenden

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#468]
Im Rahmen der MSG-Rechnungsprogrammierung haben wir noch 2 "Buttonleichen". Bitte blenden Sie diese aus:

1) Spenderdetails -> unten links -> "Rng MSG an die Bank"

![image](https://user-images.githubusercontent.com/22314271/51675931-6f75d880-1fd5-11e9-8864-a11cd8f6425b.png)

2) Spenderliste -> rechts oben "Spender MSG-Rng"

![image](https://user-images.githubusercontent.com/22314271/51676006-9df3b380-1fd5-11e9-9261-ca7b1bacaf4d.png)

Danke :-)

**Comment by mprueter** [comment]
Ist erledigt..
