### ISSUE TITLE
Einwilligungserklärung II

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#47]
Abschnitt Rahmenbedingungen „Gesprächsort“
Bitte Dropdown anlegen mit:

„Telefonat“, „Station“, „Sonstiges“ und Eingabefeld

**Comment by chrbusch** [comment]
Das ist doch schon seit heute morgen so? Wenn Sie in ein Feld, das ein dropdown hat, erneut hinein klicken können Sie einen bel. Text tippen

**Comment by Toelk-A** [comment]
ok erledigt
