### ISSUE TITLE
Personalmodul - AZK Wunsch 

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#470]
Sonderjob "AZK-Wunsch" zeigt ebenfalls kein Tages Soll an... Bitte entsprechend anpassen, da sonst fälschlicher Weise Stunden im AZK "gutgeschrieben" werden.... siehe "nicht verfügbar" als Sonderjob

![image](https://user-images.githubusercontent.com/22314271/52062040-090e2e80-2570-11e9-9b78-e6f2468900d6.png)

**Comment by Toelk-A** [comment]
ist dies erledigt?

**Comment by chrbusch** [comment]
Formel ist erweitert auf AZK-Wunsch, bitte testen
