### ISSUE TITLE
GBMV/ KVG Transplantat Details -> Werteliste Monatsstatistik einbauen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#471]
Wie bei den OG Transplantatdetails benötigen wir auch bei den KVG Details eine Werteliste "Grund für Monatsstatistik"

![image](https://user-images.githubusercontent.com/22314271/52193829-5b419f00-2851-11e9-8d63-e061e0bf29cc.png)

![image](https://user-images.githubusercontent.com/22314271/52193867-8a581080-2851-11e9-950b-ef311b4403f2.png)

Da wir sonst in der Monatsstatistik keine Angaben "Grund für Nichttransplantation" haben..

![image](https://user-images.githubusercontent.com/22314271/52193891-a5c31b80-2851-11e9-9367-04e3735fd88e.png)

**Comment by chrbusch** [comment]
Und welche Werte soll diese Liste haben?

**Comment by Toelk-A** [comment]
Wie oben beschrieben Herr Dr. Busch. Es ist genau die selbe Werteliste "Grund für Monatsstatistik ( wie oben rot markiert), die für die OG-Transplantatdetails genutzt wird.

**Comment by chrbusch** [comment]
Moin,
Feld ist platziert; dass es dieselbe Werteliste bekommen soll, stand nicht oben, und ich halte es auch nicht für sinnvoll.
Oder kann es zB bei KVG eine Endothelzellnekrose geben?

![image](https://user-images.githubusercontent.com/1241899/52553640-6f9f1200-2de4-11e9-8acf-4abb0ce0764c.jpeg)
