### ISSUE TITLE
GBMV/ Abrechnung Spaltlampenbefunde  Modifizierung der Abrechnung

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#473]
![image](https://user-images.githubusercontent.com/22314271/52463005-9572af80-2b75-11e9-934b-2fb303d6a917.png)

![image](https://user-images.githubusercontent.com/22314271/52463015-9c99bd80-2b75-11e9-9d09-0f39340e89f4.png)

![image](https://user-images.githubusercontent.com/22314271/52463022-a4596200-2b75-11e9-8f0e-4ebb758f0709.png)

Pro Hornhaut werden ca. 2 Spaltlampenuntersuchungen durchgeführt. In der Auflistung, soll aber nur die letzte (aktuellste) Spaltlampe der jeweiligen Hornhaut abgebildet und somit berechnet werden. Achtung es darf nicht zu Doppelberechnungen in 2 verscheideneen Monaten kommen. **Generell soll pro Hornhaut 1x Spaltlampe abgerechnet werden.**

![image](https://user-images.githubusercontent.com/22314271/52463199-542ecf80-2b76-11e9-8917-7f657bef9bae.png)

![image](https://user-images.githubusercontent.com/22314271/52463218-67419f80-2b76-11e9-80f8-1b7b11f31c72.png)

**Comment by chrbusch** [comment]
Dann ist das eine ganz andere Aufgabe als die bislang programmierte Befundauswertung; u.a. muss man Buch führen, welche HH schon abgerechnet wurde.
Ich dupliziere diese alte Script und modifiziere es für diese Aufgabe.

**Comment by chrbusch** [comment]
Sie finden nun den neuen Button
Abrng. SpaltLampenbefund
ebenfalls im Bereich "Auswertung"

**Comment by Toelk-A** [comment]
scheint zu funktionieren

**Comment by Toelk-A** [comment]
Folgende Spaltlampe wurde bereits im Vormonat abgerechnet und taucht nun wieder in der Liste auf. bitte prüfen.

[Spaltlampe.pdf](https://github.com/chrbusch/GTM-V/files/3809605/Spaltlampe.pdf)

**Comment by chrbusch** [comment]
Es wurden hier ZWEI Eingangsbefunde angelegt, das ist der Fehler
