### ISSUE TITLE
MSG Entnahmebericht - Todesursache abbilden

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#474]
Bitte im MSG Entnahmebericht im Feld "Besonderheiten" zukünftig die Todesursache abbilden.
Dies soll folgendermaßen aussehen:

![image](https://user-images.githubusercontent.com/22314271/52558056-8b5ce500-2df1-11e9-9370-53c6103a57a0.png)

Die Todesursache finden Sie in den Spenderdetails - Reiter Spenderdaten - Abschnitt Diagnosen
-> Die Todesursache wird mit einem "T" gelabelt. Bitte nur die "T"-gelabelte Diagnose im MSG-Entnahmebericht abbilden und bitte die Abkürzung "TU:" voranstellen

![image](https://user-images.githubusercontent.com/22314271/52558132-c3fcbe80-2df1-11e9-8512-b246355bbf4a.png)

**Comment by chrbusch** [comment]
Im NEUEN EB ist dies realisiert

**Comment by Toelk-A** [comment]
Spender ID 7371 -> hier sollte doch jetzt der neue Entnahmebericht schon Anwendung finden?
Die Todesursache wird nicht abgebildet. Ist der Button "Todesursache holen" schon programmiert?

![image](https://user-images.githubusercontent.com/22314271/52932036-d83f3f00-334e-11e9-9edd-53426d49f57d.png)

![image](https://user-images.githubusercontent.com/22314271/52932053-e55c2e00-334e-11e9-9f4b-9e20b2af7687.png)

**Comment by chrbusch** [comment]
Bei NEUEN Ente.Berichten kommt das automatisch; auch ist jetzt ein Button platziert (der unsichtbar ist, wenn keine Todesursache beim Spender angegeben wurde)

![image](https://user-images.githubusercontent.com/1241899/53405767-dada0e00-39b8-11e9-91b0-bef807a691b6.jpeg)

![image](https://user-images.githubusercontent.com/1241899/53405792-e3cadf80-39b8-11e9-9225-7f69b00a8b7e.jpeg)

**Comment by Toelk-A** [comment]
erledigt
