### ISSUE TITLE
Altersangaben Patienten in Ornella automatisch aktualisiert?

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#475]
Im Bereich Allokation konnten wir feststellen, dass das Alter der Patienten nicht dynamisch ist.

Folgende Patientin wurde am 07.08.2017 angelegt; Geburtsdatum 30.03.1956 -> zum damaligen Zeitpunkt war die Patientin 61 Jahre alt. Schaut man sich das Alter am 12.02.2019 an, so ist die Patientin noch immer 61 Jahre alt:

![image](https://user-images.githubusercontent.com/22314271/52616641-80f62600-2e99-11e9-86b3-2e24a49d3565.png)

Bitte Programmierung prüfen und BUG beheben.

**Comment by chrbusch** [comment]
Das ist Absicht!
Es wird das Alter bei Erstellung des Datensatzes "eingebrannt".
Bitte genau überlegen, ob wir das ändern sollten (was 5 Minuten dauert).
Was ist zB mit einer späteren Statistik des Alters der Patienten?

**Comment by Toelk-A** [comment]
Dann sollte das Alter beim zugeordneten Transplantat hinterlegt werden. Aber wie im genannten Fall können Patienten auch 2 oder mehr Transplantate von uns bekommen, sodass wir bei der Allokation immer das aktuelle Alter benötigen.

**Comment by chrbusch** [comment]
Das mit dem Transplantat ist eine sehr gute Idee!
Und das Patientenalter wird gleich dynamisch, give me 5 minutes

**Comment by chrbusch** [comment]
Erl.; und ich setze gerade in alle verschickten Transplantate das "Alter bei Transplantation" ein

**Comment by Toelk-A** [comment]
Kann ich dieses irgendwo einsehen? oder wird das alter im Hintergrund gespeichert?

**Comment by chrbusch** [comment]
Ich habe es gerade im Allokationsbereich der Transpl.-Detailmaske sichtbar gemacth

![bildschirmfoto 2019-02-12 um 10 49 51](https://user-images.githubusercontent.com/1241899/52626671-fa027700-2eb3-11e9-9161-9fafc854745d.jpg)
