### ISSUE TITLE
GBMV/ Personalmodul - Änderung Stundenzahl Gutschein bitte nicht rückwirkend

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#476]
Personalmodul - Mitarbeiterdetails - Überstd. Waren-GS

Wenn sich die "Überstd. Waren-GS" ändert, z.B. darf dies nicht rückwirkend für die vergangenen Monate geschehen. 
![image](https://user-images.githubusercontent.com/22314271/52767392-a1a1b580-302a-11e9-9128-a38942b012c2.png)

Gestern "testeten" wir die Änderung und es erscheint folgende Meldung:

![tks](https://user-images.githubusercontent.com/22314271/52767435-cb5adc80-302a-11e9-8c6d-ac05d93f6a63.jpg)

-> Bitte stellen Sie sicher, dass sich nur die folgenden Monate, in denen der Warengutschein noch nicht im persönlichen Kalender erscheint mit der neuen "Überstd. Waren-GS" abgerechnet wird. Gescheiht dies rückwirkend, wären alle AZK-Monatsabrechnungen in Ornella "nicht korrekt".

**Comment by chrbusch** [comment]
Bitte das neue Feld beachten; sind die Werte so richtig?

![image](https://user-images.githubusercontent.com/1241899/53324046-181e9d00-38e0-11e9-843d-c081baa8128e.jpeg)

**Comment by chrbusch** [comment]
Alles wurde nun umgebaut auf einen Wert des fraglichen Feldes PRO MONAT, der automatisch vom manuell eingetragenen Wert beim MA übernommen wird.
Bis einschl. Feb.2019 wurden die alten Werte in die Monate geholt, ab März2019 die geänderten.
Bitte aufmerksam testen!

**Comment by Toelk-A** [comment]
scheint zu funktionieren
