### ISSUE TITLE
GBMV/ Buchhaltung - Ausladung Übersicht Rechnungsstatus

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#477]
Für unsere englischen Kollegen benötigen wir wochen- bzw. monatsweise eine Ausladung (in Form einer PDF Datei) zu den gestellten "A und B-Rechnungen"

## 1) Button "Übersicht Rechnungsstatus für TRX"
-> Button bitte Buchhaltung - Funktion anlegen
![image](https://user-images.githubusercontent.com/22314271/52768015-74ee9d80-302c-11e9-841c-55be881d5e18.png)

## 2) Abfrage Zeitraum

Bitte Standardabfrage des Zeitraumes porgrammieren
![image](https://user-images.githubusercontent.com/22314271/52768077-a6ffff80-302c-11e9-9f22-24efa63aeb85.png)

## 3) Prüflauf vor Ausgabe einbauen
-> Gibt es zu jeder GTM-V Rechnung eine GBM-V Rechnung?
-> wurden Transplantate doppelt, in unterschiedlichen Rechnungen, abgerechnet?
-> Wenn Storno, wurde neue Rechnung ausgestellt?

## 4) Übersicht erstellen 
Die Transplantatliste können Sie als Grundlage nutzen:

![image](https://user-images.githubusercontent.com/22314271/52768174-00682e80-302d-11e9-8592-ac2da023c6b2.png)

Bitte folgende Werte in der Übersicht abbilden:
![image](https://user-images.githubusercontent.com/22314271/52768116-ceef6300-302c-11e9-8de1-a1e13412b869.png)

**Herstelldatum:**

![image](https://user-images.githubusercontent.com/22314271/52769177-d5330e80-302f-11e9-8319-7021572f3184.png)

**GBM-V-Code:**
= Banknummer des Transplantates

![image](https://user-images.githubusercontent.com/22314271/52769242-07dd0700-3030-11e9-8830-56ff8334f38e.png)

**Versanddatum**
![image](https://user-images.githubusercontent.com/22314271/52769333-45da2b00-3030-11e9-91e4-757d4216ffa5.png)

**d_Preis**
-> muss sich aus der Rechnungsnummer gezogen werden -> Hier aber bitte **nur** den Preis aus "B-Rechnung" nutzen. 

**alle Rngs_Nr - **
-> bitte aufsplitten in je 1 Spalte Rechnungsnummer GTM-V und 1 Spalte Rechnungsnummer GBM-V ="B-Rechnung"
-> zugehörig zur "A und B - Rechnung" soll der Status der Rechnung abgebildet werden (siehe weiter unten)

![image](https://user-images.githubusercontent.com/22314271/52769450-9baed300-3030-11e9-9869-f3024bc69118.png)

**Rechnungsdatum**

![image](https://user-images.githubusercontent.com/22314271/52769615-137cfd80-3031-11e9-9c78-d85bede5b2bf.png)

**Status**
-> Aufsplittung GTM-V und GBM-V in je eine Spalte (siehe "Rechnungsnummer)
-> 

A) GTM-V Rechnung
-> GTM-V Rechnung beglichen = Status "Bezahlt" invoiced
![image](https://user-images.githubusercontent.com/22314271/52783428-281dbd80-3052-11e9-8e37-468230637522.png)
-> dann in 

B) GBM-V Rechnung
-> zugehörige GBM-V Rechnung noch nicht beglichen, d.h. es ist noch kein Status bei "Zahlungseingang" auf den Rechnungsdetails hinterlegt

![image](https://user-images.githubusercontent.com/22314271/52783218-88f8c600-3051-11e9-9379-a5c401753bb7.png)

5) PDF erstellen
-> Überschrift

**Comment by Toelk-A** [comment]
Anbei wie eben besprochen das "Beispiel. Dies muss aber wie oben beschrieben noch modifiziert werden.

![image](https://user-images.githubusercontent.com/22314271/52941278-b0f56b80-3368-11e9-8524-5b8d6c749f67.png)

**Comment by Toelk-A** [comment]
Hallo Herr Prüter,

zu jeder "A Rechnung muss der Rechnungsstatus abgebildet werden" und zu jeder "B- Rechnung" ebenfalls. z.B. Kann die "A" Rechnung schon bezahlt worden sein, die "B Rechnung" aber noch nicht. Dies bitte noch in die jeweilige Rechnungsspalte mit einfügen.

![image](https://user-images.githubusercontent.com/22314271/53474496-7f1d8c80-3a6d-11e9-9c10-59c9e09bbeb5.png)

**Comment by mprueter** [comment]
nur famit keine Missverständnisse aufkommen: Was Sie im Moment als "Status" sehen, ist nicht der Statuts der GTMV-Rng, sondern der Status des Transplantates. Brauchen wir den gar nicht? Soll nur der Rng-Status der beiden zugehörigen Rechnungen dargestellt werden?

**Comment by chrbusch** [comment]
Bitte unverwechselbar benennen, etwa als
"Status Rng" und "Status Transpl."

**Comment by Toelk-A** [comment]
wie oben beschrieben, soll zu jeder Rechnung der Rechnungsstatus abgebildet werden.

**Comment by Toelk-A** [comment]
Wie schon telefonisch besprochen ist die PDF super geworden. Ich kann leider nicht die Werteliste Transplantate finden und somit die zusätzlichen Status nachtragen, die noch aufgenommen werden müssten. Wenn sich Dr. Busch zurückmeldet trage ich alles nach und lasse Ihnen die noch fehlende Information zukommen.

**Comment by Toelk-A** [comment]
Folgende **Transplantat**status bitte noch zusätzlich aufnehmen (gelbe Markierung):  
![image](https://user-images.githubusercontent.com/22314271/53562188-0e4fa080-3b51-11e9-8ec2-f9939cdf6709.png)

**Comment by Toelk-A** [comment]
Ab 01.03.2019 Herstellungsdatum werden alle Hornhäute mit der ihrer "Klasse" (transpl. QS + F&E) charakterisiert. Diese kann nun noch im PDF als auch in der Exceltabelle hinterlegt werden. Danach kann dieses Ticket geschlossen werden.

![image](https://user-images.githubusercontent.com/22314271/53785131-d1502900-3f17-11e9-8edb-11ec5579ab05.png)

**Comment by Toelk-A** [comment]
funktioniert alles super, danke
