### ISSUE TITLE
Buchhaltung Rechnung storniert die schon "zugeordnet ist"

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#479]
Hallo Herr Prüter,

aus Versehen wurde ein Transplantat unsererseits doppelt berechnet (Rechnungsnummer 2019-1579 sowie 2019-1578 inkl. zugehörige B-Rechnungen). Die transplantierende Einrichtung hat beide Rechnungen bezahlt (ohne vorherige Prüfung) und Dr. Nitschke hat den Geldeingang beiden Rechnungen in Ornella zugeordnet.

Heute stornierten wir die 2019-1578 inkl. B-Rechnung. Dies bedeutet aber auch im Umkehrschluss, dass die erfolgte Zuordnung "storniert" werden muss, bzw wenigstens auf "rot" zur erneuten Prüfung gesetzt werden muss (heir könnte auch eine Wiedervorlage an NIF und MAA erfolgen). Das selbe gilt auch für die B-Rechnungen, da die GTM-V der GBM-V das selbe Transplantat doppelt berechnet hat.

![image](https://user-images.githubusercontent.com/22314271/52855095-b82a3880-3120-11e9-8ecf-77b824f5e787.png)

**Comment by mprueter** [comment]
Hallo Frau Tölk,
ist das buchahalterisch so richtig? Das Geld ist ja schon geflossen. Eigentlich müsste m.E. jetzt eine Gutschrift an die Einrichtung (verbunden mit einer echten Zahlung oder wenigstens einer Aufrechnung mit anderen Rechnungen) erfolgen. Gleiches gilt auch für die internen Rechnungen...
Was meinen Sie?

**Comment by Toelk-A** [comment]
Ja da haben sie recht. Dies ist aber nach wie vor nicht programmiert. Gerne können wir Gutschriften programmieren, dann muss die Rechnung aber bei Erstellung einer Gutschrift trotzdem aus den Zuordnungen wieder "raus".

**Comment by mprueter** [comment]
Ich habe die Zuordnungen jetzt entfernt. Das können Sie auch selbst, wenn Sie den entsprechenden Datensatz in der Kontobewegungsliste aufrufen (-> Freie Suche). Ich habe die stornierten Rechnungen jeweils entfernt und den Btn IGNORIEREN bei der Kontobewegung aktiviert...

![bildschirmfoto 2019-02-18 um 10 55 04](https://user-images.githubusercontent.com/3273572/52943304-219e8700-336d-11e9-89f6-5d1c35b723d3.png)


![bildschirmfoto 2019-02-18 um 10 58 40](https://user-images.githubusercontent.com/3273572/52943313-25caa480-336d-11e9-9afc-13371e2f5c83.png)
