### ISSUE TITLE
Einwilligungserklärung III

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#48]
Abschnitt II Rahmenbedingungen - "Gesprächsteilnehmer"

Bitte 2 Dropdowns erstellen:
1) beratenden Koordinator (entspricht nichtärztliches Personal GTM-V) -> kann dann automatisch auf Seite 2 Unterschrift "Beratender Koordinator" übernommen werden

2) gesprächsführenden Arzt (entspricht ärztliches Personal GTM-V)

Bitte automatische Übernahme des Inhaltes des Feldes "Verwandschaftsgrad" (Abschnitt I Daten des nächsten Angehörigen) und Eingabefeld um weitere Personen hinzuzufügen

**Comment by chrbusch** [comment]
Ist jetzt so umgesetzt, bitte prüfen

**Comment by Toelk-A** [comment]
funktioniert super
