### ISSUE TITLE
GBMV/ Allokationswochenbericht - Status Sperre bankinterne Nummer rot einfärben

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#480]
Allokation - Allokations-Wochenbericht

![image](https://user-images.githubusercontent.com/22314271/52932158-2ce2ba00-334f-11e9-99ab-344babc80c4b.png)

Bank-Nr
grün markiert = Freigabe
blau = keine Freigabe

Bitte noch den Farbcode "rot" hinzufügen:

Besitzt das Transplantat den Status "Sperre", bitte die Bank-Nr rot einfärben. Die Rotfärbung steht hierarchisch an erster Stelle, d.h. ist das Transplantat bereits freigegeben (grün) und in Sperre muss es als "rot" angezeigt werden.

![image](https://user-images.githubusercontent.com/22314271/52932253-6f0bfb80-334f-11e9-9e71-e212257fc656.png)

**Comment by chrbusch** [comment]
Erl.
![image](https://user-images.githubusercontent.com/1241899/52937186-b8177c00-335e-11e9-8c1c-2187bc9b2fdc.jpeg)

**Comment by Toelk-A** [comment]
Leider nicht erledigt.

![image](https://user-images.githubusercontent.com/22314271/52939851-73dbaa00-3365-11e9-9a6c-5a085b67a92f.png)

**Comment by chrbusch** [comment]
Loops, Sie haben Recht! Filemaker arbeitet die Hierarchie anders ab, als ich dachte.
Nun wird grün gefärbt, wenn **Freigabe UND NICHT Sperre**

**Comment by chrbusch** [comment]
Das Bild zeigt ALLE Transplantate im Status 39
![image](https://user-images.githubusercontent.com/1241899/52941156-71c71a80-3368-11e9-9636-01a9c9c14894.jpeg)

**Comment by Toelk-A** [comment]
erledigt
