### ISSUE TITLE
Buchhaltung Storno Rechnung bitte Datum Storno einfügen, NICHT Datum Rechnung

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#481]
Rechnung wurde am 16.01.19 storniert.

![image](https://user-images.githubusercontent.com/22314271/52946235-dc318800-3373-11e9-9bb3-0c8be2326b03.png)

Druck Stornorechnung:

-> Bitte in Betreff Datum Rechnungserstellung abbilden
-> Storno: Rostock, XXXX bitte Stornodatum abbilden

![image](https://user-images.githubusercontent.com/22314271/52946291-008d6480-3374-11e9-8717-72ab433d29fa.png)

**Comment by Toelk-A** [comment]
Bitte Ticket bearbeiten

**Comment by mprueter** [comment]
Jetzt ist alles so, wie es sein soll:

![bildschirmfoto 2019-02-19 um 13 27 20](https://user-images.githubusercontent.com/3273572/53015049-59c7c780-344a-11e9-8389-8b1125fe30d5.png)


Damit das so funktioniert habe ich ein neues Feld "Datum_Storno" eingefügt, das automatisch beim Storinieren einer Rechnung mit dm aktuellen Datum befüllt wird:

![bildschirmfoto 2019-02-19 um 13 30 47](https://user-images.githubusercontent.com/3273572/53015219-ce026b00-344a-11e9-95c0-4c6af60e742e.png)

Für Altfälle habe ich einen SonderButton erstellt, der nur erscheint, wenn dieses Feld leer ist (damit Sie ggf. das Datm nachtragen können):

![bildschirmfoto 2019-02-19 um 13 31 23](https://user-images.githubusercontent.com/3273572/53015279-f7bb9200-344a-11e9-946a-809ee027aa7e.png)

**Comment by Toelk-A** [comment]
erledigt
