### ISSUE TITLE
Programmierung elektronischer Auftrag virologische Untersuchungen Plauen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#482]
Mit Bezug auf Ticket #435 muss eine elektronische Anforderung Zur Untersuchung der virologischen/serologischen Parameter nach Plauen versandt werden. Können Sie dies bitte programmieren?

**Comment by Toelk-A** [comment]
Nach unserem Telefonat erhalten Sie anbei den DIS Code der GTMV:

DE007656

https://webgate.ec.europa.eu/eucoding/lookup/compendium/secdipi.xhtml

**Comment by mprueter** [comment]
[Schnittstelle Befunderhebung_20180905.pdf](https://github.com/chrbusch/GTM-V/files/3127343/Schnittstelle.Befunderhebung_20180905.pdf)

**Comment by mprueter** [comment]
[20181019_Spezielles Screening_Rostock.pdf](https://github.com/chrbusch/GTM-V/files/3127345/20181019_Spezielles.Screening_Rostock.pdf)

**Comment by mprueter** [comment]
Für den Export der Daten ist ein Zuordnung der Plauener Parametername zu den Parameternamen in Ornella nötig. Diese sollte am besten von Ihnen (Fr. Tölk) vorgenommen werden.

Die entsprechende Eingabemaske befindet sich in der Basedata. Sie finden sie via STRG+4 und Auswahl BPL:

![Bildschirmfoto 2019-05-07 um 13 54 27](https://user-images.githubusercontent.com/3273572/57297415-d5432780-70cf-11e9-8134-b70a68fc0d47.png)

Dann bitte den Button "Plauen zeigen" suchen, um die erforderlichen Datensätze aufzurufen (ich habe alle Params berücksichtigt, die derzeit ein LDT Kürzel besitzen):

![Bildschirmfoto 2019-05-07 um 13 57 07](https://user-images.githubusercontent.com/3273572/57297596-44b91700-70d0-11e9-9150-5102008d7364.png)

...dann bitte in die gelbe Spalte die Plauener Krzel eintragen:

![Bildschirmfoto 2019-05-07 um 13 57 07](https://user-images.githubusercontent.com/3273572/57297656-7336f200-70d0-11e9-87f1-8857760674d7.png)


Die Küzel ergeben sich anhand folgender Tabelle (bitte die roten Befundnamen eintragen):

[20181019_Spezielles Screening_Rostock Kopie.pdf](https://github.com/chrbusch/GTM-V/files/3152458/20181019_Spezielles.Screening_Rostock.Kopie.pdf)

**Comment by mprueter** [comment]
Neuer Ansprechpartner BSD-Ost Plauen:
 
Hr. Wohlfarth, 0371/4322079 
h.wohlfarth@blutspende.de

**Comment by Toelk-A** [comment]
Hab die Parameterkürzel soweit vorhanden in Ornella hinterlegt. Uns fehlen noch einige Kürzel z.B.: Immunoblot zu TPHA.... werden die fehlenden Parameter noch nachgereicht oder bei Bedarf nachgefordert?

**Comment by mprueter** [comment]
Könnten Sie mir die fehlenden Parameter bitte auflisten, damit ich diese nach Plauen weiter reichen kann?

**Comment by mprueter** [comment]
Ich hab's schon. Es waren diese hier, oder?


anti-CMV
anti-HBc-IgM
anti-HCV-Immunoblot
CMT (Lues)
Trep.pall.-Blot (IgG)
Trep.pall.-Blot (IgM)

**Comment by mprueter** [comment]
Herr Franzky ist wieder der Ansprechpartner.

Von ihm habe ich die DGTI-Nr erhalten: 584 (vorläufig!!!)
Bezeichnung der Firma für Dateinamen etc . -> GT

Die Probennummer ist pro Röhrchen; ein Datensatz pro Probe und angefordertem Parameter.

Barcode auf Röhrchen entsprcht Probennummer.

**Comment by mprueter** [comment]
> Ich hab's schon. Es waren diese hier, oder?
> 
> anti-CMV
> anti-HBc-IgM
> anti-HCV-Immunoblot
> CMT (Lues)
> Trep.pall.-Blot (IgG)
> Trep.pall.-Blot (IgM)

Hier die angepasste Befundungstabelle von Hr. Franzky:
[20190513_Spezielles Screening_Rostock Kopie.pdf](https://github.com/chrbusch/GTM-V/files/3172943/20190513_Spezielles.Screening_Rostock.Kopie.pdf)

Bitte nachtragen...

**Comment by Toelk-A** [comment]
soweit es ging sind alle Parameter hinterlegt.

**Comment by Toelk-A** [comment]
Wie gehts in diesem Ticket weiter? wir werden in dieser Woche wieder Blutproben nach Plauen senden. Kann dies bereits elektronisch ausgelöst werden?

**Comment by Toelk-A** [comment]
Hallo Herr Prüter,

anbei die Mail von Herrn Franzky.

Pro Patient können wir von 1-200 Blutröhrchen senden. ALLLE haben die selbe 11-stellige Nummer. Es muss also weder zwischen Plasma, Serum Li-Hep noch zwischen prä/postmortal unterschieden werden.

VG und ein schönes Wochenende.

Hallo Fr. Tölk,

aktuell senden Sie uns eine bestimmte Anzahl von Röhrchen mit der gleichen Nummer.
Diese Vorgehensweise kann so beibehalten werden!!
Also pro Patient 1 Probennummern, d.h. die z.B. 5 Blutröhrchen habe alle die gleiche Nummern!!!


Mit freundlichen Grüßen

Hartmut Franzky
Unternehmensweiter Client Virenschutz
Lizenzmanagement
Datenschutzkoordinator P/Z


DRK-Blutspendedienst Nord-Ost
gemeinnützige GmbH
Röntgenstr. 2a
D-08529 Plauen

Tel:     +49 3741 407570
Mobil: +49 172 6547764
Fax:    +49 3741 40744570
Email:  h.franzky@blutspende.de
Web:   www.blutspende.de

**Comment by mprueter** [comment]
Der Barcode für die Blutproben enthält ab sofort folgenden Inhalt:

DGTI-Nr (3stellig) & Spender-ID (11stellig)
Bsp: 58400002312

Hintergrund ist der digitale Untersuchungsauftrag für das Labor in Plauen. Nach Rücksprache mit Hr. Franzky (s.o.) ist eine genaue Zuordnung der einzelnen Röhrchen zu einer Probe nicht nötig. Es reicht eine Zuordnung zu einem Spender. 

Da die Erfassung der Blutproben nicht in unmittelbarem Zusammenhang mit der Erstellung eines Untersuchungsauftrages erfolgt, sondern zeitlich davor und eine Zuordnung der Proben zu den angeforderten Befunden nicht nötig ist, war dieses Vorgehen derzeit am besten und user-freundlichsten zu realsisieren.

Für eine evtl. spätere Verwendung der Etiketten für eine Lagerverwaltung, ist derzeit die Verwendung von QR-Codes, die zusätzlich auf dem Etikett platziert werden angedacht.

**Comment by mprueter** [comment]
Die Erstellung eines didigtalen Untersuchungsauftrages an Plauen erfolgt jetzt automatisch beim Druck (STRG+5) eines an Plauen adressierten Untersuchngsauftrages. Dabei wird eine entsprechende Export-Datei auf dem Server im Verzeichnis

 /C:/Program Files/FileMaker/FileMaker Server/Data/Documents/FMSrvExport/

abgelegt. Von dort erfolgt die Weiterverarbeitung und die Übermittlung nach Plauen (Hr. Peter).

Aktuell wurden von mir an Hr. Franzky Testdaten per Email übermittelt, um die Funktionsfähigkiet der Barcodes in Verbindung mit dem digitalen Auftrag zu testen. Die Ergebnisse leigen noch nicht vor...

**Comment by mprueter** [comment]
@chrbusch 
Bitte folgende Scripte kritisch prüfen:
![Bildschirmfoto 2019-06-24 um 13 57 34](https://user-images.githubusercontent.com/3273572/60018442-a424b380-968b-11e9-9786-d0def618301d.png)

**Comment by Toelk-A** [comment]
Wie eben telefonisch vereinbart:

WENN Untersuchungsantrag nach Plauen geht, dann bitte den Barcode der Blutröhrchen unter dem Adressfeld abbilden.

![image](https://user-images.githubusercontent.com/22314271/60019102-5e68ea80-968d-11e9-8199-bdf8b7a53434.png)


Frau Tölk schickt anschließend den Untersuchungsantrag + Etikett per Post nach Plauen.

**Comment by chrbusch** [comment]
Ich habe die Scripts kontrolliert und für gut befunden

**Comment by mprueter** [comment]
Ein Untersuchungsauftrag an Plauen enthälz ab jetzt immer den geforderten Strichcode unterhalb des Adressfeldes:

![Bildschirmfoto 2019-07-02 um 15 53 22](https://user-images.githubusercontent.com/3273572/60518309-8ede0380-9ce1-11e9-8243-1d2c8a07a6ce.png)

**Comment by Toelk-A** [comment]
Super! wir versenden morgen Blut nach Plauen. Ich werde parallel den Brief mit dem Untersuchungsantrag + Etikett Blutröhrchen zu Herrn Franzky senden.

**Comment by mprueter** [comment]
Hallo Hr. Prüter,
 
nachdem wir im Mai schon Kontakt hatten, haben Sie während meines Urlaubs mit Hr. Franzky weiter am genannten Projekt gearbeitet. Da Hr. Franzky aktuell nicht verfügbar ist, nehme ich den Faden wieder auf. Ich beziehe mich speziell auf Ihre Mail vom 24.06.:

Haben Sie den Rücklauf einer Ergebnisdatei, basierend auf Ihrer Anforderungsdatei?

Zu Ihrer Frage: übermittelte Anforderungen, zu denen wir keine Röhrchen erhalten, übermitteln wir i.d.R. als „K.E.“ = kein Ergebnis und setzen diese auf nicht abrechenbar. Im Umkehrschluß: übermittelte Anforderungen mit Röhrchen werden befundet und abgerechnet! Unsere Schnittstelle kennt aktuell keinen Löschbefehl für nachträglich zurückgezogene Anforderungen.
 
Bei Fragen bitte melden.
 
Mit freundlichen Grüßen
Henner Wohlfarth
Koordinator IT
Stellv. AL IT
Datenschutzkoordinator C/L
 
DRK-Blutspendedienst Nord-Ost
gemeinnützige GmbH
ITM Chemnitz
Zeisigwaldstr. 103
D-09130 Chemnitz
 
Tel:   +49 371 43220-79
Fax:   +49 371 43220-44
Mobil: +49 173 6489410
eMail: h.wohlfarth@blutspende.de
Web: www.blutspende.de

**Comment by mprueter** [comment]
Hallo Hr. Prüter,
 
ich habe unsere Testumgebung um GTMV ergänzt und die Anforderungsdatei komplett verarbeitet. Im Ergebnis erhalten Sie eine „echte“ Ergebnisdatei samt den dazugehörigen Ergebnisprotokollen. Bitte bewerten. Falls Sie auch nichtnegative Ergebnisse testen wollen, dann mache ich das passend.
 
Mit freundlichen Grüßen
Henner Wohlfarth
Koordinator IT
Stellv. AL IT
Datenschutzkoordinator C/L
 
DRK-Blutspendedienst Nord-Ost
gemeinnützige GmbH
ITM Chemnitz
Zeisigwaldstr. 103
D-09130 Chemnitz
 
Tel:   +49 371 43220-79
Fax:   +49 371 43220-44
Mobil: +49 173 6489410
eMail: h.wohlfarth@blutspende.de
Web: www.blutspende.de
 
[MECKLENBURG_VORPOMMERN20190807.PDF](https://github.com/chrbusch/GTM-V/files/3485753/MECKLENBURG_VORPOMMERN20190807.PDF)

[MECKLENBURG_VORPOMMERN20190807_II.PDF](https://github.com/chrbusch/GTM-V/files/3485756/MECKLENBURG_VORPOMMERN20190807_II.PDF)

**Comment by Toelk-A** [comment]
Hallo Herr Prüter, können Sie bitte einmal in Plauen nachhaken? Vielen Dank

**Comment by mprueter** [comment]
siehe auch #775 wegen Covid19
