### ISSUE TITLE
Spendermeldungen aus CSV-Dateien übernehmen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#483]
Spender wurde automatisch angelegt allerdings OHNE Spenderkennnummer -> man kann den Spender somit nicht im System finden. ich habe die Daten nachgetragen. Bitte stellen Sie dieses Modul erst einmal hinten an, da wir erstmal die Entnahmeberichte auf die Reihe bekommen müssen.

Wir können nicht 2 große Baustellen auf einmal aufmachen. Das versteht Dr. Nitschke sicherlich

![image](https://user-images.githubusercontent.com/22314271/53071217-d9ed3c00-34e1-11e9-9bb9-613b888d5b31.png)

![image](https://user-images.githubusercontent.com/22314271/53071853-b2976e80-34e3-11e9-95c3-d15cc051c180.png)

Bitte deaktivieren Sie das System zum automatischen Einlesen von Spendermeldungen in Ornella. Ohne Anlegen einer Spenderkennummer gehen Meldungen verloren bzw. wir müssen die Eingabe doppelt prüfen. Dies ist keine Hilfe sonst zusätzliche Dokumentationsarbeit für uns.

**Comment by chrbusch** [comment]
Habe gerade die heutigen beiden SPdMeldungen und deren Ergebnis angesehen; Probleme:
A) Bei Adresse 561= Neuruppin ist kein Koordinator eingetragen
B) Im DataFile ist Station = "X2", aber in Ornella heisst keine Station "NPX2"
Bitte hierzu anrufen

**Comment by chrbusch** [comment]
Bitte sehen Sie sich den Spender 7858 genau an: Können hier weitere Werte aus dem DataFile übernommen werden? zB der Standort ganz oben? Vermutlich kann man je nach Adresse der meld. Einrichtung den Standort setzen, zB Neuruppin ist immer "GTMV HRO"?

**Comment by Toelk-A** [comment]
### A) Bei Adresse 561= Neuruppin ist kein Koordinator eingetragen
erledigt

### B) Im DataFile ist Station = "X2", aber in Ornella heisst keine Station "NPX2"

Die Adresse lautet NPX2ITS

Werden die Meldungen nur 1x am Tag abgerufen und in Ornella eingespeist? Eine der beiden Meldungen kam wohl heute Nacht und wurde erst heut morgen 08:00Uhr angelegt?

**Comment by Toelk-A** [comment]
### itte sehen Sie sich den Spender 7858 genau an: Können hier weitere Werte aus dem DataFile übernommen werden? zB der Standort ganz oben? Vermutlich kann man je nach Adresse der meld. Einrichtung den Standort setzen, zB Neuruppin ist immer "GTMV HRO"?

Habe den Standort in Adressen hinterlegt. Auf diesen kann zukünftig zurückgegriffen werden:

![image](https://user-images.githubusercontent.com/22314271/55384138-2e94c580-552a-11e9-8ce3-03cc9809f79b.png)




### Meldezeit
Die Meldezeit ist nicht korrekt. Laut FTP Datei kam die Meldung am 02.04.2019 05:34Uhr

![image](https://user-images.githubusercontent.com/22314271/55384065-0016ea80-552a-11e9-8e5f-518cf24c5b1f.png)


![image](https://user-images.githubusercontent.com/22314271/55384034-e70e3980-5529-11e9-8dfd-79db776487c5.png)


### Übernahme Prozeduren
In Spalte "H" in der Exceldatei sidn die Prozeduren verschlüsselt. Diese können auch übernommen werden und in "Prozeduren" hinterlegt werden:

![image](https://user-images.githubusercontent.com/22314271/55384226-71ef3400-552a-11e9-865c-4ea39aed2173.png)

![image](https://user-images.githubusercontent.com/22314271/55384250-86cbc780-552a-11e9-9833-bc2f955d3145.png)

**Comment by chrbusch** [comment]
Generell habe ich die Serverscripts bislang nur von 8h-22h laufen lassen; nun rennen sie rund um die Uhr

**Comment by chrbusch** [comment]
Bitte prüfen: Wird die WV korrekt erstellt, ggfs. mit Hinweis auf die zu entnehmenden Blutproben?
Kommt der Hausarzt in die Bemerkungen, wird "Blutprobe noch möglich" gesetzt?

**Comment by Toelk-A** [comment]
Neuruppin funktioniert soweit sehr gut. Einzige Anmerkung ist noch, wenn in den Diagnosen ein "Diabetes" automatisch in Ornella übernommen wird, dann soll automatisch gleich der Haken bei "ja" gesetzt werden

z.B.:
![image](https://user-images.githubusercontent.com/22314271/55873577-4d313700-5b90-11e9-91a5-cc42acd58f27.png)
.

**Comment by chrbusch** [comment]
Diabetes erl.
