### ISSUE TITLE
GBMV/ Bugfix neuer Entnahmebericht -> geschätzte Ankunftszeit

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#485]
Die geschätzte Ankunftszeit im Bankavis wird noch nicht berechnet

![image](https://user-images.githubusercontent.com/22314271/53151948-9f080880-35b4-11e9-81e7-e759222e91c2.png)

**Comment by chrbusch** [comment]
Try now…

**Comment by Toelk-A** [comment]
erledigt
