### ISSUE TITLE
Bugfix Abbildung entnommene Präparate in Spenderliste

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#486]
Es werden noch immer nicht alle entnommenen Präparate in der Spenderliste abgebildet

![image](https://user-images.githubusercontent.com/22314271/53163903-60337c00-35cf-11e9-8436-2cc8670fcd5f.png)

**Comment by chrbusch** [comment]
Ich denke, jetzt klappt es für alte und neue EntnBerichte

**Comment by Toelk-A** [comment]
Jetzt werden die Gewebe des neuen Entnahmeberichtes "doppelt abgebildet"

![image](https://user-images.githubusercontent.com/22314271/53491855-b2751100-3a97-11e9-9042-d0e4f3721b1d.png)

**Comment by chrbusch** [comment]
m.E. erledigt

**Comment by Toelk-A** [comment]
erledigt
