### ISSUE TITLE
BUGFIX - mobiles Entnahmeteam / alter Entnahmebericht

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#487]
Spender ID 7378

Alter Entnahmebericht -> mobiles Entnahmeteam übernimmt wieder keine Daten aus dem alten Entnahmebericht und ist leer

![image](https://user-images.githubusercontent.com/22314271/53169788-86ace380-35de-11e9-86ef-6724f199bd3a.png)

**Comment by chrbusch** [comment]
m.E. erledigt

**Comment by Toelk-A** [comment]
erledigt
