### ISSUE TITLE
BUGFIX - neuer Entnahmebericht Zusatzpositionen einscannen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#488]
Spender ID 7431

Zusatzpositonen können eingescannt werden, werden aber nicht im Entnahmebericht abgebildet

**Comment by Toelk-A** [comment]
Hallo Dr. Busch es könne seit Mittwoch keine Zusatzpositionen im Entnahmebericht eingescannt werden... siehe Mailverkehr. Bitte lösen Sie dringend das Probelm.. danke

**Comment by chrbusch** [comment]
Bitte jetzt erneut testen
