### ISSUE TITLE
Meldung - Softwareaktualisierung Filemaker

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#489]
Hallo Dr Busch,

was muss hier unsererseits unternommen werden?

![image](https://user-images.githubusercontent.com/22314271/53170913-94b03380-35e1-11e9-9075-2d2ceca9715a.png)

**Comment by chrbusch** [comment]
Ich würde das installieren, so wie jedes andere Update auch.
Es müssen dazu alle Filemaker-Datenbanken geschlossen sein.

**Comment by chrbusch** [comment]
Ich denke, dieses Ticket kann geschlossen werden
