### ISSUE TITLE
Einwilligungserklärung IV

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#49]
Abschnitt IV Gesprächsergebnis:

WENN "Eingeschränkte Zustimmung" angekreuzt, dann bitte ein Eingabefeld zur Definition der „eingeschränkten“ Gewebe

**Comment by chrbusch** [comment]
Ich vermute, Sie meinen "Freigabe Entnahme"?
Dort unten ist jetzt das Feld mit den zuvor gewählten Geweben platziert, und man kann Gewebe löschen oder eine Bem. eintragen

**Comment by Toelk-A** [comment]
Es geht um die Einwilligungserklärung Abschnitt IV Gesprächsergebnis. Unser Originaldokument besitzt ein Feld zum Einschreiben der "Eingeschränkten Gewebe"

![image](https://cloud.githubusercontent.com/assets/22314271/20171020/27ad1d22-a72f-11e6-81ec-c11e846f734b.png)

Genau dieses Eingabefeld benötigen wir auch in der Einwilligungserklärung in Ornella.

**Comment by chrbusch** [comment]
bitte testen, ob dies so in Ordnung :

![bildschirmfoto 2016-11-10 um 15 20 05](https://cloud.githubusercontent.com/assets/1241899/20180088/3c219b96-a759-11e6-93f4-b85fe7c3ae35.JPG)

**Comment by Toelk-A** [comment]
funktioniert super, für das Dropdown reichen "Entnahme erlaubt" und "Entnahme verweigert" aus

**Comment by chrbusch** [comment]
Bzgl. der Bezeichnungen lag hier der Fehler bei mir: Die Datenbank-TABELLE heißt zwar "EinwilligungsGespraech", aber der für Sie sichtbare Name ist "Einwilligungserklärung", sorry.
