### ISSUE TITLE
Buchhaltung - Rechnung storniert - keine Abbildung in Liste Fällige Rechnungen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#490]
Wenn eine Rechnung storniert wurde, so darf sie nicht in der Liste "fällige" bzw. "offene Rechnungen" abgebildet werden.

![image](https://user-images.githubusercontent.com/22314271/53225045-07b7b980-3677-11e9-8856-8468d30b3980.png)

**Comment by mprueter** [comment]
Dem ist schon so. Die betreffende Rechnung wurde nicht per Button storniert! Es wurde lediglich in den Bemerkungen notiert, dass sie storniert ist. 

![bildschirmfoto 2019-02-22 um 09 18 48](https://user-images.githubusercontent.com/3273572/53228914-05f3f300-3683-11e9-887b-1c3524a5fee4.png)

**Comment by Toelk-A** [comment]
Diese Rechnung habe ich persönlich storniert via Button "Storno" hierzu habe ich sogar eine Kopie auf der die Storno bestätigt ist. Wie damals schon telefonisch besprochen ändert sich der Status von "Storno" auf "Druck" nachdem die Stornorechnung gedruckt wird.... Aus diesem Grund sollte weiter oben immer "Storno" eingeblendet werden...

**Comment by mprueter** [comment]
Ich glaube das Problem ist inzwischen behoben. Ich habe die Porgrammierrung jetzt aber auch dahingehend geändert, dass beim Stornieren ein Flag in der rechnung gesetzt wird, sodass unabhängig davon, was im Statusfeld steht, die Rechnung als storniert erkannt wird:

![bildschirmfoto 2019-02-22 um 10 15 33](https://user-images.githubusercontent.com/3273572/53232195-e06ae780-368a-11e9-9742-032406ef0ffd.png)


...jetzt funktioniert es.

**Comment by Toelk-A** [comment]
ja das wurde schon programmiert. Bei der genannten Rechnung traf dies nur noch nicht zu.
