### ISSUE TITLE
BUGFIX - Neuer Entnahmebericht - Transplantatdetails - Eingangskontrolle - Transportdauer unvollständig

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#491]
Transplantatdetails ID 7449 

-> Button Eingangskontrolle (Button 134)
-> Transportdauer wird nicht mehr berechnet (Zugriff auf neuen Entnahmebericht -> Entnahmezeitpunkt...hieraus erfolgte die Berechnung der Transportdauer)

![image](https://user-images.githubusercontent.com/22314271/53227261-105fbe00-367e-11e9-8ab9-47da45dfbed9.png)

**Comment by chrbusch** [comment]
m.E. erledigt
