### ISSUE TITLE
BUGFIX neuer Entnahmebericht Seite 3 - keine Abfrage digitale Unterschrift

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#492]
Spender ID 7417

Entnahmbericht:
Digitale Unterschrift auf Seite 3 wird nicht abgefragt. Dr Manecke kann seinen Namen anklicken, jedoch erscheint nicht das Fenster zur Abfrage des Passwortes um die digitale Unterschrift zu setzen. 

![image](https://user-images.githubusercontent.com/22314271/53329752-0db6d000-38ed-11e9-9ed0-939004a9b3ce.png)

**Comment by chrbusch** [comment]
Jetzt besser…?

**Comment by Toelk-A** [comment]
erledigt
