### ISSUE TITLE
BUGFIX - Transplantaliste Button 30,31,32,33 unvollständige Auflistung TX

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#493]
Gibt man die Suchangaben wie gezeigt an und wählt den Button "30,31,32,33" wird nur Freigabestatus angezeigt. "In Herstellung und der Rest fehlt:

![image](https://user-images.githubusercontent.com/22314271/53394017-35b23c00-399e-11e9-8b68-fb33c44c63d7.png)

Klickt man nur den Status 31 "In Herstellung" an so werden keine Transplantate gefunden, obwohl es difinitiv Transplantate mit dem Status "In Herstellung" gibt

![image](https://user-images.githubusercontent.com/22314271/53394125-875ac680-399e-11e9-90da-0c18baee0167.png)

**Comment by chrbusch** [comment]
Bitte ein konkretes Beispiel nennen: Welches Transplantat sollte Ihrer Meinung nach erscheinen?

**Comment by Toelk-A** [comment]
Das Ticket ist an Herrn Prüter adressiert, da er mit der TX Liste gearbeitet hat.
Es sollten alle Transplantate erscheinen die den Status In Herstellung bzw. die weiteren o.g. Status besitzen:

![image](https://user-images.githubusercontent.com/22314271/53395069-37313380-39a1-11e9-9444-fb5194fa83b6.png)

**Comment by chrbusch** [comment]
Es sind ja mehrere Suchkriterien aktiviert.
Bitte ein KONKRETES Beispiel nennen: Welches Transplantat fehlt auf der Liste?

**Comment by chrbusch** [comment]
Nach Umbau auf die neue Tabelle SpdEntnahme (und temporär paralleler Suche in der alten Tabelle) findet das System nun 20 Transplantat. mit den oben ang. Suchkriterien

**Comment by Toelk-A** [comment]
Grund für die fehlenden Transplantatstatus war das Erstellen des neuen Entnahmeberichtes. Die Transplantatliste suchte nach der gewebeprozessierenden Einrichtung.
