### ISSUE TITLE
BUGFIX Buchhaltung - Rechnung 

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#494]
Rechnungsnummer: 2019-1667 
-> Rechnung erstellt -> Rechnung storniert -> nach Storno sollte Rechnung erneut erstellt werden, Transplantate werden laut Ornella nicht mehr gefunden.

![image](https://user-images.githubusercontent.com/22314271/53416684-49789500-39d4-11e9-95de-692d1149a226.png)

![image](https://user-images.githubusercontent.com/22314271/53416746-64e3a000-39d4-11e9-8fa2-8a48a8e4fc68.png)

![image](https://user-images.githubusercontent.com/22314271/53416764-6f059e80-39d4-11e9-86ab-cf622d01fa3c.png)

**Comment by mprueter** [comment]
Das Problem ist jetzt behoben. In Zukunft sloote bei der Stornierung auch der Bezug zu den betreffenden Trnasplantaten/Präparaten aufgehben werden. Entsprechend ist dann eine erneute Rechnungsstellung möglich.

**Comment by Toelk-A** [comment]
erledigt
