### ISSUE TITLE
BUGFIX Spenderakte drucken - Spenderakte unvollständig

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#495]
ID 7417

Die Spenderakte wird nicht vollständig erstellt. (Button: „Spenderakte drucken“ Button 96).

Die Entnahmebericht OG sowie auch der Transportbegleitschein fehlen. (siehe Anlage)

[Spenderakte_7417_190227105920.pdf](https://github.com/chrbusch/GTM-V/files/2909641/Spenderakte_7417_190227105920.pdf)

**Comment by chrbusch** [comment]
Dies habe ich an die neue Tabelle SpdEntnahme angepasst, bitte selbst auch noch einmal testen.
(Wie auch die vorigen Aufgaben in diesem Bereich ist das aus meiner Sicht kein Bugfix, sondern die Fortsetzung der Verallgemeinerung unseres Datenmodells.)

**Comment by chrbusch** [comment]
Habe noch einen Fehler gefunden, mit dem testen bitte noch warten

**Comment by chrbusch** [comment]
Der Header stimm noch nicht beim neuen EntnBericht, das prüfe ich jetzt

**Comment by Toelk-A** [comment]
Erledigt
