### ISSUE TITLE
Buchhaltung - Status Storno 2019-1662

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#498]
Die Rechnung 2019-1662 wurde storniert, taucht aber noch immer in der Liste "zu bezahlende GBMV Rng. auf"

![image](https://user-images.githubusercontent.com/22314271/53553946-07b82d80-3b3f-11e9-97cf-81dce8fc1166.png)

Können Sie bitte prüfen ob das digitale "StornoFähnchen" auch wirklich an dieser Rechnung vorhanden ist?
![image](https://user-images.githubusercontent.com/22314271/53554143-69789780-3b3f-11e9-99ee-e4cefc929f1e.png)

VG und danke

**Comment by mprueter** [comment]
Das war noch ein falscher, mittlerweile überholter Scriptschritt im Suchscript. Das ist jetzt behoben. Die Rechnung erscheint nichtmehr...

**Comment by Toelk-A** [comment]
danke
