### ISSUE TITLE
Adressenmodell, hierarchisch

### ISSUE THREAD

**Issue by chrbusch** [chrbusch/GTM-V#5]
Wir brauchen hierarchisch organisierte Adressen der Art
Krankenhaus <Kliniken < Abteilungen

Gibt es darüber hinaus Besonderheiten zu den Adressen zu erwähnen?
Zur Zeit habe ich diese Adressentypen vorgesehen:
Krankenhaus
Klinik
Abteilung
Hausarzt
Transplanteur
Transporteur
Behörde
Dienstleister
Interne Adresse
Labor
Sonstige

Gibt es weitere wichtige Typen?

**Comment by Nitschke-FP** [comment]
Die Hierarchie der Adressdaten für die Krankenhäuser ist wie folgt:
Krankenhaus<Klinik<Abteilung<Station - man kann hier auch verallgemeinern jur. Person1<jur. Person2<jur. Person3<jur. Person4, da nicht nur Krankenhäuser im Prozess eine Rolle spielen (z.B. Behörde oder Transporteur).
Einige Einrichtungen haben in dieser Hierarchie von 1-4 eine Unterstruktur nicht besetzt (z.B. Krankenhaus A hat keine Klinik sondern nur Abteilungen und Stationen, Krankenhaus B hat keine Abteilungen sondern nur Kliniken und als nächste Untereinheit Stationen.
Alle jur. Personen haben in dem Prozess eine Rolle bzw. mehrfache Rollen. So kann eine Einrichtung Spendeeinrichtung sein (meldet uns Spender), Entnahmeeinrichtung sein (hat einen Raum, wo wir die Entnahmen durchführen können) und auch eine transplantierende Einrichtung sein, wo wir Transplantate hinschicken oder ein Labor wo wir Aufträge einsenden und Befunde zurückbekommen. Die Einrichtungen haben dann auch noch administrative Bereiche, wo wir Rechnungen hinschicken, um die Nutzung der Räumlichkeiten zu bezahlen bzw. eine Rechnung stellen für ein geliefertes Transplantat.
Natürliche Personen haben analog zu den jur. Personen Rollen. z.B. meldender Arzt eines Spenders, Transplantationsbeauftragter eines Klinikums, Ärztlicher Direktor bzw. Vorstand, Transplanteur etc. denen wir berichtspflichtig sind bzw. denen wir Angebote für Transplantate zuschicken.

**Comment by chrbusch** [comment]
Es ist nun ein komplett allgemeines Adressenmodell realisiert, das eine beliebig tiefe Verschachtelung in Subadressen erlaubt.

**Comment by chrbusch** [comment]
Frage zur Benennung: Wir brauchen einen Begriff für die "Oberadresse der nächsten Ebene", zB die Abeilung, zu der eine Station gehört.
Und einen begriff für die alleroberste Ebene, s.d. zB bei "IN3" die Klinik Rostock Süd gemeint ist.
Meine Vorschläge: "Top-Adresse" ist die alleroberste, "Ober-Adresse" meint eine Stufe höher.
Einverstanden?
