### ISSUE TITLE
V2 / Einwilligungserklärung 

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#50]
Abschnitt V "Freigabe Staatsanwaltschaft"

Wenn Todesursache „natürlich“ angekreuzt, dann entfällt der restliche Teil „Freigabe Staatsanwaltschaft“: Freigabe Entnahme, Auflagen, Staatsanwaltschaft, Staatsanwalt, Datum, Uhrzeit  – ist feintuning

**Comment by chrbusch** [comment]
Ist jetzt umgesetzt, weil es so simpel zu machen ist
