### ISSUE TITLE
BIGFIX neuer Entnahmebericht MSG

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#500]
Spender ID 7568

MSG Entnahmebericht zieht sich nicht die MSG Standardsets (jung und alt)

![image](https://user-images.githubusercontent.com/22314271/53716734-24fa3e00-3e56-11e9-9548-f5013ed02bf1.png)

Bitte dringend Programmierung prüfen und Fehler beheben

**Comment by chrbusch** [comment]
Bitte jetzt testen

**Comment by Toelk-A** [comment]
erledigt
