### ISSUE TITLE
BUGFIX neuer Entnahmebericht - AGE Rechnungen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#501]
Ich wollte heute die AGE Auflistungen erstellen dun erhalte beim Prüflauf die folgenden "problematischen Entnahmen"
[SpdGewebe_Probleme_190304085104_AGE.pdf](https://github.com/chrbusch/GTM-V/files/2924785/SpdGewebe_Probleme_190304085104_AGE.pdf)

Bei Kontrolle der jeweiligen Spende sind die Entnahmeräume im System hinterlegt. Ich denke die problematischen Fälle ergeben sich durch die Erstellen des "neuen Entnahmeberichtes" Bitte dringend Programmierung prüfen. Die Auflistungen sollen heute versandt werden.
Danke

**Comment by chrbusch** [comment]
Welcher Button ist das, wo haben Sie ihn geklickt?

**Comment by Toelk-A** [comment]
Da Herr Prüter damals die Programmierung übernommen hatte wäre es sicherlich gut, wenn er einfach nur einen Hinweis von Ihnen , Herr Dr. Busch, hinsichtlich des neuen Entnahmeberichtes bekommt.

![image](https://user-images.githubusercontent.com/22314271/53719425-4b23dc00-3e5e-11e9-817b-f651208c2358.png)
