### ISSUE TITLE
BUGFIX - neuer Entnahmebericht MSG - Eingabefeld Kühlung der Präparate

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#502]
Spender ID 7568

Es fehlt ebenfalls das Fenster "Kühlung der Präparate

![image](https://user-images.githubusercontent.com/22314271/53720505-3ac13080-3e61-11e9-9fc3-3582c85cde40.png)

![image](https://user-images.githubusercontent.com/22314271/53720602-6f34ec80-3e61-11e9-9dfc-42d5b5ffba6c.png)

-> Können Sie bitte gleich parallel prüfen ob der neue Entnahmebericht KVG auch dem alten Entnahmebericht KVG entspricht? Danke

**Comment by chrbusch** [comment]
Zeitpunkt... ist jetzt sichtbar

**Comment by chrbusch** [comment]
Wg. KVG bitte anrufen

**Comment by Toelk-A** [comment]
bitte rufen Sie mich zu KVG zurück

**Comment by chrbusch** [comment]
Können Sie bitte beschreiben, was es bei KVG noch für Probleme gibt?

**Comment by Toelk-A** [comment]
Es gibt keine Probleme, es sollte nur darauf geachtet werden, dass der KVG Entnahmebericht neu dem Ausbau des KVG Entnahmeberichtes alt entspricht.
