### ISSUE TITLE
BUGFIX Transplantatliste

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#503]
allokation- Transplantatliste

Bank= GMV
Klassifikation = 1
Status 30...33

![image](https://user-images.githubusercontent.com/22314271/53797882-64e52200-3f37-11e9-80df-549e5434c0f7.png)

Bitte prüfen und behben

**Comment by chrbusch** [comment]
Bitte erneut testen

**Comment by Toelk-A** [comment]
erledigt
