### ISSUE TITLE
BUGFIX Mobiles Entnahmeteam - verzerrte Empfängeradresse

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#504]
Spender ID: 7570

mobiles Entnahmeteam -> auch im PDF verzerrt abgebildet

![image](https://user-images.githubusercontent.com/22314271/53805441-72f06e00-3f4a-11e9-9c38-3bfd35d9334a.png)

**Comment by chrbusch** [comment]
m.E. erledigt

![image](https://user-images.githubusercontent.com/1241899/53807832-ebf2c400-3f50-11e9-967d-8cb9d3295c44.jpeg)

**Comment by Toelk-A** [comment]
erledigt
