### ISSUE TITLE
BUGFIX MSG Entnahmebericht - gelöschte Präparate noch vorhanden

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#505]
Spender ID 7585

Gestern wurde die MSG Entnahme begonnen und bei hochgradigem Verdacht auf Tumorgeschehen abgebrochen.

Aus diesem Grund wurden die Original angelegten Präparate im Reiter Gewebe/Präparate/Transplantate gelöscht.

![image](https://user-images.githubusercontent.com/22314271/53936939-d6de7800-40ab-11e9-82bc-bc55e8ffa550.png)

Im MSG Entnahmebericht wurden diese allerdings nicht gelöscht sondern folgendermaßen verändert abgebildet:

![image](https://user-images.githubusercontent.com/22314271/53936912-c1694e00-40ab-11e9-8d98-9ac652b31ceb.png)

Bitte prüfen und beheben,
Danke

**Comment by chrbusch** [comment]
Wie tel. Besprochen: Im Programm erl. + für SPD 7585 manuell nachgetragen

**Comment by Toelk-A** [comment]
erledigt
