### ISSUE TITLE
Bugfix Mobiles Entnahmeteam

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#506]
Eignung des Raumes für Entnahme:

Hier wird nicht mehr automatisch der Punkt bei "ja oder nein" gesetzt

![image](https://user-images.githubusercontent.com/22314271/54285378-1f150300-45a2-11e9-941a-7271f47af734.png)

Der Bezug hierzu ist die Adressen ID des Entnahmeraumes:

![image](https://user-images.githubusercontent.com/22314271/54285455-479cfd00-45a2-11e9-80d5-947ff6002476.png)

Bitte Verknüpfung wieder programmieren.
Danke

**Comment by chrbusch** [comment]
Erl.
