### ISSUE TITLE
Buchhaltung - MSG Abrechnungen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#507]
![image](https://user-images.githubusercontent.com/22314271/54925089-e6641a80-4f0d-11e9-82ee-4ea093f653c7.png)

![image](https://user-images.githubusercontent.com/22314271/54925202-1dd2c700-4f0e-11e9-9224-325b8ee1f358.png)

Bitte hier nur MSG Spenden anzeigen, die bereits freigegeben (Gewebe versandt + Status Freigabe "Freigabe MSG" MSG) sind:

![image](https://user-images.githubusercontent.com/22314271/54925322-596d9100-4f0e-11e9-91ef-35b3167f5915.png)

**Comment by mprueter** [comment]
...das ist jetzt so umgesetzt. Bitte ggf. testen.

**Comment by Toelk-A** [comment]
erledigt, danke
