### ISSUE TITLE
GBMV/ Präparateliste bitte kein MSG anzeigen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#508]
In der Präparateliste werden derzeit alle Präparate zu den Geweben OG, MSG und KVG angezeigt. Da wir alle MSG Präparate grundsätzlich nicht in die GBMV senden, können diese bitte ausgeblendet werden.

Alle Präparate zu OG und KVG müssen nach wie vor in der Präparateliste abgebildet werden.

![image](https://user-images.githubusercontent.com/22314271/54976868-f0ccf580-4f9b-11e9-95ca-8b6b2b0a09aa.png)

![image](https://user-images.githubusercontent.com/22314271/54976906-0b9f6a00-4f9c-11e9-97ad-8079b89e5424.png)

**Comment by chrbusch** [comment]
Erl.
