### ISSUE TITLE
Einwilligungserklärung VI

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#51]
Beratender Koordinator im Angehörigengespräch, muss nicht gleich verantwortlicher Koordinator der Spendermeldung sein (bitte KEINE Änderung des Koordinators in der Spendermeldung)

TOA hat Spendermeldung angelegt, "beratender Koordinator im Einwilligungsgespräch ist Dietrich Schweder:

191016-0954-GNO-TOA
![image](https://cloud.githubusercontent.com/assets/22314271/20100421/be5ccc68-a5bd-11e6-844d-22e97745d086.png)

und nun ändert sich der Koordinator auch in der Spendermeldung (anstatt TOA nun SCD)

![image](https://cloud.githubusercontent.com/assets/22314271/20100371/898f1356-a5bd-11e6-8fcf-9b40868599f8.png)

bitte KEINE Änderung des Koordinators in der Spendermeldung

**Comment by chrbusch** [comment]
Nun gibt es ein von der SpdMldg unabhg. Feld f.d. beratenden Koordinator

**Comment by Toelk-A** [comment]
funktioniert
