### ISSUE TITLE
Spenderdetails - Neues Anklickfeld "Diabetes"

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#510]
### 1) Anklickfeld Diabetes

Wir benötigen in den Spenderdetails ein neues Anklickfeld "Diabetes "ja" / "nein" - Bitte zum Kasten "Diagnosen" hinzufügen

![image](https://user-images.githubusercontent.com/22314271/55150505-87d8af80-514c-11e9-8203-22a606da97ca.png)

### 2) Warnung in Kopfzeile / Wiedervorlage 
Wenn Feld nicht ausgefüllt bitte, bitte Warnung in Kopfzeile "Liegt ein Diabetes bei dem Spender vor"?

Falls nach 3 Tagen noch immer nicht ausgefüllt, bitte Wiedervorlage an VP UND Koordinator.

### 3) wenn "nein" angeklickt

Bitte Abbildung in der Transplantat-Auswahl + Allokation im roten Rahmen "kein Diabetes abbilden"

![image](https://user-images.githubusercontent.com/22314271/55150950-82c83000-514d-11e9-9d7d-a7db32017f65.png)

4) wenn "ja"

Bitte Abbildung in der Transplantat-Auswahl + Allokation im roten Rahmen "Diabetes abbilden"
-> dies ist bereits programmiert

Außerdem, ein weiteres Fenster öffnen (wie bei Button "neue Diagnose") damit der Koordinator gleich nach Diabetes / ICD-Code suchen kann und dieser hinterlegt wird.

![image](https://user-images.githubusercontent.com/22314271/55151192-f407e300-514d-11e9-8654-122634e322e1.png)

**Comment by chrbusch** [comment]
Bitte jetzt mal alles testen.

**Comment by Toelk-A** [comment]
ist es möglich den "Nein" nicht gelb zu hinterlegen.? Das wäre übersichtlicher für mich

![image](https://user-images.githubusercontent.com/22314271/55214350-c034c800-51f6-11e9-83b1-75b986ec5bf2.png)

**Comment by chrbusch** [comment]
Erl.
