### ISSUE TITLE
Textbaustein Abrechnung "GTMV an die Bank"

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#511]
Wo finde ich den Textbaustein zu "Abrechnung GTMV an die GBMV"?

![image](https://user-images.githubusercontent.com/22314271/55703620-655f5580-59da-11e9-83c0-c59de6722f41.png)

![image](https://user-images.githubusercontent.com/22314271/55704215-e539ef80-59db-11e9-91d3-52a813716328.png)

**Comment by chrbusch** [comment]
Bin nicht sicher, ob es dafür einen Textbaustein gibt.
Welchen Button klicken Sie, um diese Rng zu erstellen?

**Comment by chrbusch** [comment]
Die Texte waren bisher ohne Textbaustein fest im Script; ich habe dies nun umgebaut und Sie finden die Textbausteine mit den IDs 24 + 25 hierfür

![image](https://user-images.githubusercontent.com/1241899/56016059-630f3b00-5cfb-11e9-98eb-6926594cf60c.jpeg)
