### ISSUE TITLE
Chatfunktion Ornella gg. GTMVGo-App

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#512]
USer wird nicht abgebildet. Dies funktionierte bereits.

![image](https://user-images.githubusercontent.com/22314271/55873315-9d5bc980-5b8f-11e9-81b5-1cc973c7e894.png)

**Comment by chrbusch** [comment]
Das betraf das Handy von NiF, sollte bei jetzt neu erstellten Chats klappen
