### ISSUE TITLE
Spendermeldungen aus csv Datei - Adr 110 (KH Westm. H. v. Bülow)

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#513]
Hallo Dr. Busch,

da Neuruppin jetzt funktioniert kann mit der nächsten meldenden Einrichtung und dem automatischen Einlesen der Spendermeldungen begonnen werden.
![image](https://user-images.githubusercontent.com/22314271/55932397-c7fa6080-5c29-11e9-9a06-8c52e44c6497.png)

 

Es befinden sich 2 Standorte unter der Adresse 110 Ludwigslust und Hagenow. Die Stationen werden über den Code „1“ oder „2“ voneinander unterschieden.

![image](https://user-images.githubusercontent.com/22314271/55932436-f4ae7800-5c29-11e9-8b44-1409c39bd28c.png)

Der Aufbau der Excel(csv bzw. FTP) sieht etwas anders aus:

![image](https://user-images.githubusercontent.com/22314271/55932598-a188f500-5c2a-11e9-9685-39403ca16f54.png)

 

Bei Rückfragen rufen Sie mich morgen bitte ab 07:30Uhr an.

Ansprechpartner für die FTP-Dateien sind die folgenden:

Mit freundlichen Grüßen
 
Volker Brunck
 
Systembetreuer
 
Westmecklenburg Klinikum Helene von Bülow GmbH
Krankenhaus Ludwigslust
19288 Ludwigslust
Tel:    03874 433568
Fax:    03874 665574
E-Mail: volker.brunck@wmk-hvb.de

VG Anita Tölk

**Comment by chrbusch** [comment]
Wie erkennen wir hier die Stationen?
Das Bild zeigt die zZ bei den Subadressen von 110 vorhandenen Kurznamen.
Das "2G" aus der Beispieldatei kommt hier nicht vor.

![image](https://user-images.githubusercontent.com/1241899/55941052-b0c76d00-5c41-11e9-937d-d146143c9189.jpeg)

**Comment by Toelk-A** [comment]
Siehe rote Markierung

![image](https://user-images.githubusercontent.com/22314271/55941241-22072000-5c42-11e9-91c7-4994eddbc269.png)

Falls notwendig kann ich auch alles Kürzel ändern also falls das Kürzel XXX"HGN" bzw XXX"LWL" stören...

**Comment by chrbusch** [comment]
Ja, das habe ich gesehen; aber die Station heisst eben nicht "2G", und "HGN" steht mal vorne und mal hinten. Können Sie eine klare Regel für die Zuordnung nenne, oder sollten wir nicht besser das Feld "Bezng_Kz_CSV" entspr. füllen mit genau den Kürzeln, die in den Dateien kommen?

**Comment by Toelk-A** [comment]
Ich habe alle Stationen wie eben telefonisch vereinbart angepasst. 

Nach den "Abteilungen" brauch nicht gesucht werden, sondern nur nach dem Kürzel "2+Station+HGN" bzw "1+Station+LWL".

Ich kontaktiere jetzt Stephan Peter hinsichtlich der Weiterleitung.

**Comment by chrbusch** [comment]
Die Stationen sehen jetzt gut aus!
Und die Extraktion der Daten aus den neuen CSV-Dateien funktioniert nun schon, zumindest für das eine mir vorliegende Beispiel. Die Werte stimmen überein mit dem zuvor manuell angelegten Spender mit ID=7942
Es muss besprochen werden, wie mit den OPS-Codes umgegangen werden; mein Vorschlag: Die existierende Tabelle "SpdMassnahmen" reaktivieren und anzeigen so wie bislang schon die Dgn

**Comment by chrbusch** [comment]
Techn. Anm.: Die Extraktion erfolgt im neuen Script
"    \_OP5_110.Import SpdMldg HeVBülow (SP=pk_DataFile¶FileName¶r2¶r3¶content)"

**Comment by Toelk-A** [comment]
## zu den OPS-Codes:

Bitte Feld 1 wieder "aktivieren", sodass die Koordinatoren Bemerkungen wie "Antibiose... hinterlegen können"

Bitte Feld 2 "Prozeduren" für das automatische Einspeisen der OPS Codes nutzen

![image](https://user-images.githubusercontent.com/22314271/55946079-4a941780-5c4c-11e9-82c0-11f4f335b571.png)

**Comment by chrbusch** [comment]
1) Ist erledigt. Bitte mit darauf achten, dass nun nicht wieder alles in die Bem. geschrieben wird
2) ist erl. für beide Adressen

**Comment by Toelk-A** [comment]
Die Weiterleitung ist durch Stephan Peter eingerichtet. es befindet sich bereits eine csv aus Ludwdigslust in Ihrem Ordner zur weiteren Verarbeitung.

**Comment by chrbusch** [comment]
Heute wurden erstmalig erfolgreich ein Spender angelegt, allerdings nach einer Fehlerkorrektur und NACHDEM der Spender schon manuell angelegt wurde.

Bitte die Daten des TESTSpenders 7973 prüfen und vergleichen mit dem ECHTEN Spd. 7972:
Mit Ausnahme der von mir verfälschten FallNr, sieht das plausibel aus?

**Comment by chrbusch** [comment]
Bei TESTspendern erscheint nun der Header in etwas weniger hübschen Farben:

![image](https://user-images.githubusercontent.com/1241899/56089997-e5366580-5e9b-11e9-8dc5-5a42521d5852.jpeg)

**Comment by chrbusch** [comment]
Ich denke, dieses Ticket kann geschlossen werden

**Comment by Toelk-A** [comment]
Meines Erachtens werden OPS Codes nicht eingelesen/auch nicht für die Meldungen aus Neuruppin

**Comment by chrbusch** [comment]
Bitte ein konkretes Beispiel nennen, anhand dessen ich prüfen kann

**Comment by Toelk-A** [comment]
![image](https://user-images.githubusercontent.com/22314271/64175400-8332c880-ce5b-11e9-9686-db195b245f78.png)


![image](https://user-images.githubusercontent.com/22314271/64175434-90e84e00-ce5b-11e9-9123-67ebf465e3d6.png)

**Comment by chrbusch** [comment]
Eine TABELLE für OPS haben wir ja gar nicht; aber die Codes werden nun decodiert und als Klartext in das Feld "Prozeduren" unter den Diagnosen geschrieben.

**Comment by Toelk-A** [comment]
Codes werden eingelesen. Codeentschlüsselung funktioniert teilweise. Wie können wir dies vervollständigen?

![image](https://user-images.githubusercontent.com/22314271/64406812-0d10aa80-d083-11e9-8ef8-4b642579326c.png)

**Comment by chrbusch** [comment]
Zur Zeit haben wir gut 12.000 OPS-Codes im System:
![image](https://user-images.githubusercontent.com/1241899/64407688-41856600-d085-11e9-9116-e0f18ed81a35.jpeg)

**Comment by chrbusch** [comment]
Am besten wäre es, wenn Sie mir eine (eventuell käuflich zu erwerbende) Datei senden, die den aktuellen Stand des OPS enthält; diese kann ich dann in Ornella importieren.
Alternativ kann ich unerkannte Codes sammeln und einem Supervisor zur Ergänzung anbieten; es würde dann etwa im obigen Beispiel eine Meldung zu den nicht bekannten Codes
8-930 , 8-831.0 und  8-931.0
geben
Einmal eingetippt, würde ich diese Codes in die Stammtabelle schreiben. Eine importierbare Datei wäre aber viel besser!
