### ISSUE TITLE
BUGFIX Spenderdetails Button archivieren funktioniert nicht

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#514]
Filemaker wurde bereits neugestartet
Button "Archivieren an/aus" funktioniert nicht
Spender:

![image](https://user-images.githubusercontent.com/22314271/55938915-c38b7300-5c3c-11e9-945a-3cc81a2121db.png)

**Comment by chrbusch** [comment]
...aber der Spender ist doch archiviert?
![image](https://user-images.githubusercontent.com/1241899/55939391-e66a5700-5c3d-11e9-8b66-f41a9ba6d496.jpeg)

**Comment by Toelk-A** [comment]
In meinem Screenshot können Sie sehen, dass es nciht funktioniert hat...

**Comment by Toelk-A** [comment]
okay, es hat funktioniert danke
