### ISSUE TITLE
BUGFIX Freigabe Archivierung Spenderakte - Gewebe unvollständig abgebildet

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#515]
Alle OG-Spender betroffen

![image](https://user-images.githubusercontent.com/22314271/56357448-171d3400-61dc-11e9-9a34-773abbb8fa7f.png)

esfehlen MSG kVG und Haut inklusive ja nein

**Comment by chrbusch** [comment]
Ist m.E: erledigt

![image](https://user-images.githubusercontent.com/1241899/56565058-ccbaff00-65af-11e9-9f5a-7cdcfa4deb33.jpeg)
