### ISSUE TITLE
Checklisten "Entnahme" und "Aktenrecherche"

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#516]
Wie eben schon telefonisch vereinbart soll folgendes programmiert werden:

### 1) Button "Checkliste" programmieren
Bitte den Button Checkliste im linken Menü auf den Spenderdetails programmieren
![image](https://user-images.githubusercontent.com/22314271/56567820-03941380-65b6-11e9-97c0-87a05188c568.png)

### 2) Mehrfachauswahl Button Checkliste
Nach Klick des Buttons soll es Auswahl geben 
"Entnahme" bzw.
"Aktenrecherche"

### 3) Checkliste "Entnahme" erstellen

Überschrift lautet "Entnahme"
PDF Kopf ähnlich der Spendermeldung (Button Spendermeldung drucken)
![image](https://user-images.githubusercontent.com/22314271/56568084-946aef00-65b6-11e9-9d59-eb5222507622.png)

Folgende Checkliste soll mit Ankreuzfeldern hinzugefügt werden:

A) Entnahmeort: Bitte aus Entnahmebericht OG übernehmen bzw. Eingabefeld
![image](https://user-images.githubusercontent.com/22314271/56568429-42769900-65b7-11e9-9618-9e0a0a587a22.png)

B) Ankreuzfeld "Aktenrecherche"

C) Hausarzt

D) Ankreuzfeld ja/nein "Obduktion"

E) Hierzu Besonderheiten zu Diagnosen (muss auf bestimmte Diagnosen geachtet werden?)

F) Körpergewicht: bitte Eingabefeld

G) "Transfusionen /Infusionen" - Eingabefeld

H) Ankreuzfeld  ja/nein "Blut im Labor" -> kann, wenn dokumentiert, aus Spenderdetails übernommen werden

![image](https://user-images.githubusercontent.com/22314271/56568613-ac8f3e00-65b7-11e9-8563-d78eb2270bd1.png)
 
I) Ankreuzfeld  ja/nein "Postmortale Blutentnahme"

J) "Temperaturlogger" -> Eingabefeld für Nummer des Loggers

K) "Besonderheiten körperliche Untersuchung (Narben, usw…)" -> Eingabefeld Text

L) Ankreuzfeld "Besonderheiten Entnahme (Arc. Sen.; Bulbi eingefallen)" -> Eingabefeld, bitte in OG Entnahmebericht übernehmen

![image](https://user-images.githubusercontent.com/22314271/56570435-3e4c7a80-65bb-11e9-883d-70d89c1036bb.png)

M) Ankreuzfeld "Besonderheiten Nachsorge (Blutung gestillt; Kopfverband)": Eingabefeld

N) Ankreuzfeld  "Weitere besondere Vorkommnisse (z.B. Bestatter oder Klinikpersonal unkommunikativ; Verstorbener nicht in Kühlung…..):" Eingabefeld

O) "Lagerung (Platznummer) Blut in GTM-V": Eingabefeld 

P) Datum + digitale Unterschrift des Studenten
 
### 4) Checkliste "Aktenrecherche" erstellen

Überschrift lautet "Aktenrecherche"

PDF Kopf ähnlich der Spendermeldung (Button Spendermeldung drucken)
![image](https://user-images.githubusercontent.com/22314271/56568084-946aef00-65b6-11e9-9d59-eb5222507622.png)

A) Ankreuzfeld "Diagnosen"

B) Ankreuzfeld "Hausarzt"

C) Ankreuzfeld "Angehörigendaten"

D) Ankreuzfeld "Natürlicher Tod/nichtnatürlicher Tod"

E) Ankreuzfeld "Postmortale Blutentnahme"

F) Ankreuzfeld "Mikrobiologische Befunde"

G) "Sonstiges" (Eingabefeld)

H) "Diensthabender Koordinator" Eingabefeld

I) "Diensthabender Arzt" Eingabefeld

**Comment by chrbusch** [comment]
Das Grundgerüst steht schon, Sie können den neuen Button ausprobieren. An die Darstellung gehe ich spätestens morgen Vormittag, dies dann in enger Abstimmung mit Ihnen.

**Comment by chrbusch** [comment]
Es gibt nun, je nach Art des zu erwartenden Eintrags, Ankreuz- oder Eingabefelder auf der neuen Maske, auf der die Liste bearbeitet werden kann.
Wir können testen mit dem unechten Spender 8012.

![image](https://user-images.githubusercontent.com/1241899/56642104-073b9f00-6677-11e9-9add-59bf0acf5f03.jpeg)

**Comment by chrbusch** [comment]
Noch zu besprechen:
Format des Ausdrucks?
Signum: Pro Eintrag oder für die ganze Checkliste?
usw.

**Comment by Toelk-A** [comment]
### Format des Ausdrucks?
Wie der Format der Spendermeldung

### Signum: Pro Eintrag oder für die ganze Checkliste?
1x unten auf der Checkliste

**Comment by chrbusch** [comment]
Darf man eine Checkliste drucken, bei der noch Felder unbeantwortet sind?

**Comment by chrbusch** [comment]
Bitte für einige Spender die Checklisten mit realistischen Daten füllen, damit wir Spielmaterial zum Drucken haben.
Ich gehe jetzt an die Übertragung von Daten zwischen Checklisten und anderen Dokumenten, wie etwa den Entnahmeort

**Comment by Toelk-A** [comment]
![image](https://user-images.githubusercontent.com/22314271/56719211-9660b980-6740-11e9-8e44-4a2ab92a8415.png)
 würde ich gern als Spender nutzen...
Entnahmeort ist noch nicht abgebildet
Datum fehlt, zum Signum sollte digitale Unterschrift hinterlegt werden

**Comment by Toelk-A** [comment]
Bitte wie oben beschrieben programmieren.
Zusätzlich Bemerkungsfeld als "logfeld programmieren (Kürzel + Datum)
![image](https://user-images.githubusercontent.com/22314271/56727169-6d482500-6750-11e9-9f1a-e5dc03bdbb46.png)

Sowie Entnahmeort und Hausarzt über Adressbutton einspeisen

**Comment by chrbusch** [comment]
Ich baue jetzt weiter am Datenaustausch zwischen "Hauptmodulen" wie EntnBericht und "CL" (Checklisten).
Bitte zügig antworten:
A) Funktioniert das, was schon da ist, wie gewünscht?
B) Werden die CL korrekt erstellt, haben sie die richtige Auswahl an Ja/Nein   ODER  Eingabefeld?
C) Sind Einträge noch da, wenn Sie erneut für denselben Spender eine CL öffnen?
D) Darf man eine unvollständig ausgefüllte CL drucken?
E) Sollen beide Listen gemeinsam gedruckt werden oder brauchen Sie eine Auswahl in der Art wie bei deren Erstellung: "Entn/AktenR/beide?

**Comment by chrbusch** [comment]
Frage zu "Blut im Labor": Ich würde dies auf "JA" setzen, wenn 
"Blut prämortal = Ja" ODER 
"Blut postmortal = Vorhd" - richtig?

**Comment by chrbusch** [comment]
G) Sehe ich richtig, dass bislang der Hausarzt gar nicht systematisch erfasst wird, sondern in ein Bem.-Feld geschrieben wird?
Das sollten wir m.E. ändern und einen sauberen Verweis in unsere Adressentabelle realisieren.

**Comment by chrbusch** [comment]
Die oben beschrieben Datenübernahme sind jetzt fertig für Entnahmeraum, Körpergewicht und "Blut im Labor".
Bitte testen.
Wenn eine nicht-komplette Checkliste gedruckt werden darf: Sollen dabei die unbeantworteten Fragen mit gedruckt werden?

**Comment by chrbusch** [comment]
Ist es immer so, dass die Checkliste Entnahme NACH dem Entn.Bericht ausgefüllt wird?

**Comment by chrbusch** [comment]
Bitte jetzt bei Spd 8075 die Druckfunktion mit Strg-5 testen.
Signum etc kann ich erst bearbeiten, wenn ich spät abends alleine im System bin.
Bitte auch prüfen, ob eine Hausarzt-AdressenID, die nach dem NEUEN Verfahren bei der MedIndPrüfung eingegeben wird, in die CL Entnahme übernommen wird.

**Comment by chrbusch** [comment]
Signum ist nun m.E. auch fertig.
Bitte Ausdruck testen und auf Unterschrift achten.
Offene Punkte:
A) Transfer der Daten **aus** er Checkliste **an** Spd, SpdEntnahme etc.
B) AuditLog

**Comment by chrbusch** [comment]
Sollen alle Einträge ins AuditLog, oder wie bei anderen Feldern nur nachträgliche Änderungen?

**Comment by chrbusch** [comment]
soweit ich erkenne werden die Checklisten noch nicht benutzt; woran liegt das?

**Comment by Toelk-A** [comment]
[Beispiel Checkliste Entnahme.pdf](https://github.com/chrbusch/GTM-V/files/3171403/Beispiel.Checkliste.Entnahme.pdf)

Soweit sieht die Checkliste Entnahme gut aus.

Esfehlt der "Kopf zur Spendermeldung" (leere Felder, Station + Patientendaten  fehlen....")

![image](https://user-images.githubusercontent.com/22314271/57600757-fcc84300-755a-11e9-991e-fc30fbe23ab0.png)

**Comment by chrbusch** [comment]
Erst einmal habe ich das "J." bei der FallNr entfernt :-))

**Comment by chrbusch** [comment]
Nun sind die Felder im Header platziert.

![image](https://user-images.githubusercontent.com/1241899/57629096-7d0e9880-759b-11e9-963b-6ddc5137abad.jpeg)

**Comment by Toelk-A** [comment]
Bitte rosa Markierungen bearbeiten

[Modifikation Checkliste Entnahme.pdf](https://github.com/chrbusch/GTM-V/files/3176451/Modifikation.Checkliste.Entnahme.pdf)

**Comment by chrbusch** [comment]
m.E. alles erledigt, bitte testen

**Comment by chrbusch** [comment]
Wie besprochen: Für dieses interne Dokument nun ein sparsamer header, so dass es in aller Regel nur eine Druckseite geben wird

![image](https://user-images.githubusercontent.com/1241899/57909306-bb99a100-7882-11e9-824e-6e8c16cdb72a.jpeg)

**Comment by Toelk-A** [comment]
Bitte nacharbeiten.

[Nacharbeiten Checkliste Entnahme.pdf](https://github.com/chrbusch/GTM-V/files/3197153/Nacharbeiten.Checkliste.Entnahme.pdf)

**Comment by chrbusch** [comment]
Der Name fehlte, weil ich verseh. das Objekt vom Druck ausgeschlossen hatte.
Eine kompakte Darstellung hatten wir ja vereinbart, damit es nur eine Druckseite gibt.
Bitte jetzt erneut ansehen

**Comment by Toelk-A** [comment]
Geburstdatum des Verstorbenen fehlt

**Comment by chrbusch** [comment]
Beides erl., bitte prüfen
