### ISSUE TITLE
Buchhaltung - Abbildung "Kundennnummer unter Rechnungsnummer" bei Transplantatabrechnungen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#517]
Für die " TransplantatAbrng " soll zukünftig die "Kundennummer" auf der Aufwandserstattung abgebildet werden:

![image](https://user-images.githubusercontent.com/22314271/56655793-0f560780-6694-11e9-8ffa-e005c6e685de.png)

![image](https://user-images.githubusercontent.com/22314271/56655905-5217df80-6694-11e9-8d9a-bd9ea080a6cf.png)

Entweder kann die Kundennnummer direkt bei der Adresse ODER auf der Rechnungsmaske hinterlegt werden.

**Comment by chrbusch** [comment]
Können wir  nicht als KdNr einfach unsere Adressen-ID nehmen? Dann wäre der Gesamtaufwand wenige Minuten…

**Comment by Toelk-A** [comment]
Nein können wir nicht, da wir diese Nummer zum Buchen der Rechnungen benötigen. Die "Kundennummern" bestehen also bereits in unserem Buchungssystem.

**Comment by chrbusch** [comment]
OK; bei Topadressen ist ein neues Feld sichtbar auf dem Reiter "Rngs-Wesen"; was dort hinein getippt wird erscheint (spätestens ab morgen früh) auf den Rechnungen.
Bitte tragen Sie einige Werte ein!

![image](https://user-images.githubusercontent.com/1241899/56668007-1b02f780-66af-11e9-8a64-c98097d9d403.jpeg)

**Comment by chrbusch** [comment]
Feld ist auf der Rng platziert, bitte testen

**Comment by Toelk-A** [comment]
Adressen ID 1276 (TOPADRESSE)
![image](https://user-images.githubusercontent.com/22314271/56720765-cc536d00-6743-11e9-83d1-3b359356ae03.png)

Kundennnummer dokumentiert


Feld ist auf Rechnung leider nicht vorhanden
![image](https://user-images.githubusercontent.com/22314271/56720533-5b13ba00-6743-11e9-855a-e2e44d7bfb14.png)


Generell besteht bei der Uni Klinik Köln das Problem, dass wir hier 2 Kundennummern benötigen. Ich würde vorschlagen, die Kundennummer "NICHT" auf der TOPadresse zu hinterlegen sondern direkt bei der Rechnungsadresse?

Bitte um Rückmeldung

![image](https://user-images.githubusercontent.com/22314271/56721233-bf834900-6744-11e9-9772-c47d0cdbc0a8.png)

**Comment by chrbusch** [comment]
Die KdNr ist nun bei ALLEN Adressen sichtbar; und sie wird auf der Rng gedruckt:

![image](https://user-images.githubusercontent.com/1241899/56723789-ef811b00-6749-11e9-8399-cedbc20fb9b7.jpeg)

**Comment by Toelk-A** [comment]
erledigt
