### ISSUE TITLE
Bugfix Freigabeprotokoll für OG Transplantate - stromaler Patch - Kreuz im PDF fehlt

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#518]
Transplantat ID 4125
"Freigabeprotokoll für OG Transplantat

Ornella generiert das gesetzte Kreuz bei „Nur für …., Stroma Patch“ auf dem PDF nicht. Im Protokoll ist es aber angekreuzt.

![image](https://user-images.githubusercontent.com/22314271/56942526-8d466280-6b1b-11e9-81a4-c149ed3656f0.png)

Warum sind die Abbildungen zwischen Ornella und PDF so unterschiedlich?

![image](https://user-images.githubusercontent.com/22314271/56942534-98998e00-6b1b-11e9-8248-21ac4af9275d.png)

**Comment by chrbusch** [comment]
Ein veraltetes Drucklayout f.d. Freigabeprotokoll, das ich hätte löschen sollen, war noch vorhanden und hat den ganzen Druckprozess gestört; das ist beides m.E. nun behoben. Kostenfreier Bugfix.

**Comment by chrbusch** [comment]
Ich denke, dieses Ticket kann geschlossen werden
