### ISSUE TITLE
Bugfix - FreigabeArchivierung Spenderakte "Mehrfachauswahl ja/nein" 

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#519]
Spender ID 7935

Da als Gewebe nur OG angegeben ist, 

![image](https://user-images.githubusercontent.com/22314271/57298460-92368380-70d2-11e9-8cb5-f9f4288c5552.png)

kann im Prozessschritt Freigabe Spenderakte auch nur hier das "OG" für Freigabe "ja / nein" angekreuzt werden. Bei allen anderen Geweben kommen Fehlermeldungen "Dieses Feld ist nicht veränderbar". Dies funktioniert früher anders. ich weiß nicht welche Programmierungen hier vorgenommen wurden, damit dies jetzt nicht mehr funktioniert....Es müssen aber alle anderen Gewebe auf "nein" setzbar sein. 

![image](https://user-images.githubusercontent.com/22314271/57298230-fefd4e00-70d1-11e9-9bc2-7c93aa4d5558.png)

Spender ID 7880

OG, MSG und KVG 
![image](https://user-images.githubusercontent.com/22314271/57298556-cca02080-70d2-11e9-8ea6-ee0abe1a1bef.png)

Auch heir müssen die gelb markierten mit "nein" ankreuzbar sein...
![image](https://user-images.githubusercontent.com/22314271/57298622-ee010c80-70d2-11e9-8280-9e2b8645e08a.png)

**Comment by chrbusch** [comment]
m.E. erledigt.
Bitte die Maske aufrufen und dann anrufen, ist schneller am Tel. erklärt.

![image](https://user-images.githubusercontent.com/1241899/57443623-c46cf000-724e-11e9-9c6b-9a20c4dd6365.jpeg)

**Comment by Toelk-A** [comment]
Leider noch nicht erledigt.

Die rote Markierung zeigt die fehlenden Anklickmöglichkeiten. Es kann ja/nein angeklickt werden, danach verschwindet allerdings wieder der "schwarze Punkt". und es sieht aus wie gezeigt:

![image](https://user-images.githubusercontent.com/22314271/57679863-9f042b80-762c-11e9-8063-e6db6f3db4ec.png)

**Comment by chrbusch** [comment]
Ooops, da hatte ich eine Strichstärke versehentlich auf Null gesetzt, sollte jetzt klappen

![image](https://user-images.githubusercontent.com/1241899/57753230-db4a9100-76eb-11e9-939f-45fec8525d2f.jpeg)

**Comment by Toelk-A** [comment]
funktioniert wieder
