### ISSUE TITLE
Adressen in Spendermeldung / TX Anforderungen werden anders abgebildet (dies wurde nicht beauftragt)

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#522]
Beispiel Spendermeldung:

![image](https://user-images.githubusercontent.com/22314271/57600835-2b461e00-755b-11e9-9d00-047e0f771e9c.png)

Beim Suchen von Adressen sieht man auch nur Abkürzungen? Hier sieht leider keiner mehr durch. Bitte wie früher: Klinik, Abteilung,Station abbilden

![image](https://user-images.githubusercontent.com/22314271/57600926-6fd1b980-755b-11e9-897b-626be3104740.png)

Mit diesem Kürzel kann keiner etwas anfangen. Es ist weder Krankenhaus noch Station ersichtlich. Wer hat die geänderte Ansicht der Adressen beauftragt?

Beispiel Gewebeanforderungen

Hier ist genau das gleiche "Chaos" man sieht nur Abkürzungen und keine Kliniken mehr...
![image](https://user-images.githubusercontent.com/22314271/57601063-d35be700-755b-11e9-867d-6d9d7052678b.png)

Welcher OP gehört zur Klinik in BONN???
![image](https://user-images.githubusercontent.com/22314271/57601121-f4243c80-755b-11e9-9e83-c1afbf0b88b5.png)

**Comment by chrbusch** [comment]
...jetzt besser?

![image](https://user-images.githubusercontent.com/1241899/57675854-6449c580-7623-11e9-978d-31fb7897ac95.jpeg)

**Comment by Toelk-A** [comment]
erledigt, danke
