### ISSUE TITLE
GBMV/ Bemerkung/Befund Spaltlampenbefund in Kpt des TX abbilden

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#523]
ID4254

Transplantatdetails - Prozesschritt Spaltlampenbefund - Abschnitt Bemerkungen/Befund - DMEK Zone

![image](https://user-images.githubusercontent.com/22314271/57676110-11bcd900-7624-11e9-81ac-d8b0ced038d5.png)

Wenn die DMEK-Zone angekreuzt ist, bitte in der kpt (Kompaktansicht) des Transplantates abbilden

![image](https://user-images.githubusercontent.com/22314271/57676291-7841f700-7624-11e9-9387-61a6f3cfa0ec.png)

![image](https://user-images.githubusercontent.com/22314271/57676396-b3dcc100-7624-11e9-87c8-d06d17a8f362.png)

der gelb markierte "zcPT" wird derzeit händisch durch die MA eingetragen. Entweder sie bilden die DMEK Zone direkt dort im Spaltlampenbefund ab oder bei Bemerkungen ( rote Markierung)

Danke

**Comment by chrbusch** [comment]
Ist der ganze Eintrag in der Zeile SpaLaBefund manuell erfolgt? Könnte man das nicht generell "errechnen" aus den Einträgen in der SpaLaBefund-Maske?

**Comment by Toelk-A** [comment]
gerne. Soweit ich weiß ist alles manuell. Gerne können Angaben automatisch übernommen werden, allerdings muss das Spaltlampenfeld weiterhin ein "Eingabefeld" bleiben um eventuell Nachträge zu dokumentieren

**Comment by chrbusch** [comment]
Links unten beim SpaLa ist nun eine Zusammenfassung; diese wandert durch ein alle 5 Minuten ablfd. Serverscripts in die Befundzeilen des Typs 126=SpaLa
Für Transplantat 4254 resultiert hier etwa:
DMEK:zcPT; Bem.:DMEK > opt. Z. , V.a. FKN

**Comment by chrbusch** [comment]
...und jetzt, wo wir so ein Script haben: Können weitere Daten automatisch in entspr. Befundzeilen wandern?

**Comment by chrbusch** [comment]
Bitte Frau Schröder auf das neue Feld hinweisen:

![image](https://user-images.githubusercontent.com/1241899/57681170-7a5d8300-762f-11e9-81d1-e81fb71adaf4.jpeg)

**Comment by Toelk-A** [comment]
![image](https://user-images.githubusercontent.com/22314271/57682797-d4137c80-7632-11e9-8b4b-760483fd4dae.png)

**Comment by Toelk-A** [comment]
**Bsp.: Transplantatdetails ID 4268 und 4269**
-	Punkte bei DMEK-Zone in Spaltlampen-PDF können nicht mehr entfernt werden, dadurch kam es zum cS den es nicht gibt
-	für DMEK-Zone (cS, pcPT, zcPT) steht nur „DMEK:“ das führt zu Verwirrungen, es muss unbedingt „DMEK-Zone“ heißen
-	zudem werden bei diesem Bsp. Keine Bemerkungen übernommen („Bem.:“)

**Bsp. Allg.: 4268 bis 4273**
-	Datum und Endbefund werden nicht dokumentiert
-	Klassifikation Anwendung werden nicht eingetragen, dafür gibt es im SL-Befund auch kein Feld zum Eintragen (Möglichkeit eines Feldes in Befund, ohne das es auf PDF erscheint?)

**Comment by chrbusch** [comment]
Ad 1) Punkte können durch Halten der SHIFT-Taste und Klick entfernt werden, das war auch nie anders. Ich habe aber jetzt auch einen Löschbutton für dieses Feld platziert.
Ad 2) Erl.
Ad 3) Bem. werden übernommen, wenn sie gleich geschrieben werden, VOR dem Abgleich mit dem Server. Aber es muss die Unterschrift unter den Befund gesetzt werden und dies ist 2019 noch nie geschehen!
Wie besprochen programmiere ich heute, dass Frau Schröder alle heutigen Befunde auf einmal unterzeichnen kann.
Sie hat sich laut Programmanalyse dieses Jahr noch nie selbst eingeloggt, stimmt das?

**Comment by EmmaSchroederGBMV** [comment]
Ad 1) das wussten wir nicht, wurde auch nie kommuniziert...  aber danke für den Button.
Ad 2) wir testen alles am Freitag nochmal
Ad 3) das müssen wir nochmal genauer betrachten... Ein Einloggen seitens Frau Dr. Schröder hat noch nie stattgefunden. Da es bisher keine richtige Einführung in das Programm gab! 
Durch Neuerungen seitens des QM´s und die bisher stehende Papierdokumentation, muss der Befund jederzeit auch ohne die 20c (Dr. Schröder) Unterschrift eingelesen werden. Denn einen Befund kann jeder erstellen...dementsprechend dürfen diese Sachen nicht zurückgehalten werden. In Zukunft soll es eine Abänderung des Dokuments dahingehend geben, dass der Befund von einer autorisierten Person erhoben werden darf und nur im Nachhinein eine Prüfung dieses Befundes durch die 20c (Dr. Schröder/ Dr. Nitschke) erfolgen muss. Wenn hierzu noch eine Frage auftaucht bitte anrufen. 
Es ist zur Zeit nur wichtig das die Befunde übernommen werden auch ohne Unterschrift von Frau Dr. Schröder.

**Comment by chrbusch** [comment]
Frau Schröder kann nun alle gezeigten DSe unterzeichnen. Für die von gestern habe ich dies zum Testen getan

![image](https://user-images.githubusercontent.com/1241899/57767855-a7329880-770a-11e9-90a9-46f0c7f19b22.jpeg)

**Comment by Toelk-A** [comment]
LogIN als Dr. Petra Schröder:

Nach Klick auf Button "Alle unterzeichnen" erscheint folgende Fehlermeldung

![SL](https://user-images.githubusercontent.com/22314271/58021522-66bc8b80-7b0b-11e9-8ed0-424bf50493f1.jpg)

**Comment by chrbusch** [comment]
Erl.

**Comment by Toelk-A** [comment]
Unterschrift wurde gestern gegen 15:00Uhr gesetzt. Leider noch keine Ergebnisse für Spaltlampenbefund übernommen. Bitte prüfen.


![image](https://user-images.githubusercontent.com/22314271/58070712-64554280-7b9a-11e9-89d4-de806a6bdb39.png)

**Comment by chrbusch** [comment]
Die obigen "Ergebnisse" sind gelöscht und das System überträgt nur noch unterschriebene Befunde.

**Comment by Toelk-A** [comment]
Übertragung hat gut funktioniert.

Es fehlen nur noch Datum und End-Befund. Dies Bitte aus dem Splatlampenbefund übernehmen. (1 Spaltlampenbefund ist IMMER ein ENDBefund)

![Nachtrag SL Befund](https://user-images.githubusercontent.com/22314271/58156322-22013380-7c76-11e9-8882-20167197bd57.jpg)

**Comment by chrbusch** [comment]
Script wurde erweitert, sollte jetzt klappen

![image](https://user-images.githubusercontent.com/1241899/58229030-d2337280-7d30-11e9-9cdc-e34f7c84a989.jpeg)

**Comment by Toelk-A** [comment]
Übernahme funktioniert soweit. Bitte noch folgendes anpassen:

1) Datum = ?  Bitte richtig programmieren (rote Markierung)

2) Bitte Spalte Uhrzeit entfernen udn dafür Spalte "Bemerkungen" vergrößern, sodass der ganze Text abgebildet wird.
![image](https://user-images.githubusercontent.com/22314271/58305416-4e44bd80-7df8-11e9-90ff-19a898f3cc27.png)

**Comment by chrbusch** [comment]
Erl.

![image](https://user-images.githubusercontent.com/1241899/58310706-8a334f00-7e07-11e9-9053-c94c60f413a3.jpeg)
 ("?" kommt nicht mehr bei Befunden AB JETZT)

**Comment by Toelk-A** [comment]
(1 Spaltlampenbefund ist IMMER ein ENDBefund) -> bitte noch einmal prüfen, ob dies auch so programmiert ist und automatischer das Häkchen im "E" nicht um "V" gesetzt wird. Danke

**Comment by chrbusch** [comment]
Alle SpaLa-Befunde werden auf "E" gesetzt; ist sonst alles erl. hier?

(Techn. Bem.: Das ist im Script
  \_OP5D.BefundErg. SpaltLampe etc aktualisieren/ 230519 QQ
)

**Comment by Toelk-A** [comment]
JA
