### ISSUE TITLE
Bugfix - Allokation - Transplantatliste - Klick auf Button "NUR"

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#524]
Hallo Herr Busch,

neuerdings kommt die folgende Meldung nach Klick auf den Button "NUR" in der Transplantatliste:

Wer hat dies beauftragt? Dies macht den Prozess der TX Abrechnung nur umständlicher. Bitte löschen Sie die Meldung wieder

![image](https://user-images.githubusercontent.com/22314271/57915864-f7883280-7891-11e9-9f78-11c09f972b39.png)

![ALLOK ](https://user-images.githubusercontent.com/22314271/57915764-babc3b80-7891-11e9-8e53-0bf86292e89e.jpg)

**Comment by chrbusch** [comment]
Sie heben Recht, HIER ist das unpraktisch und wird deaktiviert. An anderer Stelle ist es aber sehr nützlich; dies zeige ich Ihnen, wenn wir die neue Seite zur Gestaltung der Rollen besprechen.

lg
cbu

**Comment by Toelk-A** [comment]
danke
