### ISSUE TITLE
Personalmodul: Berechtigung für Sonderjobs

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#526]
Es dürfen KEINE MItarbeiter den Sonderjob Urlaub BEZ oder AZK auswählen. Können dies war bereits programmiert.

Nur Supervisor + Buchhaltung + GF darf dies. Alle anderen Mitarbeiter dürfen die folgenden gelb markierten Optionen nicht haben:

![image](https://user-images.githubusercontent.com/22314271/58097432-a6e94000-7bd7-11e9-9af7-9fea72d7c058.png)

**Comment by chrbusch** [comment]
Wie soeben tel. besprochen passiert dies nur, weil COA in Ornella das Kreuz bei "Spezielle Rechte/Supervisor" hat.
Wir ersetzen zügig dieses Feld "Spezielle Rechte" gg. die neue, von ATö bearbeitbare RollenDefinition

**Comment by chrbusch** [comment]
m.E. ist dies erledigt mit dem neuen Ansatz
