### ISSUE TITLE
Bugfix Hausarztadresse wird als Zahl und ? abgebildet

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#527]
Spender ID 8242
Prozesschritt med Indikationsprüfung

![image](https://user-images.githubusercontent.com/22314271/58182392-cfdc0480-7cad-11e9-813a-2cdeff2d838c.png)

**Comment by chrbusch** [comment]
fixed

![image](https://user-images.githubusercontent.com/1241899/58228884-59341b00-7d30-11e9-9aad-5247c3af2d53.jpeg)

**Comment by Toelk-A** [comment]
Hausarzt wird weiterhin als Zahl abgebildet:

Spender ID: 8371

![image](https://user-images.githubusercontent.com/22314271/58868814-61d80a00-86bd-11e9-9f86-34fee9b3cc90.png)

**Comment by chrbusch** [comment]
beim letztgenannten Spd ist zumindest jetzt alles OK; ich bräuchte ein nicht korrigiertes Beispiel, um das Problem nachzuvollziehen.
Eventuell war das auch nur ein Schirm-Aktualisierungsproblem; im Script erzwinge ich jetzt einen Neuaufbau der Daten nach Auswahl des Hausarztes
