### ISSUE TITLE
Datenexport GTM-V / GBM-V

### ISSUE THREAD

**Issue by chrbusch** [chrbusch/GTM-V#528]
Es gibt nun zwei "hidden buttons" für die Exportberechtigung des jew. Mandanten.
Den beiden Rollen "Arzt G..." habe ich jew. einen dieser Buttons zugeordnet.

**Comment by chrbusch** [comment]
Das Bild zeigt alle Scripts mit "Export" im Namen; die meisten sollten für Sie erkennbar sein, weil zB der Button "Export B" heißt.
Welcher Mandant darf hier jeweils exportieren?

![image](https://user-images.githubusercontent.com/1241899/58237576-b1294c80-7d45-11e9-9187-c9fc830395aa.jpeg)

**Comment by Toelk-A** [comment]
GTM-V:
Export S
Export D
Export C
Export SD


GBM-V
Export TRX
Export B
Export E

Folgende Exporte kenne ich nicht/kann ich nicht zuordnen

Export F 
Export T2

**Comment by chrbusch** [comment]
GTM-V:
√Export S
Export D: Kann ICH nicht zuordnen
√Export C
Export SD: Kann ICH nicht zuordnen

GBM-V
√Export TRX
√Export B
√Export E

Folgende Exporte kenne ich nicht/kann ich nicht zuordnen

Export F: Das sind Transplanate + Befunde, verm. GTMV?
Export T2 Das sind Transplanate , verm. GTMV?

**Comment by Toelk-A** [comment]
### Export D: Kann ICH nicht zuordnen (GTMV)
-> ich auch nicht, war wohl ein Fehler meinerseits

### Export SD: Kann ICH nicht zuordnen (GTMV)
dies sollte der Export "Spenderdiagnosen" sein

### Export F: Das sind Transplanate + Befunde, verm. GTMV?
wenn dies mikrobiologische Befudne sind, ist Export F  **GBMV**

### Export T2 Das sind Transplanate , verm. GTMV?
Transplantate sind **GBMV**

**Comment by chrbusch** [comment]
Export SD/ Export "Spenderdiagnosen" ist Teil von ExportS und somit GTMV

ExportF betrifft Felder der GewebeEntnahme, m.E. GTMV?!

Export T2 / Transplantate umgestellt auf GBMV

**Comment by Toelk-A** [comment]
### Export SD/ Export "Spenderdiagnosen" ist Teil von ExportS und somit GTMV
okay

### ExportF betrifft Felder der GewebeEntnahme, m.E. GTMV?!
ja GTMV

### Export T2 / Transplantate umgestellt auf GBMV
okay..


Das bedeutet wir müssen für den Export auch eine neue Rolle erstellen, richtig?

**Comment by chrbusch** [comment]
Ist das jetzt alles so weit, wie Sie es vor meinem Urlaub brauchen?

**Comment by Toelk-A** [comment]
ja scheint zu funktionieren.

**Comment by Toelk-A** [comment]
Leider kann ich den Hidden Button "Export B" nicht finden

**Comment by chrbusch** [comment]
Den gibt es auch nich, wir haben einen Export-Button pro Mandant

![image](https://user-images.githubusercontent.com/1241899/62214175-d325f780-b3a4-11e9-91cc-161e36de7216.jpeg)
