### ISSUE TITLE
Wiedervorlagen in Ornella AZK Wunsch / Urlaubs Wunsch

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#533]
A) Leider fehlt das Datum für den Wunsch in der Wiedervorlage. Dies hat früher einmal funktioniert...

B) Ist es generell auch möglich nur Mitarbeiterwünsche der GTM-V für die Ärzte/buchhaltung GTM-V anzuzeigen bzw. nur Mitarbeiterwünsche GBM-V für die Ärzte/Buchhaltung GBM-V anzuzeigen?

Frau Fischer (GTMV) erhält Infos von Mitarbeitern der GBMV, löscht diese und damit sieht sie Frau Kaluzny nicht mehr in ihren Wiedervorlagen....

**Comment by Toelk-A** [comment]
weitere Idee: ist es möglich die Wiedervorlagen ähnlich dem Rollenkonzept einem Mitarbeiter zuzuordnen?

**Comment by chrbusch** [comment]
A) ist m.E. erledigt, bitte testen

B) Ich habe nun, je nach Mandant des Mitarbeiters, die folgenden Empfänger für die WV Urlaubswunsch wie folgt gesetzt:
Case( _Pos( $pk_Mand; "GB" ); "FIB¶KAL¶NIB¶";
  "NIF¶MAA¶FIC¶KAT"
)

Ist das so korrekt? Dann bitte testen.
Wir können diese Regel nun auch für alle anderen WVs anwenden, bei denen dies relevant ist
