### ISSUE TITLE
Prozesschritte Sepnderdetails - 2 Prozessschritte fehlen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#537]
Prozesschrit Checkliste und Freigabe fehlen

![tttt](https://user-images.githubusercontent.com/22314271/59093403-25521b80-8914-11e9-99a0-aa51e69f62b1.jpg)

**Comment by chrbusch** [comment]
2 Zeilen man. angelegt

**Comment by Toelk-A** [comment]
Prozessschritt Freigabe Archivierung fehlt noch

**Comment by chrbusch** [comment]
Addiert
