### ISSUE TITLE
BUGFIX/ fehlende Prozesschritte

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#539]
bei der Spende 080619-0848-GNO-PET (ID8480) fehlt in den Prozessschritten „Freigabe Gewebeentnahme“ + Checkliste

![image](https://user-images.githubusercontent.com/22314271/59324718-6b2a2d80-8ce0-11e9-9959-e77d59254f20.png)

**Comment by chrbusch** [comment]
Ist hier ein Abbruch vorgenommen worden?
Muss ich noch etwas tun, oder ist das sowieso zu spät?

**Comment by chrbusch** [comment]
Ich habe die zwei Zeilen manuell angelegt, bitte prüfen

**Comment by Toelk-A** [comment]
Prozesschritt "Freigabe Archivierung" fehlt noch

**Comment by chrbusch** [comment]
Addiert
