### ISSUE TITLE
!Wichtig! Entnahmebericht OG - Adresse verantwortlicher Arzt und des Koordinators bitte vollständig abbilden

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#54]
Spenderkennnummer: 191116-0215-GNO-SCD
Entnahmebericht OG
Seite 2 unten 

"Stempel" -> Adresse des verantwortlichen Arztes und Adresse des Koordinators sind nicht vollständig abgebildet - "Rostock"

![image](https://cloud.githubusercontent.com/assets/22314271/20554122/0f1fc28e-b15a-11e6-9a97-b5c0e9f1af81.png)

**Comment by Toelk-A** [comment]
hier übersichtlicher:

![image](https://cloud.githubusercontent.com/assets/22314271/20554210/a849a542-b15a-11e6-9b45-4001061f73c7.png)

**Comment by chrbusch** [comment]
Erledigt

![bildschirmfoto 2016-12-01 um 10 43 52](https://cloud.githubusercontent.com/assets/1241899/20788981/15caeb22-b7b3-11e6-8346-afe2d811a0e9.JPG)

**Comment by Toelk-A** [comment]
nun ist "Stempel" abgeschnitten


![image](https://cloud.githubusercontent.com/assets/22314271/20789575/3b442e16-b7b5-11e6-8ce0-1d394f98ea6e.png)

**Comment by chrbusch** [comment]
Erledigt
