### ISSUE TITLE
Bugfix/ Abbruch Spenderdetails nicht möglich

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#540]
Nach Klick auf Button Abbruch -> "Logistik intern"  werden die Prozessschritte abgebrochen(siehe unten) allerdings erscheint auf den Spenderdetails kein "Abbruch"

![image](https://user-images.githubusercontent.com/22314271/59605080-3f5add80-910e-11e9-8767-e0843eda161e.png)

![image](https://user-images.githubusercontent.com/22314271/59605029-14708980-910e-11e9-8755-f5f0b7deb630.png)

**Comment by chrbusch** [comment]
Bei Ihrem Spd 8558 sieht aber alles korrekt aus, und ich habe gerade mit Testspender 77 alles probiert: Klappt tadellos?!?

**Comment by Toelk-A** [comment]
Sie sehen ja anhand des Screenshots, dass der Abbruch nicht möglich war. woran liegt das?

**Comment by chrbusch** [comment]
Da das Problem nicht reproduzierbar ist und eben alles glatt lief, kann ich das nicht sagen.
Ist die in den vergangenen Wochen mehrfach passiert?

**Comment by Toelk-A** [comment]
manchmal gab es probleme hiermit...
