### ISSUE TITLE
Buchhaltung / AGE Rechnungen ausblenden

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#541]
Bitte wie besprochen die "AGE-Rechnungen" aus der Liste Debitor Rechnung ausblende

![image](https://user-images.githubusercontent.com/22314271/59655021-1a5f7c80-9199-11e9-819e-64b3b7464301.png)

**Comment by mprueter** [comment]
Folgende einfache Lösung habe ich erst einmal programmiert:

![Bildschirmfoto 2019-06-21 um 08 58 25](https://user-images.githubusercontent.com/3273572/59904226-4aaa5380-9403-11e9-85ff-ac8f2012ad24.png)

...mit diesem Button können Sie schnell aus jeder beliebiegen Fundmenge die AGE-Rechnungen ausschließen. Reicht das?
