### ISSUE TITLE
Wiedervorlagen addressieren, hidden buttons

### ISSUE THREAD

**Issue by chrbusch** [chrbusch/GTM-V#543]
Es gibt die folgenden Arten von WV  im Programm:
Rng bezahlt
LagerbuchungsProblem
Vorläufige Indikation zur Spende
Einwilligungsgespräch anlegen
Kontoimport für GBMV
Kontoimport für GTMV
Mediz. Indikationsprüfung anlegen
AZK MA Wunsch
Urlaub MA Wunsch
Neuer Spender über Schnittstelle
Offene Transplantat-Anforderung
RBD-Konflikt
hat Erg. <pos.> bei
Spender gesetzt auf Status
Transplantat gesetzt auf Status

Soll ich für jede (?) davon einen "hidden Button" anlegen, so dass Sie diese Buttons den Rollen zuteilen können?

**Comment by chrbusch** [comment]
Die ersten drei "hidden buttons" wurden angelegt:

![image](https://user-images.githubusercontent.com/1241899/60165695-069ec080-9800-11e9-812b-016662e3c47d.jpeg)

**Comment by chrbusch** [comment]
Sie können diese zwar schon zuordnen; aber ich muss das Script für die Wiedervorlagen noch anpassen.

**Comment by Toelk-A** [comment]
### Soll ich für jede (?) davon einen "hidden Button" anlegen, so dass Sie diese Buttons den Rollen zuteilen können?

Ja bitte

**Comment by chrbusch** [comment]
Der hidden Button "WV Spender gesetzt auf Status" ist keiner Rolle mehr zugeteilt, ist das Absicht? Es bekommt nun niemand mehr eine WV, wenn ein Spd den Status wechselt.
![image](https://user-images.githubusercontent.com/1241899/60322107-efd2a800-997e-11e9-83c9-ee96802116c1.jpeg)

**Comment by Toelk-A** [comment]
Hallo Dr. Busch, Frau Deuschle enthält keine der markierten Wiedervorlagen. Die anderen konnten wir noch nicht testen. Bitte überprüfen Sie die Programmierung der "Hidden Buttons Wiedervorlagen"

![image](https://user-images.githubusercontent.com/22314271/60644253-ce1d6900-9e35-11e9-9461-56a1d9adb0fe.png)

**Comment by chrbusch** [comment]
Ich brauche ein konkretes Beispiel: Bei welchem Transplantat wurde ein Wert gesetzt, der als WV hätte gemeldet werden müssen?

**Comment by chrbusch** [comment]
Hidden Buttons können nun bel. vielen Rollen zugeteilt werden.
Bitte prüfen, ob diese User eine WV sehen bezgl. eines positiven Befundes bei SpdTranspl mit ID=4572:KNA, NIB, DEN
Wenn nach wie vor andere WVs nicht ankommen, bitte mit konkretem Beispiel hier melden.

**Comment by Toelk-A** [comment]
Können hier anstatt der Transplantat ID´s die bankinternen Nummern abgebildet werden? Danke

![Transplantat](https://user-images.githubusercontent.com/22314271/60975739-c0338080-a32c-11e9-988d-884d46df7ffe.jpg)

**Comment by chrbusch** [comment]
Sollte bei WVs, die ab jetzt erstellt werden, so sein

**Comment by Toelk-A** [comment]
1) Beide Rollen Mitarbeiter Buchhaltung erhalten gar keine Wiedervorlagen mehr. Bitte dringendst Programmierung prüfen (Kontobewegungen, AZK - Wunsch, Urlaubs-Wunsch...)
2) Bitte Wiedervorlage "RBD-Tauschwunsch erstellen"

**Comment by chrbusch** [comment]
Ad 1) Das WV-Modul im Perso-Bereich war noch gar nicht auf "hidden buttons" umgestellt, bitte jetzt testen
Ad 2) m.E. erledigt, bite testen

Ich benutze jetzt für alle WVs aus dem PersoModul den Buttons 168, den ich umbenannt habe auf "WVs aus PersoModul" - einverstanden?

**Comment by chrbusch** [comment]
Es gibt nun zwei hidden buttons, "WV PersoModul GBMV" und "WV PersoModul GTMV".
Deren Rollenzuteilung habe ich aufgeräumt.
Die WVs betreffend die Wünschw im PersoModul (Urlaub, AZK, RBD-Tausch) werden je nach Mandant des eingeloggten Mitarb. an die Inhaber der jew. Rollen gesendet.
Bitte testen
