### ISSUE TITLE
GTMV/ Rollen + Rechte "Leitender Koordinator"

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#544]
![image](https://user-images.githubusercontent.com/22314271/60239090-c5181f00-98ac-11e9-9235-5a5e7cfcf12f.png)

Mitarbeiter, die sich in dieser Rolle befinden sollen zukünftig die Möglichkeit haben, die Spenderkennnummer zu ändern (natürlich nur solange dies keien Auswirkungen auf die Transplantate etc. hat).

Unter "Neuer Button" habe ich diese Möglichkeit jedoch nicht gefunden. 

![image](https://user-images.githubusercontent.com/22314271/60239173-03add980-98ad-11e9-9e5b-4f2710d7b012.png)

Derzeit sind dies Supervisorrechte, allerdings kann es immer einmal auftreten dass Mitarbeiter krank sind und der Koordinator in der Spenderkennnummer geändert werden soll:

![image](https://user-images.githubusercontent.com/22314271/60239245-47a0de80-98ad-11e9-85b1-118e8f53fe93.png)

-> Koordinator zu TOA geändert

![image](https://user-images.githubusercontent.com/22314271/60239266-59828180-98ad-11e9-9baa-aadb1c8501a1.png)

-> Nun muss auch die Spenderkennnummer geändert werden - Button "Spender-KrennNr. setzen"

![image](https://user-images.githubusercontent.com/22314271/60239302-7323c900-98ad-11e9-88e1-8277a50b2554.png)

Dies ist derzeit nur Supervisorn erlaubt:

![image](https://user-images.githubusercontent.com/22314271/60239328-8d5da700-98ad-11e9-8e25-6323b4b79ac9.png)

Hier bitte Möglichkeit programmieren, dass diese Funktion einer Rolle zugeordnet werden kann, gerne auch als Hidden Button.

![image](https://user-images.githubusercontent.com/22314271/60239351-a8c8b200-98ad-11e9-96a3-442e0437df00.png)

**Comment by chrbusch** [comment]
Das Ändern mancher Kennnr wurde ganz am Anfang fix auf "Supervisor only" gesetzt.
Aber mit den hidden buttons sind wir jetzt viel flexibler!
Ich habe einen entrp. definiert und der Rolle zugeordnet; dauert alles zusammen wenige Minuten. Sie können nun ohne mich anderen Rollen - auch temporär, weil zB Ärzte krank sind - diesen Button zuordnen.
![image](https://user-images.githubusercontent.com/1241899/60270217-39c07d00-98f0-11e9-83bf-e226eca2cca9.jpeg)

**Comment by chrbusch** [comment]
User in Rollen mit dem neuen Btn 180 können nun die KennNr ändern.
Ähnliches kann nun auch für nahezu beliebige andere Aktionen im Programm leicht realisiert werden.
Dem Script das prüft, ob ein User eine bestimmte Aktion durchführen darf, kann nun auch direkt die erforderliche ButtonID übergeben werden.

**Comment by Toelk-A** [comment]
Es kommt noch immer die Fehlermeldung, dass User keine supervisorrechte hat zum ändern der Spenderkennnummer. Bitte Programmierung prüfen

![leitende koord](https://user-images.githubusercontent.com/22314271/60323738-43df8b80-9983-11e9-9528-5ff2f2fbbb54.jpg)

**Comment by chrbusch** [comment]
Ich denke, hier wird etwas verwechselt: Der gezeigte Dialog gehört zum Ändern des Koordinators, nicht der KennNr. Und an dieser Funktion habe ich nichts geändert.
Sollen genau diejenigen den Koordinator wechseln dürfen, die die KennNr ändern dürfen?

**Comment by Toelk-A** [comment]
steht alles oben im Ticket... bitte nochmal nachschauen und dies programmieren. Danke

**Comment by chrbusch** [comment]
Sorry, ich habe den obigen Teil nicht beachtet; steht wirklich alles drin, daher ist der heutige erneute Umbau "bug fix"

**Comment by chrbusch** [comment]
Bitte jetzt erneut testen

**Comment by Toelk-A** [comment]
funktioniert danke
