### ISSUE TITLE
Bugfix/ KVG-Details

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#547]
Gravierender Fehler passiert:

Präparateliste nach Spender gesucht, femoralis D angeglickt, Button "Transplantate wählen"

![image](https://user-images.githubusercontent.com/22314271/60432283-29671580-9c02-11e9-8ac4-c1f4375307b0.png)

-> Info externe Banknummer, ok
-> Partnerseite anlegen wenn vorhanden -> auf "ja geklickt"
-> Eingangskontrolle OG erscheint -> dies gehört hier nicht hin

DANNN

entstanden folgenden Transplantate:

aus einer arteria femoralis dextra wurde als Partnerseite die zuletztangelegte Pulmonalklappe angelegt (die PKL gehört allerdings zu einem völlig anderen Spender!!

Dies bitte dringendst prüfen

![image](https://user-images.githubusercontent.com/22314271/60432208-f755b380-9c01-11e9-9b9a-1387caa219f9.png)

**Comment by chrbusch** [comment]
Das Script wechselt nun bei KVG zu den "KVG-Details"- ist das so gewollt?
Den Rest müssen wir besprechen und gemeinsam ausprobieren. Bitte dazu anrufen.

**Comment by chrbusch** [comment]
Das ist m.E. erledigt, aber bitte aufmerksam beobachten in den kommenden Tagen
