### ISSUE TITLE
!Wichtig!  Separate Entnahmeberichte OG, MSG, KVG mit differenzierten Entnahmezeiten

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#55]
Pro Spender benötigen wir für jeden Entnahmebericht ob OG, MSG oder KVG differenzierte Entnahmezeiten. Im Moment übernimmt Ornella automatische den "Zeitpunkt der Entnahme" (Datum und Uhrzeit) aus OG zu MSG. Dies darf nicht sein, da Entnahmen eines Spenders an unterschiedlichen Zeitpunkten (Tag + Uhrzeit) stattfinden können. Dementsprechend müssten ebenfalls 2 separate, differenzierte "Meldungen mobiles Entnahmeteam" zu den jeweiligen Zeitpunkten ausgefüllt werden können.

![image](https://cloud.githubusercontent.com/assets/22314271/20559312/2160a728-b174-11e6-95e5-aa794c10c216.png)

![image](https://cloud.githubusercontent.com/assets/22314271/20559339/3e14a28e-b174-11e6-95dd-34fa54009795.png)

**Comment by chrbusch** [comment]
Ist m.E. erledigt, bitte testen und Rückmeldung

**Comment by Toelk-A** [comment]
funktioniert
