### ISSUE TITLE
GTMV/ Spenderdetails Reiter Chat Bermerkungsfeld vergrößern

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#551]
Bitte das Bemerkungsfeld im Chat vergrößern, sodass der Text vollständig abgebildet wird (Datumsfeld, Uhrzeit USER und Textfeld können verkleinert werden). Textfeld aber bitte soverkleiner, dass ggf. auch mehrere Zeilen (ohne Reinklicken) lesbar sind.

Danke

![image](https://user-images.githubusercontent.com/22314271/61374047-abf70280-a89b-11e9-8583-0da5c231cf35.png)

**Comment by chrbusch** [comment]
Erl.
