### ISSUE TITLE
GTMV/ Spenderdetails - Abbildung bearbeitender Mitarbeiter

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#552]
Wie eben telefonisch vereinbart benötigen wir im Abschnitt Spenderkennummer, die Asuwahlmöglichkeit "Akte in Bearbeitung bei" -> Auswahl Mitarbeiter GTMV (Außer Buchhaltung + geringfügig Beschäftigte)

**Comment by chrbusch** [comment]
Tut mir leid, dass dies solange gedauert hat, aber nun können Sie es testen…

**Comment by Toelk-A** [comment]
Bitte noch die Mitarbeiterauswahl wie oben beschrieben anpassen ( keine Buchhaltung und keine geringfügig Beschäftigten abbilden)

**Comment by chrbusch** [comment]
Da diese Auswahl nicht zu unserem Rollenkonzept passt, habe ich eine neue Ankreuzoption "Spenderakte" r.o. in der User-Dateilamske geschaffen und die m.E. gewollten Mitarbeiter angekreuzt. Sie können dies nun jederzeit modifizieren.

![image](https://user-images.githubusercontent.com/1241899/61519687-cdc3c700-aa0c-11e9-8f6c-e191996ebada.jpeg)

**Comment by chrbusch** [comment]
(Techn. Anm.: Dieses Feld wird abgefragt, wenn Script "User04normal..." mit der Option "-Auswahl=[Spenderakte] " aufgerufen wird. Dies tut der Button auf Feld SpdDetails:_fk_User_Bearbeitung)

**Comment by Toelk-A** [comment]
funktioniert erstmal
