### ISSUE TITLE
Bugfix/ Versandpapiere in Spenderdokumenten abgelegt

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#553]
Spender ID 8933
Reiter Dokumente
Einwilligungsgespräch
-> es öffnet sich das PDF "Versandpapiere" eines nicht dem Spender zugehörigen Transplantates 
![image](https://user-images.githubusercontent.com/22314271/62370453-6f313980-b532-11e9-9adf-49b61cf71083.png)

zugehörige Spendertransplantate:
![image](https://user-images.githubusercontent.com/22314271/62370528-ae5f8a80-b532-11e9-8437-7b05d8451db8.png)

**Comment by chrbusch** [comment]
Sehe ich richtig, dass dies ein einmaliges Problem ist? Ich habe zZ keine Idee, wie das passiert ist.

**Comment by Toelk-A** [comment]
Zu Ihrer Mail:
Hallo - WICHTIG!

Während ich eben die Ursache eines von ATö bemerkten Fehlers in EINEM Dokument suchte stellte ich fest:
Durch einen vermutlich von mir verursachten Fehler sind etliche PDF-Dokumente zwar richtig erstellt worden, aber nicht ins Dokumentenarchiv des Spenders einsortiert worden.

Fast alle konnte ich (bug fix!!) selbst zuordnen, i.d.R. weil die Spd-KennNr im Dateinamen enthalten war.
Verbleibende Ausnahmen sollten wir Montag besprechen.

Schöne WE
cbu


Es dürfen "KEINE" Versandpapiere in den Spenderdokumenten abgelegt werden. Die Versandpapiere gehören zu den Dokumenten in den Transplantatdetails. Bitte prüfen!

**Comment by chrbusch** [comment]
Das ist jetzt ebenfalls erledigt; und die Versandpapiere bekommen jetzt auch im Archiv die korrekte "Art", was vorher nicht der Fall war (bug fix)

**Comment by Toelk-A** [comment]
danke
