### ISSUE TITLE
Änderung Mitarbeiterkürzel (ID_pk User)

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#554]
Hallo Dr Busch,

folgendes Mitarbeiterkürzel muss umbenannt werden in MEK:

![image](https://user-images.githubusercontent.com/22314271/62443225-9cf8c700-b75a-11e9-8b5e-3f3469cbc6b3.png)

Ich kann dies trotz Supervisorrechte nicht eigenständig durchführen.

**Comment by chrbusch** [comment]
Erl.

**Comment by chrbusch** [comment]
Das Passwort enthielt "KME" und ist m.E. auch zu einfach zu raten.
Bitte teilen Sie der Kollegin dieses neue Passwort mit:
M5k_1807

**Comment by Toelk-A** [comment]
Bitte ändern Sie zukünftig Passwörter nur nach Rücksprache mit uns. Frau Melcherr kann nicht arbeiten. Sie hat sich mit Ihrem neu erstellten Passwort eingeloggt, es kommt eine Meldung von Ihnen, dass sie sich bei mir melden soll. Bitte prüfen Sie die Programmierung. Dies ist Bugfix da nicht von uns beauftragt.
