### ISSUE TITLE
AGE Rechnungen - Begriff "Rechnungsnummer" entfernen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#556]
Hallo Herr Prüter,

Bitte das Wort "Rechnungsnummer" löschen und "Beleg-Nr" abbilden.

![image](https://user-images.githubusercontent.com/22314271/62523458-216b4880-b834-11e9-8343-54f6f9913280.png)

**Comment by mprueter** [comment]
Das ist jetzt so umgesetzt:

![Bildschirmfoto 2019-08-06 um 11 25 58](https://user-images.githubusercontent.com/3273572/62528523-43b59400-b83d-11e9-9766-037ca38312aa.png)


![Bildschirmfoto 2019-08-06 um 11 27 01](https://user-images.githubusercontent.com/3273572/62528531-487a4800-b83d-11e9-99d2-ca9bd554c43f.png)

**Comment by Toelk-A** [comment]
auf den aktuellen AGE Auflistungen steht noch immer Rechnungsnummer, bitte prüfen und wie oben gewünscht ändern, danke

[AGE Besipiel Rechnungsnummer.pdf](https://github.com/chrbusch/GTM-V/files/3689883/AGE.Besipiel.Rechnungsnummer.pdf)

**Comment by mprueter** [comment]
...jetzt ist aber so, wie es sein soll.
