### ISSUE TITLE
MA Gtm-V (koordinator) wird nicht in Auswahl für digitale Unterschrift Entnahmebericht abgebildet

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#558]
Der folgende Mitarbeiter wird nicht in der Koordinatorenauswahl z.B. im Entnahmebericht angezeigt. Können Sie dies bitte prüfen?
VG und danke 

![image](https://user-images.githubusercontent.com/22314271/62766143-0ac22d00-ba92-11e9-9016-00ca878dce06.png)

![image](https://user-images.githubusercontent.com/22314271/62767251-8de48280-ba94-11e9-84e0-8bb322fc633d.png)

**Comment by chrbusch** [comment]
Dort werden User gezeigt, die als Koordinator markiert sind oder als Funktion "Arzt" haben; beides ist bei Hr. Süss nicht der  Fall

![image](https://user-images.githubusercontent.com/1241899/62819789-7374dc80-bb5a-11e9-9ca5-023c8bf2c2c7.jpeg)

**Comment by Toelk-A** [comment]
"Koordinator" nachgetragen
![image](https://user-images.githubusercontent.com/22314271/62919175-326f0900-bda2-11e9-92c3-dca1f555591f.png)

Mitarbeiter erscheint trotzdem nicht in der MA-Auswahl im Entnahmebericht. Des Weiteren ist mir aufgefallen, dass Mitarbeiter GBM-V in der MA Auswahl abgebildet werden. Diese haben hier nichts zu suchen (KRB - bereits ausgeschieden, NIB, THB, ATB)


![image](https://user-images.githubusercontent.com/22314271/62919113-f20f8b00-bda1-11e9-880c-fcd47e9b4910.png)

**Comment by chrbusch** [comment]
Ich denke, wir haben hier noch ein Gemisch aus altem und neuem Konzept bezgl. der Rechte. Das erste und letzte Feld im Bild meinen wohl dasselbe; das schaue ich mal in Ruhe an.
Jedenfalls reicht jetzt der Koordinator-Hinweis in jedem dieser beiden Felder für die erwähnte Liste

![image](https://user-images.githubusercontent.com/1241899/63917429-e7f4ba00-ca3a-11e9-8334-c60450ce456d.jpeg)
