### ISSUE TITLE
Buchhaltung, Rechnung stornieren die als "bezahlt/erledigT" markiert ist

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#559]
Hallo Herr Prüter,

wir haben mal wieder ein buchhalterisches Problem 😉
Die gezeigte Rechnung muss bitte storniert werden, da aus irgend einem Grund die MSG doppelt berechnet wurde (dies fand vor ihrer tollen Programmierung statt…). Da die Rechnung bereits auf „erledigt“ gesetzt wurde, kann die Stornierung durch uns nicht mehr durchgeführt werden. Können Sie dies bitte übernehmen?

VG und danke, Anita Tölk

![ornel](https://user-images.githubusercontent.com/22314271/62768164-91790900-ba96-11e9-8698-974e31e8c51c.jpg)

**Comment by mprueter** [comment]
Die Rechnung ist stoniert.
