### ISSUE TITLE
Spenderdetails - Reiter Dokumente - Dokumente durch VP§20b freigeben

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#562]
Derezeit werden sich die geuploadeten Dokumente durch MAA / NIF / TOA angesehen udn als "gelesen" bei öffnen markiert.

A) Öffnet danach ein anderer Mitarbeiter das Dokumente ist die "gelesen Markierung" (gelb hinterlegt) nicht mehr vorhanden.

![image](https://user-images.githubusercontent.com/22314271/62936827-1338a180-bdcb-11e9-8c16-02b0e21ff272.png)

B) Wir möchten auch hier einen "Freigabe" Button ähnlich der Prozesschritte. Dieser Button darf auch nur von den Ärzten bzw. VP§20b genutzt werden können (wie auch schon in den Prozessschritten programmiert. Wird ein freigegebenes Dokument z.B. Totenschein gelöscht und anschließend wieder als "Totenschein" hochgeladen, so muss dieser erneut durch die Ärzte / VP20b freigegeben werden.

**Comment by chrbusch** [comment]
A) ist erledigt

**Comment by chrbusch** [comment]
B); Das klappt jetzt m.E. auch, bitte aufmerksam testen.
Aus technischen Gründen können Dokumente erst ab 1.7.2019 frei gegeben werden; falls es wichtig ist, auch ältere frei zu geben, bitte SMS senden
![Bildschirmfoto 2019-08-17 um 11 41 21](https://user-images.githubusercontent.com/1241899/63209655-f8746e80-c0e3-11e9-8346-9abc12f85d5f.jpg)

**Comment by Toelk-A** [comment]
zu A) nicht erledigt.

klickt man den Button Freigabe, so wird nicht geloggt wer ihn gedrückt hat und wann. Bitte Programmierung prüfen
![image](https://user-images.githubusercontent.com/22314271/63242236-08608f80-c257-11e9-8b9a-f6ac8e5747c5.png)


in den Prozessschritten wird z.B. immer das Kürzel des VP20b abgebildet + Datum, wäre gut wenn dies here auch geschieht, sodass nachvollziehbar ist, wer freigegeben hat

![image](https://user-images.githubusercontent.com/22314271/63242341-5e353780-c257-11e9-9b90-cf196181468f.png)

**Comment by chrbusch** [comment]
Das Feld war durch einen Fehler verborgen, auch wenn es ausgefüllt ist. Dies ist korrigiert, und weil es nur ein Anzeigeproblem war sind auch die bisherigen Freigaben erhalten.

![Bildschirmfoto 2019-08-25 um 08 19 22](https://user-images.githubusercontent.com/1241899/63646341-5bcc5500-c711-11e9-9f55-43fa426577c9.jpg)

**Comment by chrbusch** [comment]
Wenn ein zuvor nicht gelesenes Dokument von einer VP frei gegeben wird, solles dann auch (wie ich vermute) in dem vorderen Feld als "Gelesen" markiert werden?
