### ISSUE TITLE
BUGFIX/ Userdetail Liste - "Auch als" nciht mehr nutzbar

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#566]
Für die folgende Mitarbeiterin kann das Feld "auch als" nicht genutzt werden...

Bitte früher früher funktionierte dies immer

![image](https://user-images.githubusercontent.com/22314271/63764970-55cca480-c8c8-11e9-88dc-a2218411296e.png)

**Comment by chrbusch** [comment]
fixed
