### ISSUE TITLE
BUGFIX Export B funktioniert nicht

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#568]
Export B funktioniert nicht

**Comment by chrbusch** [comment]
Trat dies auf, NACHDE ich den ersten nicht funktionierenden Export gefixt habe?
Bitte erneut testen.

(Die Probleme sind eine Folge der Änderung der mit dem Account verbundenen Rechte, die ich für die Sperrung frei gegebener Dokumente vornehmen musste.)
