### ISSUE TITLE
BUGFIX Datum Tauschwunsch wird wieder nicht angezeigt

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#569]
In der Wiedervorlage fehlt wieder das Datum...

![image](https://user-images.githubusercontent.com/22314271/64003432-869d1b80-cb0c-11e9-8b31-68e915ab1b57.png)

**Comment by chrbusch** [comment]
Ich denke, das hat noch nie funktioniert - es war ein Tippfählär im Script.
Ist m.E. erledigt.
(Und auf jeden Fall bugfix!)
