### ISSUE TITLE
Untersg. Antrag Labor - "postmortales" Ankreuzfeld einfügen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#57]
Bitte im Untersuchungsantrag Labor je ein Feld "Vollblut/Serum - postmortal" und "EDTA-Plasma - postmortal" mit denselben Funktionen wie "prämortal" einfügen

![image](https://cloud.githubusercontent.com/assets/22314271/20594856/04e177a2-b238-11e6-8234-efc10c4967d9.png)

**Comment by chrbusch** [comment]
Erledigt, bitte testen

![bildschirmfoto 2016-12-01 um 09 35 16](https://cloud.githubusercontent.com/assets/1241899/20786936/7cbaa76e-b7a9-11e6-87b3-b5f39fbbf668.JPG)

**Comment by Toelk-A** [comment]
"prämortal" und "postmortal" bitte ausschreiben

**Comment by chrbusch** [comment]
Erl.
