### ISSUE TITLE
GBMV Bugfix/ Prozesschritt Freigabeprotokoll fehlt

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#570]
Prozesschritt Freigabeprotokoll OG fehlt (pkb 97)

![image](https://user-images.githubusercontent.com/22314271/64094640-a6c31980-cd5c-11e9-875b-5695d4927842.png)

![image](https://user-images.githubusercontent.com/22314271/64094694-d3773100-cd5c-11e9-8e83-d23ad67d6f09.png)

**Comment by chrbusch** [comment]
Erl.
