### ISSUE TITLE
GBMV/ Abrng. Spaltlampenbefund / Transplantat ID 4831

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#571]
Folgendes Transplantat wird nicht auf der Abrechnung Spaltlampenbefund abgebildet. Bitte prüfen

![image](https://user-images.githubusercontent.com/22314271/64107180-2f03e780-cd7a-11e9-97bc-8f069adafa8c.png)

![image](https://user-images.githubusercontent.com/22314271/64107125-0c71ce80-cd7a-11e9-8377-dffc8e9c9d57.png)

**Comment by chrbusch** [comment]
Ausdr. vereinbart wurde, dass bei der Abrng. nur Befunde von "SCP" werden sollen; bei diesem, unr nur diesem Fall, steht dort aber "WIS".
Kein Bugfix!

**Comment by Toelk-A** [comment]
in Ordnung Danke
