### ISSUE TITLE
Programmierung Dienstplan

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#572]
Heute habe ich den Dienstplan für Oktober erstellen lassen:

Warum werden Wünsche (SCD Wunsch RBD 26.10.19 nicht mehr übernommen?)

Herr Schweder wurde für den 18.10 eingesetzt,obwohl er an dem Wochenende garnicht verfügbar ist.

Dies bitte dringendst kontrollieren!

**Comment by chrbusch** [comment]
kein Programmierfehler!

**Comment by Toelk-A** [comment]
Nach Neuanlage des Dienstplanes ihrerseits:

Herr Schweder hat jetzt 2 Wochenenden hintereinander Dienst + WE und Wochentagsdienst Dienst

![bu](https://user-images.githubusercontent.com/22314271/64121186-62586d80-cd9e-11e9-9623-af5ba1a32086.jpg)

**Comment by chrbusch** [comment]
Schweder hat Mitte Okt. WE-Dienst, weil er "dran" ist; und danach,weil er es ausdr. wünscht.
Es wurde vereinbart, solche seltenen Spezialfälle manuel zu ändern.
Kein Bugfix

**Comment by Toelk-A** [comment]
und wie erklären Sie den Donnerstag? vor dem wochenende? das bringt usn eldier nciht weiter... bitte rufen Sie mich zurück

**Comment by chrbusch** [comment]
Donn., weil er den Freitag nicht erfasst hat als Wunsch

**Comment by chrbusch** [comment]
Ich bin der Meinung, dass wir RBD-Wünsche nicht f. Sa+So zulassen sollten und bei Freitag nach Info an den Anwender Sa+So mitbuchen. Aufwand 15 Minuten

**Comment by Toelk-A** [comment]
nein
