### ISSUE TITLE
GBMV/ Farbänderung der Beschriftung Herstelletiketten

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#574]
Hallo Dr. Busch,

ich habe hier einmal ein Bild der Herstelletiketten für CS. 
Die gelb markierten Bereiche hätten wir gern in einem klaren grün, also alles was auch schon in fett ist, zusätzlich noch farblich markiert.

(Ich habe jetzt nicht alles markiert sondern nur 2 Beispiele)

![Herstelletiketten](https://user-images.githubusercontent.com/22314271/64115196-4e593f80-cd8f-11e9-9dcc-040640303cb5.jpg)

**Comment by Toelk-A** [comment]
Haben Sie hier etwas programmiert? warum bin ich assigned?

**Comment by chrbusch** [comment]
Ich habe Sie assigned weil ich jeden Überblick verloren habe, woran ich arbeiten soll.
Künftig bitte die regel einhalten, dass ich an ALLEMN, was mir assigned ist, auch arbeiten soll.
-
Die Schrift ist nun in den zuvor nur fetten Bereichen auch grün, bitte testen.

**Comment by Toelk-A** [comment]
Wie oben beschrieben:

Die Richtung stimmt, nur brauchen wir # ausschließlich die Aufkleber für CS in grün, der Rest darf schwarz bleiben. 
So wollen wir eine bessere Unterscheidung der beiden Seiten auf einen Blick erreichen.


![cd](https://user-images.githubusercontent.com/22314271/64176120-06a0e980-ce5d-11e9-8e8a-60257ddded28.jpg)

**Comment by chrbusch** [comment]
Bitte jetzt erneut testen
