### ISSUE TITLE
Personalmodul Überstundenbericht Napieralski

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#576]
Können Sie bitte die Auszahlung + Summen überprüfen? Hier scheint etwas nciht zu stimmen

![image](https://user-images.githubusercontent.com/22314271/64244174-ddd62e00-cf08-11e9-9403-df126883dd5a.png)

**Comment by chrbusch** [comment]
Bitte lassen Sie mich nicht raten - welche der vielen Zahlen ist Ihrer Meinung nach falsch?

**Comment by Toelk-A** [comment]
wie telefonisch besprochen kann Summe der geleisteten Stunden nicht kleiner sein als die Auszahlung der selbigen Stunden

**Comment by chrbusch** [comment]
Bei mir sind die neg. Zahlen verschwunden, kurz nachdem wir tel. hatten.
Ich vermute, Sie haben den zuvor vergessenen "Steueroptimierungsbutton" geklickt?
Ist dies damit erledigt? Oder müssen wir die Aktion dieses Buttons automatisieren?

**Comment by Toelk-A** [comment]
Das Problem habe ich dann gestern selber gelöst.
Bitte Zusatzabbildungen rückgängig machen, diese waren ebenfalls nicht beauftragt (rote Markierung)

![image](https://user-images.githubusercontent.com/22314271/64406561-6c21ef80-d082-11e9-8a93-30b729f8c288.png)

**Comment by chrbusch** [comment]
Diese Felder hatte ich gestern wg. des Problemes bei Nap. platziert, sind nun wieder unsichtbar

**Comment by Toelk-A** [comment]
danke
