### ISSUE TITLE
Personalmodul _ Bugfix da nicht beauftragt

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#577]
Urlaub / Urlaubswunsch / AZK / AZK-Wunsch     Schrift war vorher dick und in blau geschrieben.
War dadurch farblich besser abgesetzt und besser zu erkennen.
Wir haben keine Änderung der Schriftfarbe beauftragt. Bitte rückgängig machen
![schrift](https://user-images.githubusercontent.com/22314271/64402801-60c8c700-d076-11e9-9570-e92f6039efde.jpg)

**Comment by chrbusch** [comment]
M.E. erledigt

![image](https://user-images.githubusercontent.com/1241899/64405322-02541680-d07f-11e9-8a6c-34f361c28df2.jpeg)
