### ISSUE TITLE
MSG Entnahmebericht Todesursache abbilden / Button Todesursache verschwunden

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#579]
Hallo Herr Busch, im Entnahmebericht MSG wird nicht mehr die Todesursache abgebildet bzw. der Button "Todesursache holen" ist verschwunden. Dies hat vorher funktioniert. Bitte Programmierung prüfen

Spender ID 9289
![image](https://user-images.githubusercontent.com/22314271/64487869-607c2780-d240-11e9-9808-3471118d523e.png)

**Comment by chrbusch** [comment]
Techn. Anm.: Button wird ausgeblendet, wenn
Length( SpdEntn.SpdGew.Spd::k_List_Dgn_Bezng_ICD_FallsTodesUrsache ) < 5
or 
_Pos( _SpdEntnahme_::d_EntBer_Besond_Abweich_Gefahr ; SpdEntn.SpdGew.Spd::k_List_Dgn_Bezng_ICD_FallsTodesUrsache )

**Comment by chrbusch** [comment]
Der Button wird (schon immer) nur gezeigt, wenn eine Dgn. als Todesursache; dies ist bei 9289 aber nicht der Fall

**Comment by Toelk-A** [comment]
Sie haben Recht!
