### ISSUE TITLE
Entnahmbericht OG und MSG nicht vorhanden

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#58]
In Spender 061016-0320-GNO-SCD  fehlen die Entnahmebericht

![image](https://cloud.githubusercontent.com/assets/22314271/20595803/bcc4774a-b23b-11e6-943d-dc43eda33de1.png)

**Comment by chrbusch** [comment]
Das ist ein sehr alter Datensatz; inzwischen ist es so, dass bei Auswahl eines neuen Gewebes ProzessSchritte addiert werden, nämlich der Entnahmebericht und die Laboruntersuchung.
In dme beiliegenden Bild erkennen Sie, dass mein heutiger Testspender mit all seinen immer vorhandenen ProzessSchritten um 9h13 angelegt; die beiden oben erwähnten PS aber erst um 9h16, weil ich da das Gewebe "OG" addiert habe.
Soll ich für ältere Datensätze dies automatisch nachholen?

![bildschirmfoto 2016-12-01 um 09 16 40](https://cloud.githubusercontent.com/assets/1241899/20786584/2bc3a43e-b7a7-11e6-8a4d-6f3ae6e13cb1.JPG)

**Comment by Toelk-A** [comment]
für alle Datensätze ab 01.10.2016

Danke

**Comment by chrbusch** [comment]
Bitte stichprobenartig prüfen, ob die Prozessschritte für den Entn.Bericht nun überall vorhanden sind
