### ISSUE TITLE
Personalmodul / Sollstunden Monat durch System nicht angelegt

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#580]
Mitarbeiterdetails Zimmermann ID 98

Arbeitsbeginn 12.08.2019

![image](https://user-images.githubusercontent.com/22314271/64514089-472fb580-d2ea-11e9-8631-d60d6aec2f7a.png)

Der August fehlt leider komtplett, sodass Ornella im persönlichen Kalender die geleisteten Stunden aufsummiert anstatt mit den Sollstunden gegenzurechnen...

![image](https://user-images.githubusercontent.com/22314271/64514048-2cf5d780-d2ea-11e9-99a6-3f27c56cef9c.png)

![image](https://user-images.githubusercontent.com/22314271/64514227-80682580-d2ea-11e9-8475-0de726d58b20.png)

**Comment by chrbusch** [comment]
Frau Zimmermann ist 2x als GTMV angelegt, daher kommt alles durcheinander:

![image](https://user-images.githubusercontent.com/1241899/64551607-ae268c00-d335-11e9-8a90-aa47532cff26.jpeg)

Bitte hierzu anrufen

**Comment by chrbusch** [comment]
Für den ersten Datensatz wurde kein "Letzter AT" eingetragen; der zweite gehört zu keinem Team, so kann das natürlich nicht klappen.

**Comment by chrbusch** [comment]
Ich korrigiere jetzt die Daten der beiden Zimmermanns und werfe manuell das Serverscript an, das die Tage anlegt

**Comment by chrbusch** [comment]
Oooops, so einfach ist das nicht! Für BEIDE Mitarb.-Datensätze wurden Arbeitszeiten dokumentiert!
![image](https://user-images.githubusercontent.com/1241899/64583534-a09eef80-d391-11e9-8652-53efd0242f3c.jpeg)

**Comment by chrbusch** [comment]
Bei Duplikation eines Mitarb. in Ornella muss der "vergangene "Datensatz UNBEDIngt auf "Login?=Nein" gesetzt werden, damit sich die Personen nich versehentlich falsch einloggt!

![image](https://user-images.githubusercontent.com/1241899/64583908-20798980-d393-11e9-948a-cf44d8c35d94.jpeg)

**Comment by chrbusch** [comment]
Weitere Kuriosität: Erst am 6.9. wurde der neue Datenbsatz für Frau Z. erstellt, und dann der "1. Arbeitstag" rückdatiert auf 12.8.2019.

![image](https://user-images.githubusercontent.com/1241899/64584237-3b003280-d394-11e9-86cf-91bdd82fa07c.jpeg)

**Comment by Toelk-A** [comment]
Hallo Herr Busch,

mir wäre es lieb wenn wir zukünftig **zusammen** an einem Ticket arbeiten. Meine Arbeitszeiten sidn grob von 08:00- 16:30Uhr. Ich bin Abends nicht mehr erreichbar und kann nicht auf Ihre Ideen / Fragen reagieren. Ich bitte Sie hierzu zukünftig NICHT alleine weiterzuarbeiten, da die eigentliche Aufgabe im Vorderraum steht und nicht wie oft der MA im System angelegt ist noch, dass Sie irgendwelche Stunden korrigieren sollen.

Der Auftrag war die AugustSOLLstunden ab 12.08. nachzuprogrammieren, da diese aus irgend einem Grund nicht vorhanden sind. Mehr soll nicht getan werden. es spielt keine Rolle ob der MA 2 oder 5 mal im System ist. Fakt ist wir können die Stunden dokumentieren, allerdings stimmt das AZK nicht, da die SOLLSTUNDEN fehlen.

**Comment by Toelk-A** [comment]
Sollstunden beim Mitarabeiter ZIP sind noch immer nicht vorhanden im August

![image](https://user-images.githubusercontent.com/22314271/64590300-8c65ed00-d3a7-11e9-9505-3f0fc9541653.png)

**Comment by chrbusch** [comment]
Im August gab es den Datensatz mit ID=98 für Frau Zimmermann noch gar nicht!
Und das System legt nie MitarbeiterMONATE an für den Zeitpunkt vor Erstellung eines Datensatzes.
Ich habe den August für ID 98 nun manuell angelegt un des werden 8 SollStd angezeigt

![image](https://user-images.githubusercontent.com/1241899/64605385-4cf9c980-d3c4-11e9-864a-42a1f69399f1.jpeg)
