### ISSUE TITLE
GTMV/ Export mobiles Entnahmeteam

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#582]
1) Wir benötigen einen neuen Export unter folgendem Menüpunkt:

![image](https://user-images.githubusercontent.com/22314271/64936248-3b497380-d855-11e9-8040-2bc6589f8e66.png)

2) ausgeladen werden sollen die folgenden Felder als Exceldatei:

[Ausladung mob Entanahmeteam.xlsx](https://github.com/chrbusch/GTM-V/files/3614905/Ausladung.mob.Entanahmeteam.xlsx)

**Comment by chrbusch** [comment]
Ich vermute, der Export soll für einen bestimmten Zeitbereich geschehen - soll dieser frei wählbar sein?
Welches Datum ist für die Suche relevant, "Entnahme am"?

**Comment by chrbusch** [comment]
Neuer Export kann getestet werden.

![image](https://user-images.githubusercontent.com/1241899/64939717-34752d80-d862-11e9-8e38-29b49c384fcd.jpeg)

**Comment by Toelk-A** [comment]
in Prüfung

**Comment by chrbusch** [comment]
Bitte auch die Frage bezgl. Suchkriterien beantworten.
Zur Zeit suche in EntnahmeDatum im frei wählbaren Zeitbereich

**Comment by Toelk-A** [comment]
Ausladung soweit in Ordnung, bitte noch gelb markierte Spalte hinzufügen

![image](https://user-images.githubusercontent.com/22314271/65137080-febe7900-da08-11e9-9fe7-35d970dacfe8.png)

**Comment by chrbusch** [comment]
Ist als jetzt 3 Spalte addiert.

(Techn. Anm.: Das ist der ExportBefehl in Script 
"EinwillGespr11.ExportMET im Zeitbereich <149>/ #582")
