### ISSUE TITLE
GTMV/ MSG Abrechnung - Spender ID 4372

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#584]
Hallo Herr Prüter folgende Spender (aus 2018) taucht auf einmal in den MSG Abrechnungen auf:

![image](https://user-images.githubusercontent.com/22314271/65118507-75e51480-d9eb-11e9-97f3-7e15b6491700.png)

![image](https://user-images.githubusercontent.com/22314271/65118534-7d0c2280-d9eb-11e9-8242-2048215168bb.png)

![image](https://user-images.githubusercontent.com/22314271/65118617-9614d380-d9eb-11e9-8a08-341236dc6c29.png)

Können Sie bitte prüfen, ob die MSG Präparate bereits als abgerechnet markiert sind und warum sie auf einmal wieder auftauchen?

Vielen Dank

**Comment by mprueter** [comment]
Problem war eine doppelt erstellte MSG-Rechnung, die korrekterweise storniert wurde (ID: 1494; RngNr: 2018-0867). Beim Stornieren wird in den Präparaten der Bezug zur stornierten Rng aufgehoben, damit die Präparate erneut abgerechnet werden können. Hier gab es den Sonderfall, dass (aus welchen Gründen auch immer) im April 2018 auch eine zweite Rng. (korrekt und bezahlt) für die Präparate des betreffenden Spenders erstellt wurde (bei der offensichtlich kein Bezug zu dn Präparaten gesetzt wurde. Beim Stornieren der falschen Rng wurde diie rng-ID in den zugheörigen Präparaten entfernt und desewegen tauchte der Spender bei der MSG-Abrechnung wieder auf.

Ich habe die RngID in den betreffenden Präparaten nachgetragen. Der Spender aus 2018 erscheint nicht mehr in der Auswahl....
