### ISSUE TITLE
Bugfix/Transplantatliste Statuswechsel Originalliste weg

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#585]
Transplantatliste -> Statuswechsel von "Verschickt" auf "zu berechnen"

![image](https://user-images.githubusercontent.com/22314271/65247471-ba0e0d00-daf0-11e9-80d0-50d8db612405.png)

die komplette Liste ist weg und es wird nur die Hornhaut angezeigt bei der der Status gewechselt wurde. Dies war früher nicht so. Früher wurde automatisch wieder die Ausgangsliste angezeigt, nachdem der Status gewechselt wurde.

![image](https://user-images.githubusercontent.com/22314271/65247606-f5104080-daf0-11e9-965e-775860635e30.png)

**Comment by chrbusch** [comment]
Fixed -  bug fix!
