### ISSUE TITLE
Kontrolle selbstständiges Transplantat ID 91

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#586]
Das Transplantat mit der ID 91 wird aus irgendeinem Grund auf "zu berechnen" gesetzt. Das Transplantat ist aus 2016 und kann also aktiv gar nicht in den Status "zu berechnen" gelangen. (dieser Statuswechsel wird auch nicht geloggt!!!!)

Am 18.09.2019 haben Frau Fischer uns ich das TX in den Status "nicht berechnen" gesetzt. Jetzt taucht das Transplantat wieder mit dem Status zu berechnen auf. Bitte dringendst prüfen

![image](https://user-images.githubusercontent.com/22314271/65248420-73b9ad80-daf2-11e9-8b0b-5e56a3b9bac6.png)

![image](https://user-images.githubusercontent.com/22314271/65248529-951a9980-daf2-11e9-86b0-c287f75cb940.png)

**Comment by chrbusch** [comment]
Tr. 91 ist der allererste Datensatz dieser Tabelle; ich kann aber auch im System keinen Hinweis finden, warum der Status selbsttätig wechselt. Wir müssen dies aufmerksam weiter beobachten.
Es gibt jedenfalls nur 2 Transplantate, die vor dem 1.7.2019 erstellt wurden und Status 48="zu berechnen" haben: IDs 91 und 993

**Comment by Toelk-A** [comment]
Es scheint, dass wir ein weiteres "selbsständiges Transplantat haben: ID 5054

befindet sich jetzt im Status "zu berechnen" wurde aber laut Statustabelle nie in den Status "zu berechnen" gesetzt. Bitte dringend prüfen hier gibt es anscheinend einen Bug

![image](https://user-images.githubusercontent.com/22314271/65301437-cc7f5980-db77-11e9-8448-077aae106ff9.png)

![image](https://user-images.githubusercontent.com/22314271/65301465-f59fea00-db77-11e9-9c55-47ad28e17c95.png)

**Comment by chrbusch** [comment]
Problem verstanden und behoben (bug fix)
