### ISSUE TITLE
BUGfix - Statusänderung - Spenderdetails - Gewebe

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#587]
zum Transplantat von heute morgen haben wir nun ein Statusproblem in den Spenderdetails

Spender ID 9402

Statusänderung Gewebe MSG auf "gewebespezifische Kontraindikation" -> Status bleibt "Planung" und ändert sich nciht 
![image](https://user-images.githubusercontent.com/22314271/65311761-5ab40980-db91-11e9-984f-7363495f704b.png)

**Comment by chrbusch** [comment]
bin dran und melde mich gleich

**Comment by chrbusch** [comment]
Erledigt, bug fix
