### ISSUE TITLE
!Wichtig!  Freigabe zum Einwilligungsgespräch durch ärztliches Personal

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#59]
Nachdem der Koordinator den Button "Koordinator ist fertig, Meldung an Ärzte" geklickt hat, soll er eine Rückmeldung von den Ärzten bekommen, dass er mit dem Einwilligungsgespräch weitermachen kann.
Hierfür benötigen wir einen Button für das ärztliche Personal - "Freigabe Einwilligungsgespräch“. Wird dieser Button vom ärztlichen Personal angeklickt, muss der zuständige Koordinator eine Mail erhalten, sodass er am Spendeprozess weiterarbeiten kann.

**Comment by chrbusch** [comment]
siehe neuen Button r.u. auf der SpdMaske

**Comment by Toelk-A** [comment]
Button nur für Ärzte sichtbar (das ist richtig), Mailinfo funktioniert ebenfalls, klickt man in "Wiedervorlagen" auf die Meldung wird man allerdings nicht zur Spende weitergeleitet

**Comment by Toelk-A** [comment]
![image](https://cloud.githubusercontent.com/assets/22314271/21043225/1eeb115c-bdf6-11e6-9b73-f6a17c11c0fc.png)

Problem besteht weiterhin, der Koordinator wird nicht zur Spendermeldung weitergeleitet

**Comment by chrbusch** [comment]
Problem gefunden und gelöst.
Es sollte jetzt auch bei den zuvor angelegten WVs zum Einwill.Gespräch funktionieren.

**Comment by Toelk-A** [comment]
Im Moment funktioniert der Mailverkehr nicht anbei der Fehler:

![image](https://cloud.githubusercontent.com/assets/22314271/21145157/7d3a3620-c14d-11e6-9edd-1ba7ab9e91e3.png)

**Comment by chrbusch** [comment]
Das Bild hat eine so schlechte Auflösung, dass ich die Schrift nicht lesen kann.
Können Sie dies bitte technisch anders lösen?
M.E. gibt es auch unter Windows eingebaute Befehle zum Erzeugen eines hoch aufgelösten Screenshots, ansonsten kostenfreie Tools dafür.

Funktioniert keine der Mailroutinen, oder nur einer nicht?

**Comment by chrbusch** [comment]
Ich habe jetzt eine andere Mailingmethode eingestellt, bitte damit testen

**Comment by Toelk-A** [comment]
mail funktioniert nicht 

![image](https://cloud.githubusercontent.com/assets/22314271/21220884/64cf9692-c2bb-11e6-9604-553d5a223314.png)

**Comment by Toelk-A** [comment]
heir nochmal die Fehler mit besserer Auflösung


![image](https://cloud.githubusercontent.com/assets/22314271/21223244/8b9758a4-c2c6-11e6-9974-61e5da492abf.png)

**Comment by chrbusch** [comment]
Meines Erachtens ist das jetzt erledigt, oder?
Dann bitte Ticket schliessen
