### ISSUE TITLE
GTMV/GBMV  Erstellung Kostenbeteiligung

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#592]
Beide Firmen müssen sich gegenseitig an Kosten beteiligen z.B. die monatliche Datenbankrechnung von CBU. Nach Rücksprache mit unserem Steuerbüro darf dies nicht in Form einer "Rechnung"erfolgen, sondern muss als "Kostenbeteiligung" ausgegeben werden.

Anbei ein Beispiel hierfür:

[Vorlage Kostenbeteiligung.pdf](https://github.com/chrbusch/GTM-V/files/3754101/Vorlage.Kostenbeteiligung.pdf)

Wir benötigen:

1) Neuer Button Kostenbeteiligung in den Adressen:

![image](https://user-images.githubusercontent.com/22314271/67263968-0068da00-f4aa-11e9-8e29-2715507885e6.png)

2) danach soll ähnlich dem "Rechnungsskript" gefragt werden welcher Mandant die Kostenbeteiligung stellt. Button für Rechnungsstellungsskript:

![image](https://user-images.githubusercontent.com/22314271/67264022-28f0d400-f4aa-11e9-8f3d-6b2b23fee4f4.png)

3) Die Kostenbeteiligungsmaske entsprechend des Mandanten und der Vorlage erstellen (siehe oben).

Bitte auf den Jahreswechsel achten, ab 2020 muss automatisch auch die "K-Nummer" in 2020 geändert werden.

**Comment by mprueter** [comment]
Das ist jetzt fertig. Die Nummer der Kostenbeteiligungen  beginnt immer mit "K" gefolgt vom Mandanten ("T" oder "B"), dem Jahr und der lfd. Nummer.

Bsp: KB2019-0004

Die Kostenbeteiligungen laufen unter der Art "Kostenbeteiligung" in der Tabelle Rechungen mit, was bedeutet, dass:

1. sie in der Liste der Rng erscheinen (können dort via Btn. ausgeblendet werden)
2. Zahlungen via Kontobewegungsliste zugeordnet werden können
3. die Stornofunktion genauso wie bei den normalen Rng funktioniert.

Die Nummer der Kaostenbeteiligungen habe ich in den Druckmasken mit "BelegNr." betitelt.

**Comment by Toelk-A** [comment]
Hallo Herr Prüter. Ich entferne das Komma selbst. Bitte noch den Rest nacharbeiten.

Vielen dank und ein schönes Wochenende.

[Kostenbeteiligung nacharbeiten.pdf](https://github.com/chrbusch/GTM-V/files/3771821/Kostenbeteiligung.nacharbeiten.pdf)

**Comment by Toelk-A** [comment]
Hallo Herr Prüter bitte Ticket bearbeiten. Danke

**Comment by mprueter** [comment]
Sieht jetzt aus wie gewünscht:

![Bildschirmfoto 2019-10-29 um 13 05 27](https://user-images.githubusercontent.com/3273572/67765623-e05a8d00-fa4c-11e9-90c0-da32f86ce081.png)

**Comment by Toelk-A** [comment]
danke
