### ISSUE TITLE
GTMV/ Zusatzprogrammierung Auditierung Einwilligungserklärung

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#593]
Prozesschrit Einwilligungserklärung
Abschnit IV Gesprächsergebnis

A) Bitte Eingabefeld Gesprächsverlauf/Protokoll um die Hälfte verkleinern (rote Markierung)

B) Bitte Zusatzeingabefeld anlegen "Anmerkungen Audit" (blaue Markierung "A)

C) Bitte digitale Unterschrift des Auditors anlegen (hellgrün)

D) Bitte Liste erstellen "auditierte Einwilligungserklärungen". Regel: wenn im Feld Anmerkungen Audit Text dokumentiert ist, dann diesen Spender bitte in der Liste abbilden

E) Liste Button  "Auditierte Einwilligungsgespräche"

![image](https://user-images.githubusercontent.com/22314271/67390241-8b2a0180-f59c-11e9-9a22-ac073c5779a3.png)

![image](https://user-images.githubusercontent.com/22314271/67389706-6c773b00-f59b-11e9-8c82-35f33ab84c4b.png)

**Comment by chrbusch** [comment]
Bitte neue 3 Felder prüfen

![image](https://user-images.githubusercontent.com/1241899/67396134-57080e00-f5a7-11e9-89c3-23fc8aa1e906.jpeg)

**Comment by chrbusch** [comment]
Button "auditierte Einwilligungserklärungen": Dabei muss m.E. die Abfrage eines Zeitbereiches hinzu, sonst wird die Liste ja schnell unhandlich lang, oder?
Da wir dies fertig haben, dupliziere ich ein entspr. Script und modifiziere es

**Comment by chrbusch** [comment]
Try now…

![image](https://user-images.githubusercontent.com/1241899/67397580-a8b19800-f5a9-11e9-8ab2-bed45c4a170f.jpeg)

**Comment by Toelk-A** [comment]
sieht gut aus!

**Comment by Toelk-A** [comment]
wir werden ab morgen testen. Die PDFs "Einwilligungserklärung" sind hiervon aber nicht betroffen richtig? Also das Audit wird nicht im PDF Spenderakte agebildet, muss allerdings nach Freigabe durch die Ärzte in dem "Schreibschutz PDF" sichtbar bleiben.

**Comment by chrbusch** [comment]
"Die PDFs "Einwilligungserklärung" sind hiervon aber nicht betroffen richtig?"
Nein, leider falsch; wir haben ja die Maske verändert, und die entspricht auch dem Druckbild.
Ich kann aber einzelne Objekte vom Druck ausschliessen. Dann bleibt u.U. eine Lücke dort, wo jetzt die neuen Felder sind.
PDF-Erstellung ist aber aus Sicht von FileMaker auch ein DRUCK, so dass die Felder dann auch im PDF weg wären. Hier muss ich noch einmal nachdenken.

**Comment by Toelk-A** [comment]
### Ich kann aber einzelne Objekte vom Druck ausschliessen. Dann bleibt u.U. eine Lücke dort, wo jetzt die neuen Felder sind.

also bitte das Audit auf keinen Fall mitdrucken

### PDF-Erstellung ist aber aus Sicht von FileMaker auch ein DRUCK, so dass die Felder dann auch im PDF weg wären. Hier muss ich noch einmal nachdenken.

ja bitte. Vielleicht hat Herr Prüter hierzu auch eine Idee?

**Comment by chrbusch** [comment]
Erst einmal erledigt; ggfs. später "schöner" machen

Techn.Anm.: Im Script Gen01… wird ober $ViewOnly=TRUE gesetzt, wenn das Dokument frei gegeben ist.
Dann wird nur ein PDF geöffnet und nicht das Eingabelayout gezeigt.
Dabei wird vorher $$ShowExtras=1 und danach wieder =0 gesetzt; die Objekte des Audit werden gezeigt wenn $$ShowExtras=1; sie sollen NICHT mit in die Spd-Akte!
