### ISSUE TITLE
GBMV/ Gewebeanforderung Details - Storno - anderes Fenster öffnet sich

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#597]
Hallo Herr Busch, manchmal müssen Gewebeanforderungen storniert werden.

![image](https://user-images.githubusercontent.com/22314271/67617870-e4d23c00-f7e7-11e9-8830-822b505e9f49.png)

Klicke ich wie hier gelb markiert auf "bestellt" um den Status auf "Storno" zu wechseln

![image](https://user-images.githubusercontent.com/22314271/67617880-fc112980-f7e7-11e9-8a81-7b5427b63cc0.png)

storniert Ornella die Anforderung springt allerdings in eine völlig andere Anforderung hinein:

![image](https://user-images.githubusercontent.com/22314271/67617891-1f3bd900-f7e8-11e9-97e5-1d8bd186a7fb.png)

Bitte Programmierung prüfen. Es soll nach der Storno logischer Weise die selbe Gewebeanforderung geöffnet bleiben.

**Comment by chrbusch** [comment]
Natürlich soll hier dieselbe Anforderung sichtbar bleiben, aber:
Ich habe dies mit genau derselben GewAnfordPos durchgespielt und alles lief perfekt; geht das bei Ihnen immer schief oder manchmal?
Ggfs. Montag per TeamViewer durchspielen.

**Comment by Toelk-A** [comment]
bei uns geht das IMMER schief. wiederholbarer Fehler

**Comment by chrbusch** [comment]
Ist das jetzt erledigt?
