### ISSUE TITLE
GBMV/ Statuswechsel Transplantae in Transplantat-Auswahl + Allokation

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#598]
nachdem der Status von "Sperre" auf in Herstellung gewechselt wird, springt Ornella automatisch in einen anderen Patientin (der Patient der zuvor eine Hornhaut allokiert bekommen hat). 

Dies ist gefährlich da Doppelallokationen möglich sind.

Bitte auch hier Programmierung prüfen

![image](https://user-images.githubusercontent.com/22314271/67617925-a25d2f00-f7e8-11e9-8a8b-c8759f6a7e4c.png)

![image](https://user-images.githubusercontent.com/22314271/67617935-b012b480-f7e8-11e9-9920-79d121c1b2c0.png)

Patienetnwechsel durch Statuswechsel Transplantat
![image](https://user-images.githubusercontent.com/22314271/67617951-d89aae80-f7e8-11e9-9d3d-588b4d150d5f.png)

Statuswechsel Transplantat war erfolgreich

**Comment by chrbusch** [comment]
Ich denke nicht, dass hier ein Programmierfehler vorliegt.
Wenn Sie nur die Transplantate im Status Sperre anzeigen, und dann einem davon einen anderen Status geben, fliegt dieses natürlich aus der Anzeige heraus - es ist ja nicht mehr auf "Sperre".
Und die Datenbank zeigt dann einen der in der Fundmenge zu "Sperre" verbleibenden Datensätze.
Vllt. verstehe ich aber auch Ihr Problem falsch, bin nicht sicher!
Wir sollten tel. besprechen und ggfs. schaue ich Ihnen per TeamViewer über die Schulter…

**Comment by Toelk-A** [comment]
es geht nicht um das Transplantat sondern darum, dass nach Statusänderung des Transplantates der vorherige Patient abgebildet wird, bei dem zuletzt ein TX allokiert wurde. 

wiederholbarer fehler dringendst prüfung!

**Comment by chrbusch** [comment]
..klappt das jetzt korrekt?
