### ISSUE TITLE
Entscheidungsbaum Spendermeldung bis Allokation

### ISSUE THREAD

**Issue by chrbusch** [chrbusch/GTM-V#6]
In der SpdMeldung wird entschieden, ob der Spender geeignet ist für Organ- u/o Gewebentnahme; sonst Abbruch. Das ist fertig.
Aber wer entscheidet wo und wann, was genau entnommen wird?
Es gibt eine Tabelle "GewebeArt" mit 5 werten {OG; KVG; MSG; Amnion; Femur}; dazu gehören jeweils etliche PräparateArten, zB ist "Arteria femoralis sin." eine der 31 PräarateArten zu KVG.

Ich stelle mir das so nun vor: An der richtigen Stelle im Prozess (die ich eben noch nicht kenne) klickt der Entscheider 1 bis 5 GewebeArten an. Zu jeder davon werden irgendwann 1 bis N Präparate entnommen und in der Datenbank ausgewählt. Dadurch laufen die entspr. Teilprozesse los.

Und verstehe ich richtig, dass wir dann einen Herstellungs-Ablauf pro Präparat brauchen?

**Comment by Nitschke-FP** [comment]
der erste Schritt bei der Erfassung der Spendendaten muss sein, den Spender zu Klassifizieren in einen postmortalen Spender oder in einen Lebendspender. Dieses wird entschieden durch die Dokumentation des Todesdatums und die Todeszeit.
Die zu entnehmenden Gewebe werden eingeteilt in ophthalmologische Gewebe (OG), kardiovaskuläre Gewebe (KVG), muskuloskelettale Gewebe (MSG) und Membrangewebe (MG).
Lebendspender können KVG (und zwar hier nur das Herz), MSG ( hier nur der Femurkopf) und MG (hier Amnion und ggf. zukünftig Perikard). Tote Spender können logischerweise alles spenden, das Amnion kann hier aus logistischen Gründen entfallen,, auch wenn es theoretisch möglich ist.
Der nächste Filter wäre die Akzeptanz des Spendenalters durch die kooperierenden Banken für die einzelnen Gewebe. Dieser wird heute erstellt und übersendet.
Hieraus resultierend soll eine Vorgabe der zu entnehmenden Gewebe erstellt werden. Im Rahmen der Entnahme kann dann hier eine weitere Einschränkung, aufgrund von vorher nicht bekannten pathologischen Veränderungen der Gewebe, der zu entnehmenden Gewebepräparate sich ergeben.
Die Dann am Ende der Entnahme im Entnahmeprotokoll dokumentierten Gewebe sind die Basis für die Herstellungsprozesse in der Bank.
