### ISSUE TITLE
Reiter "Gewebe/Präparate/Transplantate" Einfügen Button " Alle Etiketten drucken" 

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#60]
Können wir einen "MSG-SET Etiketten drucken" Butto einfügen, bei dem alle Etiketten der zu entnehmenden Knochenpräparate gedruckt werden? Ansonsten muss jedes Präparat einzeln zum Drucken angeklickt werden.

 
![image](https://cloud.githubusercontent.com/assets/22314271/21043324/9c984ee4-bdf6-11e6-97d8-e2f803f1be05.png)

**Comment by chrbusch** [comment]
Das geht recht einfach.
Ist denn der Druck für ein einzelnes Etikett jetzt genau so, wie es sein soll?

**Comment by chrbusch** [comment]
Es ist jetzt ein breiter Button zum Drucken aller Etiketten unter dem gezeigten Portal, bitte testen und Rückmeldung

**Comment by Toelk-A** [comment]
für KVG benötigen wir keine Etiketten nur MSG und OG

**Comment by chrbusch** [comment]
Erledigt

**Comment by Toelk-A** [comment]
Etikettendruck geprüft, funktioniert, ABER wir benötigen pro MSG-Set nur insgesamt 2 Aufkleber mit Entnahmedatum und Entnahmezeit, bitte ändern

**Comment by Toelk-A** [comment]
![image](https://cloud.githubusercontent.com/assets/22314271/21226270/008d07e0-c2d5-11e6-8128-c22e54c27f2e.png)

**Comment by chrbusch** [comment]
Das ist erledigt

**Comment by Toelk-A** [comment]
Bitte die "KVG Etiketten" entfernen. Wir benötigen nur Etiketten für OG und MSG.

**Comment by chrbusch** [comment]
Erl.
