### ISSUE TITLE
GTMV/ Gewebe abbilden

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#601]
Hallo Herrr Busch,

bitte zusätzlich Gewebe bei den Entnahmen abbilden -> siehe Screenshots

![image](https://user-images.githubusercontent.com/22314271/67775722-9f1fa880-fa5f-11e9-965a-1ce82f048c9c.png)

![image](https://user-images.githubusercontent.com/22314271/67775763-aba40100-fa5f-11e9-9368-ae45a8e7f603.png)

**Comment by chrbusch** [comment]
Done

![image](https://user-images.githubusercontent.com/1241899/67839627-5cf47680-faf4-11e9-8969-e80ef5bd35b4.jpeg)
