### ISSUE TITLE
GBMV/ Bugfix Prozesschritt Eingangskontrolle OG NIB kann keine Unterschrift setzen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#604]
Transplantatdetails, Prozesschritt Eingangskontrolle

NIB kann als VP keine Unterschrift setzen. Dies funktionierte vorher. Fehlermeldung anbei. Bitte Programmierung prüfen

<img width="1147" alt="Bildschirmfoto 2019-11-06 um 08 21 02" src="https://user-images.githubusercontent.com/22314271/68277982-b880b000-0070-11ea-899b-1bac36900f75.png">

**Comment by chrbusch** [comment]
Habe dies nach Tel. mit NIF gerade geändert, so das Rolle 10 für gBmv erforderlich; vorher war es Rolle 2 = Arzt gTmv
