### ISSUE TITLE
GTMV/ Prozesschritt "sehen" wird automatisch als PDF abgelegt. Bitte korrigieren

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#605]
Werden bereits freigegebene Dokument zum "lesen" als PDF geöffnet, so wird dieses PDF automatisch im Reiter "Dokum.+Status" abgelegt. Dies bitte korrigieren, da die PDF nur zum lesen, nicht zum drucken geöffnet wird (STRG+5)

![image](https://user-images.githubusercontent.com/22314271/68482870-bff3b500-023a-11ea-9632-06f577b2b7fa.png)

![image](https://user-images.githubusercontent.com/22314271/68482967-eb769f80-023a-11ea-874b-49f0b5078acd.png)

**Comment by chrbusch** [comment]
m.E. erledigt (bug fix), bitte testen

**Comment by mprueter** [comment]
War noch nicht ganz fertig. Das funktioniert jetzt aber. 

Im Script Ausgabe05BP. wurde "-noArchive" nur im lokalen Scriptparameter überprüft, nicht aber in $$Ausgabe_Options (dort wurde es übergeben)

**Comment by Toelk-A** [comment]
erledigt
