### ISSUE TITLE
BUGFIX Rufbereitschaftsplan

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#607]
1) Mitarbeiter Herstellung werden nicht abgebildet!

2) Frau Deuschle und Frau Reis gehören nicht zur Spalte VP§20b 

[RBD NOvember 2019.pdf](https://github.com/chrbusch/GTM-V/files/3839749/RBD.NOvember.2019.pdf)

**Comment by chrbusch** [comment]
Formelkorrektur (bugfix)
