### ISSUE TITLE
GBMV/ Jahreswechsel - Beginn Transplantat 2020-0001-GMV-CS/CD

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#616]
Hallo Dr Busch, können Sie bitte noch einmal überprüfen, ob am 01.01.2020 auch automatisch die Transplantate mit der bankinternen Nummer 2020-0001-GMV-XXXX beginnen? Zu Beginn diesen Jahres gab es massive Probleme und die Mitarbeiterinnen konnten nicht arbeiten....

Vielen Dank!

![image](https://user-images.githubusercontent.com/22314271/71179518-a2b9f980-2270-11ea-8a42-4a6c439668d5.png)

![image](https://user-images.githubusercontent.com/22314271/71179585-c3824f00-2270-11ea-8db3-d66d0cf62e4c.png)

**Comment by chrbusch** [comment]
Nach meiner Erinnerung gab es Problem nur, wenn der Spender nicht für das Jahr "gemeint" war, in dem die Spendermeldung einging; also etwa Eingang 31.12., 23h58; SpenderAnlage 1.1., 00:01
-
Vllt. beschreiben Sie einmal genau, wie es dann am Jahreswechsel gehandhabt werden soll.
Dieses Jahr bin ich außerdem voraussichtlich in Hamburg, so dass ich jederzeit eingreifen kann.

**Comment by chrbusch** [comment]
PS: Die Tabelle KennNr wird hier gar nicht benutzt!
Die SpenderKennNr ist ja 
DatumSpdMeldung-UhrzeitSpdMeldung-Region-Koordinator

**Comment by chrbusch** [comment]
Ich habe die Scripts geprüft, vor allem
"SpdTranspl01KN.Bank-int. KennNr setzen (SP=pk_SpdTranspl)/ "
Dort scheint alles OK; nach meiner Erinnerung haben wir das im Januar 2019 alles geklärt
