### ISSUE TITLE
Bugfix/ Personalmodul Mitarbeiter suchen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#617]
Frau Karnatz kann nicht im Personalmodul gefunden werden:

![image](https://user-images.githubusercontent.com/22314271/71660400-37c9f180-2d4b-11ea-9492-ef21e365d43b.png)

![image](https://user-images.githubusercontent.com/22314271/71660385-28e33f00-2d4b-11ea-996b-93e072f61e5d.png)

In den Userdetails ist sie angelegt, Log in erlaubt, Rolle im Personalmodul auch definiert.

![image](https://user-images.githubusercontent.com/22314271/71660477-795a9c80-2d4b-11ea-9ff8-b07dacb8311e.png)

Wir hatten vor längerem die Absprache, dass Mitarbeiter, obwohl sie nicht mehr im Unternehmen tätig sind, noch immer im Personalmodul auffindbar sein müssen. Dies funktioniert nun leider wieder nicht. Bitte Programmierung prüfen.

Danke

**Comment by chrbusch** [comment]
Ich denke, das funktioniert genau so, wie es besprochen wurde: Es wurde damals der zusätzliche Button "Aktive" programmiert.
Klicken Sie stattdessen auf "Alle", wird Frau Karnatz gefunden

![image](https://user-images.githubusercontent.com/1241899/71662938-9abf8680-2d53-11ea-8821-3030700252e2.jpeg)

**Comment by Toelk-A** [comment]
Wie Sie in meinen screenshots sehen könne, hatte ich garnicht die Auswahl zwischen "allen" und aktiven...

jetzt funktioniert es  jedenfalls :-) Danke

**Comment by chrbusch** [comment]
Nun, Ihr Screenshot zeigt den Dialog NACH erfolgter Suche; an dem ersten Dialog habe ich nichts geändert, der zeigt schon lange die Buttons "Aktive" und "Alle"
