### ISSUE TITLE
GTMV/ Optimierung Unerledigte Chatanforderungen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#618]
Hallo Herr Busch,

für die Liste /Tabelle "Unerledigte Chatanforderungen für..." im Ornella Hauptmenü Reiter Wiedervorlagen + Chat haben wir noch 2 Wünsche.

![image](https://user-images.githubusercontent.com/22314271/71667104-e7ab5900-2d63-11ea-9f6b-f4c0005b2b67.png)

Bitte fügen Sie 2 weitere Spalten ein:

1) Zusätzlich zum Text das zugehörige Bemerkungsfeld der Wiedervorlage.

2) Patientennamen abbilden, gerne auch direkt unter der Spenderkennummer.

![image](https://user-images.githubusercontent.com/22314271/71667133-07db1800-2d64-11ea-984d-c3f35a0fcaf4.png)

zu 1
![image](https://user-images.githubusercontent.com/22314271/71667195-4a045980-2d64-11ea-9471-5394c1944c6a.png)

**Comment by chrbusch** [comment]
Das Bem.-Feld ist nun vorhanden.
EINEN Patienten gibt es i.d.R. nicht; die Chat-Datensätze betreffen jeweils einen Spendern, dessen Gewebe, Präparate, Transplantate mehrere Empfänger haben können. Und oft auch (noch) gar keinen.
Wie sollen wir hier verfahren?

**Comment by Toelk-A** [comment]
### Das Bem.-Feld ist nun vorhanden.
Vielen Dank funktioniert. :-)

### EINEN Patienten gibt es i.d.R. nicht; die Chat-Datensätze betreffen jeweils einen Spendern,
Dr. Busch, Sie haben Recht! es handelt sich um den Spender, NICHT um den Patienten. Entschuldigen Sie die Verwirrungen meinerseits.

**Comment by chrbusch** [comment]
Ach so! Sollte jetzt vorhanden sein.
