### ISSUE TITLE
PDF - Hämodilution   Blutproben: wenn im Reiter "Blutproben" eingegeben bitte automatisch für dieselben Zeitpunkte 1 Hämodilution einfügen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#62]
Hallo Dr Busch, wenn wir die Blutproben in dem Reiter"Blutproben" eingetragen haben, wäre es gut diese automatisch in den Prozesschritt "Hämodilution" zu übernehmen, da wir sonst doppelte Eintragungen machen müssen und dies mehr Zeit kostet. Wenn es unterschiedliche Entnahmezeitpunkte gibt, muss natürlich für jeden Zeitpunkt eine separate Hämodilution ausgefüllt werden

**Comment by chrbusch** [comment]
Ich habe das mit Dr. N. besprochen und umgesetzt
Bitte testen, ob es jetzt so funktioniert, wie gewüscht.

**Comment by Toelk-A** [comment]
funktioniert leider nicht:
die Blutproben EDTA und Serum vom 17.12.16 um 12:34 tauchen nciht in derselben Hämodilution auf

![image](https://cloud.githubusercontent.com/assets/22314271/21638833/5e281ac8-d26d-11e6-9f6a-393b3281e0b2.png)

**Comment by Toelk-A** [comment]
Problem besteht weiterhin

**Comment by chrbusch** [comment]
ist m.E. erledigt, bitte testen

**Comment by Toelk-A** [comment]
Funktioniert leider noch nicht
ID1420

Entnahmezeitpunkt 23.01.17 06:00Uhr wurde 1x EDTA und 1x Serum abgefüllt. In der Hämodilution steht 0x Serum und 2x EDTA

![image](https://cloud.githubusercontent.com/assets/22314271/22543316/55a74bce-e930-11e6-9a2d-c1d06a99a805.png)

**Comment by chrbusch** [comment]
OK, da gab es noch eine Stelle im Script, die auf die Art des Materials schaut; bitte jetzt erneut testen

**Comment by Toelk-A** [comment]
ID 1420

nach wie vor selbes Problem
Blutprobe 24.01.2017 6:00

1xserum 1x EDTA in der Hämo tauchen wieder 2x serum 0x EDTA auf

![image](https://cloud.githubusercontent.com/assets/22314271/22596385/a52df4e4-ea2b-11e6-8ceb-d2a4a9197f4d.png)

**Comment by chrbusch** [comment]
Doch, bei Hämodil., die nach meiner Korrektur angelegt werden! Das habe ich gerade mit 1420 getestet.
Für die Übergangszeit habe ich nun die Anzahl-Felder oben editierbar gemacht; Sie können also hier die Anzahlen ändern.
Alle neu angelegten Hämodil. sollten aber OK sein.

**Comment by Toelk-A** [comment]
okay testen wir später, wenn wir neue Blutproben/Spender bekommen.
