### ISSUE TITLE
GTMV/ Übernahme Anzahl angelegter Blutproben in den Untersuchungsantrag

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#621]
Spenderdetails - Reiter Blutproben werden Blutproben angelegt

Prozessschritte - Untersuchungsantrag -> hier bitte übernehmen, aber Feld modifizierbar lassen

![image](https://user-images.githubusercontent.com/22314271/71983047-3a828600-3226-11ea-9415-c00a646080de.png)

**Comment by Toelk-A** [comment]
wie ist hier der Stand?

**Comment by chrbusch** [comment]
Mir ist nicht klar, was von dem obigen Text oben der Ist- und was der Soll-Zusatnd ist; bitte anrufen

**Comment by chrbusch** [comment]
m.E. ist das erledigt, bitte testen

**Comment by Toelk-A** [comment]
erledigt
