### ISSUE TITLE
Personalmodul - persönlicher Kalender - AZK Button für Supervisor einfügen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#623]
Wir haben für den 24.12. + 31.12. eine Sonderregelung geschaffen, die beinhaltet 100% Zuschlag. Da der 24.12. offiziell nicht als Feiertag deklariert ist, setzt Ornella automatisch "reguläre Arbeitszeit" - dies ist richtig. Die GF möchte allerdings an diesen beiden Tagen den Mitarbeitern ermöglichen Ihre Stunden auszahlen zu lassen. (dies ist bei der Stundenart "reguläre Arbeitszeit" nicht möglich und darf auch nicht sein)

Wir benötigen also einen Supervisorbutton, der erlaubt die geleistete Arbeitszeit auszahlen zu lassen und in steuerfrei + steuerpflichtig aufsplitten zu lassen (dies auch am besten über manuelle Eingabe).

Unsere Lohnauszahlung erfolgt am 15.01. Ich hoffe es ist möglich so kurzfristig noch die gewünschten Buttons + Eingaben zu programmieren.

![image](https://user-images.githubusercontent.com/22314271/72062902-fe5c2d80-32d8-11ea-8a17-9ba74d47edfc.png)

**Comment by chrbusch** [comment]
Leider ist bei mir "Land unter" weil zum Jahreswechsel meines Handelskunden Inventur haben und mich dringend brauchen. Ich versuche aber, diese Ticket heute abzuschliessen

**Comment by chrbusch** [comment]
2. AZK-Feld, das für Supervisor menuell beschreibbar ist

![image](https://user-images.githubusercontent.com/1241899/72240637-053eb500-35e5-11ea-8561-801995534537.jpeg)

Bitte testen, ob dies schon ausreicht
