### ISSUE TITLE
TransplantatStatus aufteilen in "Medizinisch" und "betriebswirtschaftlich"

### ISSUE THREAD

**Issue by chrbusch** [chrbusch/GTM-V#624]
√Erweiterung der Tabelle _Status_ um Kategorie "Tbw"
√Erweiterung  des Scripts für StatusWechsel um Kategorie "Tbw"

Welche Status gehören zur neuen Art Tbw? Sie sind dann nicht mehr verfügbar für den medizin. Status eines Transplantates
Bitte schreiben Sie die IDs hier in eine Antwort, z.B
36, 48, ...

![image](https://user-images.githubusercontent.com/1241899/73155867-469e8c80-40dc-11ea-9eb4-5bba87689e71.jpeg)

**Comment by chrbusch** [comment]
Auch in die Suchoptionen auf der Transpl.-Liste wurde das neue Feld gelegt, und das Suchscript erweitert

![image](https://user-images.githubusercontent.com/1241899/73156696-e0ffcf80-40de-11ea-802a-bd63e099fb32.jpeg)

**Comment by chrbusch** [comment]
Es gibt zahllose Stellen, an denen der medizin. Status autom. geändert wird; es muss gut durchdacht werden, wo hier der BW-Status stattdessen oder zusätzlich zu ändern ist.

**Comment by chrbusch** [comment]
Zur Zeit werden die Status bei allen Transplanataten mit Hilfe der Statuswechsel-Tabelle aufgeteilt in den BW-Status und den letzten verfügbaren medizin. Status - der bei alten Transplantaten oft fehlt.
Bitte ab 9h30 das Ergebnis anhand einiger Stichproben prüfen.

(Techn. Anm.: Alle Status wurden vor der Umrechnung durch einen Export gesicht)

**Comment by thiery-j** [comment]
Der Medizin. Status stimmt bei den überprüften Stichproben. Würde aber trotzdem vorschlagen, diesen nicht auf 30-32 stehen zu lassen, sonst tauchen alle diese Transplantate auch in der Spalte "Passende Transplantate" auf. Das ist für die wöchentliche Allokation etwas umständlich...

**Comment by thiery-j** [comment]
![Status_BW](https://user-images.githubusercontent.com/60341623/73249363-04954980-41b5-11ea-9c96-02b74b0a6537.PNG)
Auch wäre es für die Rechnungsstellung gut, wenn man direkt nach den Transplantaten suchen kann, die noch keinen BW-Status haben.
Und nachdem man in die Status-Kästchen geklickt hat, sollte es auch möglich sein, diese wieder zu löschen ohne einen anderen Status auswählen zu müssen.

**Comment by thiery-j** [comment]
Und, falls möglich, bitte auch in der Transplantat-Liste es ermöglichen, den BW-Status zu ändern (äquivalent zum med. Status)

**Comment by thiery-j** [comment]
Momentan ist es leider nicht möglich, Transplantate abzurechnen, obwohl BW-Status "48 zu berechnen" ist. Können Sie das bitte ändern?
![image](https://user-images.githubusercontent.com/60341623/73258988-1ed82300-41c7-11ea-9739-0687448aaf50.png)

**Comment by chrbusch** [comment]
Ich korrigiere dies alles ab ca. 15h
Bis dahin bitte VORSICHT

**Comment by chrbusch** [comment]
Vorschlag: Wenn ein Tr. auf Status "verschickt" gesetzt wird, folgt ein Dialog: 
BW-Status auf "zu berechnen" setzen?
Danach geht dann alles weitere automatisch!
Bitte hierzu nachdenken und dann einmal anrufen

**Comment by thiery-j** [comment]
Eine automatische Änderung des BW-Status bei Status med. "Verschickt" ist auf jeden Fall sinnvoll. Wir sprechen das noch mit der Buchhaltung ab und melden uns morgen Nachmittag

**Comment by Toelk-A** [comment]
### Eine automatische Änderung des BW-Status bei Status med. "Verschickt" ist auf jeden Fall sinnvoll. Wir sprechen das noch mit der Buchhaltung ab und melden uns morgen Nachmittag
-> dies bitte **NICHT** programmieren, "zu berechnen" muss immer manuell gesetzt werdeb, da Komplikationen auftreten können und die Buchhaltung anschließend doppelte Arbeit mit Stornorechnungen hat.

### 2) Status zu berechen
wir benötigen im betriebswirtschaftlichen Status dringendst die Möglichkeit, den Status direkt in der Transplantatliste "zu berechnen" zu ändern. Im Moment ist dies ziemlich userunfreundlich geregelt, da sich in jedes einzelne Transplantat reingeklickt werden muss um dem BW Status zu ändern. "der rote Pfeil zeigt, wo der Statuswechsel bzw. die Werteliste "bw-Status" eingebelendet werden soll)

Bitte dringendst umsetzen

![image](https://user-images.githubusercontent.com/22314271/74509504-f27c1080-4f01-11ea-9b58-7e344a6c6a0d.png)

**Comment by chrbusch** [comment]
Das BW-Feld kann nun direkt in der Liste angeklickt werden.

**Comment by Toelk-A** [comment]
erledigt
