### ISSUE TITLE
Filter erstellen - Gewebespenden für Qualitätssicherung 

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#625]
### Beispiel Spender ID 10829

seit gestern haben wir Gewebespenden im System, die aufgrund von Qualitätssicherungsprozessen durchgeführt werden, aber nicht transplantantiert werden können. Damit sämtliche Statistiken nicht verfälscht werden, müsste überlegt werden, wie diese Spender gefiltert werden können.

Mein Vorschlag:

ähnlich dem Ja/Nein Button "Echter Fall" in den Spenderdetails könnte ein QS Button Ja/nein erstellt werden und somit gefiltert werden? Beides als unechte Fälle zudefinieren scheint mir keine saubere Trennung.

![image](https://user-images.githubusercontent.com/22314271/74510060-3d4a5800-4f03-11ea-9dd8-a0f6f3afef3a.png)

**Comment by chrbusch** [comment]
Erfolgt diese Unterscheidung immer auf der Ebene SPENDER, oder könnte auch zB das OG für Transplantationen genutzt, das MSG aber für QS?

**Comment by chrbusch** [comment]
Ich schlage vor: "Echter Fall" wird zZ überall so genutzt, dass in Statistiken nur Spender mit dem Wert = 1 benutzt werden.
Wir könnten einfach den Wert 2 definieren als "QS"; das wäre eine saubere Trennung, die sehr wenig Arbeit macht!

**Comment by chrbusch** [comment]
Wie tel. besprochen: Rechts unten auf der Spendermaske its nun ein bearbeitbares Feld "Klasse Spd."; es wird automatisch auf 1=echter Spender gesetzt, kann aber manuell verändert werden.
(Soll das jeder dürfen?)
Statistiken aller Art beachten nur Fälle mit Klasse = 1

![image](https://user-images.githubusercontent.com/1241899/74524546-86a8a080-4f1f-11ea-9a25-feeebbb23338.jpeg)

Das Feld wird nun auch als Klartext auf der SpdListe angezeigt:
![image](https://user-images.githubusercontent.com/1241899/74525162-c754e980-4f20-11ea-905e-3c5fbd14e4ca.jpeg)

**Comment by Toelk-A** [comment]
erledigt, danke!
