### ISSUE TITLE
GBMV/ Herstellungsliste bitte nach ID ordnen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#627]
Bitte jüngste ID an erster Position anzeigen. Danke

![image](https://user-images.githubusercontent.com/22314271/74640301-98808280-516f-11ea-936d-bfe90a0b9a2c.png)

**Comment by chrbusch** [comment]
Dies ist nicht so einfach, wie man meinen könnte; bitte anrufen, um die Optionen zu besprechen

**Comment by Toelk-A** [comment]
erledigt danke
