### ISSUE TITLE
GTMV/ Einwilligungsgespräch / Gesprächsergebnis "schriftlich" wird nicht übernommen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#629]
Spenderdetails / Prozessschritt Einwill. Gespräch / Abschnitt Gesprächsergebnis

Beim Erstellen des Angehörigengespräches wird nach der Entscheidung (Klick auf Zustimmung/Ablehnung) die Basis „schriftlich“ nicht übernommen.

-	Es ist egal ob es sich um eine Generelle/Eingeschränkte Zustimmung oder Ablehnung handelt.
-	Die anderen Basen werden übernommen.
-	Die Basis „Schriftlich“ ist anwählbar – wird auch mit „OK“ bestätigt (also das Auswahlfenster schließt sich) – Ornella setzt dort dann aber keinen Punkt.

![image](https://user-images.githubusercontent.com/22314271/74649678-50b62700-5180-11ea-9054-8b49429f27fa.png)

**Comment by chrbusch** [comment]
Fehler erkannt und behoben; dadurch auch automatisch Korrektur aller alten Datensätze (bugfix)

**Comment by Toelk-A** [comment]
Die externen ANG-Gespräche werden immer noch nicht ausgeladen.

**Comment by Toelk-A** [comment]
Bitt o.g. Kommentar ignorieren.... Ticket ist erledigt
