### ISSUE TITLE
Sterbezeit aus Spendemerldung wird nicht in PDF übertragen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#63]
Die Sterbezeit ist in Ornella dokumentiert, fehlt allerdings in der PDF Ausgabe

![image](https://cloud.githubusercontent.com/assets/22314271/21221095/6358a118-c2bc-11e6-93fc-21d8db1ef96a.png)

**Comment by chrbusch** [comment]
Ich denke, dies ist seit langem erledigt, oder?

**Comment by Toelk-A** [comment]
erledigt
