### ISSUE TITLE
Mobile APP GTMV- Fehlermeldung

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#630]
Hallo Herr Dr. Busch wollte heute die App öffnen und habe folgende Fehlermeldung im Büro erhalten. Was kann ich tun um die app wieder zu nutzen?

![Ornello GO! APP Fehlermeldung](https://user-images.githubusercontent.com/22314271/74659327-66cde280-5194-11ea-84b1-46c798198273.jpg)

**Comment by chrbusch** [comment]
..dies haben wir per Email geklärt: Es fehlen "mobile Lizenzen", die man wegen ihres hohen Preises nur erwerben sollte, wenn dieses Problem dringlich ist.
