### ISSUE TITLE
GBMV/ Personalmodul Mitarbeiterleiste Koordinatoren Leipzig abbilden

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#633]
Bitte die Koordinatoren aus Leipzig in die Mitarbeiterliste einfügen

![image](https://user-images.githubusercontent.com/22314271/74909607-f522ae00-53b8-11ea-8907-563cf9d73bc1.png)

![image](https://user-images.githubusercontent.com/22314271/74909699-2602e300-53b9-11ea-99b2-b6bb929a80cd.png)

![image](https://user-images.githubusercontent.com/22314271/74909772-4894fc00-53b9-11ea-9121-5bb2a0f35423.png)

**Comment by chrbusch** [comment]
Sie können selbst bei beliebigen Mitarb. das Feld "RBD-Planung?" auf den Wert 1 setzen, dann bitte testen ob noch etwas fehlt.
![image](https://user-images.githubusercontent.com/1241899/74918178-ff4ca880-53c8-11ea-9157-3be2cd6b8b29.jpeg)

**Comment by Toelk-A** [comment]
Mitarbeiter Leipzig sind momentan eien Asunahme für RBD, da wir für leipzig derzeit die Dienstpläne manuell erstellen. Werden Sie, wie von Ihnen gezeigt, mit der "1" markiert dann werden sie auch werktags für Dienste eingeteilt (was nach jetzigem Stand noch nicht geplant ist). Gibt es eine andere Möglichkeit die Leipziger in der Mitarbeiterliste abzubilden?

**Comment by chrbusch** [comment]
erledigt

**Comment by Toelk-A** [comment]
ewrledigt
