### ISSUE TITLE
GTMV/ Optimierung aktueller Status Spendermeldung in APP

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#638]
Beispiel Spender ID 10902

### 1) Status des Spenders in App abbilden
-> In Ornella Status "Finale Indikationsstellung" ( Zustimmung zur Spende) -> rote Markierung unten rechts

![image](https://user-images.githubusercontent.com/22314271/75010293-14830f00-547d-11ea-8b90-d8a4ba77c4ab.png)

in APP "Liste" bitte folgendermaßen abbilden:
![image](https://user-images.githubusercontent.com/22314271/75010516-a3902700-547d-11ea-85ad-a419d30f8467.png)

**Comment by chrbusch** [comment]
Erl.

**Comment by Toelk-A** [comment]
Status wird nicht abgebildet ( auch nach Klick auf Button "Update")

**Comment by chrbusch** [comment]
Sollte jetzt alle 5 Minuten (vom ServerScript "OP5Min") aktualisiert werden

**Comment by Toelk-A** [comment]
1) Status wird jetzt, abgebildet!! -Danke! (gelb markiert)

2) Liste scheint im Moment nicht aktuell zu sein (nur 1 Spender anstatt mind. 2 vorhanden) (rote Markierung)

3) Es werden seit heute zusätzlich Diagnosen abgebildet (dies bitte nur im Details tun - da sehr unübersichtlich in der Liste) (blaue Markierung)

![image](https://user-images.githubusercontent.com/22314271/75089150-41572500-5556-11ea-8676-65b742658189.png)

**Comment by chrbusch** [comment]
Dgn kommen nur noch auf der Detailansicht

**Comment by chrbusch** [comment]
Bei mir sind 4 Spender

**Comment by chrbusch** [comment]
Wegen der z.T. vielen Diagnosen habe ich für diese einen Extrareiter erstellt, soll ich das so lassen?

![image](https://user-images.githubusercontent.com/1241899/75110260-67e78f80-562c-11ea-9eca-ccae3b5318b5.jpeg)

**Comment by Toelk-A** [comment]
nein, dies war nicht beauftragt

**Comment by chrbusch** [comment]
Da dies nun wie besprochen nun als zus. Option vorhanden ist, schlage ich vor, dieses Ticket zu schliessen

**Comment by Toelk-A** [comment]
Status wird wie oben beschrieben übernommen. Ticket wird geschlossen
