### ISSUE TITLE
Filter Spenderliste

### ISSUE THREAD

**Issue by Nitschke-FP** [chrbusch/GTM-V#64]
Filter Spenderliste: hier hätten wir noch gern aktuelle Woche, vorherige Woche, aktueller Monat, vorheriger Monat, laufendes Jahr.
10m, 60m und 3s wird nicht benötigt.
Desweiteren wäre ein Filter gut, wo die archivierten Meldungen ein bzw. ausgeschlossen werden können
siehe Mail, bekomme das Bild nicht hineinkopiert

**Comment by chrbusch** [comment]
Bitte testen; ist das jetzt so in Ordnung?
