### ISSUE TITLE
Einwilligungsgespräch freigegebn, ohne Klick auf Button

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#641]
Bei der gezeigten Spendermeldung, war das Einwilligungsgespräch schon angelegt, ohne dass ich auf den Button Arzt Freigabe in Ornella selbst (nicht der APP) geklickt habe.

In Ornella hat der Button Arzt freigabe gefehlt. Dies darf nicht passieren drigendst prüfen

![image](https://user-images.githubusercontent.com/22314271/75110608-7172f680-5630-11ea-8b7b-b3ce6542b04b.png)

**Comment by chrbusch** [comment]
Ich vermute sehr, dss es sich hie rum ein einaiges Artefakt durch die Entwicklung parallel zur Benutzung des Systems handelt, oder dass ich zB in der App beim Testen versehentlich die Freigabe erteilt habe.
Bitte kritisch beobachten v.a. bei den Spendern, die in der App in irgendeiner Weise bearbeitet werden.
Könnten Sie für diese Zwecke einen Testspender mit Namen "TestApp" erstellen?

**Comment by chrbusch** [comment]
PS: Arbeiten an diesem Punkt sind natürlich "bug fix"

**Comment by chrbusch** [comment]
habe alles geprüft und keinen Fehler gefunden.
Bitte aufmerksam beobachten!
