### ISSUE TITLE
Entnahmebericht, Dienstadresse Arzt wird nicht angezeigt

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#643]
Dienstadresse von NIF wird nicht im Entnahmebericht abgebildet. Bitte prüfen
Spender ID 10928

![image](https://user-images.githubusercontent.com/22314271/75155849-2ed51b00-5711-11ea-859e-f36282e387a1.png)

**Comment by chrbusch** [comment]
Das war aber noch nie anders, oder?
Dort wird nur ein Namensfeld eingeblendet.
Kann ich aber ändern, wenn gewünscht

**Comment by Toelk-A** [comment]
das kann nicht sein, denn bei Dr. manecke funktioniert es.

**Comment by chrbusch** [comment]
Ich habe das Feld jetzt getauscht; vorher habe ich durch ca. 20 EB geblättert und es stand immer nur der Name dort, 
Wie auch immer, jetzt ist das Adressenfeld dort

**Comment by chrbusch** [comment]
PS: Weiter unten ist ein anderer Bereich, wo ein Arzt ausgewählt werden kann; DORT stand schon immer die Adresse. Könnte es sein, dass Sie diese beiden Stellen verwechselt haben?
