### ISSUE TITLE
GTMV/ App Diagnosen Bugfix

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#644]
Bitte Registerkarte Diagnosen ausblenden. Dies war nicht beauftragt.

![image](https://user-images.githubusercontent.com/22314271/75240908-6ac9b800-57c5-11ea-9771-dea3c9af97ca.png)

**Comment by chrbusch** [comment]
Erl.
(frage mich nur , warum; hat ein Spender viele Dng, war dieser Darstellung m.E. viel übersichtlicher)
