### ISSUE TITLE
BUGFIX Chatanforderung aus APP

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#647]
der folgende Chat wurde schon mind 3x auf erledigt von mir gesetzt und taucht im ca 1h Takt immer wieder in meinen Vorlagen auf

![image](https://user-images.githubusercontent.com/22314271/75253414-c9e7f680-57de-11ea-8cd9-0fd155ef2b3a.png)

**Comment by chrbusch** [comment]
Ich denke, Ursache gefunden und behoben, ansonsten bitte erneut Bild einstellen
