### ISSUE TITLE
Herstellungsliste KVG unvollständig

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#648]
folgendes KVG Transplantat wird nicht in der Herstellungsliste KVG abgebildet

![image](https://user-images.githubusercontent.com/22314271/75335793-5bf90900-588a-11ea-874b-635cb341e06e.png)

![image](https://user-images.githubusercontent.com/22314271/75336198-ff4a1e00-588a-11ea-8c6e-ddfd9a4a501c.png)

**Comment by chrbusch** [comment]
Das Script (ID 147) such tim HerstellDatum die letzte 365 Tage; dieses Transplantat hat KEIN HerstellDatum, wird also korrekterweise nicht angezeigt

**Comment by chrbusch** [comment]
![image](https://user-images.githubusercontent.com/1241899/75341117-06295e80-5894-11ea-904e-b74c16364246.jpeg)
