### ISSUE TITLE
Löschen von Datensätzen ohne Löschen der kompletten Spenderakte möglich?

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#65]
Ist es möglich leer, falsch oder doppelt erstellte Datensätze wie z.B. in 161216-0710-GNO-SCD zu löschen ohne hierbei die komplette Spenderakte zu löschen?

![image](https://cloud.githubusercontent.com/assets/22314271/21607651/e760e452-d1b7-11e6-9c4a-ce76eb3878db.png)

**Comment by chrbusch** [comment]
Meinen Sie die Löschung eines einzelnen Prozessschrittes?
Das könnte ich problemlos frei schalten - man muss dann aber sehr vorsichtig sein!

**Comment by Toelk-A** [comment]
Ja, das Löschen eines einzelnen Prozesschrittes, der doppelt, leer oder eben falsch angelegt wurde. Vielleicht sollte diese Funktion dann nur für das ärztliche Personal freigeschalten werden.

**Comment by chrbusch** [comment]
Rechts in der Liste der Prozessschritte ist nun ein roter Löschbutton
