### ISSUE TITLE
Persönlicher Kalender Stundendokumentation TOA

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#651]
Nach Klick auf Button steuer optimieren, werden die steuerfreien Stunden in das steuerpflichtige Feld eingetragen. Bitte dringend beheben

![image](https://user-images.githubusercontent.com/22314271/75673744-f17a0b80-5c83-11ea-812e-f3d62a542de2.png)

**Comment by Toelk-A** [comment]
Hallo Herr Busch,

funktioniert nach wie vor nicht.

![image](https://user-images.githubusercontent.com/22314271/75854950-86e6de00-5df1-11ea-8f24-18532c2787ba.png)

![image](https://user-images.githubusercontent.com/22314271/75854980-9534fa00-5df1-11ea-8036-1a51caafc9b3.png)

**Comment by chrbusch** [comment]
Ist dies einmal passiert oder regelmassig?
Tritt es unabhängig von Stundenart, Wochentag etc auf?

**Comment by Toelk-A** [comment]
mir ist dies am Wochenende aufgefallen. Habe die Stunden erneut am Montag im Büro dokumentiert und es passiert der selbe Fehler.

**Comment by Toelk-A** [comment]
Dies scheint ein wiederholbarer Fehler zu sein.

**Comment by chrbusch** [comment]
Wie soeben besprochen: Formelfehler (daher bugfix), der aber nur Auszahlungen unter 3 Minuten betraf.

**Comment by Toelk-A** [comment]
erledigt
