### ISSUE TITLE
GBMV/ Transplantatliste Button Freie Suche -> Fehlermeldung

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#653]
Nach Klick auf Button freie Suche und Nutzung des Suchfeldes bankinterne Nummer erscheint folgende Fehlermeldung:

Bitte prüfen, dies war vorher nicht so.

![image](https://user-images.githubusercontent.com/22314271/76225437-c6139580-621c-11ea-984c-724c20d696db.png)

**Comment by chrbusch** [comment]
bugfixed
