### ISSUE TITLE
Ornella APP Anpassung Diesplaygröße

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#654]
Bitte App Abbildung auf Handy wie folgt anpassen: (dies betrifft auch die Registerkarten Chat und Chat neu)

![Abbildung Ornella App](https://user-images.githubusercontent.com/22314271/76498457-31d44900-643d-11ea-9ee3-fb07ab8e3a68.jpg)

**Comment by chrbusch** [comment]
Erledigt; bitte ansehen und ggf.s weitere Größenkorrektur angeben

**Comment by Toelk-A** [comment]
![ornella app](https://user-images.githubusercontent.com/22314271/76744517-a2000900-6774-11ea-818f-85582293520f.jpg)


anbei wie gewünscht das Foto von NIFS Handy. Generell wär es schön, die Schrift noch ein wenig zu vergrößern.

**Comment by chrbusch** [comment]
Schrift ist 1 px größer und Schriftfeld erneut leicht vergrößert

**Comment by Toelk-A** [comment]
Danke!
