### ISSUE TITLE
In Ornella geuploadete PDFS dynamisch gestalten?

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#655]
Hallo Herr Prüter,

ist es möglich die hochgeladenen PDFs in Ornella dynamisch zu gestalten?

Der Ablauf ist folgender:

Spenderdetails // Reiter Dokum. + Status

![image](https://user-images.githubusercontent.com/22314271/76508609-f6db1100-644e-11ea-9937-bd63e9d44aea.png)

PDF wird hochgeladen -> Leitender Koordinator schaut sich PDF an, markiert eine Diagnose gelb und schreibt einen Text heirzu. Kann diese Änderung im hochgeladenen PDF übernommen werden?

Weitere Überlegung: ist es möglich in diesem hochgeladene PDF eine digitale Unterschrift als "gelesen" einzufügen?

Bitte erst einmal nichts programmieren sondern nur durchdenken, ob dies möglich wäre. Wir wollen den "Papierkrieg der Befunde" im Büro etwas einschränken.

**Comment by mprueter** [comment]
Wie schon mal besprochen, hier ein Vorschlag für eine optische Überarbeitung des Portals:

![Bildschirmfoto 2020-05-08 um 10 43 34](https://user-images.githubusercontent.com/3273572/81388732-0017ef80-9119-11ea-9dc4-cbb6926c7c37.png)

**Comment by Toelk-A** [comment]
Diese 2 Punkte müssten noch einmal durchdacht werden:

**1) PDF wird hochgeladen -> Leitender Koordinator schaut sich PDF an, markiert eine Diagnose gelb und schreibt einen Text hierzu. Kann diese Änderung im hochgeladenen PDF übernommen werden?**
-> Gelbmarkierung hatten wir ausgeschlossen, hierfür wurde Bemerkungsfeld entwickelt

-> der Leitende Koordinator benötigt eine Möglichkeit das PDF zu bewerten. (keine Bemerkungen dann Freigabe Button ähnlich VP§20b mit der Bezeichnung "Gelesen und bewertet" bzw. einen Button "Rücksprache mit § VP 20b"


Weitere Überlegung: ist es möglich in diesem hochgeladene PDF eine digitale Unterschrift als "gelesen" einzufügen?
-> dies war auch nicht möglich, oder?

**Comment by mprueter** [comment]
Mein Vorschlag:

![Bildschirmfoto 2020-07-22 um 15 03 11](https://user-images.githubusercontent.com/3273572/88179713-98a81100-cc2c-11ea-8f40-59e5daa3cf21.png)


Diese Buttons sollten nur von Personen mit dem HiddenButton Koordinator benutzbar sein. Bei der Bewertung ist da schon so eingerichtet.

Es erscheint dann folgender Dialog (die Werteliste muss ggf. noch angepassst werden):

![Bildschirmfoto 2020-07-22 um 14 50 31](https://user-images.githubusercontent.com/3273572/88178636-fcc9d580-cc2a-11ea-82d1-af980419242e.png)


Änderungen im Bewertungsfeld werden im Protokoll erfasst:

![Bildschirmfoto 2020-07-22 um 14 50 46](https://user-images.githubusercontent.com/3273572/88178666-05221080-cc2b-11ea-98b4-13828df27810.png)

Die Eingabe der Anmerkungen des Koordinators erfolgen via Popover, damit der Zugriff steuerbar ist (bei Bedarf kann das auch noch im Protokoll geloggt werden):

![Bildschirmfoto 2020-07-22 um 14 50 40](https://user-images.githubusercontent.com/3273572/88178668-05221080-cc2b-11ea-9c1c-9a0bdebb55d3.png)

...wobei ich mit nicht sicher bin, obdas wirklich nötig ist. Der Leitende Koordinator könnte doch auch den Dokumenten-Chat benutzen. Ggfs. könnte man dessen Einträge speziell markieren oder hervorheben....

Können wir alles noch hin und her schieben und umbennenen, ist nur ein Vorschlag.

Bitte einmal testen, ob das so die richtige Richtung ist.
