### ISSUE TITLE
GTM-V/ Welcher Status Spender Datensatz wird in App abgebildet?

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#658]
Die Sepnderliste in Ornella, stimmt nicht mit der Spenderliste in der App überein. Genaugenommen geht es mir um den Status Spender :

Spenderdetails rechts unten:
![image](https://user-images.githubusercontent.com/22314271/76737274-c3f38e80-6768-11ea-9d17-73329d3592eb.png)

![image](https://user-images.githubusercontent.com/22314271/76737312-d5d53180-6768-11ea-9148-aa6d9e8b07a7.png)

Nach jetzigem Stand haben wir in Ornella folgende "offene" Spender:
12 Stück

![image](https://user-images.githubusercontent.com/22314271/76737398-fe5d2b80-6768-11ea-9a87-54008104b36d.png)

in der App werden nur 5 aus 6 angezeigt:

![image](https://user-images.githubusercontent.com/22314271/76737528-3bc1b900-6769-11ea-9b86-ae6eedd6e2d4.png)

Folgende Spender fehlen z.B. in der App:

ID 11147
ID 11152
ID 11158

**Comment by chrbusch** [comment]
Klappt der Abgleich jetzt wie gewünscht?
