### ISSUE TITLE
Bitte Bezug zwischen Anzahl Blutproben im Reiter "Blutproben" und Hämodilution herstellen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#66]
Nach Eingabe der Blutproben im Reiter Blutproben kann die Hämodilution erstellt werden. 

Klickt man nun (in der Hämodilution) oben rechts auf den Button "Nächste Blutprobe" so darf keine neue Blutprobe erstellt werden, sondern es dürfen nur die Blutproben erscheinen, die im Reiter "Blutproben" dokumentiert wurden.

Hier bitte auch darauf achten, dass Serum und EDTA vom selben Abnahmedatum und -Zeit auf ein und demselben Hämodilutionsbogen erscheinen.

**Comment by chrbusch** [comment]
Sie können nun die Proben des Spenders direkt  r.o. auf dem Dilutions-Bogen anwählen, bitte testen

![bildschirmfoto 2017-01-04 um 10 45 10](https://cloud.githubusercontent.com/assets/1241899/21638264/ec23fd68-d26a-11e6-8cbd-32587a5c8781.JPG)

**Comment by Toelk-A** [comment]
Siehe Github Ticket #62
