### ISSUE TITLE
GTMV/ Ornella APP unvollständige anzeige Spendermeldung

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#660]
Spender ID 11167 

rot= meldende Einrichtung
blau= postmortale Zeit nicht abgebildet 

bitte beides prüfen

![image](https://user-images.githubusercontent.com/22314271/76846483-dccf7300-6840-11ea-879c-e6036cacce22.png)

**Comment by chrbusch** [comment]
Check now please…

**Comment by Toelk-A** [comment]
funktioniert
