### ISSUE TITLE
GBMV/ Text formatieren

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#661]
Gewebanforderung - Transplantat Auswahl und Allokation

Können Sie die Stornos (gelbe Markierung) entweder farblich hervorheben oder die Allokation beim Status „Storno“ verbieten?

![image](https://user-images.githubusercontent.com/22314271/76867417-c851a180-6865-11ea-924d-123b88341ab1.png)

Gewebebanforderung - Gewebeanforderungsdetails

![image](https://user-images.githubusercontent.com/22314271/76867527-ec14e780-6865-11ea-94a4-9a75e407c794.png)

**Comment by chrbusch** [comment]
Bei Sttus STorno wird der lloktionsButton ausgeblendet; außerdem wird überall das Statusfeld rot gefärbt, wenn es "Storno" enthält.Reicht dies aus?

![image](https://user-images.githubusercontent.com/1241899/76935199-f6c88e80-68f0-11ea-9e7f-e2c6c88b7345.jpeg)

**Comment by Toelk-A** [comment]
super gelöst! danke
