### ISSUE TITLE
GBMV/ Personalplanung Stundendokumentation Ärzte Button Auszahlung

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#662]
Hallo Dr. Busch wie schon kurz telefonisch besprochen folgendes Problem:

Wir haben gemeinsam die Stundenarten mit ihren Charakteristika erstellt. Manche Stunde, wie z.B. die Passivstunden, können nicht ausgezahlt werden.

Für das Team "Ärzte" soll nun eine Ausnahme, in Form eines Buttons "Auszahlung" programmiert werden:

![image](https://user-images.githubusercontent.com/22314271/76945057-4e232a80-6902-11ea-9ede-1c94c309adea.png)

Dies betrifft alle Stundenarten, die normalerweise auf das AZK Konto gehen und nicht ausgezahlt werden dürfen außer die reguläre Arbeitszeit:
Stundenarten - Spalte AZK änderbar
![image](https://user-images.githubusercontent.com/22314271/76946213-fd143600-6903-11ea-8da1-7b1dc2e08bc2.png)

Dies sind folgende Stunden IDs:

-> Stunden ID Nr 8
-> Stunden ID Nr 5
-> Stunden ID Nr 6
-> Stunden ID Nr 7

**Comment by Toelk-A** [comment]
Hallo Dr Busch,
ist dies noch umsetzbar bis 30.03.20?

**Comment by chrbusch** [comment]
Ich bin nicht sicher, ob ich de Aufgabe verstanden habe; was genau soll der Button tun?
Reicht es, die AZK-Stunden auf 0 zu setzen? Das tut der neue Button jetzt; er ist sichtbar bei den 4 genannten Stundenarten

**Comment by chrbusch** [comment]
![image](https://user-images.githubusercontent.com/1241899/77887501-fde58a00-726a-11ea-93a8-d2057afbac1b.jpeg)

**Comment by Toelk-A** [comment]
Hallo Dr Busch, leider mussten wir feststellen, dass die Passivstuden NICHT auf dem Ausdruck "Überstunden" erscheinen.

Beispiel Mitarbeiter Tölk

![image](https://user-images.githubusercontent.com/22314271/81698467-4e552780-9466-11ea-9461-bfa31510de49.png)

17.04.20 1 Passivstunde Auszahlung
![image](https://user-images.githubusercontent.com/22314271/81698566-7ba1d580-9466-11ea-88d9-5acac89a2680.png)

Diese Passivstunde wird vom AZK Abgezogen (das ist auch richtig so) taucht allerdings nicht im Überstundenbericht auf (und das ist nciht gut! ;-))

![image](https://user-images.githubusercontent.com/22314271/81698766-bc015380-9466-11ea-8866-fc3ae1459581.png)

**Comment by Toelk-A** [comment]
Bitte dringendst dieses Ticket bearbeiten!

**Comment by chrbusch** [comment]
Wäre es korrekt, wenn von dem im Bild gezeigten 3 Zeilen die letzten beiden im Überstd-Bericht wären?

![image](https://user-images.githubusercontent.com/1241899/81781036-ccadda00-94f7-11ea-9102-13c5a2a241ab.jpeg)

**Comment by chrbusch** [comment]
Bei den Stundenarten gibt es rechts ein Ankreuzfeld "d_UeberStdBericht_auslassen_1"; wird dieses angekreuzt, so werden entspr. stunden ausdrücklich ignoriert beim Überstd.-Bericht.
Und für alle RBD-Passivstunden ist es angekreuzt!

![image](https://user-images.githubusercontent.com/1241899/81781470-72614900-94f8-11ea-889e-c139e8e9b367.jpeg)
