### ISSUE TITLE
Ornella APP - Liste Spendermeldungen wieder unvollständig

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#663]
Aus irgendeinem Grund ist die Liste der Sepndermeldungen in der App heute wieder unvollständig:

es fehlen:
IDs
11185
11186

-> beide haben den Status "Eingang Spendermeldung"

Es befindet sich nur die folgende Meldung in der Spenderliste APP

![image](https://user-images.githubusercontent.com/22314271/77042395-e3cec080-69bb-11ea-9903-c75f50261e8c.png)

**Comment by chrbusch** [comment]
ich kann nur schauen, wie es JETZT ist:
11186: Ablehnung, korrekterweise nicht in der App
11185: Status vorl. Indik., korrekterweise in der App

Zwischen ...85 und ...87 ist in der App eine ID-Lücke; es spricht daher alles dafür, dass 11186 erst angelegt und dann wegen des Status wieder gelöscht wurde

![image](https://user-images.githubusercontent.com/1241899/77072140-85bad100-69ed-11ea-9ed2-acb3c75a1936.jpeg)

**Comment by chrbusch** [comment]
PS: Ich lasse nun protokollieren, wann ein Spd in der App neu angelegt bzw. gelöscht wird

**Comment by Toelk-A** [comment]
Liste immernoch unvollständig, es wird nur der Testspender angezeigt. wenn man sich abmeldet udn wieder einloggt ist die aktuelle liste vorhanden.

**Comment by chrbusch** [comment]
Die App merkt nicht, wenn in Ornella neue Spender hinzukommen.
Der Button Update sollte dies aber immer korrekt darstellen
