### ISSUE TITLE
Auswertung Bestellverhalten, Storno etc

### ISSUE THREAD

**Issue by chrbusch** [chrbusch/GTM-V#664]
Storno einer GewebeAnfordeung wird bereits mit Zeitstempel gespeichert in Tabelle StatusWechsel

**Comment by Toelk-A** [comment]
Status ist in Ornella eingepflegt

bitte bei Storno noch den Grund abbilden

![image](https://user-images.githubusercontent.com/22314271/77541342-d8d8cc00-6ea4-11ea-88d7-2a6c6d846a6e.png)

**Comment by Toelk-A** [comment]
Wir ist hier Stand? wir müssen die Stornogründe noch nachdokumentieren, damit NIF seine Auswertung machen kann.

**Comment by chrbusch** [comment]
Der Grund wird jetzt angezeigt; aber die Gründe sollten VIEL kürzer formuliert werden, sonst passen sie in keine Liste.
Vorschlag: zB "COVID" anstelle von "Auswirkungen der COVID-19-Pandemie"

**Comment by Toelk-A** [comment]
Grund wird leider an falscher Stelle angezeigt. Bitte wie gezeigt (Pfeil) Grund anzeigen lassen. danke

**Comment by chrbusch** [comment]
Rechts war in der Liste das überflüssige Feld "Besteller"; alle Pos. einer GewebeAnforderung haben ja denselben Besteller.
Dort für lle Pos. den Grund zu sehen, halte ich für sinnvoll.
Links wird er nun auch gezeigt

![image](https://user-images.githubusercontent.com/1241899/77731182-b957b580-7002-11ea-8fbd-1342e2ce58c2.jpeg)
