### ISSUE TITLE
Export S - Liste Gewebe-Status mit exportieren

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#665]
![image](https://user-images.githubusercontent.com/22314271/78358444-8047b400-75b3-11ea-8917-1a330200b0fe.png)

Bitte den allgemeinen Status der Gewebe mit exportieren (Spenderdetails unten rechts) NIF benötigt dies dringend für Auswertungen.

![image](https://user-images.githubusercontent.com/22314271/78358358-58585080-75b3-11ea-97d9-57ed28447176.png)

**Comment by chrbusch** [comment]
Wird nun ls SpalteT mit exportiert

![image](https://user-images.githubusercontent.com/1241899/78421749-4da4c680-765a-11ea-8688-6f91f4eee807.jpeg)
