### ISSUE TITLE
GBMV/ dynamisches Patientenalter (Patientendetails)

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#667]
Hallo Dr Busch,

bitte einmal prüfen. Wir hatten dies vor einigen Monaten schon einmal besprochen. Das Geburtsdatum des Patienten muss dynamisch bleiben.

VG Anita Tölk

![image](https://user-images.githubusercontent.com/22314271/79339771-a3fee880-7f29-11ea-9e8a-5e549c3c662e.png)

**Comment by chrbusch** [comment]
Ja, Bugfix!
Das Altersfeld rechnet nun korrekt.

(Techn. Anm.: Feld Patient:k_Alter war indiziert und lieferte wg. CF "_Today" keine dynam. Ergebnisse. Fast sicher seinerzeit versehentlich indiziert definiert, von cbu heute geändert zu "unstored")
