### ISSUE TITLE
GTMV/ MSG Maximalalter nicht korrekt

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#668]
Hallo Dr Busch, soweit ich mich erinnere hatten wir bis einschließlich 90Jahren MSG als mgl. Gewebeart festgelegt.

Basis Prozesschritte Standardsets definieren

![image](https://user-images.githubusercontent.com/22314271/79945510-2fb6ce80-846e-11ea-8745-59fde5038152.png)

Nun haben wir einen Spender der 91 Jahre alt ist und es wird trotzdem MSG als mgl. Geweb angezeigt. Können Sie hier bitte noch einmal die Programmierung prüfen? Dies ist kein Ausnahmefall.

Spender ID 11500

![image](https://user-images.githubusercontent.com/22314271/79945448-1150d300-846e-11ea-9c78-f4cf34387e68.png)

Danke

**Comment by chrbusch** [comment]
Mit Standardsets hat dies nichts zu tun!
In der BaseData können Sie bei den Gewebearten Min/Max-Alter eintragen; und hier steht 91 bei MSG, siehe Bild.
Zugang zu der Maske:
In BaseData Strg-4, "Gewebearten" wählen

![Bildschirmfoto 2020-06-25 um 07 58 10](https://user-images.githubusercontent.com/1241899/85663657-a2843600-b6b9-11ea-8e04-a07dae391a9b.jpg)


![Bildschirmfoto 2020-06-25 um 07 57 00](https://user-images.githubusercontent.com/1241899/85663521-7b2d6900-b6b9-11ea-8e50-0a0f46bffe06.jpg)

**Comment by Toelk-A** [comment]
oka yhabe ich geändert. eigentlich hätte sich ja beides ausschließen müssen ;-)
