### ISSUE TITLE
GTMV/GBMV Ausladung EXport COVID Untersuchungen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#669]
Hallo Herr Prüter,

wie gestern telefonisch schon kurz angedeutet benötigt NIF eine Ausladung der virologischen/serologischen Untersuchungen zu COVID.

Hierzu habe ich mir folgendes überlegt:

### 1) Button "COVID Export" anlegen

Bitte im Ornella Hauptmenü "Auswertung GTM-V" den o.g. Button anlegen

![image](https://user-images.githubusercontent.com/22314271/79946005-63462880-846f-11ea-8c74-d203e011739e.png)

### 2) Exceltabelle erstellen

Ausgeladen werden sollen folgende Felder:
**Spenderdetails**
-> Spenderkennnummer
-> Geschlecht
-> Alter
-> Meldende Einrichtung (Hier denke ich reicht das Krankenhaus)

![image](https://user-images.githubusercontent.com/22314271/79946469-5b3ab880-8470-11ea-8604-7cebdef271b6.png)

**Blutproben und Befunde**
-> Ergebnis COVID- PCR
-> Ergebnis COVID-IgG
-> Ergebnis COVID-IgA

![image](https://user-images.githubusercontent.com/22314271/79946630-a1901780-8470-11ea-9858-f99fc56e95dc.png)

-> Art der Blutprobe (EDTA, SErum Li-Hep //prämortal oder postmortal) 
Hierzu muss im Prozesschritt Untersuchungsantrag nachgesehen werden welche Probe an das Südstadtlabor versandt wurde. Vorher muss Ticket #670  bearbeitet werden...) 

![image](https://user-images.githubusercontent.com/22314271/79947621-8c1bed00-8472-11ea-921e-e633f3cce17b.png)

### -> COVID Testung in meldender Einrichtung
NIF möcht ebenfalls gern wissen, ob COVID in der meldenden Einrichtung getestet wurde. Hierfür wäre meine Idee Folgende:

A) Spenderdetails Ankreuzfeld COVIDTestung in meld. Einrichtung Ja/nein , wenn Ja Ergebnisfeld Pos/neg (ähnlich Obduktionsfeld)
![image](https://user-images.githubusercontent.com/22314271/79948701-a0f98000-8474-11ea-822c-8de29f7cc422.png)

B) oder man erstellt einen COVID Prozesschritt in dem alle COVID-Ergebnisse gesammelt werden

C) ODER man registriert die COVID Klinikuntersuchung in den Befunden
![image](https://user-images.githubusercontent.com/22314271/79948940-08afcb00-8475-11ea-9bc6-ba644bf436e0.png)

Vielleicht gibt es auch eine bessere Möglichkeit als die 3 genannten ?

**Comment by Toelk-A** [comment]
Sehr gut umgesetzt!

**Comment by mprueter** [comment]
NiF hat den Export evaluiert und erhebliche Abweichungen zwischen den exportierten und den in Ornella hinterlegten Ergebnissen festgestellt.

Grund für diese Abweichungen ist, dass viele Befunde die aus den Laboren kommen (insb. Plauen) relativ zeitnah in Schriftform übermittelt werden und dann auch schon händisch eingetragen werden. Die digitalen Daten kommen dann später...

...oder bei Plauen auch manchmal gar nicht. In der SQL-Abfrage für die Exportfelder wird aber nach dem Status VE ( nur Befunde mit dem Status = "E" für erledigt ) gesucht, der beim Import gesetzt wird. Da aber u.U. keine Daten importiert wurden, sondern nur händisch eingetragen wurden, gibt es häufig keinen Wert und das Exportfeld bleibt leer. 

Um dieses Problem zu Umgehen (das sich wahrscheinlich nie ganz vermeien lassen wird) habe ich dei SQL-Abfrage in den Exportfeldern umgebaut:


Let(

  [

    vSQL = "SELECT DISTINCT({Ergebnis})
                 FROM {{Befund}}

                 WHERE {SpdID} = ?   
                 AND   {BasParID} = ?
                 AND {Ergebnis} IS NOT NULL
                 ";


    vQuery = Substitute( vSQL;

               //TO resp. table to be selected from:
               [ "{{Befund}}" ;                    
                  _SQLTable6 ( GetFieldName ( _Befund__::__pk_Befund )) ];

               // fields::
               [ "{Ergebnis}" ;
                  _SQLField6 (GetFieldName ( _Befund__::d_ErgebnisBefund )) ]; 

               [ "{SpdID}" ;
                  _SQLField6 (GetFieldName ( _Befund__::_fk_Spd ))];     /* Field 1 for search */

               [ "{BasParID}" ;
                  _SQLField6 (GetFieldName ( _Befund__::_fk_BasPar ))] ;   /* Field 2 for search */

               [ "{VE}" ;
                  _SQLField6 (GetFieldName ( _Befund__::d_v_Vorlaeufig_E_Endbefund ))]    /* Field 2 for search */


           );

    vRes = ExecuteSQL ( vQuery; ""; "";

    /* Search criteria (arguments) */

                                 _Spender__::__pk_Spender;
                                 158;  //Covid19 Iga   
                                 "E"                            
                                )

  ];

  Case ( vRes ≠ "?"; vRes ) 

)

Die Suche erfolgt jetzt allein nach Parameter un der Spender-ID und dem VOrhandensein eines Ergebnisses. Dabei werden die Ergbnisse nur separariert aufgeführt, wenn sie sich unterscheiden.
