### ISSUE TITLE
Bitte eingeschränkter Zugriff der Dropdownliste AAP/ärztliches Personal

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#67]
Den Koordinatoren darf es nicht möglich sein den AAP oder das ärztliche Personal in folgenden Prozesschritten einzugeben (Dropdownlisten blockieren):

- medizinische Indikationsprüfung
- Freigabe Gewebeentnahme
- Körperliche Untersuchung
- Entnahmebericht OG, KVG, MSG, Haut, Femurkopf
- Freigabe Archivierung 

Die Eingabe des AAP oder ärztlichen Personals (jeweilige Dropdownliste) soll als "digitale Unterschrift" dienen und darf somit nur dem ärztlichen Personal möglich sein.

**Comment by chrbusch** [comment]
Wer darf das denn? Nur ärtzliche Benutzer?

**Comment by Toelk-A** [comment]
Ja nur ärztliche Benutzer

**Comment by chrbusch** [comment]
Ich denke, diese Felder sind jetzt alle gesperrt, wenn der aktuelle user kein Arzt ist; bitte testen

**Comment by Toelk-A** [comment]
Scheint zu funktionieren
