### ISSUE TITLE
GTMV// Untersuchungsantrag GTM-V

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#670]
Bitte einmal prüfen, wenn wir einen Untersuchungsauftrag versenden und die Blutproben manuell anpassen, dann wird beim nächsten öffnen des Prozessschrittes Untersuchungsantrag nicht die modifizierte Form der Blutproben angezeigt sondern es werden sich wieder alle Blutproben gezogen...

Bitte prüfen und korrigieren...

Original wurde 1 EDTA versandt, öffnet man den Untersuchungsantrag erneut werden wieder alle 4 vorhanden Blutproben angezeigt.

![image](https://user-images.githubusercontent.com/22314271/79947214-dcdf1600-8471-11ea-9652-64bacc6ec4bb.png)

Im Original PDF wurde nur 1 EDTA an das Südstadtlabor versandt
![image](https://user-images.githubusercontent.com/22314271/79947357-216ab180-8472-11ea-8c21-dc8f9f9d2ecf.png)

Herr Prüter benötigt dies für die COVID Ausladungen #669

**Comment by chrbusch** [comment]
Die 5 Felder werden nnun nur noch dann automatisch gefüllt, wenn sie alle noch leer sind, bitte testen

(Techn. Anm.: Neue IF()-Bedingung in Script
  \_Gen01S.Specials (SP=pk_Spd¶pk_BasDok)/ 290420
ab Zeile 30
)
