### ISSUE TITLE
GTMV/ Checkliste Diagnosen Osteosynthesen abbilden

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#671]
Hallo Herr Busch, Hallo Herr Prüter,

wir haben eine kleine Modifikation für unsere Checkliste Entnahme:
![image](https://user-images.githubusercontent.com/22314271/80577532-57c2a680-8a07-11ea-8849-67fd26533dd2.png)

![image](https://user-images.githubusercontent.com/22314271/80577552-614c0e80-8a07-11ea-93ae-7c30974516e9.png)

Bitte wie folgt Feld einfügen:

![image](https://user-images.githubusercontent.com/22314271/80577676-90628000-8a07-11ea-87c6-b004897cf520.png)

"Osteosynthesen //Implantate"

-> hierzu soll automatisch die Information zu Prothesen/Implantaten aus den Diagnosen in den Spenderdetails gezogen werden.

![image](https://user-images.githubusercontent.com/22314271/80577800-c99af000-8a07-11ea-8800-cef3ef59b30b.png)

-> Sind via ICD Code die folgenden Diagnosen verschlüsselt, dann bitte in der Checkliste unter dem o.g. Punkt abbilden

![image](https://user-images.githubusercontent.com/22314271/80577502-4b3e4e00-8a07-11ea-9eac-31c85f8dff60.png)

Danke!!!!

**Comment by chrbusch** [comment]
Können vereinfachend ALLE Dgn als Kriterium dienen, deren ICD mit Z96 beginnt?

![image](https://user-images.githubusercontent.com/1241899/81156708-83550c00-8f86-11ea-926c-9b41f65c252a.jpeg)

**Comment by chrbusch** [comment]
...bitte testen

**Comment by Toelk-A** [comment]
Diagnose angelegt:
![image](https://user-images.githubusercontent.com/22314271/81178670-dc359c00-8fa8-11ea-87fd-4b3e860c3d03.png)

In der Checkliste ist Feld "Osteosynsthese" vorhanden, allerdings ohne Inhalt (heir soll das Textfeld, welches nach dem ICD Code verschlüsselt ist abgebildet werden
-> des Weiteren wurde dort ein "Adresssuchfeld" hinterlegt, dies war nicht gewünscht

![image](https://user-images.githubusercontent.com/22314271/81178762-038c6900-8fa9-11ea-9c0e-abaff9b0f321.png)

![image](https://user-images.githubusercontent.com/22314271/81178825-14d57580-8fa9-11ea-86c5-0506e55c2326.png)


Bitte prüfen

**Comment by chrbusch** [comment]
ich hatte 2 ähnlich benannte Felder verwechselt; bei mir hat es nun geklappt (bugfix)

**Comment by Toelk-A** [comment]
Hallo Herr Busch, seit neustem haben wir Prozessschritte angelegt, in denen die Spenderdiagnosen abgebildet werden. Können Sie bitte prüfen was hier passiert ist? 

um auf die eigentlichen Prozessschritte zugreifen zu können muss man nun ewig weit nach unten scrollen. Des weiteren war dies auch nicht beauftragt...

![image](https://user-images.githubusercontent.com/22314271/81535854-d2c28000-936a-11ea-9d86-a365093b2858.png)

**Comment by chrbusch** [comment]
Fehler gefunden & behoben (bugfix)

**Comment by Toelk-A** [comment]
![image](https://user-images.githubusercontent.com/22314271/81556281-5d66a780-938a-11ea-9c6a-8cee06c18636.png)  Bitte noch einmal prüfen

**Comment by chrbusch** [comment]
...kann das Ticket zu?

**Comment by Toelk-A** [comment]
ja
