### ISSUE TITLE
GTMV/GBMV/ Herstellungsliste neue Spalte einfügen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#672]
![image](https://user-images.githubusercontent.com/22314271/80585578-e63d2500-8a13-11ea-84d5-0e230532a881.png)

Bitte eine neue Spalte einfügen "Rechnungsnummer Präparate" erstellen

Rechnung wird erstellt über Adressen ID 24 (Gbmv)

-> ganz unten Button Rechnung GTM-V an Bank
![image](https://user-images.githubusercontent.com/22314271/80585781-31573800-8a14-11ea-8a5f-e78188bbfde9.png)

**Comment by mprueter** [comment]
Sie finden jetz auf der Tranplantatliste zwei neue Felder mit RngNr:

![Bildschirmfoto 2020-04-29 um 15 02 27](https://user-images.githubusercontent.com/3273572/80599211-ded54600-8a2a-11ea-8727-c16ff94c0815.png)

Zum einen handelt es sich um die RngNr der Transplantatabrechnung, zum anderen um die RngNr. der Rng "GTM-V an Bank".

Wenn Sie auf die Nummer klicken, gelangen Sie zu Rechnung.

Ist die RngNr rot, wurde die Rechnung storniert.

**Comment by Toelk-A** [comment]
Hallo Herr Prüter, wir benötigen nur die Rechnung an Bank. Weiterhin muss sichergestellt werden, dass maximal die Supervisor direkt die Rechnung anklicken können.

VG und danke

**Comment by mprueter** [comment]
...ist jetzt alles so. Bitte einmal testen!
