### ISSUE TITLE
GTMV/ Bitte Entnahmebericht löschen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#673]
Am Wochenende wurden aus Versehen 2 OG Entnahmeberichte angelegt. Bitte löschen Sie den Entnahmebericht mit der ID 3252.

Danke :-)

![image](https://user-images.githubusercontent.com/22314271/81546667-fee5fd00-937a-11ea-9495-8e151e36c802.png)

**Comment by chrbusch** [comment]
Erl.
