### ISSUE TITLE
GTMV/GBMV/ Personalkalender

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#674]
Wir haben ein kleines Problem.

![image](https://user-images.githubusercontent.com/22314271/81696261-f4536280-9463-11ea-8795-6af6e742c510.png)

Dienstplan für den Monat April und MAi 2020 zeigen keine Dienste der VP§20b Spalte an
obwohl diese in Ornella hinterlegt sind.
![image](https://user-images.githubusercontent.com/22314271/81698207-f0284480-9465-11ea-92d6-64c81e19a473.png)

Wir gehen, davon aus, dass dies damit zusammen hängt, dass das Team "Ärzte" in VP§20b umbenannt wurde

![image](https://user-images.githubusercontent.com/22314271/81698238-fa4a4300-9465-11ea-9182-275ac869a725.png)

**Comment by chrbusch** [comment]
In der Tat war es die Umbenennung!
Sollte jetzt klappen
