### ISSUE TITLE
GTMV/ Bitte OG Entnahmebericht löschen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#676]
Spender ID 11669

OG ENtnahmebericht ID 3263 löschen

![image](https://user-images.githubusercontent.com/22314271/82014857-c21d4d00-967d-11ea-8343-4b56d437cde7.png)

**Comment by chrbusch** [comment]
Erledigt; und ich denke, wir sollten für Supervisoren eine allgemeine Löschfunktion schaffen, das ist nicht viel Aufwand.

**Comment by Toelk-A** [comment]
ja bitte
