### ISSUE TITLE
GBMV/ Personalmodul "Tagesabschluss"

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#677]
![image](https://user-images.githubusercontent.com/22314271/82036192-de7eb100-96a0-11ea-9571-24c6989b6c25.png)

Team Koordinatoren ist unvollständig.

-> 1) Wie wird die Auswhal der heir abgebildetetn Mitarbeiter getroffen?
-> Sollen heir nur MA aus HRO oder auch Leipzig abgebildet werden?
-> Falls nach Standorten getrennt wird, gehört Frau akkermann (gelb markiert) Nicht in team Koordinatoren.
-> Falls ALLE Koordinatoren heir abgebildet werden sollen fehlen z.B. Herr Schweder und Frau Koch.

Bitte prüfen

![image](https://user-images.githubusercontent.com/22314271/82035883-73cd7580-96a0-11ea-91e0-d7f26240f2bb.png)

**Comment by chrbusch** [comment]
Ich denke, dies haben wir gemeinsam erledigt und Ticket kann zu?!
