### ISSUE TITLE
BankAvis GTMV an GBMV - Klarnamen durch Spenderkennnummer ersetzen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#678]
Bankavis wird im OG Entnahmebericht via Button verschickt:

Bitte Klarnamen durch Spenderkennummer ersetzen

![image](https://user-images.githubusercontent.com/22314271/82046141-a4b5a680-96b0-11ea-8583-989b2c0b6fbc.png)

**Comment by chrbusch** [comment]
Erl.
