### ISSUE TITLE
GBMV/ RBD PLan ausgeschiedene MA nicht mit Sonderjobs abbilden

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#679]
Hallo Herr Busch, der Mitarbeiter Petrowski ist am 30.03.20 ausgeschieden. Im RBD werden noch seine Sonderjobs eingeblendet. Dies bitte generell nicht mehr tun.

Ausgeschiedene MA nicht mehr im RBD mit Sonderjobs abbilden

![image](https://user-images.githubusercontent.com/22314271/82197255-09644180-98fb-11ea-9422-3a7267eb2768.png)

**Comment by chrbusch** [comment]
Der Server löscht jetzt jede Nacht MitarbeiterTage, die nach dem Ausscheiden liegen
