### ISSUE TITLE
Prozesschritt medizinische Indikationsprüfung Ja UND Nein bitte zu Ja ODER Nein Feldern ändern

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#68]
Im Moment ist es möglich bei der medizinischen Indikationsprüfung sowohl Ja als auch Nein in derselben Zeile/Fragestellung anzukreuzen. Dies bitte auf "ja" oder "Nein" ändern.

**Comment by chrbusch** [comment]
Aufgrund des Datenmodells und der vielen Felder ist dies leider sehr aufwendig!
Ist das wichtig?

**Comment by Toelk-A** [comment]
Ja, da klar sein muss ob medizinische Ausschlussgründe vorliegen.

**Comment by chrbusch** [comment]
Zunächst testweise für die ersten 10 Felder:
Wenn man nun in EINER Kategorie (ABC) Ja und Nein ankreuzt und das Feld verlässt, wird es grell gelb.
Ist das gut so? Dann mache ich es für alle Felder analog

**Comment by Toelk-A** [comment]
Ja das ist gut so
