### ISSUE TITLE
GTMV - Entnahmebericht löschen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#680]
Spender 11686 bitte Entn.bericht (ID 3273) vom 18.5. löschen

**Comment by chrbusch** [comment]
Bitte klicken SIe einfach auf das weissrote Kreuz ganz rechts! Das ist doch alles für den Supervisor priogrammiert worden.

![image](https://user-images.githubusercontent.com/1241899/82416584-8ec23000-9a7a-11ea-9d00-b81e9088bec6.jpeg)

**Comment by mprueter** [comment]
Das Problem war, dass beim Löschen des Entnahmeberichtes zwar die Spd-ID auf negativ gesetzt wurde, aber nicht die SpdGewebe-ID... Und über diese läuft u.a. die Erstellung der AGE-Abrechnung und uach die Anzeige eines vorhandenen Entnahmeberichtes. Deswegen wurde beim Anzeigen des richtigen Entnahmeberichtes auch immer der gelöschte mit angeboten.

Jetzt wird auch die SpdGewebe-ID bei der SpdEntnahem negativiert.

**Comment by Toelk-A** [comment]
Danke :-)
