### ISSUE TITLE
GTMV/ Anpassung Dokument + Layout Freigabe Archivg. SpdAkte

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#683]
Erst nach "Assignment" Ticket bearbeiten

1) Änderung "AAP" in "VP" auf Layout und Dokument 

2) Anpassung Fußzeile (oder kann ich dies selbst tun?)

![image](https://user-images.githubusercontent.com/22314271/83250147-f2014000-a1a7-11ea-8940-e7d53b6064c0.png)

**Comment by Toelk-A** [comment]
[PDF Freigabe Archivierung Spenderakte.pdf](https://github.com/chrbusch/GTM-V/files/4723263/PDF.Freigabe.Archivierung.Spenderakte.pdf)

**Comment by mprueter** [comment]
Fertig! Bitte prüfen...

**Comment by mprueter** [comment]
Auswahllisten sind auch auf HiddenButton umgestellt...
