### ISSUE TITLE
GTMV/ Anpassung Layout und Dokument Spendermeldung

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#684]
Erst nach "Assignment" Ticket bearbeiten

Änderung "AAP" in "VP" auf Layout und Dokument

Anpassung Fußzeile (oder kann ich dies selbst tun?)

![image](https://user-images.githubusercontent.com/22314271/83250463-7227a580-a1a8-11ea-9b71-f578218c2954.png)

**Comment by Toelk-A** [comment]
[PDF Spendermeldung.pdf](https://github.com/chrbusch/GTM-V/files/4723302/PDF.Spendermeldung.pdf)

**Comment by mprueter** [comment]
Fertig. Bitte prüfen...

**Comment by mprueter** [comment]
So bitte jetzt noch einmal prüfen...
