### ISSUE TITLE
GBMV/ Bugfix? Personalplanung Sollstunden pro Tag bitte bis 24.06.20 erledigen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#686]
Mitarbeiterin Thiery ID 111

hat ein falsches Stundensoll pro Tag angezeigt. Sie muss nur 6,4h leisten bekommt allerdings ein Soll von 8h angezeigt:

![image](https://user-images.githubusercontent.com/22314271/83504585-f2aa1700-a4c4-11ea-9194-6a76c77fd34d.png)

![image](https://user-images.githubusercontent.com/22314271/83504683-11101280-a4c5-11ea-8c4c-1895ae2e77f3.png)

Überlegung: Könnte dies mit der Programmierung Kurzarbeit zusammenhängen?

**Comment by chrbusch** [comment]
Bei 111 sind 8 Std. Soll-Arbeitszeit für alle Tage ab 23.5.2020 ausdrücklich eingetragen; war das früher die Soll-Arbeitszeit?
Ich ersetze das jetzt gegen 6.4.

**Comment by Toelk-A** [comment]
### Bei 111 sind 8 Std. Soll-Arbeitszeit für alle Tage ab 23.5.2020 ausdrücklich eingetragen; war das früher die Soll-Arbeitszeit?

Hier waren noch nie 8h Sollarbeitszeit für die genannte Mitarbeiterin. Wie im oben gezeigten Screenshot sollten eigentlich 6,4h abgebildet sein... Können Sie dies nochmal prüfen

**Comment by chrbusch** [comment]
Ich kann nun nichts mehr prüfen, weil ich 111 Datensätze verändert habe. Es stand definitiv für jeden dieser Tage ein Soll von 8h in dem Feld

**Comment by Toelk-A** [comment]
komisch, die Mitarbeiterin hat seit Anstelliungsbeginn nie 8h gearbeitet sondern immer 6,4h pro Tag. VG

**Comment by chrbusch** [comment]
Vorschlag: Ticket schliessen und wenn es erneut auftreten sollte, wieder öffnen
