### ISSUE TITLE
GTNMV/ Anpassung Dokument + Layout Einwilligungserklärung Seite 2

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#689]
[PDF Einwilligungserklärung.pdf](https://github.com/chrbusch/GTM-V/files/4723337/PDF.Einwilligungserklarung.pdf)

1) Wenn Koordinator = gesprächsführender arzt bitte automatisch digitale Unterschrift auch beim Arzt setzen

2) Digitales  Unterschriftenfeld Arzt hinzufügen

**Comment by mprueter** [comment]
Kann man sagen, dass wenn der Koordinator ein Arzt (HiddenButton) ist, er dann auch meist oder fast immer der gesprächsführende Arzt ist? Ist es so gemeint? 

Bsp:
NiF setzt sich als Koordinator
-> er hat auch das Recht "Arzt" -> deshalb wird auch schon gleich der gesprächsführende Arzt auf NiF gesetzt.

NiF unterschreibt bei Koordinator oder beim gesprächsführenden Arzt und beide Unterschriftenfelder werden gefüllt (weil NiF in beiden schon vorbelegt ist).

Ist es so gemeint?

**Comment by Toelk-A** [comment]
### NiF unterschreibt bei Koordinator oder beim gesprächsführenden Arzt und beide Unterschriftenfelder werden gefüllt (weil NiF in beiden schon vorbelegt ist).

Ist es so gemeint?

Ja so ist es gemeint.

Bitte noch das digitale Unterschriftenfeld für den Arzt programmieren.

**Comment by mprueter** [comment]
Das Unterschriftenfeld ist jetzt eingefügt (HiddenButton = Arzt).
Außerdem habe ich anstelle der beiden roten Buttons (User, Adr) einen Löschbutton (Papierkorb)für den gesprächsführenden Arzt eingebaut. Wenn jetzt eine Adresse ausgewählt wird, wird automatisch der evtl vorhandene User gelöscht und umgekehrt.

![Bildschirmfoto 2020-06-23 um 09 52 19asdas Kopie](https://user-images.githubusercontent.com/3273572/85376035-7b9df680-b537-11ea-99c6-dc9fbba70548.png)



Sofern ein Arzt als Koordinator eingetragen wird und das Feld für den gesprächsführenden Arzt noch nicht vorbelegt ist, wird er auch automatisch dort eingetragen. 

Sofern ein **Arzt** bei Koordinator unterschreibt und derselbe Arzt **AUCH** bei gespr.-f. Arzt eingetragen ist, wird die Unterschrift auch automatisch dort gesetzt und umgekehrt.

Sofern ein **Arzt** bei Koordinator unterschreibt und der Arzt bei gespr.-f. Arzt noch **NICHT** eingetragen ist, wird die Unterschrift dort auch automatisch gesetzt.

Technische Anmerkung:
neues Script EinwillGespr12. nur für dieses Layout eingebaut.

**Comment by Toelk-A** [comment]
sieht super aus, wir testen... :-)
