### ISSUE TITLE
Medizinische Indikationsprüfung Fehlermeldung bei OG Entnahmen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#69]
Besteht nur die Indikation für OG, so muss in der medizinischen Indikationsprüfung nicht MSG und KVG ausgefüllt werden. Dementsprechend sollte auch keine rote Markierung auftreten, wenn folgende Kreuze (Kontraindikation MSG und KVG)  nicht gesetzt sind:

![image](https://cloud.githubusercontent.com/assets/22314271/21608257/bbefc474-d1bb-11e6-8536-c9be9bab9869.png)

**Comment by chrbusch** [comment]
Erledigt, bitte testen!
Rechts oben werden jetzt auch die Gewebearten rot angezeigt (aber nicht gedruckt)

**Comment by Toelk-A** [comment]
funktioniert

**Comment by Toelk-A** [comment]
Problem ist leider wieder aufgetreten siehe ID 1179

**Comment by chrbusch** [comment]
Was genau ist passiert?

**Comment by Toelk-A** [comment]
Obwohl es nur um eine OG Entnahme geht steht eine rote Fehlermeldung, dass MSG und KVG Felder noch angekreuzt werden sollen. Dieses Problem wurde schon einmal von Ihnen gelöst, sodass ich nicht weiß warum der Fehler wieder auftritt. (Problembeschreibung steht auch oben)

**Comment by chrbusch** [comment]
OK, jetzt verstanden und umgesetzt, bitte testen
