### ISSUE TITLE
GTMV/ PDF +Layout Medizinische Indikationsprüfung anpassen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#690]
[PDF Medizinische Indikationsprüfung.pdf](https://github.com/chrbusch/GTM-V/files/4723351/PDF.Medizinische.Indikationsprufung.pdf)

**Comment by mprueter** [comment]
Hier habe ich die Versionsnummer erstmal wieder zurück gesetzt. 
Bitte noch einmal prüfen, welche Änderungen genau vorgenommen werden sollen....

**Comment by Toelk-A** [comment]
[Medizinische Indikationsprüfung.pdf](https://github.com/chrbusch/GTM-V/files/4746331/Medizinische.Indikationsprufung.pdf)

anbei die richtige Version

**Comment by Toelk-A** [comment]
[med. Indikationsprüfung.pdf](https://github.com/chrbusch/GTM-V/files/4750911/med.Indikationsprufung.pdf)

**Comment by mprueter** [comment]
Fertig... Bitte prüfen
