### ISSUE TITLE
GTMV/ PDF und Layout Freigabe Gewebeentnahme anpassen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#691]
Bitte unteres Datumsfeld + Unterschrift AAP... rauslöschen 

Arzt einfügen

[PDF Freigabe Gewebeentnahme.pdf](https://github.com/chrbusch/GTM-V/files/4723364/PDF.Freigabe.Gewebeentnahme.pdf)

**Comment by mprueter** [comment]
Fertig... Bitte Prüfen...

**Comment by Toelk-A** [comment]
Bitte den unteren eingekringelten Bereich aus dem Dokument entfernen 

![image](https://user-images.githubusercontent.com/22314271/84134573-1206ee00-aa49-11ea-833d-f771a2816659.png)

**Comment by Toelk-A** [comment]
Nach Rücksprache mit unserem QM darf ich Folgendes mitteilen:

-> wenn ein mobiles Team versandt wurde (oben als "ja" angeklickt), dann sollen unten alle 3 Felder eingeblendet werden ( Datum mob. Team Meldung + Datum + Unterschrift VP §20b) 


![image](https://user-images.githubusercontent.com/22314271/84138323-5e086180-aa4e-11ea-97d7-90815b0889d3.png)

**Comment by mprueter** [comment]
Das ist jetzt genauso umgesetzt. Bitte prüfen...

**Comment by mprueter** [comment]
Ist dieses Dokument das gleiche wie bei #693?
