### ISSUE TITLE
GTMV/ PDF Körperliche Untersuchung

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#692]
Bitte AAp in VP ändern + Versionsnummer ändern (restlichen Text bitte nicht beachten

[PDF Körperliche Untersuchung.pdf](https://github.com/chrbusch/GTM-V/files/4723370/PDF.Korperliche.Untersuchung.pdf)

**Comment by mprueter** [comment]
Versionsnummer und "VP" sollten jetzt funktionieren...
Der Hinweistext ("darf nur durch Arzt duchgeführt werden") ist noch nicht umgesetzt. Was genau soll das bedeuten?

**Comment by Toelk-A** [comment]
Dieser Text ist zu vernachlässigen ;-)

**Comment by mprueter** [comment]
Dann ist das jetzt fertig...
