### ISSUE TITLE
GTMV/ PDF Entnahmebericht OG / MSG / KVG

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#693]
Hier wird es etwas komplizierter.... Bitte für alle Entnahmeberichte OG MSG und KVG ändern

[PDF Entnahmebericht.pdf](https://github.com/chrbusch/GTM-V/files/4723399/PDF.Entnahmebericht.pdf)

1) Seitenzahlen generell von 1 bis 3von3 (nicht X von 6 oder x von 9)

2) Versionsnummer bitte auf jeder Seite hinzufügen (fehlte bis jetzt)

3) Seite 2 AAp in VP ändern

4) Seite 3 "Automatisch aus Freigabeprotokoll kopieren" -> heir muss ein Unterschriftenfeld für den Arzt eingefügt werden, welches automatisch aus dem Layout/Prozesschritt Freigabe Gewebeentnahme übernommen wird:

![image](https://user-images.githubusercontent.com/22314271/83638690-d16f2680-a5a9-11ea-888f-6a2a9e65bfde.png)

5) Im unteren Bereich bitte AAP durch "VP § 20b AMG ersetzen"

**Comment by Toelk-A** [comment]
Punkt 4 hat nicht funktioniert im Testspender 9829

**Comment by mprueter** [comment]
Jetzt funktioniert es...

**Comment by Toelk-A** [comment]
noch einmal bitte folgende Änderung im Text vornehmen (seite 2 )

5) "VP20b löschen" dafür "Verantwortlicher Arzt" 

![image](https://user-images.githubusercontent.com/22314271/84388044-37842b00-abf4-11ea-808f-0542154cefb1.png)

6) Bitte zum Verantwortlichen Arzt folgendes Programmierung hinterlegen: -> Sieh Programmierung Punkt 4 inkl. automatische Unterschrift

**Comment by mprueter** [comment]
5. ist schon mal erledigt

**Comment by mprueter** [comment]
6. Sollte jetz auch funtionieren. Bitte testen.

**Comment by Toelk-A** [comment]
OG Entnahmebericht funktioniert. Leider haben wir doch unterschiedliche Versionsnummern für den Entnahmebericht MSG + KVG :-( ich shcließe dieses Ticket öffne aber entsprechend 2 neue
