### ISSUE TITLE
GTNMV/GBMV Ornella meldet sich nciht mehr automatisch ab

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#694]
NIF bittet darum zu prüfen, warum Ornella sich nicht mehr nach einem bestimmten Zeitraum automatisch abmeldet / Nutzer ausloggt.

**Comment by mprueter** [comment]
Das sollte jetz wieder so sein. Falls nicht, bitte Rückmeldung an mich...

**Comment by Toelk-A** [comment]
Bitte ein größeres Zeitfenster programmieren. 20min möglich?

**Comment by mprueter** [comment]
Jetzt sollten 20 min eingestellt sein...
