### ISSUE TITLE
GTMV/ Userauswahllisten mit Rechten (VP §20b, Arzt, Koordinator) in Spenderakte sortieren

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#695]
Im Rahmen der Dokumentenüberarbeitung der Sepnderakte müssen dringendst aus die Auswahllisten überarbeitet werden. Derzeit können Ärzte der Gewebebank auf der Spenderakte unterzeichnen.... dies darf definitiv NICHT möglich sein

![image](https://user-images.githubusercontent.com/22314271/84011787-ed424600-a976-11ea-8bc7-23559555fa74.png)

![image](https://user-images.githubusercontent.com/22314271/84011941-195dc700-a977-11ea-9673-5c2fdc944cb1.png)

Wir benötigen prinzipiell 3 Wertelisten, in denen NUR die Mitarbeiter der GTM-V aufgelistet werden.

1) Koordinator
2) Arzt nach §8d TPG
3) VP §20b

Team 2 kann sowohl in Team 1 als auch 3 auftauchen. Team 3 auch in Team 1.

Bitte rufen Sie mich hierzu zurück

**Comment by mprueter** [comment]
Das ist jetzt grundsätzlich gelöst (HiddenButtons!). Sollte an einigen Stellen noch falsche Lsiten auftauchen, bitte dieses Ticket reaktivieren...

**Comment by Toelk-A** [comment]
erledigt, vielen Dank für die gute Lösung!
