### ISSUE TITLE
GTMV/ Checkliste Entnahme bitte Versionsnummer einfügen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#696]
[Checkliste Entnahme.pdf](https://github.com/chrbusch/GTM-V/files/4745988/Checkliste.Entnahme.pdf)

Bitte Fußzeile (grüne Markierung einfügen)

**Comment by mprueter** [comment]
Das sieht jetzt so aus:

![Bildschirmfoto 2020-06-10 um 08 41 26](https://user-images.githubusercontent.com/3273572/84235759-af6c2b80-aaf6-11ea-9e71-fe483401ba47.png)


techn.Anm.:
Änderung in SCript "5/Ausgabe als PDF (aktuelles Layout)"
außerdem wurde der BasisProzSchritt ID=164 geändert (Zuweisung BasisDokument-ID 38 und Prozessschrittart = PDF
