### ISSUE TITLE
GTMV/ Checkliste "Aktenrecherche" bitte Versionsnummer einfügen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#697]
[Checkliste Aktenrecherche.pdf](https://github.com/chrbusch/GTM-V/files/4745991/Checkliste.Aktenrecherche.pdf)

Bitte Fußzeile Versionsnummer einfügen

**Comment by mprueter** [comment]
Habe ich jetzt eingefügt... Bitte prüfen!

![Bildschirmfoto 2020-06-10 um 09 49 51](https://user-images.githubusercontent.com/3273572/84241547-e72ba100-aaff-11ea-82b5-45aac7f9fd2e.png)


Techn. Anm.:
Neues Layout für Aktenrecherche angelegt (wegen separater Layout-ID), wegen QS-Nr und Fusszeile (sonst keine saubere Steuerung über Basisdokumente mgl.), entsprechend neues Basisdokument (ID=39) angelegt und mit  BasisProzSchritt (ID=141) verknüpft (-> dort BasProzSchrArt = 2); in Script "5/Ausgabe als PDF (aktuelles Layout)" Layoutauswahl bei Druck von Checkliste dynamisiert (ca. Zeile 25 ff.)
