### ISSUE TITLE
GTMV/ Auswahlfenster bitte wieder vergrößert abbilden

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#698]
Adresse suchen 

Auswahlfenster ist zu klein, man muss ständig Fenster vergrößern um halbwegs die adressen erkennen zu können.

Aktuell

![image](https://user-images.githubusercontent.com/22314271/84121764-db74a780-aa37-11ea-9a20-af2e2de7d37a.png)

Wunsch
![image](https://user-images.githubusercontent.com/22314271/84120390-0f4ecd80-aa36-11ea-805b-ea1fccb25baa.png)

**Comment by mprueter** [comment]
Ist es jetzt besser?

**Comment by Toelk-A** [comment]
ja perfekt!
