### ISSUE TITLE
Artikel, Bestand, Charge, Rückverfolgung

### ISSUE THREAD

**Issue by chrbusch** [chrbusch/GTM-V#7]
Es entsteht gerade die Artikelverwaltung mit allem, was daran hängt.
Bitte einen der verwenden Barcode-Scanner zu uns schicken (kommt später zurück) und von allen zu bedruckenden Etikettenbögen 3 Stück im Original.
Dazu, soweit schon vorhanden, die von anderen angelieferten Barcodes (z.B. von Lieferanten) im Original zu uns.

![bildschirmfoto 2016-09-22 um 14 09 59](https://cloud.githubusercontent.com/assets/1241899/18747561/49ac3be2-80ce-11e6-8f2e-bfbd289ffa52.JPG)

**Comment by chrbusch** [comment]
Bitte einige Lieferanten oder Hersteller Ihrer Artikel als XLS- oder FileMaker-Datei liefern; oder manuell eingeben

**Comment by chrbusch** [comment]
Wie gestern besprochen bitte ich um Zusendung leerer Verpackungen von möglichst vielen verschiedenen Artikeln, damit wir alle Barcodes scannen und testen können.

**Comment by Toelk-A** [comment]
Versand der leeren Verpackungen/Barcodes erfolgt heute nach Feierabend
XLS Tabelle (Lieferant/Hersteller/Referenznummer) wird in der kommenden Woche per Mail versendet

**Comment by Toelk-A** [comment]
[Übersicht Verbrauchsmaterialien GTM-V.xlsx](https://github.com/chrbusch/GTM-V/files/569193/Ubersicht.Verbrauchsmaterialien.GTM-V.xlsx)

Anbei Exceltabelle unserer Verbrauchsmaterialien

**Comment by Toelk-A** [comment]
Exceltabelle benötigt ein Update. Bitte die o.g. Excelltabelle nicht in die Datenbank einspeisen. Spätestens Anfang nächster Woche kommt die aktuelle Version.
