### ISSUE TITLE
GTMV/ Arzt in VP 20b umbenennen -> Reiter Prozesschritte

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#700]
Bitte auch heir noch den Arzt als VP § 20b AMG  umbenennen

![image](https://user-images.githubusercontent.com/22314271/84358285-38eb2e80-abc7-11ea-9db9-cdbe9190b4f2.png)

**Comment by mprueter** [comment]
Ist erledigt.

Muss das hier auch erfolgen:

![Bildschirmfoto 2020-06-11 um 10 10 07](https://user-images.githubusercontent.com/3273572/84361499-08f25a00-abcc-11ea-8b1e-825929c48912.png)

**Comment by Toelk-A** [comment]
erledigt
