### ISSUE TITLE
GTMV/ Arzt in VP20b umbenennen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#701]
und noch einmal bitte....

Arzt löschen dafür VP § 20b AMG

![image](https://user-images.githubusercontent.com/22314271/84388539-140db000-abf5-11ea-8121-f3289f90a004.png)

**Comment by mprueter** [comment]
Erledigt. 
siehe auch #700 :-)

**Comment by Toelk-A** [comment]
danke :-)
