### ISSUE TITLE
GTMV/ Rechte Spenderdetails

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#702]
Recht "Koordinator" hinterlegen:

![image](https://user-images.githubusercontent.com/22314271/84489358-e599de80-aca1-11ea-90a3-e5167894d327.png)

**Comment by mprueter** [comment]
Erledigt! Bitte noch das Recht "Koordinator" bei allen Usern korrekt eintragen (derzeit haben 39 User dieses Recht)
