### ISSUE TITLE
GTMV/ Einwilligungserklärung

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#703]
Einwilligungserklärung 

Koordinator Recht gelb markiert
Arztrecht schwarz umrandet

![image](https://user-images.githubusercontent.com/22314271/84489565-298ce380-aca2-11ea-82bf-ae5aa033b058.png)

ACHTUNG

ggf. können auch externe Ärzte über Adressbuch hinzugefügt werden.

siehe unten "Aus Adressen"

**Comment by mprueter** [comment]
Fertig. Bitte testen.
