### ISSUE TITLE
GTMV/ Freigabe Gewebeentnahme

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#706]
Koordinator

![image](https://user-images.githubusercontent.com/22314271/84490227-20e8dd00-aca3-11ea-9430-e79f01b887ce.png)

Arzt

![image](https://user-images.githubusercontent.com/22314271/84490265-30682600-aca3-11ea-9655-1533f3ebebaa.png)

VP 20b

![image](https://user-images.githubusercontent.com/22314271/84490653-c00dd480-aca3-11ea-9cee-91566b7ef978.png)

**Comment by mprueter** [comment]
Fertig. Bitte testen!
