### ISSUE TITLE
GTMV/ Entnahmebericht

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#709]
Arzt (nicht VP20b)
![image](https://user-images.githubusercontent.com/22314271/84490988-30b4f100-aca4-11ea-844d-04f1467a0536.png)

Hilfskräfte

![image](https://user-images.githubusercontent.com/22314271/84491297-9dc88680-aca4-11ea-8ae0-5231704e9e20.png)

VP 20b

![image](https://user-images.githubusercontent.com/22314271/84491365-b9339180-aca4-11ea-8ef6-070bf2003f30.png)

**Comment by mprueter** [comment]
Fertig. Bitte testen!
