### ISSUE TITLE
Prozessschritt Einwilligungsgespräch

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#71]
Im Abschnitt Rahmenbedingungen "gesprächsführender Arzt" bitte auch hier die Möglichkeit erstellen Ärzte aus der Adressdatenbank einzutragen.

![image](https://cloud.githubusercontent.com/assets/22314271/21608505/2fbc9e30-d1bd-11e6-993f-90ccadad1cff.png)

**Comment by chrbusch** [comment]
Über diesem Feld ist nun ein Button <Aus Adressen>....

**Comment by Toelk-A** [comment]
super, funktioniert
