### ISSUE TITLE
GTMV/ Recht "TX-Koordinator"

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#712]
User DetailListe

Script prüfen
Kann dies gelöscht werden, da jetzt nebenan bei speziellen Rechten abgebildet?

![image](https://user-images.githubusercontent.com/22314271/84491755-542c6b80-aca5-11ea-9d34-678269df7bcc.png)

**Comment by chrbusch** [comment]
Ich vermute, dass dieses Feld noch benutzt wird, kann dies aber entweder systematisch prüfen, oder wir gehen testweise so vor, dass wir für einen Koord., den Wert auf 0 setzen und schauen, ob nach Neustart von Ornella noch alles klappt, was ein Koord. können soll.

**Comment by Toelk-A** [comment]
Hallo Herr Busch, bitte mit Herrn Prüter dieses Thema besprechen. Ich sollte dieses Ticket nur als Gedankenstütze erstellen. Herr Prüter hat in den letzten Tagen bereits viel heirzu programmiert udn gecheckt. Bitte nichts unternehmen. Danke
