### ISSUE TITLE
GTMV/ REchtekonzept Personalmodul

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#713]
Hallo Herr Prüter,

im Rahmen des Rechtekonzeptes (ARzt mit VP 20b ->

![image](https://user-images.githubusercontent.com/22314271/84648595-89cf8f80-af05-11ea-9823-49145e707474.png)

muss nun auch wieder im Personalmodul folgendes angepasst werden:

Dienstplan VP20b

![image](https://user-images.githubusercontent.com/22314271/84648710-b1bef300-af05-11ea-93ef-01f876bcc88c.png)

Bitte einmal prüfen, ob die Spalte VP§20b noch hinsichtlich der neuen Rolle von MAA + NIF angepasst werden muss. Wir 3 sind in dieser Dienstspalte abzubilden. Beim letzten Rollenwechsel gab es hier Probleme...

![image](https://user-images.githubusercontent.com/22314271/84648875-e92d9f80-af05-11ea-957b-6b84737f4b0f.png)

**Comment by mprueter** [comment]
Soweit ich das sehen kann, gibt es hier keine Probleme. 

Kurz zur Info: Frau Tölk ist jetzt nicht mehr in der Rolle mit der ID 2. Dort sind jetzt nur noch Dr. Manecke und Dr. Nitschke. Frau Tölk hat die Rolle ID=22.
Alle drei haben den HiddenButton = "VP GTMV" (ID=163).

Ich weiß nicht genau, ob das hierfür eine Rolle spielt? Auf den ersten Blick scheint mir die neue Rollenverteilung irrelevant zu sein. 

@chrbusch Kannst Du das bitte einmal prüfen?

**Comment by mprueter** [comment]
Nachtrag:
Soweit ich das sehe, wird die Steuerung des Plans über die Zugehörigkeit zu einem Team geregelt, die beim User hinterlegt ist. Diese Team-Tabelle ist aber unabhängig von den Rollen in Ornella, oder?

Insofern wäre ja alles gut...

**Comment by Toelk-A** [comment]
alles klar! Danke
