### ISSUE TITLE
GTMV/ CHAT bitte mit in den Auditlog

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#716]
bitte beim Chat die Wiedervorlage (WV): Ist zu erledigen loggen. Hier werden Verantwortlichkeiten ohne Rücksprache geändert 
![image](https://user-images.githubusercontent.com/22314271/84755664-2f483900-afc2-11ea-9424-3dbe0675382c.png)

**Comment by mprueter** [comment]
Das ist jetzt für folgende Felder umgesetzt:

Reiter Chats bei Spenderdetails:
Status
Text
WV-User
Datum
Uhrzeit 

Hauptmenü:
Btn. "Erledigt" in Chat-Portal

Zusätzlich gibt es in jedem Chat-Datensatz einen neuen Button (wie bei Auditlog MiBi), der den Auditlog des Chateintrages anzeigt:

![Bildschirmfoto 2020-06-18 um 13 57 54](https://user-images.githubusercontent.com/3273572/85017619-09f72e80-b16c-11ea-8d38-1fb395554db1.png)

...es öffnet sich dann ein Fenster mit allen Auditlog-Einträgen zu diesem Datensatz:

![Bildschirmfoto 2020-06-18 um 13 58 27](https://user-images.githubusercontent.com/3273572/85017688-3448ec00-b16c-11ea-9644-cd40b4c7d8bb.png)


Zusätzlich können alle Auditlogeinträge auch über den bisherigen Button "Auditlog-Gtmv" aufgerufen werden. Allerdings ist dort die Identifizierung des einzelnen Chatbeitrages schwierig, da hier nur die IDs angezeigt werden.


Technische Anmerkung:

Änderungen in folgenden Scripten:
AuditLog01. Zeile 36 ff. + pk_Chat als SP
Chat20. neues Script damit "Erl." im HM auch in Auditlog ist
AuditLog03M. Script ergänzt um SP pk_Chat
User04normal. Zeile 140 ff. optionales Auditlog, wenn in Options gewisse Werte übergeben werden

**Comment by Toelk-A** [comment]
funktioniert
