### ISSUE TITLE
WV Medizinische Indikationsprüfung 

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#72]
WV Link zum Spender funktioniert nicht

**Comment by chrbusch** [comment]
Bitte immer einen konkreten Spender nennen, mit dem ich testen kann.

**Comment by Toelk-A** [comment]
020117-0350-GNO-KRJ Fehlermeldungen gibt es nicht, klickt man auf "Spender" wird man nicht automatisch zum Spender weitergeleitet.

**Comment by chrbusch** [comment]
Bitte prüfen, ob es jetzt klappt
