### ISSUE TITLE
GTMV/ Rolle VP20b

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#720]
Wenn es eine Zustimmung zur Gewebespende gibt, erhalten die Ärzte immer eine Mail mit dieser Info. Ich erhalte diese mit der neuen Rolle nicht mehr. können Sie dies bitte noch vor dem Wochenende einstellten ( habe Dienst am Wochenende ...)

Am Besten bitte alle Wiedervorlagen + Mails prüfen, die die Ärzte bekommen Rolle 2, diese benötige ich auch

**Comment by Toelk-A** [comment]
Habbe eben in der Rolle die Wiedervorlagen geprüft (sind auch als Hidden Buttons programmiert). Verfolge dies heute Nachmittag, können ja morgen vormittag heirzu noch einmal telefonieren

**Comment by Toelk-A** [comment]
es funktioniert definitiv nicht, mit den Wiedervorlagen bei Zustimmung zur Gewebespende im Einwilligungsgespräch

**Comment by mprueter** [comment]
Bitte einmal prüfen, ob es jetzt funktioniert... Sie erhalten ggf. zwei Emails (einmal als Koordinator und immer als VP)

Eine WV wird aktuell für Sie nur angelegt, wenn Sie der Leitende Koordinator bei dem Spender sind, die VPs bekommen nur eine Email...

Technische Anmerkung:
Neues Script SYS30. zur Ausgabe von Emaillisten/pk_User_Listen zu HiddenBtn
Eingebaut in:
Akte01WV. Zeile 16 ff. (pk_User_Liste)
EinwillGespr10. Zeile 62 ff ($EmailAerzte)

**Comment by Toelk-A** [comment]
Hallo Herr prüter Ihre Mails (sowohl des Koordinators, als auch Arztes) sind gestern bei mir angekommen. ich prüfe dies heute tagsüber und gebe nochmal kurz feedback. Danke für die schnelle Umsetzung
