### ISSUE TITLE
GTMV/ Transportbegleitschein

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#721]
Bitte auch hier die Seitenzahlen anpassen 1von1 anstelle 1 von 3

[Transportbegleitschein.pdf](https://github.com/chrbusch/GTM-V/files/4799005/Transportbegleitschein.pdf)

**Comment by mprueter** [comment]
meint Spenderakte

**Comment by mprueter** [comment]
Das Problem sollte jetzt behoben sein. Bitte prüfen!


Technische Anmerkung:
komplizierter Entwurf (s.o.) verworfen; stattdessen:

k_PageNr hier nicht mehr benutzt, da es dann bei der Spenderakte schwierig wird, weil bei mehreren Scheinen z.B. 1 von 3, 2 von 3 etc. erscheint;
eine Überarbeitung von Spd00. wie bei den Entnahmeberichten ist hier nicht zwingend nötig, da dieser Beleg immer einseitig ist!!
