### ISSUE TITLE
GBMV/ Transplantatdetails - Einwilligung Forschung

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#722]
Bitte einmal kurz prüfen:

-> Im Prozesschritt Einwilligungsgespräch (Spenderdetails) Abschnitt IV Gesprächsergebnis
Hier wird dokumentiert, ob die TX nur für Transplantationszwecke (rot umrandet) oder auch für Forschung (gelb hinterlegt) freigegeben werden können. Das Etrgebnis wird automatisch auf die Transplantatdetails gespiegelt (siehe unten). Es müsste bitte einmal geprüft werden, ob der rot umrandete Part (Nur für Transplantationszwecke) auch übernommen wird, falls nicht müsste dies noch auf den Transplantatdetails eingefügt werden.

![image](https://user-images.githubusercontent.com/22314271/85107859-eb963f00-b20e-11ea-9ea5-cd31fef8a5c6.png)

-> Transplantatdetails Abschnitt Klassifikation

![image](https://user-images.githubusercontent.com/22314271/85107589-7fb3d680-b20e-11ea-8b91-e11f1b58d7b2.png)

**Comment by mprueter** [comment]
Ich habe auf dem Eingabelayout einen Popover-Button platziert, der erscheint, falls es eine unplausible Eingabe gibt:

![Bildschirmfoto 2020-06-19 um 12 10 25](https://user-images.githubusercontent.com/3273572/85123170-117c0d80-b228-11ea-81cb-77e461a18deb.png)

...also immer, wenn das Kreuz bei "...nur zu Tranpsplantationszwecken" gesetzt ist und bei Zustimmung zu Forschung und/oder QS ein "Ja" angekreuzt war. in dem Popover erscheint dann ein entsprechender Hinweis mit Handlungsanweisung:

![Bildschirmfoto 2020-06-19 um 12 31 04](https://user-images.githubusercontent.com/3273572/85123579-c7dff280-b228-11ea-81d1-65aa10f3eaef.png)


Bei den Transplantat-Details erscheint nun folgender Hinweis, falls "...nur für Transplantation" angekreuzt ist:

Für den Fall, dass trotzdem noch unplausible Eingaben erhalten bleiben, wird das ggf. beim Transplantat angezeigt:

![Bildschirmfoto 2020-06-19 um 12 34 36](https://user-images.githubusercontent.com/3273572/85124177-c3680980-b229-11ea-8b6c-a1b00a764582.png)

**Comment by mprueter** [comment]
...ich habe das im Zuge der Arbeiten an #689 noch etwas ergänzt. Sollte das Problem auftauchen, wird es jetzt auch in der Plausib-Prüfung berücksichtigt:

![Bildschirmfoto 2020-06-23 um 10 04 09](https://user-images.githubusercontent.com/3273572/85377237-16e39b80-b539-11ea-8dcc-8dbb985b7f54.png)

**Comment by Toelk-A** [comment]
DankE!
