### ISSUE TITLE
Export Einwill. Gespräche + Grund  // externe Gespräche werden nicht exportiert

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#727]
![image](https://user-images.githubusercontent.com/22314271/85999163-01281780-ba0c-11ea-968b-e3bb07b312f7.png)
[ANG_Gespräche2020.xlsx](https://github.com/chrbusch/GTM-V/files/4845109/ANG_Gesprache2020.xlsx)

Die Gespräche der externen Gesprächsführer (Krankenhausärzte = Gespräche auf Station) werden nicht mit ausgeladen.

_fk_Adr_GesprFuehrdArzt -> externe Stationsärzte wurden in dieser Spalte immer mit einer vierstelligen Nummer angezeigt, diese Spalte ist nun komplett leer

e_GesprFuehrdArzt_fk_User -> Spalte für den gesprächsführenden Arzt (GTM-V)
	dieses Feld ist bei externer Gesprächsführung durch einen Stationsarzt leer
	wenn man den Filter setzt sind hier einige Felder (14x) insgesamt leer, dies sind aber alles Dokumentationsfehler

**Comment by mprueter** [comment]
...momentan ist das Script so eingestellt, dass nur interne Gespräche ausgeladen werden. Es war wohl aber auch so, dass man früher zwischen extern und intern wählen konnte. Dieser Dialog ist deaktiviert. 

Sie möchten aber gern beides gleichzeitig ausladen, oder?

**Comment by Toelk-A** [comment]
### Sie möchten aber gern beides gleichzeitig ausladen, oder?
ja :-)

**Comment by chrbusch** [comment]
Ich habe zunächst den Dialog wieder aktiviert.
Bitte prüfen Sie, ob int und ext. Gespräche jeweils einzeln korrekt exportiert werden.
Wenn das der Fall ist, können wir leicht beides gemeinsam exportieren

**Comment by Toelk-A** [comment]
Ein dritter Button zur Ausladung von internen und externen Gesprächen („Beide“) wäre noch gut. (sieh PDF).

![image](https://user-images.githubusercontent.com/22314271/88381433-b7321780-cda6-11ea-9e95-16d0dac7bbde.png)

**Comment by mprueter** [comment]
Das ist jetzt möglich. Ich habe diesbezüglich den Dialog etwas angepasst und auch gleich um einen Button ergänzt, der Ihnen bereits hier die Wahl zwischen der Liste und der Darstellung als Grafik ermöglicht.

![Bildschirmfoto 2020-07-24 um 18 19 55](https://user-images.githubusercontent.com/3273572/88414226-cc299d80-cddc-11ea-8a40-665bf4006b11.png)

Damit die grafische Auswertung auch in Bezug auf die externen Gespräche halbwegs Sinn ergibt, habe ich diese noch einmal überarbeitet, sodass Sie jetzt immer eine korrekte Grafik zur jeweilgen Fundmenge erhalten. 

Dabei habe ich die externen Gespräche immer unter "Extern"zusammengefasst. Ich hoffe, das ist so okay?

![Bildschirmfoto 2020-07-24 um 18 12 09](https://user-images.githubusercontent.com/3273572/88414251-d77cc900-cddc-11ea-98e3-53563b1dcc25.png)
![Bildschirmfoto 2020-07-24 um 18 12 39](https://user-images.githubusercontent.com/3273572/88414254-d8155f80-cddc-11ea-96ca-55a54a0d4344.png)
![Bildschirmfoto 2020-07-24 um 18 13 02](https://user-images.githubusercontent.com/3273572/88414255-d8adf600-cddc-11ea-8378-0ee25e164d89.png)


technische Anmeerungen:
div. Änderungen im Script EinwillGespr50.:
 
-neuer Dialog in Zeile 8 ff.
-Loop in Zeile 46 ff. um $koord_fullList zu setzen (vorheriges _ListField hat Extern nicht berücksichtigt)
-$koor -> Case( _EinwillGespraech_::_fk_Adr_GesprFuehrdArzt > 0; "Extern"; _EinwillGespraech_::e_Koordinator_fk_User) in Zeile 83 um Extern ergänzt
