### ISSUE TITLE
GTMV/ Einwilligungsgespräch löschen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#728]
Hallo, Bitte Einwilligungsgespräch mit der ID 9459 löschen, danke
Spender ID 12108

![image](https://user-images.githubusercontent.com/22314271/86217753-38b7d080-bb80-11ea-9324-2309e7835382.png)

**Comment by mprueter** [comment]
Ich habe den Datansatz gelöscht. 

Insgesamt ist die derzeitige Situation aber unbefriedigend:

Für jedes neue Einwilligungsgespräch, das angegelegt wird, wird auch ein SpdProzessSchritt angelegt, ohne das der SpdProzSchritt konkret mit einem Datensatz in der Tabelle Einwilligungsgespräch verknüpft wäre. Mit der Folge, dass jeder SpdProzessschritt gesondert freigegeben werden kann und soll. Das ist vom Grundsatz her auch richtig, allerdings werden bei _**jedem**_ SpdProzSchritt _**alle (!)**_ Einwilligungsgespräche gezeigt, weil die Verknüpfung nur über das Basisdokument erfolgt. Jedem SpendenProzSchritt ist nicht eindeutig ein Dokument zugeordnet... Mit anderen Worten: Sie können momentan nur alle Einwilligungsgespräche auf einmal freigeben. Und müssen dann aber die überflüssigen SpendenProzschritte wieder löschen oder diese ebenfalls freigeben (das gilt dann eigentlich ja auch wieder für alle Einwilligungsgespräche)...


Dieses Problem stellt sich auch beim Löschen. Falls versehentlich ein Einwilligungsgespräch zuviel angelegt wurde, wurde dafür auch ein SpendenProzSchritt angelegt. Den können Sie zwar löschen, weil er aber keinen Bezug zu einem konkreten Einwilligungsgespräch hat, können Sie den Datensatz in der Tabelle Einwilligungsgespräch nicht löschen.

Wir sollten also unbedingt klären, ob die Einwilligungsgespräche nicht auch immer mit den jeweiligen SpdProzSchritten verknüpft sein sollten. Dann würde es reichen, wenn man den SpdProzSchritt löschen kann, da dann auch automatisch das konkrete Einwillligungsgespräch gelöscht werden kann.

Das gleiche m.E. gilt im übrigen auch mindestens für folgende Prozessschritte:

Einwilligungsgespräch anlegen
Meldung mobiles Entnahmeteam
Blutproben-Hämodilution anlegen
Untersuch. Antrag Labor anlegen
Koordinatorwechsel
Entnahmebericht anlegen

**Comment by mprueter** [comment]
siehe auch #730

**Comment by Toelk-A** [comment]
### Wir sollten also unbedingt klären, ob die Einwilligungsgespräche nicht auch immer mit den jeweiligen SpdProzSchritten verknüpft sein sollten. Dann würde es reichen, wenn man den SpdProzSchritt löschen kann, da dann auch automatisch das konkrete Einwillligungsgespräch gelöscht werden kann.

-> Dies würde vieles vereinfachen und eine Menge "Klicks" sparen... und ist auch userfreundlicher... :-)
