### ISSUE TITLE
Prozesschritt medizinische Indikationsprüfung - Bemerkungsfeld

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#73]
Das Bemerkungsfeld bitte unterteilen in "strukturierte Adresssuche für 5 Ärzte" und "Bemerkungen"

![image](https://cloud.githubusercontent.com/assets/22314271/21608660/3e10b3a8-d1be-11e6-9586-28748b49dc40.png)

**Comment by chrbusch** [comment]
Das ist vom Platz her ziemlich knapp, bitte ausprobieren; würden vier Ärzte reichen?

![bildschirmfoto 2017-01-17 um 12 12 28](https://cloud.githubusercontent.com/assets/1241899/22018301/7917e93a-dcae-11e6-8255-96f3a08d232b.JPG)

**Comment by Toelk-A** [comment]
Wir stellen uns das Bemerkungsfeld als 2 spaltige Tabelle vor:

In der "linken Tabellenspalte" trägt man den Arzt ein und der "rechten dazugehörigen Tabellenspalte" die Bemerkungen. So sollte es keine Platzprobleme geben

**Comment by chrbusch** [comment]
Soll es also Bemerkungen PRO ARZT geben?

**Comment by chrbusch** [comment]
Ich habe das mit Dr. N. am Tel. gerade geklärt!
