### ISSUE TITLE
GTMV/ PDF Einwilligungserklärung

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#731]
Prozessschritte
Abschnitt IV Gesprächsergebnis
Gesprächsverlauf

Neuerdings wird das Einwilligungsgespräch durch das Audit überschrieben. Dies war vorher nicht so. Bitte prüfen:

![image](https://user-images.githubusercontent.com/22314271/86446347-1f478d80-bd14-11ea-8f26-20c4a20164f7.png)

**Comment by Toelk-A** [comment]
Hallo Herr Prüter, das Audit wurde vorher nie auf dem Einwilligungsgespröch abgebildet. Aus irgendeinem grund ist dies jetzt so. Bitte wieder ausblenden

**Comment by mprueter** [comment]
Soll das generell nie gedruckt werden oder nur nicht in der Spenderakte?

**Comment by Toelk-A** [comment]
nur nicht in der Spenderakte - das war auch schonmal so programmiert.

**Comment by mprueter** [comment]
Aber das ist doch im Moment auch so. Es wird immer angeziegt, außer beim Druck in die Spenderakte...
