### ISSUE TITLE
GTMV/ Entnahmebericht Seite 3 Abschnitt "Freigabe zur Gewebaufbereitung" Arztunterschrift gesetzt, obwohl noch nicht unterzeichnet

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#732]
Hallo Herr Prüter,

im Rahmen der Verbesserungsprogrammierungen des Entnahmberichtes ist mir etwas aufgefallen. Der Arzt inkl. Arztunterschrift soll aus dem Prozessschritt "Freigabe Gewebeentnahme" gezogen werden. Das funktioniert. ALLLERDINGS wird die Unterschrift bereits gesetzt, obwohl der Arzt im Prozessschritt "Freigabe Gewebeentnahme" noch gar nicht unterzeichnet hat. Das Geht natürlich nicht. Bitte Programmierung prüfen und entsprechend anpassen.

![image](https://user-images.githubusercontent.com/22314271/86584793-c0894a80-bf85-11ea-9a44-15c208a563bd.png)

**Prozessschritt Freigabe Gewebeentnahme**

![image](https://user-images.githubusercontent.com/22314271/86585090-34c3ee00-bf86-11ea-8a80-313d54d9cdb8.png)

**Comment by mprueter** [comment]
Das Problem ist jetzt behoben. 
Ich hatte versehentlich auf ein falsches ID-Feld Bezug genommen. Bitte prüfen Sie das ganze noch einmal kritisch...

**Comment by Toelk-A** [comment]
Getestet wie folgt:

1) NIf hatte im Layout Freigabe bereits unterzeichnet mit digitaler US (habe heir von NIF auf DR Manecke gewechselt 
2) MSG Entnahmebericht geöffnet
3) folgendes Bild:

Dr Manecke als "Klarname" eingesetzt -> daneben steht die Unterschrift von Dr Nitschke

![image](https://user-images.githubusercontent.com/22314271/88797150-2773db00-d1a3-11ea-8fbc-c5887ee7711b.png)

**Comment by mprueter** [comment]
Das Problem war, dass bei Ändern des ausgewählten Users (also nicht der Unterschrift!), der User für die Unterschrift nicht automatisch geändert oder gelöscht wurde. Das Unterschriftenfeld ist so definert, dass es das Bild nur anzeigt, wenn beide User übereinstimmen. Das hatte ich so im Entnahmebericht nicht berücksichtigt.

Danke, dass Sie das so intensiv getestet haben!

Ich habe das User-Wechselscript jetzt auch so geändert, dass i.R. der Unterschriften-User jetzt immer gelöscht wird, wenn ein anderer User für die Anzeige ausgewählt wird.

_Bisher war es so, dass wenn bspw. NIF bereits unterschrieben hatte und Sie danach doch Dr. Maneke auswählen, die Unterschrift zwar nicht angezeigt wurde, solange Dr. Maneke aber nicht selbst unterzeichnet hatte war der User von NIF noch hinterlegt. Mit der Folge, dass es u.U. bei einer erneuten Auswahl von NIF dessen Unterschrift bereits vorhanden gewesen wäre, obwohl er noch gar nicht aktiv unterzeichnet hätte._

Das Problem sollte jetzt also behoben sein. 

techn. Anmerkung:
User04normal. Zeile 169 ff. ergänzt

**Comment by Toelk-A** [comment]
okay, ich behalte dies im Auge
