### ISSUE TITLE
GBMV/ Hidden Button VP 20c

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#733]
Hallo Dr Busch,

im Rahmen der "neuen Rechteverteilung in Ornella benötigen wir den "Hidden Button VP20c" + "Hidden Button Spaltlampe".

**Comment by mprueter** [comment]
Ist "Hidden Button VP20c" nicht identisch mit dem schon vorhandenen Button "VP GTMV"?
Oder meinen Sie einen Button in der die Kombination "Hidden Button VP20c" UND "Hidden Button Spaltlampe" darstellt?
(...also etwa "VP mit Spaltlampe")

**Comment by mprueter** [comment]
Ich habe erstmal die beiden gewünschten Hidden Butons angelegt. Die müssten jetzt noch den betreffenden Usern zugeordnet werden...

**Comment by Toelk-A** [comment]
erleidgt
