### ISSUE TITLE
GMBV/ Prozessschritt Spaltlampenbefund

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#734]
OG Transplantatdetails
Prozesschritt Spaltlampenbefund pkBPS= 89

![image](https://user-images.githubusercontent.com/22314271/86895834-57304580-c105-11ea-96d4-3a9e6b9f792b.png)

### 1) Falscher Mandant
Es werden im GBMV Bereich Mitarbeiter des Mandanten GTMV angezeigt. Bitte Rechteverteilung korrigieren.
Abgebildet werden dürfen heir nur Mitarbeiter die den "Hidden Button Spaltlampe" besitzen -> Siehe Ticket #733 

![image](https://user-images.githubusercontent.com/22314271/86896012-9bbbe100-c105-11ea-8ef3-31d2fed66cfe.png)
![image](https://user-images.githubusercontent.com/22314271/86896045-a8d8d000-c105-11ea-97bd-0369b24ae0d9.png)

**Comment by mprueter** [comment]
Liebe Frau Tölk, Sie müssen zunächst den neuen HiddenButton "Spaltlampe" den entsprechenden Usern zuordnen. Da kann ich das umstellen. Im Moment habe ich es erst einmal auf die User mit der Kombination "Arzt GMBV" und Mandant=GBMV eingestellt... das kann ich aber schnell umstellen, wenn Sie die User richtig gesetzt haben.

**Comment by Toelk-A** [comment]
ich habe eine neue Rolle erstellt:

VP 20c GBMV Spaltlampe -> für unsere Augenärztin, da diese derzeit nur die Spaltlampe unterzeichnet (NIB + KNA nicht).
NIB + KNA unterzeichnen die restlichen VP 20c Dokumente - Dr Schröder aber nicht.... so kann man es derzeit glaube ich am Besten filtern.

![image](https://user-images.githubusercontent.com/22314271/88885139-39538d80-d238-11ea-9c11-ec7d2a4b65de.png)

Den Hidden Button Spaltlampe habe ich der Rolle bereits hinzugefügt

**Comment by mprueter** [comment]
Okay, ist umgestellt. Das sieht dann jetzt so aus:

![Bildschirmfoto 2020-07-30 um 14 21 52](https://user-images.githubusercontent.com/3273572/88922229-1fce3800-d270-11ea-97f0-09fb7c8c953e.png)

**Comment by Toelk-A** [comment]
Danke
