### ISSUE TITLE
GBMV/ Personalmodul Export Arbeitsstunden MA GTM-V

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#735]
Bitte Export erstellen bzw. wie folgt anpassen:

### 1) Export pro Mitarbeiter existiert bereits
Persönlicher Kalender 
![image](https://user-images.githubusercontent.com/22314271/86904327-d414ec80-c110-11ea-8f0c-3bb5d0ae5bcc.png)

Diesen bitte wie folgt anpassen

### 2) Neuen Button anlegen
Bitte im Personalmodulmenü -> SUPERVISOR-> neuen Button "Exporte Arbeitszeit aller MA" anlegen

![image](https://user-images.githubusercontent.com/22314271/86904466-0aeb0280-c111-11ea-89e7-a1edac17e34a.png)

### 3) Zeitabfrage

Abfrage Zeitraum einbauen

### 4) Mandant

Abfrage GBM-V / GTM-V oder "Beide"

### 5) Aufteilung der Excel nach Teams pro Mandant
![image](https://user-images.githubusercontent.com/22314271/86905129-ee02ff00-c111-11ea-88d4-5171e4710d73.png)

### 6) Aufteilung Excel nach "Festangestellt" + "Geringfügig Beschäftigt" / Praktikanten
![image](https://user-images.githubusercontent.com/22314271/86905448-5baf2b00-c112-11ea-892b-917e87bfffd6.png)

**Comment by chrbusch** [comment]
Techn. Anm.: 
1) Das alte Script für einen MA ist "Einsatz43A.XLS-Export der Einsatz-DSe..."
2) Das neue Script ist "Einsatz43B.XLS-Export Einsatz-DSe mit Suchoptionen/  #735"
