### ISSUE TITLE
GTMV/ Auditlog Chat

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#736]
Bitte prüfen, ob der Auditlog auch die Zuordnung zum Mitarbeiter inkl. Datum und Uhrzeit loggt.

![image](https://user-images.githubusercontent.com/22314271/87280382-5d059c80-c4f2-11ea-89a5-b6d156ab5e3e.png)

**Comment by Toelk-A** [comment]
Hallo Herr Prüter,

die Zuordnung zum Mitarbeiter wird nicht geloggt:

![image](https://user-images.githubusercontent.com/22314271/88140356-e0f60d80-cbf1-11ea-89e9-2690edb89d38.png)

**Comment by mprueter** [comment]
Das Problem ist jetzt behoben. Sowohl der User, als auch das Datum werden sicher geloggt. Es gilt allerdings eine Besonderheit zu beachten:

Die Uhrzeit wird beim Anlegen eines neuen Chatbeitrages immer automatisch auf 10:00 Uhr gesetzt. Dieser Vorgang kann nicht im Auditlog erfasst werden. Sollten Sie aber diesen Wert ändern (also das Feld "betreten"), wird die Änderung geloggt.

**Comment by Toelk-A** [comment]
Der Erstwert des Koordinators von "leer" auf "TOA" wird nicht geloggt -> Änderung von "TOA" auf "WIV" wird geloggt

![image](https://user-images.githubusercontent.com/22314271/88796843-a61c4880-d1a2-11ea-8548-12590eeaec20.png)

**Comment by mprueter** [comment]
Dieser Datensatz wurde schon am 22.7.20 angelegt. Da gab es die neue Funktion noch nicht. Ich habe das gerade mit Dr. Nitschke einmal durchgespielt und da war alles gut. 

Können Sie das bitte ggf. noch einmal an einem neuen Datensatz prüfen?

**Comment by Toelk-A** [comment]
okay :-)
