### ISSUE TITLE
Datenbank generiert identische Kennnummern-bitte unterbinden

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#74]
![image](https://cloud.githubusercontent.com/assets/22314271/21608712/86c2bf88-d1be-11e6-8ba3-b6f18b2eb6b0.png)

**Comment by chrbusch** [comment]
Es gibt schon 8 solcher Dubletten; die von mir von Anfang für ungut gehaltene Regel für die KennNr erzwingt dies ja auch, wenn für beide Spender derselbe Meldezeitpunkt eingetragen wird!

Ich selbst kann da wenig tun; Sie müssen mir bitte eine neue, bessere Regel nennen, wobei ich dabei auch gerne behilflich bin.

![bildschirmfoto 2017-01-03 um 14 19 12](https://cloud.githubusercontent.com/assets/1241899/21608926/d8f01bc4-d1bf-11e6-945e-c41ca361185b.JPG)

**Comment by chrbusch** [comment]
PS: Mein Vorschlag: Nicht die Meldezeit als zweiten Bestandteil der KennNr, sondern eine "LaufNr pro Stunde"
Es wäre dann zB in den beiden ersten oben gezeigten Fällen:
080716-1001-.... und  (der erste Fall zwischen 10:00 und 10:59)
080716-1002-...  (der zweite solche Fall)

**Comment by Toelk-A** [comment]
Gesetzt den Fall Meldezeit und Datum sind identisch, wäre es möglich ein Fenster zu öffnen in dem nach der Richtigkeit der Fallnummer gefragt wird? Denn dies ist der eigentliche Fehler.

**Comment by chrbusch** [comment]
ZURÜCK, ich sehe gerade, dass die KennNr-Dubletten alle fälschlich doppelt angelegte Spender sind!
Wir wollten telefonieren...

**Comment by chrbusch** [comment]
Neben der Aufn.Nr wird nun zur Vermeidung von Dubletten auch das Spender-Geburtsdatum angefragt; bitte testen!

**Comment by Toelk-A** [comment]
ok super

**Comment by Toelk-A** [comment]
Wir hatten vor 2 Tagen wieder das Problem, der identischen Spenderkennummer. 

1) Ist es möglich Ornella eine Regel zu geben die besagt: "WENN Meldedatum UND Meldezeit UND Region UND Koordinator gleich sind" bitte Alarm   "Achtung identische Spenderkennummer" ausgeben? 

ODER 

2) Vielleicht könnte Ornella auch in diesem Fall einfach automatisch die Meldezeit um +/- 1 Minute verändern?

**Comment by chrbusch** [comment]
Ich habe es jetzt so gemacht, wie unlängst mit Dr. N. besprochen: Existiert die "normale" KennNr schon, wird automatisch die Minute so lange um 1 erhöht, bis eine eindeutige KennNr entsteht
Als Test habe ich einen Testspender erstellt, dessen KennNr-relevante Daten übereinstimmen mit denen von ID 1388, v.a. di Uhrzeit 12:40.
Dieser bekam dann automatisch, siehe Bild, die KennNr zur Uhrzeit 12:41

![bildschirmfoto 2017-01-23 um 07 29 28](https://cloud.githubusercontent.com/assets/1241899/22193755/dd592254-e13d-11e6-9c1b-8da5ec8da4c6.JPG)
