### ISSUE TITLE
GTMV/ Bitte Entnahmebericht OG löschen 3511

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#740]
Spender ID 12349

![image](https://user-images.githubusercontent.com/22314271/88369898-4f250680-cd91-11ea-90e6-0c65a92673af.png)

**Comment by mprueter** [comment]
Die Entnahme ist gelöscht. 

Sie können das aber auch selber machen. Auf dem Reiter mit den Gewebearten finden Sie ein Portal mit den Entnahmen. Und dort ein Kreuz zum Löschen eines Datensatzes:

![Bildschirmfoto 2020-07-24 um 16 27 11](https://user-images.githubusercontent.com/3273572/88405065-08560180-cdcf-11ea-9fbf-f9b0353a8f60.png)

Das Löschscript war offenbar noch nicht fertig. Ich habe es fertiggestellt...

Es funktioniert jetzt also und Sie können die gelöschte Entnahme jetzt auch im Portal "Löschungen" sehen. Bei Bedarf kann die Entnahme auch wieder hergstellt werden; das funktioniert jetzt auch...

![Bildschirmfoto 2020-07-24 um 16 55 14](https://user-images.githubusercontent.com/3273572/88405393-7bf80e80-cdcf-11ea-8599-8f0c2305c70d.png)

**Comment by Toelk-A** [comment]
super danke
