### ISSUE TITLE
GTMV/ Kühlzeitpunkt Entnahmebericht OG versus Transportbegleitschein OG

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#742]
Hallo herr Prüter,

uns ist aufgefallen, dass die hinterlegten Kühlzeiten im OG Entnahmebericht nicht automatisch in den Transportbegleitschein OG übernommen werden. Der OG Transportbegleitschein passt die Kühlzeiten immer den zuletzte hinterlegten Kühlzeiten in den Entnahmeberichten an. Das heißt im OG Begleitschein werden Kühlzeiten aus dem MSG Entnahmebericht hinterlegt. Hier bitte noch einmal die Beziehung prüfen.

Spender ID 12395

OG ENtnahmebericht
![image](https://user-images.githubusercontent.com/22314271/89004081-b26ae780-d301-11ea-92b8-259bde1812f2.png)

Transportbegleitschein OG
(Zeiten wurden bereits manuell durch uns geändert)
![image](https://user-images.githubusercontent.com/22314271/89004199-ef36de80-d301-11ea-9d86-fb2f7e6ba087.png)

MSG ENtnahmebericht
![image](https://user-images.githubusercontent.com/22314271/89004266-12fa2480-d302-11ea-83c4-5b362a3c4dfd.png)

MSG Transportbegleitschein
(wurde ebenfalls bereits manuell durch uns geändert)
![image](https://user-images.githubusercontent.com/22314271/89004355-4472f000-d302-11ea-8813-11227ef31fd0.png)

**Comment by mprueter** [comment]
Ich verstehe noch nicht ganz, was passieren soll. Aus einem anderen Grund habe habe ich gerade mit Dr. Nitschke telefoniert und ihn hierauf angesprochen. Er meinte, dass ein Transportbegleitschein eigentlich immer an genau einem Entnahmebericht hängen sollte und genau dessen Kühlzeitpunkt wiedergeben sollte. 

Oder ist es so gemeint, dass immer der Kühlzeitpunkt des aktuellsten Entnahmebreichtes eines Spenders (nachträglich?) auch in alle anderen Entnahmeberichte eingetragen werden sollte? Und dann eben auch immer in allen Transportbegleitscheinen die aktuellste Zeit erscheint, weil diese aus dem dazugehörigen Entnahmebericht gezogen wird?

**Comment by Toelk-A** [comment]
genau:

OG Entnahmebericht Kühlzeiten müssen im OG Transportbegleitschein hinterlegt sein (hier hat MSG nichts zu suchen)

Umgedreht gehört der MSG Transportbegleitschein zum MSG Entnahmebericht (hier müssen die Kühlzeiten übereinstimmen) und sind (meistens) verschieden zu den OG Kühlzeiten

**Comment by mprueter** [comment]
Ich habe jetzt mal genau nachgesehen:

Der Transportbegleitschein speist sich aus Feldern des SpdGewebes (es gibt keine eigene Tabelle dafür). Genau genommen ist das so nicht richtig. Besser wäre es wahrscheinlich, wenn der Transportbegleitschein an genau einer SpdEntnahme hinge. Gerade vor dem Hintgerund, dass zukünftig zu einem SpdGewebe auch mehrere Entnahmen möglich seien sollen.

Im Moment ist es so, dass auf dem Transportbegeitschein im Hinblick auf die Kühlzeit die Daten aus der Tabelle Spender (Beginn) angezeigt werden:

![Bildschirmfoto 2020-08-03 um 13 34 52](https://user-images.githubusercontent.com/3273572/89178655-61235800-d58e-11ea-955c-5b2f009f336e.png)

...d.h. wenn hier Daten geändert werden erscheinen diese auch in den Spender-Details:

![Bildschirmfoto 2020-08-03 um 14 01 57](https://user-images.githubusercontent.com/3273572/89180515-363b0300-d592-11ea-87e8-96ebb879ecbd.png)
![Bildschirmfoto 2020-08-03 um 14 02 11](https://user-images.githubusercontent.com/3273572/89180517-36d39980-d592-11ea-94ea-e62d54cc649e.png)


Wenn beim Spender kein Beginn für die Kühlzeit eingetragen wurde, ist auch keine Eintragung im  Transportbegleitschein mehr möglich:

![Bildschirmfoto 2020-08-03 um 13 43 10](https://user-images.githubusercontent.com/3273572/89180661-831ed980-d592-11ea-8a50-2d94bf2a18bd.png)
![Bildschirmfoto 2020-08-03 um 13 43 27](https://user-images.githubusercontent.com/3273572/89180663-83b77000-d592-11ea-966d-96d27c9fb766.png)

Das war auch so gewollt:  #129

Da der Beginn der Kühlzeit grundsätzlich für den Spender gilt, ist dies auch okay so. 

Das Ende der Kühlzeit ist aber abhängig vom Entnahmezeitpunkt (bzw. dem Wert der im jeweiligen Entnahmebericht hinterlegt ist). Für verschiedene Gewebe kann es hier aufgrund der unterschiedlichen Entnahmezeitpunkte auch unterschiedliche Endzeitpunkte für die Kühlung geben. Das gilt aber jeweils pro SpdGewebe (selbst bei mehreren SpdEntn. pro Gewebe erfolgen diese zeitgleich, haben aber ggf. andere Adressaten).

Wenn Sie momentan das Ende der Kühlzeit eintragen, wird dieser Wert beim Spdnder hinterlegt und erschient dann auch bei einem erneuten Transportbegleitschein für ein anderes SpdGewebe. Und wenn Sie den Zeitpunkt dann nach hinten verschieben, weil die Entnahme hier späte statt gefunden hat, ist es so, dass dieser neue Wert dann auch bei einem erneuten Druck des vorherigen Transportbegleitscheines erscheint. 

Genau genommen muss also das Ende der Kühlzeit immer beim Spendengewebe festgehalten werden. Oder vielleicht sogar bei der SpdEntnahme (falls es zukünftig evtl. zeitlich unterschiedliche Entnahmen eines Gewebes geben sollte).

Aufgaben aus meiner Sicht:
Transportbegleitscheine immer in Relation zu einer SpdEntnahme 
Ende der Kühlzeit aus dem SpdGewebe oder besser aus der dann zugehörigen SpdEntn. holen
Dort sind die Daten ja auch schon für die Entnahme hinterlegt:

![Bildschirmfoto 2020-08-03 um 14 25 09](https://user-images.githubusercontent.com/3273572/89182117-5a4c1380-d595-11ea-934e-63136d6006d9.png)

**Comment by Toelk-A** [comment]
Spender ID 12494

Kühlzeitpunkt im OG Entnahmebericht dokumentiert

![image](https://user-images.githubusercontent.com/22314271/89783560-6c8afc00-db17-11ea-85a8-77e7c682b567.png)

Transportbegleitschein

![image](https://user-images.githubusercontent.com/22314271/89783596-7e6c9f00-db17-11ea-8ee9-1995e56e28b4.png)


Bitte noch einmal prüfen

**Comment by mprueter** [comment]
Um das Problem jetzt ein für alle Mal und sauber zu lösen, werde ich wie folgt vorgehen (auch vor dem Hintergrund, dass es zukünftig mehrere Entnahmen für ein SpdGewebe geben könnte):

Transportbegleitscheine werden in Zukunft nicht mehr auf Basis der Tabelle SpdGewebe erstellt, sondern basieren auf ter Tabelle SpdEntn.

1. Transportbegleitscheine werden in Zukunft nicht mehr auf Basis der Tabelle SpdGewebe erstellt, sondern basieren auf der Tabelle SpdEntn. Einige Daten werden jetzt sowieso schon aus dieser Tabelle geholt. Die momentan beim Gewebe hinterlegten Felder für den Transportbegleitschein werde ich in die Tabelle SpdEntn kopieren. Anschließend wird ein neues Layout erzeugt, das dem alten entspricht, aber auf SpdENtn basiert. 

2. Wenn ich es richtig sehe, wird der SpdProzSchr. "Transportbegleitschein anlegen" immer dann erzeugt, wenn ein neues SpdGewebe angelegt wird:

![Bildschirmfoto 2020-08-11 um 14 04 29](https://user-images.githubusercontent.com/3273572/89895170-a02f5a00-dbdb-11ea-9817-1825aa692636.png)

![Bildschirmfoto 2020-08-11 um 14 04 36](https://user-images.githubusercontent.com/3273572/89895184-a58ca480-dbdb-11ea-905b-25d87a0a365b.png)

...das wird in Zukunft immer erst dann erfolgen, wenn auch ein Entnahmebericht angelegt wird. Für jeden Entnahmebericht gibt es dann immer einen speziellen Transportbegelitschein.


3. Da es schwierig wird, die vorhandenen Daten alle umzukodieren würde ich den bisherigen BasisProzSchr. für den Transportbegleitschein stilllegen und einen neuen BasisProzSchr definieren, der sich auf die SpdEntn bezieht und das neue Layout anspricht. Im Portal erscheint dann das bekannte "aF" für die bisher erstellten Transportbegleitscheine. Diese werden dann wie bisher aufgerufen werden, können aber nicht mehr erstellt werden.

Für Sie ändert sich eigentlich gar nichts, nur das Datenmodell im Hintergrund wird angepasst. Und es kann immer sicher der Bezug zu den Daten aus der SpdEntn. hergestellt werden (Kühlzeitpunkte), da wir ja bei genau dieser sind!

**Comment by Toelk-A** [comment]
Hallo Herr Prüter Sie haben mein "Go". Bis Morgen :-)

**Comment by Toelk-A** [comment]
ist dies mit dem neuen Prozessschrittportal abgegolten? :-)

**Comment by mprueter** [comment]
Ja, da beide Layouts auf derselben Tabelle beruhen und dieselben Felder anzeigen:

![Bildschirmfoto 2021-02-01 um 15 13 10](https://user-images.githubusercontent.com/3273572/106470142-724b1400-64a0-11eb-947c-2432568ccc7e.png)


![Bildschirmfoto 2021-02-01 um 15 08 12](https://user-images.githubusercontent.com/3273572/106470160-76773180-64a0-11eb-8e0c-fc0f6a6c1c8f.png)

**Comment by Toelk-A** [comment]
DANKE!
