### ISSUE TITLE
DRINGEND I GBMV/ Anpassung Formular Übergabeprotokoll für OG

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#744]
Hallo Herr Prüter,

ich hatte die Dringlichkeit der GBM-V Mitarbeiter überlesen. Ist es möglich als Prio 1 das genannte Dokument anzupassen?

[3.4.3.14.3 F Übergabeprotokoll für OG-Transplantate-04-28.07.20_NEU.pdf](https://github.com/chrbusch/GTM-V/files/5015706/3.4.3.14.3.F.Ubergabeprotokoll.fur.OG-Transplantate-04-28.07.20_NEU.pdf)

![image](https://user-images.githubusercontent.com/22314271/89179008-1fdf7800-d58f-11ea-9357-d947e4cb0802.png)

Bitte auch hier entsprechend hinterlegen

![image](https://user-images.githubusercontent.com/22314271/89179047-3b4a8300-d58f-11ea-9ee5-bff7cd3168cb.png)

**Comment by mprueter** [comment]
Ist jetzt umgestellt. Bitte testen.

**Comment by Toelk-A** [comment]
auch hier danke für die schnelle Umsetzung
