### ISSUE TITLE
DRINGEND II GBMV/ Haltbarkeit KMII anpassen (Lagerung in Transportmedium)

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#745]
Die Haltbarkeit in KMII muss auf 5 Tage reduziert werden (vorher waren es 6 Tage) Da diese Bestandteil des SECs ist, wissen wir selbst nicht, ob dort noch weitere Anpassungen nötig sind?!

![image](https://user-images.githubusercontent.com/22314271/89180158-764db600-d591-11ea-8396-91ab734e88d8.png)

### SEC CODE

PKS Code ist Teil des SEC Codes und beinhaltet das Haltbarkeitsdatum der Hornhaut
![image](https://user-images.githubusercontent.com/22314271/89184917-b9138c00-d599-11ea-8df4-46d390fa2586.png)
![image](https://user-images.githubusercontent.com/22314271/89184984-cfb9e300-d599-11ea-97be-6bbc07a5dd7e.png)

SEC COde wird hier in folgenden Dokumenten abgebildet:

![image](https://user-images.githubusercontent.com/22314271/89185082-f4ae5600-d599-11ea-839e-5cfb9ee6913d.png)

![image](https://user-images.githubusercontent.com/22314271/89185204-23c4c780-d59a-11ea-906c-10a7a505c712.png)

![image](https://user-images.githubusercontent.com/22314271/89185246-36d79780-d59a-11ea-8f4b-f5099fff709f.png)

![image](https://user-images.githubusercontent.com/22314271/89185285-4951d100-d59a-11ea-8dd5-d4999d075313.png)

**Comment by mprueter** [comment]
Ist umgestellt, und sollte jetzt überall richtig angezeigt werden. Die Änderung gilt für alle Transplantate bei den die ... ab dem 3.8.20 begonnen hat.


techn. Anmerkung:
Änderung des Feldes k_Datum_Haltbarkeit in  SpdTransplatate:

_
Case( 
  d_Datum_Haltbarkeit; d_Datum_Haltbarkeit;

  SpdTranspl.SpdPraep::_fk_GewebeArt_T = "OG";

  Case(

    /*wegen neuem Medium ab 3.8.20 -> MHD nur 5 Tage*/
    k_PS126D_DatumErl_LagTranspMedium > GetAsDate("02.08.20"); k_PS126D_DatumErl_LagTranspMedium +5;


    k_PS126D_DatumErl_LagTranspMedium; k_PS126D_DatumErl_LagTranspMedium +6;


    d_Datum_Herstellung; d_Datum_Herstellung +28
  );

 SpdTranspl.SpdPraep::_fk_GewebeArt_T = "KVG";
  Case( 
    k_PS126D_DatumErl_LagTranspMedium; k_PS126D_DatumErl_LagTranspMedium + 5*365 ;
    d_Datum_Herstellung; d_Datum_Herstellung + 5*365 ;

  )

)
_

**Comment by Toelk-A** [comment]
Vielen Dank für die schnelle Umsetzung!
