### ISSUE TITLE
GBMV/ Artikel Deatils ID 303 -> 2,5 in Werteliste aufnehmen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#746]
Wir benötigen für das Kulturmedium unter „X-fach anw.bar für“ die Auswahl 2,5 (siehe Screenshot).

![image](https://user-images.githubusercontent.com/22314271/89267712-e0209b00-d637-11ea-936f-d2472c6579f7.png)

![image](https://user-images.githubusercontent.com/22314271/89267837-08a89500-d638-11ea-88cf-ba83b4ef39ad.png)

![image](https://user-images.githubusercontent.com/22314271/89267963-2f66cb80-d638-11ea-9ffd-125b6cb01b81.png)

Hier wird der Bestand automatisch nach einscannenabgezogen. Bitte wie oben erwähnte einen "2,5" fachen bestand in der Werteliste anlegen :-)

Danke

**Comment by mprueter** [comment]
Ist jetzt vorhanden:

![Bildschirmfoto 2020-08-10 um 11 04 48](https://user-images.githubusercontent.com/3273572/89767021-6a19a980-daf9-11ea-98ce-3a32feec3979.png)
