### ISSUE TITLE
GTMV/ MSG Entnahmebericht -> Entscheidung Transplantation / Forschung fehlt

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#747]
Hallo Herr Prüter,

im MSG Entnahmebericht wir die Entscheidung zu "nur" Transplantation abgebildet alerdings fehlt die Zustimmung zur Forschung:

![image](https://user-images.githubusercontent.com/22314271/89285549-e111f680-d650-11ea-9fdd-5d0ca713d1e8.png)

Das Ergebnis wird aus dem Einwilligungsgespräch übernommen:;

![image](https://user-images.githubusercontent.com/22314271/89285628-030b7900-d651-11ea-8573-a2ed925d5f33.png)

Können Sie dies bitte noch einmal prüfen (auch für KVG Entnahmeebricht)
danke

**Comment by mprueter** [comment]
Das Problem ist jetzt gelöst, für alle Gewebearten.

Aber ich habe noch eine Frage? Momentan kann man im Entnahmebericht die oben markierten Eingaben ändern. Da hier direkt Daten aus dem finalen Einwilligungsgespräch angeziegt werden, werden bei einer Änderung im Entnahmebericht auch gleichzeitig die Daten im Einwilligungsgespräch geändert. Soll das wirklich so sein? Oder soll ich die Felder im Entnahmebericht sperren?

**Comment by Toelk-A** [comment]
### Oder soll ich die Felder im Entnahmebericht sperren?

Bitte die Felder sperren

**Comment by mprueter** [comment]
Sind jetzt alle gesperrt.
