### ISSUE TITLE
GTMV/ Artikel Details - Etikettendruck - Schrift verrutscht auf Voretikett

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#751]
Etiketten-> erste Zeile wird immer auf dem Voretikett abgebildet ( bitte LOT und MHD 1 Zeile nach unten ziehen (direkt über Barcode abbilden) dann sollte die erste Zeile (Artikelname) auch auf dem Etikett abgebildet sein .

Blaue Kante zeigt Etikettende (geld befindet sich auf dem darüberligenden Etikett)

![image](https://user-images.githubusercontent.com/22314271/89873328-8cbfc700-dbba-11ea-966b-a4be43aefca9.png)

![image](https://user-images.githubusercontent.com/22314271/89873472-c7c1fa80-dbba-11ea-88ad-3a23af71a158.png)

**Comment by mprueter** [comment]
Ist umgestellt. Bitte jetzt einmal testen...

**Comment by Toelk-A** [comment]
danke
