### ISSUE TITLE
GTMV/ Lagerwirtschaft Artikel ausscannen Packung versus Einzelartikel- Falsche Buttonbelegung

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#752]
Einzelartikel sollen ausgescannt werden:
![image](https://user-images.githubusercontent.com/22314271/89873821-4d45aa80-dbbb-11ea-8742-4c06d070d193.png)

dann
![image](https://user-images.githubusercontent.com/22314271/89873911-69e1e280-dbbb-11ea-8b36-b288cd5f7dec.png)

![image](https://user-images.githubusercontent.com/22314271/89873944-749c7780-dbbb-11ea-8424-4155aca008af.png)

![image](https://user-images.githubusercontent.com/22314271/89873981-80883980-dbbb-11ea-9226-2d50d253fb94.png)

Wir möchten Einzelartikel auscannen, da wir eine "angebrochene packung ahben. Wir klicken also auf einzeln (und nciht auf 50 - eintspricht vollständiger Packung).

![image](https://user-images.githubusercontent.com/22314271/89874062-9dbd0800-dbbb-11ea-9eed-c1ea313e1092.png)

Hier scheint der "einzelbutton" mit dem "50" Button falsch belegt zu sein (vertauscht?) Wir hatten keien Möglichkeit die konkrete Anzahl der auszuscannenden Artikel einzugeben.

Bitte dringend prüfen!

![image](https://user-images.githubusercontent.com/22314271/89874148-be855d80-dbbb-11ea-8afe-2030a8bb04cc.png)

**Comment by mprueter** [comment]
Der Fehler ist gefunden und korrigiert. Bitte testen...

**Comment by Toelk-A** [comment]
funkitoniert!
