### ISSUE TITLE
GBMV/ Anpassung Dokument Herstellungsprotokoll 1 OG

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#754]
Die GBM-V hat ein neues Dokument, dass wir in Ornella bitte geändert brauchen, siehe Anhang. (bitte auch die Fußleiste aktualisieren) Da das Dokument mit dem heutigen Tag (vergangenen Freitag)  in Kraft gesetzt wurde, benötigen wir es bitte so schnell wie es geht.

[3.4.3.1 F Herstellprot 1 (Mat) OG-09-06.08.20.pdf](https://github.com/chrbusch/GTM-V/files/5082520/3.4.3.1.F.Herstellprot.1.Mat.OG-09-06.08.20.pdf)

Bei dem Dokument entfällt der Hersteller / Lieferant und wir benötigen den Zugriff auf die Haltbarkeit. Das muss, denke ich, neu programmiert werden, stellt das ein Problem dar? 

Das Feld für die Haltbarkeit der jeweiligen Charge habe ich einmal markiert. Das sollte dann in der neuen Version abgebildet werden.

![image](https://user-images.githubusercontent.com/22314271/90370045-03523e00-e06d-11ea-9807-c2d331cffd12.png)

**Comment by mprueter** [comment]
Das ist die gleiche Anforedrung wie #753, oder?

**Comment by Toelk-A** [comment]
Hallo Herr Prüter, es ist tatsächlich so, dass sich das Dokument komplett geändert hat :-(

Ich reiche Ihnen das "neue vollständige (inkl. Transplantatnummer) spätestens bis Freitag nach.

Die Kopfzeile hat sich geändert entsprechend der oben hochgeladenen Datei.
Transplantatkennummer bitte drin lassen, Abschnitt sterile Mehrweginstrumente komplett löschen und die Tabelle, wie im o.g. Dokument anpassen. (Daten bekommen Sie aus den Artikeldetails) -> hierzu können wir auch gern noch einmal telefonieren.

VG

**Comment by Toelk-A** [comment]
Hallo Herr Prüter,

wie gestern kurz angedeutet anbei das neue "vollständige " Protokoll.

VG 
[3.4.3.1 F Herstellprot 1 (Mat) OG-09-06.08.20.pdf](https://github.com/chrbusch/GTM-V/files/5103205/3.4.3.1.F.Herstellprot.1.Mat.OG-09-06.08.20.pdf)

**Comment by Toelk-A** [comment]
danke für Ihre Bemerkung-... anbei die neuste Version inkl. digitaler US

[3.4.3.1 F Herstellprot 1 (Mat) OG-09-06.08.20_neu.pdf](https://github.com/chrbusch/GTM-V/files/5117263/3.4.3.1.F.Herstellprot.1.Mat.OG-09-06.08.20_neu.pdf)

**Comment by mprueter** [comment]
Es ist alles umgebaut. Bitte einmal testen....
