### ISSUE TITLE
GBMV/ Personalmodul - Überstunden Berichte + Stundenreport "in einem Abwasch drucken"

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#755]
Zum Monatsbeginn werden immer die Überstundenberichte und Stundenreports der Mitarbeiter (Festangestellt und Minijobber ausgedruckt.

![image](https://user-images.githubusercontent.com/22314271/90498010-12f28500-e148-11ea-9090-9f078e8c946c.png)

### 1) Neuer Button "Berichte / Reports ausdrucken"
Bitte neuen Button im personalmodul unter "Supervisor" erstellen
![image](https://user-images.githubusercontent.com/22314271/90498213-4df4b880-e148-11ea-8a41-fff5cb703ca5.png)

### 2) Filter Mandant/Prüfung einbauen
Nach Klick auf Button soll gefragt werden:
**2A) Mandant GBM-V / GTM-V/ Alle**
![image](https://user-images.githubusercontent.com/22314271/90501611-e8ef9180-e14c-11ea-8565-75016c8db743.png)

**2B) Prüfung,** 
ob jeder Tag im System abgeschlossen wurde

![image](https://user-images.githubusercontent.com/22314271/90498471-ac219b80-e148-11ea-9f10-d619f04d1e4e.png)
Jeder Tag muss also mit einer "2" markiert sein

-> Wenn dies nicht erfüllt ist, bitte Fehlermeldung mit Info welcher Mitarbeiter an welchem Tag "nicht abgeschlossen" ist

**2C) Prüfung Teil 2 - "Monatssummen aktualisieren"**
Bevor die Berichte gedruckt werden können, muss der folgende Knopf automatisiert gedrückt werden " Monatssummen aktualisieren"

Dies läuft automatisiert über Nacht. falls kurz vor dem Klick auf den o.g. Button noch einmal etwas geändert wurde, muss also "aktualisiert" werden
![image](https://user-images.githubusercontent.com/22314271/90501782-26ecb580-e14d-11ea-81ef-d5e0a760dc88.png)

**2D) wenn alle Prüfläufe in Ordnung sind, können die Stundenberichte gedruckt werden**

### 3) Achtung "Minijobber mit Stundenübertrag"
Minijobber dürfen nicht mehr als 450€ pro Monat ausgezahlt bekommen. Werden Mehrstunden geleistet, so werden diese auf den nächsten Monat übertragen. ( Dies macht das System automatisch). Die Abfrage müsste hier irgendwie mit eingebunden werden. (Minijobber sind mit "ja" gekennzeichnet")

![image](https://user-images.githubusercontent.com/22314271/90502391-0a04b200-e14e-11ea-92cc-b436f4ce07d9.png)

**Comment by Toelk-A** [comment]
Bei den Minijobberinnen fehlt Mitarbeiterin Wawra für den Monat August 

![image](https://user-images.githubusercontent.com/22314271/92105195-c57e4500-ede2-11ea-98e4-4b105fa65ed4.png)


![image](https://user-images.githubusercontent.com/22314271/92104656-ea25ed00-ede1-11ea-9e87-ef6367f5cac0.png)

**Comment by mprueter** [comment]
War einkleiner Fehler in der Datumssuche, sorry. Ist jetzt korrigiert.

**Comment by Toelk-A** [comment]
erledigt
