### ISSUE TITLE
Anpassung Kontoimport APO-Bank

### ISSUE THREAD

**Issue by mprueter** [chrbusch/GTM-V#756]
Der Import der Kontodaten muss an die geänderten Exportdateien angepasst werden.

Problem: Anstatt div. VZW-Felder un einer klaren Struktur gibt es jetzt nur noch ein Textfeld mit div. Werten in Anführungszeichen.

Lösung: Umbau von Script     \_OP5BK.Kontobew. Importieren aus (SP=Dateiname¶¶¶¶Content)/ 190820 mpr

1.  in erstem Schritt müssen die CR im Textfeld innerhalb der ANführungszeichen eliminiert werden
2. dann müssen die Semikoons innerhalb des TExtes in temp. andere Speratoren umgewandelt werden, damit die restliche Grundstruktur von $Line erhalten bleibt:

![Bildschirmfoto 2020-08-19 um 16 07 53](https://user-images.githubusercontent.com/3273572/90645397-2d0a9100-e236-11ea-8512-1629f46bfa10.png)

![Bildschirmfoto 2020-08-19 um 16 09 44](https://user-images.githubusercontent.com/3273572/90645593-6ba04b80-e236-11ea-9775-adbc8aee1698.png)

Im Weiteren wurde das Abgreifen der einzelnen Werte an die neue Struktur angepasst:

![Bildschirmfoto 2020-08-19 um 16 11 02](https://user-images.githubusercontent.com/3273572/90645733-98ecf980-e236-11ea-9749-9f76d39e5ee1.png)

Der Rest läuft wie bisher...

HINWEIS: Das manuelle Importieren von Kontodaten (Btn-ID 93) wurde deaktiviert!

**Comment by mprueter** [comment]
Die neuen Dateien müssen entsprechend den Vorgaben für die bisherigen Dateien umbenannt werden:

Umsaetze_...KTO3907546...

Beispiel:

Umsaetze_01012018_bis_10072018_KTO3907546_10072018


...und anschließend wie bisher auf dem Server ablegen.

**Comment by mprueter** [comment]
Ich benötige noch eine weitere Testdatei. Sollte der Import damit erfolgreich sein, können wir den Import wieder freischalten.

**Comment by Toelk-A** [comment]
hab eich jetzt an NIF weitergeleitet

**Comment by mprueter** [comment]
Die zweite Testdatei konnte erfolgrreich importiert werden. Allerdings ist dabei eine kleine Unstimmmigkeit aufgetaucht:

![Bildschirmfoto 2020-08-24 um 11 08 34](https://user-images.githubusercontent.com/3273572/91026840-9a823d00-e5fb-11ea-837e-7eb215494404.png)

Daueraufträge werden gänzlich ohne Inhalt, lediglich mit Betrag übermittelt. Laut NIF ist das erstmal okay so. 

Das sollten wir im Auge behalten, da es durchaus sein kann, dass so etwas noch bei anderen Auftragsarten vorkommt.

Ansonsten kann der Import jetzt wieder wie bisher aufgenommen werden.

**Comment by mprueter** [comment]
Nach dem Einlesen der ersten echten Dateien gibt es augenscheinlich Probleme mit Daten vor dem 01.06.2020:

![Bildschirmfoto 2020-08-24 um 12 32 57](https://user-images.githubusercontent.com/3273572/91037082-b8a26a00-e608-11ea-9080-8601296fd8d4.png)


...alle Daten vor dem 1.6.20 sind in einer anderen Datenstruktur übermittelt worden und demenstprechend auch nicht korrekt in Ornella importiert worden.

Der letzte korrekte Import vor der APO-Bank-Umstellung wurde aber für beide Mandanten am 29.5.20 vorgenommen, sodaß also alle Daten bis dahin schon in der DB waren!

Ich habe deshalb die falsch importierten Daten für beide Mandanten manuell gelöscht.

**Comment by mprueter** [comment]
Dei ApoBank hat erneut das Exportformat geändert. Das Texfeld mit den weiteren Infos ist jetzt nicht mehr in der 4,. Spalte, sondern in der 3. Spalte:

![Bildschirmfoto 2020-11-05 um 10 31 18](https://user-images.githubusercontent.com/3273572/98223426-59d76600-1f52-11eb-8b44-379d2af7579c.png)


Entsprechend habe ich das Script geändert:

![Bildschirmfoto 2020-11-05 um 10 31 45](https://user-images.githubusercontent.com/3273572/98223398-517f2b00-1f52-11eb-801e-2da49c19cf89.png)
