### ISSUE TITLE
GTMV/ Fertigstellung neues Portal Dokumente hochladen Teil I

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#757]
Ich habe jetzt endlich mit Dr Nitschke gesprochen,

es müssen noch einige Kleinigkeiten eingebaut werden. Wenn möglich bis Montagvormittag ;-)

Aus irgendeinem Grund erscheint hier mein USER Passwort, bitte prüfen

![image](https://user-images.githubusercontent.com/22314271/91562442-80b76180-e93d-11ea-95f4-d018514200f9.png)

**Comment by mprueter** [comment]
Das ist nur Ihr User-Kürzel, nicht Ihr Passwort. Es soll eigentlich nur anzeigen, dass Sie dort Eintargungen vornhemen können.

**Comment by mprueter** [comment]
Ich habe den Text angepasst, dann ist es eindeutiger:

![Bildschirmfoto 2020-08-31 um 13 01 34](https://user-images.githubusercontent.com/3273572/91713477-26f7a700-eb8a-11ea-8997-45b71b5216d4.png)
