### ISSUE TITLE
Prozessschritt Transportbegleitschein

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#76]
Bitte hier noch Datum und Zeitangaben aus Entnahmebericht übernehmen

**Comment by Toelk-A** [comment]
Bitte noch bearbeiten z.B. ID 1375

![image](https://cloud.githubusercontent.com/assets/22314271/22146025/a77fad4c-df03-11e6-8cf8-7eb3599c7737.png)

**Comment by chrbusch** [comment]
Bitte genau angeben, welche Felder von EntnBericht wohin auf TransportBeglSchien sollen.
Für die Berechnung von Beginn und Ende der Ischämiezeit hatte ich schon mehrfach um eine exakte Beschreibung aller Fälle gebeten, die fehlt mir nach wie vor.

**Comment by Toelk-A** [comment]
siehe #97

**Comment by Toelk-A** [comment]
ID 1394

1)Abschnitt: "Name Unterschrift des Koordinators" Dropdownliste fehlt
2) "Art der Spende" soll automatisch aus Spendermeldung übernommen werden
3) "Kühlung des Leichnams" soll automatisch aus Spendermeldung übernommen werden
4) "Beginn der Ischämiezeit" soll automatisch aus Spendermeldung übernommen werden

![image](https://cloud.githubusercontent.com/assets/22314271/22281335/c45ac560-e2d6-11e6-9f37-266fbd7f3816.png)
