### ISSUE TITLE
GTMV/ MA ID 137 taucht nicht im Team Koordinatoren Rostock auf

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#763]
Bitte prüfen,

Frau freese taucht nicht im Team Koordinatoren Rostock (in den Tagesabschlüssen + Teamkalender auf)

![image](https://user-images.githubusercontent.com/22314271/91816770-67f8c580-ec35-11ea-979a-fe87c40a6f8b.png)

**Comment by mprueter** [comment]
Jetzt sollte Frau Freese wieder beim Tagesabschluss auftauchen. Das Problem war, das die ID des Teams nicht automatisch beim Aktulaisieren der MitarbieterTage gesetzt wurde. Das habe ich jetzt korrigiert bzw. optimiert.
