### ISSUE TITLE
GBMV/ Transplantatliste bitte einmal Statuswechsel durchführen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#765]
Hallo Herr Prüter, zwischenzeitlich wurde das System in Ornella umgestellt (NIF/cBU). Zur Userfreundlichkeit bitte ich Sie umFolgendes:

Können Sie bitte alle Hornhäute, die den medizinischen Status **"34 fest allokiert" und den betriebswirtschaftlichen Status "bezahlt"** haben in den medizinischen Status "Verschickt" umwandeln?

![image](https://user-images.githubusercontent.com/22314271/92438859-f1664580-f1a9-11ea-85c4-a6700b181f7f.png)

Danke

**Comment by mprueter** [comment]
Ist erledigt es handlete sich um 132 DSe. Im Statuslog findet Sie folgenden Hinweis:

![Bildschirmfoto 2020-09-08 um 14 24 23](https://user-images.githubusercontent.com/3273572/92476343-175a0d00-f1df-11ea-84c4-d44da91d8974.png)

**Comment by Toelk-A** [comment]
erledigt, danke!
