### ISSUE TITLE
GTMV/ Mobiles Entnahmeteam - Kürzel ohne Klarnamen abgebildet

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#766]
Im Prozessschritt mobiles Team wird bei manchen Mitarbeiter nur das Kürzel, nicht der Klarname abgebildet:

![image](https://user-images.githubusercontent.com/22314271/93074447-aa35f400-f684-11ea-8cfe-ee281c0702df.png)

Sicherlich habe ich hier einen "Haken" beim Anlegen der neuen Mitarbeiter übersehen. Leider weiß ich aber nicht wo ich genua nachsuchen muss. Vielleicht haben sie eine Idee.

**Comment by mprueter** [comment]
Das Problem ist, dass die Werteliste noch nach einem alten Verfahren aufgebaut wird. Es werden nicht die Hiddenbuttons benutz, sondern ein kalkuliertes "Indexfeld":

**Case (  _Pos( d_Funktion; "Koordinator" ) > 0 or _Pos( d_Funktion; "Arzt" ) > 0 or d_Koordinator_1; __pk_User_T )**

Es werden also noch die alten Felder "Funktion" und "TX-Koordinator" benutzt:

![Bildschirmfoto 2020-09-14 um 13 49 52](https://user-images.githubusercontent.com/3273572/93082781-cdb36b80-f691-11ea-83bb-4d889f82d387.png)

Ich kann das gern auf den Auswahldialog via Hiddenbutton umstellen. Dafür müsste ich aber genau wissen, welche HiddenButtons relevant sind.

**Comment by mprueter** [comment]
Das ganze ist jetzt auf die neue Variante mit Hiddnbuttons umgebaut:

![Bildschirmfoto 2020-09-14 um 14 15 20](https://user-images.githubusercontent.com/3273572/93084841-f5580300-f694-11ea-961e-57fa4a3e50fb.png)


Entfernen können Sie den Entnehmer via Papierkorb:

![Bildschirmfoto 2020-09-14 um 14 15 32](https://user-images.githubusercontent.com/3273572/93084900-102a7780-f695-11ea-9f3a-d5311055fedb.png)



**Mir ist aufgefallen, dass dieses Dokument noch auf Basis des SpdGewebes beruht. Eigentlich hatten wir doch alles auf SpdEntnahme umgestellt, oder? Das müssten wir hier doch eigentlich auch tun...**

**Comment by Toelk-A** [comment]
wenn mal nichts zu tun ist können wir dies gern machen ;-)

**Comment by Toelk-A** [comment]
erledigt
