### ISSUE TITLE
GTMV/ Anpassung Prozessschritt Untersuchungsantrag

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#768]
Hallo Herr Prüter, im Labor Plauen gab es eine behördliche Prüfung.
Zukünftig müssen der Herz Kreislauftod (Todeszeitpunkt - "HKTS") und (wenn vorhanden) der Entnahmezeitpunkt postm. Blutprobe auf den Untersuchungsantrag mit übernommen werden.

Todeszeitpunkt finden Sie in den Spenderdetails:

![image](https://user-images.githubusercontent.com/22314271/93220272-8ea61880-f76c-11ea-884c-7a37bd0c3aa6.png)

Zeitpunkt Postmortale Blutentnahme finden Sie in der Hämodilution
![image](https://user-images.githubusercontent.com/22314271/93220390-bac19980-f76c-11ea-8866-58bba58a1b07.png)

Bitte den Prozesschritt "Untersuchungsantrag" wie folgt anpassen:

[Anpassung Untersuchungsantrag.pdf](https://github.com/chrbusch/GTM-V/files/5225437/Anpassung.Untersuchungsantrag.pdf)

Sind keine postm. Blutproben vorhanden, kann beides ausgeblendet werden.

**Comment by mprueter** [comment]
Aber genau genommen sollte es doch auch nur eingeblendet werden, wenn Röhrchen für postmortale Proben angegeben sind, oder?

![Bildschirmfoto 2020-09-23 um 10 34 40](https://user-images.githubusercontent.com/3273572/93988223-c0306c80-fd88-11ea-9255-dc0a87dbe128.png)

Es besteht ja de Möglichkeit, dass ein Untersuchungsauftrag gar keine postmortalen Proben enthält, obwohl diese vorhanden sind...

**Comment by mprueter** [comment]
Muss diese Info auch in den digitalen Untersuchungsaufträgen übermittelt werden?

**Comment by mprueter** [comment]
Ich habe es jetzt so programmiert, dass die gewünschten Daten eingeblendet werden, wenn auch postmortale Röhrchen angegeben werden:

![Bildschirmfoto 2020-09-23 um 11 24 04](https://user-images.githubusercontent.com/3273572/93993955-a5adc180-fd8f-11ea-9297-28337394a675.png)

Snd keine postmortalen Röhrchen angegeben, erscheint nichts:

![Bildschirmfoto 2020-09-23 um 11 25 03](https://user-images.githubusercontent.com/3273572/93994053-be1ddc00-fd8f-11ea-8d1e-6f0bd9e769b1.png)

Sofern mehrere Entnahmezeitpunkte für postmortale Proben eingetragen worden sind, wird immer der **älteste** angezeigt. Ich hoffe, das ist okay so.

**Comment by mprueter** [comment]
> Muss diese Info auch in den digitalen Untersuchungsaufträgen übermittelt werden?

Ich habe mit Hr. Wohlfarth telefoniert. Er meinte an ihn wären aus dem eigenen Hause keine deartigen Anforderungen heran getragen worden. Also vorerst keine Übertragung der o.g. Daten im digitalen Untersuchungsauftrag.

**Comment by Toelk-A** [comment]
keine Übertragung notwendig:-) dies fordert nur die Behörde.... inschriftlicher Form... danke für die umsetzung. getestet funktioniert!

wir beobachten heute die Datenübertragung aus Plauen. heuet morgen 06:19hat plauen sich die aufträge vom server gezogen.
