### ISSUE TITLE
!Wichtig! Entnahmebericht OG

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#77]
Druck funktioniert nicht
Bsp.: Spender 161216-0710-GNO-SCD

Nach Eingabe von Spalte und Zeile sind die zu druckenden Etiketten leer

![image](https://cloud.githubusercontent.com/assets/22314271/21610225/10894c52-d1c7-11e6-8ca4-ab9ef0819bcb.png)

**Comment by chrbusch** [comment]
Erledigt

**Comment by Toelk-A** [comment]
vorhin standen noch "rechts" und "links" auf den Etiketten jetzt fehlt es wieder

![image](https://cloud.githubusercontent.com/assets/22314271/21644447/c622b5d2-d28d-11e6-8aa4-efef81156856.png)

**Comment by chrbusch** [comment]
Auf Bitte von Dr Nitschke habe ich heute "R" und "L" umgewandelt in "R" und "S"M dadurch kann beim Drucken etwas durcheinander geraten, weil das System die alten Werte nicht mehr versteht.
Ich habe das Etikettenscript dementspr. angepasst.

**Comment by Toelk-A** [comment]
"D" und "S" wird nicht mehr angezeigt, ich nehme an es hängt mit der Änderung der OG Etiketten zusammen

1) Bitte im OG Entnahmeprotokoll die entnommenen OG Präparate mit nicht mehr mit "B" sondern mit "D" und "S" anzeigen (funktioniert nicht)

2) OG "Transportetiketten" bitte mit "rechts" und den 2. mit "links" bezeichnen  (funktioniert im Moment)

**Comment by chrbusch** [comment]
Bitte aktuellen Stand mitteilen: Klappt das jetzt?

**Comment by Toelk-A** [comment]
Transportetiketten funktionieren

Entnahmeprotokoll:

Bitte das am Anfang stehende "O," wegstreichen, bitte nur Spenderkennummer +D oder S (ohne Komma abbilden)
z.B.:  160117-1303-GNO-KRJ-OD
bzw  160117-1303-GNO-KRJ-OS

![image](https://cloud.githubusercontent.com/assets/22314271/22017137/494b9f9e-dca9-11e6-9b9a-7c3f26c13346.png)

**Comment by Toelk-A** [comment]
ID 1375

Wie im letzten Kommentar beschrieben bitte "O:" im OG Entnahmebericht entfernen

![image](https://cloud.githubusercontent.com/assets/22314271/22145764/f9191536-df02-11e6-9b06-3c8e6db4a8b8.png)

**Comment by chrbusch** [comment]
erl.
