### ISSUE TITLE
GTMV/ Checkliste OG - Augenafrbe des Spenders

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#770]
Hallo Herr Prüter,

jetzt da das Augenportal fertig programmiert ist, wäre es möglich die Werteliste der Augenfarbe aus dem Augenportal direkt in die Checkliste zu hinterlegen und zu übernehmen ins Augenportal?

![image](https://user-images.githubusercontent.com/22314271/93599951-37e44d00-f9bf-11ea-8243-4840685eae30.png)

![image](https://user-images.githubusercontent.com/22314271/93599976-4894c300-f9bf-11ea-810c-42c3f00b8148.png)

**Comment by mprueter** [comment]
Bei der Eingabe der Augenfarbe in der Chackliste erschient jetzt ein Auswahldialog mit der UKK-Werteliste:

![Bildschirmfoto 2020-09-21 um 09 00 10](https://user-images.githubusercontent.com/3273572/93741887-7bbc9980-fbed-11ea-930a-840cbadd2f43.png)

Bei der Eingabe der UKK-Daten auf dem REiter Augenanamense gibt es jetzt einen "Rädchen"-Button, der Ihnen jeweils pro Auge den ggf. vorhandenen Wert aus der Chackliste holt. Dieser kann aber auch wie bisher manuell gesetzte werden.

![Bildschirmfoto 2020-09-21 um 09 30 08](https://user-images.githubusercontent.com/3273572/93742115-d8b84f80-fbed-11ea-90af-7a5e85b15c24.png)

**Comment by Toelk-A** [comment]
in der Checkliste funktioniert es super! UKK testen wir wenn es zutrifft :-)
