### ISSUE TITLE
GTMV/  (ID 12981) MSG Entnahmeberichte nicht korrekt verknüpft

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#772]
Hallo Aniter,
beim Spender (ID 12981) sind zwei MSG-Entnahmeprotokolle angelegt. Beim Öffner des ersten gelangt man in eine OG-Protokoll aus 2018, beim Öffnen des Zweiten in ein leeres Protokoll.
Bitte Herrn Prüter prüfen lassen.
Danke und Gruß
FPN

**Comment by mprueter** [comment]
Das Problem ist behoben. Mit aller größter Wahrscheinlichkeit ist er auf Programmierarbeiten meinerseits zurück zu führen und sollte sich nicht wiederholen.

**Comment by Toelk-A** [comment]
Danke :-)
