### ISSUE TITLE
GTMV/ Übertragung virologie med Labor Rostock scheint zu haken

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#773]
Hallo Herr Prüter uns ist aufgefallen, dass bei folgendem Spender die Parameter aus Rostock Labor nicht übertragen wurden. Können Sie einmal nachsehen woran es liegt?

![image](https://user-images.githubusercontent.com/22314271/94418221-62819300-0181-11eb-821c-0121d326ba1c.png)

**Comment by mprueter** [comment]
siehe #774
