### ISSUE TITLE
GTMV/ HCV_NAT Übertragung als med. Labor gestört

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#774]
#403 

Ich versuche heirzu Herrn Trommer zu kontaktieren. Es scheint, dass zur HCV.PCR kein Messwert im Labor Südstadt erzeugt wird...

**Comment by Toelk-A** [comment]
Wie vermutet wurde die HCV-PCR zwischenzeitlich in einem anderen Labor gemessen. Dies sei aber schon lange nicht mehr so. Herr Trommer fand mit mir gemeinsam den Fehler "F" und leitet dies an die zuständen Mitarbeiter weiter. Da die Telefonverbindung sehr schlecht war schicke ich noch einmal eine Mail an Herrn Trommer.

![image](https://user-images.githubusercontent.com/22314271/94435126-0592d680-019b-11eb-985d-d2a3b37110df.png)

**Comment by Toelk-A** [comment]
Herr Trommer rief noch einmal zurück
 -> F = vorläufiger Befund - es lag noch kein Ergebnis vor, da HCV-NAT noch nicht gemessen wurde
-> das Kürzel für HCV NAT wurde von HCVM aus HCVT geändert

Habe dies jetzt in Ornella in den den Parametern getan

![image](https://user-images.githubusercontent.com/22314271/94437299-d762c600-019d-11eb-9f22-f8733e4929f9.png)

**Comment by mprueter** [comment]
Dann sollte es jetzt funktionieren. Heute (29/10/20) ist noch keine LDT-Datei mit entsprechenden Daten angekommen. Ich werde das in den nächsten Tagen im Auge behalten...
