### ISSUE TITLE
Grundsätzliche Verknüpfung von SpdProzSchritten mit jeweils EINEM Dokument

### ISSUE THREAD

**Issue by mprueter** [chrbusch/GTM-V#776]
Vorbereitende Ausführungen in #728 

Grundsätzlich sollte bei dokumentenbasierten SpdProzSchr jeder SpdProzSchr einem Dokument zugeordnet sein. In den meisten Fällen enstpricht also ein SpdProzSchr einem Datensatz in einer anderen Tabelle. Somit würde es sich anbieten, ein Feld TableID beim SpdProzSchr anzulegen und jeweils beim Anlegen eines Dokumentes zu pflegen. Ggfs. sollte eine enstprechende Flag beim BasisProzSchr eingefügt werden.

Der Zugriff vom SpdProzSchr zum Dokment kann dann mit Hilfe eines Bausteinscriptes oder einer CF zielgenau erfolgen.

**Comment by mprueter** [comment]
![Bildschirmfoto 2020-09-29 um 13 00 20](https://user-images.githubusercontent.com/3273572/94550271-c1174180-0253-11eb-81b9-83f04fcbf832.png)


in diesem Script ab Zeile 167 müsste m.E. die Verknüpfung eines SpdProzSChr mit dem soeben angelegten Datensatz in der anderen Tabelle erfolgen.

**Comment by mprueter** [comment]
![Bildschirmfoto 2020-09-29 um 13 03 09](https://user-images.githubusercontent.com/3273572/94550515-23704200-0254-11eb-9aee-2e39a0ba0a87.png)

Der Dialog ab Zeile 130 könnte dann entfallen, da es nur ein Dokument geben kann. Entweder man kann es noch bearbeiten (dann gelangt man auf die Einagbemaske) oder es ist bereits freigegeben (dann erscheint wie bisher das PDF:

**Comment by mprueter** [comment]
Ergebnis Besprechung CBU/MPr:

Erstmal den Ansatz mit einem TableID-Feld in den SPdProzSchr verfolgen. Wenn dieses Feld leer ist, alter Modus, sonst neues Script für Aufruf der zugehörigen DSe.

**Comment by Toelk-A** [comment]
Hallo Herr Prüter ist dieses Ticket erledigt?

**Comment by mprueter** [comment]
kurze Zusammenfassung des Gesprächs mit Frau Tölk heute am 27/11/2020

Workflow:
1. Eingabe aller relevanten Daten durch Koordinator -> Abschluss mit Btn. "Koordinator fertig" (Script: Spd10.):

![Bildschirmfoto 2020-11-27 um 10 09 03](https://user-images.githubusercontent.com/3273572/100431572-a537ec80-3098-11eb-9dd4-04e8098edcbb.png)

-hier noch keine weiteren SPS anlegen! Bisher noch:

![Bildschirmfoto 2020-11-27 um 08 24 38](https://user-images.githubusercontent.com/3273572/100431701-d0bad700-3098-11eb-9401-97c9c67f73cf.png)

2. Abschluss Arzt -> Neues Gewebe (z.B. OG) (Script: SpdGewebe01.)
-jetzt werden die SPS für Entn. und TranspBegleitschein und UA angelegt
-> (Transportbegleitschein und) UA sollte erst nach erfolgreichem Einwiligungsgespräch angezeigt werden!

3. Einwilligungsgespräch:
![Bildschirmfoto 2020-11-27 um 10 19 42](https://user-images.githubusercontent.com/3273572/100432578-14621080-309a-11eb-8763-7577bcf358d0.png)

4.-> wenn hier ein Erfolg verbucht wird (Script EinwillGespr10.) => SPS Medizinische Indikationsprüfung

5.  SPS Medizinische Indikationsprüfung =erfolgreich
 => UA, FreigabeGewebeEnt, Körperl. Untersuchung

6. FreigabeGewebeEnt -> erfolgt => ggf. Meldung mob. EntnTeam, wenn Entnahmeort <> GTMV-Betrebsstätte (Flag bei Masteradresse)

ACHTUNG: mob. EntnTeam hängt im Moment noch am SpdGewebe -> muss aber auf SpdEntn. umgebuat werden( die Werte können von dort übernommen werden und sollen auch nur in der SpdEntn änderbar sein!)

ABBRUCHSZENARIEN:
1. keine Freigabe bei EinwillGespr.
2. Status Gewebe = 20, 71, 15, 14

-> dann alle gewebespez. SPS (inkl. Entn etc.) löschen

Außerdem: 
Labor in UA-SPS anzeigen
+ bei SPS erst, wenn wirklich DS angelegt wurde

**Comment by mprueter** [comment]
> Labor in UA-SPS anzeigen

...bei den neuen Adminschritten (derzeit nur bei TestSpendern) ist das jetzt so:

![Bildschirmfoto 2020-11-27 um 11 02 34](https://user-images.githubusercontent.com/3273572/100436842-352d6480-30a0-11eb-8785-5526274c8abe.png)

Generell gilt: keine Adresse angezeigt = keine Adresse ausgewählt

**Comment by mprueter** [comment]
Der obige Filter war nicht korrekt. Es gibt en zentrales Markerfeld beim Spender, das auch die Anziege der Portale bei Spender steuert:

![Bildschirmfoto 2021-01-13 um 09 38 03](https://user-images.githubusercontent.com/3273572/104427070-1701c200-5583-11eb-83da-15f25338de58.png)

...alle neuen Spender ab der ID 14333 laufen jetzt über das neue Verfahren. Das Weichenscript  Workflo10a. wurde enstprechend angepasst:

![Bildschirmfoto 2021-01-13 um 09 42 04](https://user-images.githubusercontent.com/3273572/104427542-a60eda00-5583-11eb-8c88-f7d449eecee4.png)

**Comment by Toelk-A** [comment]
Hallo Herr Prüter,

mir ist noch etwas aufgefallen. Die "Mülltonne" darf nur für die VP20bs und Supervisor sichtbar sein.
VG Anita Tölk
![image](https://user-images.githubusercontent.com/22314271/105692781-27108e80-5eff-11eb-8ccf-118e008dae10.png)

**Comment by mprueter** [comment]
Frau Dr. Cordshagen hatte versehentlich das spezielle Recht Supervisor und konnte deswegen den Papierkorb sehen.
