### ISSUE TITLE
GTMV/ Spenderkennummer setzen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#778]
Hallo Herr Prüter,

wie am Telefon kurz angedeutet muss die Programmierung zum Setzen der Spenderkennnummer ein wenig angepasst werden:

![image](https://user-images.githubusercontent.com/22314271/94693671-4b36d700-0334-11eb-8c90-6b7023a586af.png)

Unsere Spenderkennnummer setzt sich zusammen aus:
Meldedatum (rot) + Meldezeit(rot) + Region der Meldung (GNO / GOS_blau) + Koordinator (grün)

Spenderkennnummern dürfen nicht doppelt vergeben werden, sodass bereits eine Programmierung existiert, die nach Zeitpunkt+ Region + Koordinator schaut. Falls alle 4 Parameter schon vorhanden sind, wir bei der Uhrzeit einfach "+1" gerechnet und somit entsteht eine Neue, noch nicht vorhandene Spenderkennnummer.
Soweit so gut. 

Bitte zukünftig die Region aus der Prüfung auslassen...damit NICHT folgende Spenderkennnummern entstehen können:

150520-1550-GNO-TOA
150520-1550-*GOS*-TOA

Nur der Regionsunterscheid kann den Spender in der Gewebebank nicht eindeutig identifizieren, da die Region nicht mit übernommen wird.

es müsste also richtig heißen:

150520-1550-GNO-TOA
150520-1551-*GOS*-TOA

**Comment by mprueter** [comment]
Das ist jetzt so angepasst. Die Region wird bei der Dublettensuche nicht mehr berücksichtigt.

Folgende Änderungen im Script Spd12.

![Bildschirmfoto 2020-10-01 um 10 27 15](https://user-images.githubusercontent.com/3273572/94786014-b9c97280-03d0-11eb-978d-a4ecba81befa.png)

**Comment by mprueter** [comment]
Eine Anmerkung noch:

In den seltenen Fällen, in denen der Zeitpunkt auf 59 Minuten endet (also z.B. 11:59) _**UND**_ es schon einen zeitgleichen Datensatz für denselben Koordinator gibt, wird eine Ziet mit "60" für die Minuten erzeugt (bezogen auf das obige Beispiel also "1160"). Ist das ein Problem?

**Comment by mprueter** [comment]
Bezogen auf die obige Anmerkungen habe ich das Script überarbeitet und dabei auch noch das Problem des Datumsübergangs behoben ( Uhrzeit 23:59).

Folgende Anpassung in Script Spd12.

![Bildschirmfoto 2020-10-01 um 12 44 36](https://user-images.githubusercontent.com/3273572/94799740-e3d86000-03e3-11eb-8768-6145f7e02109.png)

**Comment by Toelk-A** [comment]
hatten wir telefonisch geklärt 11:60 existiert in diesem Sinne nicht als Uhrzeit :-)
