### ISSUE TITLE
GTMV/ AGE Auflistung bildet eine OG Spende doppelt ab bitte prüfen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#779]
Hallo Herr Prüter,
makrierte OG Spende wir doppelt aufgelistet. Höngt dies ggf mit einem gelöschten OG Entnahmebericht zusammen, der zwar nciht mehr sichtbar ist, aber in die AGE mit eingezählt wird? Oder sind dies ggf. Skleren?

Bitte um Prüfung
[AGE Doppelabbildung OG.pdf](https://github.com/chrbusch/GTM-V/files/5325592/AGE.Doppelabbildung.OG.pdf)

**Comment by mprueter** [comment]
Es handelt sich dabei, tatsächlich um die Skleren. Das Suchscript für die AGE-Abrechnungen berücksichtigt das noch nicht. Wie soll ich damit umgehen? Wir haben zwei Entnahmen und das ist im Hinblick auf die gewebprozessierenden Einrichtungen ja auch korrekt so. 

Soll ich nun bezigen auf die AGE-Abrechnung nur eine Position erstellen? Und was ist, wenn nur die Skleren entnommen werden? Gibt es die Entschädigung dann auch? 

Also letztlich ist die Frage, ob die Entschädigung pro angelegter Entnahme oder pro entnommener Gewebeart gezahlt werden soll. Kann ich alles programmieren, ich muss nur wissen, was heraus kommen soll... ;-)

**Comment by Toelk-A** [comment]
Es handelt sich dabei, tatsächlich um die Skleren. Das Suchscript für die AGE-Abrechnungen berücksichtigt das noch nicht. Wie soll ich damit umgehen? Wir haben zwei Entnahmen und das ist im Hinblick auf die gewebprozessierenden Einrichtungen ja auch korrekt so.


AGE Auflistung bezieht sich auf Gewebe (OG) , nicht Präparate. Sklera und Kornea sind Präparate des Gewebes OG. Es hat nur 1 Entnahme des Gewebes OG stattgefunden - Raum wurde also nur 1x genutzt.. Die Präparate sind an verschiedene prozessierende Einrichtungen gegangen. Es darf in diesem Fall nur 1x OG abgebildet werden.

**Comment by mprueter** [comment]
Jetzt sollte es funtionieren.

techn. Anmerkung:
Änderung in Script RngAGE40.

![Bildschirmfoto 2020-10-12 um 17 39 29](https://user-images.githubusercontent.com/3273572/95765369-0efb6300-0cb2-11eb-9968-3c44205e7b5b.png)

**Comment by mprueter** [comment]
Bei der vorhandenen Abrechnung bitte einfach die doppelte Position aus der Rechnung löschen.
