### ISSUE TITLE
GTMV/ Checkliste Infos in ornella übernehmen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#781]
Hallo Herr Prüter,  unsere Hilfskräfte sind jetzt mit den IPADS unterwegs udn dokumentieren in der digitalen Checkliste.

![image](https://user-images.githubusercontent.com/22314271/95342697-01ac3600-08b8-11eb-8307-417c4499342f.png)

Wird in der Checkliste ein Hausarzt hinterlegt (dies erfolgt bereits via Adressuche) so soll dieser auch gleich in die medizinische Indikationsprüfung übernommen werden:

![image](https://user-images.githubusercontent.com/22314271/95342814-1e486e00-08b8-11eb-9cfd-5a8e47ba7944.png)

![image](https://user-images.githubusercontent.com/22314271/95342882-302a1100-08b8-11eb-9672-150ee60f7cae.png)

**Comment by mprueter** [comment]
Welches Feld soll wirklich gefüllt werden? Es gibt auch noch ein explizites Hausarztfeld:

![95342882-302a1100-08b8-11eb-9672-150ee60f7cae](https://user-images.githubusercontent.com/3273572/95435393-cf9be200-0952-11eb-8923-dc814dfae94b.png)

...dieses Feld ist ma gefüllt, mal nicht. Ist es noch in irgendeienr Form in Benutzung? Welches Feld soll mit den Daten aus der Checkliste gefüllt werden?
