### ISSUE TITLE
GTMV/ Checkliste Infos in ornella übernehmen _ Abschnitt Besonderheiten

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#782]
Textfeld Besonderheiten bitte direkt in den Entnahmebericht übernehmen:

![image](https://user-images.githubusercontent.com/22314271/95343103-6f586200-08b8-11eb-8e57-914bb1b81b73.png)

OG Entnahmebericht bitte hier abbilden:

![image](https://user-images.githubusercontent.com/22314271/95343225-92831180-08b8-11eb-8fdb-f0c7058939dc.png)

**Comment by mprueter** [comment]
Ich habe hier einen Button analog zum Entnahmezeitpunkt bzw. zur Kühltemperatur gesetzt, der ggf. die eingetragenen Werte aus der CL holt:

![Bildschirmfoto 2020-10-08 um 11 05 46](https://user-images.githubusercontent.com/3273572/95438361-7930a280-0956-11eb-9738-a885298f6cb0.png)

Funktion ist wie in  #723 beschrieben.

Techn. Anmerkung:
Erweiterung von Script SpdEnt20. um Art="Besonderheiten"

**Comment by Toelk-A** [comment]
super, danke!
