### ISSUE TITLE
GTMV/ Medizinische Indikationsprüfung HAusarzt

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#783]
Hallo Herr Prüter,

mir ist aufgefallen, das in der medizinischen Indikationsprüfung der Hausarzt an 2 Stellen hinterlegt werden kann:

Was ist hier der Unterschied?

![image](https://user-images.githubusercontent.com/22314271/95549410-848fd680-0a07-11eb-9dbc-4c74d048547f.png)

**Comment by mprueter** [comment]
Hab ih mich auch schon gefragt (s. #781 ) und gehofft, Sie könnten mir das sagen... ;-)

**Comment by mprueter** [comment]
Nachtrag zur weiteren Berücksichtigung (technische Anmerkung):

Um Infos aus beiden Eingabemöglichkeiten via Excel beim Spender zu exportieren, wurde ein neues Feld ( q_Hausarzt_Export_NameTel) in der Tabelle Spender eingefügt, das Infos aus beiden EIngabemöglichkeiten zusammenfasst:



`      
Let(

           [

           vIN =  Substitute(  _SQLMatch3 ( GetFieldName( _MedIndikPrfg__::__pk_MedIndikPrfg ) ; GetFieldName ( _MedIndikPrfg__::_fk_Spd ) ; _Spender__::__pk_Spender ); "¶"; ",") ;

           vT = _Spender__::q_Hausarzt_Bezng & _Append ( Substitute( _Spender__::q_Hausarzt_TelOderMobil ;"¶";" - "); " - *" ) ;

           vSQL = "SELECT  {Name} , {Tel}
                   FROM {{DokAdr}}
                   WHERE {fk_MedInPrf} IN ( " & vIN &" )";
 
           vQry = Substitute( vSQL;

                      [ "{{DokAdr}}" ;  _SQLTable6 ( GetFieldName( _DokumAdr__::__pk_DokumAdr) )];
                      [ "{Name}" ;           _SQLField6 ( GetFieldName( _DokumAdr__::q_NN_Titel_Vname_Adr)  )];
                      [ "{Tel}" ;           _SQLField6 ( GetFieldName( _DokumAdr__::q_Mobil_o_Festnetz_Adr)  )];

                      [ "{fk_MedInPrf}" ;           _SQLField6 ( GetFieldName( _DokumAdr__::_fk_MedIndikPrfg )  )]
                      );

           vRes = Case( Abs( vIN ) > 0; ExecuteSQL ( vQry; " - "; ""))
           ];
     
           Case(  vREs <> "?"; List( vT;  vREs )

           )
)
`
