### ISSUE TITLE
GTMV/ Zeitfenster postmortale Blutentnahme

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#785]
Ist vom Spender kein Blut vor Versterbezeitpunkt vorhanden. so kann in einem bestimmten Zeitfenster nach Todeseintritt noch Blut abgenommen werden. Hierzu haben wir folgende Zeitfenster:

OG: bis 24h nach Todeseintritt
MSG bis 18,5h nach Todeseintritt.

Programmierungswunsch:

Wenn bis 13h nach Todeseintritt folgendes Feld nicht mit "ja" / bzw. postmortal nicht mit "vorhanden" angekreuzt wurde bitte ALARM in Spendermeldung (Spenderdetails) programmieren: "Sind prämortale Blutproben vorhanden?" Dies kann ähnlich Diabetes / Todesursache abgebildet werden.

![image](https://user-images.githubusercontent.com/22314271/95550020-84440b00-0a08-11eb-98b4-f708b60febb6.png)

**Comment by mprueter** [comment]
Das ist jetzt so eingebaut.

![Bildschirmfoto 2020-10-09 um 13 08 36](https://user-images.githubusercontent.com/3273572/95577238-0eed3000-0a32-11eb-9ace-46bd14c948aa.png)

**Comment by mprueter** [comment]
Sollten wir nicht gleich auch noch einen Abbruchhinweis einbauen, wenn die Frist überschritten ist, also bei...

OG: nach 24h nach Todeseintritt
MSG: nach 18,5h nach Todeseintritt

und noch nichts eingetragen wurde?

**Comment by Toelk-A** [comment]
### Sollten wir nicht gleich auch noch einen Abbruchhinweis einbauen, wenn die Frist überschritten ist, also bei...
OG: nach 24h nach Todeseintritt
MSG: nach 18,5h nach Todeseintritt

Nein bitte erst einmal nicht ;-) Wir testen heute einmal, ob es nun mit dem "Alarm " besser funktioniert :-)

### Gilt das eigentlich nur bei Organspendern?
Das gilt bei allen Spendern (HKTS + Organspender).

**Comment by Toelk-A** [comment]
Bei folgendem Spender funktioniert die anzeige "Blutproben vorhanden nicht"
![image](https://user-images.githubusercontent.com/22314271/97680951-c9071300-1a97-11eb-9a97-06673a7e7aae.png)


![Uploading image.png…]()

**Comment by mprueter** [comment]
Das Problem war hier, dass "prämortal vorhanden" leer war und nicht "NEIN" angekreuzt war; bisher hab ich bei der Plausib-Prüfung immer das Vorhandensein des "NEIN" geprüft. Ist jetzt umgestellt auf das Fehlen des "ja":

![Bildschirmfoto 2020-10-30 um 14 03 46](https://user-images.githubusercontent.com/3273572/97708372-ffa15580-1ab8-11eb-8ccf-7b39f6fd0410.png)
