### ISSUE TITLE
GBMV/ Mitarbeiter Osmers taucht nicht im Tagesabschluss auf

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#786]
Mitarbeiter Osmers ist dem Team Fibu zugeordnet und taucht nicht im Tagesabschluss auf:

![image](https://user-images.githubusercontent.com/22314271/95947870-ca75e180-0def-11eb-9fc4-bb4b5a256416.png)

![image](https://user-images.githubusercontent.com/22314271/95947909-d9f52a80-0def-11eb-8058-4edb126d81ac.png)

![image](https://user-images.githubusercontent.com/22314271/95947970-f7c28f80-0def-11eb-9e4c-f7921135f72f.png)

Bitte Programmierung prüfen

**Comment by mprueter** [comment]
Bei den MitarbeiterTagen von Herrn Osmers war die Teamzuordnung nicht vorhanden. Wahrscheinlich wurden die Mitarbeitertage angelegt/aktualisiert bevor das Team gesetzt wurde. Bitte immer erst alle wichtigen Zuordnung vornehmen und dann die MA-Tage anlegen.

Jetzt ist alles gut:

![Bildschirmfoto 2020-10-14 um 09 45 29](https://user-images.githubusercontent.com/3273572/95959079-4da03300-0e02-11eb-8fa3-a95238a77894.png)
