### ISSUE TITLE
GTMV/ Wiedervorlagen Resturlaub

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#788]
Hallo Herr Prüter, die Wiedervorlage Resturlaub erhält auch ausgeschiedene Mitarbeiter. Bitte einmal programmierung prüfen.

danke :-)

![image](https://user-images.githubusercontent.com/22314271/95981701-5b17e600-0e1f-11eb-91cb-163320806523.png)

**Comment by mprueter** [comment]
Ist schon optimiert. Es werden nur noch MA angezeigt, die zum Zeitpunkt der Erstellung der WV noch nicht das Unternehmen verlasen haben.

Tehcn. Anmerkung:
Ergänzung MA-Suche in Script OPH20.
![Bildschirmfoto 2020-10-14 um 14 16 27](https://user-images.githubusercontent.com/3273572/95987756-23fa0280-0e28-11eb-820a-63d71d2c0aed.png)
