### ISSUE TITLE
GBMV/ Button "Avis-Koordinator Entnehmer"

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#789]
Transplantatdetails
![image](https://user-images.githubusercontent.com/22314271/96084921-3cb5f700-0ec0-11eb-9b73-dfd096f5c748.png)

Bitte folgende amiladresse mit in den Verteiler nehmen:

antje.cordshagen@gtm-v.de oder läuft dies auch über Hidden Buttons Wiedervorlagen?

**Comment by mprueter** [comment]
Momentan geht die Email nur an den jeweiligen Koordinator des Spenders, den Entnehmer und (explizit) Sie:

![Bildschirmfoto 2020-10-15 um 14 56 50](https://user-images.githubusercontent.com/3273572/96129337-cb456b00-0ef6-11eb-875c-508f5efb0a47.png)

Ich kann jetzt entweder Frau Cordshagen auch als ständigen Empfänger in das Script mit einbauen oder wir lösen das zukunftssicher mit einem neuen HiddenButton...

Entscheiden Sie... ;-)
