### ISSUE TITLE
Reiter Spenderdaten-Überschrift Spenderdetails - Navigationsbutton bitte anpassen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#79]
Pfeile überdecken manchmal die Spenderdetails, dies bitte ändern

![image](https://cloud.githubusercontent.com/assets/22314271/21610481/94cec8ce-d1c8-11e6-87e0-d459b0dcddc6.png)

**Comment by chrbusch** [comment]
erledigt
