### ISSUE TITLE
GTMV/ Prozesschritt Hämodlituion - Automatisierung Datum

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#790]
Hallo Herr Prüter,

in der Hämodilution soll automatisiert das Datum des Prozessschrittes "Freigabe Gewebe" übernommen werden.

![image](https://user-images.githubusercontent.com/22314271/97182415-cb6a2400-179c-11eb-9857-ccb742de719e.png)

Bitte das Datum aus dem Prozessschritt Freigabe Gewebeentnahme übernehmen:
![image](https://user-images.githubusercontent.com/22314271/97182556-fc4a5900-179c-11eb-96a0-0169db6dac49.png)

**Comment by mprueter** [comment]
Ich habe jetzt Folgendes eingebaut:

Sofern beim Setzen der Unterschrift bereits ein Unterzeichnungsdatum in der Freigabe Gewebeentnahme vorhanden ist, wird dieses auch kommentarlos bei der Hämodulation eingetragen. 

Sollte noch _**kein Unterzeichnungsdatum**_ in der Freigabe Gewebeentnahme vorhanden sein, wird das heutige Datum gesetzt und es erscheint ein Hinweis-Dialog:

![Bildschirmfoto 2020-10-27 um 09 52 40](https://user-images.githubusercontent.com/3273572/97279067-c956a280-183a-11eb-9478-80d6c3f61265.png)


techn. Anmerkung:
Änderungen in Script User04US. -> Sonderfall eingebaut:

![Bildschirmfoto 2020-10-27 um 09 23 05](https://user-images.githubusercontent.com/3273572/97279252-0de23e00-183b-11eb-805f-263d63f2be72.png)

**Comment by mprueter** [comment]
Funktioniert das denn nicht?

**Comment by Toelk-A** [comment]
erleidgt
