### ISSUE TITLE
GTMV/ Programmierung UKK F/E Projekt - Augenarzt vorhanden ja/nein

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#793]
### 1) Bitte Ankreuzfeld "Augenarzt bekannt ja/nein" anlegen

![image](https://user-images.githubusercontent.com/22314271/97673385-ffd72c00-1a8b-11eb-80bc-d7e1fb549293.png)

### 2) "nein"

Wenn nein angekreuzt, dann muss dies auch in das augenprotal übernommen werden (Kein Augenarzt bekannt, demzufolge keine Augenanamnese abseits der GBM-V mgl)

**Comment by Toelk-A** [comment]
Dieses Ticket hat höchste Priorität :-)

**Comment by mprueter** [comment]
Das Feld ist jetzt eingebaut. Bis wir einen besseren Platz finden, ganz oben in der Detailmaske:

![Bildschirmfoto 2021-01-22 um 12 32 32](https://user-images.githubusercontent.com/3273572/105486201-685e2f80-5cae-11eb-8fef-6a9459e4a9e9.png)

Dieses Feld ist immmer zu sehen, auch wenn Sie auf dem Reiter UKK unterwegs sind. Deswegen habe ich das Feld dort erstmal nicht eingebaut.

Das Textfeld wir dnur angezeigt, wenn der Augenarzt auch tatsächlich bekannt ist:

![Bildschirmfoto 2021-01-22 um 12 32 39](https://user-images.githubusercontent.com/3273572/105486360-a52a2680-5cae-11eb-9ba0-02da5f170b91.png)
