### ISSUE TITLE
GBMV/ Personalplanung_ Neuer Sonderjob für Teamkalender erstellen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#798]
Teamkalender 

![image](https://user-images.githubusercontent.com/22314271/100196248-e85b5980-2ef8-11eb-81c8-aaace91dd36d.png)

1) Bitte den Sonderjob "Sonderurlaub" erstellen. 
![image](https://user-images.githubusercontent.com/22314271/100196352-0759eb80-2ef9-11eb-88c8-f3f78957d53f.png)

2) Wird dieser Sonderjob im Teamkalender gewählt, müssen an diesem Tag KEINE Sollstunden geleistet werden. 

3) Es wäre auch gut, wenn die Möglichkeit der Eingabe des Grundes Sonderurlaub besteht/ oder Werteliste zur Auswahl.

4) Es dürfen nur Mitarbeiter mit Sonderrechten wie z.B. TOA; NIF diesen Sonderjob auswählen können.

5) Sonderurlaub müsste dann auch in Ihrer Urlaubsübersicht - siehe Ticket 797 abgebildet werden.

**Comment by mprueter** [comment]
s. #799

**Comment by mprueter** [comment]
#797

**Comment by mprueter** [comment]
Das ist jetzt wie gewünscht umgesetzt. Es gibt die beiden neuen Jobs "Sonderurlaub" und "Sonderurlaub MA Wunsch":

![Bildschirmfoto 2020-12-16 um 15 56 31](https://user-images.githubusercontent.com/3273572/102365881-52c35f00-3fb8-11eb-8740-08ac2721a78b.png)

Bei den normalen Usern wird nur der Job "Sonderurlaub MA Wunsch" angezeigt (analog zu den bisherigen Jobs für den 1/2 Urlaubstag).

Wird der der Job "Sonderurlaub" von einem berechtigten User gewählt, muss zwingend ein Grund eingetragen werden:

![Bildschirmfoto 2020-12-16 um 15 57 16](https://user-images.githubusercontent.com/3273572/102366312-ccf3e380-3fb8-11eb-87b3-51f87a2c42e5.png)

Dieser erscheint dann auch im Teamkalender:

![Bildschirmfoto 2020-12-16 um 15 57 39](https://user-images.githubusercontent.com/3273572/102366447-f3198380-3fb8-11eb-8ce7-68ae406f5005.png)


Die Summen werden dann auch enstprechend beim Mitarbeiter angezeigt:

![Bildschirmfoto 2020-12-16 um 15 45 00](https://user-images.githubusercontent.com/3273572/102366507-07f61700-3fb9-11eb-98d9-7c9558dd01d7.png)


Insgesamt läuft alles so wie bisher beim normalen Urlaub auch.

techn. Anm. (Scripte)
MitarbTag12kUf.
\_OPH20_Urlaubstage aktualis. 
MitarbTag88.

**Comment by Toelk-A** [comment]
danke :-)
