### ISSUE TITLE
GBMV/ Personalmodul _ Sonderjob 0,5d Urlaub löschen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#799]
Bitte die folgenden Sonderjobs löschen oder ggf. umbenennen / ausblenden(gelb markiert):

![image](https://user-images.githubusercontent.com/22314271/100197799-26f21380-2efb-11eb-8fb2-876d1dad8014.png)

Bitte darauf achten, dass wen diese Sonderjobs gelöscht werden, dies bitte erst ab heute gilt. Alle Mitarbeiter die bereits diesen Sonderjob im System im Teamkalender hinterlegt hatten (Vormonate/Vorjahre?), dürfen dann keinen Stundenabzug bekommen.... nicht dass wir uns sämtliche Arbeitszeitkonten der Mitarbeiter "Zerschießen" Vielleicht ist es besser den Job in der Auswahlliste einfach auszublenden ;-)

**Comment by mprueter** [comment]
Diese Jobs stehen ab sofort nicht mehr zur Auswahl. Alle vorhandenen Einträge bleiben aber enthalten.

**Comment by Toelk-A** [comment]
erledigt
