### ISSUE TITLE
Diagnosen (ICD) und Prozeduren (OPS)

### ISSUE THREAD

**Issue by chrbusch** [chrbusch/GTM-V#8]
Diagnosen (ICD): Welche erzwingen Abbruch, kann man das kompakt formulieren in der Art "Alle, deren ICD beginnt mit... oder..."?

Mir fehlt noch ein leicht importierbarer Prozeduren-Stamm mit (OPS) (zB Exceldatei)

**Comment by Nitschke-FP** [comment]
Wie sind die Diagnosen bei ihnen erfaßt? Ist der ICD-Code und der Diagnosetext in einem Feld einer Tabelle abgelegt oder ist der Code ein separates Feld ? Sind die Diagnosen entsprechenden Diagnosegruppen zugeordnet?
OPS bitte ganz nach hinten stellen und jetzt als Textfeld formatieren.

**Comment by chrbusch** [comment]
Selbstverständlich sind alle Codes in separaten Feldern!
Der ganze ICD10 ist im System, aber nicht weiter gruppiert.

**Comment by chrbusch** [comment]
Wie besprochen bitte ich um Zusendung einer XLS-tabelle mit einem nach Gruppen klassifizierten ICD-Code. Dabei wäre optimal , wenn sich die Gruppeninfo einfach in einer Spalte befindet, in der Art
Gruppe | Code | Bezeichnung

**Comment by Toelk-A** [comment]
ICD Kodes kommen Mitte nächster Woche

**Comment by Toelk-A** [comment]
Hier die Exceltabelle

Absolute Kontraindikationen sind in Blatt 3 Zelle AG mit n= nein; ja= ja und r = risikobewertet  gekennzeichnet.

Die absoluten gewebespezifischen Kontraindikationen soll die Datenbank "erlernen". Hierzu gibt es mehr Infos von Dr Nitschke.


[ICD_Code_bearbeitet_absolute Kontraindikationen.xlsx](https://github.com/chrbusch/GTM-V/files/578300/ICD_Code_bearbeitet_absolute.Kontraindikationen.xlsx)

**Comment by Toelk-A** [comment]
Ist es möglich im Nachhinein, manuell, weitere Ausschlusskriterien in die ICD codes von uns einzufügen?

**Comment by chrbusch** [comment]
Unter Hauptmenü/Supervisor/Codes 
haben Sie nun die Option, durch freie Suche in den ICD selbst Risiken und Kontraindik. anzukreuzen

**Comment by Toelk-A** [comment]
Ist es möglich gewebespezifische Kontraindikationen (OG, MSG, KVG) anzukreuzen?

**Comment by chrbusch** [comment]
Bisher nicht. Ich bräuchte ganz genaue Informationen, was denn ggfs. passieren soll, wenn jemand zB 3 Gewebearten spendet und für einige davon Kontraindik. erfasst sind.
