### ISSUE TITLE
Prozesschritte      Spender:   020117-1245-GNO-SCD

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#80]
Warum werden "Entnahmeberichte für alle Gewebe" angelegt?

![image](https://cloud.githubusercontent.com/assets/22314271/21610628/69e7934c-d1c9-11e6-9e44-d88623fa868b.png)

**Comment by chrbusch** [comment]
Das ist EIN Formular, das für bel. Gewebe benutzt werden kann!

**Comment by Toelk-A** [comment]
Aber man kann keins von beiden öffnen, außerdem gibt es ja bereits die angelegten Entnahmeberichte OG und KVG. Uns erschließt sich nicht ganz der Hintergrund dieser beiden Formulare.

![image](https://cloud.githubusercontent.com/assets/22314271/21634156/452c5826-d255-11e6-9faf-2e1499957e1f.png)

**Comment by chrbusch** [comment]
Besteht dieses Problem noch?
Dann bitte SpenderID nennen

**Comment by Toelk-A** [comment]
Problem besteht noch Spender ID ist im Titel vorhanden: 020117-1245-GNO-SCD

**Comment by chrbusch** [comment]
diese Prozessschritte wurden vor längeren Zeit angelegt, bei neuen Spendern sollte das nicht mehr geschehen. Ansonsten bitte dieses Ticket wieder aufleben lassen
