### ISSUE TITLE
GTMB/ Prozessschrite fehlen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#804]
Bei Folgendem Spender fehlen Prozesschritte. Ich kann diese nachträglich anlegen, allerdings fehlen mir die notwendigen Prozesschritt Nummern. Die hatten wir mal beide irgendwann ausgeblendet (pk oder PB???)

![image](https://user-images.githubusercontent.com/22314271/101460455-e605f000-3939-11eb-8803-fdd3a3ddcc9b.png)

![image](https://user-images.githubusercontent.com/22314271/101460481-f322df00-3939-11eb-986c-d2876d5ddac6.png)

**Comment by mprueter** [comment]
Die sind jetzt wieder eingeblendet:

![Bildschirmfoto 2020-12-08 um 10 11 54](https://user-images.githubusercontent.com/3273572/101463597-ebfdd000-393d-11eb-8859-a8568e5b5d56.png)

**Comment by Toelk-A** [comment]
erledigt
