### ISSUE TITLE
GBMV / Stundenbericht Minijobber - Änderung Stundenlohn

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#805]
Bei unseren Minijobbern kommt es vor, dass sich von einem auf den nächsten Monat der Stundenlohn ändert.

![image](https://user-images.githubusercontent.com/22314271/101483601-b1556100-3958-11eb-8572-97a96e134b97.png)

Werden aus dem Vormonat (Stundenlohn 10,-€) Übertrage in den Monat mit neuem Stundenlohn z.B. (12€) übernommen, so muss auf dem Stundenbericht entsprechend die Auszahlung aufgesplittet werden.

Bitte dringend programmieren....

**Comment by mprueter** [comment]
Ich denke, ich habe das Problem jetzt gelöst.

Für den Fall, dass ein Mitarbeiter im Vormoant einen anderen StdSatz hatte und aus diesem Monat Stunden im AZK hat, gibt es jetzt folgendes:

![Bildschirmfoto 2020-12-21 um 12 31 22](https://user-images.githubusercontent.com/3273572/102773014-c8e50e80-4388-11eb-9f50-68b983bf62d0.png)

Das Gehalt berechnet sich dann wie folgt:

![Bildschirmfoto 2020-12-21 um 12 34 19](https://user-images.githubusercontent.com/3273572/102773070-e7e3a080-4388-11eb-9434-24da5ce09284.png)

...dieses Fenster sehen Sie im Übrigen, wenn Sie auf den Stift ganz rechts klicken:

![Bildschirmfoto 2020-12-21 um 12 35 46](https://user-images.githubusercontent.com/3273572/102773205-28431e80-4389-11eb-93a4-7a94b471986d.png)

Dieser erscheint nur in diesen besonderen Fällen. HIer können Sie ggf. auch die Daten anpassen (gelbe Felder)

**GRUNDSÄTZLICH GILT:**

Sollte es im angezeigten Monat erneut zu Überstunden kommen, dann würden die Stunden aus dem Vormonat immer im aktuellen Monat verbleiben.

Sollen bspw. nur 30 statt 3,34 Std. ausgezahlt werden,  muss der Vortrag aus dem Vormonat zwingend mit eingerechnet werden. Trägt man hier bei Auszahlung 30 h ein würde sich ein Auszahlung i.H.v. 30,56 h ergeben. 

![Bildschirmfoto 2020-12-21 um 12 46 47](https://user-images.githubusercontent.com/3273572/102774101-9dfbba00-438a-11eb-8d9b-6a6d426cc5f6.png)

Das würden Sie auch immer beim "Stift" sehen:

![Bildschirmfoto 2020-12-21 um 12 47 20](https://user-images.githubusercontent.com/3273572/102774151-b9ff5b80-438a-11eb-91ea-38f28a12895b.png)

Deswegen steht diese Vortragssumme auch immer unterhalb der ausgezhalten Stunden, da diese ggf. immer mit gerechnet werden muss.

Sinn dieser Vorehensweise ist es, ein ewiges Verschleppen der alten StdSätze zu verhindern.

Eigentlich müssten wir damit hin kommen. Falls es vorkommen sollte, dass sich ein Vortrag mit abweichendem Stundensatz über mehere Monate fortsetzt, müssen wir mal sehen... **Aber eigentlich kann das nicht passieren, da die Stunden dann immer im nächsten Monat ausbezahlt werden. Einzig, wenn eine enorme Überstundenzahl in einem Monat (>100%) angehäft wurde, könnte es schwierig werden.**
