### ISSUE TITLE
GTMV/ UKK - Augenanamnese fehlt

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#806]
Spender ID 

![image](https://user-images.githubusercontent.com/22314271/101599909-da2e3280-39fa-11eb-9724-b77142f639c2.png)

linke Hornhaut wurde nach Köln versandt. Augenanamnese bleibt allerdings leer

Bitte einmal prüfen, danke

**Comment by mprueter** [comment]
Das Problem war, dass das Kennezichen für die Seite ein kleines "d" war und nicht wie sonst ein großes "D":

![Bildschirmfoto 2020-12-09 um 11 30 04](https://user-images.githubusercontent.com/3273572/101618994-f2aa4700-3a12-11eb-9cda-b5c49a3d13c9.png)

Ich habe das korrigiert und in dem entsprechenden Feld eine Funktion eingebaut, die den Feldwert immer in Großuchstaben umwandelt.

Jetzt ist wieder alles da.

**Comment by Toelk-A** [comment]
danke
