### ISSUE TITLE
GBMV/ Personalmodul / MItarbeitedetails Personalnummer hinzufügen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#807]
Die Buchhaltung hätte gern ein Eingabefeld der "betriebsinternen Personalnummer", welche gleichzeitig auch auf den Stunden/Überstundenberichten abgebildet werden soll:

![image](https://user-images.githubusercontent.com/22314271/102318175-32c07b00-3f79-11eb-90c1-1b66fe14d5f0.png)

**Comment by mprueter** [comment]
![Bildschirmfoto 2020-12-16 um 08 58 58](https://user-images.githubusercontent.com/3273572/102320705-f5f68300-3f7c-11eb-9bb1-4620f607c35b.png)

**Comment by Toelk-A** [comment]
[Personalnummern GTMV.xlsx](https://github.com/chrbusch/GTM-V/files/5701165/Personalnummern.GTMV.xlsx)

**Comment by mprueter** [comment]
Das ist jetzt umgesetzt. Beim Layout Mitarbeiter-Details findne Sie jetzt ein Eingabefeld für die Personalnummer:

![Bildschirmfoto 2020-12-16 um 12 25 40](https://user-images.githubusercontent.com/3273572/102342816-0ff28e80-3f9a-11eb-9f3b-a034dbc798ed.png)

Den meisten GTMV-Mitarbeitern konnte ich mit Hilfe Ihrer Exceltabelle eine PersonalNr. zuweisen. Bei folgenden Mitarbeitern hat es nicht geklappt:

Ausgeschieden: Nagorsnik, Nils
Thiery, Johanna
Zimmermann, Annelie
Nadermann, Freya
Frank, Tessa
Woitas (UKK Projekt), Aline

Hier bitte ggf. die PersNr. manuell nachtragen.

Bei Frau Woitas gibt es bereits einen anderen Mitarbeiter-DS der eine PersonalNR. erhalten hat. Ich weiß nicht, wie Sie das in de Buchführung handhaben. **Sollte hier die gleiche PersonalNr. hinterlegt werden, muss ich eine Kleinigkeit an der Programmierung ändern, denn momentan darf jede PersonlaNr. nur einmal in der Tabelle Mitarbeiter auftauchen.** Kann ich aber schnelle ändern..

Die PersNr. taucht jetzt sowohl bei den Minijob- als auch bei den AZK-Berichten auf:

![Bildschirmfoto 2020-12-16 um 12 41 48](https://user-images.githubusercontent.com/3273572/102344405-26014e80-3f9c-11eb-8fd9-7e3f52c40861.png)


![Bildschirmfoto 2020-12-16 um 12 15 28](https://user-images.githubusercontent.com/3273572/102344411-2699e500-3f9c-11eb-880a-3a0049e4505c.png)

![Bildschirmfoto 2020-12-16 um 12 23 12](https://user-images.githubusercontent.com/3273572/102344412-27327b80-3f9c-11eb-87db-3c99f8db45fc.png)

**Comment by Toelk-A** [comment]
Das sieht erstmal gut aus. die Buchhaltung schaut sich das ganze an und gibt mir Feedback :-)

**Comment by Toelk-A** [comment]
Frau Woitas ist 2x als aktive MA in unserer Personaldatenbank. bei beiden Accounts muss sie die 75 erhalten. Hatte dies versucht, folgende Fehlermeldung:

![image](https://user-images.githubusercontent.com/22314271/102462957-c31ac080-404a-11eb-88b9-cd8271f6657a.png)

**Comment by mprueter** [comment]
Das solte jetzt funktionieren. Bitte testen...
