### ISSUE TITLE
Buchhaltungsmodul _ "Gutschriften / STornos zuordnen"

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#809]
Unsere Mitarbeiterin aus der Buchhaltung Frau Kaluzny lisa.kaluzny@gbm-v.de bittet um die folgende Programmierung:

Hallo Anita,

am besten wäre es, wenn man in Ornella auch die Stornos zuordnen könnte, sonst wird immer eine Rechnung offen stehen bleiben, obwohl sie ausgeglichen ist.
Könnte so etwas programmiert werden? Könntest du mein Anliegen bitte an Herrn Prüter weiterleiten? Mit Dr. Nitschke habe ich gerade darüber gesprochen.

Ich müsste beim unteren Beispiel noch die Rechnungsnummern 2020-3343 und 2020-3344 zuordnen. Da ich aber auch nicht die Gutschrift 2020-3345 (Storno) zuordnen kann, denkt Ornella nach Zuordnung von 2020-3343 es sei alles erfasst, da die Summe 19390€ entspricht. Aber es fehlen dann immer noch 2020-3344 und 2020-3345 in der Zuordnung. Dann ist es mir nicht mehr möglich 2020-3344 auszugleichen. Und das ist falsch.

Hintergrund: die ursprüngliche Rechnung 2020-3196 zum Storno wurde bezahlt am 05.11.20 und jetzt 16.12.20 ziehen sie sich den Storno ab.

![Tutogen](https://user-images.githubusercontent.com/22314271/102494104-751ab280-4074-11eb-8a38-acc7a50270ec.JPG)

**Comment by mprueter** [comment]
Das Problem ist gelöst Bisher bestand nicht Möglichkeit, einen Storno einer Kontobewegung zuzuordnen. Da Stonos bei Ihnen aber wie Gutschriften behandelt werden, habe ich diese Beschränkung jetzt aufgehoben:

![Bildschirmfoto 2021-02-17 um 11 31 53](https://user-images.githubusercontent.com/3273572/108193394-ae73ab00-7115-11eb-99e8-81546742043c.png)

Mit Frau Kaluzny habe ich diesbezüglich telefoniert und sie hat es abgenickt... ;-)

**Comment by Toelk-A** [comment]
erledigt
