### ISSUE TITLE
Urlaubswerte aktualiseiren zum Jahreswechsel

### ISSUE THREAD

**Issue by mprueter** [chrbusch/GTM-V#813]
Email von NIF:
Hallo Herr Busch,
im Personalmenü ist der Sonderurlaub im letzten Jahr hinzugefügt worden. Eine entsprechende Spalte existiert auch in der Urlaubsübersicht der einzelnen Mitarbeiter (siehe Foto), jedoch wird der im Kalender dokumentierte Sonderurlaub in der Übersicht nicht angezeigt bzw. mit berechnet.
Ich bitte um Prüfung.
HG
FPN

**Comment by mprueter** [comment]
Hallo Dr. Nitschke,

ich nehme an, Sie haben die Sonderurlaubstage für 2020 erst nach dem Jahreswechsel eingetragen, oder? Das beißt sich ein bisschen mit der bisherigen Programmierung, denn wenn Sie auf „Urlaubswerte aktualisieren“ klicken, wird immer nur das aktuelle Kalenderjahr aktualisiert. Das passiert übrigens auch einmal jede Nacht automatisch.

Um solche Fälle (Korrekturen im Vorjahr) in Zukunft abzufangen, gibt es jetzt die die Möglichkeit die Urlaubswerte des Vorjahres zu aktualisieren. Die geschieht mit Hilfe eins separaten Buttons im Jahres-Portal (s. Screenshot).

Dieser Button für das Vorjahr wird 30 Tage nach Jahresbeginn ausgeblendet.

![Bildschirmfoto 2021-01-11 um 11 52 45](https://user-images.githubusercontent.com/3273572/104192311-f3256b80-541e-11eb-88ed-6f1fcff81f6b.png)

**Comment by Toelk-A** [comment]
erledigt NIF 25.01.21
