### ISSUE TITLE
Prüfung Liefertermin und OP-Termin be Transplantat Auswahl und -Allokation

### ISSUE THREAD

**Issue by mprueter** [chrbusch/GTM-V#814]
Tel. Wunsch von NIF am 110121:

Liefertermin und OP-Termin sollen wechselseitig auf Plausibilität geprüft werden:

![Bildschirmfoto 2021-01-11 um 15 14 51](https://user-images.githubusercontent.com/3273572/104193138-0dac1480-5420-11eb-85e6-2c74f8427ee6.png)

Das OP-Datum darf max. 3 Tage nach dem Leiferdatum liegen ( 12.01. = Lieferdatum -> OP-Datum max. = 15.01.)

...vorerst Prüfung nur ohne Uhrzeit (evtl. später mit Uhrzeit)

techn.. Annm. : Umsetzung mit Triggerscript auf Feldern)

**Comment by mprueter** [comment]
Das ist jetzt ist jetzt umgesetzt. Sofern die Uhrzeitfelder noch leer sind (bzw. nicht beide gefüllt sind), wird der Zeitraum nur anhand des Datums geprüft. 

![Bildschirmfoto 2021-01-12 um 12 07 10](https://user-images.githubusercontent.com/3273572/104309917-2d504500-54d3-11eb-8d68-9c18c7d0e284.png)

Bei einer Eingabe, die die 3-Tages-Grenze überschreitet erscheint dann folgende Fehlermeldung:

![Bildschirmfoto 2021-01-12 um 12 07 15](https://user-images.githubusercontent.com/3273572/104310040-5ffa3d80-54d3-11eb-805e-d2e3cd1faf0e.png)

Der eingegebene Wert wird gelöscht. Es können somit keine fehlerhaften Werte mehr eingetragen werden.

Dabei ist es im Übrigen egal, welches Feld zuerst eingetragen wird (Liefer- oder OP-Termin)

Sind nach der Eingabe beide Uhrzeitfelder gefüllt, wird der Zeitraum auch im Hinblick auf die Uhrzeit geprüft (max. Dauer 72 Stunden):

![Bildschirmfoto 2021-01-12 um 12 07 43](https://user-images.githubusercontent.com/3273572/104310327-d26b1d80-54d3-11eb-9f7a-3e5573c97a41.png)

Es erscheint dann folgende Fehlermeldung:

![Bildschirmfoto 2021-01-12 um 12 07 49](https://user-images.githubusercontent.com/3273572/104310429-fcbcdb00-54d3-11eb-9373-2cc4844baec7.png)

Auch hier ist die Reihenfoge egal.


Techn. Anmerkung:
Neues Script -> GewAnfPos23. TRIGGER TerminCheck Liefg vs. OP (SP=options)/ 120121 mpr
-> Trigger auf den Eingabefelder für Datum und Uhrzeit

**Comment by Toelk-A** [comment]
ich nehme an dies ist erledigt :-)
