### ISSUE TITLE
GBMV/ Transplantate gelöscht aber physisch vorhanden

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#816]
Hallo Herr Prüter,
bitte die gelöschten Transplantate auch wikrlich ausblenden:
![image](https://user-images.githubusercontent.com/22314271/105046437-66eff580-5a69-11eb-8e32-39194c6e9ce0.png)

**Comment by mprueter** [comment]
Das aufgerufene Transplantat ist selbst ein gelöschtes Transplantat. Die "Löschung" erfolgt dadurch, dass die Spender-ID des Transplantates negativiert wird, also im o.g. Beispiel "-13939" statt "13939". 

Im Portal "Alle Transpl. d. Spenders" sehen Sie alle Transplantate die ebenfalls die Spender-ID des aufgerufenen Transplantates besitzen (im obigen Beispiel also die ID "-13939"). 

Wenn Sie also ein gelöschtes Transplantat aufrufen, sehen Sie alle weiteren gelöschten Transplantate des Spenders. Rufen Sie ein NICHT gelöschtes Transplantat auf, sehen Sie auch nur de nicht gelöschten:

![Bildschirmfoto 2021-01-20 um 09 29 27](https://user-images.githubusercontent.com/3273572/105148141-52ac0700-5b02-11eb-862e-594e44243fcf.png)

Ich weiß nicht, ob wir daran wirklich etwas ändern sollten?

**Comment by Toelk-A** [comment]
okay:-)
wenn ich in der Transplantatliste allerdings nach der 815 suche zeigt er mir 2x die 815 für 2020 an. Eine davon ist jeweils gelöscht... müssen wir also gleichzeitig, wenn man ein TX "löscht" auch die bankinterne Nummer rausnehmen?

![image](https://user-images.githubusercontent.com/22314271/105153681-00221900-5b09-11eb-8f77-5bb80facf7ad.png)
