### ISSUE TITLE
GBMV/ Dokumentation Arbeitszeit persönlicher Kalender Ornella

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#817]
Hallo Herr Prüter,
Zur Dokumentation ihrer Arbeitszeit nutzen die Mitarbeiter den persönlichen Kalender und den Button "Arbeitszeit erfassen".  Derzeit ist in diesem Button die Loginzeit -5min abgebildet. Das heißt logge ich mich 08:15 in Ornella ein, wird auf dem Button 08:10Uhr abgebildet.

1) Dies soll zukünftig nicht mehr so sein. Es soll die genaue Loginzeit also in unserem Besipiel 08:15 auf dem Button abgebildet sein.

2) Des Weiteren soll eine Sperre eingebaut werden. Der Mitarbeiter darf maximal 2min in die Zukunft sein Arbeitszeitende dokumentieren. 

![image](https://user-images.githubusercontent.com/22314271/105145912-a537f400-5aff-11eb-9ffa-08016dbc67c2.png)

**Comment by mprueter** [comment]
Punkt 1. ist eingebaut und sollte ab morgen (21.01.2020) wie gewünscht funktionieren. Bitte prüfen!

**Comment by mprueter** [comment]
Punkt 2. ist auch angepasst. Dieses Änderung ist auch ab sofort wirksam.
E bleibt alles beim Alten, nur die Frist ist auf 2 Minuten verringert. D.h. die Mitarbieter bekommen auch weiterhin den Hinweis bei Überschreitung und können ihn ggf. übergehen. Dann erfolgt aber ein Eintrag bei der Freigabe-Bemerkung.

Techn. Anm.: Script "Einsatz01AZe.Arbeitszeit erfassen mit DlgBox (SP=pk_MATag)/ 210120 mpr" in Personal.fp7 (Z. 65 ff)

**Comment by Toelk-A** [comment]
wir testen morgen früh. 2min Programmierung ist von NIF abgesegnet :-)

**Comment by Toelk-A** [comment]
Hallo Herr Prüter mir ist heute morgen aufgefallen:

ich habe mich 07:41 in Ornella eingeloggt, angezeigt wird 07:38Uhr. es scheinen noch immer die 5min Differenz programmiert zu sein. Können Sie dies bitte noch einmal prüfen

![image](https://user-images.githubusercontent.com/22314271/105456677-e0642f80-5c85-11eb-84c4-eea341c2522d.png)

**Comment by Toelk-A** [comment]
Hallo Herr Prüter, es gibt nach wie vor einen Zeitunterschied wie oben gezeigt:

![image](https://user-images.githubusercontent.com/22314271/105669316-557e7180-5edf-11eb-81ea-b17241751ac0.png)

**Comment by mprueter** [comment]
Bei Frau Kroll konnte ich das Problem verifizieren:

![Bildschirmfoto 2021-01-25 um 12 29 18](https://user-images.githubusercontent.com/3273572/105712570-44068b00-5f1a-11eb-9ae8-0ddcd25a2c79.png)

Jetzt muss ich es nur noch lösen...

**Comment by Toelk-A** [comment]
es scheint zu funktionieren
![image](https://user-images.githubusercontent.com/22314271/105809359-d4d87780-5fa9-11eb-9116-dbafa79cdfa8.png)
 0736Uhr Laptop angeschalten
07:39 Login in Ornella

**Comment by Toelk-A** [comment]
geprüft und erledigt
