### ISSUE TITLE
GTMV/ Basisparameter Labor Medicus Südstadt Corona PCR

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#818]
Notiz:

Seit November 2020 wird kein Ergebnis der Corona PCR mehr in Ornella übertragen. Nach Rücksprache mit Herrn Trommer wurden die Kürzel verändert: COROPC, COROP2 anstelle von SARS-CoV-RT-PCR. Ich habe dies in Ornella geändert und einen 2. Parameter (COROP2) angelegt. Wir müssen die morgige Übertragung abwarten und prüfen, ob die Ergebnisse in Ornella eingelesen wurden.

![image](https://user-images.githubusercontent.com/22314271/105188399-28733d00-5b34-11eb-90a3-1d0eb516ce6f.png)

**Comment by Toelk-A** [comment]
Mail von NIF: 21.01.21

Moin Herr Prüter,
warum wird hier ein neuer Datensatz angelegt (SARS-CoV-2 RT-PCR)? Lieg es daran, dass in der Anforderung noch in Klammern (COVID-19) steht?
HG
FPN



@mprueter nun ist genau das eingetreten was ich befürchtet hatte:

Aufgrund der 2 verschiedenen SARS-CoV-PCR "Kürzel" haben wir 2 "Anforderungen" 1 leer Originalanforderung und eine 2. Eregbnisanforderung... was können wir tun? es handelt sich um die LDT Dateien die heute über Nacht eingelesen wurden... mein System ist abgestürzt sonst hätte ich Ihnen noch einen screenshot geteilt

**Comment by Toelk-A** [comment]
Ich habe den Basisparametern entsprechend die Gene zugeordnet. Wir müssten nun ab Montag prüfen, ob es nach wie vor Dopplungen gibt. Der Wunsch von Dr. Nitschke ist keine "Dopplungen" siehe oben zu haben, da dadurch die Statistik (seien Ausladung) "zerschossen" wird.

![image](https://user-images.githubusercontent.com/22314271/105501741-e0375480-5cc4-11eb-95e8-93289476e6f2.png)

**Comment by mprueter** [comment]
Kurzer Einschub:

Ich habe gesehen, das es für für IgG-Test nach Impfung mittlerweile auch eine eigenen Code gibt:

![Bildschirmfoto 2021-03-01 um 11 35 47](https://user-images.githubusercontent.com/3273572/109486087-ba029280-7a82-11eb-9c6c-ea90ab14af76.png)


Wir haben bisher nur COROG:

![Bildschirmfoto 2021-03-01 um 11 36 57](https://user-images.githubusercontent.com/3273572/109486299-fb933d80-7a82-11eb-9de7-907a78a6196f.png)

Soweit ich das sehen kann, ist der Parameter bisher nur von NiF für einen Testpatienten angefordert worden.

**Comment by mprueter** [comment]
Ich überlege gerade, ob es wirklich nötig ist eine Weiche einzubauen. Der Parameter COROP2 wurde das letzte mal am 18.11.20 vom Labor übermittelt:

![Bildschirmfoto 2021-03-01 um 13 15 27](https://user-images.githubusercontent.com/3273572/109496002-5bdcac00-7a90-11eb-9927-307e06d8a79a.png)


seither wurde nur der Parameter COROPC übermittelt, auch wenn COROP2 angefragt wurde.

**Comment by mprueter** [comment]
Ich habe das Script zum Einlesen der Parameter aus Rostock jetzt dahin gehend angepasst, dass nur noch COROPC eingelesen wird. SOllte wider Erwarten COROP2 vom Labor übermittelt werden, wird dieser Wert automatisch in COROPC umgewandelt:

![Bildschirmfoto 2021-03-01 um 14 15 11](https://user-images.githubusercontent.com/3273572/109501904-8df20c00-7a98-11eb-8870-5ab259f1ddfe.png)

Gleichzeitig ist es im Unterusuchungsantrag ab sofort nur noch möglich den Parameter mit der ID 152 für den PCR-Test zu wählen:

![Bildschirmfoto 2021-03-01 um 14 19 21](https://user-images.githubusercontent.com/3273572/109502378-30aa8a80-7a99-11eb-899b-769d2c5b4cd5.png)


Bei den Spendern, bei denen beide Parameter vorhanden waren, habe ich den Parameter COROP2 entfernt.

Die Daten sind also bereinigt.


Viellicht sollte man jetzt den Namen des Parameters COROPC in Ornella wieder auf "SARS-CoV-2 RT-PCR" (statt "SARS-CoV-2 RT-PCR (E+S Gen)") ändern? 

techn. Anm.:
Änderung in Script  \_OP5BL.: Zeile 119 ff. (s. Screenshot)

**Comment by Toelk-A** [comment]
### Viellicht sollte man jetzt den Namen des Parameters COROPC in Ornella wieder auf "SARS-CoV-2 RT-PCR" (statt "SARS-CoV-2 RT-PCR (E+S Gen)") ändern?

ja das mache ich
