### ISSUE TITLE
GTMV/ MSG Abrechnung

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#819]
Spender ID 13861

Hallo Herr Prüter,

in der Abrechnung taucht die Fascia lata auf, obwohl sie beim Spender selbst nicht als Präparat angelegt ist. Können Sie einmal nachschauen, ob es hier eine Fehlprogrammierung gab, oder ob die Fascia lata NACH Rechnungsstellung gelöscht wurde?

![image](https://user-images.githubusercontent.com/22314271/105333658-45604c80-5bd6-11eb-8aaf-f0c8b9ed1d37.png)

**Comment by mprueter** [comment]
Es ist genauso, wie Sie es geahnt haben: Die Präparate wurden nach der Rechnunsgserstellung gelöscht:

![Bildschirmfoto 2021-01-21 um 12 36 44](https://user-images.githubusercontent.com/3273572/105346255-a2afca00-5be5-11eb-8904-4a8e30be5e1f.png)

**Comment by Toelk-A** [comment]
oh mannn :-(
