### ISSUE TITLE
Export csv für UKK

### ISSUE THREAD

**Issue by mprueter** [chrbusch/GTM-V#820]
s.a. #750 
Der Export wird jetzt auf dem Server ausgeführt und wenn er fertig ist, erhält der USer eine WV (analog zu #666 )

![Bildschirmfoto 2021-01-22 um 15 03 33](https://user-images.githubusercontent.com/3273572/105500870-cea17d00-5cc3-11eb-94a8-2941b2e1e483.png)

![Bildschirmfoto 2021-01-22 um 15 03 45](https://user-images.githubusercontent.com/3273572/105500927-e11bb680-5cc3-11eb-857d-57f4373764c6.png)

![Bildschirmfoto 2021-01-22 um 15 03 55](https://user-images.githubusercontent.com/3273572/105501026-f8f33a80-5cc3-11eb-9c18-7fbdbdccddd2.png)

**Comment by mprueter** [comment]
Sie haben jetzt auch die (bisher fehlende) Möglichkeit...

1. Die UKK-SPender nach Status und Jahr zu suchen:
2. 
![Bildschirmfoto 2021-02-01 um 16 36 37](https://user-images.githubusercontent.com/3273572/106480725-fe166d80-64ab-11eb-9ed3-5d9e37a6b9d4.png)

![Bildschirmfoto 2021-02-01 um 16 36 44](https://user-images.githubusercontent.com/3273572/106480738-01115e00-64ac-11eb-8adb-830aa2faf0b8.png)


2. Den Export entsprechend nach Jahr und Status zu filtern:
3. 
![Bildschirmfoto 2021-02-01 um 16 37 02](https://user-images.githubusercontent.com/3273572/106480853-21411d00-64ac-11eb-9790-65b337ef1f88.png)

![Bildschirmfoto 2021-02-01 um 16 37 08](https://user-images.githubusercontent.com/3273572/106480864-23a37700-64ac-11eb-8d8c-1ef014beceeb.png)

**Comment by Toelk-A** [comment]
Habe gerade einmal den Klick auf "SPSS auf Desktop speichern" geklcikt udn folgende Fehlermeldung erschien:

![image](https://user-images.githubusercontent.com/22314271/106720011-3d0b0700-6603-11eb-93f0-66d7c3b99226.png)

**Comment by mprueter** [comment]
Haben Sie mal nachgesehen, ob die Datei bereits auf Ihrem Desktop liegt?

**Comment by mprueter** [comment]
Damit die Daten bank nicht überquillt, habe ich es so eingerichtet, dass der übermittelnde Datensatz nach dem ersten öffnen gelöscht wird. Deswegen erscheint beim 2. Klick auf den Button diese Fehlermeldung... Kann ich bei Gelegenheit noch optimieren..
