### ISSUE TITLE
GTMV/ MSG Abrechnung DIZG Anpassung Standardkosten

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#821]
DIZG
Erhöhung Standardkosten von 300 auf 450€

Kann ich dies manuell anpassen, da wir noch Spenden aus dem Dezember haben, die abgerechnet werden müssen? Ab Januar gilt dann die Erhöhung auf 450,-€.

VG und danke

**Comment by Toelk-A** [comment]
Hallo Herr Prüter, können morgen die MSG Rechnungen testen. Habe eben die Protokolle erhalten VG

**Comment by mprueter** [comment]
Ich habe das jetzt bei den Preisen zwei Datensätze mit einer neuen Art eingefügt:

![Bildschirmfoto 2021-01-27 um 14 53 57](https://user-images.githubusercontent.com/3273572/106001020-c07ea280-60af-11eb-8880-72a26fc24d3e.png)

Einen Datenstatz für die alte Pauschale (End-Datum: 31.12.2020) und einen für die neue Pauschale (End-Datum: 31.21.2099).

Das jeweilige Anfangsdatum habe ich zwar auch mit notiert, es hat für die Suche der Preise aber keine Bedeutung. Es wird jeweils der Preis ausgewählt, dessen End-Datum noch nicht erreicht ist. Maßgeblich ist dabei immer das Datum der Spendermeldung.

Sollte sich die Pauschale in Zuunft wieder ändern, müssen Sie nur das Enddatum bei dem "2099" Datensatz in das dann reale Enddatum ändern und einen neuen Datensatz mit dem Enddatum "2099" anlegen.

**_Grundsätzlich sollten wir überlegen, dieses Modell auch auf alle anderen Preise zu übertragen, damit Sie mich nicht jedes Mal brauchen, wenn sich ein Preis ändert und damit die Auswertungen für Dr. Nitschke auch immer korrekt bleiben._**

Sie können die MSG-Abrechnung morgen einmal laufen lassen. Die Entschädigungen dann bitte einmal gründlich prüfen.

_Techn. Anm.
Neues Script: Preis10PS. -> Abruf der Pauschale MSG für spez. Kunden (oder sofern vorhanden mit Standardpreisen)
entspr. Anpassungen in folgendenden Scripten:
RngDeb72. Z 265. ff.
SpdGewebe1AS. Z. 357 ff._

**Comment by Toelk-A** [comment]
Rechnungsstellung getestet,
hat alles funktioniert! Danke!
