### ISSUE TITLE
GBMV/ Pfeil vor und zurück Transplantatdetails

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#823]
![image](https://user-images.githubusercontent.com/22314271/105987663-e0599a80-609e-11eb-8243-e68bd2fb4562.png)

Spenderweise blättern

**Comment by mprueter** [comment]
Die Pfeile (wie beim Spender) waren sogar schon auf dem Layout vorhanden. Allerdings war in dem das Detaillayout aufrufenden Script eine zwingende ISolierung des aufgerufenen DSes definiert. Deshalb erschienen die Pfeile nie, weil ja nur ein Datensatz aufgerufen war. Außerdem wurde jedes Mal die Liste auf den aufgerufeen Datensatz beschränkt und musste immer neue aufgerufen werden.

Das habe ich jetzt dahingehend geändert, dass bei einem Aufruf aus der Transplantat-Liste (GO-Btn) keine Isolierung mehr erfolgt. DIe Navigationsbutton sollten also erscheinen, sofern mehr als ein Datensatz in der LIste aufgerufen wurde.

Bitte einmal testen...

**Comment by Toelk-A** [comment]
Mitarbeiterin GBMV hat getestet!
alles super
Vielen Dank für die schnelle Umsetzung!
