### ISSUE TITLE
GTMV/ Neues Portal Dokumente Bezeichnung

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#824]
Zum Hochladev von Dokumenten können jetzt keine Bezeichnungen mehr eingegeben werden:

![image](https://user-images.githubusercontent.com/22314271/106254494-0dca5380-6219-11eb-9191-ab12a3636306.png)

Ist es möglich hier ein Eingabefenster zu programmieren, welches bei Bedarf (ähnlich VP20b WV) angeklickt werden kann um eine Bezeichnung für das hochzuladene Dokument zu hinterlegen?

![image](https://user-images.githubusercontent.com/22314271/106254916-8fba7c80-6219-11eb-9b8b-12b655c81d1c.png)

**Comment by mprueter** [comment]
Das ist möglich. Soll das zwingend oder optional sein?

**Comment by mprueter** [comment]
Ist jetzt vorhanden...

**Comment by Toelk-A** [comment]
danke
