### ISSUE TITLE
GTMV/ Neues Portal Dokument

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#825]
Mitarbeiter WIM (nicht VP20b!) kann Einträge löschen (Mülltonne eingeblendet) bitte prüfen

![image](https://user-images.githubusercontent.com/22314271/106254988-ad87e180-6219-11eb-89b9-89e2cfab96b9.png)

**Comment by mprueter** [comment]
Er kann seine Einträge löschen, solange der Eintrag nicht freigegeben ist. Das ist mit Absicht so gemacht, da man sonst keine Chance hat versehentliche Einträge zu löschen...
