### ISSUE TITLE
Logbook-Eintrag wenn Dokument zu Spender gelöscht wird

### ISSUE THREAD

**Issue by mprueter** [chrbusch/GTM-V#828]
Sofern ein Datensatz im Portal Dokumente gelöscht wird...

![Bildschirmfoto 2021-01-29 um 15 43 36](https://user-images.githubusercontent.com/3273572/106289143-34a07e00-6249-11eb-9743-7859284ba9ce.png)

 wird das ab sofoart auch im Logbook dokumentiert;

![Bildschirmfoto 2021-01-29 um 15 45 40](https://user-images.githubusercontent.com/3273572/106289170-3b2ef580-6249-11eb-9cdc-c43d6c75ca0e.png)

**Comment by Nitschke-FP** [comment]
Kann noch Datum und Zeit der Löschung mit angezeigt werden?

Mit freundlichen Grüßen

Dr. med. Frank-Peter Nitschke
Geschäftsführender Arzt

[/Users/Frank-PeterNitschke/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_1396075393]

GTM-V Gesellschaft für Transplantationsmedizin
Mecklenburg-Vorpommern
gemeinnützige GmbH
Wilhelm-Külz-Platz 3
18055 Rostock

'           +49 381 444 30 50
7            +49 381 444 30 525
Mobil:       +49 171 222 26 06
@       frank-peter.nitschke@gtm-v.de<mailto:frank-peter.nitschke@gtm-v.de>
•          www.gtm-v.de<http://www.gtm-v.de/>

USt-IdNr.: DE 298945377 Amtsgericht Rostock, HRB 13143 Geschäftsführer:          Dr. med. Frank-Peter Nitschke
                                     Dr. med. Axel Manecke

Diese Email enthält vertrauliche und/oder rechtlich geschützte Informationen. Jeglicher unbefugter Gebrauch oder Verbreitung dieser Nachricht oder Auszüge dieser Nachricht ist strengstens verboten. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail.

This e-mail may contains confidential and/or privileged information. Any unauthorised usage or dissemination of this message in whole or in part is strictly prohibited. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail.

Von: "m.prueter" <notifications@github.com>
Antworten an: chrbusch/GTM-V <reply@reply.github.com>
Datum: Freitag, 29. Januar 2021 um 15:49
An: chrbusch/GTM-V <GTM-V@noreply.github.com>
Cc: "Dr. Frank-Peter Nitschke" <frank-peter.nitschke@gtm-v.de>, Assign <assign@noreply.github.com>
Betreff: [chrbusch/GTM-V] Logbook-Eintrag wenn Dokument zu Spender gelöscht wird (#828)


Sofern ein Datensatz im Portal Dokumente gelöscht wird...

[Bildschirmfoto 2021-01-29 um 15 43 36]<https://user-images.githubusercontent.com/3273572/106289143-34a07e00-6249-11eb-9743-7859284ba9ce.png>

wird das ab sofoart auch im Logbook dokumentiert;

[Bildschirmfoto 2021-01-29 um 15 45 40]<https://user-images.githubusercontent.com/3273572/106289170-3b2ef580-6249-11eb-9cdc-c43d6c75ca0e.png>

**Comment by mprueter** [comment]
…das ist immer automatisch das Datm des LogBook-Eintrages.

Mit freundlichen Grüßen

Maik Prüter

__________________________________________
IT-Büro Dr. Christopher Busch
Sottorfallee 18
22529 Hamburg


Kontakt in Potsdam:
Maik Prüter
Pomonaring 9
14469 Potsdam
(+49) 0331 - 96 76 35 93
mpr_christopherbusch@icloud.com

**Comment by Nitschke-FP** [comment]
Sorry, habe ich übersehen. Danke und schönes WE
FPN

Mit freundlichen Grüßen

Dr. med. Frank-Peter Nitschke
Geschäftsführender Arzt

[/Users/Frank-PeterNitschke/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_1837985417]

GTM-V Gesellschaft für Transplantationsmedizin
Mecklenburg-Vorpommern
gemeinnützige GmbH
Wilhelm-Külz-Platz 3
18055 Rostock

'           +49 381 444 30 50
7            +49 381 444 30 525
Mobil:       +49 171 222 26 06
@       frank-peter.nitschke@gtm-v.de<mailto:frank-peter.nitschke@gtm-v.de>
•          www.gtm-v.de<http://www.gtm-v.de/>

USt-IdNr.: DE 298945377 Amtsgericht Rostock, HRB 13143 Geschäftsführer:          Dr. med. Frank-Peter Nitschke
                                     Dr. med. Axel Manecke

Diese Email enthält vertrauliche und/oder rechtlich geschützte Informationen. Jeglicher unbefugter Gebrauch oder Verbreitung dieser Nachricht oder Auszüge dieser Nachricht ist strengstens verboten. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail.

This e-mail may contains confidential and/or privileged information. Any unauthorised usage or dissemination of this message in whole or in part is strictly prohibited. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail.

Von: "m.prueter" <notifications@github.com>
Antworten an: chrbusch/GTM-V <reply@reply.github.com>
Datum: Freitag, 29. Januar 2021 um 16:00
An: chrbusch/GTM-V <GTM-V@noreply.github.com>
Cc: "Dr. Frank-Peter Nitschke" <frank-peter.nitschke@gtm-v.de>, Assign <assign@noreply.github.com>
Betreff: Re: [chrbusch/GTM-V] Logbook-Eintrag wenn Dokument zu Spender gelöscht wird (#828)

…das ist immer automatisch das Datm des LogBook-Eintrages.

Mit freundlichen Grüßen

Maik Prüter

__________________________________________
IT-Büro Dr. Christopher Busch
Sottorfallee 18
22529 Hamburg


Kontakt in Potsdam:
Maik Prüter
Pomonaring 9
14469 Potsdam
(+49) 0331 - 96 76 35 93
mpr_christopherbusch@icloud.com
