### ISSUE TITLE
GTMV/ TRansportbegleitschein pro Gewebe/Entnahme

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#829]
Mit dem neuen Prozesschrittmodul sollten die Transportbegleitscheien pro Gewebe/Entnahme ausgestellt sein udn du Fußzeilen müssen entsprechend angepasst werden.

In den Basisdokumenten sind allerdings noch "ALLE" Gewebe für den selben Transportbegleitschein hinterlegt

![image](https://user-images.githubusercontent.com/22314271/106446107-212b2800-6480-11eb-8f09-4332c48163ca.png)

**Comment by mprueter** [comment]
Das ist jetzt umgesetzt. Bitte passen Sei die Werte für die anderen Gewebarten ggf. an. Die Kategorie "Alle" habe ich erst einmal drin gelassen, damit Sie die Ausgangssituation sehen. Wenn alle Gewebarten aktalisert sind, können Sie diese Zeile eigentlich löschen.

![Bildschirmfoto 2021-02-01 um 15 00 59](https://user-images.githubusercontent.com/3273572/106469024-fc927880-649e-11eb-9a5f-da4be13988de.png)

**Comment by Toelk-A** [comment]
Danke!
