### ISSUE TITLE
Einwilligungserklärung Abschnitt V Freigabe Staatsanwalt 

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#83]
wenn "Natürlich" angeklickt wird, müssen ebenfalls "Auflagen" und "Freigabe Entnahme" inklusive "Gewebe/Bemerkungstabelle" ausgeblendet werden

![image](https://cloud.githubusercontent.com/assets/22314271/21636683/e552cae8-d263-11e6-9d1c-725a0612d7a4.png)

**Comment by chrbusch** [comment]
Erledigt

**Comment by Toelk-A** [comment]
funktioniert
