### ISSUE TITLE
GTMV/ Dokumentenprotal Spenderkennummer fehlt wieder bei Wiedervorlage

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#832]
![image](https://user-images.githubusercontent.com/22314271/106589443-513ffd00-654c-11eb-870b-07bfceec20f0.png)

**Comment by mprueter** [comment]
Ich vermute, es handelt sich hier um ein Aktualisierungsproblem, da ich die SpdKennNr bisher über eine SQL-Abfrage geholt habe. Ich habe das jetzt über eine feste Beziehung gelöst, sodass dieses Problem nicht mehr auftreten sollte.

In der WV selber war nämlich die Spender-ID hinterlegt, der Zugriff auf das richtige Dokument war also von der fehlerhaften Anzeige der SpenderkennNr. nicht beeinflusst:

![Bildschirmfoto 2021-02-02 um 12 45 18](https://user-images.githubusercontent.com/3273572/106596287-14c4cf00-6555-11eb-89a0-74985503265d.png)


Bitte beobachten!

**Comment by Toelk-A** [comment]
erledigt
