### ISSUE TITLE
GTMV/Dokumentenportal Anpassungswünsche

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#833]
Hallo Herr Prüter,

nach Klick auf die Wiedervorlage öffnet sich sofort das Dokument, ohne dass man Daten des eigentlichen Spenders vorab einsehen konnte. Aus diesem Grund haben die MA folgende Anpassungswünsche:
die Mitarbeiter  haben folgende Wünsche:

![image](https://user-images.githubusercontent.com/22314271/106592090-58b4d580-654f-11eb-97d4-89afdb91b782.png)

1) Abbildung "Status des Spenders" aus den Spenderdetails
![image](https://user-images.githubusercontent.com/22314271/106592157-72eeb380-654f-11eb-9044-b4b8e800fb41.png)
 
2) Abbildung Name + Sterbezeitpuntk (HKTS) des Spender
![image](https://user-images.githubusercontent.com/22314271/106592296-a03b6180-654f-11eb-9559-6af722aad4ea.png)

bzw bei Organspender

![image](https://user-images.githubusercontent.com/22314271/106592387-bcd79980-654f-11eb-9bda-85eb3416db67.png)

3) Abbildung Gewebe des Spenders (Spenderdetails)

![image](https://user-images.githubusercontent.com/22314271/106592449-cd880f80-654f-11eb-8ca5-e1d9d53b75e3.png)

**Comment by mprueter** [comment]
Bitte einmal prüfen, ob das jetzt so okay ist:

![Bildschirmfoto 2021-02-02 um 13 18 54](https://user-images.githubusercontent.com/3273572/106599394-463f9980-6559-11eb-9991-ec58f39d7807.png)

**Comment by Toelk-A** [comment]
![image](https://user-images.githubusercontent.com/22314271/106600053-34aac180-655a-11eb-9bcf-b08a4eedbf70.png)

1) Bitte den Pfeilen entsprechend anpassen

2) Wenn Status Spendermeldung "Abbruch oder Archiviert" Spenderkennnummer bitte "rot" einblenden

**Comment by mprueter** [comment]
zu 2.:
Das ist schon so...

![Bildschirmfoto 2021-02-02 um 14 00 56](https://user-images.githubusercontent.com/3273572/106603881-2b702380-655f-11eb-9688-648c2009d4de.png)

Die farbliche Gestaltung entspricht genau der aus der Spender-Details-Maske. Dabei ist die SpdKennNr nur rot, wenn der Spender-Status = "Abbruch" ist. sonst ist er immer grün (auch bei Archivierung)

**Comment by mprueter** [comment]
Sollen die Daten eigentlich nur eingesehen werden können, oder sollen auch Eingaben gemacht werden können?

**Comment by mprueter** [comment]
Zu 1.:
 das ist jetz auch angepasst. Allerdings dürfte es Darstellungsprobleme gebe, wenn irgendwann einmal mehr als 3 Gewebearten entnommen werden sollten. Das war der Grund, warum ich die Anzeige auf die rechte Seite getan hatte... ;-)

![Bildschirmfoto 2021-02-02 um 14 15 10](https://user-images.githubusercontent.com/3273572/106605483-3deb5c80-6561-11eb-8368-9d41acc27ee2.png)

**Comment by Toelk-A** [comment]
### Sollen die Daten eigentlich nur eingesehen werden können, oder sollen auch Eingaben gemacht werden können?
nur einsehen ist besser 

### HKTS
können Sie den HKTS rechts oben neben dem Namen/alter abbilden? dann sollte unten noch 1 Zeile mehr Platz für die Gewebe sein :-)

**Comment by mprueter** [comment]
Wie besprochen jetzt HKTS etc.  neben der Spender-Art:

![Bildschirmfoto 2021-02-02 um 15 57 59](https://user-images.githubusercontent.com/3273572/106618104-72feab80-656f-11eb-9ea0-5196ecab87e4.png)

**Comment by Toelk-A** [comment]
erledigt
