### ISSUE TITLE
GTMV/ Anapssung Dokumentenprotal ICD Codes

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#834]
Halo Herr Prüter,

da das Dokumentenprotal nicht im Hintergrund geöffnet bleiben kann, was auch richtig ist ;-), benötigen wir eine Alternative um die ICD Codes in den Spenderdetails auf Vollständigkeit kontrollieren, bzw Codes hinzufügen zu können ohne ständig das Dokument zu öffnen und zu schließen. 

Ist es möglich im Dokumentenportal ein Popupfenster der ICD Codes anzeigen zu lassen bzw über diese Fenster Diagnosen hinzufügen zu können?
 Danke dun VG

![image](https://user-images.githubusercontent.com/22314271/106592853-51da9280-6550-11eb-8c34-6b35c36e19cb.png)

**Comment by mprueter** [comment]
Ist jetzt alles eingbaut uns funktionsfähig:


![Bildschirmfoto 2021-02-02 um 15 53 29](https://user-images.githubusercontent.com/3273572/106617423-e81db100-656e-11eb-8fab-b1c4230cd23e.png)


Bitte testen...

**Comment by Toelk-A** [comment]
funktioniert super

ABER ;-)

Die Mitarbeiter wünschen sich, dass nach Einagbe des ICD Codes über das Dokumentenportal, das PDF nicht automatisch wieder auf Seite 1 springt und die Mitarbeiter wieder zur vorher geöffneten Seite (z.B 4) zurückscrollen müssen.

**Comment by Toelk-A** [comment]
funktioniert noch nicht

**Comment by mprueter** [comment]
Im Modalfenster zum Dokument finden Sie jetzt einen weietren Reiter mit einer alternativen Zuordnungsmöglickeit für die ICD-Codes:

![Bildschirmfoto 2021-02-19 um 13 43 18](https://user-images.githubusercontent.com/3273572/108506997-faf7eb80-72b9-11eb-8a41-da06fa8d56ba.png)

Das Prinzip ist ganz einfach: im gelben Suchfeld tragen Sie einen Suchbegriff ein. Im blauen Portal darunter werden können Sie mit dem "+"-Button den jeweilgen Code den Diagnosen des Spender zuweisen. (Sollte der Code bereits zugewisen sein passiert einfach nix.)

Die Funktionalität entspricht dem Portal in der Spender-Deatailsmaske (Risiko, Diabetes etc.).

Es erfolgt kein versteckter Layoutwechsel und deshalb bleibt auch der Scrollbalken im Dokument an der gelcihen Stelle.

Sollte sich das unterere Portal einmal nicht automatisch aktualisieren (kann evtl. beim Zugriff über eine langsame Internetverbindung passieren), drücken Sie bitte diesen kleine Button:

![Bildschirmfoto 2021-02-19 um 13 56 35](https://user-images.githubusercontent.com/3273572/108507686-f849c600-72ba-11eb-960b-6d905fdd69ed.png)

Techn. Anm.:
Neues Script für Zuweisung des Codes via Auto-PSOS: SpdDgn01p.

Hinweis: Es gibt auch ein Bausteinscript SpdDgn01m. mit der gleichen Funktionalität um ICD-Codes einem Spd zuzuweisen. (derzeit nur bei Test-Spd mgl.)

**Comment by mprueter** [comment]
Läuft das stabil bei Ihnen?

**Comment by Toelk-A** [comment]
Hallo herr Prüter, kann scharf geschalten werden... also ist es ja schon, aber entsprechend kann die alte ICD Code Erfassung rausgenommen werden im Dokumentenprotal VG

**Comment by mprueter** [comment]
Ist umgestellt.
