### ISSUE TITLE
GTMV/ Dokumentenportal JPEG Formate werden nciht mehr angezeigt

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#835]
Hallo Herr Prüter,

mit Umstellung des Dokumentenprotals ist uns aufgefallen, das zuvor hochgeladenen JPEG FOrmat jetzt nicht mehr zu öffnen sind. Falls die Behörde einmal zur Kontrolle kommt, ist dies natürlich schwierig. Gibt es eine Möglichkeit, die vor der Umstellung des Dokumentenportals hochgeladenen JPEG Formate noch im Nachhinein öffnen zu können? 

![image](https://user-images.githubusercontent.com/22314271/106762391-14e8cb80-6636-11eb-8a4c-b902e89d72c7.png)

**Comment by mprueter** [comment]
Grundsätzlich kann ich ihnen einen Button dahin setzen, der das Dokument wie bisher öffnet. 
Wäre das okay?

**Comment by Toelk-A** [comment]
das wäre super udn ist ausreichend :-)

**Comment by mprueter** [comment]
SIe haben jetzt so einen Button, für den Notfall:

![Bildschirmfoto 2021-02-03 um 18 01 05](https://user-images.githubusercontent.com/3273572/106781917-e248ce00-6649-11eb-8fca-b6837c81cc07.png)


Der erscheint nur bei Dateien, die kein "PDF" sind. 

Wie Sie sehen, scheint es auf dem MAC aber zu funktionieren... Das hängt wieder an Adobe.

**Comment by Toelk-A** [comment]
funktioniert super! danke
