### ISSUE TITLE
GTMV Dokumentenportal

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#837]
Im Home Office ist es sehr schwer die PDFS auf dem Laptop zu lesen. Gibt es eine Möglichkeit die PDFs mittels Pfeil größer und das Dokumentenportal kleiner zu machen? Nutzt man die "+-Funktion" von Adobe muss man über einen anderen Balken ständig nach Links und rechts verschieben um das PDF lesen zu können.

![image](https://user-images.githubusercontent.com/22314271/107764974-59105600-6d31-11eb-92cf-c66139e14ddb.png)

**Comment by mprueter** [comment]
Ich kann es leider nicht so machen, dass der Ausschnitt dynamisch verschoben wird. Aber so ähnlich...

Sie finden jetzt etwa n der Mitte einen blauen Balken:

![Bildschirmfoto 2021-02-15 um 09 46 41](https://user-images.githubusercontent.com/3273572/107924350-13db6680-6f73-11eb-8031-839d63e0e1dc.png)

Wenn Sie den drücken, wird das Dokument auf dei volle Breite des Fensters vergößert. Sie gelangen dann über die beiden Balken (links oder rechts) wieder zurück in die normale Ansicht:

![Bildschirmfoto 2021-02-15 um 09 46 52](https://user-images.githubusercontent.com/3273572/107924522-59982f00-6f73-11eb-91b7-993e391e70eb.png)

**Comment by Toelk-A** [comment]
erledigt
