### ISSUE TITLE
Entnahmebericht ist immer individuell für entnommenes Gewebe

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#84]
Es muss in der Überschrift immer zwischen Entnahmebericht "OG", "KVG", "MSG" etc unterschieden werden

101216-1148-GNO-TOA

![image](https://cloud.githubusercontent.com/assets/22314271/21637427/2109c4d0-d267-11e6-8ce2-c742bc308309.png)

**Comment by Toelk-A** [comment]
scheint PDF Ausgabe Problem zu sein

**Comment by chrbusch** [comment]
Ja, ist aber jetzt behoben, oder?
