### ISSUE TITLE
GBMV/ PDF Dokument anpassen exakt zum 22.02.21_Freigabeprotokoll OG Tx Patch

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#840]
Hallo Herr Prüter,

bitte zum 22.02.21 die neue Version (in Anlage) in ornella scharfschalten. Änderungen sind gelb markiert

Danke!

[3.4.3.13.4 F Freigabeprotokoll OG-Tx Patch_markiert.pdf](https://github.com/chrbusch/GTM-V/files/5987155/3.4.3.13.4.F.Freigabeprotokoll.OG-Tx.Patch_markiert.pdf)

**Comment by mprueter** [comment]
Hier habe ich einen neuen Datensatz in den BasisDokumenten angelegt. Dieser beruht zwar auf dem geichen Drucklayout wie die Kornea-Transplantate, es wird aber eine separate QC-Nr gepflegt.

Beim Druck der Versandpapiere sollte es schon funktionieren. Beim Druck via Prozessschritt muss ich das noch prüfen.

**BITTE UNBEDINGT ZEITNAH TESTEN!!!**

Beim Druck via Prozessschritt muss ich das noch prüfen.


techn. Anm.:
Änderung in Script SpTranspl23. in Z. 86 ff. (LayoutSwitch je nach Klassifikation des Transpl.)

![Bildschirmfoto 2021-02-22 um 11 12 20](https://user-images.githubusercontent.com/3273572/108694054-d93b7600-74fe-11eb-90ed-1749990d843b.png)

**Comment by Toelk-A** [comment]
funktioniert alles -> zum Thema LOGO das "g" in gemeinnützig wird jetzt "klein " geschrieben..... ;-)

**Comment by Toelk-A** [comment]
das heißt ich müsste ein neues Logo hinterlegen.... QM diskutiert noch einmal darüber... Ihr Auftrag ist erst einmal erfüllt ;-)

**Comment by mprueter** [comment]
...noch nicht ganz, aber jetzt:

Beim Druck via Prozessschritt wird jetzt auch das richtige Layout gewählt.

techn. Anmerkung:

Scriptweiche in Gen01. (speziell für BasProzSchr-ID = 97) Z 47 ff.

![Bildschirmfoto 2021-02-22 um 11 56 09](https://user-images.githubusercontent.com/3273572/108699056-11de4e00-7505-11eb-84d1-3ee098041d59.png)
