### ISSUE TITLE
GBMV/ Personalmodul / MItarbeiterliste

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#848]
Ich benötige noch einmal die MItarbeiterliste aus 2020 zum Stand 31.12.20. Leider ist es nicht möglich einen bestimmten Zeitraum abzurufen. 

![image](https://user-images.githubusercontent.com/22314271/108713706-e2394100-7518-11eb-8f34-632d59f12834.png)

**Comment by mprueter** [comment]
Ich habe das wie folgt gelöst:

Der Dialog enthält jetzt anstatt des Buttons "Übern." die Option "Andere":

![Bildschirmfoto 2021-02-23 um 13 40 14](https://user-images.githubusercontent.com/3273572/108844820-e3cc3d00-75dc-11eb-935c-8557e9e3e7ac.png)

Wenn Sie diese Option wählen, erscheint folgender Dialog mit einer Auswahl an Monaten:

![Bildschirmfoto 2021-02-23 um 13 40 20](https://user-images.githubusercontent.com/3273572/108844901-fe9eb180-75dc-11eb-9ed1-7fc46d645bd8.png)

Ich denke, das sollte ausreichend sein, oder?

**Comment by Toelk-A** [comment]
eerledigt
