### ISSUE TITLE
GTMV/ MSG Entnahmebericht rechts unten fehlt Seitenzahl

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#849]
Hallo Herr Prüter,

uns ist aufgefallen, dass auf dem MSG Entnahmebericht die Seitenzahlen fehlen, wenn man das Dokument nach Freigabe durch VP20b über das "Auge" öffnet.

Können Sie dies bitte einmal prüfen?

Spender ID 14585
![image](https://user-images.githubusercontent.com/22314271/108723068-23831e00-7524-11eb-85e2-e22dda054f51.png)

**Comment by mprueter** [comment]
Dieses Problem trat bei allen Dokumenten auf, die Sie über das Portal der SPS als PDF geöffnet haben. Ich habe das jetzt angepasst.

techn. Anm.:
Script GEN01NEU. ergänzt um Seitenzahlgenerierung:

![Bildschirmfoto 2021-03-01 um 09 15 54](https://user-images.githubusercontent.com/3273572/109469931-017f2380-7a6f-11eb-90ea-1b27d949b645.png)

**Comment by Toelk-A** [comment]
Danke!
