### ISSUE TITLE
GTMV/ OG Entnahmebericht zerschossen 

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#850]
Spender ID 14900

Ich habe heute Morgen beim o.g. Spender ein "3. Auge" in den Präparaten gelöscht.

![image](https://user-images.githubusercontent.com/22314271/108848108-dfa21e80-75e0-11eb-926c-5c3d96ffb57b.png)

Nun hat die die GBM-V bereits Transplantate angelegt.

Wir können den OG Entnahmebericht nicht mehr öffnen. Folgende Fehlermeldung erscheint:

![image](https://user-images.githubusercontent.com/22314271/108848184-f8123900-75e0-11eb-8282-5c319db34b30.png)

Können Sie dies retten? :-)

**Comment by mprueter** [comment]
Fehler ist korrigiert, allerdings konnte ich das seltsame Verhalten des Programmes beim Löschen nicht reproduzieren.

**Comment by Toelk-A** [comment]
danke
