### ISSUE TITLE
GBMV/ Personalmodul Mitarbeiterliste

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#851]
Hallo Herr Prüter,

in 2020 hatten wir 366Tage -> bedeutet für die VP20b hätten 366d insgesamt Dienstgeleistet werden müssen. Ich komme mit meiner Rechnung und den Daten aus der Mitarbeiterliste auf 355d (gelbe Markierung). ES fehlen also 11d RBD. Können Sie bitte einmal nachschauen, ob die Berechnungen in der Mitarbeiterliste stimmen?

Danke und VG

![image](https://user-images.githubusercontent.com/22314271/108849560-8f2bc080-75e2-11eb-89ad-45835d7b087b.png)

**Comment by mprueter** [comment]
Die Summen in der Liste stimmen. Es gibt tatsächlich einige Tage, an denen kein VP20 gesetzt ist:

![Bildschirmfoto 2021-02-24 um 14 15 17](https://user-images.githubusercontent.com/3273572/109006043-e72dfa00-76aa-11eb-8dc1-01f03e8c470c.png)


???

**Comment by Toelk-A** [comment]
Sie haben Recht!
