### ISSUE TITLE
GBMV/ Button Versandpapiere drucken_TRansplantationsbegleitschein

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#852]
Die Versandpapiere beinhalten unter anderem den Transportbegleitschein, einmal mit Patientendaten und einmal blanko.

Bitte im blanko Transplantationsbegleitschein die Patienten ID NICHT abbilden. Derzeit wird diese dort auch automatisch übernommen.

Danke

**Comment by mprueter** [comment]
Es geht um diesen Button, oder?

![Bildschirmfoto 2021-03-01 um 09 20 42](https://user-images.githubusercontent.com/3273572/109470301-82d6b600-7a6f-11eb-93dd-2097bc02dba8.png)

**Comment by Toelk-A** [comment]
ja genau

**Comment by mprueter** [comment]
...ist jetzt ausgeblendet. Bitte einmal testen.

**Comment by Toelk-A** [comment]
erledigt
