### ISSUE TITLE
GTMV/ mob. Team - "werteliste" Standort mob Team

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#853]
Hallo Herr Prüter,
in der "Werteliste" - ist eigentlich eine Ornella Selbstlernliste - hat einer unser Kollegen das Wort Rostock falsch hinterlegt. Können Sie dies irgendwie rauslöschen?

Danke :-)

![image](https://user-images.githubusercontent.com/22314271/108999148-30c61700-76a2-11eb-888d-bc6f133e08a5.png)

**Comment by mprueter** [comment]
Ist korrigiert.

**Comment by Toelk-A** [comment]
danke :-)
