### ISSUE TITLE
GBMV Buchhaltung- Automatisierte Rechnungsabgrenzungen pro Monat

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#854]
Es wäre wichtig Rechnungen monatlich abzugrenzen. 
Anfang Februar sind viele Rechnungen geschrieben worden, die Leistungsdaten sowohl im Januar als auch im Februar haben.
Das macht es mir für die monatliche Meldung unheimlich schwer. Da ich diesen Sachverhalt im Buchhaltungsprogramm trennen muss.

So wird es sicherlich auch vielen Kliniken gehen, die die passende ursprüngliche Rechnung dazu haben und dem Finanzamt monatlich melden. Es wäre also freundlicher für die Kliniken und für die GBM-V.

daher meine Bitte, dass Ornella automatisch 2 Rechnungen dafür generiert, wenn 2 unterschiedliche Leistungszeiträume (Monate) auf einer Rechnung erkannt wurden.
Zum Beispiel Rechnung B2021-2597:
![image](https://user-images.githubusercontent.com/22314271/109307446-f5ae1a00-7840-11eb-8ff8-1fa1643a19a0.png)

**Comment by Toelk-A** [comment]
Wenn Status zu berechnen
![image](https://user-images.githubusercontent.com/22314271/117149240-54e75800-adb7-11eb-98d2-b8ece150ff81.png)



Duplikat an GBM-V
![image](https://user-images.githubusercontent.com/22314271/117149124-31241200-adb7-11eb-9f30-7911cef47685.png)

**Comment by mprueter** [comment]
Das Script ist jetzt angepasst. Bei den jeweils aufgerufenen GewAnfPos/Transpl. wird zunächst geprüft, ob die jeweiligen Angaben für das Lieferdatum in mehreren Kalndermonaten liegen. Sofern dies der Fall ist werden alle Transpl. pro Kalenddermonat mit einer Rechnung abgerechnet.

Zusätzlich habe ich (sofern der Aufruf des Abrechnungsscriptes über die Transplantatliste erfolgt) eine Prüfung eingebaut, die den Vorgang abbricht, sofern Transplantate für mehrere Topadressen aufgerufen sind:

![Bildschirmfoto 2021-05-06 um 14 00 37](https://user-images.githubusercontent.com/3273572/117294894-77d74200-ae73-11eb-9dff-8791603ae75b.png)


### HINWEIS/WICHTIG:
Die Abrechnung sollte unbdeingt mittelfristig auf ein ähnliches Modell wie bei MSG umgebaut werden. Die derzeitige Konzeption des Vorgangs ist äußerst abhängig von einer vorherigen fehlerfreien Auswahl der Tarnsplantate durch den User!! 

techn. Anmerkung:
Umfangreiche Änderungen in Script RngDeb50. (Loop über Monate-> je Monat eine Rechnung)
