### ISSUE TITLE
GTMV/ Wiedervorlage "Medizinische Indikationsprüfung anlegen" scheint nicht richtig programmiert

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#856]
WV medizinische Indikationsprüfung anlegen für XXXX 

- klickt man auf die WV öffnet sich ein feld in dem das Gesprächergebnis aus dem ANG dokumentiert werden soll? 
- > dies hat heir ncihts zu suchen
- Klickt man auf abbrechen kommt man in eine leere Spendermaske...

Bitte einmal Skript hinter der Wiedervorlage prüfen,

danke

![image](https://user-images.githubusercontent.com/22314271/109668922-e8ab6680-7b71-11eb-8086-da86865979eb.png)

![image](https://user-images.githubusercontent.com/22314271/109668968-f2cd6500-7b71-11eb-8471-b986a2e5ed6d.png)

![image](https://user-images.githubusercontent.com/22314271/109669022-011b8100-7b72-11eb-9895-3c86ccd08dae.png)

**Comment by mprueter** [comment]
Eigentlich soll der User hier nur zur Spendermaske wechseln oder?

**Comment by Toelk-A** [comment]
ja genau

**Comment by mprueter** [comment]
Das Problem ist jetzt behoben. Aufgrund eines Programmierfehlers wurde ein falsches Script beim Erstellen der WV für diesen SPS übergeben:

![Bildschirmfoto 2021-03-03 um 11 32 19](https://user-images.githubusercontent.com/3273572/109813608-de4ea280-7c2d-11eb-892c-6d7fe35e5319.png)

Ich habe die vorhandenen Akteeinträge aus 2021 (mit diesem Fehler) sicherheitshalber korrigiert.

techn. Anm.:
Anpassungen im Script SpdProzSchr01E. -> Aufruf des Scriptes Spd02. immer, falls kein anderes Script übergeben wurde
(Achtung: Es kann zear ein Script übergeben werden, aber momentan kann dieses immer nur mit SP(1) = $pk_Spd in der WV aufgerufen werden; momentan reicht das)

Anpassung im Script:  Workflow10. -> bei Aktion "Einwilligungsgespräch positiv" -> kein Script mehr übergeben (CallingScript war bei Script )

**Comment by Toelk-A** [comment]
danke
