### ISSUE TITLE
GBMV/ Personalmodul / Supervisor / Bericht)

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#857]
Neu angelegte Mitarbeiter für laufenden Monat tauchen im Vormonat mit -1 auf. Bitte im Bericht ausblenden(bzw. NICHT nachträglich die MItarbeiter aufführen), da nun im Nachhinein für den Februar in diesem Fall sehr viele Fehlermeldungen aufopppen... Die MItarbeiter wie frau Schölzel ahben erst im MÄrz in der GTM-V begonnen, sodass ich cnith verstehe warum sie für den Februar abgebildet wird

![image](https://user-images.githubusercontent.com/22314271/109818255-160c1900-7c33-11eb-8939-64540b83e6c8.png)

**Comment by mprueter** [comment]
Das Problem war, dass bei der Erstellung der Mitarbeitertage das Anlegen der Mitarbeiter ab dem Eintrittsdatum nur erfolgte, wenn das Eintrittsdatum in der Vergangenheit lag. Lga dieses in der Zukunft wurden die Tage immer beginnend ab dem 1.1. des laufenden Jahres angelegt.

Das habe ich jetzt geändert: Die Tage werden frühestens ab dem Eintrittsdatum angelegt. 

Die für dieses Jahr zuviel angelegten Mitarbeitertage habe ich entfernt.



techn Anmerkung:
Anspassung in Script     \_OPN10a. (Z. 46 f.)


![Bildschirmfoto 2021-03-04 um 11 06 15](https://user-images.githubusercontent.com/3273572/109947510-ae5cd900-7cd9-11eb-9673-90a6a1e758d1.png)


Let(
   [
   vEintritt = _Mitarbeiter__::d_Dd_Erster_Arbeitstag;
   vStartScript = GetAsDate( $dateStart); //entweder Monatsanfang( übergeben) oder Jahresanfang
   vStart = Max( vEintritt; vStartScript)
   ];
   vStart
)

**Comment by Toelk-A** [comment]
danke
