### ISSUE TITLE
1/2 GBMV/GTMV Adressen _ Masteradresse ausblenden

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#858]
Hallo Herr Prüter,

bei den OG Transplantatabrechnungen zieht sich dir Rechnungsmaske immer die Rechnungsadresse - was richtig ist :-)

Nun haben wir 1 Einrichtung (Adressen ID 1680), mit Besonderheiten:

1) Rechnungsstelle/Verwaltung ist von eigentlicher TX Einrichtung ausgegliedert
2) 2 Verschiedene Rechnungsadressen die beide von der TX Einrichtung ausgegliedert sind.

Die Damen der dortigen Buchhaltung hätten nun gern, dass die TX Einrichtung (Also der Adressenmaster) in den Rechnungsadressen ausgeblendet wird.

Bedeutet also wie folgt:

Rechnungsadresse 1 (ID 2305): 
![image](https://user-images.githubusercontent.com/22314271/110942750-8a813f00-833a-11eb-84eb-d9afbf6bbaf1.png)

Rechnungsadresse 2 (ID 2034)

![image](https://user-images.githubusercontent.com/22314271/110942861-b997b080-833a-11eb-95d6-98d3ea859b4e.png)

Mit der jetzigen Ornella Hierarchie müssten wir die beiden Rechnungsadressen als separate Masteradressen anlegen. Dies würde ich gern umgehen. Ist es möglich einfach nur die Masterdadresse in der Rechnungsmaske NICHT anzuzeigen?

**Comment by mprueter** [comment]
Das Problem hier war das Sie einmal nur die Masteradresse und beim anderen Beispiel nur die Topadresse ausblenden wollten. Beim nächsten Kunden ist es dann irgendwas anderes...

Deswegen habe ich eine eher pragmatische Lösung gewählt:

Sie finden anstelle des Feldes "Komplette Adresse" jetzt zwei Reiter:

![Bildschirmfoto 2021-03-15 um 14 36 03](https://user-images.githubusercontent.com/3273572/111162812-c9163400-859c-11eb-9fde-bc1720fcde52.png)

Der erste Reiter "Komplette Adresse" enthält das kalkulierte Feld, dass sie schon kennen. Aufdem zweiten Reiter "abweichende Adresse?" können Sie ggf. eine von der hierachischen Formel abweichende Adresse hinterlegen.
Solange dieses Feld leer ist (zukünftig wahrscheinlich bei 99% der Datensätze), belibt alles beim Alten.

![Bildschirmfoto 2021-03-15 um 14 36 07](https://user-images.githubusercontent.com/3273572/111163080-12ff1a00-859d-11eb-9f23-70d47dca52b2.png)

Sie können dieses Feld aber auch mit einer abweichenden Anschrift versehen (Freitextfeld). Dann erscheint die Überschrift des Reiters rot...

![Bildschirmfoto 2021-03-15 um 14 36 21](https://user-images.githubusercontent.com/3273572/111163627-8e60cb80-859d-11eb-8405-060003d9c6ab.png)

...und als Adresse wird immer die von Ihnen eingetragene Adresse verwendet:

![Bildschirmfoto 2021-03-15 um 14 36 25](https://user-images.githubusercontent.com/3273572/111163821-bd773d00-859d-11eb-91d9-28c0d8aaa7d1.png)

Ich denke, das site die praktikabelste Lösung für alle Eventualitäten... ;-)

**Comment by Toelk-A** [comment]
ja das ist eine hervorragende Lösung!

Vielen Dank!
