### ISSUE TITLE
GTMV/ Blutprobentyp hinzufügen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#859]
Hallo Herr Prüter,

1) bitte neuen Blutprobentyp "Citrat" in Auswahlliste hinzufügen:
![image](https://user-images.githubusercontent.com/22314271/111135523-0f5b9b00-857d-11eb-89d3-eb89e637d667.png)

2) bitte auch entsprechend im Prozesschritt "Untersuchungsantrag" anpassen

![image](https://user-images.githubusercontent.com/22314271/111135637-2f8b5a00-857d-11eb-9670-0dccf3ec40e7.png)

Danke

**Comment by mprueter** [comment]
Wird das "Citrat" sowohl post- als auch prämortal entnommen?
Hat das eventuell Auswirkungen auf den digitalen Untersuchngsauftrag an Plauen?

**Comment by Toelk-A** [comment]
Citrat gibt es nur prämortal

### Hat das eventuell Auswirkungen auf den digitalen Untersuchngsauftrag an Plauen?
wie meinen Sie das?

**Comment by mprueter** [comment]
Ich muss nochmal prüfen, ob die Anzhal und Art der Röhrchen im digitalen UA übermittelt wird...

**Comment by mprueter** [comment]
Brauchen wir für die Änderung des Untersuchungsantrags nicht auch eine neue Versionsnummer?

**Comment by Toelk-A** [comment]
ja auch da haben Sie Recht!

**Comment by Toelk-A** [comment]
ich hab edie nue Versionsnummer erhalten, wenn der Untersuchungsantragangepasst ist, hinterlege ich diese in ornella. VG

**Comment by mprueter** [comment]
Muss die Bluthämodulution nicht auch noch angepasst werden?

![Bildschirmfoto 2021-03-17 um 10 45 05](https://user-images.githubusercontent.com/3273572/111447911-2ed5fd80-870e-11eb-89b9-abe84404abbb.png)

**Comment by mprueter** [comment]
Dafür brauchen wir dann ggf. auch eine VersionsNr für das Dokument, oder?

**Comment by mprueter** [comment]
Vom Prinzip her ist alles fertig, ich würde es aber gern noch einmal kurz mit Ihnen besprechen, bevor ich es freischalte...

**Comment by Toelk-A** [comment]
ja benötigen wir auch ;-)
bin jetzt erreichbar.

**Comment by Toelk-A** [comment]
Abstrich bitte auch hinzufügen, wie eben besprochen, danke und Sorrry

![image](https://user-images.githubusercontent.com/22314271/111459204-b164ba00-871a-11eb-80b3-728bd8011891.png)

**Comment by mprueter** [comment]
Ist jetzt alles umgesetzt und freigeschaltet:

Der neue Auswahldialog für "Neue Blutprobe":

![Bildschirmfoto 2021-03-17 um 12 35 14](https://user-images.githubusercontent.com/3273572/111461437-80d24f80-871d-11eb-939f-c866ad4a6fa8.png)


![Bildschirmfoto 2021-03-17 um 12 35 24](https://user-images.githubusercontent.com/3273572/111461456-86c83080-871d-11eb-89b0-4995abf1623a.png)


![Bildschirmfoto 2021-03-17 um 12 35 30](https://user-images.githubusercontent.com/3273572/111461474-8b8ce480-871d-11eb-92f8-15e929cccfd4.png)

Der Unteruchungsantrag (mit Abstrich):

![Bildschirmfoto 2021-03-17 um 12 21 50](https://user-images.githubusercontent.com/3273572/111461544-9cd5f100-871d-11eb-8efc-906c9e594136.png)


Und die Hämodilution:

![Bildschirmfoto 2021-03-17 um 12 28 37](https://user-images.githubusercontent.com/3273572/111461598-b0815780-871d-11eb-8e19-b8baaa8dccd1.png)


techn. Anm.:
Änderung in Scripten:
SpdBlutprobe01OptDUP.
BlutHaemoDil0102.

**Comment by Toelk-A** [comment]
super danke! Dokumentennummern ahbe ich auch angepasst
