### ISSUE TITLE
Entnahmebericht MSG Abschnitt "Angaben zur Entnahme"

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#86]
Bitte Angaben zum "Zeitpunkt der Kühlung der Präparate" einfügen Finalversion sollte folgendermaßen aussehen:

![image](https://cloud.githubusercontent.com/assets/22314271/21640101/df4a2550-d273-11e6-8fc8-0e8cb6629a62.png)

**Comment by chrbusch** [comment]
Hier steht jetzt aber nirgends "Falls bekannt"?

**Comment by chrbusch** [comment]
Das neue Format ist jetzt umgesetzt
