### ISSUE TITLE
Lager und Mandanten

### ISSUE THREAD

**Issue by mprueter** [chrbusch/GTM-V#862]
![Bildschirmfoto 2021-03-16 um 14 28 07](https://user-images.githubusercontent.com/3273572/111316989-04c80100-8664-11eb-9ab3-85987635fed1.png)

Dort finden Sie jetzt die Spalte Mandant:

![Bildschirmfoto 2021-03-16 um 14 27 57](https://user-images.githubusercontent.com/3273572/111317131-25905680-8664-11eb-9221-0a791b7be2b0.png)

Hier können Sie den Mandanten eines Lagers zuordnen (und ich das bei der Auswahl berücksichtigen).

**Comment by Toelk-A** [comment]
erledigt
