### ISSUE TITLE
GTMV/ offeneMSG Abrechnung einer freien Rechnung zuordnen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#864]
Hallo Herr Prüter,

Folgende MSG Abrechnung muss einer freie Rechnung zugeordnet werden, damit die Spende als "bezahlt" markiert sind.

Danke

MSG Spende:

![image](https://user-images.githubusercontent.com/22314271/111471125-d9f3b080-8728-11eb-8e1c-14f9f2325be5.png)

Bitte Rechnungsnummer: 2021-3519 zuordnen und somit als "bezahlt" markieren. Danke

![image](https://user-images.githubusercontent.com/22314271/111473490-62735080-872b-11eb-9bcb-479e1bd0e03a.png)

**Comment by mprueter** [comment]
Ist erledigt:

![Bildschirmfoto 2021-03-18 um 09 10 04](https://user-images.githubusercontent.com/3273572/111593023-ca787400-87c9-11eb-92f7-0dd7be9a5a3e.png)

**Comment by Toelk-A** [comment]
Danke!
