### ISSUE TITLE
GTMV/ Prozesschritt Checkliste

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#867]
Nach Öffnen des Prozesschrittes Checkliste Spenderakte
![image](https://user-images.githubusercontent.com/22314271/111794858-f4639080-88c6-11eb-9b6c-e0dd6b1e2de8.png)
 kommt folgende Meldung

![image](https://user-images.githubusercontent.com/22314271/111794788-df86fd00-88c6-11eb-957c-bcea34404ca3.png)

Können Sie diese ausblenden?
Danke

**Comment by mprueter** [comment]
...ist abgeschaltet.
