### ISSUE TITLE
Alle Entnahmeberichte 

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#87]
Bitte paarig (beideseits) entnommene Gewebe im Entnahmebericht mit S (links) und D (rechts) aufschlüsseln

101216-1148-GNO-TOA

![image](https://cloud.githubusercontent.com/assets/22314271/21640244/df59f8c6-d274-11e6-95ab-00f05ba0faf3.png)

**Comment by Toelk-A** [comment]
funktioniert immer noch nicht

![image](https://cloud.githubusercontent.com/assets/22314271/21719231/e078d64c-d41c-11e6-80b5-f337d85ed8dd.png)

**Comment by chrbusch** [comment]
Bitte zusammen mit Dr. Nitschke hierzu anrufen; wir haben bei bilateral entnommenen Präparaten bislang nur EINEN Datensatz; zwei werden es erst bei den Transplantaten.
Ich habe dies nun durch eine Textformel gelöst, bitte kritisch ansehen!

**Comment by Toelk-A** [comment]
ist denke ich erledigt
