### ISSUE TITLE
GTMV/ Dokumentation Laborparameter Plauen versus Rostock

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#874]
Hallo Herr Prüter,

ich möchte bitte eine Maske in der ich die Parameter für Plauen und die Parameter für Rostock dokumentieren kann. Der zeit haben wir 1 Eingabemaske wo ich aber nicht sagen kann, zu welchem Labor das Kürzel denn nun eigentlich gehört.

Beispiel

![image](https://user-images.githubusercontent.com/22314271/114175640-741ad300-993a-11eb-89e0-3085f65df560.png)
![image](https://user-images.githubusercontent.com/22314271/114175695-8b59c080-993a-11eb-8bfa-bd0cc6bb4128.png)

Gehört dieser Parameter zum Rostocker Labor oder nach Plauen? Wie läuft die Zuordnung

Ich muss hier neue Parameter anlegen können.

gehe ich nun zu

![image](https://user-images.githubusercontent.com/22314271/114175797-af1d0680-993a-11eb-89aa-ec8a67c54dcb.png)

wird zwischen Plauen dun Rostock unterschieden
![image](https://user-images.githubusercontent.com/22314271/114175872-c3f99a00-993a-11eb-8f78-41dd1ccde200.png)

aber ich finde den oben gezeigten Parameter nicht in Plauen....

**Comment by mprueter** [comment]
Ich habe das jetz alles etwas vereinfacht:
Sie finden auf der BasisParameterTabelle einen Button "Neuer Parameter" mit dem Sie grundsätzlich einen neuen Paramter anlegen können.

Daneben gibt es jetzt 2 Spalten mit den Parametern für Plauen und Rostock. Sie können also, wenn Sie möchten einen Parameter für beide Labore nutzen. Sie müssen nur den enstprechenden Code in der richtigen Spalte eingeben.

Außerdem findne Sie zwei Suchbuttons, um alle OParameter der jeweiligen Labore anzuzeigen:

![Bildschirmfoto 2021-05-17 um 13 11 37](https://user-images.githubusercontent.com/3273572/118480184-33209600-b712-11eb-8ccf-5b39f5a4f29f.png)

WICHTIG: Ein Löschbutton ist ganz bewusst nicht eingebaut. Löschen sollten Sie bitte ncht ohne Rücksprache mit mir!
![Bildschirmfoto 2021-05-17 um 13 11 37](https://user-images.githubusercontent.com/3273572/118480184-33209600-b712-11eb-8ccf-5b39f5a4f29f.png)

**Comment by Toelk-A** [comment]
super danke für die anwenderfreundliche Lösung
