### ISSUE TITLE
GBMV/ Adressen ID 2330 - Transplantatabrechnung

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#876]
Wenn Transplantatempfänger Adressen ID 2330, dann

### 1) -> keine "A Rechnung" (Absender GTM-V) erstellen, sondern direkt B Rechnung (Absender GBMV) an transplantierende Einrichtung
(dies ist bereits bei Adressen ID 2080 programmiert)

### 2) Englische Rechnungsmaske
Für ausländische TX Einrichtungen soll englische Rechnungsmaske erstellt werden ( Vorlage wird nachgereicht)

### 3) Rechnungstext pro ausländischer Rechnungsadresse
Da EU und NICHT-EU Länder unterschiedliches Steuerrecht vollziehen benötigen wir zukünftig "Rechnungstextvorlagen" pro ausländischer Rechnungsadresse. Vielleicht kann man direkt bei den Adressdetails einen Button programmieren "ausländische TX Einrichtung ja/nein -> Rechnungstextvorlage bei Adresse hinterlegen?

**Comment by mprueter** [comment]
Zu 1.:
Alles was Sie dafür tun müssen, ist diese Flag setzen:

![Bildschirmfoto 2021-04-14 um 14 36 07](https://user-images.githubusercontent.com/3273572/114711101-da369a00-9d2e-11eb-8790-a43c6155d337.png)

Ist jetzt schon erledigt...

**Comment by mprueter** [comment]
zu 2. + 3.

Wir arbeiten auch jetzt schon mit Textbausteinen für den Vor- und Nachtext, wenn auch nur sehr rudimentär. Das kann man noch gut ausbauen, in dem man die eine automatische Auswahl entsprechender Textbausteine an eine Flag in der Adresse knüpft oder noch besser: man verküpft einen Textbaustein mit der Adresse... 

Sofern das englische Layout ähnlich schlicht ist, wie das bisherige, würde ich eine Lösung über Formelfelder auf dem Layout bevorzugen.

**Comment by Toelk-A** [comment]
bitte programmierung stopppen.... ich melde mich heirzu nochmal

**Comment by mprueter** [comment]
...ich habe noch nicht angefangen. Wollte nur meine Überlegungen festhalten. :-)

**Comment by Toelk-A** [comment]
Bitte nur Punkt 1 bearbeiten, Rest seitens GBM_V GF storniert.

**Comment by mprueter** [comment]
okay, Punkt 1 ist ja schon fertig (s.o.)

**Comment by Toelk-A** [comment]
danke :-)
