### ISSUE TITLE
GTMV/ Dokumentenportal - Eingabefenster zu klein

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#877]
Spender ID
Dokument HAusarzt 15279

![image](https://user-images.githubusercontent.com/22314271/114553069-8a3fd080-9c65-11eb-883c-f0614f54792d.png)

**Comment by Toelk-A** [comment]
mir ist aufgefallen:
fährt man mit der MAus über die 2 und 3. Zeile öffnet sich ein Popover und man kann den Text lesen. In der ersten Zeile funktioniert dies nicht.

**Comment by mprueter** [comment]
Grundsätzlich können Sie in jeder Zeile auf das Textfeld klicken und es öffnet sich dann ein Popover mit dem gesamten Inhalt:

![Bildschirmfoto 2021-04-14 um 14 13 34](https://user-images.githubusercontent.com/3273572/114708687-f6850780-9d2b-11eb-8aaf-33f2c5ce9b73.png)

...ich kann auch die Zeilenhöhe etwas erhöhen, allerdings sehen Sie dann u.U. manche Einträge nur, wenn Sei im Portal scrollen. (und ich kann so max. eine oder zwei zeilen mehr herausholen; aber eben für den Preis, dass Sie ein oder zwei Einträge weniger direkt sehn können)

**Comment by Toelk-A** [comment]
Zeile 1 funktioniert leider immer noch nicht :-(

![Uploading image.png…]()

**Comment by mprueter** [comment]
Es muss sich hierbei um ein Windows-Problem handeln... auf dem MAc ist alles problmelos bei allen Zeilen darstellbar.
Nach Tests mit Frau Tölk hat sich die Implemtierung eines kleinen Buttons im Feld als parktikabel und "windowssicher" herausgestellt:

![Bildschirmfoto 2021-05-17 um 13 59 59](https://user-images.githubusercontent.com/3273572/118485229-74b43f80-b718-11eb-91b9-b2c3d1352d38.png)

techn. Anm.: der eigetlich auf dem teextfeld liegende unsichtbare Popoverbutton wurde entfernt.

**Comment by Toelk-A** [comment]
erledigt
