### ISSUE TITLE
GTMV/ Hämodilution Datum Unterschrift entspricht nicht mehr dem Entnahmedatum

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#878]
Hallo Herr Prüter,

uns ist aufgefallen, dass beim Setzen der Unterschrift Hämodiltuion nicht mehr automatisch das Entnahmedatum gezogen wird.
Können Sie dies bitte einmal prüfen?

Danke

![image](https://user-images.githubusercontent.com/22314271/114704517-fb938800-9d26-11eb-94b2-616c6706f7bf.png)

![image](https://user-images.githubusercontent.com/22314271/114704571-0bab6780-9d27-11eb-8e47-c4f9182a8c4c.png)

**Comment by mprueter** [comment]
Nach Rücksprache mit Frau Tölk: Kein Programmierfehler. Datum bei BlutHäm. wird aus der Freigabe der GewebeEntn. gezogen. Bei obigen Beispeil war das dortige Datum offenbar falsch gesetzt (-> vor Entn.)

**Comment by Toelk-A** [comment]
alles geklärt, kein Programmier- sondern Anwenderfehler ;-)
