### ISSUE TITLE
GBMV/ Artikeldetails  x-fach angewendet

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#879]
Hallo herr Prüter,

ich benötige bitte den Zugang zur Werteliste "X-fach angewendet" bei den Artikeldetails, da ich eine neue Zahl einfügen muss.

Danke

![image](https://user-images.githubusercontent.com/22314271/114854570-3eb43080-9de5-11eb-9614-718fdf714b7e.png)

**Comment by mprueter** [comment]
Sie können die WL jetzt ändern:

![Bildschirmfoto 2021-04-15 um 12 29 00](https://user-images.githubusercontent.com/3273572/114855453-46c0a000-9de6-11eb-8402-e958a15a6907.png)

**Comment by Toelk-A** [comment]
erledigt! Klappt super mit dem "Edit"!!!!!!
