### ISSUE TITLE
Entnahmebericht KVG

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#88]
Bitte Fenster "Ablehnungsgrund Herz für Tx" hinzufügen (Seite 2 Entnahmebericht)

![image](https://cloud.githubusercontent.com/assets/22314271/21640902/839753e0-d278-11e6-81e3-0509f324a834.png)

**Comment by chrbusch** [comment]
Hierzu bitte anrufen!
cbu
