### ISSUE TITLE
GBMV/ Hieroglyphen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#880]
Bei Steffi (WIS) ist das mit den „Hieroglyphen“ wieder aufgetreten. Diesmal schlimmer als vorher, da auch das gesamte Eingangsprotokoll in seltsamen Schriftzeichen dargestellt war und sie auch nicht in Klarschrift schreiben konnte.
Ein Beenden von FileMaker und auch ein ordentliches Abmelden und wieder Anmelden des Remotes haben nicht funktioniert. (Aussage WIS)
So lässt es sich natürlich nicht unbedingt arbeiten.

Vielleicht kann Herr Prüter sich mal bei Steffi direkt melden? Ich bin diese Woche leider im zu Hause am Arbeiten und kann nicht direkt helfen.

**Comment by mprueter** [comment]
Aus dem FMM-Forum:

> "LÖSUNG:
> Auf dem Client-Rechner, löschen Sie den Font-Cache C: \ Windows \ System32 \ FNTCACHE.DAT und die Maschine neu zu starten."


...und

>WORKAROUNDS:
>Update to the latest version of Adobe Reader.
>Delete the Windows font cache at C:\Windows\System32\FNTCACHE.DAT and restart the machine.
>Disable Windows Font Cache Service from Control Panel\All Control Panel Items\Administrative Tools\Services
>Delete the Adobe cache inside C:\Users\<username>\AppData\Local\Temp\acrord32_sbx\
>Use a zoom level other than 100%.

>Jedenfalls nach letztem Schritt den PC komplett neu starten.
