### ISSUE TITLE
GTMV/ Automatisiertes Einlesen Spendermeldungen KMG Güstrow

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#881]
Hallo Herr Prüter,

wir haben wieder eine neue Kooperationsklinik: KMG Güstrow. Wie auch bei den Meldenden Einrichtungen Ruppiner Kliniken und Helene von Bülow (Ludwigslust und Hagenow) sollen die Meldungen automatisch in Ornella eingelesen werden.

### 1) Umbenennung Filename
[721010556.txt](https://github.com/chrbusch/GTM-V/files/6341730/721010556.txt)

Derzeit sehen die Dateien wie o.g. aus. Ich hab heute an Herrn Flader (IT KG Güstrow) um die Umbenennung der File wie folgt gebeten:

Dateibezeichnung Verstorbenenmeldung 

Das KMG Klinikum Güstrow hat bei der GTM-V die Adressen-ID 356. Bitte die Dateien in der Artbenennen:"SpdMldg356...TXT" Wenn hinter der fixen 356 noch die FallNr des KMG Klinikums Güstrow in den Dateinamen eingebracht werden kann wäre das sehr gut -und perfekt wäre, wenn dahinter der Absendezeitstempel käme. Der Dateiname wäre dann:"SpdMldg356_12345678_20190509052512.TXT" 

### 2) Eingang Spendereldungen Server GTM-V

Informationen seitens Stephan Peter ausstehend - den Kontakt kennen Sie ja bereits

### 3) Automatisertes Einlesen in Ornella (Spenderdetails)

![image](https://user-images.githubusercontent.com/22314271/115360831-4a766d00-a1c0-11eb-9c93-b25cf8c416f1.png)

1 - Fallnummer
![image](https://user-images.githubusercontent.com/22314271/115361023-785bb180-a1c0-11eb-871c-109ec6ec59b6.png)

2 und 3 (HKTS Datum Uhrzeit)
![image](https://user-images.githubusercontent.com/22314271/115361157-96c1ad00-a1c0-11eb-808c-6a2bc44c61de.png)

4 - Geschlecht
![image](https://user-images.githubusercontent.com/22314271/115361247-ae993100-a1c0-11eb-8d7f-0f3fe895c561.png)

5 - Geburtsdatum
![image](https://user-images.githubusercontent.com/22314271/115361303-bf49a700-a1c0-11eb-8aed-71ecd1853e09.png)

6 - Krankenhaus und Station = entspricht meldender Einrichtung
![image](https://user-images.githubusercontent.com/22314271/115361428-de483900-a1c0-11eb-90aa-d557d6d1b1b4.png)

-> Die Kürzel werden exakt wie in der TXT Datei angegeben in den Adressen hinterlegt

7 - ICD Diagnosen
![image](https://user-images.githubusercontent.com/22314271/115361754-2b2c0f80-a1c1-11eb-80fe-543dc808a5b2.png)

8- ist noch leer, müssen wir beobachten was zukünftig übertragen wird

### 4) Setzen der Spenderkennummer
-> Bitte auch hier die Programmierung von den Ruppiner Kliniken bzw. Ludwigslust / Hagenow übernehmen

![image](https://user-images.githubusercontent.com/22314271/115362035-70e8d800-a1c1-11eb-9fc1-ee0288765a13.png)

**Comment by mprueter** [comment]
Können wir die Daten auch per FTP oder SFTP irgendwo abholen? 
...nur falls es wieder etwas dauert bei Hr. Peter

**Comment by Toelk-A** [comment]
Hallo Herr Prüter, 

können wir dazu heute telefonieren?

Wann haben Sie ein Zeitfenster für mich?

Danke, 

SP

---
stephanpeter.com

Stephan Peter
Birkenweg 24
37574 Einbeck

0171 3010300
sp@stephanpeter.com

**Comment by mprueter** [comment]
Das Import-Script für die Meldungen aus Güstrow ist fertig. Ich habe es aber noch nicht aktiviert... damit wir es ggf. mit den ersten übermittelten Dateien testen können

techn. Anmerkung:
Script    \_OP5_356.Import SpdMldg Güstrow (SP=pk_DataFile¶FileName¶r2¶r3¶content)/ 280421 mpr

**Comment by Toelk-A** [comment]
einlesen funktioniert, Herr Napiwotzki ist am Zug, damit wir die Originaldateien einsehen können.
