### ISSUE TITLE
GTMV/ BUG Spenderliste

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#884]
Nach Klick auf Button "Letzte Spender"
![image](https://user-images.githubusercontent.com/22314271/118447563-3ce5d180-b6f1-11eb-8803-82f174a675ab.png)

erscheint Eingabefeld.

Datum 14.05.21 -> dann sollten alle Spende (Nach klick auf archivierte nicht archivierte)... ab de 14.05.21 bis heute angezeigt werden.

Nun werden nur noch die Spenden vom 14.05.21 angezeigt. 

Seit letzten Mittwoch ist dies so. Bitte einmal kurz die Programmierung prüfen,
danke

![image](https://user-images.githubusercontent.com/22314271/118447769-761e4180-b6f1-11eb-8ed8-7d7693aed357.png)

**Comment by mprueter** [comment]
Ich hatte vergangene Woche die Funktion für den Datumsdialog dahingehend angepasst, dass die Eingabe eines Datums immer genau diesen Tag anzeigt (ist für die GBMV bei der Herstellung extrem erleichternd). Ichwusste aber nicht, dass Sie anders mit der Funktion arbeiten. 

Bei Ihnen ist es jetzt wieder so wie gewohnt. Allerdings haben Sie jetz auch einen funktionierenden "Abbrechen"-Button:

![Bildschirmfoto 2021-05-17 um 10 18 26](https://user-images.githubusercontent.com/3273572/118455091-470bce00-b6f9-11eb-89c0-74e9a0a82f6b.png)

**Comment by Toelk-A** [comment]
Bei Ihnen ist es jetzt wieder so wie gewohnt. Allerdings haben Sie jetz auch einen funktionierenden "Abbrechen"-Button:

super danke
