### ISSUE TITLE
Untersuchungsantrag GTM-V Überschrift 

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#89]
Bitte in Überschrift Bindestrich in GTM-V einfügen und Überschrift im Rahmen "Untersuchungsantrag ..." löschen

![image](https://cloud.githubusercontent.com/assets/22314271/21642342/d9ae45a0-d281-11e6-9b35-8608b317eb18.png)

**Comment by chrbusch** [comment]
Erledigt
