### ISSUE TITLE
Gewebe und Präparate

### ISSUE THREAD

**Issue by chrbusch** [chrbusch/GTM-V#9]
In den mir vorliegenden XLS-Dateien ist hier vieles falsch oder doppelt, zB gibt es "femoralis" (m.E. richtig) und "femuralis"
Dann sind viele Sehnen doppelt in der Art mit "sin" und "sin." und "si", doppelten Leerzeichen usw.
Kann bitte jemand eine eindeutige, vollständige Liste der Gewebearten (OG, MSG, ..) und den dazu gehörenden Präparaten liefern? 

Dabei sollte auch vereinheitlicht werden, ob es "li", "li." oder "links" heissen soll
Oder ist dieser Vorschlag sinnvoll:
Bei der Definition der Präparate gibt es ein Ankreuzfeld "Re/Li vorhanden?"
Wir kreuzen es an zB bei Bulbus, nicht aber z.B. bei Amnion.

Wir nun ein Präparat entnommen, erfolgt bei der Erfassung, WENN dies Feld angekreuzt ist, ein Dialog. "Was wird entnommen?" mit der Auswahl "Links, rechts, beidseits"

**Comment by Nitschke-FP** [comment]
Bei der Definition der Präparate gibt es ein Ankreuzfeld "Re/Li vorhanden?"
Wir kreuzen es an zB bei Bulbus, nicht aber z.B. bei Amnion.

Wir nun ein Präparat entnommen, erfolgt bei der Erfassung, WENN dies Feld angekreuzt ist, ein Dialog. "Was wird entnommen?" mit der Auswahl "Links, rechts, beidseitig" -Perfekt!!!!!

Tabelle zu den Präparaten kommt bis heute Mittag

**Comment by Nitschke-FP** [comment]
Bitte Frau Anita Tölk (anita.toelk@gtm-v.de)in diese Unterhaltungen mit einladen.
