### ISSUE TITLE
!!WICHTIG!!  Zweithöchste Priorität Emailverkehr !!WICHTIG!!

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#90]
Wir stellen uns folgenden Mailverkehr vor:

1)	Koordinator schließt Spendermeldung ab -> Mail an Ärzte **(funktioniert)**

2)	Freigabe zum Einwilligungsgespräch (Wiedervorlage) Ärzte -> Koordinator 
a.	Mail an Koordinator **(funktioniert nicht)**
b.	Wenn „Button“ der Ärzte bereits angeklickt wurde, soll dieser verschwinden, da sonst das ärztliche Personal nicht weiß ob die „Freigabe zum Einwilligungsgespräch“ bereits stattgefunden hat und immer wieder neue Einwilligungsgespräche angelegt werden (Bild) 

![image](https://cloud.githubusercontent.com/assets/22314271/21644234/cedb71e2-d28c-11e6-83be-47c5347d3302.png)

3)	Zustimmung bei Einwilligungsgespräch: Info Mail (keine WV) **(noch nicht etabliert)** an ärztliches Personal mit Inhalt:
a.	Art der Zustimmung: generelle oder eingeschränkte Zustimmung
b.	Bearbeitung medizinische Indikationsprüfung

4)	Medizinische Indikationsprrüfung durch Ärzte abgeschlossen wenn:
a.	„keine Hinweise“
b.	basierend auf aktuellem Kenntnisstand ist die Entnahme indiziert für „OG, MSG,KVG…“ Kästchen angekreuzt 
c.	sowie „Arztunterschrift“ 
DANN Mail an Koordinator mit Inhalt „keine Hinweise“ und Entnahme indiziert für folgende Gewebe …    **(noch nicht etabliert)**

**Comment by Toelk-A** [comment]
Emailverkehr funktioniert nach wie vor leider gar nicht

![image](https://cloud.githubusercontent.com/assets/22314271/21748986/0c794d6c-d594-11e6-8649-65499a9490a8.png)

**Comment by chrbusch** [comment]
Bitte bis auf weiteres NICHT auf den Arztbutton klicken, sondern mir die SpdKennNr mitteilen; ich kann das dann tun und Zeile für Zeile die Prozedur prüfen.

**Comment by chrbusch** [comment]
Ich denke, ich habe es gefunden; bitte nun doch selbst testen.

**Comment by chrbusch** [comment]
Freigabe zum Einwilligungsgespräch (Wiedervorlage) Ärzte -> Koordinator
a.	Mail an Koordinator (funktioniert nicht)

Jetzt erledigt

b.	Wenn „Button“ der Ärzte bereits angeklickt wurde, soll dieser verschwinden,
Auch erledigt

**Comment by chrbusch** [comment]
Nun auch erledigt:
3. Zustimmung bei Einwilligungsgespräch: Info Mail (keine WV) (noch nicht etabliert) an ärztliches Personal mit Inhalt:
a.	Art der Zustimmung: generelle oder eingeschränkte Zustimmung
b.	Bearbeitung medizinische Indikationsprüfung

**Comment by chrbusch** [comment]
4.Medizinische Indikationsprrüfung durch Ärzte abgeschlossen wenn:...

sollte nun auch klappen, bitte prüfen (Es muss der blaue Button geklickt werden, der nur erscheint, wenn die genannten Bedingungen erfüllt sind)
Bitte alles prüfen und ggfs. Ticket schliessen


![bildschirmfoto 2017-01-16 um 13 12 49](https://cloud.githubusercontent.com/assets/1241899/21982616/7e7ec4e6-dbed-11e6-8487-d68c390b24a5.JPG)

**Comment by Toelk-A** [comment]
Wir haben eben einen Testlauf gestartet:

Koordinator schließt Spendermeldung ab -> Mail an Ärzte **funktioniert nicht**

Testlauf gestoppt

![image](https://cloud.githubusercontent.com/assets/22314271/22017736/da8f1cb8-dcab-11e6-924e-04c75441508d.png)

**Comment by Toelk-A** [comment]
Ich revidiere mich Mailverkehr hat funktioniert wir testen 1x komplett durch dann melde ich mich noch einmal

**Comment by Toelk-A** [comment]
Test war erfolgreich. Ist es möglich den Button "Mitteilung an Koordinator" (Punkt 4.) ebenfalls zu entfernen, nachdem er gedrückt wurde?

Dieser Button darf nur anklickbar sein, wenn alle Kreuze im Bereich B für die indizierte Spenden gesetzt sind. (Achtung bei OG sind es weniger als bei KVG/MSG).

**Comment by Toelk-A** [comment]
Gestern Abend erhielt ich folgende Fehlermeldung für Spenderkennummer: 170117-1300-GNO-PET

![image](https://cloud.githubusercontent.com/assets/22314271/22061852/225ef4e8-dd77-11e6-9f97-ed624d822d72.png)

**Comment by chrbusch** [comment]
Wenn das einmalig war und ansonsten funktioniert, ist es fast sicher eine technische Störung, nicht die Programmierung.
Bitte Ticket schliessen und erst wieder eröffnen, wenn das mehrfach vorkommt

**Comment by Toelk-A** [comment]
erneute Fehlermeldung ID 1767

![image](https://cloud.githubusercontent.com/assets/22314271/22145412/8f4bcd3e-df01-11e6-9305-3f1762d169c0.png)

**Comment by Toelk-A** [comment]
Korrektur: ID = 1371

**Comment by Toelk-A** [comment]
Es gibt nach wie vor jeden tag Fehlermeldungen:

![image](https://cloud.githubusercontent.com/assets/22314271/22245786/132ac3c0-e232-11e6-8217-578087c61df2.png)

**Comment by Toelk-A** [comment]
![image](https://cloud.githubusercontent.com/assets/22314271/22245850/575f443a-e232-11e6-83e8-9abd60608f52.png)

**Comment by chrbusch** [comment]
Tritt dieses Problem auch auf, wenn Dr. Manecke Emails endet?

**Comment by chrbusch** [comment]
Die Fehlernummer 1502 bedeutet: "Connection refused by SMTP server"
Ca. jede 5. Email, die Ornella senden will, hat dieses Problem.
Ihr Emailserver "denkt" also, dass User Name oder Passwort falsch sind.
Wer ist hier technisch zuständig?
Der möge mich bitte anrufen.

**Comment by chrbusch** [comment]
Meines Erachtens zeigt die Abhängigkeit des Problems von Arbeitsplatz und Anwendern, dass dies nichts mit meinem Programm zu tun hat, sondern vermutlich (!) an den Email-Client-Einstellungen zu liegen scheint.
Ich weiss jedenfalls nicht, was ich hier tun könnte!

**Comment by Toelk-A** [comment]
Mailverkehr scheint jetzt zu funktionieren
