### ISSUE TITLE
Etikettendruck MSG und OG

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#91]
Der Etikettendruck funktioniert soweit, allerdings wäre es gut wenn auch die letzte Zeile auf Seite 1 bedruckt wird, bevor mit Seite 2 begonnen wird

![etiketten msg und og](https://cloud.githubusercontent.com/assets/22314271/21684631/c8573838-d35e-11e6-9a3f-ff56cab44c36.JPG)

**Comment by chrbusch** [comment]
Das hängt leider eher von den Fähigkeiten des Druckers ab als von der Programmierung.
Ich habe jetzt aber einmal angenommen, dass Ihr Drucker direkt bis zur Papierkante unten drucken kann; 
Evt. wird jetzt die letzte Reihe Etiketten unten angeschnitten, bitte aufmerksam beobachten.

**Comment by Toelk-A** [comment]
soeben geprüft, die letzte Etikettenzeile bleibt nach wie vor leer. 

Können wir etwas vor Ort an unserem Drucker ändern? Versucht man das Ganze in Word auszudrucken, wird bis zur letzten Etikettenzeile vollständig gedruckt.

**Comment by chrbusch** [comment]
bitte kritisch testen, ich habe die etiketten vertikal etwas gekürzt _ passen jetzt alle inhalte noch drauf??

**Comment by Toelk-A** [comment]
ab der 3. Zeile passt die Schrift  nicht mehr auf die Etiketten

**Comment by chrbusch** [comment]
Habe etwas mehr Platz geschaffen; wenn es noch passiert, bitte Foto des Ausdrucks schicken (so wie oben)

**Comment by Toelk-A** [comment]
funktioniert noch immer nicht:
ab der 4. Zeile verrutscht die Kennummer zu weit nach oben

![image](https://cloud.githubusercontent.com/assets/22314271/22247759/b38ec970-e23b-11e6-820a-57fc27a1b44e.png)
