### ISSUE TITLE
Etikettendruck MSG

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#93]
Bitte bei den ersten beiden Aufklebern "Entnahmedatum /Entnahmezeit" noch die Spenderkennummer hinzufügen. Dies ist sehr wichtig.

**Comment by chrbusch** [comment]
Ich habe das geprüft und finde keinen Fehler; bitte IMMER ein konkretes Beispiel nennen

**Comment by chrbusch** [comment]
Habe es doch gefunden, erledigt
