### ISSUE TITLE
Änderung der "Nutzerrechte" für Dr Manecke

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#94]
Bitte ändern Sie die Rechte für Dr. Manecke entsprechend den Rechten von Dr Nitschke (ärztliches Personal).

Für Dr Manecke muss es möglich sein die Spenderkennummer zu ändern.

![image](https://cloud.githubusercontent.com/assets/22314271/21760690/6312a212-d64e-11e6-9184-addcd5b021ed.png)

**Comment by Toelk-A** [comment]
Dr Manecke kann keine Spenderkennummer ändern (siehe "test" Patient"

**Comment by chrbusch** [comment]
Er müsste sich bitte neu einloggen.
Wenn es dann immer noch nicht klappt, bitte Screenshot der fehlermeldung senden

**Comment by Toelk-A** [comment]
Dr Manecke kann noch immer keine Spenderkennummer ändern:

"Aktion verboten, weil: Spenderkennummer wurde schon gesetzt"

ID 1351

**Comment by chrbusch** [comment]
Ja, aber da ist doch ein Button "Supervs: Ignor."; klickt man den, geht es weiter!
