### ISSUE TITLE
Einwilligungsgespräch benötigt ein Eingabefeld für Wiederspruchsfrist

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#96]
Bitte legen Sie ein Eingabefeld an um die wiedrspruchsfrist (Datum und Uhrzeit eingeben zu können)

![image](https://cloud.githubusercontent.com/assets/22314271/21892858/0bd5c9ba-d8d9-11e6-9e56-d55edc33cb2f.png)

**Comment by chrbusch** [comment]
Erledigt, bitte testen - auch Schriftgröße etc

![bildschirmfoto 2017-01-16 um 09 49 30](https://cloud.githubusercontent.com/assets/1241899/21976228/2507a6f6-dbd1-11e6-8cc4-29f12009d35c.JPG)

**Comment by Toelk-A** [comment]
funktioniert
