### ISSUE TITLE
AGENDA Rostock Nächstes Treffen

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#98]
- Etikettendruck MSG/OG

**Comment by chrbusch** [comment]
Wir wollen verstehen und beheben, dass die letzte Zeile auf den Bögen stets leer bleibt (leider ein bekanntes Filemaker-Problem)

**Comment by chrbusch** [comment]
Sämtliche Scanvorgänge von Barcodes technisch abklären und testen

**Comment by chrbusch** [comment]
Einbindung der "Zeitarbeits-Software" namens Extra_Planung in Ornella?
