### ISSUE TITLE
PDF erstellen in Spendermeldung funktioniert nicht

### ISSUE THREAD

**Issue by Toelk-A** [chrbusch/GTM-V#99]
folgender Fehler taucht auf

![fehler](https://cloud.githubusercontent.com/assets/22314271/22283731/281eaa78-e2e4-11e6-80c4-24be2d592f35.png)

**Comment by Toelk-A** [comment]
ID 1401

**Comment by chrbusch** [comment]
Fataler Tippfehler im Script, ist korrigiert!
